Z3: FPRef Class Reference
FPRef Class Reference
Public Member Functions
def sort (self)
def ebits (self)
def sbits (self)
def as_string (self)
def __le__ (self, other)
def __lt__ (self, other)
def __ge__ (self, other)
def __gt__ (self, other)
def __add__ (self, other)
def __radd__ (self, other)
def __sub__ (self, other)
def __rsub__ (self, other)
def __mul__ (self, other)
def __rmul__ (self, other)
def __pos__ (self)
def __neg__ (self)
def __div__ (self, other)
def __rdiv__ (self, other)
def __truediv__ (self, other)
def __rtruediv__ (self, other)
def __mod__ (self, other)
def __rmod__ (self, other)
Public Member Functions inherited from ExprRef
def as_ast (self)
def get_id (self)
def sort_kind (self)
def __eq__ (self, other)
def __hash__ (self)
def __ne__ (self, other)
def params (self)
def decl (self)
def num_args (self)
def arg (self, idx)
def children (self)
def from_string (self, s)
def serialize (self)
Public Member Functions inherited from AstRef
def __init__ (self, ast, ctx=None)
def __del__ (self)
def __deepcopy__ (self, memo={})
def __str__ (self)
def __repr__ (self)
def __nonzero__ (self)
def __bool__ (self)
def sexpr (self)
def ctx_ref (self)
def eq (self, other)
def translate (self, target)
def __copy__ (self)
def hash (self)
Public Member Functions inherited from Z3PPObject
def use_pp (self)
Additional Inherited Members
Data Fields inherited from AstRef
ast
ctx
Detailed Description
Floating-point expressions.
Definition at line 9480 of file z3py.py.
Member Function Documentation
__add__()
def __add__ (self, other)
Create the Z3 expression `self + other`.
>>> x = FP('x', FPSort(8, 24))
>>> y = FP('y', FPSort(8, 24))
>>> x + y
x + y
>>> (x + y).sort()
FPSort(8, 24)
Definition at line 9526 of file z3py.py.
     def __add__(self, other):
         """Create the Z3 expression `self + other`.
         >>> x = FP('x', FPSort(8, 24))
         >>> y = FP('y', FPSort(8, 24))
         >>> x + y
         x + y
         >>> (x + y).sort()
         FPSort(8, 24)
         """
         [a, b] = _coerce_fp_expr_list([self, other], self.ctx)
         return fpAdd(_dflt_rm(), a, b, self.ctx)
__div__()
def __div__ (self, other)
Create the Z3 expression `self / other`.
>>> x = FP('x', FPSort(8, 24))
>>> y = FP('y', FPSort(8, 24))
>>> x / y
x / y
>>> (x / y).sort()
FPSort(8, 24)
>>> 10 / y
1.25*(2**3) / y
Definition at line 9613 of file z3py.py.
     def __div__(self, other):
         """Create the Z3 expression `self / other`.
         >>> x = FP('x', FPSort(8, 24))
         >>> y = FP('y', FPSort(8, 24))
         >>> x / y
         x / y
         >>> (x / y).sort()
         FPSort(8, 24)
         >>> 10 / y
         1.25*(2**3) / y
         """
         [a, b] = _coerce_fp_expr_list([self, other], self.ctx)
         return fpDiv(_dflt_rm(), a, b, self.ctx)
Referenced by ArithRef.__truediv__(), BitVecRef.__truediv__(), and FPRef.__truediv__().
__ge__()
def __ge__ (self, other)
Definition at line 9520 of file z3py.py.
     def __ge__(self, other):
         return fpGEQ(self, other, self.ctx)
__gt__()
def __gt__ (self, other)
Definition at line 9523 of file z3py.py.
     def __gt__(self, other):
         return fpGT(self, other, self.ctx)
__le__()
def __le__ (self, other)
Definition at line 9514 of file z3py.py.
     def __le__(self, other):
         return fpLEQ(self, other, self.ctx)
__lt__()
def __lt__ (self, other)
Definition at line 9517 of file z3py.py.
     def __lt__(self, other):
         return fpLT(self, other, self.ctx)
__mod__()
def __mod__ (self, other)
Create the Z3 expression mod `self % other`.
Definition at line 9649 of file z3py.py.
     def __mod__(self, other):
         """Create the Z3 expression mod `self % other`."""
         return fpRem(self, other)
__mul__()
def __mul__ (self, other)
Create the Z3 expression `self * other`.
>>> x = FP('x', FPSort(8, 24))
>>> y = FP('y', FPSort(8, 24))
>>> x * y
x * y
>>> (x * y).sort()
FPSort(8, 24)
>>> 10 * y
1.25*(2**3) * y
Definition at line 9572 of file z3py.py.
     def __mul__(self, other):
         """Create the Z3 expression `self * other`.
         >>> x = FP('x', FPSort(8, 24))
         >>> y = FP('y', FPSort(8, 24))
         >>> x * y
         x * y
         >>> (x * y).sort()
         FPSort(8, 24)
         >>> 10 * y
         1.25*(2**3) * y
         """
         [a, b] = _coerce_fp_expr_list([self, other], self.ctx)
         return fpMul(_dflt_rm(), a, b, self.ctx)
__neg__()
def __neg__ (self)
Create the Z3 expression `-self`.
>>> x = FP('x', Float32())
>>> -x
-x
Definition at line 9604 of file z3py.py.
     def __neg__(self):
         """Create the Z3 expression `-self`.
         >>> x = FP('x', Float32())
         >>> -x
         -x
         """
         return fpNeg(self)
__pos__()
def __pos__ (self)
Create the Z3 expression `+self`.
Definition at line 9600 of file z3py.py.
     def __pos__(self):
         """Create the Z3 expression `+self`."""
         return self
__radd__()
def __radd__ (self, other)
Create the Z3 expression `other + self`.
>>> x = FP('x', FPSort(8, 24))
>>> 10 + x
1.25*(2**3) + x
Definition at line 9539 of file z3py.py.
     def __radd__(self, other):
         """Create the Z3 expression `other + self`.
         >>> x = FP('x', FPSort(8, 24))
         >>> 10 + x
         1.25*(2**3) + x
         """
         [a, b] = _coerce_fp_expr_list([other, self], self.ctx)
         return fpAdd(_dflt_rm(), a, b, self.ctx)
__rdiv__()
def __rdiv__ (self, other)
Create the Z3 expression `other / self`.
>>> x = FP('x', FPSort(8, 24))
>>> y = FP('y', FPSort(8, 24))
>>> x / y
x / y
>>> x / 10
x / 1.25*(2**3)
Definition at line 9628 of file z3py.py.
     def __rdiv__(self, other):
         """Create the Z3 expression `other / self`.
         >>> x = FP('x', FPSort(8, 24))
         >>> y = FP('y', FPSort(8, 24))
         >>> x / y
         x / y
         >>> x / 10
         x / 1.25*(2**3)
         """
         [a, b] = _coerce_fp_expr_list([other, self], self.ctx)
         return fpDiv(_dflt_rm(), a, b, self.ctx)
Referenced by ArithRef.__rtruediv__(), BitVecRef.__rtruediv__(), and FPRef.__rtruediv__().
__rmod__()
def __rmod__ (self, other)
Create the Z3 expression mod `other % self`.
Definition at line 9653 of file z3py.py.
     def __rmod__(self, other):
         """Create the Z3 expression mod `other % self`."""
         return fpRem(other, self)
__rmul__()
def __rmul__ (self, other)
Create the Z3 expression `other * self`.
>>> x = FP('x', FPSort(8, 24))
>>> y = FP('y', FPSort(8, 24))
>>> x * y
x * y
>>> x * 10
x * 1.25*(2**3)
Definition at line 9587 of file z3py.py.
     def __rmul__(self, other):
         """Create the Z3 expression `other * self`.
         >>> x = FP('x', FPSort(8, 24))
         >>> y = FP('y', FPSort(8, 24))
         >>> x * y
         x * y
         >>> x * 10
         x * 1.25*(2**3)
         """
         [a, b] = _coerce_fp_expr_list([other, self], self.ctx)
         return fpMul(_dflt_rm(), a, b, self.ctx)
__rsub__()
def __rsub__ (self, other)
Create the Z3 expression `other - self`.
>>> x = FP('x', FPSort(8, 24))
>>> 10 - x
1.25*(2**3) - x
Definition at line 9562 of file z3py.py.
     def __rsub__(self, other):
         """Create the Z3 expression `other - self`.
         >>> x = FP('x', FPSort(8, 24))
         >>> 10 - x
         1.25*(2**3) - x
         """
         [a, b] = _coerce_fp_expr_list([other, self], self.ctx)
         return fpSub(_dflt_rm(), a, b, self.ctx)
__rtruediv__()
def __rtruediv__ (self, other)
Create the Z3 expression division `other / self`.
Definition at line 9645 of file z3py.py.
     def __rtruediv__(self, other):
         """Create the Z3 expression division `other / self`."""
         return self.__rdiv__(other)
__sub__()
def __sub__ (self, other)
Create the Z3 expression `self - other`.
>>> x = FP('x', FPSort(8, 24))
>>> y = FP('y', FPSort(8, 24))
>>> x - y
x - y
>>> (x - y).sort()
FPSort(8, 24)
Definition at line 9549 of file z3py.py.
     def __sub__(self, other):
         """Create the Z3 expression `self - other`.
         >>> x = FP('x', FPSort(8, 24))
         >>> y = FP('y', FPSort(8, 24))
         >>> x - y
         x - y
         >>> (x - y).sort()
         FPSort(8, 24)
         """
         [a, b] = _coerce_fp_expr_list([self, other], self.ctx)
         return fpSub(_dflt_rm(), a, b, self.ctx)
__truediv__()
def __truediv__ (self, other)
Create the Z3 expression division `self / other`.
Definition at line 9641 of file z3py.py.
     def __truediv__(self, other):
         """Create the Z3 expression division `self / other`."""
         return self.__div__(other)
as_string()
def as_string (self)
Return a Z3 floating point expression as a Python string.
Reimplemented in FPNumRef.
Definition at line 9510 of file z3py.py.
     def as_string(self):
         """Return a Z3 floating point expression as a Python string."""
         return Z3_ast_to_string(self.ctx_ref(), self.as_ast())
Referenced by IntNumRef.as_long(), BitVecNumRef.as_long(), and FiniteDomainNumRef.as_long().
ebits()
def ebits (self)
Retrieves the number of bits reserved for the exponent in the FloatingPoint expression `self`.
>>> b = FPSort(8, 24)
>>> b.ebits()
8
Definition at line 9494 of file z3py.py.
     def ebits(self):
         """Retrieves the number of bits reserved for the exponent in the FloatingPoint expression `self`.
         >>> b = FPSort(8, 24)
         >>> b.ebits()
         8
         """
         return self.sort().ebits()
sbits()
def sbits (self)
Retrieves the number of bits reserved for the exponent in the FloatingPoint expression `self`.
>>> b = FPSort(8, 24)
>>> b.sbits()
24
Definition at line 9502 of file z3py.py.
     def sbits(self):
         """Retrieves the number of bits reserved for the exponent in the FloatingPoint expression `self`.
         >>> b = FPSort(8, 24)
         >>> b.sbits()
         24
         """
         return self.sort().sbits()
sort()
def sort (self)
Return the sort of the floating-point expression `self`.
>>> x = FP('1.0', FPSort(8, 24))
>>> x.sort()
FPSort(8, 24)
>>> x.sort() == FPSort(8, 24)
True
Reimplemented from ExprRef.
Definition at line 9483 of file z3py.py.
     def sort(self):
         """Return the sort of the floating-point expression `self`.
         >>> x = FP('1.0', FPSort(8, 24))
         >>> x.sort()
         FPSort(8, 24)
         >>> x.sort() == FPSort(8, 24)
         True
         """
         return FPSortRef(Z3_get_sort(self.ctx_ref(), self.as_ast()), self.ctx)
Referenced by FPNumRef.as_string(), ArrayRef.domain(), ArrayRef.domain_n(), FPRef.ebits(), ArithRef.is_int(), ArithRef.is_real(), ArrayRef.range(), FPRef.sbits(), BitVecRef.size(), and ExprRef.sort_kind().