Z3: FPNumRef Class Reference
FPNumRef Class Reference
Public Member Functions
def sign (self)
def sign_as_bv (self)
def significand (self)
def significand_as_long (self)
def significand_as_bv (self)
def exponent (self, biased=True)
def exponent_as_long (self, biased=True)
def exponent_as_bv (self, biased=True)
def isNaN (self)
def isInf (self)
def isZero (self)
def isNormal (self)
def isSubnormal (self)
def isPositive (self)
def isNegative (self)
def as_string (self)
Public Member Functions inherited from FPRef
def sort (self)
def ebits (self)
def sbits (self)
def __le__ (self, other)
def __lt__ (self, other)
def __ge__ (self, other)
def __gt__ (self, other)
def __add__ (self, other)
def __radd__ (self, other)
def __sub__ (self, other)
def __rsub__ (self, other)
def __mul__ (self, other)
def __rmul__ (self, other)
def __pos__ (self)
def __neg__ (self)
def __div__ (self, other)
def __rdiv__ (self, other)
def __truediv__ (self, other)
def __rtruediv__ (self, other)
def __mod__ (self, other)
def __rmod__ (self, other)
Public Member Functions inherited from ExprRef
def as_ast (self)
def get_id (self)
def sort_kind (self)
def __eq__ (self, other)
def __hash__ (self)
def __ne__ (self, other)
def params (self)
def decl (self)
def num_args (self)
def arg (self, idx)
def children (self)
def from_string (self, s)
def serialize (self)
Public Member Functions inherited from AstRef
def __init__ (self, ast, ctx=None)
def __del__ (self)
def __deepcopy__ (self, memo={})
def __str__ (self)
def __repr__ (self)
def __nonzero__ (self)
def __bool__ (self)
def sexpr (self)
def ctx_ref (self)
def eq (self, other)
def translate (self, target)
def __copy__ (self)
def hash (self)
Public Member Functions inherited from Z3PPObject
def use_pp (self)
Additional Inherited Members
Data Fields inherited from AstRef
ast
ctx
Detailed Description
The sign of the numeral.
>>> x = FPVal(+1.0, FPSort(8, 24))
>>> x.sign()
False
>>> x = FPVal(-1.0, FPSort(8, 24))
>>> x.sign()
True
Definition at line 9736 of file z3py.py.
Member Function Documentation
as_string()
def as_string (self)
Return a Z3 floating point expression as a Python string.
Reimplemented from FPRef.
Definition at line 9867 of file z3py.py.
     def as_string(self):
         s = Z3_get_numeral_string(self.ctx.ref(), self.as_ast())
         return ("FPVal(%s, %s)" % (s, self.sort()))
Referenced by IntNumRef.as_long(), BitVecNumRef.as_long(), and FiniteDomainNumRef.as_long().
exponent()
def exponent (self, biased = True)
Definition at line 9800 of file z3py.py.
     def exponent(self, biased=True):
         return Z3_fpa_get_numeral_exponent_string(self.ctx.ref(), self.as_ast(), biased)
exponent_as_bv()
def exponent_as_bv (self, biased = True)
Definition at line 9821 of file z3py.py.
     def exponent_as_bv(self, biased=True):
         return BitVecNumRef(Z3_fpa_get_numeral_exponent_bv(self.ctx.ref(), self.as_ast(), biased), self.ctx)
exponent_as_long()
def exponent_as_long (self, biased = True)
Definition at line 9810 of file z3py.py.
     def exponent_as_long(self, biased=True):
         ptr = (ctypes.c_longlong * 1)()
         if not Z3_fpa_get_numeral_exponent_int64(self.ctx.ref(), self.as_ast(), ptr, biased):
             raise Z3Exception("error retrieving the exponent of a numeral.")
         return ptr[0]
isInf()
def isInf (self)
Definition at line 9831 of file z3py.py.
     def isInf(self):
         return Z3_fpa_is_numeral_inf(self.ctx.ref(), self.as_ast())
isNaN()
def isNaN (self)
Definition at line 9826 of file z3py.py.
     def isNaN(self):
         return Z3_fpa_is_numeral_nan(self.ctx.ref(), self.as_ast())
isNegative()
def isNegative (self)
Definition at line 9856 of file z3py.py.
     def isNegative(self):
         return Z3_fpa_is_numeral_negative(self.ctx.ref(), self.as_ast())
isNormal()
def isNormal (self)
Definition at line 9841 of file z3py.py.
     def isNormal(self):
         return Z3_fpa_is_numeral_normal(self.ctx.ref(), self.as_ast())
isPositive()
def isPositive (self)
Definition at line 9851 of file z3py.py.
     def isPositive(self):
         return Z3_fpa_is_numeral_positive(self.ctx.ref(), self.as_ast())
isSubnormal()
def isSubnormal (self)
Definition at line 9846 of file z3py.py.
     def isSubnormal(self):
         return Z3_fpa_is_numeral_subnormal(self.ctx.ref(), self.as_ast())
isZero()
def isZero (self)
Definition at line 9836 of file z3py.py.
     def isZero(self):
         return Z3_fpa_is_numeral_zero(self.ctx.ref(), self.as_ast())
sign()
def sign (self)
Definition at line 9747 of file z3py.py.
     def sign(self):
         num = (ctypes.c_int)()
         nsign = Z3_fpa_get_numeral_sign(self.ctx.ref(), self.as_ast(), byref(num))
         if nsign is False:
             raise Z3Exception("error retrieving the sign of a numeral.")
         return num.value != 0
sign_as_bv()
def sign_as_bv (self)
Definition at line 9759 of file z3py.py.
     def sign_as_bv(self):
         return BitVecNumRef(Z3_fpa_get_numeral_sign_bv(self.ctx.ref(), self.as_ast()), self.ctx)
significand()
def significand (self)
Definition at line 9769 of file z3py.py.
     def significand(self):
         return Z3_fpa_get_numeral_significand_string(self.ctx.ref(), self.as_ast())
significand_as_bv()
def significand_as_bv (self)
Definition at line 9790 of file z3py.py.
     def significand_as_bv(self):
         return BitVecNumRef(Z3_fpa_get_numeral_significand_bv(self.ctx.ref(), self.as_ast()), self.ctx)
significand_as_long()
def significand_as_long (self)
Definition at line 9779 of file z3py.py.
     def significand_as_long(self):
         ptr = (ctypes.c_ulonglong * 1)()
         if not Z3_fpa_get_numeral_significand_uint64(self.ctx.ref(), self.as_ast(), ptr):
             raise Z3Exception("error retrieving the significand of a numeral.")
         return ptr[0]