Z3: simplifier Class Reference
simplifier Class Reference
Public Member Functions
simplifier (context &c, char const *name)
simplifier (context &c, Z3_simplifier s)
simplifier (simplifier const &s)
~simplifier () override
operator Z3_simplifier () const
simplifier & operator= (simplifier const &s)
std::string help () const
param_descrs get_param_descrs ()
Public Member Functions inherited from object
object (context &c)
virtual ~object ()=default
context & ctx () const
Z3_error_code check_error () const
Friends
simplifier operator& (simplifier const &t1, simplifier const &t2)
simplifier with (simplifier const &t, params const &p)
Additional Inherited Members
Protected Attributes inherited from object
context * m_ctx
Detailed Description
Definition at line 3169 of file z3++.h.
Constructor & Destructor Documentation
simplifier() [1/3]
simplifier (context & c, char const * name) inline
Definition at line 3176 of file z3++.h.
 :object(c) { Z3_simplifier r = Z3_mk_simplifier(c, name); check_error(); init(r); }
Referenced by Simplifier::__deepcopy__(), Simplifier::__del__(), Simplifier::add(), Simplifier::help(), Simplifier::param_descrs(), and Simplifier::using_params().
simplifier() [2/3]
simplifier (context & c, Z3_simplifier s) inline
Definition at line 3177 of file z3++.h.
 :object(c) { init(s); }
Referenced by Simplifier::__deepcopy__(), Simplifier::__del__(), Simplifier::add(), Simplifier::help(), Simplifier::param_descrs(), and Simplifier::using_params().
simplifier() [3/3]
simplifier (simplifier const & s) inline
Definition at line 3178 of file z3++.h.
 :object(s) { init(s.m_simplifier); }
Referenced by Simplifier::__deepcopy__(), Simplifier::__del__(), Simplifier::add(), Simplifier::help(), Simplifier::param_descrs(), and Simplifier::using_params().
~simplifier()
~simplifier () inline override
Definition at line 3179 of file z3++.h.
 { Z3_simplifier_dec_ref(ctx(), m_simplifier); }
Member Function Documentation
get_param_descrs()
param_descrs get_param_descrs () inline
Definition at line 3191 of file z3++.h.
 { return param_descrs(ctx(), Z3_simplifier_get_param_descrs(ctx(), m_simplifier)); }
help()
std::string help () const inline
Definition at line 3188 of file z3++.h.
 { char const * r = Z3_simplifier_get_help(ctx(), m_simplifier); check_error();  return r; }
operator Z3_simplifier()
operator Z3_simplifier () const inline
Definition at line 3180 of file z3++.h.
 { return m_simplifier; }
operator=()
simplifier& operator= (simplifier const & s) inline
Definition at line 3181 of file z3++.h.
{
             Z3_simplifier_inc_ref(s.ctx(), s.m_simplifier);
             Z3_simplifier_dec_ref(ctx(), m_simplifier);
             object::operator=(s);
             m_simplifier = s.m_simplifier;
             return *this;
         }
Friends And Related Function Documentation
operator&
simplifier operator& (simplifier const & t1, simplifier const & t2) friend
Definition at line 3197 of file z3++.h.
{
         check_context(t1, t2);
         Z3_simplifier r = Z3_simplifier_and_then(t1.ctx(), t1, t2);
         t1.check_error();
         return simplifier(t1.ctx(), r);
     }
with
simplifier with (simplifier const & t, params const & p) friend
Definition at line 3204 of file z3++.h.
{
         Z3_simplifier r = Z3_simplifier_using_params(t.ctx(), t, p);
         t.check_error();
         return simplifier(t.ctx(), r);
     }