Z3: ExprRef Class Reference
ExprRef Class Reference
Expressions.
Public Member Functions
def as_ast (self)
def get_id (self)
def sort (self)
def sort_kind (self)
def __eq__ (self, other)
def __hash__ (self)
def __ne__ (self, other)
def params (self)
def decl (self)
def num_args (self)
def arg (self, idx)
def children (self)
def from_string (self, s)
def serialize (self)
Public Member Functions inherited from AstRef
def __init__ (self, ast, ctx=None)
def __del__ (self)
def __deepcopy__ (self, memo={})
def __str__ (self)
def __repr__ (self)
def __nonzero__ (self)
def __bool__ (self)
def sexpr (self)
def ctx_ref (self)
def eq (self, other)
def translate (self, target)
def __copy__ (self)
def hash (self)
Public Member Functions inherited from Z3PPObject
def use_pp (self)
Additional Inherited Members
Data Fields inherited from AstRef
ast
ctx
Detailed Description
Expressions.
Constraints, formulas and terms are expressions in Z3.
Expressions are ASTs. Every expression has a sort.
There are three main kinds of expressions:
function applications, quantifiers and bounded variables.
A constant is a function application with 0 arguments.
For quantifier free problems, all expressions are
function applications.
Definition at line 979 of file z3py.py.
Member Function Documentation
__eq__()
def __eq__ (self, other)
Return a Z3 expression that represents the constraint `self == other`.
If `other` is `None`, then this method simply returns `False`.
>>> a = Int('a')
>>> b = Int('b')
>>> a == b
a == b
>>> a is None
False
Reimplemented from AstRef.
Definition at line 1019 of file z3py.py.
     def __eq__(self, other):
         """Return a Z3 expression that represents the constraint `self == other`.
         If `other` is `None`, then this method simply returns `False`.
         >>> a = Int('a')
         >>> b = Int('b')
         >>> a == b
         a == b
         >>> a is None
         False
         """
         if other is None:
             return False
         a, b = _coerce_exprs(self, other)
         return BoolRef(Z3_mk_eq(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
Referenced by CheckSatResult.__ne__(), and Probe.__ne__().
__hash__()
def __hash__ (self)
 Hash code.
Reimplemented from AstRef.
Definition at line 1036 of file z3py.py.
     def __hash__(self):
         """ Hash code. """
         return AstRef.__hash__(self)
__ne__()
def __ne__ (self, other)
Return a Z3 expression that represents the constraint `self != other`.
If `other` is `None`, then this method simply returns `True`.
>>> a = Int('a')
>>> b = Int('b')
>>> a != b
a != b
>>> a is not None
True
Definition at line 1040 of file z3py.py.
     def __ne__(self, other):
         """Return a Z3 expression that represents the constraint `self != other`.
         If `other` is `None`, then this method simply returns `True`.
         >>> a = Int('a')
         >>> b = Int('b')
         >>> a != b
         a != b
         >>> a is not None
         True
         """
         if other is None:
             return True
         a, b = _coerce_exprs(self, other)
         _args, sz = _to_ast_array((a, b))
         return BoolRef(Z3_mk_distinct(self.ctx_ref(), 2, _args), self.ctx)
arg()
def arg (self, idx)
Return argument `idx` of the application `self`.
This method assumes that `self` is a function application with at least `idx+1` arguments.
>>> a = Int('a')
>>> b = Int('b')
>>> f = Function('f', IntSort(), IntSort(), IntSort(), IntSort())
>>> t = f(a, b, 0)
>>> t.arg(0)
a
>>> t.arg(1)
b
>>> t.arg(2)
0
Definition at line 1092 of file z3py.py.
     def arg(self, idx):
         """Return argument `idx` of the application `self`.
         This method assumes that `self` is a function application with at least `idx+1` arguments.
         >>> a = Int('a')
         >>> b = Int('b')
         >>> f = Function('f', IntSort(), IntSort(), IntSort(), IntSort())
         >>> t = f(a, b, 0)
         >>> t.arg(0)
         a
         >>> t.arg(1)
         b
         >>> t.arg(2)
         0
         """
         if z3_debug():
             _z3_assert(is_app(self), "Z3 application expected")
             _z3_assert(idx < self.num_args(), "Invalid argument index")
         return _to_expr_ref(Z3_get_app_arg(self.ctx_ref(), self.as_ast(), idx), self.ctx)
Referenced by AstRef.__bool__(), and ExprRef.children().
as_ast()
def as_ast (self)
Return a pointer to the corresponding C Z3_ast object.
Reimplemented from AstRef.
Reimplemented in QuantifierRef, and PatternRef.
Definition at line 990 of file z3py.py.
     def as_ast(self):
         return self.ast
Referenced by AstRef.__del__(), SeqRef.__ge__(), SeqRef.__getitem__(), SeqRef.__gt__(), BitVecRef.__invert__(), SeqRef.__le__(), CharRef.__le__(), SeqRef.__lt__(), ArithRef.__neg__(), BitVecRef.__neg__(), AlgebraicNumRef.approx(), ExprRef.arg(), IntNumRef.as_binary_string(), BitVecNumRef.as_binary_string(), RatNumRef.as_decimal(), AlgebraicNumRef.as_decimal(), IntNumRef.as_string(), RatNumRef.as_string(), BitVecNumRef.as_string(), FiniteDomainRef.as_string(), FiniteDomainNumRef.as_string(), FPRef.as_string(), FPRMRef.as_string(), FPNumRef.as_string(), SeqRef.as_string(), SeqRef.at(), ExprRef.decl(), ArrayRef.default(), RatNumRef.denominator(), AstRef.eq(), FPNumRef.exponent(), FPNumRef.exponent_as_bv(), FPNumRef.exponent_as_long(), AstRef.get_id(), SortRef.get_id(), FuncDeclRef.get_id(), ExprRef.get_id(), PatternRef.get_id(), QuantifierRef.get_id(), AstRef.hash(), AlgebraicNumRef.index(), CharRef.is_digit(), SeqRef.is_string(), SeqRef.is_string_value(), FPNumRef.isInf(), FPNumRef.isNaN(), FPNumRef.isNegative(), FPNumRef.isNormal(), FPNumRef.isPositive(), FPNumRef.isSubnormal(), FPNumRef.isZero(), ExprRef.num_args(), RatNumRef.numerator(), AlgebraicNumRef.poly(), AstRef.sexpr(), FPNumRef.sign(), FPNumRef.sign_as_bv(), FPNumRef.significand(), FPNumRef.significand_as_bv(), FPNumRef.significand_as_long(), ExprRef.sort(), BoolRef.sort(), QuantifierRef.sort(), ArithRef.sort(), BitVecRef.sort(), ArrayRef.sort(), DatatypeRef.sort(), FiniteDomainRef.sort(), FPRef.sort(), SeqRef.sort(), CharRef.to_bv(), CharRef.to_int(), and AstRef.translate().
children()
def children (self)
Return a list containing the children of the given expression
>>> a = Int('a')
>>> b = Int('b')
>>> f = Function('f', IntSort(), IntSort(), IntSort(), IntSort())
>>> t = f(a, b, 0)
>>> t.children()
[a, b, 0]
Reimplemented in QuantifierRef.
Definition at line 1113 of file z3py.py.
     def children(self):
         """Return a list containing the children of the given expression
         >>> a = Int('a')
         >>> b = Int('b')
         >>> f = Function('f', IntSort(), IntSort(), IntSort(), IntSort())
         >>> t = f(a, b, 0)
         >>> t.children()
         [a, b, 0]
         """
         if is_app(self):
             return [self.arg(i) for i in range(self.num_args())]
         else:
             return []
decl()
def decl (self)
Return the Z3 function declaration associated with a Z3 application.
>>> f = Function('f', IntSort(), IntSort())
>>> a = Int('a')
>>> t = f(a)
>>> eq(t.decl(), f)
True
>>> (a + 1).decl()
+
Definition at line 1061 of file z3py.py.
     def decl(self):
         """Return the Z3 function declaration associated with a Z3 application.
         >>> f = Function('f', IntSort(), IntSort())
         >>> a = Int('a')
         >>> t = f(a)
         >>> eq(t.decl(), f)
         True
         >>> (a + 1).decl()
         +
         """
         if z3_debug():
             _z3_assert(is_app(self), "Z3 application expected")
         return FuncDeclRef(Z3_get_app_decl(self.ctx_ref(), self.as_ast()), self.ctx)
Referenced by ExprRef.params().
from_string()
def from_string (self, s)
Definition at line 1128 of file z3py.py.
     def from_string(self, s):
         pass
get_id()
def get_id (self)
Return unique identifier for object. It can be used for hash-tables and maps.
Reimplemented from AstRef.
Reimplemented in QuantifierRef, and PatternRef.
Definition at line 993 of file z3py.py.
     def get_id(self):
         return Z3_get_ast_id(self.ctx_ref(), self.as_ast())
num_args()
def num_args (self)
Return the number of arguments of a Z3 application.
>>> a = Int('a')
>>> b = Int('b')
>>> (a + b).num_args()
2
>>> f = Function('f', IntSort(), IntSort(), IntSort(), IntSort())
>>> t = f(a, b, 0)
>>> t.num_args()
3
Definition at line 1076 of file z3py.py.
     def num_args(self):
         """Return the number of arguments of a Z3 application.
         >>> a = Int('a')
         >>> b = Int('b')
         >>> (a + b).num_args()
         2
         >>> f = Function('f', IntSort(), IntSort(), IntSort(), IntSort())
         >>> t = f(a, b, 0)
         >>> t.num_args()
         3
         """
         if z3_debug():
             _z3_assert(is_app(self), "Z3 application expected")
         return int(Z3_get_app_num_args(self.ctx_ref(), self.as_ast()))
Referenced by AstRef.__bool__(), ExprRef.arg(), FuncEntry.arg_value(), FuncEntry.as_list(), and ExprRef.children().
params()
def params (self)
Definition at line 1058 of file z3py.py.
     def params(self):
         return self.decl().params()
Referenced by ParamsRef.__deepcopy__(), ParamsRef.__del__(), ParamsRef.__repr__(), ParamsRef.set(), and ParamsRef.validate().
serialize()
def serialize (self)
Definition at line 1131 of file z3py.py.
     def serialize(self):
         s = Solver()
         f = Function('F', self.sort(), BoolSort(self.ctx))
         s.add(f(self))
         return s.sexpr()
sort()
def sort (self)
Return the sort of expression `self`.
>>> x = Int('x')
>>> (x + 1).sort()
Int
>>> y = Real('y')
>>> (x + y).sort()
Real
Reimplemented in SeqRef, FPRef, FiniteDomainRef, DatatypeRef, ArrayRef, BitVecRef, ArithRef, QuantifierRef, and BoolRef.
Definition at line 996 of file z3py.py.
     def sort(self):
         """Return the sort of expression `self`.
         >>> x = Int('x')
         >>> (x + 1).sort()
         Int
         >>> y = Real('y')
         >>> (x + y).sort()
         Real
         """
         return _sort(self.ctx, self.as_ast())
Referenced by FPNumRef.as_string(), ArrayRef.domain(), ArrayRef.domain_n(), FPRef.ebits(), ArithRef.is_int(), ArithRef.is_real(), ArrayRef.range(), FPRef.sbits(), BitVecRef.size(), and ExprRef.sort_kind().
sort_kind()
def sort_kind (self)
Shorthand for `self.sort().kind()`.
>>> a = Array('a', IntSort(), IntSort())
>>> a.sort_kind() == Z3_ARRAY_SORT
True
>>> a.sort_kind() == Z3_INT_SORT
False
Definition at line 1008 of file z3py.py.
     def sort_kind(self):
         """Shorthand for `self.sort().kind()`.
         >>> a = Array('a', IntSort(), IntSort())
         >>> a.sort_kind() == Z3_ARRAY_SORT
         True
         >>> a.sort_kind() == Z3_INT_SORT
         False
         """
         return self.sort().kind()