Z3: ArrayRef Class Reference
ArrayRef Class Reference
Public Member Functions
def sort (self)
def domain (self)
def domain_n (self, i)
def range (self)
def __getitem__ (self, arg)
def default (self)
Public Member Functions inherited from ExprRef
def as_ast (self)
def get_id (self)
def sort_kind (self)
def __eq__ (self, other)
def __hash__ (self)
def __ne__ (self, other)
def params (self)
def decl (self)
def num_args (self)
def arg (self, idx)
def children (self)
def from_string (self, s)
def serialize (self)
Public Member Functions inherited from AstRef
def __init__ (self, ast, ctx=None)
def __del__ (self)
def __deepcopy__ (self, memo={})
def __str__ (self)
def __repr__ (self)
def __nonzero__ (self)
def __bool__ (self)
def sexpr (self)
def ctx_ref (self)
def eq (self, other)
def translate (self, target)
def __copy__ (self)
def hash (self)
Public Member Functions inherited from Z3PPObject
def use_pp (self)
Additional Inherited Members
Data Fields inherited from AstRef
ast
ctx
Detailed Description
Array expressions.
Definition at line 4594 of file z3py.py.
Member Function Documentation
__getitem__()
def __getitem__ (self, arg)
Return the Z3 expression `self[arg]`.
>>> a = Array('a', IntSort(), BoolSort())
>>> i = Int('i')
>>> a[i]
a[i]
>>> a[i].sexpr()
'(select a i)'
Definition at line 4628 of file z3py.py.
     def __getitem__(self, arg):
         """Return the Z3 expression `self[arg]`.
         >>> a = Array('a', IntSort(), BoolSort())
         >>> i = Int('i')
         >>> a[i]
         a[i]
         >>> a[i].sexpr()
         '(select a i)'
         """
         return _array_select(self, arg)
default()
def default (self)
Definition at line 4640 of file z3py.py.
     def default(self):
         return _to_expr_ref(Z3_mk_array_default(self.ctx_ref(), self.as_ast()), self.ctx)
domain()
def domain (self)
Shorthand for `self.sort().domain()`.
>>> a = Array('a', IntSort(), BoolSort())
>>> a.domain()
Int
Definition at line 4606 of file z3py.py.
     def domain(self):
         """Shorthand for `self.sort().domain()`.
         >>> a = Array('a', IntSort(), BoolSort())
         >>> a.domain()
         Int
         """
         return self.sort().domain()
Referenced by FuncDeclRef.__call__(), and ArrayRef.default().
domain_n()
def domain_n (self, i)
Shorthand for self.sort().domain_n(i)`.
Definition at line 4615 of file z3py.py.
     def domain_n(self, i):
         """Shorthand for self.sort().domain_n(i)`."""
         return self.sort().domain_n(i)
Referenced by ArrayRef.default().
range()
def range (self)
Shorthand for `self.sort().range()`.
>>> a = Array('a', IntSort(), BoolSort())
>>> a.range()
Bool
Definition at line 4619 of file z3py.py.
     def range(self):
         """Shorthand for `self.sort().range()`.
         >>> a = Array('a', IntSort(), BoolSort())
         >>> a.range()
         Bool
         """
         return self.sort().range()
Referenced by ArrayRef.default().
sort()
def sort (self)
Return the array sort of the array expression `self`.
>>> a = Array('a', IntSort(), BoolSort())
>>> a.sort()
Array(Int, Bool)
Reimplemented from ExprRef.
Definition at line 4597 of file z3py.py.
     def sort(self):
         """Return the array sort of the array expression `self`.
         >>> a = Array('a', IntSort(), BoolSort())
         >>> a.sort()
         Array(Int, Bool)
         """
         return ArraySortRef(Z3_get_sort(self.ctx_ref(), self.as_ast()), self.ctx)
Referenced by FPNumRef.as_string(), ArrayRef.domain(), ArrayRef.domain_n(), FPRef.ebits(), ArithRef.is_int(), ArithRef.is_real(), ArrayRef.range(), FPRef.sbits(), BitVecRef.size(), and ExprRef.sort_kind().