Z3: ArithRef Class Reference
ArithRef Class Reference
Public Member Functions
def sort (self)
def is_int (self)
def is_real (self)
def __add__ (self, other)
def __radd__ (self, other)
def __mul__ (self, other)
def __rmul__ (self, other)
def __sub__ (self, other)
def __rsub__ (self, other)
def __pow__ (self, other)
def __rpow__ (self, other)
def __div__ (self, other)
def __truediv__ (self, other)
def __rdiv__ (self, other)
def __rtruediv__ (self, other)
def __mod__ (self, other)
def __rmod__ (self, other)
def __neg__ (self)
def __pos__ (self)
def __le__ (self, other)
def __lt__ (self, other)
def __gt__ (self, other)
def __ge__ (self, other)
Public Member Functions inherited from ExprRef
def as_ast (self)
def get_id (self)
def sort_kind (self)
def __eq__ (self, other)
def __hash__ (self)
def __ne__ (self, other)
def params (self)
def decl (self)
def num_args (self)
def arg (self, idx)
def children (self)
def from_string (self, s)
def serialize (self)
Public Member Functions inherited from AstRef
def __init__ (self, ast, ctx=None)
def __del__ (self)
def __deepcopy__ (self, memo={})
def __str__ (self)
def __repr__ (self)
def __nonzero__ (self)
def __bool__ (self)
def sexpr (self)
def ctx_ref (self)
def eq (self, other)
def translate (self, target)
def __copy__ (self)
def hash (self)
Public Member Functions inherited from Z3PPObject
def use_pp (self)
Additional Inherited Members
Data Fields inherited from AstRef
ast
ctx
Detailed Description
Integer and Real expressions.
Definition at line 2371 of file z3py.py.
Member Function Documentation
__add__()
def __add__ (self, other)
Create the Z3 expression `self + other`.
>>> x = Int('x')
>>> y = Int('y')
>>> x + y
x + y
>>> (x + y).sort()
Int
Definition at line 2409 of file z3py.py.
     def __add__(self, other):
         """Create the Z3 expression `self + other`.
         >>> x = Int('x')
         >>> y = Int('y')
         >>> x + y
         x + y
         >>> (x + y).sort()
         Int
         """
         a, b = _coerce_exprs(self, other)
         return ArithRef(_mk_bin(Z3_mk_add, a, b), self.ctx)
__div__()
def __div__ (self, other)
Create the Z3 expression `other/self`.
>>> x = Int('x')
>>> y = Int('y')
>>> x/y
x/y
>>> (x/y).sort()
Int
>>> (x/y).sexpr()
'(div x y)'
>>> x = Real('x')
>>> y = Real('y')
>>> x/y
x/y
>>> (x/y).sort()
Real
>>> (x/y).sexpr()
'(/ x y)'
Definition at line 2508 of file z3py.py.
     def __div__(self, other):
         """Create the Z3 expression `other/self`.
         >>> x = Int('x')
         >>> y = Int('y')
         >>> x/y
         x/y
         >>> (x/y).sort()
         Int
         >>> (x/y).sexpr()
         '(div x y)'
         >>> x = Real('x')
         >>> y = Real('y')
         >>> x/y
         x/y
         >>> (x/y).sort()
         Real
         >>> (x/y).sexpr()
         '(/ x y)'
         """
         a, b = _coerce_exprs(self, other)
         return ArithRef(Z3_mk_div(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
Referenced by ArithRef.__truediv__(), BitVecRef.__truediv__(), and FPRef.__truediv__().
__ge__()
def __ge__ (self, other)
Create the Z3 expression `other >= self`.
>>> x, y = Ints('x y')
>>> x >= y
x >= y
>>> y = Real('y')
>>> x >= y
ToReal(x) >= y
Definition at line 2642 of file z3py.py.
     def __ge__(self, other):
         """Create the Z3 expression `other >= self`.
         >>> x, y = Ints('x y')
         >>> x >= y
         x >= y
         >>> y = Real('y')
         >>> x >= y
         ToReal(x) >= y
         """
         a, b = _coerce_exprs(self, other)
         return BoolRef(Z3_mk_ge(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
__gt__()
def __gt__ (self, other)
Create the Z3 expression `other > self`.
>>> x, y = Ints('x y')
>>> x > y
x > y
>>> y = Real('y')
>>> x > y
ToReal(x) > y
Definition at line 2629 of file z3py.py.
     def __gt__(self, other):
         """Create the Z3 expression `other > self`.
         >>> x, y = Ints('x y')
         >>> x > y
         x > y
         >>> y = Real('y')
         >>> x > y
         ToReal(x) > y
         """
         a, b = _coerce_exprs(self, other)
         return BoolRef(Z3_mk_gt(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
__le__()
def __le__ (self, other)
Create the Z3 expression `other <= self`.
>>> x, y = Ints('x y')
>>> x <= y
x <= y
>>> y = Real('y')
>>> x <= y
ToReal(x) <= y
Definition at line 2603 of file z3py.py.
     def __le__(self, other):
         """Create the Z3 expression `other <= self`.
         >>> x, y = Ints('x y')
         >>> x <= y
         x <= y
         >>> y = Real('y')
         >>> x <= y
         ToReal(x) <= y
         """
         a, b = _coerce_exprs(self, other)
         return BoolRef(Z3_mk_le(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
__lt__()
def __lt__ (self, other)
Create the Z3 expression `other < self`.
>>> x, y = Ints('x y')
>>> x < y
x < y
>>> y = Real('y')
>>> x < y
ToReal(x) < y
Definition at line 2616 of file z3py.py.
     def __lt__(self, other):
         """Create the Z3 expression `other < self`.
         >>> x, y = Ints('x y')
         >>> x < y
         x < y
         >>> y = Real('y')
         >>> x < y
         ToReal(x) < y
         """
         a, b = _coerce_exprs(self, other)
         return BoolRef(Z3_mk_lt(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
__mod__()
def __mod__ (self, other)
Create the Z3 expression `other%self`.
>>> x = Int('x')
>>> y = Int('y')
>>> x % y
x%y
>>> simplify(IntVal(10) % IntVal(3))
1
Definition at line 2556 of file z3py.py.
     def __mod__(self, other):
         """Create the Z3 expression `other%self`.
         >>> x = Int('x')
         >>> y = Int('y')
         >>> x % y
         x%y
         >>> simplify(IntVal(10) % IntVal(3))
         1
         """
         a, b = _coerce_exprs(self, other)
         if z3_debug():
             _z3_assert(a.is_int(), "Z3 integer expression expected")
         return ArithRef(Z3_mk_mod(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
__mul__()
def __mul__ (self, other)
Create the Z3 expression `self * other`.
>>> x = Real('x')
>>> y = Real('y')
>>> x * y
x*y
>>> (x * y).sort()
Real
Definition at line 2432 of file z3py.py.
     def __mul__(self, other):
         """Create the Z3 expression `self * other`.
         >>> x = Real('x')
         >>> y = Real('y')
         >>> x * y
         x*y
         >>> (x * y).sort()
         Real
         """
         if isinstance(other, BoolRef):
             return If(other, self, 0)
         a, b = _coerce_exprs(self, other)
         return ArithRef(_mk_bin(Z3_mk_mul, a, b), self.ctx)
__neg__()
def __neg__ (self)
Return an expression representing `-self`.
>>> x = Int('x')
>>> -x
-x
>>> simplify(-(-x))
x
Definition at line 2583 of file z3py.py.
     def __neg__(self):
         """Return an expression representing `-self`.
         >>> x = Int('x')
         >>> -x
         -x
         >>> simplify(-(-x))
         x
         """
         return ArithRef(Z3_mk_unary_minus(self.ctx_ref(), self.as_ast()), self.ctx)
__pos__()
def __pos__ (self)
Return `self`.
>>> x = Int('x')
>>> +x
x
Definition at line 2594 of file z3py.py.
     def __pos__(self):
         """Return `self`.
         >>> x = Int('x')
         >>> +x
         x
         """
         return self
__pow__()
def __pow__ (self, other)
Create the Z3 expression `self**other` (** is the power operator).
>>> x = Real('x')
>>> x**3
x**3
>>> (x**3).sort()
Real
>>> simplify(IntVal(2)**8)
256
Definition at line 2480 of file z3py.py.
     def __pow__(self, other):
         """Create the Z3 expression `self**other` (** is the power operator).
         >>> x = Real('x')
         >>> x**3
         x**3
         >>> (x**3).sort()
         Real
         >>> simplify(IntVal(2)**8)
         256
         """
         a, b = _coerce_exprs(self, other)
         return ArithRef(Z3_mk_power(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
__radd__()
def __radd__ (self, other)
Create the Z3 expression `other + self`.
>>> x = Int('x')
>>> 10 + x
10 + x
Definition at line 2422 of file z3py.py.
     def __radd__(self, other):
         """Create the Z3 expression `other + self`.
         >>> x = Int('x')
         >>> 10 + x
         10 + x
         """
         a, b = _coerce_exprs(self, other)
         return ArithRef(_mk_bin(Z3_mk_add, b, a), self.ctx)
__rdiv__()
def __rdiv__ (self, other)
Create the Z3 expression `other/self`.
>>> x = Int('x')
>>> 10/x
10/x
>>> (10/x).sexpr()
'(div 10 x)'
>>> x = Real('x')
>>> 10/x
10/x
>>> (10/x).sexpr()
'(/ 10.0 x)'
Definition at line 2535 of file z3py.py.
     def __rdiv__(self, other):
         """Create the Z3 expression `other/self`.
         >>> x = Int('x')
         >>> 10/x
         10/x
         >>> (10/x).sexpr()
         '(div 10 x)'
         >>> x = Real('x')
         >>> 10/x
         10/x
         >>> (10/x).sexpr()
         '(/ 10.0 x)'
         """
         a, b = _coerce_exprs(self, other)
         return ArithRef(Z3_mk_div(self.ctx_ref(), b.as_ast(), a.as_ast()), self.ctx)
Referenced by ArithRef.__rtruediv__(), BitVecRef.__rtruediv__(), and FPRef.__rtruediv__().
__rmod__()
def __rmod__ (self, other)
Create the Z3 expression `other%self`.
>>> x = Int('x')
>>> 10 % x
10%x
Definition at line 2571 of file z3py.py.
     def __rmod__(self, other):
         """Create the Z3 expression `other%self`.
         >>> x = Int('x')
         >>> 10 % x
         10%x
         """
         a, b = _coerce_exprs(self, other)
         if z3_debug():
             _z3_assert(a.is_int(), "Z3 integer expression expected")
         return ArithRef(Z3_mk_mod(self.ctx_ref(), b.as_ast(), a.as_ast()), self.ctx)
__rmul__()
def __rmul__ (self, other)
Create the Z3 expression `other * self`.
>>> x = Real('x')
>>> 10 * x
10*x
Definition at line 2447 of file z3py.py.
     def __rmul__(self, other):
         """Create the Z3 expression `other * self`.
         >>> x = Real('x')
         >>> 10 * x
         10*x
         """
         a, b = _coerce_exprs(self, other)
         return ArithRef(_mk_bin(Z3_mk_mul, b, a), self.ctx)
__rpow__()
def __rpow__ (self, other)
Create the Z3 expression `other**self` (** is the power operator).
>>> x = Real('x')
>>> 2**x
2**x
>>> (2**x).sort()
Real
>>> simplify(2**IntVal(8))
256
Definition at line 2494 of file z3py.py.
     def __rpow__(self, other):
         """Create the Z3 expression `other**self` (** is the power operator).
         >>> x = Real('x')
         >>> 2**x
         2**x
         >>> (2**x).sort()
         Real
         >>> simplify(2**IntVal(8))
         256
         """
         a, b = _coerce_exprs(self, other)
         return ArithRef(Z3_mk_power(self.ctx_ref(), b.as_ast(), a.as_ast()), self.ctx)
__rsub__()
def __rsub__ (self, other)
Create the Z3 expression `other - self`.
>>> x = Int('x')
>>> 10 - x
10 - x
Definition at line 2470 of file z3py.py.
     def __rsub__(self, other):
         """Create the Z3 expression `other - self`.
         >>> x = Int('x')
         >>> 10 - x
         10 - x
         """
         a, b = _coerce_exprs(self, other)
         return ArithRef(_mk_bin(Z3_mk_sub, b, a), self.ctx)
__rtruediv__()
def __rtruediv__ (self, other)
Create the Z3 expression `other/self`.
Definition at line 2552 of file z3py.py.
     def __rtruediv__(self, other):
         """Create the Z3 expression `other/self`."""
         return self.__rdiv__(other)
__sub__()
def __sub__ (self, other)
Create the Z3 expression `self - other`.
>>> x = Int('x')
>>> y = Int('y')
>>> x - y
x - y
>>> (x - y).sort()
Int
Definition at line 2457 of file z3py.py.
     def __sub__(self, other):
         """Create the Z3 expression `self - other`.
         >>> x = Int('x')
         >>> y = Int('y')
         >>> x - y
         x - y
         >>> (x - y).sort()
         Int
         """
         a, b = _coerce_exprs(self, other)
         return ArithRef(_mk_bin(Z3_mk_sub, a, b), self.ctx)
__truediv__()
def __truediv__ (self, other)
Create the Z3 expression `other/self`.
Definition at line 2531 of file z3py.py.
     def __truediv__(self, other):
         """Create the Z3 expression `other/self`."""
         return self.__div__(other)
is_int()
def is_int (self)
Return `True` if `self` is an integer expression.
>>> x = Int('x')
>>> x.is_int()
True
>>> (x + 1).is_int()
True
>>> y = Real('y')
>>> (x + y).is_int()
False
Reimplemented in RatNumRef.
Definition at line 2384 of file z3py.py.
     def is_int(self):
         """Return `True` if `self` is an integer expression.
         >>> x = Int('x')
         >>> x.is_int()
         True
         >>> (x + 1).is_int()
         True
         >>> y = Real('y')
         >>> (x + y).is_int()
         False
         """
         return self.sort().is_int()
Referenced by IntNumRef.as_long().
is_real()
def is_real (self)
Return `True` if `self` is an real expression.
>>> x = Real('x')
>>> x.is_real()
True
>>> (x + 1).is_real()
True
Reimplemented in RatNumRef.
Definition at line 2398 of file z3py.py.
     def is_real(self):
         """Return `True` if `self` is an real expression.
         >>> x = Real('x')
         >>> x.is_real()
         True
         >>> (x + 1).is_real()
         True
         """
         return self.sort().is_real()
sort()
def sort (self)
Return the sort (type) of the arithmetical expression `self`.
>>> Int('x').sort()
Int
>>> (Real('x') + 1).sort()
Real
Reimplemented from ExprRef.
Definition at line 2374 of file z3py.py.
     def sort(self):
         """Return the sort (type) of the arithmetical expression `self`.
         >>> Int('x').sort()
         Int
         >>> (Real('x') + 1).sort()
         Real
         """
         return ArithSortRef(Z3_get_sort(self.ctx_ref(), self.as_ast()), self.ctx)