Z3: Params Class Reference
Params Class Reference
Public Member Functions
void add (Symbol name, boolean value)
void add (Symbol name, double value)
void add (Symbol name, String value)
void add (Symbol name, Symbol value)
void add (String name, boolean value)
void add (String name, int value)
void add (String name, double value)
void add (String name, Symbol value)
void add (String name, String value)
String toString ()
Additional Inherited Members
Static Public Member Functions inherited from Z3Object
static long[] arrayToNative (Z3Object[] a)
static int arrayLength (Z3Object[] a)
Detailed Description
A ParameterSet represents a configuration in the form of Symbol/value pairs.
Definition at line 26 of file Params.java.
Member Function Documentation
add() [1/9]
void add (String name, boolean value) inline
Adds a parameter setting.
Definition at line 69 of file Params.java.
    {
        Native.paramsSetBool(getContext().nCtx(), getNativeObject(),
                getContext().mkSymbol(name).getNativeObject(), value);
    }
Referenced by Solver.__iadd__().
add() [2/9]
void add (String name, double value) inline
Adds a parameter setting.
Definition at line 87 of file Params.java.
    {
        Native.paramsSetDouble(getContext().nCtx(), getNativeObject(), getContext()
                .mkSymbol(name).getNativeObject(), value);
    }
Referenced by Solver.__iadd__().
add() [3/9]
void add (String name, int value) inline
Adds a parameter setting.
Definition at line 78 of file Params.java.
    {
        Native.paramsSetUint(getContext().nCtx(), getNativeObject(), getContext()
                .mkSymbol(name).getNativeObject(), value);
    }
Referenced by Solver.__iadd__().
add() [4/9]
void add (String name, String value) inline
Adds a parameter setting.
Definition at line 105 of file Params.java.
    {
        Native.paramsSetSymbol(getContext().nCtx(), getNativeObject(),
                getContext().mkSymbol(name).getNativeObject(),
                getContext().mkSymbol(value).getNativeObject());
    }
Referenced by Solver.__iadd__().
add() [5/9]
void add (String name, Symbol value) inline
Adds a parameter setting.
Definition at line 96 of file Params.java.
    {
        Native.paramsSetSymbol(getContext().nCtx(), getNativeObject(), getContext()
                .mkSymbol(name).getNativeObject(), value.getNativeObject());
    }
Referenced by Solver.__iadd__().
add() [6/9]
void add (Symbol name, boolean value) inline
Adds a parameter setting.
Definition at line 30 of file Params.java.
    {
        Native.paramsSetBool(getContext().nCtx(), getNativeObject(),
                name.getNativeObject(), (value));
    }
Referenced by Solver.__iadd__().
add() [7/9]
void add (Symbol name, double value) inline
Adds a parameter setting.
Definition at line 39 of file Params.java.
    {
        Native.paramsSetDouble(getContext().nCtx(), getNativeObject(),
                name.getNativeObject(), value);
    }
Referenced by Solver.__iadd__().
add() [8/9]
void add (Symbol name, String value) inline
Adds a parameter setting.
Definition at line 48 of file Params.java.
    {
        Native.paramsSetSymbol(getContext().nCtx(), getNativeObject(),
                name.getNativeObject(),
                getContext().mkSymbol(value).getNativeObject());
    }
Referenced by Solver.__iadd__().
add() [9/9]
void add (Symbol name, Symbol value) inline
Adds a parameter setting.
Definition at line 59 of file Params.java.
    {
        Native.paramsSetSymbol(getContext().nCtx(), getNativeObject(),
                name.getNativeObject(), value.getNativeObject());
    }
Referenced by Solver.__iadd__().
toString()
String toString () inline
A string representation of the parameter set.
Definition at line 117 of file Params.java.
    {
        return Native.paramsToString(getContext().nCtx(), getNativeObject());
    }