Z3: params Class Reference
params Class Reference
#include <z3++.h>
Public Member Functions
params (context &c)
params (params const &s)
~params () override
operator Z3_params () const
params & operator= (params const &s)
void set (char const *k, bool b)
void set (char const *k, unsigned n)
void set (char const *k, double n)
void set (char const *k, symbol const &s)
void set (char const *k, char const *s)
Public Member Functions inherited from object
object (context &c)
virtual ~object ()=default
context & ctx () const
Z3_error_code check_error () const
Friends
std::ostream & operator<< (std::ostream &out, params const &p)
Additional Inherited Members
Protected Attributes inherited from object
context * m_ctx
Detailed Description
Definition at line 542 of file z3++.h.
Constructor & Destructor Documentation
params() [1/2]
params (context & c) inline
Definition at line 545 of file z3++.h.
:object(c) { m_params = Z3_mk_params(c); Z3_params_inc_ref(ctx(), m_params); }
Referenced by ParamsRef::__deepcopy__(), ParamsRef::__del__(), ParamsRef::__repr__(), ParamsRef::set(), and ParamsRef::validate().
params() [2/2]
params (params const & s) inline
Definition at line 546 of file z3++.h.
:object(s), m_params(s.m_params) { Z3_params_inc_ref(ctx(), m_params); }
Referenced by ParamsRef::__deepcopy__(), ParamsRef::__del__(), ParamsRef::__repr__(), ParamsRef::set(), and ParamsRef::validate().
~params()
~params () inline override
Definition at line 547 of file z3++.h.
{ Z3_params_dec_ref(ctx(), m_params); }
Member Function Documentation
operator Z3_params()
operator Z3_params () const inline
Definition at line 548 of file z3++.h.
{ return m_params; }
operator=()
params & operator= (params const & s) inline
Definition at line 549 of file z3++.h.
{
            Z3_params_inc_ref(s.ctx(), s.m_params);
            Z3_params_dec_ref(ctx(), m_params);
            object::operator=(s);
            m_params = s.m_params;
            return *this;
        }
set() [1/5]
void set (char const * k, bool b) inline
Definition at line 556 of file z3++.h.
{ Z3_params_set_bool(ctx(), m_params, ctx().str_symbol(k), b); }
Referenced by solver::set(), solver::set(), solver::set(), solver::set(), and solver::set().
set() [2/5]
void set (char const * k, char const * s) inline
Definition at line 560 of file z3++.h.
{ Z3_params_set_symbol(ctx(), m_params, ctx().str_symbol(k), ctx().str_symbol(s)); }
set() [3/5]
void set (char const * k, double n) inline
Definition at line 558 of file z3++.h.
{ Z3_params_set_double(ctx(), m_params, ctx().str_symbol(k), n); }
set() [4/5]
void set (char const * k, symbol const & s) inline
Definition at line 559 of file z3++.h.
{ Z3_params_set_symbol(ctx(), m_params, ctx().str_symbol(k), s); }
set() [5/5]
void set (char const * k, unsigned n) inline
Definition at line 557 of file z3++.h.
{ Z3_params_set_uint(ctx(), m_params, ctx().str_symbol(k), n); }
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & out, params const & p) friend
Definition at line 564 of file z3++.h.
{
        out << Z3_params_to_string(p.ctx(), p); return out;
    }