Z3: Solver Class Reference
Solver Class Reference
Solvers.
Data Structures
class DecRefQueue
Public Member Functions
void Set (string name, bool value)
Sets parameter on the solver
void Set (string name, uint value)
Sets parameter on the solver
void Set (string name, double value)
Sets parameter on the solver
void Set (string name, string value)
Sets parameter on the solver
void Set (string name, Symbol value)
Sets parameter on the solver
void Set (Symbol name, bool value)
Sets parameter on the solver
void Set (Symbol name, uint value)
Sets parameter on the solver
void Set (Symbol name, double value)
Sets parameter on the solver
void Set (Symbol name, string value)
Sets parameter on the solver
void Set (Symbol name, Symbol value)
Sets parameter on the solver
void Push ()
Creates a backtracking point.
void Pop (uint n=1)
Backtracks n backtracking points.
void Reset ()
Resets the Solver.
void Assert (params BoolExpr[] constraints)
Assert a constraint (or multiple) into the solver.
void Add (params BoolExpr[] constraints)
Alias for Assert.
void Add (IEnumerable< BoolExpr > constraints)
Alias for Assert.
void AssertAndTrack (BoolExpr[] constraints, BoolExpr[] ps)
Assert multiple constraints into the solver, and track them (in the unsat) core using the Boolean constants in ps.
void AssertAndTrack (BoolExpr constraint, BoolExpr p)
Assert a constraint into the solver, and track it (in the unsat) core using the Boolean constant p.
void FromFile (string file)
Load solver assertions from a file.
void FromString (string str)
Load solver assertions from a string.
Status Check (params Expr[] assumptions)
Checks whether the assertions in the solver are consistent or not.
Status Check (IEnumerable< BoolExpr > assumptions)
Checks whether the assertions in the solver are consistent or not.
Status Consequences (IEnumerable< BoolExpr > assumptions, IEnumerable< Expr > variables, out BoolExpr[] consequences)
Retrieve fixed assignments to the set of variables in the form of consequences. Each consequence is an implication of the form
IEnumerable< BoolExpr[]> Cube ()
Return a set of cubes.
Solver Translate (Context ctx)
Create a clone of the current solver with respect to ctx.
void ImportModelConverter (Solver src)
Import model converter from other solver.
override string ToString ()
A string representation of the solver.
Public Member Functions inherited from Z3Object
void Dispose ()
Disposes of the underlying native Z3 object.
Properties
string Help [get]
A string that describes all available solver parameters.
Params Parameters [set]
Sets the solver parameters.
ParamDescrs ParameterDescriptions [get]
Retrieves parameter descriptions for solver.
uint NumScopes [get]
The current number of backtracking points (scopes).
uint NumAssertions [get]
The number of assertions in the solver.
BoolExpr[] Assertions [get]
The set of asserted formulas.
BoolExpr[] Units [get]
Currently inferred units.
Model Model [get]
The model of the last Check(params Expr[] assumptions).
Expr Proof [get]
The proof of the last Check(params Expr[] assumptions).
BoolExpr[] UnsatCore [get]
The unsat core of the last Check.
string ReasonUnknown [get]
A brief justification of why the last call to Check returned UNKNOWN.
uint BacktrackLevel [get, set]
Backtrack level that can be adjusted by conquer process
BoolExpr[] CubeVariables [get, set]
Variables available and returned by the cuber.
Statistics Statistics [get]
Solver statistics.
Properties inherited from Z3Object
Context Context [get]
Access Context object
Detailed Description
Solvers.
Definition at line 30 of file Solver.cs.
Member Function Documentation
Add() [1/2]
void Add (IEnumerable< BoolExpr > constraints) inline
Alias for Assert.
Definition at line 223 of file Solver.cs.
         {
             Assert(constraints.ToArray());
         }
Add() [2/2]
void Add (params BoolExpr[] constraints) inline
Alias for Assert.
Definition at line 215 of file Solver.cs.
         {
             Assert(constraints);
         }
Assert()
void Assert (params BoolExpr[] constraints) inline
Assert a constraint (or multiple) into the solver.
Definition at line 200 of file Solver.cs.
         {
             Debug.Assert(constraints != null);
             Debug.Assert(constraints.All(c => c != null));
             Context.CheckContextMatch<BoolExpr>(constraints);
             foreach (BoolExpr a in constraints)
             {
                 Native.Z3_solver_assert(Context.nCtx, NativeObject, a.NativeObject);
             }
         }
Referenced by Solver.Add(), Context.MkSolver(), and Solver.Translate().
AssertAndTrack() [1/2]
void AssertAndTrack (BoolExpr constraint, BoolExpr p) inline
Assert a constraint into the solver, and track it (in the unsat) core using the Boolean constant p.
This API is an alternative to Check(Expr[]) with assumptions for extracting unsat cores. Both APIs can be used in the same solver. The unsat core will contain a combination of the Boolean variables provided using AssertAndTrack(BoolExpr[],BoolExpr[]) and the Boolean literals provided using Check(Expr[]) with assumptions.
Definition at line 264 of file Solver.cs.
         {
             Debug.Assert(constraint != null);
             Debug.Assert(p != null);
             Context.CheckContextMatch(constraint);
             Context.CheckContextMatch(p);
             Native.Z3_solver_assert_and_track(Context.nCtx, NativeObject, constraint.NativeObject, p.NativeObject);
         }
AssertAndTrack() [2/2]
void AssertAndTrack (BoolExpr[] constraints, BoolExpr[] ps) inline
Assert multiple constraints into the solver, and track them (in the unsat) core using the Boolean constants in ps.
This API is an alternative to Check(Expr[]) with assumptions for extracting unsat cores. Both APIs can be used in the same solver. The unsat core will contain a combination of the Boolean variables provided using AssertAndTrack(BoolExpr[],BoolExpr[]) and the Boolean literals provided using Check(Expr[]) with assumptions.
Definition at line 239 of file Solver.cs.
         {
             Debug.Assert(constraints != null);
             Debug.Assert(constraints.All(c => c != null));
             Debug.Assert(ps.All(c => c != null));
             Context.CheckContextMatch<BoolExpr>(constraints);
             Context.CheckContextMatch<BoolExpr>(ps);
             if (constraints.Length != ps.Length)
                 throw new Z3Exception("Argument size mismatch");
             for (int i = 0 ; i < constraints.Length; i++)
                 Native.Z3_solver_assert_and_track(Context.nCtx, NativeObject, constraints[i].NativeObject, ps[i].NativeObject);
         }
Check() [1/2]
Status Check (IEnumerable< BoolExpr > assumptions) inline
Checks whether the assertions in the solver are consistent or not.
See also
Model, UnsatCore, Proof
Definition at line 354 of file Solver.cs.
         {
             Z3_lbool r;
             BoolExpr[] asms = assumptions.ToArray();
             if (asms.Length == 0)
                 r = (Z3_lbool)Native.Z3_solver_check(Context.nCtx, NativeObject);
             else
                 r = (Z3_lbool)Native.Z3_solver_check_assumptions(Context.nCtx, NativeObject, (uint)asms.Length, AST.ArrayToNative(asms));
             return lboolToStatus(r);
         }
Check() [2/2]
Status Check (params Expr[] assumptions) inline
Checks whether the assertions in the solver are consistent or not.
See also
Model, UnsatCore, Proof
Definition at line 336 of file Solver.cs.
         {
             Z3_lbool r;
             if (assumptions == null || assumptions.Length == 0)
                 r = (Z3_lbool)Native.Z3_solver_check(Context.nCtx, NativeObject);
             else
                 r = (Z3_lbool)Native.Z3_solver_check_assumptions(Context.nCtx, NativeObject, (uint)assumptions.Length, AST.ArrayToNative(assumptions));
             return lboolToStatus(r);
         }
Consequences()
Status Consequences (IEnumerable< BoolExpr > assumptions, IEnumerable< Expr > variables, out BoolExpr[] consequences) inline
Retrieve fixed assignments to the set of variables in the form of consequences. Each consequence is an implication of the form
  relevant-assumptions Implies variable = value
where the relevant assumptions is a subset of the assumptions that are passed in and the equality on the right side of the implication indicates how a variable is fixed.
See also
Model, UnsatCore, Proof
Definition at line 380 of file Solver.cs.
         {
             using ASTVector result = new ASTVector(Context);
             using ASTVector asms = new ASTVector(Context);
             using ASTVector vars = new ASTVector(Context);
             foreach (var asm in assumptions) asms.Push(asm);
             foreach (var v in variables) vars.Push(v);
             Z3_lbool r = (Z3_lbool)Native.Z3_solver_get_consequences(Context.nCtx, NativeObject, asms.NativeObject, vars.NativeObject, result.NativeObject);
             consequences = result.ToBoolExprArray();
             return lboolToStatus(r);
         }
Cube()
IEnumerable<BoolExpr[]> Cube () inline
Return a set of cubes.
Definition at line 474 of file Solver.cs.
         {
              using ASTVector cv = new ASTVector(Context);
              if (CubeVariables != null)
                 foreach (var b in CubeVariables) cv.Push(b);
              while (true) {
                 var lvl = BacktrackLevel;
                 BacktrackLevel = uint.MaxValue;
                 using ASTVector r = new ASTVector(Context, Native.Z3_solver_cube(Context.nCtx, NativeObject, cv.NativeObject, lvl));
                 var v = r.ToBoolExprArray();
                 CubeVariables = cv.ToBoolExprArray();
                 if (v.Length == 1 && v[0].IsFalse) {
                    break;
                 }
                 yield return v;
                 if (v.Length == 0) {
                    break;
                 }
              }
         }
FromFile()
void FromFile (string file) inline
Load solver assertions from a file.
Definition at line 277 of file Solver.cs.
         {
              Native.Z3_solver_from_file(Context.nCtx, NativeObject, file);
         }
FromString()
void FromString (string str) inline
Load solver assertions from a string.
Definition at line 285 of file Solver.cs.
         {
              Native.Z3_solver_from_string(Context.nCtx, NativeObject, str);
         }
ImportModelConverter()
void ImportModelConverter (Solver src) inline
Import model converter from other solver.
Definition at line 508 of file Solver.cs.
         {
              Native.Z3_solver_import_model_converter(Context.nCtx, src.NativeObject, NativeObject);
         }
Pop()
void Pop (uint n = 1) inline
Backtracks n backtracking points.
Note that an exception is thrown if n is not smaller than NumScopes
See also
Push
Definition at line 183 of file Solver.cs.
         {
             Native.Z3_solver_pop(Context.nCtx, NativeObject, n);
         }
Push()
void Push () inline
Creates a backtracking point.
See also
Pop
Definition at line 173 of file Solver.cs.
         {
             Native.Z3_solver_push(Context.nCtx, NativeObject);
         }
Reset()
void Reset () inline
Resets the Solver.
This removes all assertions from the solver.
Definition at line 192 of file Solver.cs.
         {
             Native.Z3_solver_reset(Context.nCtx, NativeObject);
         }
Set() [1/10]
void Set (string name, bool value) inline
Sets parameter on the solver
Definition at line 61 of file Solver.cs.
     {
         using var parameters = Context.MkParams().Add(name, value);
         Parameters = parameters;
     }
Set() [2/10]
void Set (string name, double value) inline
Sets parameter on the solver
Definition at line 79 of file Solver.cs.
     {
         using var parameters = Context.MkParams().Add(name, value);
         Parameters = parameters;
     }
Set() [3/10]
void Set (string name, string value) inline
Sets parameter on the solver
Definition at line 88 of file Solver.cs.
     {
         using var parameters = Context.MkParams().Add(name, value);
         Parameters = parameters;
     }
Set() [4/10]
void Set (string name, Symbol value) inline
Sets parameter on the solver
Definition at line 97 of file Solver.cs.
     {
         using var parameters = Context.MkParams().Add(name, value);
         Parameters = parameters;
     }
Set() [5/10]
void Set (string name, uint value) inline
Sets parameter on the solver
Definition at line 70 of file Solver.cs.
     {
         using var parameters = Context.MkParams().Add(name, value);
         Parameters = parameters;
     }
Set() [6/10]
void Set (Symbol name, bool value) inline
Sets parameter on the solver
Definition at line 106 of file Solver.cs.
     {
         using var parameters = Context.MkParams().Add(name, value);
         Parameters = parameters;
     }
Set() [7/10]
void Set (Symbol name, double value) inline
Sets parameter on the solver
Definition at line 124 of file Solver.cs.
     {
         using var parameters = Context.MkParams().Add(name, value);
         Parameters = parameters;
     }
Set() [8/10]
void Set (Symbol name, string value) inline
Sets parameter on the solver
Definition at line 133 of file Solver.cs.
     {
         using var parameters = Context.MkParams().Add(name, value);
         Parameters = parameters;
     }
Set() [9/10]
void Set (Symbol name, Symbol value) inline
Sets parameter on the solver
Definition at line 142 of file Solver.cs.
     {
         using var parameters = Context.MkParams().Add(name, value);
         Parameters = parameters;
     }
Set() [10/10]
void Set (Symbol name, uint value) inline
Sets parameter on the solver
Definition at line 115 of file Solver.cs.
     {
         using var parameters = Context.MkParams().Add(name, value);
         Parameters = parameters;
     }
ToString()
override string ToString () inline
A string representation of the solver.
Definition at line 528 of file Solver.cs.
         {
             return Native.Z3_solver_to_string(Context.nCtx, NativeObject);
         }
Translate()
Solver Translate (Context ctx) inline
Create a clone of the current solver with respect to ctx.
Definition at line 499 of file Solver.cs.
         {
              Debug.Assert(ctx != null);
              return new Solver(ctx, Native.Z3_solver_translate(Context.nCtx, NativeObject, ctx.nCtx));
         }
Property Documentation
Assertions
BoolExpr [] Assertions get
The set of asserted formulas.
Definition at line 306 of file Solver.cs.
         {
             get
             {
                 using ASTVector assertions = new ASTVector(Context, Native.Z3_solver_get_assertions(Context.nCtx, NativeObject));
                 return assertions.ToBoolExprArray();
             }
         }
BacktrackLevel
uint BacktrackLevel get set
Backtrack level that can be adjusted by conquer process
Definition at line 463 of file Solver.cs.
 { get; set; }
Referenced by Solver.Cube().
CubeVariables
BoolExpr [] CubeVariables get set
Variables available and returned by the cuber.
Definition at line 468 of file Solver.cs.
 { get; set; }
Referenced by Solver.Cube().
string Help get
A string that describes all available solver parameters.
Definition at line 36 of file Solver.cs.
         {
             get
             {
                 return Native.Z3_solver_get_help(Context.nCtx, NativeObject);
             }
         }
Model
Model Model get
The model of the last Check(params Expr[] assumptions).
The result is null if Check(params Expr[] assumptions) was not invoked before, if its results was not SATISFIABLE, or if model production is not enabled.
Definition at line 400 of file Solver.cs.
         {
             get
             {
                 IntPtr x = Native.Z3_solver_get_model(Context.nCtx, NativeObject);
                 if (x == IntPtr.Zero)
                     return null;
                 else
                     return new Model(Context, x);
             }
         }
NumAssertions
uint NumAssertions get
The number of assertions in the solver.
Definition at line 294 of file Solver.cs.
         {
             get
             {
                 using ASTVector assertions = new ASTVector(Context, Native.Z3_solver_get_assertions(Context.nCtx, NativeObject));
                 return assertions.Size;
             }
         }
NumScopes
uint NumScopes get
The current number of backtracking points (scopes).
See also
Pop, Push
Definition at line 165 of file Solver.cs.
         {
             get { return Native.Z3_solver_get_num_scopes(Context.nCtx, NativeObject); }
         }
ParameterDescriptions
ParamDescrs ParameterDescriptions get
Retrieves parameter descriptions for solver.
Definition at line 154 of file Solver.cs.
         {
             get { return new ParamDescrs(Context, Native.Z3_solver_get_param_descrs(Context.nCtx, NativeObject)); }
         }
Parameters
Params Parameters set
Sets the solver parameters.
Definition at line 48 of file Solver.cs.
         {
             set
             {
                 Debug.Assert(value != null);
                 Context.CheckContextMatch(value);
                 Native.Z3_solver_set_params(Context.nCtx, NativeObject, value.NativeObject);
             }
         }
Referenced by Solver.Set().
Proof
Expr Proof get
The proof of the last Check(params Expr[] assumptions).
The result is null if Check(params Expr[] assumptions) was not invoked before, if its results was not UNSATISFIABLE, or if proof production is disabled.
Definition at line 419 of file Solver.cs.
         {
             get
             {
                 IntPtr x = Native.Z3_solver_get_proof(Context.nCtx, NativeObject);
                 if (x == IntPtr.Zero)
                     return null;
                 else
                     return Expr.Create(Context, x);
             }
         }
ReasonUnknown
string ReasonUnknown get
A brief justification of why the last call to Check returned UNKNOWN.
Definition at line 452 of file Solver.cs.
         {
             get
             {
                 return Native.Z3_solver_get_reason_unknown(Context.nCtx, NativeObject);
             }
         }
Statistics
Statistics Statistics get
Solver statistics.
Definition at line 517 of file Solver.cs.
         {
             get
             {
                 return new Statistics(Context, Native.Z3_solver_get_statistics(Context.nCtx, NativeObject));
             }
         }
Units
BoolExpr [] Units get
Currently inferred units.
Definition at line 319 of file Solver.cs.
         {
             get
             {
                 using ASTVector assertions = new ASTVector(Context, Native.Z3_solver_get_units(Context.nCtx, NativeObject));
                 return assertions.ToBoolExprArray();
             }
         }
UnsatCore
BoolExpr [] UnsatCore get
The unsat core of the last Check.
The unsat core is a subset of Assertions The result is empty if Check was not invoked before, if its results was not UNSATISFIABLE, or if core production is disabled.
Definition at line 439 of file Solver.cs.
         {
             get
             {
                 using ASTVector core = new ASTVector(Context, Native.Z3_solver_get_unsat_core(Context.nCtx, NativeObject));
                 return core.ToBoolExprArray();
             }
         }