Z3: model Class Reference
model Class Reference
#include <z3++.h>
Data Structures
struct translate
Public Member Functions
model (context &c)
model (context &c, Z3_model m)
model (model const &s)
model (model &src, context &dst, translate)
~model () override
operator Z3_model () const
model & operator= (model const &s)
expr eval (expr const &n, bool model_completion=false) const
unsigned num_consts () const
unsigned num_funcs () const
func_decl get_const_decl (unsigned i) const
func_decl get_func_decl (unsigned i) const
unsigned size () const
func_decl operator[] (int i) const
expr get_const_interp (func_decl c) const
func_interp get_func_interp (func_decl f) const
bool has_interp (func_decl f) const
func_interp add_func_interp (func_decl &f, expr &else_val)
void add_const_interp (func_decl &f, expr &value)
std::string to_string () const
Public Member Functions inherited from object
object (context &c)
virtual ~object ()=default
context & ctx () const
Z3_error_code check_error () const
Friends
std::ostream & operator<< (std::ostream &out, model const &m)
Additional Inherited Members
Protected Attributes inherited from object
context * m_ctx
Detailed Description
Definition at line 2629 of file z3++.h.
Constructor & Destructor Documentation
model() [1/4]
model (context & c) inline
Definition at line 2637 of file z3++.h.
:object(c) { init(Z3_mk_model(c)); }
Referenced by ModelRef::__del__(), ModelRef::__getitem__(), ModelRef::__len__(), ModelRef::decls(), ModelRef::eval(), ModelRef::get_interp(), ModelRef::get_sort(), ModelRef::get_universe(), ModelRef::num_sorts(), ModelRef::project(), ModelRef::project_with_witness(), ModelRef::sexpr(), ModelRef::translate(), and ModelRef::update_value().
model() [2/4]
model (context & c, Z3_model m) inline
Definition at line 2638 of file z3++.h.
:object(c) { init(m); }
Referenced by ModelRef::__del__(), ModelRef::__getitem__(), ModelRef::__len__(), ModelRef::decls(), ModelRef::eval(), ModelRef::get_interp(), ModelRef::get_sort(), ModelRef::get_universe(), ModelRef::num_sorts(), ModelRef::project(), ModelRef::project_with_witness(), ModelRef::sexpr(), ModelRef::translate(), and ModelRef::update_value().
model() [3/4]
model (model const & s) inline
Definition at line 2639 of file z3++.h.
:object(s) { init(s.m_model); }
Referenced by ModelRef::__del__(), ModelRef::__getitem__(), ModelRef::__len__(), ModelRef::decls(), ModelRef::eval(), ModelRef::get_interp(), ModelRef::get_sort(), ModelRef::get_universe(), ModelRef::num_sorts(), ModelRef::project(), ModelRef::project_with_witness(), ModelRef::sexpr(), ModelRef::translate(), and ModelRef::update_value().
model() [4/4]
model (model & src, context & dst, translate) inline
Definition at line 2640 of file z3++.h.
: object(dst) { init(Z3_model_translate(src.ctx(), src, dst)); }
Referenced by ModelRef::__del__(), ModelRef::__getitem__(), ModelRef::__len__(), ModelRef::decls(), ModelRef::eval(), ModelRef::get_interp(), ModelRef::get_sort(), ModelRef::get_universe(), ModelRef::num_sorts(), ModelRef::project(), ModelRef::project_with_witness(), ModelRef::sexpr(), ModelRef::translate(), and ModelRef::update_value().
~model()
~model () inline override
Definition at line 2641 of file z3++.h.
{ Z3_model_dec_ref(ctx(), m_model); }
Member Function Documentation
add_const_interp()
void add_const_interp (func_decl & f, expr & value) inline
Definition at line 2700 of file z3++.h.
{
            Z3_add_const_interp(ctx(), m_model, f, value);
            check_error();
        }
add_func_interp()
func_interp add_func_interp (func_decl & f, expr & else_val) inline
Definition at line 2694 of file z3++.h.
{
            Z3_func_interp r = Z3_add_func_interp(ctx(), m_model, f, else_val);
            check_error();
            return func_interp(ctx(), r);
        }
eval()
expr eval (expr const & n, bool model_completion = false) const inline
Definition at line 2651 of file z3++.h.
{
            check_context(*this, n);
            Z3_ast r = 0;
            bool status = Z3_model_eval(ctx(), m_model, n, model_completion, &r);
            check_error();
            if (status == false && ctx().enable_exceptions())
                Z3_THROW(exception("failed to evaluate expression"));
            return expr(ctx(), r);
        }
Referenced by ModelRef::evaluate().
get_const_decl()
func_decl get_const_decl (unsigned i) const inline
Definition at line 2663 of file z3++.h.
{ Z3_func_decl r = Z3_model_get_const_decl(ctx(), m_model, i); check_error(); return func_decl(ctx(), r); }
Referenced by model::operator[]().
get_const_interp()
expr get_const_interp (func_decl c) const inline
Definition at line 2674 of file z3++.h.
{
            check_context(*this, c);
            Z3_ast r = Z3_model_get_const_interp(ctx(), m_model, c);
            check_error();
            return expr(ctx(), r);
        }
get_func_decl()
func_decl get_func_decl (unsigned i) const inline
Definition at line 2664 of file z3++.h.
{ Z3_func_decl r = Z3_model_get_func_decl(ctx(), m_model, i); check_error(); return func_decl(ctx(), r); }
Referenced by model::operator[]().
get_func_interp()
func_interp get_func_interp (func_decl f) const inline
Definition at line 2680 of file z3++.h.
{
            check_context(*this, f);
            Z3_func_interp r = Z3_model_get_func_interp(ctx(), m_model, f);
            check_error();
            return func_interp(ctx(), r);
        }
has_interp()
bool has_interp (func_decl f) const inline
Definition at line 2689 of file z3++.h.
{
            check_context(*this, f);
            return Z3_model_has_interp(ctx(), m_model, f);
        }
num_consts()
unsigned num_consts () const inline
Definition at line 2661 of file z3++.h.
{ return Z3_model_get_num_consts(ctx(), m_model); }
Referenced by model::operator[](), and model::size().
num_funcs()
unsigned num_funcs () const inline
Definition at line 2662 of file z3++.h.
{ return Z3_model_get_num_funcs(ctx(), m_model); }
Referenced by model::size().
operator Z3_model()
operator Z3_model () const inline
Definition at line 2642 of file z3++.h.
{ return m_model; }
operator=()
model & operator= (model const & s) inline
Definition at line 2643 of file z3++.h.
{
            Z3_model_inc_ref(s.ctx(), s.m_model);
            Z3_model_dec_ref(ctx(), m_model);
            object::operator=(s);
            m_model = s.m_model;
            return *this;
        }
operator[]()
func_decl operator[] (int i) const inline
Definition at line 2666 of file z3++.h.
{
            assert(0 <= i);
            return static_cast<unsigned>(i) < num_consts() ? get_const_decl(i) : get_func_decl(i - num_consts());
        }
size()
unsigned size () const inline
Definition at line 2665 of file z3++.h.
{ return num_consts() + num_funcs(); }
Referenced by ParamDescrsRef::__len__(), Goal::__len__(), BitVecNumRef::as_signed_long(), and BitVecSortRef::subsort().
to_string()
std::string to_string () const inline
Definition at line 2707 of file z3++.h.
{ return m_model ? std::string(Z3_model_to_string(ctx(), m_model)) : "null"; }
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & out, model const & m) friend
Definition at line 2709 of file z3++.h.
{ return out << m.to_string(); }