Z3: Params Class Reference
Params Class Reference
A Params objects represents a configuration in the form of Symbol/value pairs.
Public Member Functions
Params Add (Symbol name, bool value)
Adds a parameter setting.
Params Add (Symbol name, uint value)
Adds a parameter setting.
Params Add (Symbol name, double value)
Adds a parameter setting.
Params Add (Symbol name, string value)
Adds a parameter setting.
Params Add (Symbol name, Symbol value)
Adds a parameter setting.
Params Add (string name, bool value)
Adds a parameter setting.
Params Add (string name, uint value)
Adds a parameter setting.
Params Add (string name, double value)
Adds a parameter setting.
Params Add (string name, Symbol value)
Adds a parameter setting.
Params Add (string name, string value)
Adds a parameter setting.
override string ToString ()
A string representation of the parameter set.
Public Member Functions inherited from Z3Object
void Dispose ()
Disposes of the underlying native Z3 object.
Additional Inherited Members
Properties inherited from Z3Object
Context Context [get]
Access Context object.
Detailed Description
A Params objects represents a configuration in the form of Symbol/value pairs.
Definition at line 28 of file Params.cs.
Member Function Documentation
Add() [1/10]
Params Add (string name, bool value) inline
Adds a parameter setting.
Definition at line 90 of file Params.cs.
        {
            Native.Z3_params_set_bool(Context.nCtx, NativeObject, Context.MkSymbol(name).NativeObject, (byte)(value ? 1 : 0));
            return this;
        }
Add() [2/10]
Params Add (string name, double value) inline
Adds a parameter setting.
Definition at line 108 of file Params.cs.
        {
            Native.Z3_params_set_double(Context.nCtx, NativeObject, Context.MkSymbol(name).NativeObject, value);
            return this;
        }
Add() [3/10]
Params Add (string name, string value) inline
Adds a parameter setting.
Definition at line 128 of file Params.cs.
        {
            Debug.Assert(name != null);
            Debug.Assert(value != null);
            Native.Z3_params_set_symbol(Context.nCtx, NativeObject, Context.MkSymbol(name).NativeObject, Context.MkSymbol(value).NativeObject);
            return this;
        }
Add() [4/10]
Params Add (string name, Symbol value) inline
Adds a parameter setting.
Definition at line 117 of file Params.cs.
        {
            Debug.Assert(value != null);
            Native.Z3_params_set_symbol(Context.nCtx, NativeObject, Context.MkSymbol(name).NativeObject, value.NativeObject);
            return this;
        }
Add() [5/10]
Params Add (string name, uint value) inline
Adds a parameter setting.
Definition at line 99 of file Params.cs.
        {
            Native.Z3_params_set_uint(Context.nCtx, NativeObject, Context.MkSymbol(name).NativeObject, value);
            return this;
        }
Add() [6/10]
Params Add (Symbol name, bool value) inline
Adds a parameter setting.
Definition at line 33 of file Params.cs.
        {
            Debug.Assert(name != null);
            Native.Z3_params_set_bool(Context.nCtx, NativeObject, name.NativeObject, (byte)(value ? 1 : 0));
            return this;
        }
Referenced by Optimize.Set(), Solver.Set(), Optimize.Set(), Solver.Set(), Optimize.Set(), Solver.Set(), Optimize.Set(), Solver.Set(), Optimize.Set(), Solver.Set(), Optimize.Set(), Solver.Set(), Optimize.Set(), Solver.Set(), Optimize.Set(), Solver.Set(), Optimize.Set(), Solver.Set(), Optimize.Set(), and Solver.Set().
Add() [7/10]
Params Add (Symbol name, double value) inline
Adds a parameter setting.
Definition at line 55 of file Params.cs.
        {
            Debug.Assert(name != null);
            Native.Z3_params_set_double(Context.nCtx, NativeObject, name.NativeObject, value);
            return this;
        }
Add() [8/10]
Params Add (Symbol name, string value) inline
Adds a parameter setting.
Definition at line 66 of file Params.cs.
        {
            Debug.Assert(value != null);
            Native.Z3_params_set_symbol(Context.nCtx, NativeObject, name.NativeObject, Context.MkSymbol(value).NativeObject);
            return this;
        }
Add() [9/10]
Params Add (Symbol name, Symbol value) inline
Adds a parameter setting.
Definition at line 77 of file Params.cs.
        {
            Debug.Assert(name != null);
            Debug.Assert(value != null);
            Native.Z3_params_set_symbol(Context.nCtx, NativeObject, name.NativeObject, value.NativeObject);
            return this;
        }
Add() [10/10]
Params Add (Symbol name, uint value) inline
Adds a parameter setting.
Definition at line 44 of file Params.cs.
        {
            Debug.Assert(name != null);
            Native.Z3_params_set_uint(Context.nCtx, NativeObject, name.NativeObject, value);
            return this;
        }
ToString()
override string ToString () inline
A string representation of the parameter set.
Definition at line 140 of file Params.cs.
        {
            return Native.Z3_params_to_string(Context.nCtx, NativeObject);
        }