Z3: FuncDeclRef Class Reference
FuncDeclRef Class Reference
Function Declarations.
Public Member Functions
def as_ast (self)
def get_id (self)
def as_func_decl (self)
def name (self)
def arity (self)
def domain (self, i)
def range (self)
def kind (self)
def params (self)
def __call__ (self, *args)
Public Member Functions inherited from AstRef
def __init__ (self, ast, ctx=None)
def __del__ (self)
def __deepcopy__ (self, memo={})
def __str__ (self)
def __repr__ (self)
def __eq__ (self, other)
def __hash__ (self)
def __nonzero__ (self)
def __bool__ (self)
def sexpr (self)
def ctx_ref (self)
def eq (self, other)
def translate (self, target)
def __copy__ (self)
def hash (self)
Public Member Functions inherited from Z3PPObject
def use_pp (self)
Additional Inherited Members
Data Fields inherited from AstRef
ast
ctx
Detailed Description
Function Declarations.
Function declaration. Every constant and function have an associated declaration.
The declaration assigns a name, a sort (i.e., type), and for function
the sort (i.e., type) of each of its arguments. Note that, in Z3,
a constant is a function with 0 arguments.
Definition at line 740 of file z3py.py.
Member Function Documentation
__call__()
def __call__ (self, * args)
Create a Z3 application expression using the function `self`, and the given arguments.
The arguments must be Z3 expressions. This method assumes that
the sorts of the elements in `args` match the sorts of the
domain. Limited coercion is supported.  For example, if
args[0] is a Python integer, and the function expects a Z3
integer, then the argument is automatically converted into a
Z3 integer.
>>> f = Function('f', IntSort(), RealSort(), BoolSort())
>>> x = Int('x')
>>> y = Real('y')
>>> f(x, y)
f(x, y)
>>> f(x, x)
f(x, ToReal(x))
Definition at line 837 of file z3py.py.
     def __call__(self, *args):
         """Create a Z3 application expression using the function `self`, and the given arguments.
         The arguments must be Z3 expressions. This method assumes that
         the sorts of the elements in `args` match the sorts of the
         domain. Limited coercion is supported.  For example, if
         args[0] is a Python integer, and the function expects a Z3
         integer, then the argument is automatically converted into a
         Z3 integer.
         >>> f = Function('f', IntSort(), RealSort(), BoolSort())
         >>> x = Int('x')
         >>> y = Real('y')
         >>> f(x, y)
         f(x, y)
         >>> f(x, x)
         f(x, ToReal(x))
         """
         args = _get_args(args)
         num = len(args)
         _args = (Ast * num)()
         saved = []
         for i in range(num):
             # self.domain(i).cast(args[i]) may create a new Z3 expression,
             # then we must save in 'saved' to prevent it from being garbage collected.
             tmp = self.domain(i).cast(args[i])
             saved.append(tmp)
             _args[i] = tmp.as_ast()
         return _to_expr_ref(Z3_mk_app(self.ctx_ref(), self.ast, len(args), _args), self.ctx)
arity()
def arity (self)
Return the number of arguments of a function declaration.
If `self` is a constant, then `self.arity()` is 0.
>>> f = Function('f', IntSort(), RealSort(), BoolSort())
>>> f.arity()
2
Definition at line 768 of file z3py.py.
     def arity(self):
         """Return the number of arguments of a function declaration.
         If `self` is a constant, then `self.arity()` is 0.
         >>> f = Function('f', IntSort(), RealSort(), BoolSort())
         >>> f.arity()
         2
         """
         return int(Z3_get_arity(self.ctx_ref(), self.ast))
as_ast()
def as_ast (self)
Return a pointer to the corresponding C Z3_ast object.
Reimplemented from AstRef.
Definition at line 748 of file z3py.py.
     def as_ast(self):
         return Z3_func_decl_to_ast(self.ctx_ref(), self.ast)
Referenced by AstRef.__del__(), SeqRef.__ge__(), SeqRef.__getitem__(), SeqRef.__gt__(), BitVecRef.__invert__(), SeqRef.__le__(), CharRef.__le__(), SeqRef.__lt__(), ArithRef.__neg__(), BitVecRef.__neg__(), AlgebraicNumRef.approx(), ExprRef.arg(), IntNumRef.as_binary_string(), BitVecNumRef.as_binary_string(), RatNumRef.as_decimal(), AlgebraicNumRef.as_decimal(), IntNumRef.as_string(), RatNumRef.as_string(), BitVecNumRef.as_string(), FiniteDomainRef.as_string(), FiniteDomainNumRef.as_string(), FPRef.as_string(), FPRMRef.as_string(), FPNumRef.as_string(), SeqRef.as_string(), SeqRef.at(), ExprRef.decl(), ArrayRef.default(), RatNumRef.denominator(), AstRef.eq(), FPNumRef.exponent(), FPNumRef.exponent_as_bv(), FPNumRef.exponent_as_long(), AstRef.get_id(), SortRef.get_id(), FuncDeclRef.get_id(), ExprRef.get_id(), PatternRef.get_id(), QuantifierRef.get_id(), AstRef.hash(), AlgebraicNumRef.index(), CharRef.is_digit(), SeqRef.is_string(), SeqRef.is_string_value(), FPNumRef.isInf(), FPNumRef.isNaN(), FPNumRef.isNegative(), FPNumRef.isNormal(), FPNumRef.isPositive(), FPNumRef.isSubnormal(), FPNumRef.isZero(), ExprRef.num_args(), RatNumRef.numerator(), AlgebraicNumRef.poly(), AstRef.sexpr(), FPNumRef.sign(), FPNumRef.sign_as_bv(), FPNumRef.significand(), FPNumRef.significand_as_bv(), FPNumRef.significand_as_long(), ExprRef.sort(), BoolRef.sort(), QuantifierRef.sort(), ArithRef.sort(), BitVecRef.sort(), ArrayRef.sort(), DatatypeRef.sort(), FiniteDomainRef.sort(), FPRef.sort(), SeqRef.sort(), CharRef.to_bv(), CharRef.to_int(), and AstRef.translate().
as_func_decl()
def as_func_decl (self)
Definition at line 754 of file z3py.py.
     def as_func_decl(self):
         return self.ast
domain()
def domain (self, i)
Return the sort of the argument `i` of a function declaration.
This method assumes that `0 <= i < self.arity()`.
>>> f = Function('f', IntSort(), RealSort(), BoolSort())
>>> f.domain(0)
Int
>>> f.domain(1)
Real
Definition at line 778 of file z3py.py.
     def domain(self, i):
         """Return the sort of the argument `i` of a function declaration.
         This method assumes that `0 <= i < self.arity()`.
         >>> f = Function('f', IntSort(), RealSort(), BoolSort())
         >>> f.domain(0)
         Int
         >>> f.domain(1)
         Real
         """
         return _to_sort_ref(Z3_get_domain(self.ctx_ref(), self.ast, i), self.ctx)
Referenced by FuncDeclRef.__call__().
get_id()
def get_id (self)
Return unique identifier for object. It can be used for hash-tables and maps.
Reimplemented from AstRef.
Definition at line 751 of file z3py.py.
     def get_id(self):
         return Z3_get_ast_id(self.ctx_ref(), self.as_ast())
kind()
def kind (self)
Return the internal kind of a function declaration.
It can be used to identify Z3 built-in functions such as addition, multiplication, etc.
>>> x = Int('x')
>>> d = (x + 1).decl()
>>> d.kind() == Z3_OP_ADD
True
>>> d.kind() == Z3_OP_MUL
False
Definition at line 800 of file z3py.py.
     def kind(self):
         """Return the internal kind of a function declaration.
         It can be used to identify Z3 built-in functions such as addition, multiplication, etc.
         >>> x = Int('x')
         >>> d = (x + 1).decl()
         >>> d.kind() == Z3_OP_ADD
         True
         >>> d.kind() == Z3_OP_MUL
         False
         """
         return Z3_get_decl_kind(self.ctx_ref(), self.ast)
Referenced by ArithSortRef.is_int(), and ArithSortRef.is_real().
name()
def name (self)
Return the name of the function declaration `self`.
>>> f = Function('f', IntSort(), IntSort())
>>> f.name()
'f'
>>> isinstance(f.name(), str)
True
Definition at line 757 of file z3py.py.
     def name(self):
         """Return the name of the function declaration `self`.
         >>> f = Function('f', IntSort(), IntSort())
         >>> f.name()
         'f'
         >>> isinstance(f.name(), str)
         True
         """
         return _symbol2py(self.ctx, Z3_get_decl_name(self.ctx_ref(), self.ast))
Referenced by Datatype.__deepcopy__(), and Datatype.__repr__().
params()
def params (self)
Definition at line 813 of file z3py.py.
     def params(self):
         ctx = self.ctx
         n = Z3_get_decl_num_parameters(self.ctx_ref(), self.ast)
         result = [None for i in range(n)]
         for i in range(n):
             k = Z3_get_decl_parameter_kind(self.ctx_ref(), self.ast, i)
             if k == Z3_PARAMETER_INT:
                 result[i] = Z3_get_decl_int_parameter(self.ctx_ref(), self.ast, i)
             elif k == Z3_PARAMETER_DOUBLE:
                 result[i] = Z3_get_decl_double_parameter(self.ctx_ref(), self.ast, i)
             elif k == Z3_PARAMETER_RATIONAL:
                 result[i] = Z3_get_decl_rational_parameter(self.ctx_ref(), self.ast, i)
             elif k == Z3_PARAMETER_SYMBOL:
                 result[i] = Z3_get_decl_symbol_parameter(self.ctx_ref(), self.ast, i)
             elif k == Z3_PARAMETER_SORT:
                 result[i] = SortRef(Z3_get_decl_sort_parameter(self.ctx_ref(), self.ast, i), ctx)
             elif k == Z3_PARAMETER_AST:
                 result[i] = ExprRef(Z3_get_decl_ast_parameter(self.ctx_ref(), self.ast, i), ctx)
             elif k == Z3_PARAMETER_FUNC_DECL:
                 result[i] = FuncDeclRef(Z3_get_decl_func_decl_parameter(self.ctx_ref(), self.ast, i), ctx)
             else:
                 assert(False)
         return result
Referenced by ParamsRef.__deepcopy__(), ParamsRef.__del__(), ParamsRef.__repr__(), ParamsRef.set(), and ParamsRef.validate().
range()
def range (self)
Return the sort of the range of a function declaration.
For constants, this is the sort of the constant.
>>> f = Function('f', IntSort(), RealSort(), BoolSort())
>>> f.range()
Bool
Definition at line 790 of file z3py.py.
     def range(self):
         """Return the sort of the range of a function declaration.
         For constants, this is the sort of the constant.
         >>> f = Function('f', IntSort(), RealSort(), BoolSort())
         >>> f.range()
         Bool
         """
         return _to_sort_ref(Z3_get_range(self.ctx_ref(), self.ast), self.ctx)
Referenced by FuncDeclRef.__call__(), and FuncDeclRef.params().