Z3: OptimizeObjective Class Reference
OptimizeObjective Class Reference
Optimize.
Public Member Functions
def __init__ (self, opt, value, is_max)
def lower (self)
def upper (self)
def lower_values (self)
def upper_values (self)
def value (self)
def __str__ (self)
Detailed Description
Optimize.
Definition at line 7890 of file z3py.py.
Constructor & Destructor Documentation
__init__()
def __init__ (self, opt, value, is_max)
Definition at line 7891 of file z3py.py.
     def __init__(self, opt, value, is_max):
         self._opt = opt
         self._value = value
         self._is_max = is_max
Member Function Documentation
__str__()
def __str__ (self)
Definition at line 7918 of file z3py.py.
     def __str__(self):
         return "%s:%s" % (self._value, self._is_max)
lower()
def lower (self)
Definition at line 7896 of file z3py.py.
     def lower(self):
         opt = self._opt
         return _to_expr_ref(Z3_optimize_get_lower(opt.ctx.ref(), opt.optimize, self._value), opt.ctx)
Referenced by OptimizeObjective.value().
lower_values()
def lower_values (self)
Definition at line 7904 of file z3py.py.
     def lower_values(self):
         opt = self._opt
         return AstVector(Z3_optimize_get_lower_as_vector(opt.ctx.ref(), opt.optimize, self._value), opt.ctx)
upper()
def upper (self)
Definition at line 7900 of file z3py.py.
     def upper(self):
         opt = self._opt
         return _to_expr_ref(Z3_optimize_get_upper(opt.ctx.ref(), opt.optimize, self._value), opt.ctx)
Referenced by OptimizeObjective.value().
upper_values()
def upper_values (self)
Definition at line 7908 of file z3py.py.
     def upper_values(self):
         opt = self._opt
         return AstVector(Z3_optimize_get_upper_as_vector(opt.ctx.ref(), opt.optimize, self._value), opt.ctx)
value()
def value (self)
Definition at line 7912 of file z3py.py.
     def value(self):
         if self._is_max:
             return self.upper()
         else:
             return self.lower()
Referenced by FuncEntry.as_list().