Z3: UserPropagateBase Class Reference
UserPropagateBase Class Reference
Public Member Functions
def __init__ (self, s, ctx=None)
def __del__ (self)
def ctx (self)
def ctx_ref (self)
def add_fixed (self, fixed)
def add_created (self, created)
def add_final (self, final)
def add_eq (self, eq)
def add_diseq (self, diseq)
def add_decide (self, decide)
def push (self)
def pop (self, num_scopes)
def fresh (self, new_ctx)
def add (self, e)
def next_split (self, t, idx, phase)
def propagate (self, e, ids, eqs=[])
def conflict (self, deps=[], eqs=[])
Data Fields
solver
fresh_ctx
cb
id
fixed
final
eq
diseq
created
decide
Detailed Description
Definition at line 11467 of file z3py.py.
Constructor & Destructor Documentation
__init__()
def __init__ (self, s, ctx = None)
Definition at line 11476 of file z3py.py.
     def __init__(self, s, ctx=None):
         assert s is None or ctx is None
         ensure_prop_closures()
         self.solver = s
         self._ctx = None
         self.fresh_ctx = None
         self.cb = None
         self.id = _prop_closures.insert(self)
         self.fixed = None
         self.final = None
         self.eq = None
         self.diseq = None
         self.created = None
         if ctx:
             self.fresh_ctx = ctx
         if s:
             Z3_solver_propagate_init(self.ctx_ref(),
                                      s.solver,
                                      ctypes.c_void_p(self.id),
                                      _user_prop_push,
                                      _user_prop_pop,
                                      _user_prop_fresh)
__del__()
def __del__ (self)
Definition at line 11499 of file z3py.py.
     def __del__(self):
         if self._ctx:
             self._ctx.ctx = None
Member Function Documentation
add()
def add (self, e)
Definition at line 11563 of file z3py.py.
     def add(self, e):
         assert not self._ctx
         if self.solver:
             Z3_solver_propagate_register(self.ctx_ref(), self.solver.solver, e.ast)
         else:
             Z3_solver_propagate_register_cb(self.ctx_ref(), ctypes.c_void_p(self.cb), e.ast)
add_created()
def add_created (self, created)
Definition at line 11519 of file z3py.py.
     def add_created(self, created):
         assert not self.created
         assert not self._ctx
         if self.solver:
             Z3_solver_propagate_created(self.ctx_ref(), self.solver.solver, _user_prop_created)
         self.created = created
add_decide()
def add_decide (self, decide)
Definition at line 11547 of file z3py.py.
     def add_decide(self, decide):
         assert not self.decide
         assert not self._ctx
         if self.solver:
             Z3_solver_propagate_decide(self.ctx_ref(), self.solver.solver, _user_prop_decide)
         self.decide = decide
add_diseq()
def add_diseq (self, diseq)
Definition at line 11540 of file z3py.py.
     def add_diseq(self, diseq):
         assert not self.diseq
         assert not self._ctx
         if self.solver:
             Z3_solver_propagate_diseq(self.ctx_ref(), self.solver.solver, _user_prop_diseq)
         self.diseq = diseq
add_eq()
def add_eq (self, eq)
Definition at line 11533 of file z3py.py.
     def add_eq(self, eq):
         assert not self.eq
         assert not self._ctx
         if self.solver:
             Z3_solver_propagate_eq(self.ctx_ref(), self.solver.solver, _user_prop_eq)
         self.eq = eq
add_final()
def add_final (self, final)
Definition at line 11526 of file z3py.py.
     def add_final(self, final):
         assert not self.final
         assert not self._ctx
         if self.solver:
             Z3_solver_propagate_final(self.ctx_ref(), self.solver.solver, _user_prop_final)
         self.final = final
add_fixed()
def add_fixed (self, fixed)
Definition at line 11512 of file z3py.py.
     def add_fixed(self, fixed):
         assert not self.fixed
         assert not self._ctx
         if self.solver:
             Z3_solver_propagate_fixed(self.ctx_ref(), self.solver.solver, _user_prop_fixed)
         self.fixed = fixed
conflict()
def conflict (self, deps = [], eqs = [])
Definition at line 11589 of file z3py.py.
     def conflict(self, deps = [], eqs = []):
         self.propagate(BoolVal(False, self.ctx()), deps, eqs)
ctx()
def ctx (self)
Definition at line 11503 of file z3py.py.
     def ctx(self):
         if self.fresh_ctx:
             return self.fresh_ctx
         else:
             return self.solver.ctx
Referenced by UserPropagateBase.conflict(), and UserPropagateBase.ctx_ref().
ctx_ref()
def ctx_ref (self)
Definition at line 11509 of file z3py.py.
     def ctx_ref(self):
         return self.ctx().ref()
Referenced by UserPropagateBase.add(), UserPropagateBase.add_created(), UserPropagateBase.add_decide(), UserPropagateBase.add_diseq(), UserPropagateBase.add_eq(), UserPropagateBase.add_final(), UserPropagateBase.add_fixed(), and UserPropagateBase.next_split().
fresh()
def fresh (self, new_ctx)
Definition at line 11560 of file z3py.py.
     def fresh(self, new_ctx):
         raise Z3Exception("fresh needs to be overwritten")
next_split()
def next_split (self, t, idx, phase)
Definition at line 11575 of file z3py.py.
     def next_split(self, t, idx, phase):
         Z3_solver_next_split(self.ctx_ref(), ctypes.c_void_p(self.cb), t.ast, idx, phase)
pop()
def pop (self, num_scopes)
Definition at line 11557 of file z3py.py.
     def pop(self, num_scopes):
         raise Z3Exception("pop needs to be overwritten")
propagate()
def propagate (self, e, ids, eqs = [])
Definition at line 11581 of file z3py.py.
     def propagate(self, e, ids, eqs=[]):
         _ids, num_fixed = _to_ast_array(ids)
         num_eqs = len(eqs)
         _lhs, _num_lhs = _to_ast_array([x for x, y in eqs])
         _rhs, _num_rhs = _to_ast_array([y for x, y in eqs])
         Z3_solver_propagate_consequence(e.ctx.ref(), ctypes.c_void_p(
             self.cb), num_fixed, _ids, num_eqs, _lhs, _rhs, e.ast)
Referenced by UserPropagateBase.conflict().
push()
def push (self)
Definition at line 11554 of file z3py.py.
     def push(self):
         raise Z3Exception("push needs to be overwritten")
Field Documentation
cb
cb
Definition at line 11482 of file z3py.py.
Referenced by UserPropagateBase.add(), UserPropagateBase.next_split(), and UserPropagateBase.propagate().
created
created
Definition at line 11488 of file z3py.py.
Referenced by UserPropagateBase.add_created().
decide
decide
Definition at line 11552 of file z3py.py.
Referenced by UserPropagateBase.add_decide().
diseq
diseq
Definition at line 11487 of file z3py.py.
Referenced by UserPropagateBase.add_diseq().
eq
eq
Definition at line 11486 of file z3py.py.
Referenced by AstRef.__eq__(), UserPropagateBase.add_eq(), SortRef.cast(), and BoolSortRef.cast().
final
final
Definition at line 11485 of file z3py.py.
Referenced by UserPropagateBase.add_final().
fixed
fixed
Definition at line 11484 of file z3py.py.
Referenced by UserPropagateBase.add_fixed().
fresh_ctx
fresh_ctx
Definition at line 11481 of file z3py.py.
Referenced by UserPropagateBase.ctx().
id
id
Definition at line 11483 of file z3py.py.
solver
solver
Definition at line 11479 of file z3py.py.
Referenced by UserPropagateBase.add(), UserPropagateBase.add_created(), UserPropagateBase.add_decide(), UserPropagateBase.add_diseq(), UserPropagateBase.add_eq(), UserPropagateBase.add_final(), UserPropagateBase.add_fixed(), and UserPropagateBase.ctx().