Z3: Solver Class Reference
Solver Class Reference
Public Member Functions
String getHelp ()
void setParameters (Params value)
ParamDescrs getParameterDescriptions ()
int getNumScopes ()
void push ()
void pop ()
void pop (int n)
void reset ()
void interrupt ()
void add (Expr< BoolSort >... constraints)
void assertAndTrack (Expr< BoolSort >[] constraints, Expr< BoolSort >[] ps)
void assertAndTrack (Expr< BoolSort > constraint, Expr< BoolSort > p)
void fromFile (String file)
Load solver assertions from a file.
void fromString (String str)
Load solver assertions from a string.
int getNumAssertions ()
BoolExpr[] getAssertions ()
final Status check (Expr< BoolSort >... assumptions)
Status check ()
Status getConsequences (Expr< BoolSort >[] assumptions, Expr<?>[] variables, List< Expr< BoolSort > > consequences)
Model getModel ()
Expr<?> getProof ()
BoolExpr[] getUnsatCore ()
String getReasonUnknown ()
Solver translate (Context ctx)
Statistics getStatistics ()
String toString ()
Additional Inherited Members
Static Public Member Functions inherited from Z3Object
static long[] arrayToNative (Z3Object[] a)
static int arrayLength (Z3Object[] a)
Detailed Description
Solvers.
Definition at line 30 of file Solver.java.
Member Function Documentation
add()
void add (Expr< BoolSort >... constraints) inline
Assert a multiple constraints into the solver.
Exceptions
Z3Exception
Definition at line 128 of file Solver.java.
    {
        getContext().checkContextMatch(constraints);
        for (Expr<BoolSort> a : constraints)
        {
            Native.solverAssert(getContext().nCtx(), getNativeObject(),
                    a.getNativeObject());
        }
    }
Referenced by Solver.__iadd__().
assertAndTrack() [1/2]
void assertAndTrack (Expr< BoolSort > constraint, Expr< BoolSort > p) inline
Assert a constraint into the solver, and track it (in the unsat) core using the Boolean constant p.
Remarks: This API is an alternative to check with assumptions for extracting unsat cores. Both APIs can be used in the same solver. The unsat core will contain a combination of the Boolean variables provided using assertAndTrack and the Boolean literals provided using check with assumptions.
Definition at line 180 of file Solver.java.
    {
        getContext().checkContextMatch(constraint);
        getContext().checkContextMatch(p);
        Native.solverAssertAndTrack(getContext().nCtx(), getNativeObject(),
                constraint.getNativeObject(), p.getNativeObject());
    }
assertAndTrack() [2/2]
void assertAndTrack (Expr< BoolSort >[] constraints, Expr< BoolSort >[] ps) inline
Assert multiple constraints into the solver, and track them (in the unsat) core using the Boolean constants in ps.
Remarks: This API is an alternative to check() with assumptions for extracting unsat cores. Both APIs can be used in the same solver. The unsat core will contain a combination of the Boolean variables provided using #assertAndTrack and the Boolean literals provided using check() with assumptions.
Definition at line 153 of file Solver.java.
    {
        getContext().checkContextMatch(constraints);
        getContext().checkContextMatch(ps);
        if (constraints.length != ps.length) {
            throw new Z3Exception("Argument size mismatch");
        }
        for (int i = 0; i < constraints.length; i++) {
            Native.solverAssertAndTrack(getContext().nCtx(), getNativeObject(),
                constraints[i].getNativeObject(), ps[i].getNativeObject());
        }
    }
check() [1/2]
Status check () inline
Checks whether the assertions in the solver are consistent or not. Remarks:
See also
#getModel
#getUnsatCore
#getProof
Definition at line 258 of file Solver.java.
    {
        return check((Expr[]) null);
    }
check() [2/2]
final Status check (Expr< BoolSort >... assumptions) inline
Checks whether the assertions in the solver are consistent or not. Remarks:
See also
#getModel
#getUnsatCore
#getProof
Definition at line 236 of file Solver.java.
    {
        Z3_lbool r;
        if (assumptions == null) {
            r = Z3_lbool.fromInt(Native.solverCheck(getContext().nCtx(),
                getNativeObject()));
        } else {
            r = Z3_lbool.fromInt(Native.solverCheckAssumptions(getContext()
                .nCtx(), getNativeObject(), assumptions.length, AST
                .arrayToNative(assumptions)));
        }
        return lboolToStatus(r);
    }
fromFile()
void fromFile (String file) inline
Load solver assertions from a file.
Definition at line 192 of file Solver.java.
    {
        Native.solverFromFile(getContext().nCtx(), getNativeObject(), file);
    }
fromString()
void fromString (String str) inline
Load solver assertions from a string.
Definition at line 200 of file Solver.java.
    {
        Native.solverFromString(getContext().nCtx(), getNativeObject(), str);
    }
getAssertions()
BoolExpr[] getAssertions () inline
The set of asserted formulas.
Exceptions
Z3Exception
Definition at line 222 of file Solver.java.
    {
        ASTVector assrts = new ASTVector(getContext(), Native.solverGetAssertions(getContext().nCtx(), getNativeObject()));
        return assrts.ToBoolExprArray();
    }
getConsequences()
Status getConsequences (Expr< BoolSort >[] assumptions, Expr<?>[] variables, List< Expr< BoolSort > > consequences) inline
Retrieve fixed assignments to the set of variables in the form of consequences. Each consequence is an implication of the form
  relevant-assumptions Implies variable = value
where the relevant assumptions is a subset of the assumptions that are passed in and the equality on the right side of the implication indicates how a variable is fixed.
Definition at line 274 of file Solver.java.
    {
        ASTVector result = new ASTVector(getContext());
        ASTVector asms = new ASTVector(getContext());
        ASTVector vars = new ASTVector(getContext());
        for (Expr<BoolSort> asm : assumptions) asms.push(asm);
        for (Expr<?> v : variables) vars.push(v);
        int r = Native.solverGetConsequences(getContext().nCtx(), getNativeObject(), asms.getNativeObject(), vars.getNativeObject(), result.getNativeObject());
        for (int i = 0; i < result.size(); ++i) consequences.add((BoolExpr) Expr.create(getContext(), result.get(i).getNativeObject()));
        return lboolToStatus(Z3_lbool.fromInt(r));
    }
getHelp()
String getHelp () inline
A string that describes all available solver parameters.
Definition at line 34 of file Solver.java.
    {
        return Native.solverGetHelp(getContext().nCtx(), getNativeObject());
    }
getModel()
Model getModel () inline
The model of the last Check. Remarks: The result is null if Check was not invoked before, if its results was not SATISFIABLE, or if model production is not enabled.
Exceptions
Z3Exception
Definition at line 296 of file Solver.java.
    {
        long x = Native.solverGetModel(getContext().nCtx(), getNativeObject());
        if (x == 0) {
            return null;
        } else {
            return new Model(getContext(), x);
        }
    }
getNumAssertions()
int getNumAssertions () inline
The number of assertions in the solver.
Exceptions
Z3Exception
Definition at line 211 of file Solver.java.
    {
        ASTVector assrts = new ASTVector(getContext(), Native.solverGetAssertions(getContext().nCtx(), getNativeObject()));
        return assrts.size();
    }
getNumScopes()
int getNumScopes () inline
The current number of backtracking points (scopes).
See also
#pop
#push
Definition at line 67 of file Solver.java.
    {
        return Native
                .solverGetNumScopes(getContext().nCtx(), getNativeObject());
    }
getParameterDescriptions()
ParamDescrs getParameterDescriptions () inline
Retrieves parameter descriptions for solver.
Exceptions
Z3Exception
Definition at line 56 of file Solver.java.
    {
        return new ParamDescrs(getContext(), Native.solverGetParamDescrs(
                getContext().nCtx(), getNativeObject()));
    }
getProof()
Expr<?> getProof () inline
The proof of the last Check. Remarks: The result is null if Check was not invoked before, if its results was not UNSATISFIABLE, or if proof production is disabled.
Exceptions
Z3Exception
Definition at line 315 of file Solver.java.
    {
        long x = Native.solverGetProof(getContext().nCtx(), getNativeObject());
        if (x == 0) {
            return null;
        } else {
            return Expr.create(getContext(), x);
        }
    }
getReasonUnknown()
String getReasonUnknown () inline
A brief justification of why the last call to Check returned UNKNOWN.
Definition at line 345 of file Solver.java.
    {
        return Native.solverGetReasonUnknown(getContext().nCtx(),
                getNativeObject());
    }
getStatistics()
Statistics getStatistics () inline
Solver statistics.
Exceptions
Z3Exception
Definition at line 364 of file Solver.java.
    {
        return new Statistics(getContext(), Native.solverGetStatistics(
                getContext().nCtx(), getNativeObject()));
    }
getUnsatCore()
BoolExpr[] getUnsatCore () inline
The unsat core of the last Check. Remarks: The unsat core is a subset of Assertions The result is empty if Check was not invoked before, if its results was not UNSATISFIABLE, or if core production is disabled.
Exceptions
Z3Exception
Definition at line 334 of file Solver.java.
    {
        ASTVector core = new ASTVector(getContext(), Native.solverGetUnsatCore(getContext().nCtx(), getNativeObject()));
        return core.ToBoolExprArray();
    }
interrupt()
void interrupt () inline
Interrupt the execution of the solver object. Remarks: This ensures that the interrupt applies only to the given solver object and it applies only if it is running.
Definition at line 118 of file Solver.java.
    {
        Native.solverInterrupt(getContext().nCtx(), getNativeObject());
    }
pop() [1/2]
void pop () inline
Backtracks one backtracking point. Remarks: .
Definition at line 86 of file Solver.java.
    {
        pop(1);
    }
Referenced by Solver.__exit__().
pop() [2/2]
void pop (int n) inline
Backtracks n backtracking points. Remarks: Note that an exception is thrown if n is not smaller than NumScopes
See also
#push
Definition at line 98 of file Solver.java.
    {
        Native.solverPop(getContext().nCtx(), getNativeObject(), n);
    }
Referenced by Solver.__exit__().
push()
void push () inline
Creates a backtracking point.
See also
#pop
Definition at line 77 of file Solver.java.
    {
        Native.solverPush(getContext().nCtx(), getNativeObject());
    }
Referenced by Solver.__enter__().
reset()
void reset () inline
Resets the Solver. Remarks: This removes all assertions from the solver.
Definition at line 108 of file Solver.java.
    {
        Native.solverReset(getContext().nCtx(), getNativeObject());
    }
setParameters()
void setParameters (Params value) inline
Sets the solver parameters.
Exceptions
Z3Exception
Definition at line 44 of file Solver.java.
    {
        getContext().checkContextMatch(value);
        Native.solverSetParams(getContext().nCtx(), getNativeObject(),
                value.getNativeObject());
    }
toString()
String toString () inline
A string representation of the solver.
Definition at line 374 of file Solver.java.
    {
        return Native
                .solverToString(getContext().nCtx(), getNativeObject());
    }
translate()
Solver translate (Context ctx) inline
Create a clone of the current solver with respect toctx.
Definition at line 354 of file Solver.java.
    {
        return new Solver(ctx, Native.solverTranslate(getContext().nCtx(), getNativeObject(), ctx.nCtx()));
    }
Referenced by AstRef.__copy__(), Goal.__copy__(), AstVector.__copy__(), FuncInterp.__copy__(), ModelRef.__copy__(), Goal.__deepcopy__(), AstVector.__deepcopy__(), FuncInterp.__deepcopy__(), and ModelRef.__deepcopy__().