Z3: IntNumRef Class Reference
IntNumRef Class Reference
Public Member Functions
def as_long (self)
def as_string (self)
def as_binary_string (self)
Public Member Functions inherited from ArithRef
def sort (self)
def is_int (self)
def is_real (self)
def __add__ (self, other)
def __radd__ (self, other)
def __mul__ (self, other)
def __rmul__ (self, other)
def __sub__ (self, other)
def __rsub__ (self, other)
def __pow__ (self, other)
def __rpow__ (self, other)
def __div__ (self, other)
def __truediv__ (self, other)
def __rdiv__ (self, other)
def __rtruediv__ (self, other)
def __mod__ (self, other)
def __rmod__ (self, other)
def __neg__ (self)
def __pos__ (self)
def __le__ (self, other)
def __lt__ (self, other)
def __gt__ (self, other)
def __ge__ (self, other)
Public Member Functions inherited from ExprRef
def as_ast (self)
def get_id (self)
def sort_kind (self)
def __eq__ (self, other)
def __hash__ (self)
def __ne__ (self, other)
def params (self)
def decl (self)
def num_args (self)
def arg (self, idx)
def children (self)
def from_string (self, s)
def serialize (self)
Public Member Functions inherited from AstRef
def __init__ (self, ast, ctx=None)
def __del__ (self)
def __deepcopy__ (self, memo={})
def __str__ (self)
def __repr__ (self)
def __nonzero__ (self)
def __bool__ (self)
def sexpr (self)
def ctx_ref (self)
def eq (self, other)
def translate (self, target)
def __copy__ (self)
def hash (self)
Public Member Functions inherited from Z3PPObject
def use_pp (self)
Additional Inherited Members
Data Fields inherited from AstRef
ast
ctx
Detailed Description
Integer values.
Definition at line 2944 of file z3py.py.
Member Function Documentation
as_binary_string()
def as_binary_string (self)
Return a Z3 integer numeral as a Python binary string.
>>> v = IntVal(10)
>>> v.as_binary_string()
'1010'
Definition at line 2968 of file z3py.py.
     def as_binary_string(self):
         """Return a Z3 integer numeral as a Python binary string.
         >>> v = IntVal(10)
         >>> v.as_binary_string()
         '1010'
         """
         return Z3_get_numeral_binary_string(self.ctx_ref(), self.as_ast())
as_long()
def as_long (self)
Return a Z3 integer numeral as a Python long (bignum) numeral.
>>> v = IntVal(1)
>>> v + 1
1 + 1
>>> v.as_long() + 1
2
Definition at line 2947 of file z3py.py.
     def as_long(self):
         """Return a Z3 integer numeral as a Python long (bignum) numeral.
         >>> v = IntVal(1)
         >>> v + 1
         1 + 1
         >>> v.as_long() + 1
         2
         """
         if z3_debug():
             _z3_assert(self.is_int(), "Integer value expected")
         return int(self.as_string())
Referenced by BitVecNumRef.as_signed_long().
as_string()
def as_string (self)
Return a Z3 integer numeral as a Python string.
>>> v = IntVal(100)
>>> v.as_string()
'100'
Definition at line 2960 of file z3py.py.
     def as_string(self):
         """Return a Z3 integer numeral as a Python string.
         >>> v = IntVal(100)
         >>> v.as_string()
         '100'
         """
         return Z3_get_numeral_string(self.ctx_ref(), self.as_ast())
Referenced by IntNumRef.as_long(), BitVecNumRef.as_long(), and FiniteDomainNumRef.as_long().