Z3: exception Class Reference
exception Class Reference
Exception used to sign API usage errors.
Public Member Functions
exception (char const *msg)
char const * msg () const
Friends
std::ostream & operator<< (std::ostream &out, exception const &e)
Detailed Description
Exception used to sign API usage errors.
Definition at line 80 of file z3++.h.
Constructor & Destructor Documentation
exception (char const * msg) inline
Definition at line 83 of file z3++.h.
Referenced by context::check_error(), context::check_parser_error(), model::eval(), expr::get_numeral_int(), expr::get_numeral_int64(), expr::get_numeral_uint(), expr::get_numeral_uint64(), and z3::par_or().
 :m_msg(msg) {}
Member Function Documentation
char const* msg () const inline
Definition at line 84 of file z3++.h.
Referenced by z3::operator<<().
 { return m_msg.c_str(); }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, exception const & e) friend
Definition at line 87 of file z3++.h.
Referenced by model::add_const_interp(), goal::as_expr(), apply_result::convert_model(), stats::double_value(), ast::hash(), exception::msg(), solver::proof(), params::set(), optimize::statistics(), and symbol::to_int().
 { out << e.msg(); return out; }