Z3: AST Class Reference
AST Class Reference
Public Member Functions
boolean equals (Object o)
int compareTo (Object other)
int hashCode ()
int getId ()
AST translate (Context ctx)
Z3_ast_kind getASTKind ()
boolean isExpr ()
boolean isApp ()
boolean isVar ()
boolean isQuantifier ()
boolean isSort ()
boolean isFuncDecl ()
String toString ()
String getSExpr ()
Public Member Functions inherited from Z3Object
void dispose ()
Public Member Functions inherited from IDisposable
void dispose ()
Additional Inherited Members
Protected Member Functions inherited from Z3Object
void finalize ()
Detailed Description
The abstract syntax tree (AST) class.
Definition at line 25 of file AST.java.
Member Function Documentation
int compareTo (Object other) inline
Object Comparison.
Parameters
other Another AST
Returns
Negative if the object should be sorted before
other
, positive if after else zero.
Exceptions
Z3Exception on error
Definition at line 60 of file AST.java.
     {
         if (other == null)
             return 1;
         AST oAST = null;
         try
         {
             oAST = AST.class.cast(other);
         } catch (ClassCastException e)
         {
             return 1;
         }
         if (getId() < oAST.getId())
             return -1;
         else if (getId() > oAST.getId())
             return +1;
         else
             return 0;
     }
boolean equals (Object o) inline
Object comparison.
Parameters
o another AST
Definition at line 32 of file AST.java.
     {
         AST casted = null;
         try
         {
             casted = AST.class.cast(o);
         } catch (ClassCastException e)
         {
             return false;
         }
         return
             (this == casted) ||
             (this != null) &&
             (casted != null) &&
             (getContext().nCtx() == casted.getContext().nCtx()) &&
             (Native.isEqAst(getContext().nCtx(), getNativeObject(), casted.getNativeObject()));
 }
Z3_ast_kind getASTKind () inline
The kind of the AST.
Exceptions
Z3Exception on error
Definition at line 127 of file AST.java.
Referenced by AST.isApp(), AST.isExpr(), AST.isFuncDecl(), AST.isQuantifier(), AST.isSort(), and AST.isVar().
     {
         return Z3_ast_kind.fromInt(Native.getAstKind(getContext().nCtx(),
                 getNativeObject()));
     }
int getId () inline
A unique identifier for the AST (unique among all ASTs).
Exceptions
Z3Exception on error
Definition at line 101 of file AST.java.
Referenced by AST.compareTo().
     {
         return Native.getAstId(getContext().nCtx(), getNativeObject());
     }
String getSExpr () inline
A string representation of the AST in s-expression notation.
Definition at line 215 of file AST.java.
     {
         return Native.astToString(getContext().nCtx(), getNativeObject());
     }
int hashCode () inline
The AST's hash code.
Returns
A hash code
Definition at line 87 of file AST.java.
     {
         int r = 0;
         try {
             Native.getAstHash(getContext().nCtx(), getNativeObject());
         }
         catch (Z3Exception ex) {}
         return r;
     }
boolean isApp () inline
Indicates whether the AST is an application
Returns
a boolean
Exceptions
Z3Exception on error
Definition at line 157 of file AST.java.
Referenced by Expr.isAdd(), Expr.isAnd(), Expr.isArithmeticNumeral(), Expr.isArrayMap(), Expr.isAsArray(), Expr.isBVAdd(), Expr.isBVAND(), Expr.isBVBitOne(), Expr.isBVBitZero(), Expr.isBVCarry(), Expr.isBVComp(), Expr.isBVConcat(), Expr.isBVExtract(), Expr.isBVMul(), Expr.isBVNAND(), Expr.isBVNOR(), Expr.isBVNOT(), Expr.isBVNumeral(), Expr.isBVOR(), Expr.isBVReduceAND(), Expr.isBVReduceOR(), Expr.isBVRepeat(), Expr.isBVRotateLeft(), Expr.isBVRotateLeftExtended(), Expr.isBVRotateRight(), Expr.isBVRotateRightExtended(), Expr.isBVSDiv(), Expr.isBVSGE(), Expr.isBVSGT(), Expr.isBVShiftLeft(), Expr.isBVShiftRightArithmetic(), Expr.isBVShiftRightLogical(), Expr.isBVSignExtension(), Expr.isBVSLE(), Expr.isBVSLT(), Expr.isBVSMod(), Expr.isBVSRem(), Expr.isBVSub(), Expr.isBVToInt(), Expr.isBVUDiv(), Expr.isBVUGE(), Expr.isBVUGT(), Expr.isBVULE(), Expr.isBVULT(), Expr.isBVUMinus(), Expr.isBVURem(), Expr.isBVXNOR(), Expr.isBVXOR(), Expr.isBVXOR3(), Expr.isBVZeroExtension(), Expr.isConst(), Expr.isConstantArray(), Expr.isDefaultArray(), Expr.isDistinct(), Expr.isDiv(), Expr.isEmptyRelation(), Expr.isEq(), Expr.isFalse(), Expr.isFiniteDomainLT(), Expr.isGE(), Expr.isGT(), Expr.isIDiv(), Expr.isIff(), Expr.isImplies(), Expr.isIntToBV(), Expr.isIntToReal(), Expr.isIsEmptyRelation(), Expr.isITE(), Expr.isLabel(), Expr.isLabelLit(), Expr.isLE(), Expr.isLT(), Expr.isModulus(), Expr.isMul(), Expr.isNot(), Expr.isOEQ(), Expr.isOr(), Expr.isProofAndElimination(), Expr.isProofApplyDef(), Expr.isProofAsserted(), Expr.isProofCNFStar(), Expr.isProofCommutativity(), Expr.isProofDefAxiom(), Expr.isProofDefIntro(), Expr.isProofDER(), Expr.isProofDistributivity(), Expr.isProofElimUnusedVars(), Expr.isProofGoal(), Expr.isProofHypothesis(), Expr.isProofIFFFalse(), Expr.isProofIFFOEQ(), Expr.isProofIFFTrue(), Expr.isProofLemma(), Expr.isProofModusPonens(), Expr.isProofModusPonensOEQ(), Expr.isProofMonotonicity(), Expr.isProofNNFNeg(), Expr.isProofNNFPos(), Expr.isProofNNFStar(), Expr.isProofOrElimination(), Expr.isProofPullQuant(), Expr.isProofPullQuantStar(), Expr.isProofPushQuant(), Expr.isProofQuantInst(), Expr.isProofQuantIntro(), Expr.isProofReflexivity(), Expr.isProofRewrite(), Expr.isProofRewriteStar(), Expr.isProofSkolemize(), Expr.isProofSymmetry(), Expr.isProofTheoryLemma(), Expr.isProofTransitivity(), Expr.isProofTransitivityStar(), Expr.isProofTrue(), Expr.isProofUnitResolution(), Expr.isRealIsInt(), Expr.isRealToInt(), Expr.isRelationalJoin(), Expr.isRelationClone(), Expr.isRelationComplement(), Expr.isRelationFilter(), Expr.isRelationNegationFilter(), Expr.isRelationProject(), Expr.isRelationRename(), Expr.isRelationSelect(), Expr.isRelationStore(), Expr.isRelationUnion(), Expr.isRelationWiden(), Expr.isRemainder(), FPRMNum.isRNA(), FPRMNum.isRNE(), FPRMNum.isRoundNearestTiesToAway(), FPRMNum.isRoundNearestTiesToEven(), FPRMNum.isRoundTowardNegative(), FPRMNum.isRoundTowardPositive(), FPRMNum.isRoundTowardZero(), FPRMNum.isRTN(), FPRMNum.isRTP(), FPRMNum.isRTZ(), Expr.isSelect(), Expr.isSetComplement(), Expr.isSetDifference(), Expr.isSetIntersect(), Expr.isSetSubset(), Expr.isSetUnion(), Expr.isStore(), Expr.isSub(), Expr.isTrue(), Expr.isUMinus(), Expr.isXor(), and Expr.update().
     {
         return this.getASTKind() == Z3_ast_kind.Z3_APP_AST;
     }
boolean isExpr () inline
Indicates whether the AST is an Expr
Exceptions
Z3Exception on error
Z3Exception on error
Definition at line 138 of file AST.java.
Referenced by Expr.isBool().
     {
         switch (getASTKind())
         {
         case Z3_APP_AST:
         case Z3_NUMERAL_AST:
         case Z3_QUANTIFIER_AST:
         case Z3_VAR_AST:
             return true;
         default:
             return false;
         }
     }
boolean isFuncDecl () inline
Indicates whether the AST is a FunctionDeclaration
Definition at line 193 of file AST.java.
     {
         return this.getASTKind() == Z3_ast_kind.Z3_FUNC_DECL_AST;
     }
boolean isQuantifier () inline
Indicates whether the AST is a Quantifier
Returns
a boolean
Exceptions
Z3Exception on error
Definition at line 177 of file AST.java.
     {
         return this.getASTKind() == Z3_ast_kind.Z3_QUANTIFIER_AST;
     }
boolean isSort () inline
Indicates whether the AST is a Sort
Definition at line 185 of file AST.java.
     {
         return this.getASTKind() == Z3_ast_kind.Z3_SORT_AST;
     }
boolean isVar () inline
Indicates whether the AST is a BoundVariable.
Returns
a boolean
Exceptions
Z3Exception on error
Definition at line 167 of file AST.java.
Referenced by Expr.getIndex().
     {
         return this.getASTKind() == Z3_ast_kind.Z3_VAR_AST;
     }
String toString () inline
A string representation of the AST.
Definition at line 201 of file AST.java.
     {
         try
         {
             return Native.astToString(getContext().nCtx(), getNativeObject());
         } catch (Z3Exception e)
         {
             return "Z3Exception: " + e.getMessage();
         }
     }
AST translate (Context ctx) inline
Translates (copies) the AST to the Context
ctx
.
Parameters
ctx A context
Returns
A copy of the AST which is associated with
ctx
Exceptions
Z3Exception on error
Definition at line 113 of file AST.java.
     {
         if (getContext() == ctx)
             return this;
         else
             return new AST(ctx, Native.translate(getContext().nCtx(),
                     getNativeObject(), ctx.nCtx()));
     }