Z3: BitVecRef Class Reference
BitVecRef Class Reference
Public Member Functions
def sort (self)
def size (self)
def __add__ (self, other)
def __radd__ (self, other)
def __mul__ (self, other)
def __rmul__ (self, other)
def __sub__ (self, other)
def __rsub__ (self, other)
def __or__ (self, other)
def __ror__ (self, other)
def __and__ (self, other)
def __rand__ (self, other)
def __xor__ (self, other)
def __rxor__ (self, other)
def __pos__ (self)
def __neg__ (self)
def __invert__ (self)
def __div__ (self, other)
def __truediv__ (self, other)
def __rdiv__ (self, other)
def __rtruediv__ (self, other)
def __mod__ (self, other)
def __rmod__ (self, other)
def __le__ (self, other)
def __lt__ (self, other)
def __gt__ (self, other)
def __ge__ (self, other)
def __rshift__ (self, other)
def __lshift__ (self, other)
def __rrshift__ (self, other)
def __rlshift__ (self, other)
Public Member Functions inherited from ExprRef
def as_ast (self)
def get_id (self)
def sort_kind (self)
def __eq__ (self, other)
def __hash__ (self)
def __ne__ (self, other)
def params (self)
def decl (self)
def num_args (self)
def arg (self, idx)
def children (self)
def from_string (self, s)
def serialize (self)
Public Member Functions inherited from AstRef
def __init__ (self, ast, ctx=None)
def __del__ (self)
def __deepcopy__ (self, memo={})
def __str__ (self)
def __repr__ (self)
def __nonzero__ (self)
def __bool__ (self)
def sexpr (self)
def ctx_ref (self)
def eq (self, other)
def translate (self, target)
def __copy__ (self)
def hash (self)
Public Member Functions inherited from Z3PPObject
def use_pp (self)
Additional Inherited Members
Data Fields inherited from AstRef
ast
ctx
Detailed Description
Bit-vector expressions.
Definition at line 3478 of file z3py.py.
Member Function Documentation
__add__()
def __add__ (self, other)
Create the Z3 expression `self + other`.
>>> x = BitVec('x', 32)
>>> y = BitVec('y', 32)
>>> x + y
x + y
>>> (x + y).sort()
BitVec(32)
Definition at line 3503 of file z3py.py.
     def __add__(self, other):
         """Create the Z3 expression `self + other`.
         >>> x = BitVec('x', 32)
         >>> y = BitVec('y', 32)
         >>> x + y
         x + y
         >>> (x + y).sort()
         BitVec(32)
         """
         a, b = _coerce_exprs(self, other)
         return BitVecRef(Z3_mk_bvadd(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
__and__()
def __and__ (self, other)
Create the Z3 expression bitwise-and `self & other`.
>>> x = BitVec('x', 32)
>>> y = BitVec('y', 32)
>>> x & y
x & y
>>> (x & y).sort()
BitVec(32)
Definition at line 3595 of file z3py.py.
     def __and__(self, other):
         """Create the Z3 expression bitwise-and `self & other`.
         >>> x = BitVec('x', 32)
         >>> y = BitVec('y', 32)
         >>> x & y
         x & y
         >>> (x & y).sort()
         BitVec(32)
         """
         a, b = _coerce_exprs(self, other)
         return BitVecRef(Z3_mk_bvand(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
__div__()
def __div__ (self, other)
Create the Z3 expression (signed) division `self / other`.
Use the function UDiv() for unsigned division.
>>> x = BitVec('x', 32)
>>> y = BitVec('y', 32)
>>> x / y
x/y
>>> (x / y).sort()
BitVec(32)
>>> (x / y).sexpr()
'(bvsdiv x y)'
>>> UDiv(x, y).sexpr()
'(bvudiv x y)'
Definition at line 3672 of file z3py.py.
     def __div__(self, other):
         """Create the Z3 expression (signed) division `self / other`.
         Use the function UDiv() for unsigned division.
         >>> x = BitVec('x', 32)
         >>> y = BitVec('y', 32)
         >>> x / y
         x/y
         >>> (x / y).sort()
         BitVec(32)
         >>> (x / y).sexpr()
         '(bvsdiv x y)'
         >>> UDiv(x, y).sexpr()
         '(bvudiv x y)'
         """
         a, b = _coerce_exprs(self, other)
         return BitVecRef(Z3_mk_bvsdiv(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
Referenced by BitVecRef.__truediv__(), and FPRef.__truediv__().
__ge__()
def __ge__ (self, other)
Create the Z3 expression (signed) `other >= self`.
Use the function UGE() for unsigned greater than or equal to.
>>> x, y = BitVecs('x y', 32)
>>> x >= y
x >= y
>>> (x >= y).sexpr()
'(bvsge x y)'
>>> UGE(x, y).sexpr()
'(bvuge x y)'
Definition at line 3802 of file z3py.py.
     def __ge__(self, other):
         """Create the Z3 expression (signed) `other >= self`.
         Use the function UGE() for unsigned greater than or equal to.
         >>> x, y = BitVecs('x y', 32)
         >>> x >= y
         x >= y
         >>> (x >= y).sexpr()
         '(bvsge x y)'
         >>> UGE(x, y).sexpr()
         '(bvuge x y)'
         """
         a, b = _coerce_exprs(self, other)
         return BoolRef(Z3_mk_bvsge(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
__gt__()
def __gt__ (self, other)
Create the Z3 expression (signed) `other > self`.
Use the function UGT() for unsigned greater than.
>>> x, y = BitVecs('x y', 32)
>>> x > y
x > y
>>> (x > y).sexpr()
'(bvsgt x y)'
>>> UGT(x, y).sexpr()
'(bvugt x y)'
Definition at line 3786 of file z3py.py.
     def __gt__(self, other):
         """Create the Z3 expression (signed) `other > self`.
         Use the function UGT() for unsigned greater than.
         >>> x, y = BitVecs('x y', 32)
         >>> x > y
         x > y
         >>> (x > y).sexpr()
         '(bvsgt x y)'
         >>> UGT(x, y).sexpr()
         '(bvugt x y)'
         """
         a, b = _coerce_exprs(self, other)
         return BoolRef(Z3_mk_bvsgt(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
__invert__()
def __invert__ (self)
Create the Z3 expression bitwise-not `~self`.
>>> x = BitVec('x', 32)
>>> ~x
~x
>>> simplify(~(~x))
x
Definition at line 3661 of file z3py.py.
     def __invert__(self):
         """Create the Z3 expression bitwise-not `~self`.
         >>> x = BitVec('x', 32)
         >>> ~x
         ~x
         >>> simplify(~(~x))
         x
         """
         return BitVecRef(Z3_mk_bvnot(self.ctx_ref(), self.as_ast()), self.ctx)
__le__()
def __le__ (self, other)
Create the Z3 expression (signed) `other <= self`.
Use the function ULE() for unsigned less than or equal to.
>>> x, y = BitVecs('x y', 32)
>>> x <= y
x <= y
>>> (x <= y).sexpr()
'(bvsle x y)'
>>> ULE(x, y).sexpr()
'(bvule x y)'
Definition at line 3754 of file z3py.py.
     def __le__(self, other):
         """Create the Z3 expression (signed) `other <= self`.
         Use the function ULE() for unsigned less than or equal to.
         >>> x, y = BitVecs('x y', 32)
         >>> x <= y
         x <= y
         >>> (x <= y).sexpr()
         '(bvsle x y)'
         >>> ULE(x, y).sexpr()
         '(bvule x y)'
         """
         a, b = _coerce_exprs(self, other)
         return BoolRef(Z3_mk_bvsle(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
__lshift__()
def __lshift__ (self, other)
Create the Z3 expression left shift `self << other`
>>> x, y = BitVecs('x y', 32)
>>> x << y
x << y
>>> (x << y).sexpr()
'(bvshl x y)'
>>> simplify(BitVecVal(2, 3) << 1)
4
Definition at line 3848 of file z3py.py.
     def __lshift__(self, other):
         """Create the Z3 expression left shift `self << other`
         >>> x, y = BitVecs('x y', 32)
         >>> x << y
         x << y
         >>> (x << y).sexpr()
         '(bvshl x y)'
         >>> simplify(BitVecVal(2, 3) << 1)
         4
         """
         a, b = _coerce_exprs(self, other)
         return BitVecRef(Z3_mk_bvshl(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
__lt__()
def __lt__ (self, other)
Create the Z3 expression (signed) `other < self`.
Use the function ULT() for unsigned less than.
>>> x, y = BitVecs('x y', 32)
>>> x < y
x < y
>>> (x < y).sexpr()
'(bvslt x y)'
>>> ULT(x, y).sexpr()
'(bvult x y)'
Definition at line 3770 of file z3py.py.
     def __lt__(self, other):
         """Create the Z3 expression (signed) `other < self`.
         Use the function ULT() for unsigned less than.
         >>> x, y = BitVecs('x y', 32)
         >>> x < y
         x < y
         >>> (x < y).sexpr()
         '(bvslt x y)'
         >>> ULT(x, y).sexpr()
         '(bvult x y)'
         """
         a, b = _coerce_exprs(self, other)
         return BoolRef(Z3_mk_bvslt(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
__mod__()
def __mod__ (self, other)
Create the Z3 expression (signed) mod `self % other`.
Use the function URem() for unsigned remainder, and SRem() for signed remainder.
>>> x = BitVec('x', 32)
>>> y = BitVec('y', 32)
>>> x % y
x%y
>>> (x % y).sort()
BitVec(32)
>>> (x % y).sexpr()
'(bvsmod x y)'
>>> URem(x, y).sexpr()
'(bvurem x y)'
>>> SRem(x, y).sexpr()
'(bvsrem x y)'
Definition at line 3715 of file z3py.py.
     def __mod__(self, other):
         """Create the Z3 expression (signed) mod `self % other`.
         Use the function URem() for unsigned remainder, and SRem() for signed remainder.
         >>> x = BitVec('x', 32)
         >>> y = BitVec('y', 32)
         >>> x % y
         x%y
         >>> (x % y).sort()
         BitVec(32)
         >>> (x % y).sexpr()
         '(bvsmod x y)'
         >>> URem(x, y).sexpr()
         '(bvurem x y)'
         >>> SRem(x, y).sexpr()
         '(bvsrem x y)'
         """
         a, b = _coerce_exprs(self, other)
         return BitVecRef(Z3_mk_bvsmod(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
__mul__()
def __mul__ (self, other)
Create the Z3 expression `self * other`.
>>> x = BitVec('x', 32)
>>> y = BitVec('y', 32)
>>> x * y
x*y
>>> (x * y).sort()
BitVec(32)
Definition at line 3526 of file z3py.py.
     def __mul__(self, other):
         """Create the Z3 expression `self * other`.
         >>> x = BitVec('x', 32)
         >>> y = BitVec('y', 32)
         >>> x * y
         x*y
         >>> (x * y).sort()
         BitVec(32)
         """
         a, b = _coerce_exprs(self, other)
         return BitVecRef(Z3_mk_bvmul(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
__neg__()
def __neg__ (self)
Return an expression representing `-self`.
>>> x = BitVec('x', 32)
>>> -x
-x
>>> simplify(-(-x))
x
Definition at line 3650 of file z3py.py.
     def __neg__(self):
         """Return an expression representing `-self`.
         >>> x = BitVec('x', 32)
         >>> -x
         -x
         >>> simplify(-(-x))
         x
         """
         return BitVecRef(Z3_mk_bvneg(self.ctx_ref(), self.as_ast()), self.ctx)
__or__()
def __or__ (self, other)
Create the Z3 expression bitwise-or `self | other`.
>>> x = BitVec('x', 32)
>>> y = BitVec('y', 32)
>>> x | y
x | y
>>> (x | y).sort()
BitVec(32)
Definition at line 3572 of file z3py.py.
     def __or__(self, other):
         """Create the Z3 expression bitwise-or `self | other`.
         >>> x = BitVec('x', 32)
         >>> y = BitVec('y', 32)
         >>> x | y
         x | y
         >>> (x | y).sort()
         BitVec(32)
         """
         a, b = _coerce_exprs(self, other)
         return BitVecRef(Z3_mk_bvor(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
__pos__()
def __pos__ (self)
Return `self`.
>>> x = BitVec('x', 32)
>>> +x
x
Definition at line 3641 of file z3py.py.
     def __pos__(self):
         """Return `self`.
         >>> x = BitVec('x', 32)
         >>> +x
         x
         """
         return self
__radd__()
def __radd__ (self, other)
Create the Z3 expression `other + self`.
>>> x = BitVec('x', 32)
>>> 10 + x
10 + x
Definition at line 3516 of file z3py.py.
     def __radd__(self, other):
         """Create the Z3 expression `other + self`.
         >>> x = BitVec('x', 32)
         >>> 10 + x
         10 + x
         """
         a, b = _coerce_exprs(self, other)
         return BitVecRef(Z3_mk_bvadd(self.ctx_ref(), b.as_ast(), a.as_ast()), self.ctx)
__rand__()
def __rand__ (self, other)
Create the Z3 expression bitwise-or `other & self`.
>>> x = BitVec('x', 32)
>>> 10 & x
10 & x
Definition at line 3608 of file z3py.py.
     def __rand__(self, other):
         """Create the Z3 expression bitwise-or `other & self`.
         >>> x = BitVec('x', 32)
         >>> 10 & x
         10 & x
         """
         a, b = _coerce_exprs(self, other)
         return BitVecRef(Z3_mk_bvand(self.ctx_ref(), b.as_ast(), a.as_ast()), self.ctx)
__rdiv__()
def __rdiv__ (self, other)
Create the Z3 expression (signed) division `other / self`.
Use the function UDiv() for unsigned division.
>>> x = BitVec('x', 32)
>>> 10 / x
10/x
>>> (10 / x).sexpr()
'(bvsdiv #x0000000a x)'
>>> UDiv(10, x).sexpr()
'(bvudiv #x0000000a x)'
Definition at line 3695 of file z3py.py.
     def __rdiv__(self, other):
         """Create the Z3 expression (signed) division `other / self`.
         Use the function UDiv() for unsigned division.
         >>> x = BitVec('x', 32)
         >>> 10 / x
         10/x
         >>> (10 / x).sexpr()
         '(bvsdiv #x0000000a x)'
         >>> UDiv(10, x).sexpr()
         '(bvudiv #x0000000a x)'
         """
         a, b = _coerce_exprs(self, other)
         return BitVecRef(Z3_mk_bvsdiv(self.ctx_ref(), b.as_ast(), a.as_ast()), self.ctx)
Referenced by BitVecRef.__rtruediv__(), and FPRef.__rtruediv__().
__rlshift__()
def __rlshift__ (self, other)
Create the Z3 expression left shift `other << self`.
Use the function LShR() for the right logical shift
>>> x = BitVec('x', 32)
>>> 10 << x
10 << x
>>> (10 << x).sexpr()
'(bvshl #x0000000a x)'
Definition at line 3876 of file z3py.py.
     def __rlshift__(self, other):
         """Create the Z3 expression left shift `other << self`.
         Use the function LShR() for the right logical shift
         >>> x = BitVec('x', 32)
         >>> 10 << x
         10 << x
         >>> (10 << x).sexpr()
         '(bvshl #x0000000a x)'
         """
         a, b = _coerce_exprs(self, other)
         return BitVecRef(Z3_mk_bvshl(self.ctx_ref(), b.as_ast(), a.as_ast()), self.ctx)
__rmod__()
def __rmod__ (self, other)
Create the Z3 expression (signed) mod `other % self`.
Use the function URem() for unsigned remainder, and SRem() for signed remainder.
>>> x = BitVec('x', 32)
>>> 10 % x
10%x
>>> (10 % x).sexpr()
'(bvsmod #x0000000a x)'
>>> URem(10, x).sexpr()
'(bvurem #x0000000a x)'
>>> SRem(10, x).sexpr()
'(bvsrem #x0000000a x)'
Definition at line 3736 of file z3py.py.
     def __rmod__(self, other):
         """Create the Z3 expression (signed) mod `other % self`.
         Use the function URem() for unsigned remainder, and SRem() for signed remainder.
         >>> x = BitVec('x', 32)
         >>> 10 % x
         10%x
         >>> (10 % x).sexpr()
         '(bvsmod #x0000000a x)'
         >>> URem(10, x).sexpr()
         '(bvurem #x0000000a x)'
         >>> SRem(10, x).sexpr()
         '(bvsrem #x0000000a x)'
         """
         a, b = _coerce_exprs(self, other)
         return BitVecRef(Z3_mk_bvsmod(self.ctx_ref(), b.as_ast(), a.as_ast()), self.ctx)
__rmul__()
def __rmul__ (self, other)
Create the Z3 expression `other * self`.
>>> x = BitVec('x', 32)
>>> 10 * x
10*x
Definition at line 3539 of file z3py.py.
     def __rmul__(self, other):
         """Create the Z3 expression `other * self`.
         >>> x = BitVec('x', 32)
         >>> 10 * x
         10*x
         """
         a, b = _coerce_exprs(self, other)
         return BitVecRef(Z3_mk_bvmul(self.ctx_ref(), b.as_ast(), a.as_ast()), self.ctx)
__ror__()
def __ror__ (self, other)
Create the Z3 expression bitwise-or `other | self`.
>>> x = BitVec('x', 32)
>>> 10 | x
10 | x
Definition at line 3585 of file z3py.py.
     def __ror__(self, other):
         """Create the Z3 expression bitwise-or `other | self`.
         >>> x = BitVec('x', 32)
         >>> 10 | x
         10 | x
         """
         a, b = _coerce_exprs(self, other)
         return BitVecRef(Z3_mk_bvor(self.ctx_ref(), b.as_ast(), a.as_ast()), self.ctx)
__rrshift__()
def __rrshift__ (self, other)
Create the Z3 expression (arithmetical) right shift `other` >> `self`.
Use the function LShR() for the right logical shift
>>> x = BitVec('x', 32)
>>> 10 >> x
10 >> x
>>> (10 >> x).sexpr()
'(bvashr #x0000000a x)'
Definition at line 3862 of file z3py.py.
     def __rrshift__(self, other):
         """Create the Z3 expression (arithmetical) right shift `other` >> `self`.
         Use the function LShR() for the right logical shift
         >>> x = BitVec('x', 32)
         >>> 10 >> x
         10 >> x
         >>> (10 >> x).sexpr()
         '(bvashr #x0000000a x)'
         """
         a, b = _coerce_exprs(self, other)
         return BitVecRef(Z3_mk_bvashr(self.ctx_ref(), b.as_ast(), a.as_ast()), self.ctx)
__rshift__()
def __rshift__ (self, other)
Create the Z3 expression (arithmetical) right shift `self >> other`
Use the function LShR() for the right logical shift
>>> x, y = BitVecs('x y', 32)
>>> x >> y
x >> y
>>> (x >> y).sexpr()
'(bvashr x y)'
>>> LShR(x, y).sexpr()
'(bvlshr x y)'
>>> BitVecVal(4, 3)
4
>>> BitVecVal(4, 3).as_signed_long()
-4
>>> simplify(BitVecVal(4, 3) >> 1).as_signed_long()
-2
>>> simplify(BitVecVal(4, 3) >> 1)
6
>>> simplify(LShR(BitVecVal(4, 3), 1))
2
>>> simplify(BitVecVal(2, 3) >> 1)
1
>>> simplify(LShR(BitVecVal(2, 3), 1))
1
Definition at line 3818 of file z3py.py.
     def __rshift__(self, other):
         """Create the Z3 expression (arithmetical) right shift `self >> other`
         Use the function LShR() for the right logical shift
         >>> x, y = BitVecs('x y', 32)
         >>> x >> y
         x >> y
         >>> (x >> y).sexpr()
         '(bvashr x y)'
         >>> LShR(x, y).sexpr()
         '(bvlshr x y)'
         >>> BitVecVal(4, 3)
         4
         >>> BitVecVal(4, 3).as_signed_long()
         -4
         >>> simplify(BitVecVal(4, 3) >> 1).as_signed_long()
         -2
         >>> simplify(BitVecVal(4, 3) >> 1)
         6
         >>> simplify(LShR(BitVecVal(4, 3), 1))
         2
         >>> simplify(BitVecVal(2, 3) >> 1)
         1
         >>> simplify(LShR(BitVecVal(2, 3), 1))
         1
         """
         a, b = _coerce_exprs(self, other)
         return BitVecRef(Z3_mk_bvashr(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
__rsub__()
def __rsub__ (self, other)
Create the Z3 expression `other - self`.
>>> x = BitVec('x', 32)
>>> 10 - x
10 - x
Definition at line 3562 of file z3py.py.
     def __rsub__(self, other):
         """Create the Z3 expression `other - self`.
         >>> x = BitVec('x', 32)
         >>> 10 - x
         10 - x
         """
         a, b = _coerce_exprs(self, other)
         return BitVecRef(Z3_mk_bvsub(self.ctx_ref(), b.as_ast(), a.as_ast()), self.ctx)
__rtruediv__()
def __rtruediv__ (self, other)
Create the Z3 expression (signed) division `other / self`.
Definition at line 3711 of file z3py.py.
     def __rtruediv__(self, other):
         """Create the Z3 expression (signed) division `other / self`."""
         return self.__rdiv__(other)
__rxor__()
def __rxor__ (self, other)
Create the Z3 expression bitwise-xor `other ^ self`.
>>> x = BitVec('x', 32)
>>> 10 ^ x
10 ^ x
Definition at line 3631 of file z3py.py.
     def __rxor__(self, other):
         """Create the Z3 expression bitwise-xor `other ^ self`.
         >>> x = BitVec('x', 32)
         >>> 10 ^ x
         10 ^ x
         """
         a, b = _coerce_exprs(self, other)
         return BitVecRef(Z3_mk_bvxor(self.ctx_ref(), b.as_ast(), a.as_ast()), self.ctx)
__sub__()
def __sub__ (self, other)
Create the Z3 expression `self - other`.
>>> x = BitVec('x', 32)
>>> y = BitVec('y', 32)
>>> x - y
x - y
>>> (x - y).sort()
BitVec(32)
Definition at line 3549 of file z3py.py.
     def __sub__(self, other):
         """Create the Z3 expression `self - other`.
         >>> x = BitVec('x', 32)
         >>> y = BitVec('y', 32)
         >>> x - y
         x - y
         >>> (x - y).sort()
         BitVec(32)
         """
         a, b = _coerce_exprs(self, other)
         return BitVecRef(Z3_mk_bvsub(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
__truediv__()
def __truediv__ (self, other)
Create the Z3 expression (signed) division `self / other`.
Definition at line 3691 of file z3py.py.
     def __truediv__(self, other):
         """Create the Z3 expression (signed) division `self / other`."""
         return self.__div__(other)
__xor__()
def __xor__ (self, other)
Create the Z3 expression bitwise-xor `self ^ other`.
>>> x = BitVec('x', 32)
>>> y = BitVec('y', 32)
>>> x ^ y
x ^ y
>>> (x ^ y).sort()
BitVec(32)
Definition at line 3618 of file z3py.py.
     def __xor__(self, other):
         """Create the Z3 expression bitwise-xor `self ^ other`.
         >>> x = BitVec('x', 32)
         >>> y = BitVec('y', 32)
         >>> x ^ y
         x ^ y
         >>> (x ^ y).sort()
         BitVec(32)
         """
         a, b = _coerce_exprs(self, other)
         return BitVecRef(Z3_mk_bvxor(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
size()
def size (self)
Return the number of bits of the bit-vector expression `self`.
>>> x = BitVec('x', 32)
>>> (x + 1).size()
32
>>> Concat(x, x).size()
64
Definition at line 3492 of file z3py.py.
     def size(self):
         """Return the number of bits of the bit-vector expression `self`.
         >>> x = BitVec('x', 32)
         >>> (x + 1).size()
         32
         >>> Concat(x, x).size()
         64
         """
         return self.sort().size()
Referenced by ParamDescrsRef.__len__(), Goal.__len__(), and BitVecNumRef.as_signed_long().
sort()
def sort (self)
Return the sort of the bit-vector expression `self`.
>>> x = BitVec('x', 32)
>>> x.sort()
BitVec(32)
>>> x.sort() == BitVecSort(32)
True
Reimplemented from ExprRef.
Definition at line 3481 of file z3py.py.
     def sort(self):
         """Return the sort of the bit-vector expression `self`.
         >>> x = BitVec('x', 32)
         >>> x.sort()
         BitVec(32)
         >>> x.sort() == BitVecSort(32)
         True
         """
         return BitVecSortRef(Z3_get_sort(self.ctx_ref(), self.as_ast()), self.ctx)