Z3: array< T > Class Template Reference
array< T > Class Template Reference
Public Member Functions
array (unsigned sz)
template<typename T2 >
array (ast_vector_tpl< T2 > const &v)
void resize (unsigned sz)
unsigned size () const
T & operator[] (int i)
const T & operator[] (int i) const
const T * ptr () const
T * ptr ()
Detailed Description
template<typename T>
class z3::array< T >
Definition at line 430 of file z3++.h.
Constructor & Destructor Documentation
array() [1/2]
array (unsigned sz) inline
Definition at line 436 of file z3++.h.
 :m_array(new T[sz]),m_size(sz) {}
array() [2/2]
array (ast_vector_tpl< T2 > const & v)
Definition at line 2285 of file z3++.h.
                                                :m_array(new T[v.size()]), m_size(v.size()) {
         for (unsigned i = 0; i < m_size; i++) {
             m_array[i] = v[i];
         }
     }
Member Function Documentation
operator[]() [1/2]
T& operator[] (int i) inline
Definition at line 441 of file z3++.h.
 { assert(0 <= i); assert(static_cast<unsigned>(i) < m_size); return m_array[i]; }
operator[]() [2/2]
const T& operator[] (int i) const inline
Definition at line 442 of file z3++.h.
 { assert(0 <= i); assert(static_cast<unsigned>(i) < m_size); return m_array[i]; }
ptr() [1/2]
T* ptr () inline
Definition at line 444 of file z3++.h.
 { return m_array.get(); }
ptr() [2/2]
const T* ptr () const inline
Definition at line 443 of file z3++.h.
 { return m_array.get(); }
Referenced by constructors::add(), context::array_sort(), goal::as_expr(), z3::atleast(), z3::atmost(), context::bv_val(), solver::check(), optimize::check(), z3::concat(), user_propagator_base::conflict(), constructor_list::constructor_list(), context::datatype(), context::datatypes(), z3::distinct(), context::enumeration_sort(), z3::exists(), z3::forall(), context::function(), z3::lambda(), z3::mk_and(), z3::mk_or(), func_decl::operator()(), z3::par_or(), context::parse_file(), context::parse_string(), z3::pbeq(), z3::pbge(), z3::pble(), user_propagator_base::propagate(), fixedpoint::query(), constructors::query(), z3::re_intersect(), context::recdef(), context::recfun(), z3::select(), z3::store(), expr::substitute(), z3::sum(), solver::to_smt2(), fixedpoint::to_string(), solver::trail(), context::tuple_sort(), and context::user_propagate_function().
resize()
void resize (unsigned sz) inline
Definition at line 439 of file z3++.h.
 { m_array.reset(new T[sz]); m_size = sz; }
Referenced by solver::trail().
size()
unsigned size () const inline
Definition at line 440 of file z3++.h.
 { return m_size; }
Referenced by context::array_sort(), z3::atleast(), z3::atmost(), z3::concat(), z3::distinct(), z3::exists(), z3::forall(), z3::lambda(), z3::mk_and(), z3::mk_or(), z3::pbeq(), z3::pbge(), z3::pble(), user_propagator_base::propagate(), fixedpoint::query(), z3::re_intersect(), context::recdef(), z3::select(), z3::store(), z3::sum(), solver::to_smt2(), fixedpoint::to_string(), and context::user_propagate_function().