Z3: Goal Class Reference
Goal Class Reference
Public Member Functions
Z3_goal_prec getPrecision ()
boolean isPrecise ()
boolean isUnderApproximation ()
boolean isOverApproximation ()
boolean isGarbage ()
final void add (Expr< BoolSort >... constraints)
boolean inconsistent ()
int getDepth ()
void reset ()
int size ()
BoolExpr[] getFormulas ()
int getNumExprs ()
boolean isDecidedSat ()
boolean isDecidedUnsat ()
Goal translate (Context ctx)
Goal simplify ()
Goal simplify (Params p)
String toString ()
BoolExpr AsBoolExpr ()
Model convertModel (Model m)
Additional Inherited Members
Static Public Member Functions inherited from Z3Object
static long[] arrayToNative (Z3Object[] a)
static int arrayLength (Z3Object[] a)
Detailed Description
A goal (aka problem). A goal is essentially a set of formulas, that can be solved and/or transformed using tactics and solvers.
Definition at line 28 of file Goal.java.
Member Function Documentation
add()
final void add (Expr< BoolSort >... constraints) inline
Adds the
constraints
to the given goal.
Exceptions
Z3Exception
Definition at line 82 of file Goal.java.
     {
         getContext().checkContextMatch(constraints);
         for (Expr<BoolSort> c : constraints)
         {
             Native.goalAssert(getContext().nCtx(), getNativeObject(),
                     c.getNativeObject());
         }
     }
Referenced by Solver.__iadd__(), Fixedpoint.__iadd__(), and Optimize.__iadd__().
AsBoolExpr()
BoolExpr AsBoolExpr () inline
Goal to BoolExpr conversion.
Returns a string representation of the Goal.
Definition at line 224 of file Goal.java.
{
         int n = size();
         if (n == 0) {
             return getContext().mkTrue();
         } else if (n == 1) {
             return getFormulas()[0];
         } else {
             return getContext().mkAnd(getFormulas());
         }
     }
convertModel()
Model convertModel (Model m) inline
Convert a model for the goal into a model of the original goal from which this goal was derived.
Returns
A model for
g
Exceptions
Z3Exception
Definition at line 252 of file Goal.java.
     {
         return new Model(getContext(),
             Native.goalConvertModel(getContext().nCtx(), getNativeObject(), m.getNativeObject()));
     }
getDepth()
int getDepth () inline
The depth of the goal. Remarks: This tracks how many transformations were applied to it.
Definition at line 105 of file Goal.java.
     {
         return Native.goalDepth(getContext().nCtx(), getNativeObject());
     }
getFormulas()
BoolExpr [] getFormulas () inline
The formulas in the goal.
Exceptions
Z3Exception
Definition at line 131 of file Goal.java.
     {
         int n = size();
         BoolExpr[] res = new BoolExpr[n];
         for (int i = 0; i < n; i++)
             res[i] = (BoolExpr) Expr.create(getContext(), Native.goalFormula(getContext().nCtx(), getNativeObject(), i));
         return res;
     }
Referenced by Goal.AsBoolExpr().
getNumExprs()
int getNumExprs () inline
The number of formulas, subformulas and terms in the goal.
Definition at line 143 of file Goal.java.
     {
         return Native.goalNumExprs(getContext().nCtx(), getNativeObject());
     }
getPrecision()
Z3_goal_prec getPrecision () inline
The precision of the goal. Remarks: Goals can be transformed using over and under approximations. An under approximation is applied when the objective is to find a model for a given goal. An over approximation is applied when the objective is to find a proof for a given goal.
Definition at line 37 of file Goal.java.
     {
         return Z3_goal_prec.fromInt(Native.goalPrecision(getContext().nCtx(),
                 getNativeObject()));
     }
Referenced by Goal.isGarbage(), Goal.isOverApproximation(), Goal.isPrecise(), and Goal.isUnderApproximation().
inconsistent()
boolean inconsistent () inline
Indicates whether the goal contains ‘false’.
Definition at line 95 of file Goal.java.
     {
         return Native.goalInconsistent(getContext().nCtx(), getNativeObject());
     }
isDecidedSat()
boolean isDecidedSat () inline
Indicates whether the goal is empty, and it is precise or the product of an under approximation.
Definition at line 152 of file Goal.java.
     {
         return Native.goalIsDecidedSat(getContext().nCtx(), getNativeObject());
     }
isDecidedUnsat()
boolean isDecidedUnsat () inline
Indicates whether the goal contains ‘false’, and it is precise or the product of an over approximation.
Definition at line 161 of file Goal.java.
     {
         return Native
                 .goalIsDecidedUnsat(getContext().nCtx(), getNativeObject());
     }
isGarbage()
boolean isGarbage () inline
Indicates whether the goal is garbage (i.e., the product of over- and under-approximations).
Definition at line 71 of file Goal.java.
     {
         return getPrecision() == Z3_goal_prec.Z3_GOAL_UNDER_OVER;
     }
isOverApproximation()
boolean isOverApproximation () inline
Indicates whether the goal is an over-approximation.
Definition at line 62 of file Goal.java.
     {
         return getPrecision() == Z3_goal_prec.Z3_GOAL_OVER;
     }
isPrecise()
boolean isPrecise () inline
Indicates whether the goal is precise.
Definition at line 46 of file Goal.java.
     {
         return getPrecision() == Z3_goal_prec.Z3_GOAL_PRECISE;
     }
isUnderApproximation()
boolean isUnderApproximation () inline
Indicates whether the goal is an under-approximation.
Definition at line 54 of file Goal.java.
     {
         return getPrecision() == Z3_goal_prec.Z3_GOAL_UNDER;
     }
reset()
void reset () inline
Erases all formulas from the given goal.
Definition at line 113 of file Goal.java.
     {
         Native.goalReset(getContext().nCtx(), getNativeObject());
     }
simplify() [1/2]
Goal simplify () inline
Simplifies the goal. Remarks: Essentially invokes the ‘simplify’ tactic on the goal.
Definition at line 183 of file Goal.java.
     {
         Tactic t = getContext().mkTactic("simplify");
         ApplyResult res = t.apply(this);
         if (res.getNumSubgoals() == 0)
             throw new Z3Exception("No subgoals");
         else
             return res.getSubgoals()[0];
     }
simplify() [2/2]
Goal simplify (Params p) inline
Simplifies the goal. Remarks: Essentially invokes the ‘simplify’ tactic on the goal.
Definition at line 199 of file Goal.java.
     {
         Tactic t = getContext().mkTactic("simplify");
         ApplyResult res = t.apply(this, p);
         if (res.getNumSubgoals() == 0)
             throw new Z3Exception("No subgoals");
         else
             return res.getSubgoals()[0];
     }
size()
int size () inline
The number of formulas in the goal.
Definition at line 121 of file Goal.java.
     {
         return Native.goalSize(getContext().nCtx(), getNativeObject());
     }
Referenced by ParamDescrsRef.__len__(), Goal.__len__(), BitVecNumRef.as_signed_long(), Goal.AsBoolExpr(), Goal.getFormulas(), and BitVecSortRef.subsort().
toString()
String toString () inline
Goal to string conversion.
Returns
A string representation of the Goal.
Definition at line 215 of file Goal.java.
{
         return Native.goalToString(getContext().nCtx(), getNativeObject());
     }
translate()
Goal translate (Context ctx) inline
Translates (copies) the Goal to the target Context
ctx
.
Exceptions
Z3Exception
Definition at line 172 of file Goal.java.
     {
         return new Goal(ctx, Native.goalTranslate(getContext().nCtx(),
                 getNativeObject(), ctx.nCtx()));
     }
Referenced by AstRef.__copy__(), Goal.__copy__(), AstVector.__copy__(), FuncInterp.__copy__(), ModelRef.__copy__(), Solver.__copy__(), Goal.__deepcopy__(), AstVector.__deepcopy__(), FuncInterp.__deepcopy__(), ModelRef.__deepcopy__(), and Solver.__deepcopy__().