Z3: Native Class Reference
Native Class Reference
Data Structures
class LIB
Public Member Functions
delegate void Z3_error_handler (Z3_context c, Z3_error_code e)
Static Public Member Functions
static void Z3_set_error_handler (Z3_context a0, Z3_error_handler a1)
static void Z3_global_param_set (string a0, string a1)
static void Z3_global_param_reset_all ()
static int Z3_global_param_get (string a0, out IntPtr a1)
static Z3_config Z3_mk_config ()
static void Z3_del_config (Z3_config a0)
static void Z3_set_param_value (Z3_config a0, string a1, string a2)
static Z3_context Z3_mk_context (Z3_config a0)
static Z3_context Z3_mk_context_rc (Z3_config a0)
static void Z3_del_context (Z3_context a0)
static void Z3_inc_ref (Z3_context a0, Z3_ast a1)
static void Z3_dec_ref (Z3_context a0, Z3_ast a1)
static void Z3_update_param_value (Z3_context a0, string a1, string a2)
static void Z3_interrupt (Z3_context a0)
static Z3_params Z3_mk_params (Z3_context a0)
static void Z3_params_inc_ref (Z3_context a0, Z3_params a1)
static void Z3_params_dec_ref (Z3_context a0, Z3_params a1)
static void Z3_params_set_bool (Z3_context a0, Z3_params a1, IntPtr a2, int a3)
static void Z3_params_set_uint (Z3_context a0, Z3_params a1, IntPtr a2, uint a3)
static void Z3_params_set_double (Z3_context a0, Z3_params a1, IntPtr a2, double a3)
static void Z3_params_set_symbol (Z3_context a0, Z3_params a1, IntPtr a2, IntPtr a3)
static string Z3_params_to_string (Z3_context a0, Z3_params a1)
static void Z3_params_validate (Z3_context a0, Z3_params a1, Z3_param_descrs a2)
static void Z3_param_descrs_inc_ref (Z3_context a0, Z3_param_descrs a1)
static void Z3_param_descrs_dec_ref (Z3_context a0, Z3_param_descrs a1)
static uint Z3_param_descrs_get_kind (Z3_context a0, Z3_param_descrs a1, IntPtr a2)
static uint Z3_param_descrs_size (Z3_context a0, Z3_param_descrs a1)
static IntPtr Z3_param_descrs_get_name (Z3_context a0, Z3_param_descrs a1, uint a2)
static string Z3_param_descrs_to_string (Z3_context a0, Z3_param_descrs a1)
static IntPtr Z3_mk_int_symbol (Z3_context a0, int a1)
static IntPtr Z3_mk_string_symbol (Z3_context a0, string a1)
static Z3_sort Z3_mk_uninterpreted_sort (Z3_context a0, IntPtr a1)
static Z3_sort Z3_mk_bool_sort (Z3_context a0)
static Z3_sort Z3_mk_int_sort (Z3_context a0)
static Z3_sort Z3_mk_real_sort (Z3_context a0)
static Z3_sort Z3_mk_bv_sort (Z3_context a0, uint a1)
static Z3_sort Z3_mk_finite_domain_sort (Z3_context a0, IntPtr a1, UInt64 a2)
static Z3_sort Z3_mk_array_sort (Z3_context a0, Z3_sort a1, Z3_sort a2)
static Z3_sort Z3_mk_tuple_sort (Z3_context a0, IntPtr a1, uint a2, [In] IntPtr[] a3, [In] Z3_sort[] a4, [In, Out] ref Z3_func_decl a5, [Out] Z3_func_decl[] a6)
static Z3_sort Z3_mk_enumeration_sort (Z3_context a0, IntPtr a1, uint a2, [In] IntPtr[] a3, [Out] Z3_func_decl[] a4, [Out] Z3_func_decl[] a5)
static Z3_sort Z3_mk_list_sort (Z3_context a0, IntPtr a1, Z3_sort a2, [In, Out] ref Z3_func_decl a3, [In, Out] ref Z3_func_decl a4, [In, Out] ref Z3_func_decl a5, [In, Out] ref Z3_func_decl a6, [In, Out] ref Z3_func_decl a7, [In, Out] ref Z3_func_decl a8)
static Z3_constructor Z3_mk_constructor (Z3_context a0, IntPtr a1, IntPtr a2, uint a3, [In] IntPtr[] a4, [In] Z3_sort[] a5, [In] uint[] a6)
static void Z3_del_constructor (Z3_context a0, Z3_constructor a1)
static Z3_sort Z3_mk_datatype (Z3_context a0, IntPtr a1, uint a2, [In, Out] Z3_constructor[] a3)
static Z3_constructor_list Z3_mk_constructor_list (Z3_context a0, uint a1, [In] Z3_constructor[] a2)
static void Z3_del_constructor_list (Z3_context a0, Z3_constructor_list a1)
static void Z3_mk_datatypes (Z3_context a0, uint a1, [In] IntPtr[] a2, [Out] Z3_sort[] a3, [In, Out] Z3_constructor_list[] a4)
static void Z3_query_constructor (Z3_context a0, Z3_constructor a1, uint a2, [In, Out] ref Z3_func_decl a3, [In, Out] ref Z3_func_decl a4, [Out] Z3_func_decl[] a5)
static Z3_func_decl Z3_mk_func_decl (Z3_context a0, IntPtr a1, uint a2, [In] Z3_sort[] a3, Z3_sort a4)
static Z3_ast Z3_mk_app (Z3_context a0, Z3_func_decl a1, uint a2, [In] Z3_ast[] a3)
static Z3_ast Z3_mk_const (Z3_context a0, IntPtr a1, Z3_sort a2)
static Z3_func_decl Z3_mk_fresh_func_decl (Z3_context a0, string a1, uint a2, [In] Z3_sort[] a3, Z3_sort a4)
static Z3_ast Z3_mk_fresh_const (Z3_context a0, string a1, Z3_sort a2)
static Z3_ast Z3_mk_true (Z3_context a0)
static Z3_ast Z3_mk_false (Z3_context a0)
static Z3_ast Z3_mk_eq (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_distinct (Z3_context a0, uint a1, [In] Z3_ast[] a2)
static Z3_ast Z3_mk_not (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_mk_ite (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_ast a3)
static Z3_ast Z3_mk_iff (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_implies (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_xor (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_and (Z3_context a0, uint a1, [In] Z3_ast[] a2)
static Z3_ast Z3_mk_or (Z3_context a0, uint a1, [In] Z3_ast[] a2)
static Z3_ast Z3_mk_add (Z3_context a0, uint a1, [In] Z3_ast[] a2)
static Z3_ast Z3_mk_mul (Z3_context a0, uint a1, [In] Z3_ast[] a2)
static Z3_ast Z3_mk_sub (Z3_context a0, uint a1, [In] Z3_ast[] a2)
static Z3_ast Z3_mk_unary_minus (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_mk_div (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_mod (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_rem (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_power (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_lt (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_le (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_gt (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_ge (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_int2real (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_mk_real2int (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_mk_is_int (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_mk_bvnot (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_mk_bvredand (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_mk_bvredor (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_mk_bvand (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvor (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvxor (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvnand (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvnor (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvxnor (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvneg (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_mk_bvadd (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvsub (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvmul (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvudiv (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvsdiv (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvurem (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvsrem (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvsmod (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvult (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvslt (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvule (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvsle (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvuge (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvsge (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvugt (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvsgt (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_concat (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_extract (Z3_context a0, uint a1, uint a2, Z3_ast a3)
static Z3_ast Z3_mk_sign_ext (Z3_context a0, uint a1, Z3_ast a2)
static Z3_ast Z3_mk_zero_ext (Z3_context a0, uint a1, Z3_ast a2)
static Z3_ast Z3_mk_repeat (Z3_context a0, uint a1, Z3_ast a2)
static Z3_ast Z3_mk_bvshl (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvlshr (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvashr (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_rotate_left (Z3_context a0, uint a1, Z3_ast a2)
static Z3_ast Z3_mk_rotate_right (Z3_context a0, uint a1, Z3_ast a2)
static Z3_ast Z3_mk_ext_rotate_left (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_ext_rotate_right (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_int2bv (Z3_context a0, uint a1, Z3_ast a2)
static Z3_ast Z3_mk_bv2int (Z3_context a0, Z3_ast a1, int a2)
static Z3_ast Z3_mk_bvadd_no_overflow (Z3_context a0, Z3_ast a1, Z3_ast a2, int a3)
static Z3_ast Z3_mk_bvadd_no_underflow (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvsub_no_overflow (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvsub_no_underflow (Z3_context a0, Z3_ast a1, Z3_ast a2, int a3)
static Z3_ast Z3_mk_bvsdiv_no_overflow (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_bvneg_no_overflow (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_mk_bvmul_no_overflow (Z3_context a0, Z3_ast a1, Z3_ast a2, int a3)
static Z3_ast Z3_mk_bvmul_no_underflow (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_select (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_store (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_ast a3)
static Z3_ast Z3_mk_const_array (Z3_context a0, Z3_sort a1, Z3_ast a2)
static Z3_ast Z3_mk_map (Z3_context a0, Z3_func_decl a1, uint a2, [In] Z3_ast[] a3)
static Z3_ast Z3_mk_array_default (Z3_context a0, Z3_ast a1)
static Z3_sort Z3_mk_set_sort (Z3_context a0, Z3_sort a1)
static Z3_ast Z3_mk_empty_set (Z3_context a0, Z3_sort a1)
static Z3_ast Z3_mk_full_set (Z3_context a0, Z3_sort a1)
static Z3_ast Z3_mk_set_add (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_set_del (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_set_union (Z3_context a0, uint a1, [In] Z3_ast[] a2)
static Z3_ast Z3_mk_set_intersect (Z3_context a0, uint a1, [In] Z3_ast[] a2)
static Z3_ast Z3_mk_set_difference (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_set_complement (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_mk_set_member (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_set_subset (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_numeral (Z3_context a0, string a1, Z3_sort a2)
static Z3_ast Z3_mk_real (Z3_context a0, int a1, int a2)
static Z3_ast Z3_mk_int (Z3_context a0, int a1, Z3_sort a2)
static Z3_ast Z3_mk_unsigned_int (Z3_context a0, uint a1, Z3_sort a2)
static Z3_ast Z3_mk_int64 (Z3_context a0, Int64 a1, Z3_sort a2)
static Z3_ast Z3_mk_unsigned_int64 (Z3_context a0, UInt64 a1, Z3_sort a2)
static Z3_pattern Z3_mk_pattern (Z3_context a0, uint a1, [In] Z3_ast[] a2)
static Z3_ast Z3_mk_bound (Z3_context a0, uint a1, Z3_sort a2)
static Z3_ast Z3_mk_forall (Z3_context a0, uint a1, uint a2, [In] Z3_pattern[] a3, uint a4, [In] Z3_sort[] a5, [In] IntPtr[] a6, Z3_ast a7)
static Z3_ast Z3_mk_exists (Z3_context a0, uint a1, uint a2, [In] Z3_pattern[] a3, uint a4, [In] Z3_sort[] a5, [In] IntPtr[] a6, Z3_ast a7)
static Z3_ast Z3_mk_quantifier (Z3_context a0, int a1, uint a2, uint a3, [In] Z3_pattern[] a4, uint a5, [In] Z3_sort[] a6, [In] IntPtr[] a7, Z3_ast a8)
static Z3_ast Z3_mk_quantifier_ex (Z3_context a0, int a1, uint a2, IntPtr a3, IntPtr a4, uint a5, [In] Z3_pattern[] a6, uint a7, [In] Z3_ast[] a8, uint a9, [In] Z3_sort[] a10, [In] IntPtr[] a11, Z3_ast a12)
static Z3_ast Z3_mk_forall_const (Z3_context a0, uint a1, uint a2, [In] Z3_app[] a3, uint a4, [In] Z3_pattern[] a5, Z3_ast a6)
static Z3_ast Z3_mk_exists_const (Z3_context a0, uint a1, uint a2, [In] Z3_app[] a3, uint a4, [In] Z3_pattern[] a5, Z3_ast a6)
static Z3_ast Z3_mk_quantifier_const (Z3_context a0, int a1, uint a2, uint a3, [In] Z3_app[] a4, uint a5, [In] Z3_pattern[] a6, Z3_ast a7)
static Z3_ast Z3_mk_quantifier_const_ex (Z3_context a0, int a1, uint a2, IntPtr a3, IntPtr a4, uint a5, [In] Z3_app[] a6, uint a7, [In] Z3_pattern[] a8, uint a9, [In] Z3_ast[] a10, Z3_ast a11)
static uint Z3_get_symbol_kind (Z3_context a0, IntPtr a1)
static int Z3_get_symbol_int (Z3_context a0, IntPtr a1)
static string Z3_get_symbol_string (Z3_context a0, IntPtr a1)
static IntPtr Z3_get_sort_name (Z3_context a0, Z3_sort a1)
static uint Z3_get_sort_id (Z3_context a0, Z3_sort a1)
static Z3_ast Z3_sort_to_ast (Z3_context a0, Z3_sort a1)
static int Z3_is_eq_sort (Z3_context a0, Z3_sort a1, Z3_sort a2)
static uint Z3_get_sort_kind (Z3_context a0, Z3_sort a1)
static uint Z3_get_bv_sort_size (Z3_context a0, Z3_sort a1)
static int Z3_get_finite_domain_sort_size (Z3_context a0, Z3_sort a1, [In, Out] ref UInt64 a2)
static Z3_sort Z3_get_array_sort_domain (Z3_context a0, Z3_sort a1)
static Z3_sort Z3_get_array_sort_range (Z3_context a0, Z3_sort a1)
static Z3_func_decl Z3_get_tuple_sort_mk_decl (Z3_context a0, Z3_sort a1)
static uint Z3_get_tuple_sort_num_fields (Z3_context a0, Z3_sort a1)
static Z3_func_decl Z3_get_tuple_sort_field_decl (Z3_context a0, Z3_sort a1, uint a2)
static uint Z3_get_datatype_sort_num_constructors (Z3_context a0, Z3_sort a1)
static Z3_func_decl Z3_get_datatype_sort_constructor (Z3_context a0, Z3_sort a1, uint a2)
static Z3_func_decl Z3_get_datatype_sort_recognizer (Z3_context a0, Z3_sort a1, uint a2)
static Z3_func_decl Z3_get_datatype_sort_constructor_accessor (Z3_context a0, Z3_sort a1, uint a2, uint a3)
static uint Z3_get_relation_arity (Z3_context a0, Z3_sort a1)
static Z3_sort Z3_get_relation_column (Z3_context a0, Z3_sort a1, uint a2)
static Z3_ast Z3_func_decl_to_ast (Z3_context a0, Z3_func_decl a1)
static int Z3_is_eq_func_decl (Z3_context a0, Z3_func_decl a1, Z3_func_decl a2)
static uint Z3_get_func_decl_id (Z3_context a0, Z3_func_decl a1)
static IntPtr Z3_get_decl_name (Z3_context a0, Z3_func_decl a1)
static uint Z3_get_decl_kind (Z3_context a0, Z3_func_decl a1)
static uint Z3_get_domain_size (Z3_context a0, Z3_func_decl a1)
static uint Z3_get_arity (Z3_context a0, Z3_func_decl a1)
static Z3_sort Z3_get_domain (Z3_context a0, Z3_func_decl a1, uint a2)
static Z3_sort Z3_get_range (Z3_context a0, Z3_func_decl a1)
static uint Z3_get_decl_num_parameters (Z3_context a0, Z3_func_decl a1)
static uint Z3_get_decl_parameter_kind (Z3_context a0, Z3_func_decl a1, uint a2)
static int Z3_get_decl_int_parameter (Z3_context a0, Z3_func_decl a1, uint a2)
static double Z3_get_decl_double_parameter (Z3_context a0, Z3_func_decl a1, uint a2)
static IntPtr Z3_get_decl_symbol_parameter (Z3_context a0, Z3_func_decl a1, uint a2)
static Z3_sort Z3_get_decl_sort_parameter (Z3_context a0, Z3_func_decl a1, uint a2)
static Z3_ast Z3_get_decl_ast_parameter (Z3_context a0, Z3_func_decl a1, uint a2)
static Z3_func_decl Z3_get_decl_func_decl_parameter (Z3_context a0, Z3_func_decl a1, uint a2)
static string Z3_get_decl_rational_parameter (Z3_context a0, Z3_func_decl a1, uint a2)
static Z3_ast Z3_app_to_ast (Z3_context a0, Z3_app a1)
static Z3_func_decl Z3_get_app_decl (Z3_context a0, Z3_app a1)
static uint Z3_get_app_num_args (Z3_context a0, Z3_app a1)
static Z3_ast Z3_get_app_arg (Z3_context a0, Z3_app a1, uint a2)
static int Z3_is_eq_ast (Z3_context a0, Z3_ast a1, Z3_ast a2)
static uint Z3_get_ast_id (Z3_context a0, Z3_ast a1)
static uint Z3_get_ast_hash (Z3_context a0, Z3_ast a1)
static Z3_sort Z3_get_sort (Z3_context a0, Z3_ast a1)
static int Z3_is_well_sorted (Z3_context a0, Z3_ast a1)
static uint Z3_get_bool_value (Z3_context a0, Z3_ast a1)
static uint Z3_get_ast_kind (Z3_context a0, Z3_ast a1)
static int Z3_is_app (Z3_context a0, Z3_ast a1)
static int Z3_is_numeral_ast (Z3_context a0, Z3_ast a1)
static int Z3_is_algebraic_number (Z3_context a0, Z3_ast a1)
static Z3_app Z3_to_app (Z3_context a0, Z3_ast a1)
static Z3_func_decl Z3_to_func_decl (Z3_context a0, Z3_ast a1)
static string Z3_get_numeral_string (Z3_context a0, Z3_ast a1)
static string Z3_get_numeral_decimal_string (Z3_context a0, Z3_ast a1, uint a2)
static Z3_ast Z3_get_numerator (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_get_denominator (Z3_context a0, Z3_ast a1)
static int Z3_get_numeral_small (Z3_context a0, Z3_ast a1, [In, Out] ref Int64 a2, [In, Out] ref Int64 a3)
static int Z3_get_numeral_int (Z3_context a0, Z3_ast a1, [In, Out] ref int a2)
static int Z3_get_numeral_uint (Z3_context a0, Z3_ast a1, [In, Out] ref uint a2)
static int Z3_get_numeral_uint64 (Z3_context a0, Z3_ast a1, [In, Out] ref UInt64 a2)
static int Z3_get_numeral_int64 (Z3_context a0, Z3_ast a1, [In, Out] ref Int64 a2)
static int Z3_get_numeral_rational_int64 (Z3_context a0, Z3_ast a1, [In, Out] ref Int64 a2, [In, Out] ref Int64 a3)
static Z3_ast Z3_get_algebraic_number_lower (Z3_context a0, Z3_ast a1, uint a2)
static Z3_ast Z3_get_algebraic_number_upper (Z3_context a0, Z3_ast a1, uint a2)
static Z3_ast Z3_pattern_to_ast (Z3_context a0, Z3_pattern a1)
static uint Z3_get_pattern_num_terms (Z3_context a0, Z3_pattern a1)
static Z3_ast Z3_get_pattern (Z3_context a0, Z3_pattern a1, uint a2)
static uint Z3_get_index_value (Z3_context a0, Z3_ast a1)
static int Z3_is_quantifier_forall (Z3_context a0, Z3_ast a1)
static uint Z3_get_quantifier_weight (Z3_context a0, Z3_ast a1)
static uint Z3_get_quantifier_num_patterns (Z3_context a0, Z3_ast a1)
static Z3_pattern Z3_get_quantifier_pattern_ast (Z3_context a0, Z3_ast a1, uint a2)
static uint Z3_get_quantifier_num_no_patterns (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_get_quantifier_no_pattern_ast (Z3_context a0, Z3_ast a1, uint a2)
static uint Z3_get_quantifier_num_bound (Z3_context a0, Z3_ast a1)
static IntPtr Z3_get_quantifier_bound_name (Z3_context a0, Z3_ast a1, uint a2)
static Z3_sort Z3_get_quantifier_bound_sort (Z3_context a0, Z3_ast a1, uint a2)
static Z3_ast Z3_get_quantifier_body (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_simplify (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_simplify_ex (Z3_context a0, Z3_ast a1, Z3_params a2)
static string Z3_simplify_get_help (Z3_context a0)
static Z3_param_descrs Z3_simplify_get_param_descrs (Z3_context a0)
static Z3_ast Z3_update_term (Z3_context a0, Z3_ast a1, uint a2, [In] Z3_ast[] a3)
static Z3_ast Z3_substitute (Z3_context a0, Z3_ast a1, uint a2, [In] Z3_ast[] a3, [In] Z3_ast[] a4)
static Z3_ast Z3_substitute_vars (Z3_context a0, Z3_ast a1, uint a2, [In] Z3_ast[] a3)
static Z3_ast Z3_translate (Z3_context a0, Z3_ast a1, Z3_context a2)
static void Z3_model_inc_ref (Z3_context a0, Z3_model a1)
static void Z3_model_dec_ref (Z3_context a0, Z3_model a1)
static int Z3_model_eval (Z3_context a0, Z3_model a1, Z3_ast a2, int a3, [In, Out] ref Z3_ast a4)
static Z3_ast Z3_model_get_const_interp (Z3_context a0, Z3_model a1, Z3_func_decl a2)
static Z3_func_interp Z3_model_get_func_interp (Z3_context a0, Z3_model a1, Z3_func_decl a2)
static uint Z3_model_get_num_consts (Z3_context a0, Z3_model a1)
static Z3_func_decl Z3_model_get_const_decl (Z3_context a0, Z3_model a1, uint a2)
static uint Z3_model_get_num_funcs (Z3_context a0, Z3_model a1)
static Z3_func_decl Z3_model_get_func_decl (Z3_context a0, Z3_model a1, uint a2)
static uint Z3_model_get_num_sorts (Z3_context a0, Z3_model a1)
static Z3_sort Z3_model_get_sort (Z3_context a0, Z3_model a1, uint a2)
static Z3_ast_vector Z3_model_get_sort_universe (Z3_context a0, Z3_model a1, Z3_sort a2)
static int Z3_is_as_array (Z3_context a0, Z3_ast a1)
static Z3_func_decl Z3_get_as_array_func_decl (Z3_context a0, Z3_ast a1)
static void Z3_func_interp_inc_ref (Z3_context a0, Z3_func_interp a1)
static void Z3_func_interp_dec_ref (Z3_context a0, Z3_func_interp a1)
static uint Z3_func_interp_get_num_entries (Z3_context a0, Z3_func_interp a1)
static Z3_func_entry Z3_func_interp_get_entry (Z3_context a0, Z3_func_interp a1, uint a2)
static Z3_ast Z3_func_interp_get_else (Z3_context a0, Z3_func_interp a1)
static uint Z3_func_interp_get_arity (Z3_context a0, Z3_func_interp a1)
static void Z3_func_entry_inc_ref (Z3_context a0, Z3_func_entry a1)
static void Z3_func_entry_dec_ref (Z3_context a0, Z3_func_entry a1)
static Z3_ast Z3_func_entry_get_value (Z3_context a0, Z3_func_entry a1)
static uint Z3_func_entry_get_num_args (Z3_context a0, Z3_func_entry a1)
static Z3_ast Z3_func_entry_get_arg (Z3_context a0, Z3_func_entry a1, uint a2)
static int Z3_open_log (string a0)
static void Z3_append_log (string a0)
static void Z3_close_log ()
static void Z3_toggle_warning_messages (int a0)
static void Z3_set_ast_print_mode (Z3_context a0, uint a1)
static string Z3_ast_to_string (Z3_context a0, Z3_ast a1)
static string Z3_pattern_to_string (Z3_context a0, Z3_pattern a1)
static string Z3_sort_to_string (Z3_context a0, Z3_sort a1)
static string Z3_func_decl_to_string (Z3_context a0, Z3_func_decl a1)
static string Z3_model_to_string (Z3_context a0, Z3_model a1)
static string Z3_benchmark_to_smtlib_string (Z3_context a0, string a1, string a2, string a3, string a4, uint a5, [In] Z3_ast[] a6, Z3_ast a7)
static Z3_ast Z3_parse_smtlib2_string (Z3_context a0, string a1, uint a2, [In] IntPtr[] a3, [In] Z3_sort[] a4, uint a5, [In] IntPtr[] a6, [In] Z3_func_decl[] a7)
static Z3_ast Z3_parse_smtlib2_file (Z3_context a0, string a1, uint a2, [In] IntPtr[] a3, [In] Z3_sort[] a4, uint a5, [In] IntPtr[] a6, [In] Z3_func_decl[] a7)
static void Z3_parse_smtlib_string (Z3_context a0, string a1, uint a2, [In] IntPtr[] a3, [In] Z3_sort[] a4, uint a5, [In] IntPtr[] a6, [In] Z3_func_decl[] a7)
static void Z3_parse_smtlib_file (Z3_context a0, string a1, uint a2, [In] IntPtr[] a3, [In] Z3_sort[] a4, uint a5, [In] IntPtr[] a6, [In] Z3_func_decl[] a7)
static uint Z3_get_smtlib_num_formulas (Z3_context a0)
static Z3_ast Z3_get_smtlib_formula (Z3_context a0, uint a1)
static uint Z3_get_smtlib_num_assumptions (Z3_context a0)
static Z3_ast Z3_get_smtlib_assumption (Z3_context a0, uint a1)
static uint Z3_get_smtlib_num_decls (Z3_context a0)
static Z3_func_decl Z3_get_smtlib_decl (Z3_context a0, uint a1)
static uint Z3_get_smtlib_num_sorts (Z3_context a0)
static Z3_sort Z3_get_smtlib_sort (Z3_context a0, uint a1)
static string Z3_get_smtlib_error (Z3_context a0)
static uint Z3_get_error_code (Z3_context a0)
static void Z3_set_error (Z3_context a0, uint a1)
static string Z3_get_error_msg (uint a0)
static string Z3_get_error_msg_ex (Z3_context a0, uint a1)
static void Z3_get_version ([In, Out] ref uint a0, [In, Out] ref uint a1, [In, Out] ref uint a2, [In, Out] ref uint a3)
static void Z3_enable_trace (string a0)
static void Z3_disable_trace (string a0)
static void Z3_reset_memory ()
static Z3_fixedpoint Z3_mk_fixedpoint (Z3_context a0)
static void Z3_fixedpoint_inc_ref (Z3_context a0, Z3_fixedpoint a1)
static void Z3_fixedpoint_dec_ref (Z3_context a0, Z3_fixedpoint a1)
static void Z3_fixedpoint_add_rule (Z3_context a0, Z3_fixedpoint a1, Z3_ast a2, IntPtr a3)
static void Z3_fixedpoint_add_fact (Z3_context a0, Z3_fixedpoint a1, Z3_func_decl a2, uint a3, [In] uint[] a4)
static void Z3_fixedpoint_assert (Z3_context a0, Z3_fixedpoint a1, Z3_ast a2)
static int Z3_fixedpoint_query (Z3_context a0, Z3_fixedpoint a1, Z3_ast a2)
static int Z3_fixedpoint_query_relations (Z3_context a0, Z3_fixedpoint a1, uint a2, [In] Z3_func_decl[] a3)
static Z3_ast Z3_fixedpoint_get_answer (Z3_context a0, Z3_fixedpoint a1)
static string Z3_fixedpoint_get_reason_unknown (Z3_context a0, Z3_fixedpoint a1)
static void Z3_fixedpoint_update_rule (Z3_context a0, Z3_fixedpoint a1, Z3_ast a2, IntPtr a3)
static uint Z3_fixedpoint_get_num_levels (Z3_context a0, Z3_fixedpoint a1, Z3_func_decl a2)
static Z3_ast Z3_fixedpoint_get_cover_delta (Z3_context a0, Z3_fixedpoint a1, int a2, Z3_func_decl a3)
static void Z3_fixedpoint_add_cover (Z3_context a0, Z3_fixedpoint a1, int a2, Z3_func_decl a3, Z3_ast a4)
static Z3_stats Z3_fixedpoint_get_statistics (Z3_context a0, Z3_fixedpoint a1)
static void Z3_fixedpoint_register_relation (Z3_context a0, Z3_fixedpoint a1, Z3_func_decl a2)
static void Z3_fixedpoint_set_predicate_representation (Z3_context a0, Z3_fixedpoint a1, Z3_func_decl a2, uint a3, [In] IntPtr[] a4)
static Z3_ast_vector Z3_fixedpoint_get_rules (Z3_context a0, Z3_fixedpoint a1)
static Z3_ast_vector Z3_fixedpoint_get_assertions (Z3_context a0, Z3_fixedpoint a1)
static void Z3_fixedpoint_set_params (Z3_context a0, Z3_fixedpoint a1, Z3_params a2)
static string Z3_fixedpoint_get_help (Z3_context a0, Z3_fixedpoint a1)
static Z3_param_descrs Z3_fixedpoint_get_param_descrs (Z3_context a0, Z3_fixedpoint a1)
static string Z3_fixedpoint_to_string (Z3_context a0, Z3_fixedpoint a1, uint a2, [In] Z3_ast[] a3)
static Z3_ast_vector Z3_fixedpoint_from_string (Z3_context a0, Z3_fixedpoint a1, string a2)
static Z3_ast_vector Z3_fixedpoint_from_file (Z3_context a0, Z3_fixedpoint a1, string a2)
static void Z3_fixedpoint_push (Z3_context a0, Z3_fixedpoint a1)
static void Z3_fixedpoint_pop (Z3_context a0, Z3_fixedpoint a1)
static Z3_ast_vector Z3_mk_ast_vector (Z3_context a0)
static void Z3_ast_vector_inc_ref (Z3_context a0, Z3_ast_vector a1)
static void Z3_ast_vector_dec_ref (Z3_context a0, Z3_ast_vector a1)
static uint Z3_ast_vector_size (Z3_context a0, Z3_ast_vector a1)
static Z3_ast Z3_ast_vector_get (Z3_context a0, Z3_ast_vector a1, uint a2)
static void Z3_ast_vector_set (Z3_context a0, Z3_ast_vector a1, uint a2, Z3_ast a3)
static void Z3_ast_vector_resize (Z3_context a0, Z3_ast_vector a1, uint a2)
static void Z3_ast_vector_push (Z3_context a0, Z3_ast_vector a1, Z3_ast a2)
static Z3_ast_vector Z3_ast_vector_translate (Z3_context a0, Z3_ast_vector a1, Z3_context a2)
static string Z3_ast_vector_to_string (Z3_context a0, Z3_ast_vector a1)
static Z3_ast_map Z3_mk_ast_map (Z3_context a0)
static void Z3_ast_map_inc_ref (Z3_context a0, Z3_ast_map a1)
static void Z3_ast_map_dec_ref (Z3_context a0, Z3_ast_map a1)
static int Z3_ast_map_contains (Z3_context a0, Z3_ast_map a1, Z3_ast a2)
static Z3_ast Z3_ast_map_find (Z3_context a0, Z3_ast_map a1, Z3_ast a2)
static void Z3_ast_map_insert (Z3_context a0, Z3_ast_map a1, Z3_ast a2, Z3_ast a3)
static void Z3_ast_map_erase (Z3_context a0, Z3_ast_map a1, Z3_ast a2)
static void Z3_ast_map_reset (Z3_context a0, Z3_ast_map a1)
static uint Z3_ast_map_size (Z3_context a0, Z3_ast_map a1)
static Z3_ast_vector Z3_ast_map_keys (Z3_context a0, Z3_ast_map a1)
static string Z3_ast_map_to_string (Z3_context a0, Z3_ast_map a1)
static Z3_goal Z3_mk_goal (Z3_context a0, int a1, int a2, int a3)
static void Z3_goal_inc_ref (Z3_context a0, Z3_goal a1)
static void Z3_goal_dec_ref (Z3_context a0, Z3_goal a1)
static uint Z3_goal_precision (Z3_context a0, Z3_goal a1)
static void Z3_goal_assert (Z3_context a0, Z3_goal a1, Z3_ast a2)
static int Z3_goal_inconsistent (Z3_context a0, Z3_goal a1)
static uint Z3_goal_depth (Z3_context a0, Z3_goal a1)
static void Z3_goal_reset (Z3_context a0, Z3_goal a1)
static uint Z3_goal_size (Z3_context a0, Z3_goal a1)
static Z3_ast Z3_goal_formula (Z3_context a0, Z3_goal a1, uint a2)
static uint Z3_goal_num_exprs (Z3_context a0, Z3_goal a1)
static int Z3_goal_is_decided_sat (Z3_context a0, Z3_goal a1)
static int Z3_goal_is_decided_unsat (Z3_context a0, Z3_goal a1)
static Z3_goal Z3_goal_translate (Z3_context a0, Z3_goal a1, Z3_context a2)
static string Z3_goal_to_string (Z3_context a0, Z3_goal a1)
static Z3_tactic Z3_mk_tactic (Z3_context a0, string a1)
static void Z3_tactic_inc_ref (Z3_context a0, Z3_tactic a1)
static void Z3_tactic_dec_ref (Z3_context a0, Z3_tactic a1)
static Z3_probe Z3_mk_probe (Z3_context a0, string a1)
static void Z3_probe_inc_ref (Z3_context a0, Z3_probe a1)
static void Z3_probe_dec_ref (Z3_context a0, Z3_probe a1)
static Z3_tactic Z3_tactic_and_then (Z3_context a0, Z3_tactic a1, Z3_tactic a2)
static Z3_tactic Z3_tactic_or_else (Z3_context a0, Z3_tactic a1, Z3_tactic a2)
static Z3_tactic Z3_tactic_par_or (Z3_context a0, uint a1, [In] Z3_tactic[] a2)
static Z3_tactic Z3_tactic_par_and_then (Z3_context a0, Z3_tactic a1, Z3_tactic a2)
static Z3_tactic Z3_tactic_try_for (Z3_context a0, Z3_tactic a1, uint a2)
static Z3_tactic Z3_tactic_when (Z3_context a0, Z3_probe a1, Z3_tactic a2)
static Z3_tactic Z3_tactic_cond (Z3_context a0, Z3_probe a1, Z3_tactic a2, Z3_tactic a3)
static Z3_tactic Z3_tactic_repeat (Z3_context a0, Z3_tactic a1, uint a2)
static Z3_tactic Z3_tactic_skip (Z3_context a0)
static Z3_tactic Z3_tactic_fail (Z3_context a0)
static Z3_tactic Z3_tactic_fail_if (Z3_context a0, Z3_probe a1)
static Z3_tactic Z3_tactic_fail_if_not_decided (Z3_context a0)
static Z3_tactic Z3_tactic_using_params (Z3_context a0, Z3_tactic a1, Z3_params a2)
static Z3_probe Z3_probe_const (Z3_context a0, double a1)
static Z3_probe Z3_probe_lt (Z3_context a0, Z3_probe a1, Z3_probe a2)
static Z3_probe Z3_probe_gt (Z3_context a0, Z3_probe a1, Z3_probe a2)
static Z3_probe Z3_probe_le (Z3_context a0, Z3_probe a1, Z3_probe a2)
static Z3_probe Z3_probe_ge (Z3_context a0, Z3_probe a1, Z3_probe a2)
static Z3_probe Z3_probe_eq (Z3_context a0, Z3_probe a1, Z3_probe a2)
static Z3_probe Z3_probe_and (Z3_context a0, Z3_probe a1, Z3_probe a2)
static Z3_probe Z3_probe_or (Z3_context a0, Z3_probe a1, Z3_probe a2)
static Z3_probe Z3_probe_not (Z3_context a0, Z3_probe a1)
static uint Z3_get_num_tactics (Z3_context a0)
static string Z3_get_tactic_name (Z3_context a0, uint a1)
static uint Z3_get_num_probes (Z3_context a0)
static string Z3_get_probe_name (Z3_context a0, uint a1)
static string Z3_tactic_get_help (Z3_context a0, Z3_tactic a1)
static Z3_param_descrs Z3_tactic_get_param_descrs (Z3_context a0, Z3_tactic a1)
static string Z3_tactic_get_descr (Z3_context a0, string a1)
static string Z3_probe_get_descr (Z3_context a0, string a1)
static double Z3_probe_apply (Z3_context a0, Z3_probe a1, Z3_goal a2)
static Z3_apply_result Z3_tactic_apply (Z3_context a0, Z3_tactic a1, Z3_goal a2)
static Z3_apply_result Z3_tactic_apply_ex (Z3_context a0, Z3_tactic a1, Z3_goal a2, Z3_params a3)
static void Z3_apply_result_inc_ref (Z3_context a0, Z3_apply_result a1)
static void Z3_apply_result_dec_ref (Z3_context a0, Z3_apply_result a1)
static string Z3_apply_result_to_string (Z3_context a0, Z3_apply_result a1)
static uint Z3_apply_result_get_num_subgoals (Z3_context a0, Z3_apply_result a1)
static Z3_goal Z3_apply_result_get_subgoal (Z3_context a0, Z3_apply_result a1, uint a2)
static Z3_model Z3_apply_result_convert_model (Z3_context a0, Z3_apply_result a1, uint a2, Z3_model a3)
static Z3_solver Z3_mk_solver (Z3_context a0)
static Z3_solver Z3_mk_simple_solver (Z3_context a0)
static Z3_solver Z3_mk_solver_for_logic (Z3_context a0, IntPtr a1)
static Z3_solver Z3_mk_solver_from_tactic (Z3_context a0, Z3_tactic a1)
static string Z3_solver_get_help (Z3_context a0, Z3_solver a1)
static Z3_param_descrs Z3_solver_get_param_descrs (Z3_context a0, Z3_solver a1)
static void Z3_solver_set_params (Z3_context a0, Z3_solver a1, Z3_params a2)
static void Z3_solver_inc_ref (Z3_context a0, Z3_solver a1)
static void Z3_solver_dec_ref (Z3_context a0, Z3_solver a1)
static void Z3_solver_push (Z3_context a0, Z3_solver a1)
static void Z3_solver_pop (Z3_context a0, Z3_solver a1, uint a2)
static void Z3_solver_reset (Z3_context a0, Z3_solver a1)
static uint Z3_solver_get_num_scopes (Z3_context a0, Z3_solver a1)
static void Z3_solver_assert (Z3_context a0, Z3_solver a1, Z3_ast a2)
static void Z3_solver_assert_and_track (Z3_context a0, Z3_solver a1, Z3_ast a2, Z3_ast a3)
static Z3_ast_vector Z3_solver_get_assertions (Z3_context a0, Z3_solver a1)
static int Z3_solver_check (Z3_context a0, Z3_solver a1)
static int Z3_solver_check_assumptions (Z3_context a0, Z3_solver a1, uint a2, [In] Z3_ast[] a3)
static Z3_model Z3_solver_get_model (Z3_context a0, Z3_solver a1)
static Z3_ast Z3_solver_get_proof (Z3_context a0, Z3_solver a1)
static Z3_ast_vector Z3_solver_get_unsat_core (Z3_context a0, Z3_solver a1)
static string Z3_solver_get_reason_unknown (Z3_context a0, Z3_solver a1)
static Z3_stats Z3_solver_get_statistics (Z3_context a0, Z3_solver a1)
static string Z3_solver_to_string (Z3_context a0, Z3_solver a1)
static string Z3_stats_to_string (Z3_context a0, Z3_stats a1)
static void Z3_stats_inc_ref (Z3_context a0, Z3_stats a1)
static void Z3_stats_dec_ref (Z3_context a0, Z3_stats a1)
static uint Z3_stats_size (Z3_context a0, Z3_stats a1)
static string Z3_stats_get_key (Z3_context a0, Z3_stats a1, uint a2)
static int Z3_stats_is_uint (Z3_context a0, Z3_stats a1, uint a2)
static int Z3_stats_is_double (Z3_context a0, Z3_stats a1, uint a2)
static uint Z3_stats_get_uint_value (Z3_context a0, Z3_stats a1, uint a2)
static double Z3_stats_get_double_value (Z3_context a0, Z3_stats a1, uint a2)
static Z3_func_decl Z3_mk_injective_function (Z3_context a0, IntPtr a1, uint a2, [In] Z3_sort[] a3, Z3_sort a4)
static void Z3_set_logic (Z3_context a0, string a1)
static void Z3_push (Z3_context a0)
static void Z3_pop (Z3_context a0, uint a1)
static uint Z3_get_num_scopes (Z3_context a0)
static void Z3_persist_ast (Z3_context a0, Z3_ast a1, uint a2)
static void Z3_assert_cnstr (Z3_context a0, Z3_ast a1)
static int Z3_check_and_get_model (Z3_context a0, [In, Out] ref Z3_model a1)
static int Z3_check (Z3_context a0)
static int Z3_check_assumptions (Z3_context a0, uint a1, [In] Z3_ast[] a2, [In, Out] ref Z3_model a3, [In, Out] ref Z3_ast a4, [In, Out] ref uint a5, [Out] Z3_ast[] a6)
static uint Z3_get_implied_equalities (Z3_context a0, Z3_solver a1, uint a2, [In] Z3_ast[] a3, [Out] uint[] a4)
static void Z3_del_model (Z3_context a0, Z3_model a1)
static void Z3_soft_check_cancel (Z3_context a0)
static uint Z3_get_search_failure (Z3_context a0)
static Z3_ast Z3_mk_label (Z3_context a0, IntPtr a1, int a2, Z3_ast a3)
static Z3_literals Z3_get_relevant_labels (Z3_context a0)
static Z3_literals Z3_get_relevant_literals (Z3_context a0)
static Z3_literals Z3_get_guessed_literals (Z3_context a0)
static void Z3_del_literals (Z3_context a0, Z3_literals a1)
static uint Z3_get_num_literals (Z3_context a0, Z3_literals a1)
static IntPtr Z3_get_label_symbol (Z3_context a0, Z3_literals a1, uint a2)
static Z3_ast Z3_get_literal (Z3_context a0, Z3_literals a1, uint a2)
static void Z3_disable_literal (Z3_context a0, Z3_literals a1, uint a2)
static void Z3_block_literals (Z3_context a0, Z3_literals a1)
static uint Z3_get_model_num_constants (Z3_context a0, Z3_model a1)
static Z3_func_decl Z3_get_model_constant (Z3_context a0, Z3_model a1, uint a2)
static uint Z3_get_model_num_funcs (Z3_context a0, Z3_model a1)
static Z3_func_decl Z3_get_model_func_decl (Z3_context a0, Z3_model a1, uint a2)
static int Z3_eval_func_decl (Z3_context a0, Z3_model a1, Z3_func_decl a2, [In, Out] ref Z3_ast a3)
static int Z3_is_array_value (Z3_context a0, Z3_model a1, Z3_ast a2, [In, Out] ref uint a3)
static void Z3_get_array_value (Z3_context a0, Z3_model a1, Z3_ast a2, uint a3, [Out] Z3_ast[] a4, [Out] Z3_ast[] a5, [In, Out] ref Z3_ast a6)
static Z3_ast Z3_get_model_func_else (Z3_context a0, Z3_model a1, uint a2)
static uint Z3_get_model_func_num_entries (Z3_context a0, Z3_model a1, uint a2)
static uint Z3_get_model_func_entry_num_args (Z3_context a0, Z3_model a1, uint a2, uint a3)
static Z3_ast Z3_get_model_func_entry_arg (Z3_context a0, Z3_model a1, uint a2, uint a3, uint a4)
static Z3_ast Z3_get_model_func_entry_value (Z3_context a0, Z3_model a1, uint a2, uint a3)
static int Z3_eval (Z3_context a0, Z3_model a1, Z3_ast a2, [In, Out] ref Z3_ast a3)
static int Z3_eval_decl (Z3_context a0, Z3_model a1, Z3_func_decl a2, uint a3, [In] Z3_ast[] a4, [In, Out] ref Z3_ast a5)
static string Z3_context_to_string (Z3_context a0)
static string Z3_statistics_to_string (Z3_context a0)
static Z3_ast Z3_get_context_assignment (Z3_context a0)
static int Z3_algebraic_is_value (Z3_context a0, Z3_ast a1)
static int Z3_algebraic_is_pos (Z3_context a0, Z3_ast a1)
static int Z3_algebraic_is_neg (Z3_context a0, Z3_ast a1)
static int Z3_algebraic_is_zero (Z3_context a0, Z3_ast a1)
static int Z3_algebraic_sign (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_algebraic_add (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_algebraic_sub (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_algebraic_mul (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_algebraic_div (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_algebraic_root (Z3_context a0, Z3_ast a1, uint a2)
static Z3_ast Z3_algebraic_power (Z3_context a0, Z3_ast a1, uint a2)
static int Z3_algebraic_lt (Z3_context a0, Z3_ast a1, Z3_ast a2)
static int Z3_algebraic_gt (Z3_context a0, Z3_ast a1, Z3_ast a2)
static int Z3_algebraic_le (Z3_context a0, Z3_ast a1, Z3_ast a2)
static int Z3_algebraic_ge (Z3_context a0, Z3_ast a1, Z3_ast a2)
static int Z3_algebraic_eq (Z3_context a0, Z3_ast a1, Z3_ast a2)
static int Z3_algebraic_neq (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast_vector Z3_algebraic_roots (Z3_context a0, Z3_ast a1, uint a2, [In] Z3_ast[] a3)
static int Z3_algebraic_eval (Z3_context a0, Z3_ast a1, uint a2, [In] Z3_ast[] a3)
static Z3_ast_vector Z3_polynomial_subresultants (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_ast a3)
static void Z3_rcf_del (Z3_context a0, Z3_rcf_num a1)
static Z3_rcf_num Z3_rcf_mk_rational (Z3_context a0, string a1)
static Z3_rcf_num Z3_rcf_mk_small_int (Z3_context a0, int a1)
static Z3_rcf_num Z3_rcf_mk_pi (Z3_context a0)
static Z3_rcf_num Z3_rcf_mk_e (Z3_context a0)
static Z3_rcf_num Z3_rcf_mk_infinitesimal (Z3_context a0)
static uint Z3_rcf_mk_roots (Z3_context a0, uint a1, [In] Z3_rcf_num[] a2, [Out] Z3_rcf_num[] a3)
static Z3_rcf_num Z3_rcf_add (Z3_context a0, Z3_rcf_num a1, Z3_rcf_num a2)
static Z3_rcf_num Z3_rcf_sub (Z3_context a0, Z3_rcf_num a1, Z3_rcf_num a2)
static Z3_rcf_num Z3_rcf_mul (Z3_context a0, Z3_rcf_num a1, Z3_rcf_num a2)
static Z3_rcf_num Z3_rcf_div (Z3_context a0, Z3_rcf_num a1, Z3_rcf_num a2)
static Z3_rcf_num Z3_rcf_neg (Z3_context a0, Z3_rcf_num a1)
static Z3_rcf_num Z3_rcf_inv (Z3_context a0, Z3_rcf_num a1)
static Z3_rcf_num Z3_rcf_power (Z3_context a0, Z3_rcf_num a1, uint a2)
static int Z3_rcf_lt (Z3_context a0, Z3_rcf_num a1, Z3_rcf_num a2)
static int Z3_rcf_gt (Z3_context a0, Z3_rcf_num a1, Z3_rcf_num a2)
static int Z3_rcf_le (Z3_context a0, Z3_rcf_num a1, Z3_rcf_num a2)
static int Z3_rcf_ge (Z3_context a0, Z3_rcf_num a1, Z3_rcf_num a2)
static int Z3_rcf_eq (Z3_context a0, Z3_rcf_num a1, Z3_rcf_num a2)
static int Z3_rcf_neq (Z3_context a0, Z3_rcf_num a1, Z3_rcf_num a2)
static string Z3_rcf_num_to_string (Z3_context a0, Z3_rcf_num a1, int a2, int a3)
static string Z3_rcf_num_to_decimal_string (Z3_context a0, Z3_rcf_num a1, uint a2)
static void Z3_rcf_get_numerator_denominator (Z3_context a0, Z3_rcf_num a1, [In, Out] ref Z3_rcf_num a2, [In, Out] ref Z3_rcf_num a3)
static Z3_ast Z3_mk_interpolant (Z3_context a0, Z3_ast a1)
static Z3_context Z3_mk_interpolation_context (Z3_config a0)
static Z3_ast_vector Z3_get_interpolant (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_params a3)
static int Z3_compute_interpolant (Z3_context a0, Z3_ast a1, Z3_params a2, [In, Out] ref Z3_ast_vector a3, [In, Out] ref Z3_model a4)
static string Z3_interpolation_profile (Z3_context a0)
static int Z3_read_interpolation_problem (Z3_context a0, [In, Out] ref uint a1, [Out] out Z3_ast[] a2, [Out] out uint[] a3, string a4, out IntPtr a5, [In, Out] ref uint a6, [Out] out Z3_ast[] a7)
static int Z3_check_interpolant (Z3_context a0, uint a1, [In] Z3_ast[] a2, [In] uint[] a3, [In] Z3_ast[] a4, out IntPtr a5, uint a6, [In] Z3_ast[] a7)
static void Z3_write_interpolation_problem (Z3_context a0, uint a1, [In] Z3_ast[] a2, [In] uint[] a3, string a4, uint a5, [In] Z3_ast[] a6)
static Z3_sort Z3_mk_fpa_rounding_mode_sort (Z3_context a0)
static Z3_ast Z3_mk_fpa_round_nearest_ties_to_even (Z3_context a0)
static Z3_ast Z3_mk_fpa_rne (Z3_context a0)
static Z3_ast Z3_mk_fpa_round_nearest_ties_to_away (Z3_context a0)
static Z3_ast Z3_mk_fpa_rna (Z3_context a0)
static Z3_ast Z3_mk_fpa_round_toward_positive (Z3_context a0)
static Z3_ast Z3_mk_fpa_rtp (Z3_context a0)
static Z3_ast Z3_mk_fpa_round_toward_negative (Z3_context a0)
static Z3_ast Z3_mk_fpa_rtn (Z3_context a0)
static Z3_ast Z3_mk_fpa_round_toward_zero (Z3_context a0)
static Z3_ast Z3_mk_fpa_rtz (Z3_context a0)
static Z3_sort Z3_mk_fpa_sort (Z3_context a0, uint a1, uint a2)
static Z3_sort Z3_mk_fpa_sort_half (Z3_context a0)
static Z3_sort Z3_mk_fpa_sort_16 (Z3_context a0)
static Z3_sort Z3_mk_fpa_sort_single (Z3_context a0)
static Z3_sort Z3_mk_fpa_sort_32 (Z3_context a0)
static Z3_sort Z3_mk_fpa_sort_double (Z3_context a0)
static Z3_sort Z3_mk_fpa_sort_64 (Z3_context a0)
static Z3_sort Z3_mk_fpa_sort_quadruple (Z3_context a0)
static Z3_sort Z3_mk_fpa_sort_128 (Z3_context a0)
static Z3_ast Z3_mk_fpa_nan (Z3_context a0, Z3_sort a1)
static Z3_ast Z3_mk_fpa_inf (Z3_context a0, Z3_sort a1, int a2)
static Z3_ast Z3_mk_fpa_zero (Z3_context a0, Z3_sort a1, int a2)
static Z3_ast Z3_mk_fpa_fp (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_ast a3)
static Z3_ast Z3_mk_fpa_numeral_float (Z3_context a0, float a1, Z3_sort a2)
static Z3_ast Z3_mk_fpa_numeral_double (Z3_context a0, double a1, Z3_sort a2)
static Z3_ast Z3_mk_fpa_numeral_int (Z3_context a0, int a1, Z3_sort a2)
static Z3_ast Z3_mk_fpa_numeral_int_uint (Z3_context a0, int a1, int a2, uint a3, Z3_sort a4)
static Z3_ast Z3_mk_fpa_numeral_int64_uint64 (Z3_context a0, int a1, Int64 a2, UInt64 a3, Z3_sort a4)
static Z3_ast Z3_mk_fpa_abs (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_mk_fpa_neg (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_mk_fpa_add (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_ast a3)
static Z3_ast Z3_mk_fpa_sub (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_ast a3)
static Z3_ast Z3_mk_fpa_mul (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_ast a3)
static Z3_ast Z3_mk_fpa_div (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_ast a3)
static Z3_ast Z3_mk_fpa_fma (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_ast a3, Z3_ast a4)
static Z3_ast Z3_mk_fpa_sqrt (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_fpa_rem (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_fpa_round_to_integral (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_fpa_min (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_fpa_max (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_fpa_leq (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_fpa_lt (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_fpa_geq (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_fpa_gt (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_fpa_eq (Z3_context a0, Z3_ast a1, Z3_ast a2)
static Z3_ast Z3_mk_fpa_is_normal (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_mk_fpa_is_subnormal (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_mk_fpa_is_zero (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_mk_fpa_is_infinite (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_mk_fpa_is_nan (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_mk_fpa_is_negative (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_mk_fpa_is_positive (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_mk_fpa_to_fp_bv (Z3_context a0, Z3_ast a1, Z3_sort a2)
static Z3_ast Z3_mk_fpa_to_fp_float (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_sort a3)
static Z3_ast Z3_mk_fpa_to_fp_real (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_sort a3)
static Z3_ast Z3_mk_fpa_to_fp_signed (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_sort a3)
static Z3_ast Z3_mk_fpa_to_fp_unsigned (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_sort a3)
static Z3_ast Z3_mk_fpa_to_ubv (Z3_context a0, Z3_ast a1, Z3_ast a2, uint a3)
static Z3_ast Z3_mk_fpa_to_sbv (Z3_context a0, Z3_ast a1, Z3_ast a2, uint a3)
static Z3_ast Z3_mk_fpa_to_real (Z3_context a0, Z3_ast a1)
static uint Z3_fpa_get_ebits (Z3_context a0, Z3_sort a1)
static uint Z3_fpa_get_sbits (Z3_context a0, Z3_sort a1)
static int Z3_fpa_get_numeral_sign (Z3_context a0, Z3_ast a1, [In, Out] ref int a2)
static string Z3_fpa_get_numeral_significand_string (Z3_context a0, Z3_ast a1)
static string Z3_fpa_get_numeral_exponent_string (Z3_context a0, Z3_ast a1)
static int Z3_fpa_get_numeral_exponent_int64 (Z3_context a0, Z3_ast a1, [In, Out] ref Int64 a2)
static Z3_ast Z3_mk_fpa_to_ieee_bv (Z3_context a0, Z3_ast a1)
static Z3_ast Z3_mk_fpa_to_fp_int_real (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_ast a3, Z3_sort a4)
Detailed Description
Definition at line 39 of file Native.cs.
Member Function Documentation
static Z3_ast Z3_algebraic_add (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 5662 of file Native.cs.
{
             Z3_ast r = LIB.Z3_algebraic_add(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_algebraic_div (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 5686 of file Native.cs.
{
             Z3_ast r = LIB.Z3_algebraic_div(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_algebraic_eq (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 5742 of file Native.cs.
{
             int r = LIB.Z3_algebraic_eq(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_algebraic_eval (Z3_context a0, Z3_ast a1, uint a2, [In] Z3_ast[] a3) inline static
Definition at line 5766 of file Native.cs.
{
             int r = LIB.Z3_algebraic_eval(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_algebraic_ge (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 5734 of file Native.cs.
{
             int r = LIB.Z3_algebraic_ge(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_algebraic_gt (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 5718 of file Native.cs.
{
             int r = LIB.Z3_algebraic_gt(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_algebraic_is_neg (Z3_context a0, Z3_ast a1) inline static
Definition at line 5638 of file Native.cs.
{
             int r = LIB.Z3_algebraic_is_neg(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_algebraic_is_pos (Z3_context a0, Z3_ast a1) inline static
Definition at line 5630 of file Native.cs.
{
             int r = LIB.Z3_algebraic_is_pos(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_algebraic_is_value (Z3_context a0, Z3_ast a1) inline static
Definition at line 5622 of file Native.cs.
{
             int r = LIB.Z3_algebraic_is_value(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_algebraic_is_zero (Z3_context a0, Z3_ast a1) inline static
Definition at line 5646 of file Native.cs.
{
             int r = LIB.Z3_algebraic_is_zero(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_algebraic_le (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 5726 of file Native.cs.
{
             int r = LIB.Z3_algebraic_le(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_algebraic_lt (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 5710 of file Native.cs.
{
             int r = LIB.Z3_algebraic_lt(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_algebraic_mul (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 5678 of file Native.cs.
{
             Z3_ast r = LIB.Z3_algebraic_mul(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_algebraic_neq (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 5750 of file Native.cs.
{
             int r = LIB.Z3_algebraic_neq(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_algebraic_power (Z3_context a0, Z3_ast a1, uint a2) inline static
Definition at line 5702 of file Native.cs.
{
             Z3_ast r = LIB.Z3_algebraic_power(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_algebraic_root (Z3_context a0, Z3_ast a1, uint a2) inline static
Definition at line 5694 of file Native.cs.
{
             Z3_ast r = LIB.Z3_algebraic_root(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast_vector Z3_algebraic_roots (Z3_context a0, Z3_ast a1, uint a2, [In] Z3_ast[] a3) inline static
Definition at line 5758 of file Native.cs.
{
             Z3_ast_vector r = LIB.Z3_algebraic_roots(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_algebraic_sign (Z3_context a0, Z3_ast a1) inline static
Definition at line 5654 of file Native.cs.
{
             int r = LIB.Z3_algebraic_sign(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_algebraic_sub (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 5670 of file Native.cs.
{
             Z3_ast r = LIB.Z3_algebraic_sub(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_app_to_ast (Z3_context a0, Z3_app a1) inline static
Definition at line 3410 of file Native.cs.
{
             Z3_ast r = LIB.Z3_app_to_ast(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_append_log (string a0) inline static
Definition at line 4009 of file Native.cs.
{
             LIB.Z3_append_log(a0);
         }
static Z3_model Z3_apply_result_convert_model (Z3_context a0, Z3_apply_result a1, uint a2, Z3_model a3) inline static
Definition at line 5043 of file Native.cs.
Referenced by ApplyResult.ConvertModel().
{
             Z3_model r = LIB.Z3_apply_result_convert_model(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_apply_result_dec_ref (Z3_context a0, Z3_apply_result a1) inline static
Definition at line 5012 of file Native.cs.
{
             LIB.Z3_apply_result_dec_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static uint Z3_apply_result_get_num_subgoals (Z3_context a0, Z3_apply_result a1) inline static
Definition at line 5027 of file Native.cs.
{
             uint r = LIB.Z3_apply_result_get_num_subgoals(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_goal Z3_apply_result_get_subgoal (Z3_context a0, Z3_apply_result a1, uint a2) inline static
Definition at line 5035 of file Native.cs.
{
             Z3_goal r = LIB.Z3_apply_result_get_subgoal(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_apply_result_inc_ref (Z3_context a0, Z3_apply_result a1) inline static
Definition at line 5005 of file Native.cs.
{
             LIB.Z3_apply_result_inc_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static string Z3_apply_result_to_string (Z3_context a0, Z3_apply_result a1) inline static
Definition at line 5019 of file Native.cs.
Referenced by ApplyResult.ToString().
{
             IntPtr r = LIB.Z3_apply_result_to_string(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static void Z3_assert_cnstr (Z3_context a0, Z3_ast a1) inline static
Definition at line 5349 of file Native.cs.
{
             LIB.Z3_assert_cnstr(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static int Z3_ast_map_contains (Z3_context a0, Z3_ast_map a1, Z3_ast a2) inline static
Definition at line 4520 of file Native.cs.
{
             int r = LIB.Z3_ast_map_contains(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_ast_map_dec_ref (Z3_context a0, Z3_ast_map a1) inline static
Definition at line 4513 of file Native.cs.
{
             LIB.Z3_ast_map_dec_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_ast_map_erase (Z3_context a0, Z3_ast_map a1, Z3_ast a2) inline static
Definition at line 4543 of file Native.cs.
{
             LIB.Z3_ast_map_erase(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static Z3_ast Z3_ast_map_find (Z3_context a0, Z3_ast_map a1, Z3_ast a2) inline static
Definition at line 4528 of file Native.cs.
{
             Z3_ast r = LIB.Z3_ast_map_find(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_ast_map_inc_ref (Z3_context a0, Z3_ast_map a1) inline static
Definition at line 4506 of file Native.cs.
{
             LIB.Z3_ast_map_inc_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_ast_map_insert (Z3_context a0, Z3_ast_map a1, Z3_ast a2, Z3_ast a3) inline static
Definition at line 4536 of file Native.cs.
{
             LIB.Z3_ast_map_insert(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static Z3_ast_vector Z3_ast_map_keys (Z3_context a0, Z3_ast_map a1) inline static
Definition at line 4565 of file Native.cs.
{
             Z3_ast_vector r = LIB.Z3_ast_map_keys(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_ast_map_reset (Z3_context a0, Z3_ast_map a1) inline static
Definition at line 4550 of file Native.cs.
{
             LIB.Z3_ast_map_reset(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static uint Z3_ast_map_size (Z3_context a0, Z3_ast_map a1) inline static
Definition at line 4557 of file Native.cs.
{
             uint r = LIB.Z3_ast_map_size(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_ast_map_to_string (Z3_context a0, Z3_ast_map a1) inline static
Definition at line 4573 of file Native.cs.
{
             IntPtr r = LIB.Z3_ast_map_to_string(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static string Z3_ast_to_string (Z3_context a0, Z3_ast a1) inline static
Definition at line 4028 of file Native.cs.
Referenced by AST.SExpr(), and AST.ToString().
{
             IntPtr r = LIB.Z3_ast_to_string(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static void Z3_ast_vector_dec_ref (Z3_context a0, Z3_ast_vector a1) inline static
Definition at line 4438 of file Native.cs.
{
             LIB.Z3_ast_vector_dec_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static Z3_ast Z3_ast_vector_get (Z3_context a0, Z3_ast_vector a1, uint a2) inline static
Definition at line 4453 of file Native.cs.
{
             Z3_ast r = LIB.Z3_ast_vector_get(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_ast_vector_inc_ref (Z3_context a0, Z3_ast_vector a1) inline static
Definition at line 4431 of file Native.cs.
{
             LIB.Z3_ast_vector_inc_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_ast_vector_push (Z3_context a0, Z3_ast_vector a1, Z3_ast a2) inline static
Definition at line 4475 of file Native.cs.
Referenced by ASTVector.Push().
{
             LIB.Z3_ast_vector_push(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_ast_vector_resize (Z3_context a0, Z3_ast_vector a1, uint a2) inline static
Definition at line 4468 of file Native.cs.
Referenced by ASTVector.Resize().
{
             LIB.Z3_ast_vector_resize(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_ast_vector_set (Z3_context a0, Z3_ast_vector a1, uint a2, Z3_ast a3) inline static
Definition at line 4461 of file Native.cs.
{
             LIB.Z3_ast_vector_set(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static uint Z3_ast_vector_size (Z3_context a0, Z3_ast_vector a1) inline static
Definition at line 4445 of file Native.cs.
{
             uint r = LIB.Z3_ast_vector_size(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_ast_vector_to_string (Z3_context a0, Z3_ast_vector a1) inline static
Definition at line 4490 of file Native.cs.
Referenced by ASTVector.ToString().
{
             IntPtr r = LIB.Z3_ast_vector_to_string(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static Z3_ast_vector Z3_ast_vector_translate (Z3_context a0, Z3_ast_vector a1, Z3_context a2) inline static
Definition at line 4482 of file Native.cs.
Referenced by ASTVector.Translate().
{
             Z3_ast_vector r = LIB.Z3_ast_vector_translate(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_benchmark_to_smtlib_string (Z3_context a0, string a1, string a2, string a3, string a4, uint a5, [In] Z3_ast[] a6, Z3_ast a7) inline static
Definition at line 4068 of file Native.cs.
{
             IntPtr r = LIB.Z3_benchmark_to_smtlib_string(a0, a1, a2, a3, a4, a5, a6, a7);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static void Z3_block_literals (Z3_context a0, Z3_literals a1) inline static
Definition at line 5480 of file Native.cs.
{
             LIB.Z3_block_literals(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static int Z3_check (Z3_context a0) inline static
Definition at line 5364 of file Native.cs.
{
             int r = LIB.Z3_check(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_check_and_get_model (Z3_context a0, [In, Out] ref Z3_model a1) inline static
Definition at line 5356 of file Native.cs.
{
             int r = LIB.Z3_check_and_get_model(a0, ref a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_check_assumptions (Z3_context a0, uint a1, [In] Z3_ast[] a2, [In, Out] ref Z3_model a3, [In, Out] ref Z3_ast a4, [In, Out] ref uint a5, [Out] Z3_ast[] a6) inline static
Definition at line 5372 of file Native.cs.
{
             int r = LIB.Z3_check_assumptions(a0, a1, a2, ref a3, ref a4, ref a5, a6);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_check_interpolant (Z3_context a0, uint a1, [In] Z3_ast[] a2, [In] uint[] a3, [In] Z3_ast[] a4, out IntPtr a5, uint a6, [In] Z3_ast[] a7) inline static
Definition at line 6009 of file Native.cs.
Referenced by InterpolationContext.CheckInterpolant().
{
             int r = LIB.Z3_check_interpolant(a0, a1, a2, a3, a4, out a5, a6, a7);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_close_log () inline static
Definition at line 4013 of file Native.cs.
{
             LIB.Z3_close_log();
         }
static int Z3_compute_interpolant (Z3_context a0, Z3_ast a1, Z3_params a2, [In, Out] ref Z3_ast_vector a3, [In, Out] ref Z3_model a4) inline static
Definition at line 5985 of file Native.cs.
Referenced by InterpolationContext.ComputeInterpolant().
{
             int r = LIB.Z3_compute_interpolant(a0, a1, a2, ref a3, ref a4);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_context_to_string (Z3_context a0) inline static
Definition at line 5598 of file Native.cs.
{
             IntPtr r = LIB.Z3_context_to_string(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static void Z3_dec_ref (Z3_context a0, Z3_ast a1) inline static
Definition at line 1930 of file Native.cs.
{
             LIB.Z3_dec_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_del_config (Z3_config a0) inline static
Definition at line 1897 of file Native.cs.
Referenced by Context.Context().
{
             LIB.Z3_del_config(a0);
         }
static void Z3_del_constructor (Z3_context a0, Z3_constructor a1) inline static
Definition at line 2166 of file Native.cs.
{
             LIB.Z3_del_constructor(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_del_constructor_list (Z3_context a0, Z3_constructor_list a1) inline static
Definition at line 2189 of file Native.cs.
{
             LIB.Z3_del_constructor_list(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_del_context (Z3_context a0) inline static
Definition at line 1919 of file Native.cs.
{
             LIB.Z3_del_context(a0);
         }
static void Z3_del_literals (Z3_context a0, Z3_literals a1) inline static
Definition at line 5442 of file Native.cs.
{
             LIB.Z3_del_literals(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_del_model (Z3_context a0, Z3_model a1) inline static
Definition at line 5388 of file Native.cs.
{
             LIB.Z3_del_model(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_disable_literal (Z3_context a0, Z3_literals a1, uint a2) inline static
Definition at line 5473 of file Native.cs.
{
             LIB.Z3_disable_literal(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_disable_trace (string a0) inline static
Definition at line 4211 of file Native.cs.
{
             LIB.Z3_disable_trace(a0);
         }
static void Z3_enable_trace (string a0) inline static
Definition at line 4207 of file Native.cs.
{
             LIB.Z3_enable_trace(a0);
         }
delegate void Z3_error_handler (Z3_context c, Z3_error_code e)
static int Z3_eval (Z3_context a0, Z3_model a1, Z3_ast a2, [In, Out] ref Z3_ast a3) inline static
Definition at line 5582 of file Native.cs.
{
             int r = LIB.Z3_eval(a0, a1, a2, ref a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_eval_decl (Z3_context a0, Z3_model a1, Z3_func_decl a2, uint a3, [In] Z3_ast[] a4, [In, Out] ref Z3_ast a5) inline static
Definition at line 5590 of file Native.cs.
{
             int r = LIB.Z3_eval_decl(a0, a1, a2, a3, a4, ref a5);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_eval_func_decl (Z3_context a0, Z3_model a1, Z3_func_decl a2, [In, Out] ref Z3_ast a3) inline static
Definition at line 5519 of file Native.cs.
{
             int r = LIB.Z3_eval_func_decl(a0, a1, a2, ref a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_fixedpoint_add_cover (Z3_context a0, Z3_fixedpoint a1, int a2, Z3_func_decl a3, Z3_ast a4) inline static
Definition at line 4317 of file Native.cs.
Referenced by Fixedpoint.AddCover().
{
             LIB.Z3_fixedpoint_add_cover(a0, a1, a2, a3, a4);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_fixedpoint_add_fact (Z3_context a0, Z3_fixedpoint a1, Z3_func_decl a2, uint a3, [In] uint[] a4) inline static
Definition at line 4248 of file Native.cs.
Referenced by Fixedpoint.AddFact().
{
             LIB.Z3_fixedpoint_add_fact(a0, a1, a2, a3, a4);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_fixedpoint_add_rule (Z3_context a0, Z3_fixedpoint a1, Z3_ast a2, IntPtr a3) inline static
Definition at line 4241 of file Native.cs.
Referenced by Fixedpoint.AddRule().
{
             LIB.Z3_fixedpoint_add_rule(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_fixedpoint_assert (Z3_context a0, Z3_fixedpoint a1, Z3_ast a2) inline static
Definition at line 4255 of file Native.cs.
Referenced by Fixedpoint.Assert().
{
             LIB.Z3_fixedpoint_assert(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_fixedpoint_dec_ref (Z3_context a0, Z3_fixedpoint a1) inline static
Definition at line 4234 of file Native.cs.
{
             LIB.Z3_fixedpoint_dec_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static Z3_ast_vector Z3_fixedpoint_from_file (Z3_context a0, Z3_fixedpoint a1, string a2) inline static
Definition at line 4401 of file Native.cs.
Referenced by Fixedpoint.ParseFile().
{
             Z3_ast_vector r = LIB.Z3_fixedpoint_from_file(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast_vector Z3_fixedpoint_from_string (Z3_context a0, Z3_fixedpoint a1, string a2) inline static
Definition at line 4393 of file Native.cs.
Referenced by Fixedpoint.ParseString().
{
             Z3_ast_vector r = LIB.Z3_fixedpoint_from_string(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_fixedpoint_get_answer (Z3_context a0, Z3_fixedpoint a1) inline static
Definition at line 4278 of file Native.cs.
Referenced by Fixedpoint.GetAnswer().
{
             Z3_ast r = LIB.Z3_fixedpoint_get_answer(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast_vector Z3_fixedpoint_get_assertions (Z3_context a0, Z3_fixedpoint a1) inline static
Definition at line 4354 of file Native.cs.
{
             Z3_ast_vector r = LIB.Z3_fixedpoint_get_assertions(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_fixedpoint_get_cover_delta (Z3_context a0, Z3_fixedpoint a1, int a2, Z3_func_decl a3) inline static
Definition at line 4309 of file Native.cs.
Referenced by Fixedpoint.GetCoverDelta().
{
             Z3_ast r = LIB.Z3_fixedpoint_get_cover_delta(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_fixedpoint_get_help (Z3_context a0, Z3_fixedpoint a1) inline static
Definition at line 4369 of file Native.cs.
{
             IntPtr r = LIB.Z3_fixedpoint_get_help(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static uint Z3_fixedpoint_get_num_levels (Z3_context a0, Z3_fixedpoint a1, Z3_func_decl a2) inline static
Definition at line 4301 of file Native.cs.
Referenced by Fixedpoint.GetNumLevels().
{
             uint r = LIB.Z3_fixedpoint_get_num_levels(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_param_descrs Z3_fixedpoint_get_param_descrs (Z3_context a0, Z3_fixedpoint a1) inline static
Definition at line 4377 of file Native.cs.
{
             Z3_param_descrs r = LIB.Z3_fixedpoint_get_param_descrs(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_fixedpoint_get_reason_unknown (Z3_context a0, Z3_fixedpoint a1) inline static
Definition at line 4286 of file Native.cs.
Referenced by Fixedpoint.GetReasonUnknown().
{
             IntPtr r = LIB.Z3_fixedpoint_get_reason_unknown(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static Z3_ast_vector Z3_fixedpoint_get_rules (Z3_context a0, Z3_fixedpoint a1) inline static
Definition at line 4346 of file Native.cs.
{
             Z3_ast_vector r = LIB.Z3_fixedpoint_get_rules(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_stats Z3_fixedpoint_get_statistics (Z3_context a0, Z3_fixedpoint a1) inline static
Definition at line 4324 of file Native.cs.
{
             Z3_stats r = LIB.Z3_fixedpoint_get_statistics(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_fixedpoint_inc_ref (Z3_context a0, Z3_fixedpoint a1) inline static
Definition at line 4227 of file Native.cs.
{
             LIB.Z3_fixedpoint_inc_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_fixedpoint_pop (Z3_context a0, Z3_fixedpoint a1) inline static
Definition at line 4416 of file Native.cs.
Referenced by Fixedpoint.Pop().
{
             LIB.Z3_fixedpoint_pop(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_fixedpoint_push (Z3_context a0, Z3_fixedpoint a1) inline static
Definition at line 4409 of file Native.cs.
Referenced by Fixedpoint.Push().
{
             LIB.Z3_fixedpoint_push(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static int Z3_fixedpoint_query (Z3_context a0, Z3_fixedpoint a1, Z3_ast a2) inline static
Definition at line 4262 of file Native.cs.
Referenced by Fixedpoint.Query().
{
             int r = LIB.Z3_fixedpoint_query(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_fixedpoint_query_relations (Z3_context a0, Z3_fixedpoint a1, uint a2, [In] Z3_func_decl[] a3) inline static
Definition at line 4270 of file Native.cs.
Referenced by Fixedpoint.Query().
{
             int r = LIB.Z3_fixedpoint_query_relations(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_fixedpoint_register_relation (Z3_context a0, Z3_fixedpoint a1, Z3_func_decl a2) inline static
Definition at line 4332 of file Native.cs.
Referenced by Fixedpoint.RegisterRelation().
{
             LIB.Z3_fixedpoint_register_relation(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_fixedpoint_set_params (Z3_context a0, Z3_fixedpoint a1, Z3_params a2) inline static
Definition at line 4362 of file Native.cs.
{
             LIB.Z3_fixedpoint_set_params(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_fixedpoint_set_predicate_representation (Z3_context a0, Z3_fixedpoint a1, Z3_func_decl a2, uint a3, [In] IntPtr[] a4) inline static
Definition at line 4339 of file Native.cs.
Referenced by Fixedpoint.SetPredicateRepresentation().
{
             LIB.Z3_fixedpoint_set_predicate_representation(a0, a1, a2, a3, a4);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static string Z3_fixedpoint_to_string (Z3_context a0, Z3_fixedpoint a1, uint a2, [In] Z3_ast[] a3) inline static
Definition at line 4385 of file Native.cs.
Referenced by Fixedpoint.ToString().
{
             IntPtr r = LIB.Z3_fixedpoint_to_string(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static void Z3_fixedpoint_update_rule (Z3_context a0, Z3_fixedpoint a1, Z3_ast a2, IntPtr a3) inline static
Definition at line 4294 of file Native.cs.
Referenced by Fixedpoint.UpdateRule().
{
             LIB.Z3_fixedpoint_update_rule(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static uint Z3_fpa_get_ebits (Z3_context a0, Z3_sort a1) inline static
Definition at line 6512 of file Native.cs.
{
             uint r = LIB.Z3_fpa_get_ebits(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_fpa_get_numeral_exponent_int64 (Z3_context a0, Z3_ast a1, [In, Out] ref Int64 a2) inline static
Definition at line 6552 of file Native.cs.
{
             int r = LIB.Z3_fpa_get_numeral_exponent_int64(a0, a1, ref a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_fpa_get_numeral_exponent_string (Z3_context a0, Z3_ast a1) inline static
Definition at line 6544 of file Native.cs.
{
             IntPtr r = LIB.Z3_fpa_get_numeral_exponent_string(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static int Z3_fpa_get_numeral_sign (Z3_context a0, Z3_ast a1, [In, Out] ref int a2) inline static
Definition at line 6528 of file Native.cs.
{
             int r = LIB.Z3_fpa_get_numeral_sign(a0, a1, ref a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_fpa_get_numeral_significand_string (Z3_context a0, Z3_ast a1) inline static
Definition at line 6536 of file Native.cs.
{
             IntPtr r = LIB.Z3_fpa_get_numeral_significand_string(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static uint Z3_fpa_get_sbits (Z3_context a0, Z3_sort a1) inline static
Definition at line 6520 of file Native.cs.
{
             uint r = LIB.Z3_fpa_get_sbits(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_func_decl_to_ast (Z3_context a0, Z3_func_decl a1) inline static
Definition at line 3266 of file Native.cs.
{
             Z3_ast r = LIB.Z3_func_decl_to_ast(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_func_decl_to_string (Z3_context a0, Z3_func_decl a1) inline static
Definition at line 4052 of file Native.cs.
Referenced by FuncDecl.ToString().
{
             IntPtr r = LIB.Z3_func_decl_to_string(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static void Z3_func_entry_dec_ref (Z3_context a0, Z3_func_entry a1) inline static
Definition at line 3973 of file Native.cs.
{
             LIB.Z3_func_entry_dec_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static Z3_ast Z3_func_entry_get_arg (Z3_context a0, Z3_func_entry a1, uint a2) inline static
Definition at line 3996 of file Native.cs.
{
             Z3_ast r = LIB.Z3_func_entry_get_arg(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_func_entry_get_num_args (Z3_context a0, Z3_func_entry a1) inline static
Definition at line 3988 of file Native.cs.
{
             uint r = LIB.Z3_func_entry_get_num_args(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_func_entry_get_value (Z3_context a0, Z3_func_entry a1) inline static
Definition at line 3980 of file Native.cs.
{
             Z3_ast r = LIB.Z3_func_entry_get_value(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_func_entry_inc_ref (Z3_context a0, Z3_func_entry a1) inline static
Definition at line 3966 of file Native.cs.
{
             LIB.Z3_func_entry_inc_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_func_interp_dec_ref (Z3_context a0, Z3_func_interp a1) inline static
Definition at line 3927 of file Native.cs.
{
             LIB.Z3_func_interp_dec_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static uint Z3_func_interp_get_arity (Z3_context a0, Z3_func_interp a1) inline static
Definition at line 3958 of file Native.cs.
{
             uint r = LIB.Z3_func_interp_get_arity(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_func_interp_get_else (Z3_context a0, Z3_func_interp a1) inline static
Definition at line 3950 of file Native.cs.
{
             Z3_ast r = LIB.Z3_func_interp_get_else(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_func_entry Z3_func_interp_get_entry (Z3_context a0, Z3_func_interp a1, uint a2) inline static
Definition at line 3942 of file Native.cs.
{
             Z3_func_entry r = LIB.Z3_func_interp_get_entry(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_func_interp_get_num_entries (Z3_context a0, Z3_func_interp a1) inline static
Definition at line 3934 of file Native.cs.
{
             uint r = LIB.Z3_func_interp_get_num_entries(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_func_interp_inc_ref (Z3_context a0, Z3_func_interp a1) inline static
Definition at line 3920 of file Native.cs.
{
             LIB.Z3_func_interp_inc_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static Z3_ast Z3_get_algebraic_number_lower (Z3_context a0, Z3_ast a1, uint a2) inline static
Definition at line 3618 of file Native.cs.
Referenced by AlgebraicNum.ToLower().
{
             Z3_ast r = LIB.Z3_get_algebraic_number_lower(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_get_algebraic_number_upper (Z3_context a0, Z3_ast a1, uint a2) inline static
Definition at line 3626 of file Native.cs.
Referenced by AlgebraicNum.ToUpper().
{
             Z3_ast r = LIB.Z3_get_algebraic_number_upper(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_get_app_arg (Z3_context a0, Z3_app a1, uint a2) inline static
Definition at line 3434 of file Native.cs.
{
             Z3_ast r = LIB.Z3_get_app_arg(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_func_decl Z3_get_app_decl (Z3_context a0, Z3_app a1) inline static
Definition at line 3418 of file Native.cs.
{
             Z3_func_decl r = LIB.Z3_get_app_decl(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_app_num_args (Z3_context a0, Z3_app a1) inline static
Definition at line 3426 of file Native.cs.
{
             uint r = LIB.Z3_get_app_num_args(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_arity (Z3_context a0, Z3_func_decl a1) inline static
Definition at line 3314 of file Native.cs.
{
             uint r = LIB.Z3_get_arity(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_get_array_sort_domain (Z3_context a0, Z3_sort a1) inline static
Definition at line 3178 of file Native.cs.
{
             Z3_sort r = LIB.Z3_get_array_sort_domain(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_get_array_sort_range (Z3_context a0, Z3_sort a1) inline static
Definition at line 3186 of file Native.cs.
{
             Z3_sort r = LIB.Z3_get_array_sort_range(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_get_array_value (Z3_context a0, Z3_model a1, Z3_ast a2, uint a3, [Out] Z3_ast[] a4, [Out] Z3_ast[] a5, [In, Out] ref Z3_ast a6) inline static
Definition at line 5535 of file Native.cs.
{
             LIB.Z3_get_array_value(a0, a1, a2, a3, a4, a5, ref a6);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static Z3_func_decl Z3_get_as_array_func_decl (Z3_context a0, Z3_ast a1) inline static
Definition at line 3912 of file Native.cs.
Referenced by Model.FuncInterp().
{
             Z3_func_decl r = LIB.Z3_get_as_array_func_decl(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_ast_hash (Z3_context a0, Z3_ast a1) inline static
Definition at line 3458 of file Native.cs.
Referenced by AST.GetHashCode().
{
             uint r = LIB.Z3_get_ast_hash(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_ast_id (Z3_context a0, Z3_ast a1) inline static
Definition at line 3450 of file Native.cs.
{
             uint r = LIB.Z3_get_ast_id(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_ast_kind (Z3_context a0, Z3_ast a1) inline static
Definition at line 3490 of file Native.cs.
{
             uint r = LIB.Z3_get_ast_kind(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_bool_value (Z3_context a0, Z3_ast a1) inline static
Definition at line 3482 of file Native.cs.
{
             uint r = LIB.Z3_get_bool_value(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_bv_sort_size (Z3_context a0, Z3_sort a1) inline static
Definition at line 3162 of file Native.cs.
{
             uint r = LIB.Z3_get_bv_sort_size(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_get_context_assignment (Z3_context a0) inline static
Definition at line 5614 of file Native.cs.
{
             Z3_ast r = LIB.Z3_get_context_assignment(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_func_decl Z3_get_datatype_sort_constructor (Z3_context a0, Z3_sort a1, uint a2) inline static
Definition at line 3226 of file Native.cs.
Referenced by EnumSort.ConstDecl().
{
             Z3_func_decl r = LIB.Z3_get_datatype_sort_constructor(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_func_decl Z3_get_datatype_sort_constructor_accessor (Z3_context a0, Z3_sort a1, uint a2, uint a3) inline static
Definition at line 3242 of file Native.cs.
{
             Z3_func_decl r = LIB.Z3_get_datatype_sort_constructor_accessor(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_datatype_sort_num_constructors (Z3_context a0, Z3_sort a1) inline static
Definition at line 3218 of file Native.cs.
{
             uint r = LIB.Z3_get_datatype_sort_num_constructors(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_func_decl Z3_get_datatype_sort_recognizer (Z3_context a0, Z3_sort a1, uint a2) inline static
Definition at line 3234 of file Native.cs.
Referenced by EnumSort.TesterDecl().
{
             Z3_func_decl r = LIB.Z3_get_datatype_sort_recognizer(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_get_decl_ast_parameter (Z3_context a0, Z3_func_decl a1, uint a2) inline static
Definition at line 3386 of file Native.cs.
{
             Z3_ast r = LIB.Z3_get_decl_ast_parameter(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static double Z3_get_decl_double_parameter (Z3_context a0, Z3_func_decl a1, uint a2) inline static
Definition at line 3362 of file Native.cs.
{
             double r = LIB.Z3_get_decl_double_parameter(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_func_decl Z3_get_decl_func_decl_parameter (Z3_context a0, Z3_func_decl a1, uint a2) inline static
Definition at line 3394 of file Native.cs.
{
             Z3_func_decl r = LIB.Z3_get_decl_func_decl_parameter(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_get_decl_int_parameter (Z3_context a0, Z3_func_decl a1, uint a2) inline static
Definition at line 3354 of file Native.cs.
{
             int r = LIB.Z3_get_decl_int_parameter(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_decl_kind (Z3_context a0, Z3_func_decl a1) inline static
Definition at line 3298 of file Native.cs.
{
             uint r = LIB.Z3_get_decl_kind(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static IntPtr Z3_get_decl_name (Z3_context a0, Z3_func_decl a1) inline static
Definition at line 3290 of file Native.cs.
{
             IntPtr r = LIB.Z3_get_decl_name(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_decl_num_parameters (Z3_context a0, Z3_func_decl a1) inline static
Definition at line 3338 of file Native.cs.
{
             uint r = LIB.Z3_get_decl_num_parameters(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_decl_parameter_kind (Z3_context a0, Z3_func_decl a1, uint a2) inline static
Definition at line 3346 of file Native.cs.
{
             uint r = LIB.Z3_get_decl_parameter_kind(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_get_decl_rational_parameter (Z3_context a0, Z3_func_decl a1, uint a2) inline static
Definition at line 3402 of file Native.cs.
{
             IntPtr r = LIB.Z3_get_decl_rational_parameter(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static Z3_sort Z3_get_decl_sort_parameter (Z3_context a0, Z3_func_decl a1, uint a2) inline static
Definition at line 3378 of file Native.cs.
{
             Z3_sort r = LIB.Z3_get_decl_sort_parameter(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static IntPtr Z3_get_decl_symbol_parameter (Z3_context a0, Z3_func_decl a1, uint a2) inline static
Definition at line 3370 of file Native.cs.
{
             IntPtr r = LIB.Z3_get_decl_symbol_parameter(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_get_denominator (Z3_context a0, Z3_ast a1) inline static
Definition at line 3562 of file Native.cs.
{
             Z3_ast r = LIB.Z3_get_denominator(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_get_domain (Z3_context a0, Z3_func_decl a1, uint a2) inline static
Definition at line 3322 of file Native.cs.
{
             Z3_sort r = LIB.Z3_get_domain(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_domain_size (Z3_context a0, Z3_func_decl a1) inline static
Definition at line 3306 of file Native.cs.
{
             uint r = LIB.Z3_get_domain_size(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_error_code (Z3_context a0) inline static
Definition at line 4178 of file Native.cs.
{
             uint r = LIB.Z3_get_error_code(a0);
             return r;
         }
static string Z3_get_error_msg (uint a0) inline static
Definition at line 4190 of file Native.cs.
{
             IntPtr r = LIB.Z3_get_error_msg(a0);
             return Marshal.PtrToStringAnsi(r);
         }
static string Z3_get_error_msg_ex (Z3_context a0, uint a1) inline static
Definition at line 4195 of file Native.cs.
{
             IntPtr r = LIB.Z3_get_error_msg_ex(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static int Z3_get_finite_domain_sort_size (Z3_context a0, Z3_sort a1, [In, Out] ref UInt64 a2) inline static
Definition at line 3170 of file Native.cs.
{
             int r = LIB.Z3_get_finite_domain_sort_size(a0, a1, ref a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_func_decl_id (Z3_context a0, Z3_func_decl a1) inline static
Definition at line 3282 of file Native.cs.
{
             uint r = LIB.Z3_get_func_decl_id(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_literals Z3_get_guessed_literals (Z3_context a0) inline static
Definition at line 5434 of file Native.cs.
{
             Z3_literals r = LIB.Z3_get_guessed_literals(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_implied_equalities (Z3_context a0, Z3_solver a1, uint a2, [In] Z3_ast[] a3, [Out] uint[] a4) inline static
Definition at line 5380 of file Native.cs.
{
             uint r = LIB.Z3_get_implied_equalities(a0, a1, a2, a3, a4);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_index_value (Z3_context a0, Z3_ast a1) inline static
Definition at line 3658 of file Native.cs.
{
             uint r = LIB.Z3_get_index_value(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast_vector Z3_get_interpolant (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_params a3) inline static
Definition at line 5977 of file Native.cs.
Referenced by InterpolationContext.GetInterpolant().
{
             Z3_ast_vector r = LIB.Z3_get_interpolant(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static IntPtr Z3_get_label_symbol (Z3_context a0, Z3_literals a1, uint a2) inline static
Definition at line 5457 of file Native.cs.
{
             IntPtr r = LIB.Z3_get_label_symbol(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_get_literal (Z3_context a0, Z3_literals a1, uint a2) inline static
Definition at line 5465 of file Native.cs.
{
             Z3_ast r = LIB.Z3_get_literal(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_func_decl Z3_get_model_constant (Z3_context a0, Z3_model a1, uint a2) inline static
Definition at line 5495 of file Native.cs.
{
             Z3_func_decl r = LIB.Z3_get_model_constant(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_func_decl Z3_get_model_func_decl (Z3_context a0, Z3_model a1, uint a2) inline static
Definition at line 5511 of file Native.cs.
{
             Z3_func_decl r = LIB.Z3_get_model_func_decl(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_get_model_func_else (Z3_context a0, Z3_model a1, uint a2) inline static
Definition at line 5542 of file Native.cs.
{
             Z3_ast r = LIB.Z3_get_model_func_else(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_get_model_func_entry_arg (Z3_context a0, Z3_model a1, uint a2, uint a3, uint a4) inline static
Definition at line 5566 of file Native.cs.
{
             Z3_ast r = LIB.Z3_get_model_func_entry_arg(a0, a1, a2, a3, a4);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_model_func_entry_num_args (Z3_context a0, Z3_model a1, uint a2, uint a3) inline static
Definition at line 5558 of file Native.cs.
{
             uint r = LIB.Z3_get_model_func_entry_num_args(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_get_model_func_entry_value (Z3_context a0, Z3_model a1, uint a2, uint a3) inline static
Definition at line 5574 of file Native.cs.
{
             Z3_ast r = LIB.Z3_get_model_func_entry_value(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_model_func_num_entries (Z3_context a0, Z3_model a1, uint a2) inline static
Definition at line 5550 of file Native.cs.
{
             uint r = LIB.Z3_get_model_func_num_entries(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_model_num_constants (Z3_context a0, Z3_model a1) inline static
Definition at line 5487 of file Native.cs.
{
             uint r = LIB.Z3_get_model_num_constants(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_model_num_funcs (Z3_context a0, Z3_model a1) inline static
Definition at line 5503 of file Native.cs.
{
             uint r = LIB.Z3_get_model_num_funcs(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_num_literals (Z3_context a0, Z3_literals a1) inline static
Definition at line 5449 of file Native.cs.
{
             uint r = LIB.Z3_get_num_literals(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_num_probes (Z3_context a0) inline static
Definition at line 4933 of file Native.cs.
{
             uint r = LIB.Z3_get_num_probes(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_num_scopes (Z3_context a0) inline static
Definition at line 5334 of file Native.cs.
{
             uint r = LIB.Z3_get_num_scopes(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_num_tactics (Z3_context a0) inline static
Definition at line 4917 of file Native.cs.
{
             uint r = LIB.Z3_get_num_tactics(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_get_numeral_decimal_string (Z3_context a0, Z3_ast a1, uint a2) inline static
Definition at line 3546 of file Native.cs.
Referenced by AlgebraicNum.ToDecimal(), and RatNum.ToDecimalString().
{
             IntPtr r = LIB.Z3_get_numeral_decimal_string(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static int Z3_get_numeral_int (Z3_context a0, Z3_ast a1, [In, Out] ref int a2) inline static
Definition at line 3578 of file Native.cs.
{
             int r = LIB.Z3_get_numeral_int(a0, a1, ref a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_get_numeral_int64 (Z3_context a0, Z3_ast a1, [In, Out] ref Int64 a2) inline static
Definition at line 3602 of file Native.cs.
{
             int r = LIB.Z3_get_numeral_int64(a0, a1, ref a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_get_numeral_rational_int64 (Z3_context a0, Z3_ast a1, [In, Out] ref Int64 a2, [In, Out] ref Int64 a3) inline static
Definition at line 3610 of file Native.cs.
{
             int r = LIB.Z3_get_numeral_rational_int64(a0, a1, ref a2, ref a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_get_numeral_small (Z3_context a0, Z3_ast a1, [In, Out] ref Int64 a2, [In, Out] ref Int64 a3) inline static
Definition at line 3570 of file Native.cs.
{
             int r = LIB.Z3_get_numeral_small(a0, a1, ref a2, ref a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_get_numeral_string (Z3_context a0, Z3_ast a1) inline static
Definition at line 3538 of file Native.cs.
Referenced by FPRMNum.ToString(), RatNum.ToString(), FPNum.ToString(), BitVecNum.ToString(), and IntNum.ToString().
{
             IntPtr r = LIB.Z3_get_numeral_string(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static int Z3_get_numeral_uint (Z3_context a0, Z3_ast a1, [In, Out] ref uint a2) inline static
Definition at line 3586 of file Native.cs.
{
             int r = LIB.Z3_get_numeral_uint(a0, a1, ref a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_get_numeral_uint64 (Z3_context a0, Z3_ast a1, [In, Out] ref UInt64 a2) inline static
Definition at line 3594 of file Native.cs.
{
             int r = LIB.Z3_get_numeral_uint64(a0, a1, ref a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_get_numerator (Z3_context a0, Z3_ast a1) inline static
Definition at line 3554 of file Native.cs.
{
             Z3_ast r = LIB.Z3_get_numerator(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_get_pattern (Z3_context a0, Z3_pattern a1, uint a2) inline static
Definition at line 3650 of file Native.cs.
{
             Z3_ast r = LIB.Z3_get_pattern(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_pattern_num_terms (Z3_context a0, Z3_pattern a1) inline static
Definition at line 3642 of file Native.cs.
{
             uint r = LIB.Z3_get_pattern_num_terms(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_get_probe_name (Z3_context a0, uint a1) inline static
Definition at line 4941 of file Native.cs.
{
             IntPtr r = LIB.Z3_get_probe_name(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static Z3_ast Z3_get_quantifier_body (Z3_context a0, Z3_ast a1) inline static
Definition at line 3738 of file Native.cs.
{
             Z3_ast r = LIB.Z3_get_quantifier_body(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static IntPtr Z3_get_quantifier_bound_name (Z3_context a0, Z3_ast a1, uint a2) inline static
Definition at line 3722 of file Native.cs.
{
             IntPtr r = LIB.Z3_get_quantifier_bound_name(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_get_quantifier_bound_sort (Z3_context a0, Z3_ast a1, uint a2) inline static
Definition at line 3730 of file Native.cs.
{
             Z3_sort r = LIB.Z3_get_quantifier_bound_sort(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_get_quantifier_no_pattern_ast (Z3_context a0, Z3_ast a1, uint a2) inline static
Definition at line 3706 of file Native.cs.
{
             Z3_ast r = LIB.Z3_get_quantifier_no_pattern_ast(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_quantifier_num_bound (Z3_context a0, Z3_ast a1) inline static
Definition at line 3714 of file Native.cs.
{
             uint r = LIB.Z3_get_quantifier_num_bound(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_quantifier_num_no_patterns (Z3_context a0, Z3_ast a1) inline static
Definition at line 3698 of file Native.cs.
{
             uint r = LIB.Z3_get_quantifier_num_no_patterns(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_quantifier_num_patterns (Z3_context a0, Z3_ast a1) inline static
Definition at line 3682 of file Native.cs.
{
             uint r = LIB.Z3_get_quantifier_num_patterns(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_pattern Z3_get_quantifier_pattern_ast (Z3_context a0, Z3_ast a1, uint a2) inline static
Definition at line 3690 of file Native.cs.
{
             Z3_pattern r = LIB.Z3_get_quantifier_pattern_ast(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_quantifier_weight (Z3_context a0, Z3_ast a1) inline static
Definition at line 3674 of file Native.cs.
{
             uint r = LIB.Z3_get_quantifier_weight(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_get_range (Z3_context a0, Z3_func_decl a1) inline static
Definition at line 3330 of file Native.cs.
Referenced by Model.ConstInterp(), and Model.FuncInterp().
{
             Z3_sort r = LIB.Z3_get_range(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_relation_arity (Z3_context a0, Z3_sort a1) inline static
Definition at line 3250 of file Native.cs.
{
             uint r = LIB.Z3_get_relation_arity(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_get_relation_column (Z3_context a0, Z3_sort a1, uint a2) inline static
Definition at line 3258 of file Native.cs.
{
             Z3_sort r = LIB.Z3_get_relation_column(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_literals Z3_get_relevant_labels (Z3_context a0) inline static
Definition at line 5418 of file Native.cs.
{
             Z3_literals r = LIB.Z3_get_relevant_labels(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_literals Z3_get_relevant_literals (Z3_context a0) inline static
Definition at line 5426 of file Native.cs.
{
             Z3_literals r = LIB.Z3_get_relevant_literals(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_search_failure (Z3_context a0) inline static
Definition at line 5402 of file Native.cs.
{
             uint r = LIB.Z3_get_search_failure(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_get_smtlib_assumption (Z3_context a0, uint a1) inline static
Definition at line 4130 of file Native.cs.
{
             Z3_ast r = LIB.Z3_get_smtlib_assumption(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_func_decl Z3_get_smtlib_decl (Z3_context a0, uint a1) inline static
Definition at line 4146 of file Native.cs.
{
             Z3_func_decl r = LIB.Z3_get_smtlib_decl(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_get_smtlib_error (Z3_context a0) inline static
Definition at line 4170 of file Native.cs.
{
             IntPtr r = LIB.Z3_get_smtlib_error(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static Z3_ast Z3_get_smtlib_formula (Z3_context a0, uint a1) inline static
Definition at line 4114 of file Native.cs.
{
             Z3_ast r = LIB.Z3_get_smtlib_formula(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_smtlib_num_assumptions (Z3_context a0) inline static
Definition at line 4122 of file Native.cs.
{
             uint r = LIB.Z3_get_smtlib_num_assumptions(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_smtlib_num_decls (Z3_context a0) inline static
Definition at line 4138 of file Native.cs.
{
             uint r = LIB.Z3_get_smtlib_num_decls(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_smtlib_num_formulas (Z3_context a0) inline static
Definition at line 4106 of file Native.cs.
{
             uint r = LIB.Z3_get_smtlib_num_formulas(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_smtlib_num_sorts (Z3_context a0) inline static
Definition at line 4154 of file Native.cs.
{
             uint r = LIB.Z3_get_smtlib_num_sorts(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_get_smtlib_sort (Z3_context a0, uint a1) inline static
Definition at line 4162 of file Native.cs.
{
             Z3_sort r = LIB.Z3_get_smtlib_sort(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_get_sort (Z3_context a0, Z3_ast a1) inline static
Definition at line 3466 of file Native.cs.
{
             Z3_sort r = LIB.Z3_get_sort(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_sort_id (Z3_context a0, Z3_sort a1) inline static
Definition at line 3130 of file Native.cs.
{
             uint r = LIB.Z3_get_sort_id(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_sort_kind (Z3_context a0, Z3_sort a1) inline static
Definition at line 3154 of file Native.cs.
Referenced by Model.ConstInterp(), and Model.FuncInterp().
{
             uint r = LIB.Z3_get_sort_kind(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static IntPtr Z3_get_sort_name (Z3_context a0, Z3_sort a1) inline static
Definition at line 3122 of file Native.cs.
{
             IntPtr r = LIB.Z3_get_sort_name(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_get_symbol_int (Z3_context a0, IntPtr a1) inline static
Definition at line 3106 of file Native.cs.
{
             int r = LIB.Z3_get_symbol_int(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_symbol_kind (Z3_context a0, IntPtr a1) inline static
Definition at line 3098 of file Native.cs.
{
             uint r = LIB.Z3_get_symbol_kind(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_get_symbol_string (Z3_context a0, IntPtr a1) inline static
Definition at line 3114 of file Native.cs.
{
             IntPtr r = LIB.Z3_get_symbol_string(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static string Z3_get_tactic_name (Z3_context a0, uint a1) inline static
Definition at line 4925 of file Native.cs.
{
             IntPtr r = LIB.Z3_get_tactic_name(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static Z3_func_decl Z3_get_tuple_sort_field_decl (Z3_context a0, Z3_sort a1, uint a2) inline static
Definition at line 3210 of file Native.cs.
{
             Z3_func_decl r = LIB.Z3_get_tuple_sort_field_decl(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_func_decl Z3_get_tuple_sort_mk_decl (Z3_context a0, Z3_sort a1) inline static
Definition at line 3194 of file Native.cs.
{
             Z3_func_decl r = LIB.Z3_get_tuple_sort_mk_decl(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_get_tuple_sort_num_fields (Z3_context a0, Z3_sort a1) inline static
Definition at line 3202 of file Native.cs.
{
             uint r = LIB.Z3_get_tuple_sort_num_fields(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_get_version ([In, Out] ref uint a0, [In, Out] ref uint a1, [In, Out] ref uint a2, [In, Out] ref uint a3) inline static
Definition at line 4203 of file Native.cs.
{
             LIB.Z3_get_version(ref a0, ref a1, ref a2, ref a3);
         }
static int Z3_global_param_get (string a0, out IntPtr a1) inline static
Definition at line 1887 of file Native.cs.
{
             int r = LIB.Z3_global_param_get(a0, out a1);
             return r;
         }
static void Z3_global_param_reset_all () inline static
Definition at line 1883 of file Native.cs.
{
             LIB.Z3_global_param_reset_all();
         }
static void Z3_global_param_set (string a0, string a1) inline static
Definition at line 1879 of file Native.cs.
{
             LIB.Z3_global_param_set(a0, a1);
         }
static void Z3_goal_assert (Z3_context a0, Z3_goal a1, Z3_ast a2) inline static
Definition at line 4611 of file Native.cs.
Referenced by Goal.Assert().
{
             LIB.Z3_goal_assert(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_goal_dec_ref (Z3_context a0, Z3_goal a1) inline static
Definition at line 4596 of file Native.cs.
{
             LIB.Z3_goal_dec_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static uint Z3_goal_depth (Z3_context a0, Z3_goal a1) inline static
Definition at line 4626 of file Native.cs.
{
             uint r = LIB.Z3_goal_depth(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_goal_formula (Z3_context a0, Z3_goal a1, uint a2) inline static
Definition at line 4649 of file Native.cs.
{
             Z3_ast r = LIB.Z3_goal_formula(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_goal_inc_ref (Z3_context a0, Z3_goal a1) inline static
Definition at line 4589 of file Native.cs.
{
             LIB.Z3_goal_inc_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static int Z3_goal_inconsistent (Z3_context a0, Z3_goal a1) inline static
Definition at line 4618 of file Native.cs.
{
             int r = LIB.Z3_goal_inconsistent(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_goal_is_decided_sat (Z3_context a0, Z3_goal a1) inline static
Definition at line 4665 of file Native.cs.
{
             int r = LIB.Z3_goal_is_decided_sat(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_goal_is_decided_unsat (Z3_context a0, Z3_goal a1) inline static
Definition at line 4673 of file Native.cs.
{
             int r = LIB.Z3_goal_is_decided_unsat(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_goal_num_exprs (Z3_context a0, Z3_goal a1) inline static
Definition at line 4657 of file Native.cs.
{
             uint r = LIB.Z3_goal_num_exprs(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_goal_precision (Z3_context a0, Z3_goal a1) inline static
Definition at line 4603 of file Native.cs.
{
             uint r = LIB.Z3_goal_precision(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_goal_reset (Z3_context a0, Z3_goal a1) inline static
Definition at line 4634 of file Native.cs.
Referenced by Goal.Reset().
{
             LIB.Z3_goal_reset(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static uint Z3_goal_size (Z3_context a0, Z3_goal a1) inline static
Definition at line 4641 of file Native.cs.
{
             uint r = LIB.Z3_goal_size(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_goal_to_string (Z3_context a0, Z3_goal a1) inline static
Definition at line 4689 of file Native.cs.
Referenced by Goal.ToString().
{
             IntPtr r = LIB.Z3_goal_to_string(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static Z3_goal Z3_goal_translate (Z3_context a0, Z3_goal a1, Z3_context a2) inline static
Definition at line 4681 of file Native.cs.
Referenced by Goal.Translate().
{
             Z3_goal r = LIB.Z3_goal_translate(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_inc_ref (Z3_context a0, Z3_ast a1) inline static
Definition at line 1923 of file Native.cs.
{
             LIB.Z3_inc_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static string Z3_interpolation_profile (Z3_context a0) inline static
Definition at line 5993 of file Native.cs.
Referenced by InterpolationContext.InterpolationProfile().
{
             IntPtr r = LIB.Z3_interpolation_profile(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static void Z3_interrupt (Z3_context a0) inline static
Definition at line 1944 of file Native.cs.
Referenced by Context.Interrupt().
{
             LIB.Z3_interrupt(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static int Z3_is_algebraic_number (Z3_context a0, Z3_ast a1) inline static
Definition at line 3514 of file Native.cs.
{
             int r = LIB.Z3_is_algebraic_number(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_is_app (Z3_context a0, Z3_ast a1) inline static
Definition at line 3498 of file Native.cs.
{
             int r = LIB.Z3_is_app(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_is_array_value (Z3_context a0, Z3_model a1, Z3_ast a2, [In, Out] ref uint a3) inline static
Definition at line 5527 of file Native.cs.
{
             int r = LIB.Z3_is_array_value(a0, a1, a2, ref a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_is_as_array (Z3_context a0, Z3_ast a1) inline static
Definition at line 3904 of file Native.cs.
Referenced by Model.FuncInterp().
{
             int r = LIB.Z3_is_as_array(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_is_eq_ast (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 3442 of file Native.cs.
Referenced by AST.operator==().
{
             int r = LIB.Z3_is_eq_ast(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_is_eq_func_decl (Z3_context a0, Z3_func_decl a1, Z3_func_decl a2) inline static
Definition at line 3274 of file Native.cs.
Referenced by FuncDecl.operator==().
{
             int r = LIB.Z3_is_eq_func_decl(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_is_eq_sort (Z3_context a0, Z3_sort a1, Z3_sort a2) inline static
Definition at line 3146 of file Native.cs.
Referenced by Sort.operator==().
{
             int r = LIB.Z3_is_eq_sort(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_is_numeral_ast (Z3_context a0, Z3_ast a1) inline static
Definition at line 3506 of file Native.cs.
{
             int r = LIB.Z3_is_numeral_ast(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_is_quantifier_forall (Z3_context a0, Z3_ast a1) inline static
Definition at line 3666 of file Native.cs.
{
             int r = LIB.Z3_is_quantifier_forall(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_is_well_sorted (Z3_context a0, Z3_ast a1) inline static
Definition at line 3474 of file Native.cs.
{
             int r = LIB.Z3_is_well_sorted(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_add (Z3_context a0, uint a1, [In] Z3_ast[] a2) inline static
Definition at line 2338 of file Native.cs.
{
             Z3_ast r = LIB.Z3_mk_add(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_and (Z3_context a0, uint a1, [In] Z3_ast[] a2) inline static
Definition at line 2322 of file Native.cs.
Referenced by Context.MkAnd().
{
             Z3_ast r = LIB.Z3_mk_and(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_app (Z3_context a0, Z3_func_decl a1, uint a2, [In] Z3_ast[] a3) inline static
Definition at line 2218 of file Native.cs.
{
             Z3_ast r = LIB.Z3_mk_app(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_array_default (Z3_context a0, Z3_ast a1) inline static
Definition at line 2874 of file Native.cs.
Referenced by Context.MkTermArray().
{
             Z3_ast r = LIB.Z3_mk_array_default(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_mk_array_sort (Z3_context a0, Z3_sort a1, Z3_sort a2) inline static
Definition at line 2126 of file Native.cs.
{
             Z3_sort r = LIB.Z3_mk_array_sort(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast_map Z3_mk_ast_map (Z3_context a0) inline static
Definition at line 4498 of file Native.cs.
{
             Z3_ast_map r = LIB.Z3_mk_ast_map(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast_vector Z3_mk_ast_vector (Z3_context a0) inline static
Definition at line 4423 of file Native.cs.
{
             Z3_ast_vector r = LIB.Z3_mk_ast_vector(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_mk_bool_sort (Z3_context a0) inline static
Definition at line 2086 of file Native.cs.
{
             Z3_sort r = LIB.Z3_mk_bool_sort(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bound (Z3_context a0, uint a1, Z3_sort a2) inline static
Definition at line 3026 of file Native.cs.
{
             Z3_ast r = LIB.Z3_mk_bound(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bv2int (Z3_context a0, Z3_ast a1, int a2) inline static
Definition at line 2770 of file Native.cs.
Referenced by Context.MkBV2Int().
{
             Z3_ast r = LIB.Z3_mk_bv2int(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_mk_bv_sort (Z3_context a0, uint a1) inline static
Definition at line 2110 of file Native.cs.
Referenced by Context.MkBitVecSort().
{
             Z3_sort r = LIB.Z3_mk_bv_sort(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvadd (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2538 of file Native.cs.
Referenced by Context.MkBVAdd().
{
             Z3_ast r = LIB.Z3_mk_bvadd(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvadd_no_overflow (Z3_context a0, Z3_ast a1, Z3_ast a2, int a3) inline static
Definition at line 2778 of file Native.cs.
Referenced by Context.MkBVAddNoOverflow().
{
             Z3_ast r = LIB.Z3_mk_bvadd_no_overflow(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvadd_no_underflow (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2786 of file Native.cs.
Referenced by Context.MkBVAddNoUnderflow().
{
             Z3_ast r = LIB.Z3_mk_bvadd_no_underflow(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvand (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2482 of file Native.cs.
Referenced by Context.MkBVAND().
{
             Z3_ast r = LIB.Z3_mk_bvand(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvashr (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2722 of file Native.cs.
Referenced by Context.MkBVASHR().
{
             Z3_ast r = LIB.Z3_mk_bvashr(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvlshr (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2714 of file Native.cs.
Referenced by Context.MkBVLSHR().
{
             Z3_ast r = LIB.Z3_mk_bvlshr(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvmul (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2554 of file Native.cs.
Referenced by Context.MkBVMul().
{
             Z3_ast r = LIB.Z3_mk_bvmul(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvmul_no_overflow (Z3_context a0, Z3_ast a1, Z3_ast a2, int a3) inline static
Definition at line 2826 of file Native.cs.
Referenced by Context.MkBVMulNoOverflow().
{
             Z3_ast r = LIB.Z3_mk_bvmul_no_overflow(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvmul_no_underflow (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2834 of file Native.cs.
Referenced by Context.MkBVMulNoUnderflow().
{
             Z3_ast r = LIB.Z3_mk_bvmul_no_underflow(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvnand (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2506 of file Native.cs.
Referenced by Context.MkBVNAND().
{
             Z3_ast r = LIB.Z3_mk_bvnand(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvneg (Z3_context a0, Z3_ast a1) inline static
Definition at line 2530 of file Native.cs.
Referenced by Context.MkBVNeg().
{
             Z3_ast r = LIB.Z3_mk_bvneg(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvneg_no_overflow (Z3_context a0, Z3_ast a1) inline static
Definition at line 2818 of file Native.cs.
Referenced by Context.MkBVNegNoOverflow().
{
             Z3_ast r = LIB.Z3_mk_bvneg_no_overflow(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvnor (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2514 of file Native.cs.
Referenced by Context.MkBVNOR().
{
             Z3_ast r = LIB.Z3_mk_bvnor(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvnot (Z3_context a0, Z3_ast a1) inline static
Definition at line 2458 of file Native.cs.
{
             Z3_ast r = LIB.Z3_mk_bvnot(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvor (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2490 of file Native.cs.
Referenced by Context.MkBVOR().
{
             Z3_ast r = LIB.Z3_mk_bvor(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvredand (Z3_context a0, Z3_ast a1) inline static
Definition at line 2466 of file Native.cs.
Referenced by Context.MkBVRedAND().
{
             Z3_ast r = LIB.Z3_mk_bvredand(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvredor (Z3_context a0, Z3_ast a1) inline static
Definition at line 2474 of file Native.cs.
Referenced by Context.MkBVRedOR().
{
             Z3_ast r = LIB.Z3_mk_bvredor(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvsdiv (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2570 of file Native.cs.
Referenced by Context.MkBVSDiv().
{
             Z3_ast r = LIB.Z3_mk_bvsdiv(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvsdiv_no_overflow (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2810 of file Native.cs.
Referenced by Context.MkBVSDivNoOverflow().
{
             Z3_ast r = LIB.Z3_mk_bvsdiv_no_overflow(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvsge (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2642 of file Native.cs.
Referenced by Context.MkBVSGE().
{
             Z3_ast r = LIB.Z3_mk_bvsge(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvsgt (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2658 of file Native.cs.
Referenced by Context.MkBVSGT().
{
             Z3_ast r = LIB.Z3_mk_bvsgt(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvshl (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2706 of file Native.cs.
Referenced by Context.MkBVSHL().
{
             Z3_ast r = LIB.Z3_mk_bvshl(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvsle (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2626 of file Native.cs.
Referenced by Context.MkBVSLE().
{
             Z3_ast r = LIB.Z3_mk_bvsle(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvslt (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2610 of file Native.cs.
Referenced by Context.MkBVSLT().
{
             Z3_ast r = LIB.Z3_mk_bvslt(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvsmod (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2594 of file Native.cs.
Referenced by Context.MkBVSMod().
{
             Z3_ast r = LIB.Z3_mk_bvsmod(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvsrem (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2586 of file Native.cs.
Referenced by Context.MkBVSRem().
{
             Z3_ast r = LIB.Z3_mk_bvsrem(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvsub (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2546 of file Native.cs.
Referenced by Context.MkBVSub().
{
             Z3_ast r = LIB.Z3_mk_bvsub(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvsub_no_overflow (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2794 of file Native.cs.
Referenced by Context.MkBVSubNoOverflow().
{
             Z3_ast r = LIB.Z3_mk_bvsub_no_overflow(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvsub_no_underflow (Z3_context a0, Z3_ast a1, Z3_ast a2, int a3) inline static
Definition at line 2802 of file Native.cs.
Referenced by Context.MkBVSubNoUnderflow().
{
             Z3_ast r = LIB.Z3_mk_bvsub_no_underflow(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvudiv (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2562 of file Native.cs.
Referenced by Context.MkBVUDiv().
{
             Z3_ast r = LIB.Z3_mk_bvudiv(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvuge (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2634 of file Native.cs.
Referenced by Context.MkBVUGE().
{
             Z3_ast r = LIB.Z3_mk_bvuge(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvugt (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2650 of file Native.cs.
Referenced by Context.MkBVUGT().
{
             Z3_ast r = LIB.Z3_mk_bvugt(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvule (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2618 of file Native.cs.
Referenced by Context.MkBVULE().
{
             Z3_ast r = LIB.Z3_mk_bvule(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvult (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2602 of file Native.cs.
Referenced by Context.MkBVULT().
{
             Z3_ast r = LIB.Z3_mk_bvult(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvurem (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2578 of file Native.cs.
Referenced by Context.MkBVURem().
{
             Z3_ast r = LIB.Z3_mk_bvurem(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvxnor (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2522 of file Native.cs.
Referenced by Context.MkBVXNOR().
{
             Z3_ast r = LIB.Z3_mk_bvxnor(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_bvxor (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2498 of file Native.cs.
Referenced by Context.MkBVXOR().
{
             Z3_ast r = LIB.Z3_mk_bvxor(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_concat (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2666 of file Native.cs.
Referenced by Context.MkConcat().
{
             Z3_ast r = LIB.Z3_mk_concat(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_config Z3_mk_config () inline static
Definition at line 1892 of file Native.cs.
Referenced by Context.Context().
{
             Z3_config r = LIB.Z3_mk_config();
             return r;
         }
static Z3_ast Z3_mk_const (Z3_context a0, IntPtr a1, Z3_sort a2) inline static
Definition at line 2226 of file Native.cs.
{
             Z3_ast r = LIB.Z3_mk_const(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_const_array (Z3_context a0, Z3_sort a1, Z3_ast a2) inline static
Definition at line 2858 of file Native.cs.
Referenced by Context.MkConstArray().
{
             Z3_ast r = LIB.Z3_mk_const_array(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_constructor Z3_mk_constructor (Z3_context a0, IntPtr a1, IntPtr a2, uint a3, [In] IntPtr[] a4, [In] Z3_sort[] a5, [In] uint[] a6) inline static
Definition at line 2158 of file Native.cs.
{
             Z3_constructor r = LIB.Z3_mk_constructor(a0, a1, a2, a3, a4, a5, a6);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_constructor_list Z3_mk_constructor_list (Z3_context a0, uint a1, [In] Z3_constructor[] a2) inline static
Definition at line 2181 of file Native.cs.
{
             Z3_constructor_list r = LIB.Z3_mk_constructor_list(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_context Z3_mk_context (Z3_config a0) inline static
Definition at line 1905 of file Native.cs.
{
             Z3_context r = LIB.Z3_mk_context(a0);
             if (r == IntPtr.Zero)
                 throw new Z3Exception("Object allocation failed.");
             return r;
         }
static Z3_context Z3_mk_context_rc (Z3_config a0) inline static
Definition at line 1912 of file Native.cs.
Referenced by Context.Context().
{
             Z3_context r = LIB.Z3_mk_context_rc(a0);
             if (r == IntPtr.Zero)
                 throw new Z3Exception("Object allocation failed.");
             return r;
         }
static Z3_sort Z3_mk_datatype (Z3_context a0, IntPtr a1, uint a2, [In, Out] Z3_constructor[] a3) inline static
Definition at line 2173 of file Native.cs.
{
             Z3_sort r = LIB.Z3_mk_datatype(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_mk_datatypes (Z3_context a0, uint a1, [In] IntPtr[] a2, [Out] Z3_sort[] a3, [In, Out] Z3_constructor_list[] a4) inline static
Definition at line 2196 of file Native.cs.
Referenced by Context.MkDatatypeSorts().
{
             LIB.Z3_mk_datatypes(a0, a1, a2, a3, a4);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static Z3_ast Z3_mk_distinct (Z3_context a0, uint a1, [In] Z3_ast[] a2) inline static
Definition at line 2274 of file Native.cs.
Referenced by Context.MkDistinct().
{
             Z3_ast r = LIB.Z3_mk_distinct(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_div (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2370 of file Native.cs.
Referenced by Context.MkDiv().
{
             Z3_ast r = LIB.Z3_mk_div(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_empty_set (Z3_context a0, Z3_sort a1) inline static
Definition at line 2890 of file Native.cs.
Referenced by Context.MkEmptySet().
{
             Z3_ast r = LIB.Z3_mk_empty_set(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_mk_enumeration_sort (Z3_context a0, IntPtr a1, uint a2, [In] IntPtr[] a3, [Out] Z3_func_decl[] a4, [Out] Z3_func_decl[] a5) inline static
Definition at line 2142 of file Native.cs.
{
             Z3_sort r = LIB.Z3_mk_enumeration_sort(a0, a1, a2, a3, a4, a5);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_eq (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2266 of file Native.cs.
Referenced by Context.MkEq().
{
             Z3_ast r = LIB.Z3_mk_eq(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_exists (Z3_context a0, uint a1, uint a2, [In] Z3_pattern[] a3, uint a4, [In] Z3_sort[] a5, [In] IntPtr[] a6, Z3_ast a7) inline static
Definition at line 3042 of file Native.cs.
{
             Z3_ast r = LIB.Z3_mk_exists(a0, a1, a2, a3, a4, a5, a6, a7);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_exists_const (Z3_context a0, uint a1, uint a2, [In] Z3_app[] a3, uint a4, [In] Z3_pattern[] a5, Z3_ast a6) inline static
Definition at line 3074 of file Native.cs.
{
             Z3_ast r = LIB.Z3_mk_exists_const(a0, a1, a2, a3, a4, a5, a6);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_ext_rotate_left (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2746 of file Native.cs.
Referenced by Context.MkBVRotateLeft().
{
             Z3_ast r = LIB.Z3_mk_ext_rotate_left(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_ext_rotate_right (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2754 of file Native.cs.
Referenced by Context.MkBVRotateRight().
{
             Z3_ast r = LIB.Z3_mk_ext_rotate_right(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_extract (Z3_context a0, uint a1, uint a2, Z3_ast a3) inline static
Definition at line 2674 of file Native.cs.
Referenced by Context.MkExtract().
{
             Z3_ast r = LIB.Z3_mk_extract(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_false (Z3_context a0) inline static
Definition at line 2258 of file Native.cs.
Referenced by Context.MkFalse().
{
             Z3_ast r = LIB.Z3_mk_false(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_mk_finite_domain_sort (Z3_context a0, IntPtr a1, UInt64 a2) inline static
Definition at line 2118 of file Native.cs.
{
             Z3_sort r = LIB.Z3_mk_finite_domain_sort(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_fixedpoint Z3_mk_fixedpoint (Z3_context a0) inline static
Definition at line 4219 of file Native.cs.
{
             Z3_fixedpoint r = LIB.Z3_mk_fixedpoint(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_forall (Z3_context a0, uint a1, uint a2, [In] Z3_pattern[] a3, uint a4, [In] Z3_sort[] a5, [In] IntPtr[] a6, Z3_ast a7) inline static
Definition at line 3034 of file Native.cs.
{
             Z3_ast r = LIB.Z3_mk_forall(a0, a1, a2, a3, a4, a5, a6, a7);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_forall_const (Z3_context a0, uint a1, uint a2, [In] Z3_app[] a3, uint a4, [In] Z3_pattern[] a5, Z3_ast a6) inline static
Definition at line 3066 of file Native.cs.
{
             Z3_ast r = LIB.Z3_mk_forall_const(a0, a1, a2, a3, a4, a5, a6);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_abs (Z3_context a0, Z3_ast a1) inline static
Definition at line 6256 of file Native.cs.
{
             Z3_ast r = LIB.Z3_mk_fpa_abs(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_add (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_ast a3) inline static
Definition at line 6272 of file Native.cs.
Referenced by Context.MkFPAdd().
{
             Z3_ast r = LIB.Z3_mk_fpa_add(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_div (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_ast a3) inline static
Definition at line 6296 of file Native.cs.
Referenced by Context.MkFPDiv().
{
             Z3_ast r = LIB.Z3_mk_fpa_div(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_eq (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 6384 of file Native.cs.
Referenced by Context.MkFPEq().
{
             Z3_ast r = LIB.Z3_mk_fpa_eq(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_fma (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_ast a3, Z3_ast a4) inline static
Definition at line 6304 of file Native.cs.
Referenced by Context.MkFPFMA().
{
             Z3_ast r = LIB.Z3_mk_fpa_fma(a0, a1, a2, a3, a4);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_fp (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_ast a3) inline static
Definition at line 6208 of file Native.cs.
{
             Z3_ast r = LIB.Z3_mk_fpa_fp(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_geq (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 6368 of file Native.cs.
Referenced by Context.MkFPGEq().
{
             Z3_ast r = LIB.Z3_mk_fpa_geq(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_gt (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 6376 of file Native.cs.
Referenced by Context.MkFPGt().
{
             Z3_ast r = LIB.Z3_mk_fpa_gt(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_inf (Z3_context a0, Z3_sort a1, int a2) inline static
Definition at line 6192 of file Native.cs.
Referenced by Context.MkFPInf().
{
             Z3_ast r = LIB.Z3_mk_fpa_inf(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_is_infinite (Z3_context a0, Z3_ast a1) inline static
Definition at line 6416 of file Native.cs.
Referenced by Context.MkFPIsInfinite().
{
             Z3_ast r = LIB.Z3_mk_fpa_is_infinite(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_is_nan (Z3_context a0, Z3_ast a1) inline static
Definition at line 6424 of file Native.cs.
Referenced by Context.MkFPIsNaN().
{
             Z3_ast r = LIB.Z3_mk_fpa_is_nan(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_is_negative (Z3_context a0, Z3_ast a1) inline static
Definition at line 6432 of file Native.cs.
Referenced by Context.MkFPIsNegative().
{
             Z3_ast r = LIB.Z3_mk_fpa_is_negative(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_is_normal (Z3_context a0, Z3_ast a1) inline static
Definition at line 6392 of file Native.cs.
Referenced by Context.MkFPIsNormal().
{
             Z3_ast r = LIB.Z3_mk_fpa_is_normal(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_is_positive (Z3_context a0, Z3_ast a1) inline static
Definition at line 6440 of file Native.cs.
Referenced by Context.MkFPIsPositive().
{
             Z3_ast r = LIB.Z3_mk_fpa_is_positive(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_is_subnormal (Z3_context a0, Z3_ast a1) inline static
Definition at line 6400 of file Native.cs.
Referenced by Context.MkFPIsSubnormal().
{
             Z3_ast r = LIB.Z3_mk_fpa_is_subnormal(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_is_zero (Z3_context a0, Z3_ast a1) inline static
Definition at line 6408 of file Native.cs.
Referenced by Context.MkFPIsZero().
{
             Z3_ast r = LIB.Z3_mk_fpa_is_zero(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_leq (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 6352 of file Native.cs.
Referenced by Context.MkFPLEq().
{
             Z3_ast r = LIB.Z3_mk_fpa_leq(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_lt (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 6360 of file Native.cs.
Referenced by Context.MkFPLt().
{
             Z3_ast r = LIB.Z3_mk_fpa_lt(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_max (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 6344 of file Native.cs.
Referenced by Context.MkFPMax().
{
             Z3_ast r = LIB.Z3_mk_fpa_max(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_min (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 6336 of file Native.cs.
Referenced by Context.MkFPMin().
{
             Z3_ast r = LIB.Z3_mk_fpa_min(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_mul (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_ast a3) inline static
Definition at line 6288 of file Native.cs.
Referenced by Context.MkFPMul().
{
             Z3_ast r = LIB.Z3_mk_fpa_mul(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_nan (Z3_context a0, Z3_sort a1) inline static
Definition at line 6184 of file Native.cs.
{
             Z3_ast r = LIB.Z3_mk_fpa_nan(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_neg (Z3_context a0, Z3_ast a1) inline static
Definition at line 6264 of file Native.cs.
Referenced by Context.MkFPNeg().
{
             Z3_ast r = LIB.Z3_mk_fpa_neg(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_numeral_double (Z3_context a0, double a1, Z3_sort a2) inline static
Definition at line 6224 of file Native.cs.
Referenced by Context.MkFPNumeral().
{
             Z3_ast r = LIB.Z3_mk_fpa_numeral_double(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_numeral_float (Z3_context a0, float a1, Z3_sort a2) inline static
Definition at line 6216 of file Native.cs.
Referenced by Context.MkFPNumeral().
{
             Z3_ast r = LIB.Z3_mk_fpa_numeral_float(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_numeral_int (Z3_context a0, int a1, Z3_sort a2) inline static
Definition at line 6232 of file Native.cs.
Referenced by Context.MkFPNumeral().
{
             Z3_ast r = LIB.Z3_mk_fpa_numeral_int(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_numeral_int64_uint64 (Z3_context a0, int a1, Int64 a2, UInt64 a3, Z3_sort a4) inline static
Definition at line 6248 of file Native.cs.
Referenced by Context.MkFPNumeral().
{
             Z3_ast r = LIB.Z3_mk_fpa_numeral_int64_uint64(a0, a1, a2, a3, a4);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_numeral_int_uint (Z3_context a0, int a1, int a2, uint a3, Z3_sort a4) inline static
Definition at line 6240 of file Native.cs.
Referenced by Context.MkFPNumeral().
{
             Z3_ast r = LIB.Z3_mk_fpa_numeral_int_uint(a0, a1, a2, a3, a4);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_rem (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 6320 of file Native.cs.
Referenced by Context.MkFPRem().
{
             Z3_ast r = LIB.Z3_mk_fpa_rem(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_rna (Z3_context a0) inline static
Definition at line 6056 of file Native.cs.
Referenced by Context.MkFPRNA().
{
             Z3_ast r = LIB.Z3_mk_fpa_rna(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_rne (Z3_context a0) inline static
Definition at line 6040 of file Native.cs.
Referenced by Context.MkFPRNE().
{
             Z3_ast r = LIB.Z3_mk_fpa_rne(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_round_nearest_ties_to_away (Z3_context a0) inline static
Definition at line 6048 of file Native.cs.
Referenced by Context.MkFPRoundNearestTiesToAway().
{
             Z3_ast r = LIB.Z3_mk_fpa_round_nearest_ties_to_away(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_round_nearest_ties_to_even (Z3_context a0) inline static
Definition at line 6032 of file Native.cs.
{
             Z3_ast r = LIB.Z3_mk_fpa_round_nearest_ties_to_even(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_round_to_integral (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 6328 of file Native.cs.
Referenced by Context.MkFPRoundToIntegral().
{
             Z3_ast r = LIB.Z3_mk_fpa_round_to_integral(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_round_toward_negative (Z3_context a0) inline static
Definition at line 6080 of file Native.cs.
Referenced by Context.MkFPRoundTowardNegative().
{
             Z3_ast r = LIB.Z3_mk_fpa_round_toward_negative(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_round_toward_positive (Z3_context a0) inline static
Definition at line 6064 of file Native.cs.
Referenced by Context.MkFPRoundTowardPositive().
{
             Z3_ast r = LIB.Z3_mk_fpa_round_toward_positive(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_round_toward_zero (Z3_context a0) inline static
Definition at line 6096 of file Native.cs.
Referenced by Context.MkFPRoundTowardZero().
{
             Z3_ast r = LIB.Z3_mk_fpa_round_toward_zero(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_mk_fpa_rounding_mode_sort (Z3_context a0) inline static
Definition at line 6024 of file Native.cs.
{
             Z3_sort r = LIB.Z3_mk_fpa_rounding_mode_sort(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_rtn (Z3_context a0) inline static
Definition at line 6088 of file Native.cs.
Referenced by Context.MkFPRTN().
{
             Z3_ast r = LIB.Z3_mk_fpa_rtn(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_rtp (Z3_context a0) inline static
Definition at line 6072 of file Native.cs.
Referenced by Context.MkFPRTP().
{
             Z3_ast r = LIB.Z3_mk_fpa_rtp(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_rtz (Z3_context a0) inline static
Definition at line 6104 of file Native.cs.
Referenced by Context.MkFPRTZ().
{
             Z3_ast r = LIB.Z3_mk_fpa_rtz(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_mk_fpa_sort (Z3_context a0, uint a1, uint a2) inline static
Definition at line 6112 of file Native.cs.
{
             Z3_sort r = LIB.Z3_mk_fpa_sort(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_mk_fpa_sort_128 (Z3_context a0) inline static
Definition at line 6176 of file Native.cs.
Referenced by Context.MkFPSort128().
{
             Z3_sort r = LIB.Z3_mk_fpa_sort_128(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_mk_fpa_sort_16 (Z3_context a0) inline static
Definition at line 6128 of file Native.cs.
Referenced by Context.MkFPSort16().
{
             Z3_sort r = LIB.Z3_mk_fpa_sort_16(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_mk_fpa_sort_32 (Z3_context a0) inline static
Definition at line 6144 of file Native.cs.
Referenced by Context.MkFPSort32().
{
             Z3_sort r = LIB.Z3_mk_fpa_sort_32(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_mk_fpa_sort_64 (Z3_context a0) inline static
Definition at line 6160 of file Native.cs.
Referenced by Context.MkFPSort64().
{
             Z3_sort r = LIB.Z3_mk_fpa_sort_64(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_mk_fpa_sort_double (Z3_context a0) inline static
Definition at line 6152 of file Native.cs.
Referenced by Context.MkFPSortDouble().
{
             Z3_sort r = LIB.Z3_mk_fpa_sort_double(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_mk_fpa_sort_half (Z3_context a0) inline static
Definition at line 6120 of file Native.cs.
Referenced by Context.MkFPSortHalf().
{
             Z3_sort r = LIB.Z3_mk_fpa_sort_half(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_mk_fpa_sort_quadruple (Z3_context a0) inline static
Definition at line 6168 of file Native.cs.
Referenced by Context.MkFPSortQuadruple().
{
             Z3_sort r = LIB.Z3_mk_fpa_sort_quadruple(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_mk_fpa_sort_single (Z3_context a0) inline static
Definition at line 6136 of file Native.cs.
Referenced by Context.MkFPSortSingle().
{
             Z3_sort r = LIB.Z3_mk_fpa_sort_single(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_sqrt (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 6312 of file Native.cs.
Referenced by Context.MkFPSqrt().
{
             Z3_ast r = LIB.Z3_mk_fpa_sqrt(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_sub (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_ast a3) inline static
Definition at line 6280 of file Native.cs.
Referenced by Context.MkFPSub().
{
             Z3_ast r = LIB.Z3_mk_fpa_sub(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_to_fp_bv (Z3_context a0, Z3_ast a1, Z3_sort a2) inline static
Definition at line 6448 of file Native.cs.
Referenced by Context.MkFPToFP().
{
             Z3_ast r = LIB.Z3_mk_fpa_to_fp_bv(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_to_fp_float (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_sort a3) inline static
Definition at line 6456 of file Native.cs.
Referenced by Context.MkFPToFP().
{
             Z3_ast r = LIB.Z3_mk_fpa_to_fp_float(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_to_fp_int_real (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_ast a3, Z3_sort a4) inline static
Definition at line 6568 of file Native.cs.
Referenced by Context.MkFPToFP().
{
             Z3_ast r = LIB.Z3_mk_fpa_to_fp_int_real(a0, a1, a2, a3, a4);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_to_fp_real (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_sort a3) inline static
Definition at line 6464 of file Native.cs.
Referenced by Context.MkFPToFP().
{
             Z3_ast r = LIB.Z3_mk_fpa_to_fp_real(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_to_fp_signed (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_sort a3) inline static
Definition at line 6472 of file Native.cs.
Referenced by Context.MkFPToFP().
{
             Z3_ast r = LIB.Z3_mk_fpa_to_fp_signed(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_to_fp_unsigned (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_sort a3) inline static
Definition at line 6480 of file Native.cs.
Referenced by Context.MkFPToFP().
{
             Z3_ast r = LIB.Z3_mk_fpa_to_fp_unsigned(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_to_ieee_bv (Z3_context a0, Z3_ast a1) inline static
Definition at line 6560 of file Native.cs.
{
             Z3_ast r = LIB.Z3_mk_fpa_to_ieee_bv(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_to_real (Z3_context a0, Z3_ast a1) inline static
Definition at line 6504 of file Native.cs.
Referenced by Context.MkFPToReal().
{
             Z3_ast r = LIB.Z3_mk_fpa_to_real(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_to_sbv (Z3_context a0, Z3_ast a1, Z3_ast a2, uint a3) inline static
Definition at line 6496 of file Native.cs.
{
             Z3_ast r = LIB.Z3_mk_fpa_to_sbv(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_to_ubv (Z3_context a0, Z3_ast a1, Z3_ast a2, uint a3) inline static
Definition at line 6488 of file Native.cs.
{
             Z3_ast r = LIB.Z3_mk_fpa_to_ubv(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fpa_zero (Z3_context a0, Z3_sort a1, int a2) inline static
Definition at line 6200 of file Native.cs.
Referenced by Context.MkFPZero().
{
             Z3_ast r = LIB.Z3_mk_fpa_zero(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_fresh_const (Z3_context a0, string a1, Z3_sort a2) inline static
Definition at line 2242 of file Native.cs.
Referenced by Context.MkFreshConst().
{
             Z3_ast r = LIB.Z3_mk_fresh_const(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_func_decl Z3_mk_fresh_func_decl (Z3_context a0, string a1, uint a2, [In] Z3_sort[] a3, Z3_sort a4) inline static
Definition at line 2234 of file Native.cs.
{
             Z3_func_decl r = LIB.Z3_mk_fresh_func_decl(a0, a1, a2, a3, a4);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_full_set (Z3_context a0, Z3_sort a1) inline static
Definition at line 2898 of file Native.cs.
Referenced by Context.MkFullSet().
{
             Z3_ast r = LIB.Z3_mk_full_set(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_func_decl Z3_mk_func_decl (Z3_context a0, IntPtr a1, uint a2, [In] Z3_sort[] a3, Z3_sort a4) inline static
Definition at line 2210 of file Native.cs.
{
             Z3_func_decl r = LIB.Z3_mk_func_decl(a0, a1, a2, a3, a4);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_ge (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2426 of file Native.cs.
Referenced by Context.MkGe().
{
             Z3_ast r = LIB.Z3_mk_ge(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_goal Z3_mk_goal (Z3_context a0, int a1, int a2, int a3) inline static
Definition at line 4581 of file Native.cs.
{
             Z3_goal r = LIB.Z3_mk_goal(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_gt (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2418 of file Native.cs.
Referenced by Context.MkGt().
{
             Z3_ast r = LIB.Z3_mk_gt(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_iff (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2298 of file Native.cs.
Referenced by Context.MkIff().
{
             Z3_ast r = LIB.Z3_mk_iff(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_implies (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2306 of file Native.cs.
Referenced by Context.MkImplies().
{
             Z3_ast r = LIB.Z3_mk_implies(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_func_decl Z3_mk_injective_function (Z3_context a0, IntPtr a1, uint a2, [In] Z3_sort[] a3, Z3_sort a4) inline static
Definition at line 5305 of file Native.cs.
{
             Z3_func_decl r = LIB.Z3_mk_injective_function(a0, a1, a2, a3, a4);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_int (Z3_context a0, int a1, Z3_sort a2) inline static
Definition at line 2986 of file Native.cs.
Referenced by Context.MkInt(), Context.MkNumeral(), and Context.MkReal().
{
             Z3_ast r = LIB.Z3_mk_int(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_int2bv (Z3_context a0, uint a1, Z3_ast a2) inline static
Definition at line 2762 of file Native.cs.
Referenced by Context.MkInt2BV().
{
             Z3_ast r = LIB.Z3_mk_int2bv(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_int2real (Z3_context a0, Z3_ast a1) inline static
Definition at line 2434 of file Native.cs.
Referenced by Context.MkInt2Real().
{
             Z3_ast r = LIB.Z3_mk_int2real(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_int64 (Z3_context a0, Int64 a1, Z3_sort a2) inline static
Definition at line 3002 of file Native.cs.
Referenced by Context.MkInt(), Context.MkNumeral(), and Context.MkReal().
{
             Z3_ast r = LIB.Z3_mk_int64(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_mk_int_sort (Z3_context a0) inline static
Definition at line 2094 of file Native.cs.
{
             Z3_sort r = LIB.Z3_mk_int_sort(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static IntPtr Z3_mk_int_symbol (Z3_context a0, int a1) inline static
Definition at line 2062 of file Native.cs.
{
             IntPtr r = LIB.Z3_mk_int_symbol(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_interpolant (Z3_context a0, Z3_ast a1) inline static
Definition at line 5964 of file Native.cs.
{
             Z3_ast r = LIB.Z3_mk_interpolant(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_context Z3_mk_interpolation_context (Z3_config a0) inline static
Definition at line 5972 of file Native.cs.
{
             Z3_context r = LIB.Z3_mk_interpolation_context(a0);
             return r;
         }
static Z3_ast Z3_mk_is_int (Z3_context a0, Z3_ast a1) inline static
Definition at line 2450 of file Native.cs.
Referenced by Context.MkIsInteger().
{
             Z3_ast r = LIB.Z3_mk_is_int(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_ite (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_ast a3) inline static
Definition at line 2290 of file Native.cs.
Referenced by Context.MkITE().
{
             Z3_ast r = LIB.Z3_mk_ite(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_label (Z3_context a0, IntPtr a1, int a2, Z3_ast a3) inline static
Definition at line 5410 of file Native.cs.
{
             Z3_ast r = LIB.Z3_mk_label(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_le (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2410 of file Native.cs.
Referenced by Context.MkLe().
{
             Z3_ast r = LIB.Z3_mk_le(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_mk_list_sort (Z3_context a0, IntPtr a1, Z3_sort a2, [In, Out] ref Z3_func_decl a3, [In, Out] ref Z3_func_decl a4, [In, Out] ref Z3_func_decl a5, [In, Out] ref Z3_func_decl a6, [In, Out] ref Z3_func_decl a7, [In, Out] ref Z3_func_decl a8) inline static
Definition at line 2150 of file Native.cs.
{
             Z3_sort r = LIB.Z3_mk_list_sort(a0, a1, a2, ref a3, ref a4, ref a5, ref a6, ref a7, ref a8);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_lt (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2402 of file Native.cs.
Referenced by Context.MkLt().
{
             Z3_ast r = LIB.Z3_mk_lt(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_map (Z3_context a0, Z3_func_decl a1, uint a2, [In] Z3_ast[] a3) inline static
Definition at line 2866 of file Native.cs.
Referenced by Context.MkMap().
{
             Z3_ast r = LIB.Z3_mk_map(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_mod (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2378 of file Native.cs.
Referenced by Context.MkMod().
{
             Z3_ast r = LIB.Z3_mk_mod(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_mul (Z3_context a0, uint a1, [In] Z3_ast[] a2) inline static
Definition at line 2346 of file Native.cs.
Referenced by Context.MkMul().
{
             Z3_ast r = LIB.Z3_mk_mul(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_not (Z3_context a0, Z3_ast a1) inline static
Definition at line 2282 of file Native.cs.
Referenced by Context.MkNot().
{
             Z3_ast r = LIB.Z3_mk_not(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_numeral (Z3_context a0, string a1, Z3_sort a2) inline static
Definition at line 2970 of file Native.cs.
Referenced by Context.MkReal().
{
             Z3_ast r = LIB.Z3_mk_numeral(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_or (Z3_context a0, uint a1, [In] Z3_ast[] a2) inline static
Definition at line 2330 of file Native.cs.
Referenced by Context.MkOr().
{
             Z3_ast r = LIB.Z3_mk_or(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_params Z3_mk_params (Z3_context a0) inline static
Definition at line 1951 of file Native.cs.
{
             Z3_params r = LIB.Z3_mk_params(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_pattern Z3_mk_pattern (Z3_context a0, uint a1, [In] Z3_ast[] a2) inline static
Definition at line 3018 of file Native.cs.
{
             Z3_pattern r = LIB.Z3_mk_pattern(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_power (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2394 of file Native.cs.
Referenced by Context.MkPower().
{
             Z3_ast r = LIB.Z3_mk_power(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_probe Z3_mk_probe (Z3_context a0, string a1) inline static
Definition at line 4719 of file Native.cs.
{
             Z3_probe r = LIB.Z3_mk_probe(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_quantifier (Z3_context a0, int a1, uint a2, uint a3, [In] Z3_pattern[] a4, uint a5, [In] Z3_sort[] a6, [In] IntPtr[] a7, Z3_ast a8) inline static
Definition at line 3050 of file Native.cs.
{
             Z3_ast r = LIB.Z3_mk_quantifier(a0, a1, a2, a3, a4, a5, a6, a7, a8);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_quantifier_const (Z3_context a0, int a1, uint a2, uint a3, [In] Z3_app[] a4, uint a5, [In] Z3_pattern[] a6, Z3_ast a7) inline static
Definition at line 3082 of file Native.cs.
{
             Z3_ast r = LIB.Z3_mk_quantifier_const(a0, a1, a2, a3, a4, a5, a6, a7);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_quantifier_const_ex (Z3_context a0, int a1, uint a2, IntPtr a3, IntPtr a4, uint a5, [In] Z3_app[] a6, uint a7, [In] Z3_pattern[] a8, uint a9, [In] Z3_ast[] a10, Z3_ast a11) inline static
Definition at line 3090 of file Native.cs.
{
             Z3_ast r = LIB.Z3_mk_quantifier_const_ex(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_quantifier_ex (Z3_context a0, int a1, uint a2, IntPtr a3, IntPtr a4, uint a5, [In] Z3_pattern[] a6, uint a7, [In] Z3_ast[] a8, uint a9, [In] Z3_sort[] a10, [In] IntPtr[] a11, Z3_ast a12) inline static
Definition at line 3058 of file Native.cs.
{
             Z3_ast r = LIB.Z3_mk_quantifier_ex(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_real (Z3_context a0, int a1, int a2) inline static
Definition at line 2978 of file Native.cs.
{
             Z3_ast r = LIB.Z3_mk_real(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_real2int (Z3_context a0, Z3_ast a1) inline static
Definition at line 2442 of file Native.cs.
Referenced by Context.MkReal2Int().
{
             Z3_ast r = LIB.Z3_mk_real2int(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_mk_real_sort (Z3_context a0) inline static
Definition at line 2102 of file Native.cs.
{
             Z3_sort r = LIB.Z3_mk_real_sort(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_rem (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2386 of file Native.cs.
Referenced by Context.MkRem().
{
             Z3_ast r = LIB.Z3_mk_rem(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_repeat (Z3_context a0, uint a1, Z3_ast a2) inline static
Definition at line 2698 of file Native.cs.
Referenced by Context.MkRepeat().
{
             Z3_ast r = LIB.Z3_mk_repeat(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_rotate_left (Z3_context a0, uint a1, Z3_ast a2) inline static
Definition at line 2730 of file Native.cs.
Referenced by Context.MkBVRotateLeft().
{
             Z3_ast r = LIB.Z3_mk_rotate_left(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_rotate_right (Z3_context a0, uint a1, Z3_ast a2) inline static
Definition at line 2738 of file Native.cs.
Referenced by Context.MkBVRotateRight().
{
             Z3_ast r = LIB.Z3_mk_rotate_right(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_select (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2842 of file Native.cs.
Referenced by Context.MkSelect().
{
             Z3_ast r = LIB.Z3_mk_select(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_set_add (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2906 of file Native.cs.
Referenced by Context.MkSetAdd().
{
             Z3_ast r = LIB.Z3_mk_set_add(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_set_complement (Z3_context a0, Z3_ast a1) inline static
Definition at line 2946 of file Native.cs.
Referenced by Context.MkSetComplement().
{
             Z3_ast r = LIB.Z3_mk_set_complement(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_set_del (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2914 of file Native.cs.
Referenced by Context.MkSetDel().
{
             Z3_ast r = LIB.Z3_mk_set_del(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_set_difference (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2938 of file Native.cs.
Referenced by Context.MkSetDifference().
{
             Z3_ast r = LIB.Z3_mk_set_difference(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_set_intersect (Z3_context a0, uint a1, [In] Z3_ast[] a2) inline static
Definition at line 2930 of file Native.cs.
Referenced by Context.MkSetIntersection().
{
             Z3_ast r = LIB.Z3_mk_set_intersect(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_set_member (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2954 of file Native.cs.
Referenced by Context.MkSetMembership().
{
             Z3_ast r = LIB.Z3_mk_set_member(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_mk_set_sort (Z3_context a0, Z3_sort a1) inline static
Definition at line 2882 of file Native.cs.
{
             Z3_sort r = LIB.Z3_mk_set_sort(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_set_subset (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2962 of file Native.cs.
Referenced by Context.MkSetSubset().
{
             Z3_ast r = LIB.Z3_mk_set_subset(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_set_union (Z3_context a0, uint a1, [In] Z3_ast[] a2) inline static
Definition at line 2922 of file Native.cs.
Referenced by Context.MkSetUnion().
{
             Z3_ast r = LIB.Z3_mk_set_union(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_sign_ext (Z3_context a0, uint a1, Z3_ast a2) inline static
Definition at line 2682 of file Native.cs.
Referenced by Context.MkSignExt().
{
             Z3_ast r = LIB.Z3_mk_sign_ext(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_solver Z3_mk_simple_solver (Z3_context a0) inline static
Definition at line 5059 of file Native.cs.
Referenced by Context.MkSimpleSolver().
{
             Z3_solver r = LIB.Z3_mk_simple_solver(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_solver Z3_mk_solver (Z3_context a0) inline static
Definition at line 5051 of file Native.cs.
{
             Z3_solver r = LIB.Z3_mk_solver(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_solver Z3_mk_solver_for_logic (Z3_context a0, IntPtr a1) inline static
Definition at line 5067 of file Native.cs.
{
             Z3_solver r = LIB.Z3_mk_solver_for_logic(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_solver Z3_mk_solver_from_tactic (Z3_context a0, Z3_tactic a1) inline static
Definition at line 5075 of file Native.cs.
Referenced by Context.MkSolver().
{
             Z3_solver r = LIB.Z3_mk_solver_from_tactic(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_store (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_ast a3) inline static
Definition at line 2850 of file Native.cs.
Referenced by Context.MkStore().
{
             Z3_ast r = LIB.Z3_mk_store(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static IntPtr Z3_mk_string_symbol (Z3_context a0, string a1) inline static
Definition at line 2070 of file Native.cs.
{
             IntPtr r = LIB.Z3_mk_string_symbol(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_sub (Z3_context a0, uint a1, [In] Z3_ast[] a2) inline static
Definition at line 2354 of file Native.cs.
Referenced by Context.MkSub().
{
             Z3_ast r = LIB.Z3_mk_sub(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_tactic Z3_mk_tactic (Z3_context a0, string a1) inline static
Definition at line 4697 of file Native.cs.
{
             Z3_tactic r = LIB.Z3_mk_tactic(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_true (Z3_context a0) inline static
Definition at line 2250 of file Native.cs.
{
             Z3_ast r = LIB.Z3_mk_true(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_mk_tuple_sort (Z3_context a0, IntPtr a1, uint a2, [In] IntPtr[] a3, [In] Z3_sort[] a4, [In, Out] ref Z3_func_decl a5, [Out] Z3_func_decl[] a6) inline static
Definition at line 2134 of file Native.cs.
{
             Z3_sort r = LIB.Z3_mk_tuple_sort(a0, a1, a2, a3, a4, ref a5, a6);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_unary_minus (Z3_context a0, Z3_ast a1) inline static
Definition at line 2362 of file Native.cs.
Referenced by Context.MkUnaryMinus().
{
             Z3_ast r = LIB.Z3_mk_unary_minus(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_mk_uninterpreted_sort (Z3_context a0, IntPtr a1) inline static
Definition at line 2078 of file Native.cs.
{
             Z3_sort r = LIB.Z3_mk_uninterpreted_sort(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_unsigned_int (Z3_context a0, uint a1, Z3_sort a2) inline static
Definition at line 2994 of file Native.cs.
Referenced by Context.MkInt(), Context.MkNumeral(), and Context.MkReal().
{
             Z3_ast r = LIB.Z3_mk_unsigned_int(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_unsigned_int64 (Z3_context a0, UInt64 a1, Z3_sort a2) inline static
Definition at line 3010 of file Native.cs.
Referenced by Context.MkInt(), Context.MkNumeral(), and Context.MkReal().
{
             Z3_ast r = LIB.Z3_mk_unsigned_int64(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_xor (Z3_context a0, Z3_ast a1, Z3_ast a2) inline static
Definition at line 2314 of file Native.cs.
Referenced by Context.MkXor().
{
             Z3_ast r = LIB.Z3_mk_xor(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_mk_zero_ext (Z3_context a0, uint a1, Z3_ast a2) inline static
Definition at line 2690 of file Native.cs.
Referenced by Context.MkZeroExt().
{
             Z3_ast r = LIB.Z3_mk_zero_ext(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_model_dec_ref (Z3_context a0, Z3_model a1) inline static
Definition at line 3817 of file Native.cs.
{
             LIB.Z3_model_dec_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static int Z3_model_eval (Z3_context a0, Z3_model a1, Z3_ast a2, int a3, [In, Out] ref Z3_ast a4) inline static
Definition at line 3824 of file Native.cs.
Referenced by Model.Eval().
{
             int r = LIB.Z3_model_eval(a0, a1, a2, a3, ref a4);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_func_decl Z3_model_get_const_decl (Z3_context a0, Z3_model a1, uint a2) inline static
Definition at line 3856 of file Native.cs.
{
             Z3_func_decl r = LIB.Z3_model_get_const_decl(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_model_get_const_interp (Z3_context a0, Z3_model a1, Z3_func_decl a2) inline static
Definition at line 3832 of file Native.cs.
Referenced by Model.ConstInterp(), and Model.FuncInterp().
{
             Z3_ast r = LIB.Z3_model_get_const_interp(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_func_decl Z3_model_get_func_decl (Z3_context a0, Z3_model a1, uint a2) inline static
Definition at line 3872 of file Native.cs.
{
             Z3_func_decl r = LIB.Z3_model_get_func_decl(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_func_interp Z3_model_get_func_interp (Z3_context a0, Z3_model a1, Z3_func_decl a2) inline static
Definition at line 3840 of file Native.cs.
Referenced by Model.FuncInterp().
{
             Z3_func_interp r = LIB.Z3_model_get_func_interp(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_model_get_num_consts (Z3_context a0, Z3_model a1) inline static
Definition at line 3848 of file Native.cs.
{
             uint r = LIB.Z3_model_get_num_consts(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_model_get_num_funcs (Z3_context a0, Z3_model a1) inline static
Definition at line 3864 of file Native.cs.
{
             uint r = LIB.Z3_model_get_num_funcs(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_model_get_num_sorts (Z3_context a0, Z3_model a1) inline static
Definition at line 3880 of file Native.cs.
{
             uint r = LIB.Z3_model_get_num_sorts(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_sort Z3_model_get_sort (Z3_context a0, Z3_model a1, uint a2) inline static
Definition at line 3888 of file Native.cs.
{
             Z3_sort r = LIB.Z3_model_get_sort(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast_vector Z3_model_get_sort_universe (Z3_context a0, Z3_model a1, Z3_sort a2) inline static
Definition at line 3896 of file Native.cs.
Referenced by Model.SortUniverse().
{
             Z3_ast_vector r = LIB.Z3_model_get_sort_universe(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_model_inc_ref (Z3_context a0, Z3_model a1) inline static
Definition at line 3810 of file Native.cs.
{
             LIB.Z3_model_inc_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static string Z3_model_to_string (Z3_context a0, Z3_model a1) inline static
Definition at line 4060 of file Native.cs.
Referenced by Model.ToString().
{
             IntPtr r = LIB.Z3_model_to_string(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static int Z3_open_log (string a0) inline static
Definition at line 4004 of file Native.cs.
{
             int r = LIB.Z3_open_log(a0);
             return r;
         }
static void Z3_param_descrs_dec_ref (Z3_context a0, Z3_param_descrs a1) inline static
Definition at line 2023 of file Native.cs.
{
             LIB.Z3_param_descrs_dec_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static uint Z3_param_descrs_get_kind (Z3_context a0, Z3_param_descrs a1, IntPtr a2) inline static
Definition at line 2030 of file Native.cs.
Referenced by ParamDescrs.GetKind().
{
             uint r = LIB.Z3_param_descrs_get_kind(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static IntPtr Z3_param_descrs_get_name (Z3_context a0, Z3_param_descrs a1, uint a2) inline static
Definition at line 2046 of file Native.cs.
{
             IntPtr r = LIB.Z3_param_descrs_get_name(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_param_descrs_inc_ref (Z3_context a0, Z3_param_descrs a1) inline static
Definition at line 2016 of file Native.cs.
{
             LIB.Z3_param_descrs_inc_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static uint Z3_param_descrs_size (Z3_context a0, Z3_param_descrs a1) inline static
Definition at line 2038 of file Native.cs.
{
             uint r = LIB.Z3_param_descrs_size(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_param_descrs_to_string (Z3_context a0, Z3_param_descrs a1) inline static
Definition at line 2054 of file Native.cs.
Referenced by ParamDescrs.ToString().
{
             IntPtr r = LIB.Z3_param_descrs_to_string(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static void Z3_params_dec_ref (Z3_context a0, Z3_params a1) inline static
Definition at line 1966 of file Native.cs.
{
             LIB.Z3_params_dec_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_params_inc_ref (Z3_context a0, Z3_params a1) inline static
Definition at line 1959 of file Native.cs.
{
             LIB.Z3_params_inc_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_params_set_bool (Z3_context a0, Z3_params a1, IntPtr a2, int a3) inline static
Definition at line 1973 of file Native.cs.
Referenced by Params.Add().
{
             LIB.Z3_params_set_bool(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_params_set_double (Z3_context a0, Z3_params a1, IntPtr a2, double a3) inline static
Definition at line 1987 of file Native.cs.
Referenced by Params.Add().
{
             LIB.Z3_params_set_double(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_params_set_symbol (Z3_context a0, Z3_params a1, IntPtr a2, IntPtr a3) inline static
Definition at line 1994 of file Native.cs.
Referenced by Params.Add().
{
             LIB.Z3_params_set_symbol(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_params_set_uint (Z3_context a0, Z3_params a1, IntPtr a2, uint a3) inline static
Definition at line 1980 of file Native.cs.
Referenced by Params.Add().
{
             LIB.Z3_params_set_uint(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static string Z3_params_to_string (Z3_context a0, Z3_params a1) inline static
Definition at line 2001 of file Native.cs.
Referenced by Params.ToString().
{
             IntPtr r = LIB.Z3_params_to_string(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static void Z3_params_validate (Z3_context a0, Z3_params a1, Z3_param_descrs a2) inline static
Definition at line 2009 of file Native.cs.
Referenced by ParamDescrs.Validate().
{
             LIB.Z3_params_validate(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static Z3_ast Z3_parse_smtlib2_file (Z3_context a0, string a1, uint a2, [In] IntPtr[] a3, [In] Z3_sort[] a4, uint a5, [In] IntPtr[] a6, [In] Z3_func_decl[] a7) inline static
Definition at line 4084 of file Native.cs.
Referenced by Context.ParseSMTLIB2File().
{
             Z3_ast r = LIB.Z3_parse_smtlib2_file(a0, a1, a2, a3, a4, a5, a6, a7);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_parse_smtlib2_string (Z3_context a0, string a1, uint a2, [In] IntPtr[] a3, [In] Z3_sort[] a4, uint a5, [In] IntPtr[] a6, [In] Z3_func_decl[] a7) inline static
Definition at line 4076 of file Native.cs.
Referenced by Context.ParseSMTLIB2String().
{
             Z3_ast r = LIB.Z3_parse_smtlib2_string(a0, a1, a2, a3, a4, a5, a6, a7);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_parse_smtlib_file (Z3_context a0, string a1, uint a2, [In] IntPtr[] a3, [In] Z3_sort[] a4, uint a5, [In] IntPtr[] a6, [In] Z3_func_decl[] a7) inline static
Definition at line 4099 of file Native.cs.
Referenced by Context.ParseSMTLIBFile().
{
             LIB.Z3_parse_smtlib_file(a0, a1, a2, a3, a4, a5, a6, a7);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_parse_smtlib_string (Z3_context a0, string a1, uint a2, [In] IntPtr[] a3, [In] Z3_sort[] a4, uint a5, [In] IntPtr[] a6, [In] Z3_func_decl[] a7) inline static
Definition at line 4092 of file Native.cs.
Referenced by Context.ParseSMTLIBString().
{
             LIB.Z3_parse_smtlib_string(a0, a1, a2, a3, a4, a5, a6, a7);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static Z3_ast Z3_pattern_to_ast (Z3_context a0, Z3_pattern a1) inline static
Definition at line 3634 of file Native.cs.
{
             Z3_ast r = LIB.Z3_pattern_to_ast(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_pattern_to_string (Z3_context a0, Z3_pattern a1) inline static
Definition at line 4036 of file Native.cs.
Referenced by Pattern.ToString().
{
             IntPtr r = LIB.Z3_pattern_to_string(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static void Z3_persist_ast (Z3_context a0, Z3_ast a1, uint a2) inline static
Definition at line 5342 of file Native.cs.
{
             LIB.Z3_persist_ast(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static Z3_ast_vector Z3_polynomial_subresultants (Z3_context a0, Z3_ast a1, Z3_ast a2, Z3_ast a3) inline static
Definition at line 5774 of file Native.cs.
{
             Z3_ast_vector r = LIB.Z3_polynomial_subresultants(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_pop (Z3_context a0, uint a1) inline static
Definition at line 5327 of file Native.cs.
{
             LIB.Z3_pop(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static Z3_probe Z3_probe_and (Z3_context a0, Z3_probe a1, Z3_probe a2) inline static
Definition at line 4893 of file Native.cs.
Referenced by Context.And().
{
             Z3_probe r = LIB.Z3_probe_and(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static double Z3_probe_apply (Z3_context a0, Z3_probe a1, Z3_goal a2) inline static
Definition at line 4981 of file Native.cs.
Referenced by Probe.Apply().
{
             double r = LIB.Z3_probe_apply(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_probe Z3_probe_const (Z3_context a0, double a1) inline static
Definition at line 4845 of file Native.cs.
Referenced by Context.ConstProbe().
{
             Z3_probe r = LIB.Z3_probe_const(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_probe_dec_ref (Z3_context a0, Z3_probe a1) inline static
Definition at line 4734 of file Native.cs.
{
             LIB.Z3_probe_dec_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static Z3_probe Z3_probe_eq (Z3_context a0, Z3_probe a1, Z3_probe a2) inline static
Definition at line 4885 of file Native.cs.
Referenced by Context.Eq().
{
             Z3_probe r = LIB.Z3_probe_eq(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_probe Z3_probe_ge (Z3_context a0, Z3_probe a1, Z3_probe a2) inline static
Definition at line 4877 of file Native.cs.
Referenced by Context.Ge().
{
             Z3_probe r = LIB.Z3_probe_ge(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_probe_get_descr (Z3_context a0, string a1) inline static
Definition at line 4973 of file Native.cs.
Referenced by Context.ProbeDescription().
{
             IntPtr r = LIB.Z3_probe_get_descr(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static Z3_probe Z3_probe_gt (Z3_context a0, Z3_probe a1, Z3_probe a2) inline static
Definition at line 4861 of file Native.cs.
Referenced by Context.Gt().
{
             Z3_probe r = LIB.Z3_probe_gt(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_probe_inc_ref (Z3_context a0, Z3_probe a1) inline static
Definition at line 4727 of file Native.cs.
{
             LIB.Z3_probe_inc_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static Z3_probe Z3_probe_le (Z3_context a0, Z3_probe a1, Z3_probe a2) inline static
Definition at line 4869 of file Native.cs.
Referenced by Context.Le().
{
             Z3_probe r = LIB.Z3_probe_le(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_probe Z3_probe_lt (Z3_context a0, Z3_probe a1, Z3_probe a2) inline static
Definition at line 4853 of file Native.cs.
Referenced by Context.Lt().
{
             Z3_probe r = LIB.Z3_probe_lt(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_probe Z3_probe_not (Z3_context a0, Z3_probe a1) inline static
Definition at line 4909 of file Native.cs.
Referenced by Context.Not().
{
             Z3_probe r = LIB.Z3_probe_not(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_probe Z3_probe_or (Z3_context a0, Z3_probe a1, Z3_probe a2) inline static
Definition at line 4901 of file Native.cs.
Referenced by Context.Or().
{
             Z3_probe r = LIB.Z3_probe_or(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_push (Z3_context a0) inline static
Definition at line 5320 of file Native.cs.
{
             LIB.Z3_push(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_query_constructor (Z3_context a0, Z3_constructor a1, uint a2, [In, Out] ref Z3_func_decl a3, [In, Out] ref Z3_func_decl a4, [Out] Z3_func_decl[] a5) inline static
Definition at line 2203 of file Native.cs.
{
             LIB.Z3_query_constructor(a0, a1, a2, ref a3, ref a4, a5);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static Z3_rcf_num Z3_rcf_add (Z3_context a0, Z3_rcf_num a1, Z3_rcf_num a2) inline static
Definition at line 5837 of file Native.cs.
{
             Z3_rcf_num r = LIB.Z3_rcf_add(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_rcf_del (Z3_context a0, Z3_rcf_num a1) inline static
Definition at line 5782 of file Native.cs.
{
             LIB.Z3_rcf_del(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static Z3_rcf_num Z3_rcf_div (Z3_context a0, Z3_rcf_num a1, Z3_rcf_num a2) inline static
Definition at line 5861 of file Native.cs.
{
             Z3_rcf_num r = LIB.Z3_rcf_div(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_rcf_eq (Z3_context a0, Z3_rcf_num a1, Z3_rcf_num a2) inline static
Definition at line 5925 of file Native.cs.
{
             int r = LIB.Z3_rcf_eq(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_rcf_ge (Z3_context a0, Z3_rcf_num a1, Z3_rcf_num a2) inline static
Definition at line 5917 of file Native.cs.
{
             int r = LIB.Z3_rcf_ge(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_rcf_get_numerator_denominator (Z3_context a0, Z3_rcf_num a1, [In, Out] ref Z3_rcf_num a2, [In, Out] ref Z3_rcf_num a3) inline static
Definition at line 5957 of file Native.cs.
{
             LIB.Z3_rcf_get_numerator_denominator(a0, a1, ref a2, ref a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static int Z3_rcf_gt (Z3_context a0, Z3_rcf_num a1, Z3_rcf_num a2) inline static
Definition at line 5901 of file Native.cs.
{
             int r = LIB.Z3_rcf_gt(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_rcf_num Z3_rcf_inv (Z3_context a0, Z3_rcf_num a1) inline static
Definition at line 5877 of file Native.cs.
{
             Z3_rcf_num r = LIB.Z3_rcf_inv(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_rcf_le (Z3_context a0, Z3_rcf_num a1, Z3_rcf_num a2) inline static
Definition at line 5909 of file Native.cs.
{
             int r = LIB.Z3_rcf_le(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_rcf_lt (Z3_context a0, Z3_rcf_num a1, Z3_rcf_num a2) inline static
Definition at line 5893 of file Native.cs.
{
             int r = LIB.Z3_rcf_lt(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_rcf_num Z3_rcf_mk_e (Z3_context a0) inline static
Definition at line 5813 of file Native.cs.
{
             Z3_rcf_num r = LIB.Z3_rcf_mk_e(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_rcf_num Z3_rcf_mk_infinitesimal (Z3_context a0) inline static
Definition at line 5821 of file Native.cs.
{
             Z3_rcf_num r = LIB.Z3_rcf_mk_infinitesimal(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_rcf_num Z3_rcf_mk_pi (Z3_context a0) inline static
Definition at line 5805 of file Native.cs.
{
             Z3_rcf_num r = LIB.Z3_rcf_mk_pi(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_rcf_num Z3_rcf_mk_rational (Z3_context a0, string a1) inline static
Definition at line 5789 of file Native.cs.
{
             Z3_rcf_num r = LIB.Z3_rcf_mk_rational(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_rcf_mk_roots (Z3_context a0, uint a1, [In] Z3_rcf_num[] a2, [Out] Z3_rcf_num[] a3) inline static
Definition at line 5829 of file Native.cs.
{
             uint r = LIB.Z3_rcf_mk_roots(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_rcf_num Z3_rcf_mk_small_int (Z3_context a0, int a1) inline static
Definition at line 5797 of file Native.cs.
{
             Z3_rcf_num r = LIB.Z3_rcf_mk_small_int(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_rcf_num Z3_rcf_mul (Z3_context a0, Z3_rcf_num a1, Z3_rcf_num a2) inline static
Definition at line 5853 of file Native.cs.
{
             Z3_rcf_num r = LIB.Z3_rcf_mul(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_rcf_num Z3_rcf_neg (Z3_context a0, Z3_rcf_num a1) inline static
Definition at line 5869 of file Native.cs.
{
             Z3_rcf_num r = LIB.Z3_rcf_neg(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_rcf_neq (Z3_context a0, Z3_rcf_num a1, Z3_rcf_num a2) inline static
Definition at line 5933 of file Native.cs.
{
             int r = LIB.Z3_rcf_neq(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_rcf_num_to_decimal_string (Z3_context a0, Z3_rcf_num a1, uint a2) inline static
Definition at line 5949 of file Native.cs.
{
             IntPtr r = LIB.Z3_rcf_num_to_decimal_string(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static string Z3_rcf_num_to_string (Z3_context a0, Z3_rcf_num a1, int a2, int a3) inline static
Definition at line 5941 of file Native.cs.
{
             IntPtr r = LIB.Z3_rcf_num_to_string(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static Z3_rcf_num Z3_rcf_power (Z3_context a0, Z3_rcf_num a1, uint a2) inline static
Definition at line 5885 of file Native.cs.
{
             Z3_rcf_num r = LIB.Z3_rcf_power(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_rcf_num Z3_rcf_sub (Z3_context a0, Z3_rcf_num a1, Z3_rcf_num a2) inline static
Definition at line 5845 of file Native.cs.
{
             Z3_rcf_num r = LIB.Z3_rcf_sub(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_read_interpolation_problem (Z3_context a0, [In, Out] ref uint a1, [Out] out Z3_ast[] a2, [Out] out uint[] a3, string a4, out IntPtr a5, [In, Out] ref uint a6, [Out] out Z3_ast[] a7) inline static
Definition at line 6001 of file Native.cs.
Referenced by InterpolationContext.ReadInterpolationProblem().
{
             int r = LIB.Z3_read_interpolation_problem(a0, ref a1, out a2, out a3, a4, out a5, ref a6, out a7);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_reset_memory () inline static
Definition at line 4215 of file Native.cs.
{
             LIB.Z3_reset_memory();
         }
static void Z3_set_ast_print_mode (Z3_context a0, uint a1) inline static
Definition at line 4021 of file Native.cs.
{
             LIB.Z3_set_ast_print_mode(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_set_error (Z3_context a0, uint a1) inline static
Definition at line 4183 of file Native.cs.
{
             LIB.Z3_set_error(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_set_error_handler (Z3_context a0, Z3_error_handler a1) inline static
Definition at line 1872 of file Native.cs.
{
             LIB.Z3_set_error_handler(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_set_logic (Z3_context a0, string a1) inline static
Definition at line 5313 of file Native.cs.
{
             LIB.Z3_set_logic(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_set_param_value (Z3_config a0, string a1, string a2) inline static
Definition at line 1901 of file Native.cs.
Referenced by Context.Context().
{
             LIB.Z3_set_param_value(a0, a1, a2);
         }
static Z3_ast Z3_simplify (Z3_context a0, Z3_ast a1) inline static
Definition at line 3746 of file Native.cs.
Referenced by Expr.Simplify().
{
             Z3_ast r = LIB.Z3_simplify(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_simplify_ex (Z3_context a0, Z3_ast a1, Z3_params a2) inline static
Definition at line 3754 of file Native.cs.
Referenced by Expr.Simplify().
{
             Z3_ast r = LIB.Z3_simplify_ex(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_simplify_get_help (Z3_context a0) inline static
Definition at line 3762 of file Native.cs.
Referenced by Context.SimplifyHelp().
{
             IntPtr r = LIB.Z3_simplify_get_help(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static Z3_param_descrs Z3_simplify_get_param_descrs (Z3_context a0) inline static
Definition at line 3770 of file Native.cs.
{
             Z3_param_descrs r = LIB.Z3_simplify_get_param_descrs(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_soft_check_cancel (Z3_context a0) inline static
Definition at line 5395 of file Native.cs.
{
             LIB.Z3_soft_check_cancel(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_solver_assert (Z3_context a0, Z3_solver a1, Z3_ast a2) inline static
Definition at line 5149 of file Native.cs.
Referenced by Solver.Assert().
{
             LIB.Z3_solver_assert(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_solver_assert_and_track (Z3_context a0, Z3_solver a1, Z3_ast a2, Z3_ast a3) inline static
Definition at line 5156 of file Native.cs.
Referenced by Solver.AssertAndTrack().
{
             LIB.Z3_solver_assert_and_track(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static int Z3_solver_check (Z3_context a0, Z3_solver a1) inline static
Definition at line 5171 of file Native.cs.
Referenced by Solver.Check().
{
             int r = LIB.Z3_solver_check(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_solver_check_assumptions (Z3_context a0, Z3_solver a1, uint a2, [In] Z3_ast[] a3) inline static
Definition at line 5179 of file Native.cs.
Referenced by Solver.Check().
{
             int r = LIB.Z3_solver_check_assumptions(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_solver_dec_ref (Z3_context a0, Z3_solver a1) inline static
Definition at line 5113 of file Native.cs.
{
             LIB.Z3_solver_dec_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static Z3_ast_vector Z3_solver_get_assertions (Z3_context a0, Z3_solver a1) inline static
Definition at line 5163 of file Native.cs.
{
             Z3_ast_vector r = LIB.Z3_solver_get_assertions(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_solver_get_help (Z3_context a0, Z3_solver a1) inline static
Definition at line 5083 of file Native.cs.
{
             IntPtr r = LIB.Z3_solver_get_help(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static Z3_model Z3_solver_get_model (Z3_context a0, Z3_solver a1) inline static
Definition at line 5187 of file Native.cs.
{
             Z3_model r = LIB.Z3_solver_get_model(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_solver_get_num_scopes (Z3_context a0, Z3_solver a1) inline static
Definition at line 5141 of file Native.cs.
{
             uint r = LIB.Z3_solver_get_num_scopes(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_param_descrs Z3_solver_get_param_descrs (Z3_context a0, Z3_solver a1) inline static
Definition at line 5091 of file Native.cs.
{
             Z3_param_descrs r = LIB.Z3_solver_get_param_descrs(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_solver_get_proof (Z3_context a0, Z3_solver a1) inline static
Definition at line 5195 of file Native.cs.
{
             Z3_ast r = LIB.Z3_solver_get_proof(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_solver_get_reason_unknown (Z3_context a0, Z3_solver a1) inline static
Definition at line 5211 of file Native.cs.
{
             IntPtr r = LIB.Z3_solver_get_reason_unknown(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static Z3_stats Z3_solver_get_statistics (Z3_context a0, Z3_solver a1) inline static
Definition at line 5219 of file Native.cs.
{
             Z3_stats r = LIB.Z3_solver_get_statistics(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast_vector Z3_solver_get_unsat_core (Z3_context a0, Z3_solver a1) inline static
Definition at line 5203 of file Native.cs.
{
             Z3_ast_vector r = LIB.Z3_solver_get_unsat_core(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_solver_inc_ref (Z3_context a0, Z3_solver a1) inline static
Definition at line 5106 of file Native.cs.
{
             LIB.Z3_solver_inc_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_solver_pop (Z3_context a0, Z3_solver a1, uint a2) inline static
Definition at line 5127 of file Native.cs.
Referenced by Solver.Pop().
{
             LIB.Z3_solver_pop(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_solver_push (Z3_context a0, Z3_solver a1) inline static
Definition at line 5120 of file Native.cs.
Referenced by Solver.Push().
{
             LIB.Z3_solver_push(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_solver_reset (Z3_context a0, Z3_solver a1) inline static
Definition at line 5134 of file Native.cs.
Referenced by Solver.Reset().
{
             LIB.Z3_solver_reset(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static void Z3_solver_set_params (Z3_context a0, Z3_solver a1, Z3_params a2) inline static
Definition at line 5099 of file Native.cs.
{
             LIB.Z3_solver_set_params(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static string Z3_solver_to_string (Z3_context a0, Z3_solver a1) inline static
Definition at line 5227 of file Native.cs.
Referenced by Solver.ToString().
{
             IntPtr r = LIB.Z3_solver_to_string(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static Z3_ast Z3_sort_to_ast (Z3_context a0, Z3_sort a1) inline static
Definition at line 3138 of file Native.cs.
{
             Z3_ast r = LIB.Z3_sort_to_ast(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_sort_to_string (Z3_context a0, Z3_sort a1) inline static
Definition at line 4044 of file Native.cs.
Referenced by Sort.ToString().
{
             IntPtr r = LIB.Z3_sort_to_string(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static string Z3_statistics_to_string (Z3_context a0) inline static
Definition at line 5606 of file Native.cs.
{
             IntPtr r = LIB.Z3_statistics_to_string(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static void Z3_stats_dec_ref (Z3_context a0, Z3_stats a1) inline static
Definition at line 5250 of file Native.cs.
{
             LIB.Z3_stats_dec_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static double Z3_stats_get_double_value (Z3_context a0, Z3_stats a1, uint a2) inline static
Definition at line 5297 of file Native.cs.
{
             double r = LIB.Z3_stats_get_double_value(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_stats_get_key (Z3_context a0, Z3_stats a1, uint a2) inline static
Definition at line 5265 of file Native.cs.
{
             IntPtr r = LIB.Z3_stats_get_key(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static uint Z3_stats_get_uint_value (Z3_context a0, Z3_stats a1, uint a2) inline static
Definition at line 5289 of file Native.cs.
{
             uint r = LIB.Z3_stats_get_uint_value(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_stats_inc_ref (Z3_context a0, Z3_stats a1) inline static
Definition at line 5243 of file Native.cs.
{
             LIB.Z3_stats_inc_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static int Z3_stats_is_double (Z3_context a0, Z3_stats a1, uint a2) inline static
Definition at line 5281 of file Native.cs.
{
             int r = LIB.Z3_stats_is_double(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static int Z3_stats_is_uint (Z3_context a0, Z3_stats a1, uint a2) inline static
Definition at line 5273 of file Native.cs.
{
             int r = LIB.Z3_stats_is_uint(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static uint Z3_stats_size (Z3_context a0, Z3_stats a1) inline static
Definition at line 5257 of file Native.cs.
{
             uint r = LIB.Z3_stats_size(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_stats_to_string (Z3_context a0, Z3_stats a1) inline static
Definition at line 5235 of file Native.cs.
Referenced by Statistics.ToString().
{
             IntPtr r = LIB.Z3_stats_to_string(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static Z3_ast Z3_substitute (Z3_context a0, Z3_ast a1, uint a2, [In] Z3_ast[] a3, [In] Z3_ast[] a4) inline static
Definition at line 3786 of file Native.cs.
Referenced by Expr.Substitute().
{
             Z3_ast r = LIB.Z3_substitute(a0, a1, a2, a3, a4);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_ast Z3_substitute_vars (Z3_context a0, Z3_ast a1, uint a2, [In] Z3_ast[] a3) inline static
Definition at line 3794 of file Native.cs.
Referenced by Expr.SubstituteVars().
{
             Z3_ast r = LIB.Z3_substitute_vars(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_tactic Z3_tactic_and_then (Z3_context a0, Z3_tactic a1, Z3_tactic a2) inline static
Definition at line 4741 of file Native.cs.
Referenced by Context.AndThen().
{
             Z3_tactic r = LIB.Z3_tactic_and_then(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_apply_result Z3_tactic_apply (Z3_context a0, Z3_tactic a1, Z3_goal a2) inline static
Definition at line 4989 of file Native.cs.
Referenced by Tactic.Apply().
{
             Z3_apply_result r = LIB.Z3_tactic_apply(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_apply_result Z3_tactic_apply_ex (Z3_context a0, Z3_tactic a1, Z3_goal a2, Z3_params a3) inline static
Definition at line 4997 of file Native.cs.
Referenced by Tactic.Apply().
{
             Z3_apply_result r = LIB.Z3_tactic_apply_ex(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_tactic Z3_tactic_cond (Z3_context a0, Z3_probe a1, Z3_tactic a2, Z3_tactic a3) inline static
Definition at line 4789 of file Native.cs.
Referenced by Context.Cond().
{
             Z3_tactic r = LIB.Z3_tactic_cond(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_tactic_dec_ref (Z3_context a0, Z3_tactic a1) inline static
Definition at line 4712 of file Native.cs.
{
             LIB.Z3_tactic_dec_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static Z3_tactic Z3_tactic_fail (Z3_context a0) inline static
Definition at line 4813 of file Native.cs.
Referenced by Context.Fail().
{
             Z3_tactic r = LIB.Z3_tactic_fail(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_tactic Z3_tactic_fail_if (Z3_context a0, Z3_probe a1) inline static
Definition at line 4821 of file Native.cs.
Referenced by Context.FailIf().
{
             Z3_tactic r = LIB.Z3_tactic_fail_if(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_tactic Z3_tactic_fail_if_not_decided (Z3_context a0) inline static
Definition at line 4829 of file Native.cs.
Referenced by Context.FailIfNotDecided().
{
             Z3_tactic r = LIB.Z3_tactic_fail_if_not_decided(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static string Z3_tactic_get_descr (Z3_context a0, string a1) inline static
Definition at line 4965 of file Native.cs.
Referenced by Context.TacticDescription().
{
             IntPtr r = LIB.Z3_tactic_get_descr(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static string Z3_tactic_get_help (Z3_context a0, Z3_tactic a1) inline static
Definition at line 4949 of file Native.cs.
{
             IntPtr r = LIB.Z3_tactic_get_help(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return Marshal.PtrToStringAnsi(r);
         }
static Z3_param_descrs Z3_tactic_get_param_descrs (Z3_context a0, Z3_tactic a1) inline static
Definition at line 4957 of file Native.cs.
{
             Z3_param_descrs r = LIB.Z3_tactic_get_param_descrs(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_tactic_inc_ref (Z3_context a0, Z3_tactic a1) inline static
Definition at line 4705 of file Native.cs.
{
             LIB.Z3_tactic_inc_ref(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static Z3_tactic Z3_tactic_or_else (Z3_context a0, Z3_tactic a1, Z3_tactic a2) inline static
Definition at line 4749 of file Native.cs.
Referenced by Context.OrElse().
{
             Z3_tactic r = LIB.Z3_tactic_or_else(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_tactic Z3_tactic_par_and_then (Z3_context a0, Z3_tactic a1, Z3_tactic a2) inline static
Definition at line 4765 of file Native.cs.
Referenced by Context.ParAndThen().
{
             Z3_tactic r = LIB.Z3_tactic_par_and_then(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_tactic Z3_tactic_par_or (Z3_context a0, uint a1, [In] Z3_tactic[] a2) inline static
Definition at line 4757 of file Native.cs.
Referenced by Context.ParOr().
{
             Z3_tactic r = LIB.Z3_tactic_par_or(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_tactic Z3_tactic_repeat (Z3_context a0, Z3_tactic a1, uint a2) inline static
Definition at line 4797 of file Native.cs.
Referenced by Context.Repeat().
{
             Z3_tactic r = LIB.Z3_tactic_repeat(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_tactic Z3_tactic_skip (Z3_context a0) inline static
Definition at line 4805 of file Native.cs.
Referenced by Context.Skip().
{
             Z3_tactic r = LIB.Z3_tactic_skip(a0);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_tactic Z3_tactic_try_for (Z3_context a0, Z3_tactic a1, uint a2) inline static
Definition at line 4773 of file Native.cs.
Referenced by Context.TryFor().
{
             Z3_tactic r = LIB.Z3_tactic_try_for(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_tactic Z3_tactic_using_params (Z3_context a0, Z3_tactic a1, Z3_params a2) inline static
Definition at line 4837 of file Native.cs.
Referenced by Context.UsingParams().
{
             Z3_tactic r = LIB.Z3_tactic_using_params(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_tactic Z3_tactic_when (Z3_context a0, Z3_probe a1, Z3_tactic a2) inline static
Definition at line 4781 of file Native.cs.
Referenced by Context.When().
{
             Z3_tactic r = LIB.Z3_tactic_when(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_app Z3_to_app (Z3_context a0, Z3_ast a1) inline static
Definition at line 3522 of file Native.cs.
{
             Z3_app r = LIB.Z3_to_app(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static Z3_func_decl Z3_to_func_decl (Z3_context a0, Z3_ast a1) inline static
Definition at line 3530 of file Native.cs.
{
             Z3_func_decl r = LIB.Z3_to_func_decl(a0, a1);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_toggle_warning_messages (int a0) inline static
Definition at line 4017 of file Native.cs.
{
             LIB.Z3_toggle_warning_messages(a0);
         }
static Z3_ast Z3_translate (Z3_context a0, Z3_ast a1, Z3_context a2) inline static
Definition at line 3802 of file Native.cs.
Referenced by AST.Translate(), and Expr.Translate().
{
             Z3_ast r = LIB.Z3_translate(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_update_param_value (Z3_context a0, string a1, string a2) inline static
Definition at line 1937 of file Native.cs.
{
             LIB.Z3_update_param_value(a0, a1, a2);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }
static Z3_ast Z3_update_term (Z3_context a0, Z3_ast a1, uint a2, [In] Z3_ast[] a3) inline static
Definition at line 3778 of file Native.cs.
Referenced by Expr.Update().
{
             Z3_ast r = LIB.Z3_update_term(a0, a1, a2, a3);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
             return r;
         }
static void Z3_write_interpolation_problem (Z3_context a0, uint a1, [In] Z3_ast[] a2, [In] uint[] a3, string a4, uint a5, [In] Z3_ast[] a6) inline static
Definition at line 6017 of file Native.cs.
Referenced by InterpolationContext.WriteInterpolationProblem().
{
             LIB.Z3_write_interpolation_problem(a0, a1, a2, a3, a4, a5, a6);
             Z3_error_code err = (Z3_error_code)LIB.Z3_get_error_code(a0);
             if (err != Z3_error_code.Z3_OK)
                 throw new Z3Exception(Marshal.PtrToStringAnsi(LIB.Z3_get_error_msg_ex(a0, (uint)err)));
         }