Z3: user_propagator_base Class Reference
user_propagator_base Class Reference abstract
Public Member Functions
user_propagator_base (context &c)
user_propagator_base (solver *s)
virtual void push ()=0
virtual void pop (unsigned num_scopes)=0
virtual ~user_propagator_base ()
context & ctx ()
virtual user_propagator_base * fresh (context &ctx)=0
user_propagators created using fresh() are created during search and their lifetimes are restricted to search time. They should be garbage collected by the propagator used to invoke fresh(). The life-time of the Z3_context object can only be assumed valid during callbacks, such as fixed(), which contains expressions based on the context.
void register_fixed (fixed_eh_t &f)
register callbacks. Callbacks can only be registered with user_propagators that were created using a solver.
void register_fixed ()
void register_eq (eq_eh_t &f)
void register_eq ()
void register_final (final_eh_t &f)
register a callback on final-check. During the final check stage, all propagations have been processed. This is an opportunity for the user-propagator to delay some analysis that could be expensive to perform incrementally. It is also an opportunity for the propagator to implement branch and bound optimization.
void register_final ()
void register_created (created_eh_t &c)
void register_created ()
void register_decide (decide_eh_t &c)
void register_decide ()
virtual void fixed (expr const &, expr const &)
virtual void eq (expr const &, expr const &)
virtual void final ()
virtual void created (expr const &)
virtual void decide (expr const &, unsigned, bool)
bool next_split (expr const &e, unsigned idx, Z3_lbool phase)
void add (expr const &e)
tracks e by a unique identifier that is returned by the call.
void conflict (expr_vector const &fixed)
void conflict (expr_vector const &fixed, expr_vector const &lhs, expr_vector const &rhs)
bool propagate (expr_vector const &fixed, expr const &conseq)
bool propagate (expr_vector const &fixed, expr_vector const &lhs, expr_vector const &rhs, expr const &conseq)
Detailed Description
Definition at line 4291 of file z3++.h.
Constructor & Destructor Documentation
user_propagator_base() [1/2]
user_propagator_base (context & c) inline
Definition at line 4374 of file z3++.h.
 : s(nullptr), c(&c) {}
user_propagator_base() [2/2]
user_propagator_base (solver * s) inline
Definition at line 4376 of file z3++.h.
                                        : s(s), c(nullptr) {
             Z3_solver_propagate_init(ctx(), *s, this, push_eh, pop_eh, fresh_eh);
         }
~user_propagator_base()
virtual ~user_propagator_base () inline virtual
Definition at line 4383 of file z3++.h.
{
             for (auto& subcontext : subcontexts) {
                 subcontext->detach(); // detach first; the subcontexts will be freed internally!
                 delete subcontext;
             }
         }
Member Function Documentation
add()
void add (expr const & e) inline
tracks e by a unique identifier that is returned by the call.
If the fixed() callback is registered and if e is a Boolean or Bit-vector, the fixed() callback gets invoked when e is bound to a value. If the eq() callback is registered, then equalities between registered expressions are reported. A consumer can use the propagate or conflict functions to invoke propagations or conflicts as a consequence of these callbacks. These functions take a list of identifiers for registered expressions that have been fixed. The list of identifiers must correspond to already fixed values. Similarly, a list of propagated equalities can be supplied. These must correspond to equalities that have been registered during a callback.
Definition at line 4527 of file z3++.h.
{
             if (cb)
                 Z3_solver_propagate_register_cb(ctx(), cb, e);
             else if (s)
                 Z3_solver_propagate_register(ctx(), *s, e);
             else
                 assert(false);
         }
Referenced by Solver::__iadd__(), Fixedpoint::__iadd__(), and Optimize::__iadd__().
conflict() [1/2]
void conflict (expr_vector const & fixed) inline
Definition at line 4536 of file z3++.h.
{
             assert(cb);
             expr conseq = ctx().bool_val(false);
             array<Z3_ast> _fixed(fixed);
             Z3_solver_propagate_consequence(ctx(), cb, fixed.size(), _fixed.ptr(), 0, nullptr, nullptr, conseq);
         }
conflict() [2/2]
void conflict (expr_vector const & fixed, expr_vector const & lhs, expr_vector const & rhs) inline
Definition at line 4543 of file z3++.h.
{
             assert(cb);
             assert(lhs.size() == rhs.size());
             expr conseq = ctx().bool_val(false);
             array<Z3_ast> _fixed(fixed);
             array<Z3_ast> _lhs(lhs);
             array<Z3_ast> _rhs(rhs);
             Z3_solver_propagate_consequence(ctx(), cb, fixed.size(), _fixed.ptr(), lhs.size(), _lhs.ptr(), _rhs.ptr(), conseq);
         }
created()
virtual void created (expr const &) inline virtual
Definition at line 4504 of file z3++.h.
 {}
Referenced by UserPropagateBase::add_created(), and user_propagator_base::register_created().
ctx()
context& ctx () inline
Definition at line 4390 of file z3++.h.
{
             return c ? *c : s->ctx();
         }
Referenced by ArithRef::__add__(), BitVecRef::__add__(), FPRef::__add__(), BitVecRef::__and__(), FuncDeclRef::__call__(), Probe::__call__(), AstMap::__contains__(), AstRef::__copy__(), Goal::__copy__(), AstVector::__copy__(), FuncInterp::__copy__(), ModelRef::__copy__(), Solver::__copy__(), AstRef::__deepcopy__(), Datatype::__deepcopy__(), ParamsRef::__deepcopy__(), ParamDescrsRef::__deepcopy__(), Goal::__deepcopy__(), AstVector::__deepcopy__(), AstMap::__deepcopy__(), FuncEntry::__deepcopy__(), FuncInterp::__deepcopy__(), ModelRef::__deepcopy__(), Statistics::__deepcopy__(), Solver::__deepcopy__(), Fixedpoint::__deepcopy__(), Optimize::__deepcopy__(), ApplyResult::__deepcopy__(), Simplifier::__deepcopy__(), Tactic::__deepcopy__(), Probe::__deepcopy__(), Context::__del__(), AstRef::__del__(), ScopedConstructor::__del__(), ScopedConstructorList::__del__(), ParamsRef::__del__(), ParamDescrsRef::__del__(), Goal::__del__(), AstVector::__del__(), AstMap::__del__(), FuncEntry::__del__(), FuncInterp::__del__(), ModelRef::__del__(), Statistics::__del__(), Solver::__del__(), Fixedpoint::__del__(), Optimize::__del__(), ApplyResult::__del__(), Simplifier::__del__(), Tactic::__del__(), Probe::__del__(), ParserContext::__del__(), ArithRef::__div__(), BitVecRef::__div__(), FPRef::__div__(), ExprRef::__eq__(), Probe::__eq__(), ArithRef::__ge__(), BitVecRef::__ge__(), Probe::__ge__(), FPRef::__ge__(), SeqRef::__ge__(), AstVector::__getitem__(), SeqRef::__getitem__(), ModelRef::__getitem__(), Statistics::__getitem__(), ApplyResult::__getitem__(), AstMap::__getitem__(), ArithRef::__gt__(), BitVecRef::__gt__(), Probe::__gt__(), FPRef::__gt__(), SeqRef::__gt__(), BitVecRef::__invert__(), ArithRef::__le__(), BitVecRef::__le__(), Probe::__le__(), FPRef::__le__(), SeqRef::__le__(), CharRef::__le__(), AstVector::__len__(), AstMap::__len__(), ModelRef::__len__(), Statistics::__len__(), ApplyResult::__len__(), BitVecRef::__lshift__(), ArithRef::__lt__(), BitVecRef::__lt__(), Probe::__lt__(), FPRef::__lt__(), SeqRef::__lt__(), ArithRef::__mod__(), BitVecRef::__mod__(), BoolRef::__mul__(), ArithRef::__mul__(), BitVecRef::__mul__(), FPRef::__mul__(), ExprRef::__ne__(), Probe::__ne__(), ArithRef::__neg__(), BitVecRef::__neg__(), BitVecRef::__or__(), ArithRef::__pow__(), ArithRef::__radd__(), BitVecRef::__radd__(), FPRef::__radd__(), BitVecRef::__rand__(), ArithRef::__rdiv__(), BitVecRef::__rdiv__(), FPRef::__rdiv__(), ParamsRef::__repr__(), ParamDescrsRef::__repr__(), AstMap::__repr__(), Statistics::__repr__(), BitVecRef::__rlshift__(), ArithRef::__rmod__(), BitVecRef::__rmod__(), ArithRef::__rmul__(), BitVecRef::__rmul__(), FPRef::__rmul__(), BitVecRef::__ror__(), ArithRef::__rpow__(), BitVecRef::__rrshift__(), BitVecRef::__rshift__(), ArithRef::__rsub__(), BitVecRef::__rsub__(), FPRef::__rsub__(), BitVecRef::__rxor__(), AstVector::__setitem__(), AstMap::__setitem__(), ArithRef::__sub__(), BitVecRef::__sub__(), FPRef::__sub__(), BitVecRef::__xor__(), DatatypeSortRef::accessor(), user_propagator_base::add(), Simplifier::add(), Fixedpoint::add_cover(), ParserContext::add_decl(), Fixedpoint::add_rule(), Optimize::add_soft(), ParserContext::add_sort(), Tactic::apply(), AlgebraicNumRef::approx(), ExprRef::arg(), FuncEntry::arg_value(), FuncInterp::arity(), Goal::as_expr(), ApplyResult::as_expr(), FPNumRef::as_string(), Solver::assert_and_track(), Optimize::assert_and_track(), Goal::assert_exprs(), Solver::assert_exprs(), Fixedpoint::assert_exprs(), Optimize::assert_exprs(), Solver::assertions(), Optimize::assertions(), SeqRef::at(), SeqSortRef::basis(), ReSortRef::basis(), QuantifierRef::body(), BoolSortRef::cast(), Solver::check(), Optimize::check(), user_propagator_base::conflict(), UserPropagateBase::conflict(), Solver::consequences(), DatatypeSortRef::constructor(), Goal::convert_model(), AstRef::ctx_ref(), UserPropagateBase::ctx_ref(), ExprRef::decl(), ModelRef::decls(), ArrayRef::default(), RatNumRef::denominator(), Goal::depth(), Goal::dimacs(), Solver::dimacs(), ArraySortRef::domain(), FuncDeclRef::domain(), ArraySortRef::domain_n(), FuncInterp::else_value(), FuncInterp::entry(), AstMap::erase(), ModelRef::eval(), FPNumRef::exponent(), FPNumRef::exponent_as_bv(), FPNumRef::exponent_as_long(), Solver::from_file(), Optimize::from_file(), Solver::from_string(), Optimize::from_string(), ParserContext::from_string(), Goal::get(), Fixedpoint::get_answer(), Fixedpoint::get_assertions(), Fixedpoint::get_cover_delta(), ParamDescrsRef::get_documentation(), Fixedpoint::get_ground_sat_answer(), ModelRef::get_interp(), Statistics::get_key_value(), ParamDescrsRef::get_kind(), ParamDescrsRef::get_name(), Fixedpoint::get_num_levels(), Fixedpoint::get_rule_names_along_trace(), Fixedpoint::get_rules(), Fixedpoint::get_rules_along_trace(), ModelRef::get_sort(), ModelRef::get_universe(), Solver::help(), Fixedpoint::help(), Optimize::help(), Simplifier::help(), Tactic::help(), Solver::import_model_converter(), Goal::inconsistent(), Solver::interrupt(), CharRef::is_digit(), FPNumRef::isInf(), FPNumRef::isNaN(), FPNumRef::isNegative(), FPNumRef::isNormal(), FPNumRef::isPositive(), FPNumRef::isSubnormal(), FPNumRef::isZero(), AstMap::keys(), Statistics::keys(), SortRef::kind(), Optimize::maximize(), Optimize::minimize(), Solver::model(), Optimize::model(), SortRef::name(), FuncDeclRef::name(), Solver::next(), user_propagator_base::next_split(), QuantifierRef::no_pattern(), Solver::non_units(), FuncEntry::num_args(), FuncInterp::num_entries(), Solver::num_scopes(), ModelRef::num_sorts(), RatNumRef::numerator(), Optimize::objectives(), Solver::param_descrs(), Fixedpoint::param_descrs(), Optimize::param_descrs(), Simplifier::param_descrs(), Tactic::param_descrs(), FuncDeclRef::params(), Fixedpoint::parse_file(), Fixedpoint::parse_string(), QuantifierRef::pattern(), AlgebraicNumRef::poly(), Optimize::pop(), Solver::pop(), Goal::prec(), Solver::proof(), user_propagator_base::propagate(), Solver::push(), Optimize::push(), AstVector::push(), QuantifierRef::qid(), Fixedpoint::query(), Fixedpoint::query_from_lvl(), FuncDeclRef::range(), ArraySortRef::range(), Solver::reason_unknown(), Fixedpoint::reason_unknown(), Optimize::reason_unknown(), DatatypeSortRef::recognizer(), Context::ref(), user_propagator_base::register_created(), user_propagator_base::register_decide(), user_propagator_base::register_eq(), user_propagator_base::register_final(), user_propagator_base::register_fixed(), Fixedpoint::register_relation(), AstMap::reset(), Solver::reset(), AstVector::resize(), Solver::root(), Solver::set(), Fixedpoint::set(), Optimize::set(), ParamsRef::set(), Solver::set_initial_value(), Optimize::set_initial_value(), Optimize::set_on_model(), Fixedpoint::set_predicate_representation(), Goal::sexpr(), AstVector::sexpr(), ModelRef::sexpr(), Solver::sexpr(), Fixedpoint::sexpr(), Optimize::sexpr(), ApplyResult::sexpr(), FPNumRef::sign(), FPNumRef::sign_as_bv(), FPNumRef::significand(), FPNumRef::significand_as_bv(), FPNumRef::significand_as_long(), ParamDescrsRef::size(), Goal::size(), QuantifierRef::skolem_id(), Tactic::solver(), ExprRef::sort(), BoolRef::sort(), QuantifierRef::sort(), ArithRef::sort(), BitVecRef::sort(), ArrayRef::sort(), DatatypeRef::sort(), FiniteDomainRef::sort(), FPRef::sort(), SeqRef::sort(), Solver::statistics(), Fixedpoint::statistics(), Optimize::statistics(), CharRef::to_bv(), CharRef::to_int(), Solver::to_smt2(), Fixedpoint::to_string(), Solver::trail(), Solver::trail_levels(), AstVector::translate(), FuncInterp::translate(), AstRef::translate(), Goal::translate(), ModelRef::translate(), Solver::translate(), Solver::units(), Solver::unsat_core(), Optimize::unsat_core(), Fixedpoint::update_rule(), user_propagator_base::user_propagator_base(), Simplifier::using_params(), ParamsRef::validate(), FuncEntry::value(), QuantifierRef::var_name(), and QuantifierRef::var_sort().
decide()
virtual void decide (expr const & , unsigned , bool) inline virtual
Definition at line 4506 of file z3++.h.
 {}
Referenced by UserPropagateBase::add_decide(), and user_propagator_base::register_decide().
eq()
virtual void eq (expr const & , expr const &) inline virtual
Definition at line 4500 of file z3++.h.
 { }
Referenced by AstRef::__eq__(), UserPropagateBase::add_eq(), SortRef::cast(), BoolSortRef::cast(), and user_propagator_base::register_eq().
final()
virtual void final () inline virtual
Definition at line 4502 of file z3++.h.
 { }
Referenced by UserPropagateBase::add_final().
fixed()
virtual void fixed (expr const & , expr const &) inline virtual
Definition at line 4498 of file z3++.h.
 { }
Referenced by UserPropagateBase::add_fixed(), user_propagator_base::conflict(), user_propagator_base::propagate(), and user_propagator_base::register_fixed().
fresh()
virtual user_propagator_base* fresh (context & ctx) pure virtual
user_propagators created using fresh() are created during search and their lifetimes are restricted to search time. They should be garbage collected by the propagator used to invoke fresh(). The life-time of the Z3_context object can only be assumed valid during callbacks, such as fixed(), which contains expressions based on the context.
next_split()
bool next_split (expr const & e, unsigned idx, Z3_lbool phase) inline
Definition at line 4508 of file z3++.h.
{
             assert(cb);
             return Z3_solver_next_split(ctx(), cb, e, idx, phase);
         }
pop()
virtual void pop (unsigned num_scopes) pure virtual
Referenced by Solver::__exit__().
propagate() [1/2]
bool propagate (expr_vector const & fixed, expr const & conseq) inline
Definition at line 4553 of file z3++.h.
{
             assert(cb);
             assert((Z3_context)conseq.ctx() == (Z3_context)ctx());
             array<Z3_ast> _fixed(fixed);
             return Z3_solver_propagate_consequence(ctx(), cb, _fixed.size(), _fixed.ptr(), 0, nullptr, nullptr, conseq);
         }
Referenced by UserPropagateBase::conflict().
propagate() [2/2]
bool propagate (expr_vector const & fixed, expr_vector const & lhs, expr_vector const & rhs, expr const & conseq) inline
Definition at line 4560 of file z3++.h.
{
             assert(cb);
             assert((Z3_context)conseq.ctx() == (Z3_context)ctx());
             assert(lhs.size() == rhs.size());
             array<Z3_ast> _fixed(fixed);
             array<Z3_ast> _lhs(lhs);
             array<Z3_ast> _rhs(rhs);
             return Z3_solver_propagate_consequence(ctx(), cb, _fixed.size(), _fixed.ptr(), lhs.size(), _lhs.ptr(), _rhs.ptr(), conseq);
         }
Referenced by UserPropagateBase::conflict().
push()
virtual void push () pure virtual
Referenced by Solver::__enter__().
register_created() [1/2]
void register_created () inline
Definition at line 4473 of file z3++.h.
{
             m_created_eh = [this](expr const& e) {
                 created(e);
             };
             if (s) {
                 Z3_solver_propagate_created(ctx(), *s, created_eh);
             }
         }
register_created() [2/2]
void register_created (created_eh_t & c) inline
Definition at line 4466 of file z3++.h.
{
             m_created_eh = c;
             if (s) {
                 Z3_solver_propagate_created(ctx(), *s, created_eh);
             }
         }
register_decide() [1/2]
void register_decide () inline
Definition at line 4489 of file z3++.h.
{
             m_decide_eh = [this](expr val, unsigned bit, bool is_pos) {
                 decide(val, bit, is_pos);
             };
             if (s) {
                 Z3_solver_propagate_decide(ctx(), *s, decide_eh);
             }
         }
register_decide() [2/2]
void register_decide (decide_eh_t & c) inline
Definition at line 4482 of file z3++.h.
{
             m_decide_eh = c;
             if (s) {
                 Z3_solver_propagate_decide(ctx(), *s, decide_eh);
             }
         }
register_eq() [1/2]
void register_eq () inline
Definition at line 4433 of file z3++.h.
{
             m_eq_eh = [this](expr const& x, expr const& y) {
                 eq(x, y);
             };
             if (s) {
                 Z3_solver_propagate_eq(ctx(), *s, eq_eh);
             }
         }
register_eq() [2/2]
void register_eq (eq_eh_t & f) inline
Definition at line 4426 of file z3++.h.
{
             m_eq_eh = f;
             if (s) {
                 Z3_solver_propagate_eq(ctx(), *s, eq_eh);
             }
         }
register_final() [1/2]
void register_final () inline
Definition at line 4457 of file z3++.h.
{
             m_final_eh = [this]() {
                 final();
             };
             if (s) {
                 Z3_solver_propagate_final(ctx(), *s, final_eh);
             }
         }
register_final() [2/2]
void register_final (final_eh_t & f) inline
register a callback on final-check. During the final check stage, all propagations have been processed. This is an opportunity for the user-propagator to delay some analysis that could be expensive to perform incrementally. It is also an opportunity for the propagator to implement branch and bound optimization.
Definition at line 4450 of file z3++.h.
{
             m_final_eh = f;
             if (s) {
                 Z3_solver_propagate_final(ctx(), *s, final_eh);
             }
         }
register_fixed() [1/2]
void register_fixed () inline
Definition at line 4417 of file z3++.h.
{
             m_fixed_eh = [this](expr const &id, expr const &e) {
                 fixed(id, e);
             };
             if (s) {
                 Z3_solver_propagate_fixed(ctx(), *s, fixed_eh);
             }
         }
register_fixed() [2/2]
void register_fixed (fixed_eh_t & f) inline
register callbacks. Callbacks can only be registered with user_propagators that were created using a solver.
Definition at line 4410 of file z3++.h.
{
             m_fixed_eh = f;
             if (s) {
                 Z3_solver_propagate_fixed(ctx(), *s, fixed_eh);
             }
         }