Z3: RatNumRef Class Reference
RatNumRef Class Reference
Public Member Functions
def numerator (self)
def denominator (self)
def numerator_as_long (self)
def denominator_as_long (self)
def is_int (self)
def is_real (self)
def is_int_value (self)
def as_long (self)
def as_decimal (self, prec)
def as_string (self)
def as_fraction (self)
Public Member Functions inherited from ArithRef
def sort (self)
def __add__ (self, other)
def __radd__ (self, other)
def __mul__ (self, other)
def __rmul__ (self, other)
def __sub__ (self, other)
def __rsub__ (self, other)
def __pow__ (self, other)
def __rpow__ (self, other)
def __div__ (self, other)
def __truediv__ (self, other)
def __rdiv__ (self, other)
def __rtruediv__ (self, other)
def __mod__ (self, other)
def __rmod__ (self, other)
def __neg__ (self)
def __pos__ (self)
def __le__ (self, other)
def __lt__ (self, other)
def __gt__ (self, other)
def __ge__ (self, other)
Public Member Functions inherited from ExprRef
def as_ast (self)
def get_id (self)
def sort_kind (self)
def __eq__ (self, other)
def __hash__ (self)
def __ne__ (self, other)
def params (self)
def decl (self)
def num_args (self)
def arg (self, idx)
def children (self)
Public Member Functions inherited from AstRef
def __init__ (self, ast, ctx=None)
def __del__ (self)
def __deepcopy__ (self, memo={})
def __str__ (self)
def __repr__ (self)
def __nonzero__ (self)
def __bool__ (self)
def sexpr (self)
def ctx_ref (self)
def eq (self, other)
def translate (self, target)
def __copy__ (self)
def hash (self)
Public Member Functions inherited from Z3PPObject
def use_pp (self)
Additional Inherited Members
Data Fields inherited from AstRef
ast
ctx
Detailed Description
Rational values.
Definition at line 2803 of file z3py.py.
Member Function Documentation
as_decimal()
def as_decimal (self, prec)
Return a Z3 rational value as a string in decimal notation using at most `prec` decimal places.
>>> v = RealVal("1/5")
>>> v.as_decimal(3)
'0.2'
>>> v = RealVal("1/3")
>>> v.as_decimal(3)
'0.333?'
Definition at line 2869 of file z3py.py.
     def as_decimal(self, prec):
         """ Return a Z3 rational value as a string in decimal notation using at most `prec` decimal places.
         >>> v = RealVal("1/5")
         >>> v.as_decimal(3)
         '0.2'
         >>> v = RealVal("1/3")
         >>> v.as_decimal(3)
         '0.333?'
         """
         return Z3_get_numeral_decimal_string(self.ctx_ref(), self.as_ast(), prec)
as_fraction()
def as_fraction (self)
Return a Z3 rational as a Python Fraction object.
>>> v = RealVal("1/5")
>>> v.as_fraction()
Fraction(1, 5)
Definition at line 2890 of file z3py.py.
     def as_fraction(self):
         """Return a Z3 rational as a Python Fraction object.
         >>> v = RealVal("1/5")
         >>> v.as_fraction()
         Fraction(1, 5)
         """
         return Fraction(self.numerator_as_long(), self.denominator_as_long())
as_long()
def as_long (self)
Definition at line 2865 of file z3py.py.
     def as_long(self):
         _z3_assert(self.is_int_value(), "Expected integer fraction")
         return self.numerator_as_long()
Referenced by BitVecNumRef.as_signed_long(), RatNumRef.denominator_as_long(), and RatNumRef.numerator_as_long().
as_string()
def as_string (self)
Return a Z3 rational numeral as a Python string.
>>> v = Q(3,6)
>>> v.as_string()
'1/2'
Definition at line 2881 of file z3py.py.
     def as_string(self):
         """Return a Z3 rational numeral as a Python string.
         >>> v = Q(3,6)
         >>> v.as_string()
         '1/2'
         """
         return Z3_get_numeral_string(self.ctx_ref(), self.as_ast())
Referenced by BitVecNumRef.as_long(), and FiniteDomainNumRef.as_long().
denominator()
def denominator (self)
Return the denominator of a Z3 rational numeral.
>>> is_rational_value(Q(3,5))
True
>>> n = Q(3,5)
>>> n.denominator()
5
Definition at line 2821 of file z3py.py.
     def denominator(self):
         """ Return the denominator of a Z3 rational numeral.
         >>> is_rational_value(Q(3,5))
         True
         >>> n = Q(3,5)
         >>> n.denominator()
         5
         """
         return IntNumRef(Z3_get_denominator(self.ctx_ref(), self.as_ast()), self.ctx)
Referenced by RatNumRef.denominator_as_long(), and RatNumRef.is_int_value().
denominator_as_long()
def denominator_as_long (self)
Return the denominator as a Python long.
>>> v = RealVal("1/3")
>>> v
1/3
>>> v.denominator_as_long()
3
Definition at line 2845 of file z3py.py.
     def denominator_as_long(self):
         """ Return the denominator as a Python long.
         >>> v = RealVal("1/3")
         >>> v
         1/3
         >>> v.denominator_as_long()
         3
         """
         return self.denominator().as_long()
Referenced by RatNumRef.as_fraction(), and RatNumRef.is_int_value().
is_int()
def is_int (self)
Return `True` if `self` is an integer expression.
>>> x = Int('x')
>>> x.is_int()
True
>>> (x + 1).is_int()
True
>>> y = Real('y')
>>> (x + y).is_int()
False
Reimplemented from ArithRef.
Definition at line 2856 of file z3py.py.
     def is_int(self):
         return False
Referenced by RatNumRef.is_int_value().
is_int_value()
def is_int_value (self)
Definition at line 2862 of file z3py.py.
     def is_int_value(self):
         return self.denominator().is_int() and self.denominator_as_long() == 1
Referenced by RatNumRef.as_long().
is_real()
def is_real (self)
Return `True` if `self` is an real expression.
>>> x = Real('x')
>>> x.is_real()
True
>>> (x + 1).is_real()
True
Reimplemented from ArithRef.
Definition at line 2859 of file z3py.py.
     def is_real(self):
         return True
numerator()
def numerator (self)
Return the numerator of a Z3 rational numeral.
>>> is_rational_value(RealVal("3/5"))
True
>>> n = RealVal("3/5")
>>> n.numerator()
3
>>> is_rational_value(Q(3,5))
True
>>> Q(3,5).numerator()
3
Definition at line 2806 of file z3py.py.
     def numerator(self):
         """ Return the numerator of a Z3 rational numeral.
         >>> is_rational_value(RealVal("3/5"))
         True
         >>> n = RealVal("3/5")
         >>> n.numerator()
         3
         >>> is_rational_value(Q(3,5))
         True
         >>> Q(3,5).numerator()
         3
         """
         return IntNumRef(Z3_get_numerator(self.ctx_ref(), self.as_ast()), self.ctx)
Referenced by RatNumRef.numerator_as_long().
numerator_as_long()
def numerator_as_long (self)
Return the numerator as a Python long.
>>> v = RealVal(10000000000)
>>> v
10000000000
>>> v + 1
10000000000 + 1
>>> v.numerator_as_long() + 1 == 10000000001
True
Definition at line 2832 of file z3py.py.
     def numerator_as_long(self):
         """ Return the numerator as a Python long.
         >>> v = RealVal(10000000000)
         >>> v
         10000000000
         >>> v + 1
         10000000000 + 1
         >>> v.numerator_as_long() + 1 == 10000000001
         True
         """
         return self.numerator().as_long()
Referenced by RatNumRef.as_fraction(), and RatNumRef.as_long().