Z3: Z3_goal_prec Enum Reference
Z3_goal_prec Enum Reference
Public Member Functions
Z3_goal_prec (int v)
final int toInt ()
Static Public Member Functions
static final Z3_goal_prec fromInt (int v)
Data Fields
Z3_GOAL_PRECISE =(0)
Z3_GOAL_UNDER =(1)
Z3_GOAL_OVER =(2)
Z3_GOAL_UNDER_OVER =(3)
Detailed Description
Z3_goal_prec
Definition at line 13 of file Z3_goal_prec.java.
Constructor & Destructor Documentation
Z3_goal_prec (int v) inline
Definition at line 21 of file Z3_goal_prec.java.
{
         this.intValue = v;
     }
Member Function Documentation
static final Z3_goal_prec fromInt (int v) inline static
Definition at line 35 of file Z3_goal_prec.java.
Referenced by Goal.getPrecision().
{
         Z3_goal_prec k = Z3_goal_prec_MappingHolder.intMapping.get(v);
         if (k != null) return k;
         throw new IllegalArgumentException("Illegal value " + v + " for Z3_goal_prec");
     }
final int toInt () inline
Definition at line 41 of file Z3_goal_prec.java.
 { return this.intValue; }
Field Documentation
Z3_GOAL_OVER =(2)
Definition at line 16 of file Z3_goal_prec.java.
Referenced by Goal.isOverApproximation().
Z3_GOAL_PRECISE =(0)
Definition at line 14 of file Z3_goal_prec.java.
Referenced by Goal.isPrecise().
Z3_GOAL_UNDER =(1)
Definition at line 15 of file Z3_goal_prec.java.
Referenced by Goal.isUnderApproximation().
Z3_GOAL_UNDER_OVER =(3)
Definition at line 17 of file Z3_goal_prec.java.
Referenced by Goal.isGarbage().