Z3: Z3_error_code Enum Reference
Z3_error_code Enum Reference
Public Member Functions
Z3_error_code (int v)
final int toInt ()
Static Public Member Functions
static final Z3_error_code fromInt (int v)
Data Fields
Z3_OK =(0)
Z3_SORT_ERROR =(1)
Z3_IOB =(2)
Z3_INVALID_ARG =(3)
Z3_PARSER_ERROR =(4)
Z3_NO_PARSER =(5)
Z3_INVALID_PATTERN =(6)
Z3_MEMOUT_FAIL =(7)
Z3_FILE_ACCESS_ERROR =(8)
Z3_INTERNAL_FATAL =(9)
Z3_INVALID_USAGE =(10)
Z3_DEC_REF_ERROR =(11)
Z3_EXCEPTION =(12)
Detailed Description
Z3_error_code
Definition at line 13 of file Z3_error_code.java.
Constructor & Destructor Documentation
Z3_error_code (int v) inline
Definition at line 30 of file Z3_error_code.java.
{
         this.intValue = v;
     }
Member Function Documentation
static final Z3_error_code fromInt (int v) inline static
Definition at line 44 of file Z3_error_code.java.
Referenced by Native.addConstInterp(), Native.addFuncInterp(), Native.algebraicAdd(), Native.algebraicDiv(), Native.algebraicEq(), Native.algebraicEval(), Native.algebraicGe(), Native.algebraicGt(), Native.algebraicIsNeg(), Native.algebraicIsPos(), Native.algebraicIsValue(), Native.algebraicIsZero(), Native.algebraicLe(), Native.algebraicLt(), Native.algebraicMul(), Native.algebraicNeq(), Native.algebraicPower(), Native.algebraicRoot(), Native.algebraicRoots(), Native.algebraicSign(), Native.algebraicSub(), Native.applyResultConvertModel(), Native.applyResultDecRef(), Native.applyResultGetNumSubgoals(), Native.applyResultGetSubgoal(), Native.applyResultIncRef(), Native.applyResultToString(), Native.appToAst(), Native.astMapContains(), Native.astMapDecRef(), Native.astMapErase(), Native.astMapFind(), Native.astMapIncRef(), Native.astMapInsert(), Native.astMapKeys(), Native.astMapReset(), Native.astMapSize(), Native.astMapToString(), Native.astToString(), Native.astVectorDecRef(), Native.astVectorGet(), Native.astVectorIncRef(), Native.astVectorPush(), Native.astVectorResize(), Native.astVectorSet(), Native.astVectorSize(), Native.astVectorToString(), Native.astVectorTranslate(), Native.benchmarkToSmtlibString(), Native.checkInterpolant(), Native.computeInterpolant(), Native.datatypeUpdateField(), Native.decRef(), Native.delConstructor(), Native.delConstructorList(), Native.fixedpointAddCover(), Native.fixedpointAddFact(), Native.fixedpointAddInvariant(), Native.fixedpointAddRule(), Native.fixedpointAssert(), Native.fixedpointDecRef(), Native.fixedpointFromFile(), Native.fixedpointFromString(), Native.fixedpointGetAnswer(), Native.fixedpointGetAssertions(), Native.fixedpointGetCoverDelta(), Native.fixedpointGetGroundSatAnswer(), Native.fixedpointGetHelp(), Native.fixedpointGetNumLevels(), Native.fixedpointGetParamDescrs(), Native.fixedpointGetReachable(), Native.fixedpointGetReasonUnknown(), Native.fixedpointGetRuleNamesAlongTrace(), Native.fixedpointGetRules(), Native.fixedpointGetRulesAlongTrace(), Native.fixedpointGetStatistics(), Native.fixedpointIncRef(), Native.fixedpointPop(), Native.fixedpointPush(), Native.fixedpointQuery(), Native.fixedpointQueryFromLvl(), Native.fixedpointQueryRelations(), Native.fixedpointRegisterRelation(), Native.fixedpointSetParams(), Native.fixedpointSetPredicateRepresentation(), Native.fixedpointToString(), Native.fixedpointUpdateRule(), Native.fpaGetEbits(), Native.fpaGetNumeralExponentBv(), Native.fpaGetNumeralExponentInt64(), Native.fpaGetNumeralExponentString(), Native.fpaGetNumeralSign(), Native.fpaGetNumeralSignBv(), Native.fpaGetNumeralSignificandBv(), Native.fpaGetNumeralSignificandString(), Native.fpaGetNumeralSignificandUint64(), Native.fpaGetSbits(), Native.fpaIsNumeralInf(), Native.fpaIsNumeralNan(), Native.fpaIsNumeralNegative(), Native.fpaIsNumeralNormal(), Native.fpaIsNumeralPositive(), Native.fpaIsNumeralSubnormal(), Native.fpaIsNumeralZero(), Native.funcDeclToAst(), Native.funcDeclToString(), Native.funcEntryDecRef(), Native.funcEntryGetArg(), Native.funcEntryGetNumArgs(), Native.funcEntryGetValue(), Native.funcEntryIncRef(), Native.funcInterpAddEntry(), Native.funcInterpDecRef(), Native.funcInterpGetArity(), Native.funcInterpGetElse(), Native.funcInterpGetEntry(), Native.funcInterpGetNumEntries(), Native.funcInterpIncRef(), Native.funcInterpSetElse(), Native.getAlgebraicNumberLower(), Native.getAlgebraicNumberUpper(), Native.getAppArg(), Native.getAppDecl(), Native.getAppNumArgs(), Native.getArity(), Native.getArraySortDomain(), Native.getArraySortRange(), Native.getAsArrayFuncDecl(), Native.getAstHash(), Native.getAstId(), Native.getAstKind(), Native.getBoolValue(), Native.getBvSortSize(), Native.getDatatypeSortConstructor(), Native.getDatatypeSortConstructorAccessor(), Native.getDatatypeSortNumConstructors(), Native.getDatatypeSortRecognizer(), Native.getDeclAstParameter(), Native.getDeclDoubleParameter(), Native.getDeclFuncDeclParameter(), Native.getDeclIntParameter(), Native.getDeclKind(), Native.getDeclName(), Native.getDeclNumParameters(), Native.getDeclParameterKind(), Native.getDeclRationalParameter(), Native.getDeclSortParameter(), Native.getDeclSymbolParameter(), Native.getDenominator(), Native.getDomain(), Native.getDomainSize(), Native.getErrorMsg(), Native.getFiniteDomainSortSize(), Native.getFuncDeclId(), Native.getImpliedEqualities(), Native.getIndexValue(), Native.getInterpolant(), Native.getNumeralDecimalString(), Native.getNumeralInt(), Native.getNumeralInt64(), Native.getNumeralRationalInt64(), Native.getNumeralSmall(), Native.getNumeralString(), Native.getNumeralUint(), Native.getNumeralUint64(), Native.getNumerator(), Native.getNumProbes(), Native.getNumTactics(), Native.getParserError(), Native.getPattern(), Native.getPatternNumTerms(), Native.getProbeName(), Native.getQuantifierBody(), Native.getQuantifierBoundName(), Native.getQuantifierBoundSort(), Native.getQuantifierNoPatternAst(), Native.getQuantifierNumBound(), Native.getQuantifierNumNoPatterns(), Native.getQuantifierNumPatterns(), Native.getQuantifierPatternAst(), Native.getQuantifierWeight(), Native.getRange(), Native.getRelationArity(), Native.getRelationColumn(), Native.getSort(), Native.getSortId(), Native.getSortKind(), Native.getSortName(), Native.getString(), Native.getSymbolInt(), Native.getSymbolKind(), Native.getSymbolString(), Native.getTacticName(), Native.getTupleSortFieldDecl(), Native.getTupleSortMkDecl(), Native.getTupleSortNumFields(), Native.goalAssert(), Native.goalDecRef(), Native.goalDepth(), Native.goalFormula(), Native.goalInconsistent(), Native.goalIncRef(), Native.goalIsDecidedSat(), Native.goalIsDecidedUnsat(), Native.goalNumExprs(), Native.goalPrecision(), Native.goalReset(), Native.goalSize(), Native.goalToString(), Native.goalTranslate(), Native.incRef(), Native.interpolationProfile(), Native.interrupt(), Native.isAlgebraicNumber(), Native.isApp(), Native.isAsArray(), Native.isEqAst(), Native.isEqFuncDecl(), Native.isEqSort(), Native.isNumeralAst(), Native.isQuantifierForall(), Native.isReSort(), Native.isSeqSort(), Native.isString(), Native.isStringSort(), Native.isWellSorted(), Native.mkAdd(), Native.mkAnd(), Native.mkApp(), Native.mkArrayDefault(), Native.mkArrayExt(), Native.mkArraySort(), Native.mkArraySortN(), Native.mkAsArray(), Native.mkAstMap(), Native.mkAstVector(), Native.mkAtleast(), Native.mkAtmost(), Native.mkBoolSort(), Native.mkBound(), Native.mkBv2int(), Native.mkBvadd(), Native.mkBvaddNoOverflow(), Native.mkBvaddNoUnderflow(), Native.mkBvand(), Native.mkBvashr(), Native.mkBvlshr(), Native.mkBvmul(), Native.mkBvmulNoOverflow(), Native.mkBvmulNoUnderflow(), Native.mkBvnand(), Native.mkBvneg(), Native.mkBvnegNoOverflow(), Native.mkBvnor(), Native.mkBvnot(), Native.mkBvNumeral(), Native.mkBvor(), Native.mkBvredand(), Native.mkBvredor(), Native.mkBvsdiv(), Native.mkBvsdivNoOverflow(), Native.mkBvsge(), Native.mkBvsgt(), Native.mkBvshl(), Native.mkBvsle(), Native.mkBvslt(), Native.mkBvsmod(), Native.mkBvSort(), Native.mkBvsrem(), Native.mkBvsub(), Native.mkBvsubNoOverflow(), Native.mkBvsubNoUnderflow(), Native.mkBvudiv(), Native.mkBvuge(), Native.mkBvugt(), Native.mkBvule(), Native.mkBvult(), Native.mkBvurem(), Native.mkBvxnor(), Native.mkBvxor(), Native.mkConcat(), Native.mkConst(), Native.mkConstArray(), Native.mkConstructor(), Native.mkConstructorList(), Native.mkDatatype(), Native.mkDatatypes(), Native.mkDistinct(), Native.mkDiv(), Native.mkEmptySet(), Native.mkEnumerationSort(), Native.mkEq(), Native.mkExists(), Native.mkExistsConst(), Native.mkExtract(), Native.mkExtRotateLeft(), Native.mkExtRotateRight(), Native.mkFalse(), Native.mkFiniteDomainSort(), Native.mkFixedpoint(), Native.mkForall(), Native.mkForallConst(), Native.mkFpaAbs(), Native.mkFpaAdd(), Native.mkFpaDiv(), Native.mkFpaEq(), Native.mkFpaFma(), Native.mkFpaFp(), Native.mkFpaGeq(), Native.mkFpaGt(), Native.mkFpaInf(), Native.mkFpaIsInfinite(), Native.mkFpaIsNan(), Native.mkFpaIsNegative(), Native.mkFpaIsNormal(), Native.mkFpaIsPositive(), Native.mkFpaIsSubnormal(), Native.mkFpaIsZero(), Native.mkFpaLeq(), Native.mkFpaLt(), Native.mkFpaMax(), Native.mkFpaMin(), Native.mkFpaMul(), Native.mkFpaNan(), Native.mkFpaNeg(), Native.mkFpaNumeralDouble(), Native.mkFpaNumeralFloat(), Native.mkFpaNumeralInt(), Native.mkFpaNumeralInt64Uint64(), Native.mkFpaNumeralIntUint(), Native.mkFpaRem(), Native.mkFpaRna(), Native.mkFpaRne(), Native.mkFpaRoundingModeSort(), Native.mkFpaRoundNearestTiesToAway(), Native.mkFpaRoundNearestTiesToEven(), Native.mkFpaRoundToIntegral(), Native.mkFpaRoundTowardNegative(), Native.mkFpaRoundTowardPositive(), Native.mkFpaRoundTowardZero(), Native.mkFpaRtn(), Native.mkFpaRtp(), Native.mkFpaRtz(), Native.mkFpaSort(), Native.mkFpaSort128(), Native.mkFpaSort16(), Native.mkFpaSort32(), Native.mkFpaSort64(), Native.mkFpaSortDouble(), Native.mkFpaSortHalf(), Native.mkFpaSortQuadruple(), Native.mkFpaSortSingle(), Native.mkFpaSqrt(), Native.mkFpaSub(), Native.mkFpaToFpBv(), Native.mkFpaToFpFloat(), Native.mkFpaToFpIntReal(), Native.mkFpaToFpReal(), Native.mkFpaToFpSigned(), Native.mkFpaToFpUnsigned(), Native.mkFpaToIeeeBv(), Native.mkFpaToReal(), Native.mkFpaToSbv(), Native.mkFpaToUbv(), Native.mkFpaZero(), Native.mkFreshConst(), Native.mkFreshFuncDecl(), Native.mkFullSet(), Native.mkFuncDecl(), Native.mkGe(), Native.mkGoal(), Native.mkGt(), Native.mkIff(), Native.mkImplies(), Native.mkInt(), Native.mkInt2bv(), Native.mkInt2real(), Native.mkInt64(), Native.mkInterpolant(), Native.mkIntSort(), Native.mkIntSymbol(), Native.mkIntToStr(), Native.mkIsInt(), Native.mkIte(), Native.mkLe(), Native.mkListSort(), Native.mkLt(), Native.mkMap(), Native.mkMod(), Native.mkModel(), Native.mkMul(), Native.mkNot(), Native.mkNumeral(), Native.mkOptimize(), Native.mkOr(), Native.mkParams(), Native.mkPattern(), Native.mkPbeq(), Native.mkPbge(), Native.mkPble(), Native.mkPower(), Native.mkProbe(), Native.mkQuantifier(), Native.mkQuantifierConst(), Native.mkQuantifierConstEx(), Native.mkQuantifierEx(), Native.mkReal(), Native.mkReal2int(), Native.mkRealSort(), Native.mkReComplement(), Native.mkReConcat(), Native.mkReEmpty(), Native.mkReFull(), Native.mkReIntersect(), Native.mkReLoop(), Native.mkRem(), Native.mkReOption(), Native.mkRepeat(), Native.mkRePlus(), Native.mkReRange(), Native.mkReSort(), Native.mkReStar(), Native.mkReUnion(), Native.mkRotateLeft(), Native.mkRotateRight(), Native.mkSelect(), Native.mkSelectN(), Native.mkSeqAt(), Native.mkSeqConcat(), Native.mkSeqContains(), Native.mkSeqEmpty(), Native.mkSeqExtract(), Native.mkSeqIndex(), Native.mkSeqInRe(), Native.mkSeqLength(), Native.mkSeqPrefix(), Native.mkSeqReplace(), Native.mkSeqSort(), Native.mkSeqSuffix(), Native.mkSeqToRe(), Native.mkSeqUnit(), Native.mkSetAdd(), Native.mkSetComplement(), Native.mkSetDel(), Native.mkSetDifference(), Native.mkSetIntersect(), Native.mkSetMember(), Native.mkSetSort(), Native.mkSetSubset(), Native.mkSetUnion(), Native.mkSignExt(), Native.mkSimpleSolver(), Native.mkSolver(), Native.mkSolverForLogic(), Native.mkSolverFromTactic(), Native.mkStore(), Native.mkStoreN(), Native.mkString(), Native.mkStringSort(), Native.mkStringSymbol(), Native.mkStrToInt(), Native.mkSub(), Native.mkTactic(), Native.mkTrue(), Native.mkTupleSort(), Native.mkUnaryMinus(), Native.mkUninterpretedSort(), Native.mkUnsignedInt(), Native.mkUnsignedInt64(), Native.mkXor(), Native.mkZeroExt(), Native.modelDecRef(), Native.modelEval(), Native.modelExtrapolate(), Native.modelGetConstDecl(), Native.modelGetConstInterp(), Native.modelGetFuncDecl(), Native.modelGetFuncInterp(), Native.modelGetNumConsts(), Native.modelGetNumFuncs(), Native.modelGetNumSorts(), Native.modelGetSort(), Native.modelGetSortUniverse(), Native.modelHasInterp(), Native.modelIncRef(), Native.modelToString(), Native.optimizeAssert(), Native.optimizeAssertSoft(), Native.optimizeCheck(), Native.optimizeDecRef(), Native.optimizeFromFile(), Native.optimizeFromString(), Native.optimizeGetAssertions(), Native.optimizeGetHelp(), Native.optimizeGetLower(), Native.optimizeGetLowerAsVector(), Native.optimizeGetModel(), Native.optimizeGetObjectives(), Native.optimizeGetParamDescrs(), Native.optimizeGetReasonUnknown(), Native.optimizeGetStatistics(), Native.optimizeGetUpper(), Native.optimizeGetUpperAsVector(), Native.optimizeIncRef(), Native.optimizeMaximize(), Native.optimizeMinimize(), Native.optimizePop(), Native.optimizePush(), Native.optimizeSetParams(), Native.optimizeToString(), Native.paramDescrsDecRef(), Native.paramDescrsGetDocumentation(), Native.paramDescrsGetKind(), Native.paramDescrsGetName(), Native.paramDescrsIncRef(), Native.paramDescrsSize(), Native.paramDescrsToString(), Native.paramsDecRef(), Native.paramsIncRef(), Native.paramsSetBool(), Native.paramsSetDouble(), Native.paramsSetSymbol(), Native.paramsSetUint(), Native.paramsToString(), Native.paramsValidate(), Native.parseSmtlib2File(), Native.parseSmtlib2String(), Native.patternToAst(), Native.patternToString(), Native.polynomialSubresultants(), Native.probeAnd(), Native.probeApply(), Native.probeConst(), Native.probeDecRef(), Native.probeEq(), Native.probeGe(), Native.probeGetDescr(), Native.probeGt(), Native.probeIncRef(), Native.probeLe(), Native.probeLt(), Native.probeNot(), Native.probeOr(), Native.qeLite(), Native.qeModelProject(), Native.qeModelProjectSkolem(), Native.queryConstructor(), Native.rcfAdd(), Native.rcfDel(), Native.rcfDiv(), Native.rcfEq(), Native.rcfGe(), Native.rcfGetNumeratorDenominator(), Native.rcfGt(), Native.rcfInv(), Native.rcfLe(), Native.rcfLt(), Native.rcfMkE(), Native.rcfMkInfinitesimal(), Native.rcfMkPi(), Native.rcfMkRational(), Native.rcfMkRoots(), Native.rcfMkSmallInt(), Native.rcfMul(), Native.rcfNeg(), Native.rcfNeq(), Native.rcfNumToDecimalString(), Native.rcfNumToString(), Native.rcfPower(), Native.rcfSub(), Native.readInterpolationProblem(), Native.setAstPrintMode(), Native.setError(), Native.simplify(), Native.simplifyEx(), Native.simplifyGetHelp(), Native.simplifyGetParamDescrs(), Native.solverAssert(), Native.solverAssertAndTrack(), Native.solverCheck(), Native.solverCheckAssumptions(), Native.solverDecRef(), Native.solverFromFile(), Native.solverFromString(), Native.solverGetAssertions(), Native.solverGetConsequences(), Native.solverGetHelp(), Native.solverGetModel(), Native.solverGetNumScopes(), Native.solverGetParamDescrs(), Native.solverGetProof(), Native.solverGetReasonUnknown(), Native.solverGetStatistics(), Native.solverGetUnsatCore(), Native.solverIncRef(), Native.solverPop(), Native.solverPush(), Native.solverReset(), Native.solverSetParams(), Native.solverToString(), Native.solverTranslate(), Native.sortToAst(), Native.sortToString(), Native.statsDecRef(), Native.statsGetDoubleValue(), Native.statsGetKey(), Native.statsGetUintValue(), Native.statsIncRef(), Native.statsIsDouble(), Native.statsIsUint(), Native.statsSize(), Native.statsToString(), Native.substitute(), Native.substituteVars(), Native.tacticAndThen(), Native.tacticApply(), Native.tacticApplyEx(), Native.tacticCond(), Native.tacticDecRef(), Native.tacticFail(), Native.tacticFailIf(), Native.tacticFailIfNotDecided(), Native.tacticGetDescr(), Native.tacticGetHelp(), Native.tacticGetParamDescrs(), Native.tacticIncRef(), Native.tacticOrElse(), Native.tacticParAndThen(), Native.tacticParOr(), Native.tacticRepeat(), Native.tacticSkip(), Native.tacticTryFor(), Native.tacticUsingParams(), Native.tacticWhen(), Native.toApp(), Native.toFuncDecl(), Native.translate(), Native.updateParamValue(), Native.updateTerm(), and Native.writeInterpolationProblem().
{
         Z3_error_code k = Z3_error_code_MappingHolder.intMapping.get(v);
         if (k != null) return k;
         throw new IllegalArgumentException("Illegal value " + v + " for Z3_error_code");
     }
final int toInt () inline
Definition at line 50 of file Z3_error_code.java.
Referenced by Native.addConstInterp(), Native.addFuncInterp(), Native.algebraicAdd(), Native.algebraicDiv(), Native.algebraicEq(), Native.algebraicEval(), Native.algebraicGe(), Native.algebraicGt(), Native.algebraicIsNeg(), Native.algebraicIsPos(), Native.algebraicIsValue(), Native.algebraicIsZero(), Native.algebraicLe(), Native.algebraicLt(), Native.algebraicMul(), Native.algebraicNeq(), Native.algebraicPower(), Native.algebraicRoot(), Native.algebraicRoots(), Native.algebraicSign(), Native.algebraicSub(), Native.applyResultConvertModel(), Native.applyResultDecRef(), Native.applyResultGetNumSubgoals(), Native.applyResultGetSubgoal(), Native.applyResultIncRef(), Native.applyResultToString(), Native.appToAst(), Native.astMapContains(), Native.astMapDecRef(), Native.astMapErase(), Native.astMapFind(), Native.astMapIncRef(), Native.astMapInsert(), Native.astMapKeys(), Native.astMapReset(), Native.astMapSize(), Native.astMapToString(), Native.astToString(), Native.astVectorDecRef(), Native.astVectorGet(), Native.astVectorIncRef(), Native.astVectorPush(), Native.astVectorResize(), Native.astVectorSet(), Native.astVectorSize(), Native.astVectorToString(), Native.astVectorTranslate(), Native.benchmarkToSmtlibString(), Native.checkInterpolant(), Native.computeInterpolant(), Native.datatypeUpdateField(), Native.decRef(), Native.delConstructor(), Native.delConstructorList(), Native.fixedpointAddCover(), Native.fixedpointAddFact(), Native.fixedpointAddInvariant(), Native.fixedpointAddRule(), Native.fixedpointAssert(), Native.fixedpointDecRef(), Native.fixedpointFromFile(), Native.fixedpointFromString(), Native.fixedpointGetAnswer(), Native.fixedpointGetAssertions(), Native.fixedpointGetCoverDelta(), Native.fixedpointGetGroundSatAnswer(), Native.fixedpointGetHelp(), Native.fixedpointGetNumLevels(), Native.fixedpointGetParamDescrs(), Native.fixedpointGetReachable(), Native.fixedpointGetReasonUnknown(), Native.fixedpointGetRuleNamesAlongTrace(), Native.fixedpointGetRules(), Native.fixedpointGetRulesAlongTrace(), Native.fixedpointGetStatistics(), Native.fixedpointIncRef(), Native.fixedpointPop(), Native.fixedpointPush(), Native.fixedpointQuery(), Native.fixedpointQueryFromLvl(), Native.fixedpointQueryRelations(), Native.fixedpointRegisterRelation(), Native.fixedpointSetParams(), Native.fixedpointSetPredicateRepresentation(), Native.fixedpointToString(), Native.fixedpointUpdateRule(), Native.fpaGetEbits(), Native.fpaGetNumeralExponentBv(), Native.fpaGetNumeralExponentInt64(), Native.fpaGetNumeralExponentString(), Native.fpaGetNumeralSign(), Native.fpaGetNumeralSignBv(), Native.fpaGetNumeralSignificandBv(), Native.fpaGetNumeralSignificandString(), Native.fpaGetNumeralSignificandUint64(), Native.fpaGetSbits(), Native.fpaIsNumeralInf(), Native.fpaIsNumeralNan(), Native.fpaIsNumeralNegative(), Native.fpaIsNumeralNormal(), Native.fpaIsNumeralPositive(), Native.fpaIsNumeralSubnormal(), Native.fpaIsNumeralZero(), Native.funcDeclToAst(), Native.funcDeclToString(), Native.funcEntryDecRef(), Native.funcEntryGetArg(), Native.funcEntryGetNumArgs(), Native.funcEntryGetValue(), Native.funcEntryIncRef(), Native.funcInterpAddEntry(), Native.funcInterpDecRef(), Native.funcInterpGetArity(), Native.funcInterpGetElse(), Native.funcInterpGetEntry(), Native.funcInterpGetNumEntries(), Native.funcInterpIncRef(), Native.funcInterpSetElse(), Native.getAlgebraicNumberLower(), Native.getAlgebraicNumberUpper(), Native.getAppArg(), Native.getAppDecl(), Native.getAppNumArgs(), Native.getArity(), Native.getArraySortDomain(), Native.getArraySortRange(), Native.getAsArrayFuncDecl(), Native.getAstHash(), Native.getAstId(), Native.getAstKind(), Native.getBoolValue(), Native.getBvSortSize(), Native.getDatatypeSortConstructor(), Native.getDatatypeSortConstructorAccessor(), Native.getDatatypeSortNumConstructors(), Native.getDatatypeSortRecognizer(), Native.getDeclAstParameter(), Native.getDeclDoubleParameter(), Native.getDeclFuncDeclParameter(), Native.getDeclIntParameter(), Native.getDeclKind(), Native.getDeclName(), Native.getDeclNumParameters(), Native.getDeclParameterKind(), Native.getDeclRationalParameter(), Native.getDeclSortParameter(), Native.getDeclSymbolParameter(), Native.getDenominator(), Native.getDomain(), Native.getDomainSize(), Native.getErrorMsg(), Native.getFiniteDomainSortSize(), Native.getFuncDeclId(), Native.getImpliedEqualities(), Native.getIndexValue(), Native.getInterpolant(), Native.getNumeralDecimalString(), Native.getNumeralInt(), Native.getNumeralInt64(), Native.getNumeralRationalInt64(), Native.getNumeralSmall(), Native.getNumeralString(), Native.getNumeralUint(), Native.getNumeralUint64(), Native.getNumerator(), Native.getNumProbes(), Native.getNumTactics(), Native.getParserError(), Native.getPattern(), Native.getPatternNumTerms(), Native.getProbeName(), Native.getQuantifierBody(), Native.getQuantifierBoundName(), Native.getQuantifierBoundSort(), Native.getQuantifierNoPatternAst(), Native.getQuantifierNumBound(), Native.getQuantifierNumNoPatterns(), Native.getQuantifierNumPatterns(), Native.getQuantifierPatternAst(), Native.getQuantifierWeight(), Native.getRange(), Native.getRelationArity(), Native.getRelationColumn(), Native.getSort(), Native.getSortId(), Native.getSortKind(), Native.getSortName(), Native.getString(), Native.getSymbolInt(), Native.getSymbolKind(), Native.getSymbolString(), Native.getTacticName(), Native.getTupleSortFieldDecl(), Native.getTupleSortMkDecl(), Native.getTupleSortNumFields(), Native.goalAssert(), Native.goalDecRef(), Native.goalDepth(), Native.goalFormula(), Native.goalInconsistent(), Native.goalIncRef(), Native.goalIsDecidedSat(), Native.goalIsDecidedUnsat(), Native.goalNumExprs(), Native.goalPrecision(), Native.goalReset(), Native.goalSize(), Native.goalToString(), Native.goalTranslate(), Native.incRef(), Native.interpolationProfile(), Native.interrupt(), Native.isAlgebraicNumber(), Native.isApp(), Native.isAsArray(), Native.isEqAst(), Native.isEqFuncDecl(), Native.isEqSort(), Native.isNumeralAst(), Native.isQuantifierForall(), Native.isReSort(), Native.isSeqSort(), Native.isString(), Native.isStringSort(), Native.isWellSorted(), Native.mkAdd(), Native.mkAnd(), Native.mkApp(), Native.mkArrayDefault(), Native.mkArrayExt(), Native.mkArraySort(), Native.mkArraySortN(), Native.mkAsArray(), Native.mkAstMap(), Native.mkAstVector(), Native.mkAtleast(), Native.mkAtmost(), Native.mkBoolSort(), Native.mkBound(), Native.mkBv2int(), Native.mkBvadd(), Native.mkBvaddNoOverflow(), Native.mkBvaddNoUnderflow(), Native.mkBvand(), Native.mkBvashr(), Native.mkBvlshr(), Native.mkBvmul(), Native.mkBvmulNoOverflow(), Native.mkBvmulNoUnderflow(), Native.mkBvnand(), Native.mkBvneg(), Native.mkBvnegNoOverflow(), Native.mkBvnor(), Native.mkBvnot(), Native.mkBvNumeral(), Native.mkBvor(), Native.mkBvredand(), Native.mkBvredor(), Native.mkBvsdiv(), Native.mkBvsdivNoOverflow(), Native.mkBvsge(), Native.mkBvsgt(), Native.mkBvshl(), Native.mkBvsle(), Native.mkBvslt(), Native.mkBvsmod(), Native.mkBvSort(), Native.mkBvsrem(), Native.mkBvsub(), Native.mkBvsubNoOverflow(), Native.mkBvsubNoUnderflow(), Native.mkBvudiv(), Native.mkBvuge(), Native.mkBvugt(), Native.mkBvule(), Native.mkBvult(), Native.mkBvurem(), Native.mkBvxnor(), Native.mkBvxor(), Native.mkConcat(), Native.mkConst(), Native.mkConstArray(), Native.mkConstructor(), Native.mkConstructorList(), Native.mkDatatype(), Native.mkDatatypes(), Native.mkDistinct(), Native.mkDiv(), Native.mkEmptySet(), Native.mkEnumerationSort(), Native.mkEq(), Native.mkExists(), Native.mkExistsConst(), Native.mkExtract(), Native.mkExtRotateLeft(), Native.mkExtRotateRight(), Native.mkFalse(), Native.mkFiniteDomainSort(), Native.mkFixedpoint(), Native.mkForall(), Native.mkForallConst(), Native.mkFpaAbs(), Native.mkFpaAdd(), Native.mkFpaDiv(), Native.mkFpaEq(), Native.mkFpaFma(), Native.mkFpaFp(), Native.mkFpaGeq(), Native.mkFpaGt(), Native.mkFpaInf(), Native.mkFpaIsInfinite(), Native.mkFpaIsNan(), Native.mkFpaIsNegative(), Native.mkFpaIsNormal(), Native.mkFpaIsPositive(), Native.mkFpaIsSubnormal(), Native.mkFpaIsZero(), Native.mkFpaLeq(), Native.mkFpaLt(), Native.mkFpaMax(), Native.mkFpaMin(), Native.mkFpaMul(), Native.mkFpaNan(), Native.mkFpaNeg(), Native.mkFpaNumeralDouble(), Native.mkFpaNumeralFloat(), Native.mkFpaNumeralInt(), Native.mkFpaNumeralInt64Uint64(), Native.mkFpaNumeralIntUint(), Native.mkFpaRem(), Native.mkFpaRna(), Native.mkFpaRne(), Native.mkFpaRoundingModeSort(), Native.mkFpaRoundNearestTiesToAway(), Native.mkFpaRoundNearestTiesToEven(), Native.mkFpaRoundToIntegral(), Native.mkFpaRoundTowardNegative(), Native.mkFpaRoundTowardPositive(), Native.mkFpaRoundTowardZero(), Native.mkFpaRtn(), Native.mkFpaRtp(), Native.mkFpaRtz(), Native.mkFpaSort(), Native.mkFpaSort128(), Native.mkFpaSort16(), Native.mkFpaSort32(), Native.mkFpaSort64(), Native.mkFpaSortDouble(), Native.mkFpaSortHalf(), Native.mkFpaSortQuadruple(), Native.mkFpaSortSingle(), Native.mkFpaSqrt(), Native.mkFpaSub(), Native.mkFpaToFpBv(), Native.mkFpaToFpFloat(), Native.mkFpaToFpIntReal(), Native.mkFpaToFpReal(), Native.mkFpaToFpSigned(), Native.mkFpaToFpUnsigned(), Native.mkFpaToIeeeBv(), Native.mkFpaToReal(), Native.mkFpaToSbv(), Native.mkFpaToUbv(), Native.mkFpaZero(), Native.mkFreshConst(), Native.mkFreshFuncDecl(), Native.mkFullSet(), Native.mkFuncDecl(), Native.mkGe(), Native.mkGoal(), Native.mkGt(), Native.mkIff(), Native.mkImplies(), Native.mkInt(), Native.mkInt2bv(), Native.mkInt2real(), Native.mkInt64(), Native.mkInterpolant(), Native.mkIntSort(), Native.mkIntSymbol(), Native.mkIntToStr(), Native.mkIsInt(), Native.mkIte(), Native.mkLe(), Native.mkListSort(), Native.mkLt(), Native.mkMap(), Native.mkMod(), Native.mkModel(), Native.mkMul(), Native.mkNot(), Native.mkNumeral(), Native.mkOptimize(), Native.mkOr(), Native.mkParams(), Native.mkPattern(), Native.mkPbeq(), Native.mkPbge(), Native.mkPble(), Native.mkPower(), Native.mkProbe(), Native.mkQuantifier(), Native.mkQuantifierConst(), Native.mkQuantifierConstEx(), Native.mkQuantifierEx(), Native.mkReal(), Native.mkReal2int(), Native.mkRealSort(), Native.mkReComplement(), Native.mkReConcat(), Native.mkReEmpty(), Native.mkReFull(), Native.mkReIntersect(), Native.mkReLoop(), Native.mkRem(), Native.mkReOption(), Native.mkRepeat(), Native.mkRePlus(), Native.mkReRange(), Native.mkReSort(), Native.mkReStar(), Native.mkReUnion(), Native.mkRotateLeft(), Native.mkRotateRight(), Native.mkSelect(), Native.mkSelectN(), Native.mkSeqAt(), Native.mkSeqConcat(), Native.mkSeqContains(), Native.mkSeqEmpty(), Native.mkSeqExtract(), Native.mkSeqIndex(), Native.mkSeqInRe(), Native.mkSeqLength(), Native.mkSeqPrefix(), Native.mkSeqReplace(), Native.mkSeqSort(), Native.mkSeqSuffix(), Native.mkSeqToRe(), Native.mkSeqUnit(), Native.mkSetAdd(), Native.mkSetComplement(), Native.mkSetDel(), Native.mkSetDifference(), Native.mkSetIntersect(), Native.mkSetMember(), Native.mkSetSort(), Native.mkSetSubset(), Native.mkSetUnion(), Native.mkSignExt(), Native.mkSimpleSolver(), Native.mkSolver(), Native.mkSolverForLogic(), Native.mkSolverFromTactic(), Native.mkStore(), Native.mkStoreN(), Native.mkString(), Native.mkStringSort(), Native.mkStringSymbol(), Native.mkStrToInt(), Native.mkSub(), Native.mkTactic(), Native.mkTrue(), Native.mkTupleSort(), Native.mkUnaryMinus(), Native.mkUninterpretedSort(), Native.mkUnsignedInt(), Native.mkUnsignedInt64(), Native.mkXor(), Native.mkZeroExt(), Native.modelDecRef(), Native.modelEval(), Native.modelExtrapolate(), Native.modelGetConstDecl(), Native.modelGetConstInterp(), Native.modelGetFuncDecl(), Native.modelGetFuncInterp(), Native.modelGetNumConsts(), Native.modelGetNumFuncs(), Native.modelGetNumSorts(), Native.modelGetSort(), Native.modelGetSortUniverse(), Native.modelHasInterp(), Native.modelIncRef(), Native.modelToString(), Native.optimizeAssert(), Native.optimizeAssertSoft(), Native.optimizeCheck(), Native.optimizeDecRef(), Native.optimizeFromFile(), Native.optimizeFromString(), Native.optimizeGetAssertions(), Native.optimizeGetHelp(), Native.optimizeGetLower(), Native.optimizeGetLowerAsVector(), Native.optimizeGetModel(), Native.optimizeGetObjectives(), Native.optimizeGetParamDescrs(), Native.optimizeGetReasonUnknown(), Native.optimizeGetStatistics(), Native.optimizeGetUpper(), Native.optimizeGetUpperAsVector(), Native.optimizeIncRef(), Native.optimizeMaximize(), Native.optimizeMinimize(), Native.optimizePop(), Native.optimizePush(), Native.optimizeSetParams(), Native.optimizeToString(), Native.paramDescrsDecRef(), Native.paramDescrsGetDocumentation(), Native.paramDescrsGetKind(), Native.paramDescrsGetName(), Native.paramDescrsIncRef(), Native.paramDescrsSize(), Native.paramDescrsToString(), Native.paramsDecRef(), Native.paramsIncRef(), Native.paramsSetBool(), Native.paramsSetDouble(), Native.paramsSetSymbol(), Native.paramsSetUint(), Native.paramsToString(), Native.paramsValidate(), Native.parseSmtlib2File(), Native.parseSmtlib2String(), Native.patternToAst(), Native.patternToString(), Native.polynomialSubresultants(), Native.probeAnd(), Native.probeApply(), Native.probeConst(), Native.probeDecRef(), Native.probeEq(), Native.probeGe(), Native.probeGetDescr(), Native.probeGt(), Native.probeIncRef(), Native.probeLe(), Native.probeLt(), Native.probeNot(), Native.probeOr(), Native.qeLite(), Native.qeModelProject(), Native.qeModelProjectSkolem(), Native.queryConstructor(), Native.rcfAdd(), Native.rcfDel(), Native.rcfDiv(), Native.rcfEq(), Native.rcfGe(), Native.rcfGetNumeratorDenominator(), Native.rcfGt(), Native.rcfInv(), Native.rcfLe(), Native.rcfLt(), Native.rcfMkE(), Native.rcfMkInfinitesimal(), Native.rcfMkPi(), Native.rcfMkRational(), Native.rcfMkRoots(), Native.rcfMkSmallInt(), Native.rcfMul(), Native.rcfNeg(), Native.rcfNeq(), Native.rcfNumToDecimalString(), Native.rcfNumToString(), Native.rcfPower(), Native.rcfSub(), Native.readInterpolationProblem(), Native.setAstPrintMode(), Native.setError(), Native.simplify(), Native.simplifyEx(), Native.simplifyGetHelp(), Native.simplifyGetParamDescrs(), Native.solverAssert(), Native.solverAssertAndTrack(), Native.solverCheck(), Native.solverCheckAssumptions(), Native.solverDecRef(), Native.solverFromFile(), Native.solverFromString(), Native.solverGetAssertions(), Native.solverGetConsequences(), Native.solverGetHelp(), Native.solverGetModel(), Native.solverGetNumScopes(), Native.solverGetParamDescrs(), Native.solverGetProof(), Native.solverGetReasonUnknown(), Native.solverGetStatistics(), Native.solverGetUnsatCore(), Native.solverIncRef(), Native.solverPop(), Native.solverPush(), Native.solverReset(), Native.solverSetParams(), Native.solverToString(), Native.solverTranslate(), Native.sortToAst(), Native.sortToString(), Native.statsDecRef(), Native.statsGetDoubleValue(), Native.statsGetKey(), Native.statsGetUintValue(), Native.statsIncRef(), Native.statsIsDouble(), Native.statsIsUint(), Native.statsSize(), Native.statsToString(), Native.substitute(), Native.substituteVars(), Native.tacticAndThen(), Native.tacticApply(), Native.tacticApplyEx(), Native.tacticCond(), Native.tacticDecRef(), Native.tacticFail(), Native.tacticFailIf(), Native.tacticFailIfNotDecided(), Native.tacticGetDescr(), Native.tacticGetHelp(), Native.tacticGetParamDescrs(), Native.tacticIncRef(), Native.tacticOrElse(), Native.tacticParAndThen(), Native.tacticParOr(), Native.tacticRepeat(), Native.tacticSkip(), Native.tacticTryFor(), Native.tacticUsingParams(), Native.tacticWhen(), Native.toApp(), Native.toFuncDecl(), Native.translate(), Native.updateParamValue(), Native.updateTerm(), and Native.writeInterpolationProblem().
 { return this.intValue; }
Field Documentation
Z3_DEC_REF_ERROR =(11)
Definition at line 25 of file Z3_error_code.java.
Z3_EXCEPTION =(12)
Definition at line 26 of file Z3_error_code.java.
Z3_FILE_ACCESS_ERROR =(8)
Definition at line 22 of file Z3_error_code.java.
Z3_INTERNAL_FATAL =(9)
Definition at line 23 of file Z3_error_code.java.
Z3_INVALID_ARG =(3)
Definition at line 17 of file Z3_error_code.java.
Z3_INVALID_PATTERN =(6)
Definition at line 20 of file Z3_error_code.java.
Z3_INVALID_USAGE =(10)
Definition at line 24 of file Z3_error_code.java.
Z3_IOB =(2)
Definition at line 16 of file Z3_error_code.java.
Z3_MEMOUT_FAIL =(7)
Definition at line 21 of file Z3_error_code.java.
Z3_NO_PARSER =(5)
Definition at line 19 of file Z3_error_code.java.
Z3_OK =(0)
Definition at line 14 of file Z3_error_code.java.
Referenced by Native.addConstInterp(), Native.addFuncInterp(), Native.algebraicAdd(), Native.algebraicDiv(), Native.algebraicEq(), Native.algebraicEval(), Native.algebraicGe(), Native.algebraicGt(), Native.algebraicIsNeg(), Native.algebraicIsPos(), Native.algebraicIsValue(), Native.algebraicIsZero(), Native.algebraicLe(), Native.algebraicLt(), Native.algebraicMul(), Native.algebraicNeq(), Native.algebraicPower(), Native.algebraicRoot(), Native.algebraicRoots(), Native.algebraicSign(), Native.algebraicSub(), Native.applyResultConvertModel(), Native.applyResultDecRef(), Native.applyResultGetNumSubgoals(), Native.applyResultGetSubgoal(), Native.applyResultIncRef(), Native.applyResultToString(), Native.appToAst(), Native.astMapContains(), Native.astMapDecRef(), Native.astMapErase(), Native.astMapFind(), Native.astMapIncRef(), Native.astMapInsert(), Native.astMapKeys(), Native.astMapReset(), Native.astMapSize(), Native.astMapToString(), Native.astToString(), Native.astVectorDecRef(), Native.astVectorGet(), Native.astVectorIncRef(), Native.astVectorPush(), Native.astVectorResize(), Native.astVectorSet(), Native.astVectorSize(), Native.astVectorToString(), Native.astVectorTranslate(), Native.benchmarkToSmtlibString(), Native.checkInterpolant(), Native.computeInterpolant(), Native.datatypeUpdateField(), Native.decRef(), Native.delConstructor(), Native.delConstructorList(), Native.fixedpointAddCover(), Native.fixedpointAddFact(), Native.fixedpointAddInvariant(), Native.fixedpointAddRule(), Native.fixedpointAssert(), Native.fixedpointDecRef(), Native.fixedpointFromFile(), Native.fixedpointFromString(), Native.fixedpointGetAnswer(), Native.fixedpointGetAssertions(), Native.fixedpointGetCoverDelta(), Native.fixedpointGetGroundSatAnswer(), Native.fixedpointGetHelp(), Native.fixedpointGetNumLevels(), Native.fixedpointGetParamDescrs(), Native.fixedpointGetReachable(), Native.fixedpointGetReasonUnknown(), Native.fixedpointGetRuleNamesAlongTrace(), Native.fixedpointGetRules(), Native.fixedpointGetRulesAlongTrace(), Native.fixedpointGetStatistics(), Native.fixedpointIncRef(), Native.fixedpointPop(), Native.fixedpointPush(), Native.fixedpointQuery(), Native.fixedpointQueryFromLvl(), Native.fixedpointQueryRelations(), Native.fixedpointRegisterRelation(), Native.fixedpointSetParams(), Native.fixedpointSetPredicateRepresentation(), Native.fixedpointToString(), Native.fixedpointUpdateRule(), Native.fpaGetEbits(), Native.fpaGetNumeralExponentBv(), Native.fpaGetNumeralExponentInt64(), Native.fpaGetNumeralExponentString(), Native.fpaGetNumeralSign(), Native.fpaGetNumeralSignBv(), Native.fpaGetNumeralSignificandBv(), Native.fpaGetNumeralSignificandString(), Native.fpaGetNumeralSignificandUint64(), Native.fpaGetSbits(), Native.fpaIsNumeralInf(), Native.fpaIsNumeralNan(), Native.fpaIsNumeralNegative(), Native.fpaIsNumeralNormal(), Native.fpaIsNumeralPositive(), Native.fpaIsNumeralSubnormal(), Native.fpaIsNumeralZero(), Native.funcDeclToAst(), Native.funcDeclToString(), Native.funcEntryDecRef(), Native.funcEntryGetArg(), Native.funcEntryGetNumArgs(), Native.funcEntryGetValue(), Native.funcEntryIncRef(), Native.funcInterpAddEntry(), Native.funcInterpDecRef(), Native.funcInterpGetArity(), Native.funcInterpGetElse(), Native.funcInterpGetEntry(), Native.funcInterpGetNumEntries(), Native.funcInterpIncRef(), Native.funcInterpSetElse(), Native.getAlgebraicNumberLower(), Native.getAlgebraicNumberUpper(), Native.getAppArg(), Native.getAppDecl(), Native.getAppNumArgs(), Native.getArity(), Native.getArraySortDomain(), Native.getArraySortRange(), Native.getAsArrayFuncDecl(), Native.getAstHash(), Native.getAstId(), Native.getAstKind(), Native.getBoolValue(), Native.getBvSortSize(), Native.getDatatypeSortConstructor(), Native.getDatatypeSortConstructorAccessor(), Native.getDatatypeSortNumConstructors(), Native.getDatatypeSortRecognizer(), Native.getDeclAstParameter(), Native.getDeclDoubleParameter(), Native.getDeclFuncDeclParameter(), Native.getDeclIntParameter(), Native.getDeclKind(), Native.getDeclName(), Native.getDeclNumParameters(), Native.getDeclParameterKind(), Native.getDeclRationalParameter(), Native.getDeclSortParameter(), Native.getDeclSymbolParameter(), Native.getDenominator(), Native.getDomain(), Native.getDomainSize(), Native.getErrorMsg(), Native.getFiniteDomainSortSize(), Native.getFuncDeclId(), Native.getImpliedEqualities(), Native.getIndexValue(), Native.getInterpolant(), Native.getNumeralDecimalString(), Native.getNumeralInt(), Native.getNumeralInt64(), Native.getNumeralRationalInt64(), Native.getNumeralSmall(), Native.getNumeralString(), Native.getNumeralUint(), Native.getNumeralUint64(), Native.getNumerator(), Native.getNumProbes(), Native.getNumTactics(), Native.getParserError(), Native.getPattern(), Native.getPatternNumTerms(), Native.getProbeName(), Native.getQuantifierBody(), Native.getQuantifierBoundName(), Native.getQuantifierBoundSort(), Native.getQuantifierNoPatternAst(), Native.getQuantifierNumBound(), Native.getQuantifierNumNoPatterns(), Native.getQuantifierNumPatterns(), Native.getQuantifierPatternAst(), Native.getQuantifierWeight(), Native.getRange(), Native.getRelationArity(), Native.getRelationColumn(), Native.getSort(), Native.getSortId(), Native.getSortKind(), Native.getSortName(), Native.getString(), Native.getSymbolInt(), Native.getSymbolKind(), Native.getSymbolString(), Native.getTacticName(), Native.getTupleSortFieldDecl(), Native.getTupleSortMkDecl(), Native.getTupleSortNumFields(), Native.goalAssert(), Native.goalDecRef(), Native.goalDepth(), Native.goalFormula(), Native.goalInconsistent(), Native.goalIncRef(), Native.goalIsDecidedSat(), Native.goalIsDecidedUnsat(), Native.goalNumExprs(), Native.goalPrecision(), Native.goalReset(), Native.goalSize(), Native.goalToString(), Native.goalTranslate(), Native.incRef(), Native.interpolationProfile(), Native.interrupt(), Native.isAlgebraicNumber(), Native.isApp(), Native.isAsArray(), Native.isEqAst(), Native.isEqFuncDecl(), Native.isEqSort(), Native.isNumeralAst(), Native.isQuantifierForall(), Native.isReSort(), Native.isSeqSort(), Native.isString(), Native.isStringSort(), Native.isWellSorted(), Native.mkAdd(), Native.mkAnd(), Native.mkApp(), Native.mkArrayDefault(), Native.mkArrayExt(), Native.mkArraySort(), Native.mkArraySortN(), Native.mkAsArray(), Native.mkAstMap(), Native.mkAstVector(), Native.mkAtleast(), Native.mkAtmost(), Native.mkBoolSort(), Native.mkBound(), Native.mkBv2int(), Native.mkBvadd(), Native.mkBvaddNoOverflow(), Native.mkBvaddNoUnderflow(), Native.mkBvand(), Native.mkBvashr(), Native.mkBvlshr(), Native.mkBvmul(), Native.mkBvmulNoOverflow(), Native.mkBvmulNoUnderflow(), Native.mkBvnand(), Native.mkBvneg(), Native.mkBvnegNoOverflow(), Native.mkBvnor(), Native.mkBvnot(), Native.mkBvNumeral(), Native.mkBvor(), Native.mkBvredand(), Native.mkBvredor(), Native.mkBvsdiv(), Native.mkBvsdivNoOverflow(), Native.mkBvsge(), Native.mkBvsgt(), Native.mkBvshl(), Native.mkBvsle(), Native.mkBvslt(), Native.mkBvsmod(), Native.mkBvSort(), Native.mkBvsrem(), Native.mkBvsub(), Native.mkBvsubNoOverflow(), Native.mkBvsubNoUnderflow(), Native.mkBvudiv(), Native.mkBvuge(), Native.mkBvugt(), Native.mkBvule(), Native.mkBvult(), Native.mkBvurem(), Native.mkBvxnor(), Native.mkBvxor(), Native.mkConcat(), Native.mkConst(), Native.mkConstArray(), Native.mkConstructor(), Native.mkConstructorList(), Native.mkDatatype(), Native.mkDatatypes(), Native.mkDistinct(), Native.mkDiv(), Native.mkEmptySet(), Native.mkEnumerationSort(), Native.mkEq(), Native.mkExists(), Native.mkExistsConst(), Native.mkExtract(), Native.mkExtRotateLeft(), Native.mkExtRotateRight(), Native.mkFalse(), Native.mkFiniteDomainSort(), Native.mkFixedpoint(), Native.mkForall(), Native.mkForallConst(), Native.mkFpaAbs(), Native.mkFpaAdd(), Native.mkFpaDiv(), Native.mkFpaEq(), Native.mkFpaFma(), Native.mkFpaFp(), Native.mkFpaGeq(), Native.mkFpaGt(), Native.mkFpaInf(), Native.mkFpaIsInfinite(), Native.mkFpaIsNan(), Native.mkFpaIsNegative(), Native.mkFpaIsNormal(), Native.mkFpaIsPositive(), Native.mkFpaIsSubnormal(), Native.mkFpaIsZero(), Native.mkFpaLeq(), Native.mkFpaLt(), Native.mkFpaMax(), Native.mkFpaMin(), Native.mkFpaMul(), Native.mkFpaNan(), Native.mkFpaNeg(), Native.mkFpaNumeralDouble(), Native.mkFpaNumeralFloat(), Native.mkFpaNumeralInt(), Native.mkFpaNumeralInt64Uint64(), Native.mkFpaNumeralIntUint(), Native.mkFpaRem(), Native.mkFpaRna(), Native.mkFpaRne(), Native.mkFpaRoundingModeSort(), Native.mkFpaRoundNearestTiesToAway(), Native.mkFpaRoundNearestTiesToEven(), Native.mkFpaRoundToIntegral(), Native.mkFpaRoundTowardNegative(), Native.mkFpaRoundTowardPositive(), Native.mkFpaRoundTowardZero(), Native.mkFpaRtn(), Native.mkFpaRtp(), Native.mkFpaRtz(), Native.mkFpaSort(), Native.mkFpaSort128(), Native.mkFpaSort16(), Native.mkFpaSort32(), Native.mkFpaSort64(), Native.mkFpaSortDouble(), Native.mkFpaSortHalf(), Native.mkFpaSortQuadruple(), Native.mkFpaSortSingle(), Native.mkFpaSqrt(), Native.mkFpaSub(), Native.mkFpaToFpBv(), Native.mkFpaToFpFloat(), Native.mkFpaToFpIntReal(), Native.mkFpaToFpReal(), Native.mkFpaToFpSigned(), Native.mkFpaToFpUnsigned(), Native.mkFpaToIeeeBv(), Native.mkFpaToReal(), Native.mkFpaToSbv(), Native.mkFpaToUbv(), Native.mkFpaZero(), Native.mkFreshConst(), Native.mkFreshFuncDecl(), Native.mkFullSet(), Native.mkFuncDecl(), Native.mkGe(), Native.mkGoal(), Native.mkGt(), Native.mkIff(), Native.mkImplies(), Native.mkInt(), Native.mkInt2bv(), Native.mkInt2real(), Native.mkInt64(), Native.mkInterpolant(), Native.mkIntSort(), Native.mkIntSymbol(), Native.mkIntToStr(), Native.mkIsInt(), Native.mkIte(), Native.mkLe(), Native.mkListSort(), Native.mkLt(), Native.mkMap(), Native.mkMod(), Native.mkModel(), Native.mkMul(), Native.mkNot(), Native.mkNumeral(), Native.mkOptimize(), Native.mkOr(), Native.mkParams(), Native.mkPattern(), Native.mkPbeq(), Native.mkPbge(), Native.mkPble(), Native.mkPower(), Native.mkProbe(), Native.mkQuantifier(), Native.mkQuantifierConst(), Native.mkQuantifierConstEx(), Native.mkQuantifierEx(), Native.mkReal(), Native.mkReal2int(), Native.mkRealSort(), Native.mkReComplement(), Native.mkReConcat(), Native.mkReEmpty(), Native.mkReFull(), Native.mkReIntersect(), Native.mkReLoop(), Native.mkRem(), Native.mkReOption(), Native.mkRepeat(), Native.mkRePlus(), Native.mkReRange(), Native.mkReSort(), Native.mkReStar(), Native.mkReUnion(), Native.mkRotateLeft(), Native.mkRotateRight(), Native.mkSelect(), Native.mkSelectN(), Native.mkSeqAt(), Native.mkSeqConcat(), Native.mkSeqContains(), Native.mkSeqEmpty(), Native.mkSeqExtract(), Native.mkSeqIndex(), Native.mkSeqInRe(), Native.mkSeqLength(), Native.mkSeqPrefix(), Native.mkSeqReplace(), Native.mkSeqSort(), Native.mkSeqSuffix(), Native.mkSeqToRe(), Native.mkSeqUnit(), Native.mkSetAdd(), Native.mkSetComplement(), Native.mkSetDel(), Native.mkSetDifference(), Native.mkSetIntersect(), Native.mkSetMember(), Native.mkSetSort(), Native.mkSetSubset(), Native.mkSetUnion(), Native.mkSignExt(), Native.mkSimpleSolver(), Native.mkSolver(), Native.mkSolverForLogic(), Native.mkSolverFromTactic(), Native.mkStore(), Native.mkStoreN(), Native.mkString(), Native.mkStringSort(), Native.mkStringSymbol(), Native.mkStrToInt(), Native.mkSub(), Native.mkTactic(), Native.mkTrue(), Native.mkTupleSort(), Native.mkUnaryMinus(), Native.mkUninterpretedSort(), Native.mkUnsignedInt(), Native.mkUnsignedInt64(), Native.mkXor(), Native.mkZeroExt(), Native.modelDecRef(), Native.modelEval(), Native.modelExtrapolate(), Native.modelGetConstDecl(), Native.modelGetConstInterp(), Native.modelGetFuncDecl(), Native.modelGetFuncInterp(), Native.modelGetNumConsts(), Native.modelGetNumFuncs(), Native.modelGetNumSorts(), Native.modelGetSort(), Native.modelGetSortUniverse(), Native.modelHasInterp(), Native.modelIncRef(), Native.modelToString(), Native.optimizeAssert(), Native.optimizeAssertSoft(), Native.optimizeCheck(), Native.optimizeDecRef(), Native.optimizeFromFile(), Native.optimizeFromString(), Native.optimizeGetAssertions(), Native.optimizeGetHelp(), Native.optimizeGetLower(), Native.optimizeGetLowerAsVector(), Native.optimizeGetModel(), Native.optimizeGetObjectives(), Native.optimizeGetParamDescrs(), Native.optimizeGetReasonUnknown(), Native.optimizeGetStatistics(), Native.optimizeGetUpper(), Native.optimizeGetUpperAsVector(), Native.optimizeIncRef(), Native.optimizeMaximize(), Native.optimizeMinimize(), Native.optimizePop(), Native.optimizePush(), Native.optimizeSetParams(), Native.optimizeToString(), Native.paramDescrsDecRef(), Native.paramDescrsGetDocumentation(), Native.paramDescrsGetKind(), Native.paramDescrsGetName(), Native.paramDescrsIncRef(), Native.paramDescrsSize(), Native.paramDescrsToString(), Native.paramsDecRef(), Native.paramsIncRef(), Native.paramsSetBool(), Native.paramsSetDouble(), Native.paramsSetSymbol(), Native.paramsSetUint(), Native.paramsToString(), Native.paramsValidate(), Native.parseSmtlib2File(), Native.parseSmtlib2String(), Native.patternToAst(), Native.patternToString(), Native.polynomialSubresultants(), Native.probeAnd(), Native.probeApply(), Native.probeConst(), Native.probeDecRef(), Native.probeEq(), Native.probeGe(), Native.probeGetDescr(), Native.probeGt(), Native.probeIncRef(), Native.probeLe(), Native.probeLt(), Native.probeNot(), Native.probeOr(), Native.qeLite(), Native.qeModelProject(), Native.qeModelProjectSkolem(), Native.queryConstructor(), Native.rcfAdd(), Native.rcfDel(), Native.rcfDiv(), Native.rcfEq(), Native.rcfGe(), Native.rcfGetNumeratorDenominator(), Native.rcfGt(), Native.rcfInv(), Native.rcfLe(), Native.rcfLt(), Native.rcfMkE(), Native.rcfMkInfinitesimal(), Native.rcfMkPi(), Native.rcfMkRational(), Native.rcfMkRoots(), Native.rcfMkSmallInt(), Native.rcfMul(), Native.rcfNeg(), Native.rcfNeq(), Native.rcfNumToDecimalString(), Native.rcfNumToString(), Native.rcfPower(), Native.rcfSub(), Native.readInterpolationProblem(), Native.setAstPrintMode(), Native.setError(), Native.simplify(), Native.simplifyEx(), Native.simplifyGetHelp(), Native.simplifyGetParamDescrs(), Native.solverAssert(), Native.solverAssertAndTrack(), Native.solverCheck(), Native.solverCheckAssumptions(), Native.solverDecRef(), Native.solverFromFile(), Native.solverFromString(), Native.solverGetAssertions(), Native.solverGetConsequences(), Native.solverGetHelp(), Native.solverGetModel(), Native.solverGetNumScopes(), Native.solverGetParamDescrs(), Native.solverGetProof(), Native.solverGetReasonUnknown(), Native.solverGetStatistics(), Native.solverGetUnsatCore(), Native.solverIncRef(), Native.solverPop(), Native.solverPush(), Native.solverReset(), Native.solverSetParams(), Native.solverToString(), Native.solverTranslate(), Native.sortToAst(), Native.sortToString(), Native.statsDecRef(), Native.statsGetDoubleValue(), Native.statsGetKey(), Native.statsGetUintValue(), Native.statsIncRef(), Native.statsIsDouble(), Native.statsIsUint(), Native.statsSize(), Native.statsToString(), Native.substitute(), Native.substituteVars(), Native.tacticAndThen(), Native.tacticApply(), Native.tacticApplyEx(), Native.tacticCond(), Native.tacticDecRef(), Native.tacticFail(), Native.tacticFailIf(), Native.tacticFailIfNotDecided(), Native.tacticGetDescr(), Native.tacticGetHelp(), Native.tacticGetParamDescrs(), Native.tacticIncRef(), Native.tacticOrElse(), Native.tacticParAndThen(), Native.tacticParOr(), Native.tacticRepeat(), Native.tacticSkip(), Native.tacticTryFor(), Native.tacticUsingParams(), Native.tacticWhen(), Native.toApp(), Native.toFuncDecl(), Native.translate(), Native.updateParamValue(), Native.updateTerm(), and Native.writeInterpolationProblem().
Z3_PARSER_ERROR =(4)
Definition at line 18 of file Z3_error_code.java.
Z3_SORT_ERROR =(1)
Definition at line 15 of file Z3_error_code.java.