Z3: Status Enum Reference
Status Enum Reference
Public Member Functions
Status (int v)
final int toInt ()
Static Public Member Functions
static Status fromInt (int v)
Data Fields
UNSATISFIABLE =(-1)
UNKNOWN =(0)
SATISFIABLE =(1)
Detailed Description
Status values.
Definition at line 23 of file Status.java.
Constructor & Destructor Documentation
Status()
Status (int v) inline
Definition at line 36 of file Status.java.
    {
        this.intValue = v;
    }
Member Function Documentation
fromInt()
static Status fromInt (int v) inline static
Definition at line 41 of file Status.java.
    {
        for (Status k : values())
            if (k.intValue == v)
                return k;
        return values()[0];
    }
Referenced by Optimize.Check(), and Solver.check().
toInt()
final int toInt () inline
Definition at line 49 of file Status.java.
    {
        return this.intValue;
    }
Field Documentation
SATISFIABLE
SATISFIABLE =(1)
Definition at line 32 of file Status.java.
Referenced by Optimize.Check(), Fixedpoint.query(), and Fixedpoint.query().
UNKNOWN
UNKNOWN =(0)
Definition at line 29 of file Status.java.
Referenced by Optimize.Check(), Fixedpoint.query(), and Fixedpoint.query().
UNSATISFIABLE
UNSATISFIABLE =(-1)
Definition at line 26 of file Status.java.
Referenced by Optimize.Check(), Fixedpoint.query(), and Fixedpoint.query().