Z3: Z3_parameter_kind Enum Reference
Z3_parameter_kind Enum Reference
Public Member Functions
Z3_parameter_kind (int v)
final int toInt ()
Static Public Member Functions
static final Z3_parameter_kind fromInt (int v)
Data Fields
Z3_PARAMETER_FUNC_DECL =(6)
Z3_PARAMETER_DOUBLE =(1)
Z3_PARAMETER_SYMBOL =(3)
Z3_PARAMETER_INT =(0)
Z3_PARAMETER_AST =(5)
Z3_PARAMETER_SORT =(4)
Z3_PARAMETER_RATIONAL =(2)
Detailed Description
Z3_parameter_kind
Definition at line 10 of file Z3_parameter_kind.java.
Constructor & Destructor Documentation
Z3_parameter_kind (int v) inline
Definition at line 21 of file Z3_parameter_kind.java.
{
         this.intValue = v;
     }
Member Function Documentation
static final Z3_parameter_kind fromInt (int v) inline static
Definition at line 25 of file Z3_parameter_kind.java.
Referenced by FuncDecl.getParameters().
{
         for (Z3_parameter_kind k: values())
             if (k.intValue == v) return k;
         return values()[0];
     }
final int toInt () inline
Definition at line 31 of file Z3_parameter_kind.java.
 { return this.intValue; }
Field Documentation
Z3_PARAMETER_AST =(5)
Definition at line 15 of file Z3_parameter_kind.java.
Referenced by FuncDecl.Parameter.getAST().
Z3_PARAMETER_DOUBLE =(1)
Definition at line 12 of file Z3_parameter_kind.java.
Referenced by FuncDecl.Parameter.getDouble().
Z3_PARAMETER_FUNC_DECL =(6)
Definition at line 11 of file Z3_parameter_kind.java.
Referenced by FuncDecl.Parameter.getFuncDecl().
Z3_PARAMETER_INT =(0)
Definition at line 14 of file Z3_parameter_kind.java.
Referenced by FuncDecl.Parameter.getInt().
Z3_PARAMETER_RATIONAL =(2)
Definition at line 17 of file Z3_parameter_kind.java.
Referenced by FuncDecl.Parameter.getRational().
Z3_PARAMETER_SORT =(4)
Definition at line 16 of file Z3_parameter_kind.java.
Referenced by FuncDecl.Parameter.getSort().
Z3_PARAMETER_SYMBOL =(3)
Definition at line 13 of file Z3_parameter_kind.java.
Referenced by FuncDecl.Parameter.getSymbol().