Z3: C API
C API
Types
enum Z3_lbool { Z3_L_FALSE = -1 , Z3_L_UNDEF , Z3_L_TRUE }
Lifted Boolean type: false, undefined, true.
enum Z3_symbol_kind { Z3_INT_SYMBOL , Z3_STRING_SYMBOL }
The different kinds of symbol. In Z3, a symbol can be represented using integers and strings (See Z3_get_symbol_kind).
enum Z3_parameter_kind {
Z3_PARAMETER_INT , Z3_PARAMETER_DOUBLE , Z3_PARAMETER_RATIONAL , Z3_PARAMETER_SYMBOL ,
Z3_PARAMETER_SORT , Z3_PARAMETER_AST , Z3_PARAMETER_FUNC_DECL , Z3_PARAMETER_INTERNAL ,
Z3_PARAMETER_ZSTRING
}
The different kinds of parameters that can be associated with function symbols.
enum Z3_sort_kind {
Z3_UNINTERPRETED_SORT , Z3_BOOL_SORT , Z3_INT_SORT , Z3_REAL_SORT ,
Z3_BV_SORT , Z3_ARRAY_SORT , Z3_DATATYPE_SORT , Z3_RELATION_SORT ,
Z3_FINITE_DOMAIN_SORT , Z3_FLOATING_POINT_SORT , Z3_ROUNDING_MODE_SORT , Z3_SEQ_SORT ,
Z3_RE_SORT , Z3_CHAR_SORT , Z3_TYPE_VAR , Z3_UNKNOWN_SORT = 1000
}
The different kinds of Z3 types (See Z3_get_sort_kind).
enum Z3_ast_kind {
Z3_NUMERAL_AST , Z3_APP_AST , Z3_VAR_AST , Z3_QUANTIFIER_AST ,
Z3_SORT_AST , Z3_FUNC_DECL_AST , Z3_UNKNOWN_AST = 1000
}
The different kinds of Z3 AST (abstract syntax trees). That is, terms, formulas and types.
enum Z3_decl_kind {
Z3_OP_TRUE = 0x100 , Z3_OP_FALSE , Z3_OP_EQ , Z3_OP_DISTINCT ,
Z3_OP_ITE , Z3_OP_AND , Z3_OP_OR , Z3_OP_IFF ,
Z3_OP_XOR , Z3_OP_NOT , Z3_OP_IMPLIES , Z3_OP_OEQ ,
Z3_OP_ANUM = 0x200 , Z3_OP_AGNUM , Z3_OP_LE , Z3_OP_GE ,
Z3_OP_LT , Z3_OP_GT , Z3_OP_ADD , Z3_OP_SUB ,
Z3_OP_UMINUS , Z3_OP_MUL , Z3_OP_DIV , Z3_OP_IDIV ,
Z3_OP_REM , Z3_OP_MOD , Z3_OP_TO_REAL , Z3_OP_TO_INT ,
Z3_OP_IS_INT , Z3_OP_POWER , Z3_OP_ABS , Z3_OP_STORE = 0x300 ,
Z3_OP_SELECT , Z3_OP_CONST_ARRAY , Z3_OP_ARRAY_MAP , Z3_OP_ARRAY_DEFAULT ,
Z3_OP_SET_UNION , Z3_OP_SET_INTERSECT , Z3_OP_SET_DIFFERENCE , Z3_OP_SET_COMPLEMENT ,
Z3_OP_SET_SUBSET , Z3_OP_AS_ARRAY , Z3_OP_ARRAY_EXT , Z3_OP_BNUM = 0x400 ,
Z3_OP_BIT1 , Z3_OP_BIT0 , Z3_OP_BNEG , Z3_OP_BADD ,
Z3_OP_BSUB , Z3_OP_BMUL , Z3_OP_BSDIV , Z3_OP_BUDIV ,
Z3_OP_BSREM , Z3_OP_BUREM , Z3_OP_BSMOD , Z3_OP_BSDIV0 ,
Z3_OP_BUDIV0 , Z3_OP_BSREM0 , Z3_OP_BUREM0 , Z3_OP_BSMOD0 ,
Z3_OP_ULEQ , Z3_OP_SLEQ , Z3_OP_UGEQ , Z3_OP_SGEQ ,
Z3_OP_ULT , Z3_OP_SLT , Z3_OP_UGT , Z3_OP_SGT ,
Z3_OP_BAND , Z3_OP_BOR , Z3_OP_BNOT , Z3_OP_BXOR ,
Z3_OP_BNAND , Z3_OP_BNOR , Z3_OP_BXNOR , Z3_OP_CONCAT ,
Z3_OP_SIGN_EXT , Z3_OP_ZERO_EXT , Z3_OP_EXTRACT , Z3_OP_REPEAT ,
Z3_OP_BREDOR , Z3_OP_BREDAND , Z3_OP_BCOMP , Z3_OP_BSHL ,
Z3_OP_BLSHR , Z3_OP_BASHR , Z3_OP_ROTATE_LEFT , Z3_OP_ROTATE_RIGHT ,
Z3_OP_EXT_ROTATE_LEFT , Z3_OP_EXT_ROTATE_RIGHT , Z3_OP_BIT2BOOL , Z3_OP_INT2BV ,
Z3_OP_BV2INT , Z3_OP_SBV2INT , Z3_OP_CARRY , Z3_OP_XOR3 ,
Z3_OP_BSMUL_NO_OVFL , Z3_OP_BUMUL_NO_OVFL , Z3_OP_BSMUL_NO_UDFL , Z3_OP_BSDIV_I ,
Z3_OP_BUDIV_I , Z3_OP_BSREM_I , Z3_OP_BUREM_I , Z3_OP_BSMOD_I ,
Z3_OP_PR_UNDEF = 0x500 , Z3_OP_PR_TRUE , Z3_OP_PR_ASSERTED , Z3_OP_PR_GOAL ,
Z3_OP_PR_MODUS_PONENS , Z3_OP_PR_REFLEXIVITY , Z3_OP_PR_SYMMETRY , Z3_OP_PR_TRANSITIVITY ,
Z3_OP_PR_TRANSITIVITY_STAR , Z3_OP_PR_MONOTONICITY , Z3_OP_PR_QUANT_INTRO , Z3_OP_PR_BIND ,
Z3_OP_PR_DISTRIBUTIVITY , Z3_OP_PR_AND_ELIM , Z3_OP_PR_NOT_OR_ELIM , Z3_OP_PR_REWRITE ,
Z3_OP_PR_REWRITE_STAR , Z3_OP_PR_PULL_QUANT , Z3_OP_PR_PUSH_QUANT , Z3_OP_PR_ELIM_UNUSED_VARS ,
Z3_OP_PR_DER , Z3_OP_PR_QUANT_INST , Z3_OP_PR_HYPOTHESIS , Z3_OP_PR_LEMMA ,
Z3_OP_PR_UNIT_RESOLUTION , Z3_OP_PR_IFF_TRUE , Z3_OP_PR_IFF_FALSE , Z3_OP_PR_COMMUTATIVITY ,
Z3_OP_PR_DEF_AXIOM , Z3_OP_PR_ASSUMPTION_ADD , Z3_OP_PR_LEMMA_ADD , Z3_OP_PR_REDUNDANT_DEL ,
Z3_OP_PR_CLAUSE_TRAIL , Z3_OP_PR_DEF_INTRO , Z3_OP_PR_APPLY_DEF , Z3_OP_PR_IFF_OEQ ,
Z3_OP_PR_NNF_POS , Z3_OP_PR_NNF_NEG , Z3_OP_PR_SKOLEMIZE , Z3_OP_PR_MODUS_PONENS_OEQ ,
Z3_OP_PR_TH_LEMMA , Z3_OP_PR_HYPER_RESOLVE , Z3_OP_RA_STORE = 0x600 , Z3_OP_RA_EMPTY ,
Z3_OP_RA_IS_EMPTY , Z3_OP_RA_JOIN , Z3_OP_RA_UNION , Z3_OP_RA_WIDEN ,
Z3_OP_RA_PROJECT , Z3_OP_RA_FILTER , Z3_OP_RA_NEGATION_FILTER , Z3_OP_RA_RENAME ,
Z3_OP_RA_COMPLEMENT , Z3_OP_RA_SELECT , Z3_OP_RA_CLONE , Z3_OP_FD_CONSTANT ,
Z3_OP_FD_LT , Z3_OP_SEQ_UNIT , Z3_OP_SEQ_EMPTY , Z3_OP_SEQ_CONCAT ,
Z3_OP_SEQ_PREFIX , Z3_OP_SEQ_SUFFIX , Z3_OP_SEQ_CONTAINS , Z3_OP_SEQ_EXTRACT ,
Z3_OP_SEQ_REPLACE , Z3_OP_SEQ_REPLACE_RE , Z3_OP_SEQ_REPLACE_RE_ALL , Z3_OP_SEQ_REPLACE_ALL ,
Z3_OP_SEQ_AT , Z3_OP_SEQ_NTH , Z3_OP_SEQ_LENGTH , Z3_OP_SEQ_INDEX ,
Z3_OP_SEQ_LAST_INDEX , Z3_OP_SEQ_TO_RE , Z3_OP_SEQ_IN_RE , Z3_OP_SEQ_MAP ,
Z3_OP_SEQ_MAPI , Z3_OP_SEQ_FOLDL , Z3_OP_SEQ_FOLDLI , Z3_OP_STR_TO_INT ,
Z3_OP_INT_TO_STR , Z3_OP_UBV_TO_STR , Z3_OP_SBV_TO_STR , Z3_OP_STR_TO_CODE ,
Z3_OP_STR_FROM_CODE , Z3_OP_STRING_LT , Z3_OP_STRING_LE , Z3_OP_RE_PLUS ,
Z3_OP_RE_STAR , Z3_OP_RE_OPTION , Z3_OP_RE_CONCAT , Z3_OP_RE_UNION ,
Z3_OP_RE_RANGE , Z3_OP_RE_DIFF , Z3_OP_RE_INTERSECT , Z3_OP_RE_LOOP ,
Z3_OP_RE_POWER , Z3_OP_RE_COMPLEMENT , Z3_OP_RE_EMPTY_SET , Z3_OP_RE_FULL_SET ,
Z3_OP_RE_FULL_CHAR_SET , Z3_OP_RE_OF_PRED , Z3_OP_RE_REVERSE , Z3_OP_RE_DERIVATIVE ,
Z3_OP_CHAR_CONST , Z3_OP_CHAR_LE , Z3_OP_CHAR_TO_INT , Z3_OP_CHAR_TO_BV ,
Z3_OP_CHAR_FROM_BV , Z3_OP_CHAR_IS_DIGIT , Z3_OP_LABEL = 0x700 , Z3_OP_LABEL_LIT ,
Z3_OP_DT_CONSTRUCTOR =0x800 , Z3_OP_DT_RECOGNISER , Z3_OP_DT_IS , Z3_OP_DT_ACCESSOR ,
Z3_OP_DT_UPDATE_FIELD , Z3_OP_PB_AT_MOST =0x900 , Z3_OP_PB_AT_LEAST , Z3_OP_PB_LE ,
Z3_OP_PB_GE , Z3_OP_PB_EQ , Z3_OP_SPECIAL_RELATION_LO = 0xa000 , Z3_OP_SPECIAL_RELATION_PO ,
Z3_OP_SPECIAL_RELATION_PLO , Z3_OP_SPECIAL_RELATION_TO , Z3_OP_SPECIAL_RELATION_TC , Z3_OP_SPECIAL_RELATION_TRC ,
Z3_OP_FPA_RM_NEAREST_TIES_TO_EVEN = 0xb000 , Z3_OP_FPA_RM_NEAREST_TIES_TO_AWAY , Z3_OP_FPA_RM_TOWARD_POSITIVE , Z3_OP_FPA_RM_TOWARD_NEGATIVE ,
Z3_OP_FPA_RM_TOWARD_ZERO , Z3_OP_FPA_NUM , Z3_OP_FPA_PLUS_INF , Z3_OP_FPA_MINUS_INF ,
Z3_OP_FPA_NAN , Z3_OP_FPA_PLUS_ZERO , Z3_OP_FPA_MINUS_ZERO , Z3_OP_FPA_ADD ,
Z3_OP_FPA_SUB , Z3_OP_FPA_NEG , Z3_OP_FPA_MUL , Z3_OP_FPA_DIV ,
Z3_OP_FPA_REM , Z3_OP_FPA_ABS , Z3_OP_FPA_MIN , Z3_OP_FPA_MAX ,
Z3_OP_FPA_FMA , Z3_OP_FPA_SQRT , Z3_OP_FPA_ROUND_TO_INTEGRAL , Z3_OP_FPA_EQ ,
Z3_OP_FPA_LT , Z3_OP_FPA_GT , Z3_OP_FPA_LE , Z3_OP_FPA_GE ,
Z3_OP_FPA_IS_NAN , Z3_OP_FPA_IS_INF , Z3_OP_FPA_IS_ZERO , Z3_OP_FPA_IS_NORMAL ,
Z3_OP_FPA_IS_SUBNORMAL , Z3_OP_FPA_IS_NEGATIVE , Z3_OP_FPA_IS_POSITIVE , Z3_OP_FPA_FP ,
Z3_OP_FPA_TO_FP , Z3_OP_FPA_TO_FP_UNSIGNED , Z3_OP_FPA_TO_UBV , Z3_OP_FPA_TO_SBV ,
Z3_OP_FPA_TO_REAL , Z3_OP_FPA_TO_IEEE_BV , Z3_OP_FPA_BVWRAP , Z3_OP_FPA_BV2RM ,
Z3_OP_INTERNAL , Z3_OP_RECURSIVE , Z3_OP_UNINTERPRETED
}
The different kinds of interpreted function kinds.
enum Z3_param_kind {
Z3_PK_UINT , Z3_PK_BOOL , Z3_PK_DOUBLE , Z3_PK_SYMBOL ,
Z3_PK_STRING , Z3_PK_OTHER , Z3_PK_INVALID
}
The different kinds of parameters that can be associated with parameter sets. (see Z3_mk_params).
enum Z3_ast_print_mode { Z3_PRINT_SMTLIB_FULL , Z3_PRINT_LOW_LEVEL , Z3_PRINT_SMTLIB2_COMPLIANT }
Z3 pretty printing modes (See Z3_set_ast_print_mode).
enum Z3_error_code {
Z3_OK , Z3_SORT_ERROR , Z3_IOB , Z3_INVALID_ARG ,
Z3_PARSER_ERROR , Z3_NO_PARSER , Z3_INVALID_PATTERN , Z3_MEMOUT_FAIL ,
Z3_FILE_ACCESS_ERROR , Z3_INTERNAL_FATAL , Z3_INVALID_USAGE , Z3_DEC_REF_ERROR ,
Z3_EXCEPTION
}
Z3 error codes (See Z3_get_error_code).
enum Z3_goal_prec { Z3_GOAL_PRECISE , Z3_GOAL_UNDER , Z3_GOAL_OVER , Z3_GOAL_UNDER_OVER }
Z3 custom error handler (See Z3_set_error_handler).
typedef const char * Z3_string
Z3 string type. It is just an alias for const char *.
typedef char const * Z3_char_ptr
typedef Z3_string * Z3_string_ptr
Fixedpoint facilities
typedef void Z3_fixedpoint_reduce_assign_callback_fptr(void *, Z3_func_decl, unsigned, Z3_ast const [], unsigned, Z3_ast const [])
The following utilities allows adding user-defined domains.
typedef void Z3_fixedpoint_reduce_app_callback_fptr(void *, Z3_func_decl, unsigned, Z3_ast const [], Z3_ast *)
typedef void(* Z3_fixedpoint_new_lemma_eh) (void *state, Z3_ast lemma, unsigned level)
typedef void(* Z3_fixedpoint_predecessor_eh) (void *state)
typedef void(* Z3_fixedpoint_unfold_eh) (void *state)
Z3_fixedpoint Z3_API Z3_mk_fixedpoint (Z3_context c)
Create a new fixedpoint context.
void Z3_API Z3_fixedpoint_inc_ref (Z3_context c, Z3_fixedpoint d)
Increment the reference counter of the given fixedpoint context.
void Z3_API Z3_fixedpoint_dec_ref (Z3_context c, Z3_fixedpoint d)
Decrement the reference counter of the given fixedpoint context.
void Z3_API Z3_fixedpoint_add_rule (Z3_context c, Z3_fixedpoint d, Z3_ast rule, Z3_symbol name)
Add a universal Horn clause as a named rule. The horn_rule should be of the form:
void Z3_API Z3_fixedpoint_add_fact (Z3_context c, Z3_fixedpoint d, Z3_func_decl r, unsigned num_args, unsigned args[])
Add a Database fact.
void Z3_API Z3_fixedpoint_assert (Z3_context c, Z3_fixedpoint d, Z3_ast axiom)
Assert a constraint to the fixedpoint context.
Z3_lbool Z3_API Z3_fixedpoint_query (Z3_context c, Z3_fixedpoint d, Z3_ast query)
Pose a query against the asserted rules.
Z3_lbool Z3_API Z3_fixedpoint_query_relations (Z3_context c, Z3_fixedpoint d, unsigned num_relations, Z3_func_decl const relations[])
Pose multiple queries against the asserted rules.
Z3_ast Z3_API Z3_fixedpoint_get_answer (Z3_context c, Z3_fixedpoint d)
Retrieve a formula that encodes satisfying answers to the query.
Z3_string Z3_API Z3_fixedpoint_get_reason_unknown (Z3_context c, Z3_fixedpoint d)
Retrieve a string that describes the last status returned by Z3_fixedpoint_query.
void Z3_API Z3_fixedpoint_update_rule (Z3_context c, Z3_fixedpoint d, Z3_ast a, Z3_symbol name)
Update a named rule. A rule with the same name must have been previously created.
unsigned Z3_API Z3_fixedpoint_get_num_levels (Z3_context c, Z3_fixedpoint d, Z3_func_decl pred)
Query the PDR engine for the maximal levels properties are known about predicate.
Z3_ast Z3_API Z3_fixedpoint_get_cover_delta (Z3_context c, Z3_fixedpoint d, int level, Z3_func_decl pred)
void Z3_API Z3_fixedpoint_add_cover (Z3_context c, Z3_fixedpoint d, int level, Z3_func_decl pred, Z3_ast property)
Add property about the predicate pred. Add a property of predicate pred at level. It gets pushed forward when possible.
Z3_stats Z3_API Z3_fixedpoint_get_statistics (Z3_context c, Z3_fixedpoint d)
Retrieve statistics information from the last call to Z3_fixedpoint_query.
void Z3_API Z3_fixedpoint_register_relation (Z3_context c, Z3_fixedpoint d, Z3_func_decl f)
Register relation as Fixedpoint defined. Fixedpoint defined relations have least-fixedpoint semantics. For example, the relation is empty if it does not occur in a head or a fact.
void Z3_API Z3_fixedpoint_set_predicate_representation (Z3_context c, Z3_fixedpoint d, Z3_func_decl f, unsigned num_relations, Z3_symbol const relation_kinds[])
Configure the predicate representation.
Z3_ast_vector Z3_API Z3_fixedpoint_get_rules (Z3_context c, Z3_fixedpoint f)
Retrieve set of rules from fixedpoint context.
Z3_ast_vector Z3_API Z3_fixedpoint_get_assertions (Z3_context c, Z3_fixedpoint f)
Retrieve set of background assertions from fixedpoint context.
void Z3_API Z3_fixedpoint_set_params (Z3_context c, Z3_fixedpoint f, Z3_params p)
Set parameters on fixedpoint context.
Z3_string Z3_API Z3_fixedpoint_get_help (Z3_context c, Z3_fixedpoint f)
Return a string describing all fixedpoint available parameters.
Z3_param_descrs Z3_API Z3_fixedpoint_get_param_descrs (Z3_context c, Z3_fixedpoint f)
Return the parameter description set for the given fixedpoint object.
Z3_string Z3_API Z3_fixedpoint_to_string (Z3_context c, Z3_fixedpoint f, unsigned num_queries, Z3_ast queries[])
Print the current rules and background axioms as a string.
Z3_ast_vector Z3_API Z3_fixedpoint_from_string (Z3_context c, Z3_fixedpoint f, Z3_string s)
Parse an SMT-LIB2 string with fixedpoint rules. Add the rules to the current fixedpoint context. Return the set of queries in the string.
Z3_ast_vector Z3_API Z3_fixedpoint_from_file (Z3_context c, Z3_fixedpoint f, Z3_string s)
Parse an SMT-LIB2 file with fixedpoint rules. Add the rules to the current fixedpoint context. Return the set of queries in the file.
void Z3_API Z3_fixedpoint_init (Z3_context c, Z3_fixedpoint d, void *state)
Initialize the context with a user-defined state.
void Z3_API Z3_fixedpoint_set_reduce_assign_callback (Z3_context c, Z3_fixedpoint d, Z3_fixedpoint_reduce_assign_callback_fptr cb)
Register a callback to destructive updates.
void Z3_API Z3_fixedpoint_set_reduce_app_callback (Z3_context c, Z3_fixedpoint d, Z3_fixedpoint_reduce_app_callback_fptr cb)
Register a callback for building terms based on the relational operators.
void Z3_API Z3_fixedpoint_add_callback (Z3_context ctx, Z3_fixedpoint f, void *state, Z3_fixedpoint_new_lemma_eh new_lemma_eh, Z3_fixedpoint_predecessor_eh predecessor_eh, Z3_fixedpoint_unfold_eh unfold_eh)
set export callback for lemmas
void Z3_API Z3_fixedpoint_add_constraint (Z3_context c, Z3_fixedpoint d, Z3_ast e, unsigned lvl)
Algebraic Numbers
bool Z3_API Z3_algebraic_is_value (Z3_context c, Z3_ast a)
Return true if a can be used as value in the Z3 real algebraic number package.
bool Z3_API Z3_algebraic_is_pos (Z3_context c, Z3_ast a)
Return true if a is positive, and false otherwise.
bool Z3_API Z3_algebraic_is_neg (Z3_context c, Z3_ast a)
Return true if a is negative, and false otherwise.
bool Z3_API Z3_algebraic_is_zero (Z3_context c, Z3_ast a)
Return true if a is zero, and false otherwise.
int Z3_API Z3_algebraic_sign (Z3_context c, Z3_ast a)
Return 1 if a is positive, 0 if a is zero, and -1 if a is negative.
Z3_ast Z3_API Z3_algebraic_add (Z3_context c, Z3_ast a, Z3_ast b)
Return the value a + b.
Z3_ast Z3_API Z3_algebraic_sub (Z3_context c, Z3_ast a, Z3_ast b)
Return the value a - b.
Z3_ast Z3_API Z3_algebraic_mul (Z3_context c, Z3_ast a, Z3_ast b)
Return the value a * b.
Z3_ast Z3_API Z3_algebraic_div (Z3_context c, Z3_ast a, Z3_ast b)
Return the value a / b.
Z3_ast Z3_API Z3_algebraic_root (Z3_context c, Z3_ast a, unsigned k)
Return the a^(1/k)
Z3_ast Z3_API Z3_algebraic_power (Z3_context c, Z3_ast a, unsigned k)
Return the a^k.
bool Z3_API Z3_algebraic_lt (Z3_context c, Z3_ast a, Z3_ast b)
Return true if a < b, and false otherwise.
bool Z3_API Z3_algebraic_gt (Z3_context c, Z3_ast a, Z3_ast b)
Return true if a > b, and false otherwise.
bool Z3_API Z3_algebraic_le (Z3_context c, Z3_ast a, Z3_ast b)
Return true if a <= b, and false otherwise.
bool Z3_API Z3_algebraic_ge (Z3_context c, Z3_ast a, Z3_ast b)
Return true if a >= b, and false otherwise.
bool Z3_API Z3_algebraic_eq (Z3_context c, Z3_ast a, Z3_ast b)
Return true if a == b, and false otherwise.
bool Z3_API Z3_algebraic_neq (Z3_context c, Z3_ast a, Z3_ast b)
Return true if a != b, and false otherwise.
Z3_ast_vector Z3_API Z3_algebraic_roots (Z3_context c, Z3_ast p, unsigned n, Z3_ast a[])
Given a multivariate polynomial p(x_0, ..., x_{n-1}, x_n), returns the roots of the univariate polynomial p(a[0], ..., a[n-1], x_n).
int Z3_API Z3_algebraic_eval (Z3_context c, Z3_ast p, unsigned n, Z3_ast a[])
Given a multivariate polynomial p(x_0, ..., x_{n-1}), return the sign of p(a[0], ..., a[n-1]).
Z3_ast_vector Z3_API Z3_algebraic_get_poly (Z3_context c, Z3_ast a)
Return the coefficients of the defining polynomial.
unsigned Z3_API Z3_algebraic_get_i (Z3_context c, Z3_ast a)
Return which root of the polynomial the algebraic number represents.
Global Parameters
void Z3_API Z3_global_param_set (Z3_string param_id, Z3_string param_value)
Set a global (or module) parameter. This setting is shared by all Z3 contexts.
void Z3_API Z3_global_param_reset_all (void)
Restore the value of all global (and module) parameters. This command will not affect already created objects (such as tactics and solvers).
bool Z3_API Z3_global_param_get (Z3_string param_id, Z3_string_ptr param_value)
Get a global (or module) parameter.
Create configuration
Z3_config Z3_API Z3_mk_config (void)
Create a configuration object for the Z3 context object.
void Z3_API Z3_del_config (Z3_config c)
Delete the given configuration object.
void Z3_API Z3_set_param_value (Z3_config c, Z3_string param_id, Z3_string param_value)
Set a configuration parameter.
Context and AST Reference Counting
Z3_context Z3_API Z3_mk_context (Z3_config c)
Create a context using the given configuration.
Z3_context Z3_API Z3_mk_context_rc (Z3_config c)
Create a context using the given configuration. This function is similar to Z3_mk_context. However, in the context returned by this function, the user is responsible for managing Z3_ast reference counters. Managing reference counters is a burden and error-prone, but allows the user to use the memory more efficiently. The user must invoke Z3_inc_ref for any Z3_ast returned by Z3, and Z3_dec_ref whenever the Z3_ast is not needed anymore. This idiom is similar to the one used in BDD (binary decision diagrams) packages such as CUDD.
void Z3_API Z3_del_context (Z3_context c)
Delete the given logical context.
void Z3_API Z3_inc_ref (Z3_context c, Z3_ast a)
Increment the reference counter of the given AST. The context c should have been created using Z3_mk_context_rc. This function is a NOOP if c was created using Z3_mk_context.
void Z3_API Z3_dec_ref (Z3_context c, Z3_ast a)
Decrement the reference counter of the given AST. The context c should have been created using Z3_mk_context_rc. This function is a NOOP if c was created using Z3_mk_context.
void Z3_API Z3_update_param_value (Z3_context c, Z3_string param_id, Z3_string param_value)
Set a value of a context parameter.
Z3_param_descrs Z3_API Z3_get_global_param_descrs (Z3_context c)
Retrieve description of global parameters.
void Z3_API Z3_interrupt (Z3_context c)
Interrupt the execution of a Z3 procedure. This procedure can be used to interrupt: solvers, simplifiers and tactics.
void Z3_API Z3_enable_concurrent_dec_ref (Z3_context c)
use concurrency control for dec-ref. Reference counting decrements are allowed in separate threads from the context. If this setting is not invoked, reference counting decrements are not going to be thread safe.
Parameters
Z3_params Z3_API Z3_mk_params (Z3_context c)
Create a Z3 (empty) parameter set. Starting at Z3 4.0, parameter sets are used to configure many components such as: simplifiers, tactics, solvers, etc.
void Z3_API Z3_params_inc_ref (Z3_context c, Z3_params p)
Increment the reference counter of the given parameter set.
void Z3_API Z3_params_dec_ref (Z3_context c, Z3_params p)
Decrement the reference counter of the given parameter set.
void Z3_API Z3_params_set_bool (Z3_context c, Z3_params p, Z3_symbol k, bool v)
Add a Boolean parameter k with value v to the parameter set p.
void Z3_API Z3_params_set_uint (Z3_context c, Z3_params p, Z3_symbol k, unsigned v)
Add a unsigned parameter k with value v to the parameter set p.
void Z3_API Z3_params_set_double (Z3_context c, Z3_params p, Z3_symbol k, double v)
Add a double parameter k with value v to the parameter set p.
void Z3_API Z3_params_set_symbol (Z3_context c, Z3_params p, Z3_symbol k, Z3_symbol v)
Add a symbol parameter k with value v to the parameter set p.
Z3_string Z3_API Z3_params_to_string (Z3_context c, Z3_params p)
Convert a parameter set into a string. This function is mainly used for printing the contents of a parameter set.
void Z3_API Z3_params_validate (Z3_context c, Z3_params p, Z3_param_descrs d)
Validate the parameter set p against the parameter description set d.
Parameter Descriptions
void Z3_API Z3_param_descrs_inc_ref (Z3_context c, Z3_param_descrs p)
Increment the reference counter of the given parameter description set.
void Z3_API Z3_param_descrs_dec_ref (Z3_context c, Z3_param_descrs p)
Decrement the reference counter of the given parameter description set.
Z3_param_kind Z3_API Z3_param_descrs_get_kind (Z3_context c, Z3_param_descrs p, Z3_symbol n)
Return the kind associated with the given parameter name n.
unsigned Z3_API Z3_param_descrs_size (Z3_context c, Z3_param_descrs p)
Return the number of parameters in the given parameter description set.
Z3_symbol Z3_API Z3_param_descrs_get_name (Z3_context c, Z3_param_descrs p, unsigned i)
Return the name of the parameter at given index i.
Z3_string Z3_API Z3_param_descrs_get_documentation (Z3_context c, Z3_param_descrs p, Z3_symbol s)
Retrieve documentation string corresponding to parameter name s.
Z3_string Z3_API Z3_param_descrs_to_string (Z3_context c, Z3_param_descrs p)
Convert a parameter description set into a string. This function is mainly used for printing the contents of a parameter description set.
Symbols
Z3_symbol Z3_API Z3_mk_int_symbol (Z3_context c, int i)
Create a Z3 symbol using an integer.
Z3_symbol Z3_API Z3_mk_string_symbol (Z3_context c, Z3_string s)
Create a Z3 symbol using a C string.
Sorts
Z3_sort Z3_API Z3_mk_uninterpreted_sort (Z3_context c, Z3_symbol s)
Create a free (uninterpreted) type using the given name (symbol).
Z3_sort Z3_API Z3_mk_type_variable (Z3_context c, Z3_symbol s)
Create a type variable.
Z3_sort Z3_API Z3_mk_bool_sort (Z3_context c)
Create the Boolean type.
Z3_sort Z3_API Z3_mk_int_sort (Z3_context c)
Create the integer type.
Z3_sort Z3_API Z3_mk_real_sort (Z3_context c)
Create the real type.
Z3_sort Z3_API Z3_mk_bv_sort (Z3_context c, unsigned sz)
Create a bit-vector type of the given size.
Z3_sort Z3_API Z3_mk_finite_domain_sort (Z3_context c, Z3_symbol name, uint64_t size)
Create a named finite domain sort.
Z3_sort Z3_API Z3_mk_array_sort (Z3_context c, Z3_sort domain, Z3_sort range)
Create an array type.
Z3_sort Z3_API Z3_mk_array_sort_n (Z3_context c, unsigned n, Z3_sort const *domain, Z3_sort range)
Create an array type with N arguments.
Z3_sort Z3_API Z3_mk_tuple_sort (Z3_context c, Z3_symbol mk_tuple_name, unsigned num_fields, Z3_symbol const field_names[], Z3_sort const field_sorts[], Z3_func_decl *mk_tuple_decl, Z3_func_decl proj_decl[])
Create a tuple type.
Z3_sort Z3_API Z3_mk_enumeration_sort (Z3_context c, Z3_symbol name, unsigned n, Z3_symbol const enum_names[], Z3_func_decl enum_consts[], Z3_func_decl enum_testers[])
Create a enumeration sort.
Z3_sort Z3_API Z3_mk_list_sort (Z3_context c, Z3_symbol name, Z3_sort elem_sort, Z3_func_decl *nil_decl, Z3_func_decl *is_nil_decl, Z3_func_decl *cons_decl, Z3_func_decl *is_cons_decl, Z3_func_decl *head_decl, Z3_func_decl *tail_decl)
Create a list sort.
Z3_constructor Z3_API Z3_mk_constructor (Z3_context c, Z3_symbol name, Z3_symbol recognizer, unsigned num_fields, Z3_symbol const field_names[], Z3_sort const sorts[], unsigned sort_refs[])
Create a constructor.
unsigned Z3_API Z3_constructor_num_fields (Z3_context c, Z3_constructor constr)
Retrieve the number of fields of a constructor.
void Z3_API Z3_del_constructor (Z3_context c, Z3_constructor constr)
Reclaim memory allocated to constructor.
Z3_sort Z3_API Z3_mk_datatype (Z3_context c, Z3_symbol name, unsigned num_constructors, Z3_constructor constructors[])
Create datatype, such as lists, trees, records, enumerations or unions of records. The datatype may be recursive. Return the datatype sort.
Z3_sort Z3_API Z3_mk_polymorphic_datatype (Z3_context c, Z3_symbol name, unsigned num_parameters, Z3_sort parameters[], unsigned num_constructors, Z3_constructor constructors[])
Create a parametric datatype with explicit type parameters.
Z3_sort Z3_API Z3_mk_datatype_sort (Z3_context c, Z3_symbol name, unsigned num_params, Z3_sort const params[])
create a forward reference to a recursive datatype being declared. The forward reference can be used in a nested occurrence: the range of an array or as element sort of a sequence. The forward reference should only be used when used in an accessor for a recursive datatype that gets declared.
Z3_constructor_list Z3_API Z3_mk_constructor_list (Z3_context c, unsigned num_constructors, Z3_constructor const constructors[])
Create list of constructors.
void Z3_API Z3_del_constructor_list (Z3_context c, Z3_constructor_list clist)
Reclaim memory allocated for constructor list.
void Z3_API Z3_mk_datatypes (Z3_context c, unsigned num_sorts, Z3_symbol const sort_names[], Z3_sort sorts[], Z3_constructor_list constructor_lists[])
Create mutually recursive datatypes.
void Z3_API Z3_query_constructor (Z3_context c, Z3_constructor constr, unsigned num_fields, Z3_func_decl *constructor, Z3_func_decl *tester, Z3_func_decl accessors[])
Query constructor for declared functions.
Constants and Applications
Z3_func_decl Z3_API Z3_mk_func_decl (Z3_context c, Z3_symbol s, unsigned domain_size, Z3_sort const domain[], Z3_sort range)
Declare a constant or function.
Z3_ast Z3_API Z3_mk_app (Z3_context c, Z3_func_decl d, unsigned num_args, Z3_ast const args[])
Create a constant or function application.
Z3_ast Z3_API Z3_mk_const (Z3_context c, Z3_symbol s, Z3_sort ty)
Declare and create a constant.
Z3_func_decl Z3_API Z3_mk_fresh_func_decl (Z3_context c, Z3_string prefix, unsigned domain_size, Z3_sort const domain[], Z3_sort range)
Declare a fresh constant or function.
Z3_ast Z3_API Z3_mk_fresh_const (Z3_context c, Z3_string prefix, Z3_sort ty)
Declare and create a fresh constant.
Z3_func_decl Z3_API Z3_mk_rec_func_decl (Z3_context c, Z3_symbol s, unsigned domain_size, Z3_sort const domain[], Z3_sort range)
Declare a recursive function.
void Z3_API Z3_add_rec_def (Z3_context c, Z3_func_decl f, unsigned n, Z3_ast args[], Z3_ast body)
Define the body of a recursive function.
Propositional Logic and Equality
Z3_ast Z3_API Z3_mk_true (Z3_context c)
Create an AST node representing true.
Z3_ast Z3_API Z3_mk_false (Z3_context c)
Create an AST node representing false.
Z3_ast Z3_API Z3_mk_eq (Z3_context c, Z3_ast l, Z3_ast r)
Create an AST node representing l = r.
Z3_ast Z3_API Z3_mk_distinct (Z3_context c, unsigned num_args, Z3_ast const args[])
Create an AST node representing distinct(args[0], ..., args[num_args-1]).
Z3_ast Z3_API Z3_mk_not (Z3_context c, Z3_ast a)
Create an AST node representing not(a).
Z3_ast Z3_API Z3_mk_ite (Z3_context c, Z3_ast t1, Z3_ast t2, Z3_ast t3)
Create an AST node representing an if-then-else: ite(t1, t2, t3).
Z3_ast Z3_API Z3_mk_iff (Z3_context c, Z3_ast t1, Z3_ast t2)
Create an AST node representing t1 iff t2.
Z3_ast Z3_API Z3_mk_implies (Z3_context c, Z3_ast t1, Z3_ast t2)
Create an AST node representing t1 implies t2.
Z3_ast Z3_API Z3_mk_xor (Z3_context c, Z3_ast t1, Z3_ast t2)
Create an AST node representing t1 xor t2.
Z3_ast Z3_API Z3_mk_and (Z3_context c, unsigned num_args, Z3_ast const args[])
Create an AST node representing args[0] and ... and args[num_args-1].
Z3_ast Z3_API Z3_mk_or (Z3_context c, unsigned num_args, Z3_ast const args[])
Create an AST node representing args[0] or ... or args[num_args-1].
Integers and Reals
Z3_ast Z3_API Z3_mk_add (Z3_context c, unsigned num_args, Z3_ast const args[])
Create an AST node representing args[0] + ... + args[num_args-1].
Z3_ast Z3_API Z3_mk_mul (Z3_context c, unsigned num_args, Z3_ast const args[])
Create an AST node representing args[0] * ... * args[num_args-1].
Z3_ast Z3_API Z3_mk_sub (Z3_context c, unsigned num_args, Z3_ast const args[])
Create an AST node representing args[0] - ... - args[num_args - 1].
Z3_ast Z3_API Z3_mk_unary_minus (Z3_context c, Z3_ast arg)
Create an AST node representing - arg.
Z3_ast Z3_API Z3_mk_div (Z3_context c, Z3_ast arg1, Z3_ast arg2)
Create an AST node representing arg1 div arg2.
Z3_ast Z3_API Z3_mk_mod (Z3_context c, Z3_ast arg1, Z3_ast arg2)
Create an AST node representing arg1 mod arg2.
Z3_ast Z3_API Z3_mk_rem (Z3_context c, Z3_ast arg1, Z3_ast arg2)
Create an AST node representing arg1 rem arg2.
Z3_ast Z3_API Z3_mk_power (Z3_context c, Z3_ast arg1, Z3_ast arg2)
Create an AST node representing arg1 ^ arg2.
Z3_ast Z3_API Z3_mk_abs (Z3_context c, Z3_ast arg)
Take the absolute value of an integer.
Z3_ast Z3_API Z3_mk_lt (Z3_context c, Z3_ast t1, Z3_ast t2)
Create less than.
Z3_ast Z3_API Z3_mk_le (Z3_context c, Z3_ast t1, Z3_ast t2)
Create less than or equal to.
Z3_ast Z3_API Z3_mk_gt (Z3_context c, Z3_ast t1, Z3_ast t2)
Create greater than.
Z3_ast Z3_API Z3_mk_ge (Z3_context c, Z3_ast t1, Z3_ast t2)
Create greater than or equal to.
Z3_ast Z3_API Z3_mk_divides (Z3_context c, Z3_ast t1, Z3_ast t2)
Create division predicate.
Z3_ast Z3_API Z3_mk_int2real (Z3_context c, Z3_ast t1)
Coerce an integer to a real.
Z3_ast Z3_API Z3_mk_real2int (Z3_context c, Z3_ast t1)
Coerce a real to an integer.
Z3_ast Z3_API Z3_mk_is_int (Z3_context c, Z3_ast t1)
Check if a real number is an integer.
Bit-vectors
Z3_ast Z3_API Z3_mk_bvnot (Z3_context c, Z3_ast t1)
Bitwise negation.
Z3_ast Z3_API Z3_mk_bvredand (Z3_context c, Z3_ast t1)
Take conjunction of bits in vector, return vector of length 1.
Z3_ast Z3_API Z3_mk_bvredor (Z3_context c, Z3_ast t1)
Take disjunction of bits in vector, return vector of length 1.
Z3_ast Z3_API Z3_mk_bvand (Z3_context c, Z3_ast t1, Z3_ast t2)
Bitwise and.
Z3_ast Z3_API Z3_mk_bvor (Z3_context c, Z3_ast t1, Z3_ast t2)
Bitwise or.
Z3_ast Z3_API Z3_mk_bvxor (Z3_context c, Z3_ast t1, Z3_ast t2)
Bitwise exclusive-or.
Z3_ast Z3_API Z3_mk_bvnand (Z3_context c, Z3_ast t1, Z3_ast t2)
Bitwise nand.
Z3_ast Z3_API Z3_mk_bvnor (Z3_context c, Z3_ast t1, Z3_ast t2)
Bitwise nor.
Z3_ast Z3_API Z3_mk_bvxnor (Z3_context c, Z3_ast t1, Z3_ast t2)
Bitwise xnor.
Z3_ast Z3_API Z3_mk_bvneg (Z3_context c, Z3_ast t1)
Standard two's complement unary minus.
Z3_ast Z3_API Z3_mk_bvadd (Z3_context c, Z3_ast t1, Z3_ast t2)
Standard two's complement addition.
Z3_ast Z3_API Z3_mk_bvsub (Z3_context c, Z3_ast t1, Z3_ast t2)
Standard two's complement subtraction.
Z3_ast Z3_API Z3_mk_bvmul (Z3_context c, Z3_ast t1, Z3_ast t2)
Standard two's complement multiplication.
Z3_ast Z3_API Z3_mk_bvudiv (Z3_context c, Z3_ast t1, Z3_ast t2)
Unsigned division.
Z3_ast Z3_API Z3_mk_bvsdiv (Z3_context c, Z3_ast t1, Z3_ast t2)
Two's complement signed division.
Z3_ast Z3_API Z3_mk_bvurem (Z3_context c, Z3_ast t1, Z3_ast t2)
Unsigned remainder.
Z3_ast Z3_API Z3_mk_bvsrem (Z3_context c, Z3_ast t1, Z3_ast t2)
Two's complement signed remainder (sign follows dividend).
Z3_ast Z3_API Z3_mk_bvsmod (Z3_context c, Z3_ast t1, Z3_ast t2)
Two's complement signed remainder (sign follows divisor).
Z3_ast Z3_API Z3_mk_bvult (Z3_context c, Z3_ast t1, Z3_ast t2)
Unsigned less than.
Z3_ast Z3_API Z3_mk_bvslt (Z3_context c, Z3_ast t1, Z3_ast t2)
Two's complement signed less than.
Z3_ast Z3_API Z3_mk_bvule (Z3_context c, Z3_ast t1, Z3_ast t2)
Unsigned less than or equal to.
Z3_ast Z3_API Z3_mk_bvsle (Z3_context c, Z3_ast t1, Z3_ast t2)
Two's complement signed less than or equal to.
Z3_ast Z3_API Z3_mk_bvuge (Z3_context c, Z3_ast t1, Z3_ast t2)
Unsigned greater than or equal to.
Z3_ast Z3_API Z3_mk_bvsge (Z3_context c, Z3_ast t1, Z3_ast t2)
Two's complement signed greater than or equal to.
Z3_ast Z3_API Z3_mk_bvugt (Z3_context c, Z3_ast t1, Z3_ast t2)
Unsigned greater than.
Z3_ast Z3_API Z3_mk_bvsgt (Z3_context c, Z3_ast t1, Z3_ast t2)
Two's complement signed greater than.
Z3_ast Z3_API Z3_mk_concat (Z3_context c, Z3_ast t1, Z3_ast t2)
Concatenate the given bit-vectors.
Z3_ast Z3_API Z3_mk_extract (Z3_context c, unsigned high, unsigned low, Z3_ast t1)
Extract the bits high down to low from a bit-vector of size m to yield a new bit-vector of size n, where n = high - low + 1.
Z3_ast Z3_API Z3_mk_sign_ext (Z3_context c, unsigned i, Z3_ast t1)
Sign-extend of the given bit-vector to the (signed) equivalent bit-vector of size m+i, where m is the size of the given bit-vector.
Z3_ast Z3_API Z3_mk_zero_ext (Z3_context c, unsigned i, Z3_ast t1)
Extend the given bit-vector with zeros to the (unsigned) equivalent bit-vector of size m+i, where m is the size of the given bit-vector.
Z3_ast Z3_API Z3_mk_repeat (Z3_context c, unsigned i, Z3_ast t1)
Repeat the given bit-vector up length i.
Z3_ast Z3_API Z3_mk_bit2bool (Z3_context c, unsigned i, Z3_ast t1)
Extracts the bit at position i of a bit-vector and yields a boolean.
Z3_ast Z3_API Z3_mk_bvshl (Z3_context c, Z3_ast t1, Z3_ast t2)
Shift left.
Z3_ast Z3_API Z3_mk_bvlshr (Z3_context c, Z3_ast t1, Z3_ast t2)
Logical shift right.
Z3_ast Z3_API Z3_mk_bvashr (Z3_context c, Z3_ast t1, Z3_ast t2)
Arithmetic shift right.
Z3_ast Z3_API Z3_mk_rotate_left (Z3_context c, unsigned i, Z3_ast t1)
Rotate bits of t1 to the left i times.
Z3_ast Z3_API Z3_mk_rotate_right (Z3_context c, unsigned i, Z3_ast t1)
Rotate bits of t1 to the right i times.
Z3_ast Z3_API Z3_mk_ext_rotate_left (Z3_context c, Z3_ast t1, Z3_ast t2)
Rotate bits of t1 to the left t2 times.
Z3_ast Z3_API Z3_mk_ext_rotate_right (Z3_context c, Z3_ast t1, Z3_ast t2)
Rotate bits of t1 to the right t2 times.
Z3_ast Z3_API Z3_mk_int2bv (Z3_context c, unsigned n, Z3_ast t1)
Create an n bit bit-vector from the integer argument t1.
Z3_ast Z3_API Z3_mk_bv2int (Z3_context c, Z3_ast t1, bool is_signed)
Create an integer from the bit-vector argument t1. If is_signed is false, then the bit-vector t1 is treated as unsigned. So the result is non-negative and in the range [0..2^N-1], where N are the number of bits in t1. If is_signed is true, t1 is treated as a signed bit-vector.
Z3_ast Z3_API Z3_mk_bvadd_no_overflow (Z3_context c, Z3_ast t1, Z3_ast t2, bool is_signed)
Create a predicate that checks that the bit-wise addition of t1 and t2 does not overflow.
Z3_ast Z3_API Z3_mk_bvadd_no_underflow (Z3_context c, Z3_ast t1, Z3_ast t2)
Create a predicate that checks that the bit-wise signed addition of t1 and t2 does not underflow.
Z3_ast Z3_API Z3_mk_bvsub_no_overflow (Z3_context c, Z3_ast t1, Z3_ast t2)
Create a predicate that checks that the bit-wise signed subtraction of t1 and t2 does not overflow.
Z3_ast Z3_API Z3_mk_bvsub_no_underflow (Z3_context c, Z3_ast t1, Z3_ast t2, bool is_signed)
Create a predicate that checks that the bit-wise subtraction of t1 and t2 does not underflow.
Z3_ast Z3_API Z3_mk_bvsdiv_no_overflow (Z3_context c, Z3_ast t1, Z3_ast t2)
Create a predicate that checks that the bit-wise signed division of t1 and t2 does not overflow.
Z3_ast Z3_API Z3_mk_bvneg_no_overflow (Z3_context c, Z3_ast t1)
Check that bit-wise negation does not overflow when t1 is interpreted as a signed bit-vector.
Z3_ast Z3_API Z3_mk_bvmul_no_overflow (Z3_context c, Z3_ast t1, Z3_ast t2, bool is_signed)
Create a predicate that checks that the bit-wise multiplication of t1 and t2 does not overflow.
Z3_ast Z3_API Z3_mk_bvmul_no_underflow (Z3_context c, Z3_ast t1, Z3_ast t2)
Create a predicate that checks that the bit-wise signed multiplication of t1 and t2 does not underflow.
Arrays
Z3_ast Z3_API Z3_mk_select (Z3_context c, Z3_ast a, Z3_ast i)
Array read. The argument a is the array and i is the index of the array that gets read.
Z3_ast Z3_API Z3_mk_select_n (Z3_context c, Z3_ast a, unsigned n, Z3_ast const *idxs)
n-ary Array read. The argument a is the array and idxs are the indices of the array that gets read.
Z3_ast Z3_API Z3_mk_store (Z3_context c, Z3_ast a, Z3_ast i, Z3_ast v)
Array update.
Z3_ast Z3_API Z3_mk_store_n (Z3_context c, Z3_ast a, unsigned n, Z3_ast const *idxs, Z3_ast v)
n-ary Array update.
Z3_ast Z3_API Z3_mk_const_array (Z3_context c, Z3_sort domain, Z3_ast v)
Create the constant array.
Z3_ast Z3_API Z3_mk_map (Z3_context c, Z3_func_decl f, unsigned n, Z3_ast const *args)
Map f on the argument arrays.
Z3_ast Z3_API Z3_mk_array_default (Z3_context c, Z3_ast array)
Access the array default value. Produces the default range value, for arrays that can be represented as finite maps with a default range value.
Z3_ast Z3_API Z3_mk_as_array (Z3_context c, Z3_func_decl f)
Create array with the same interpretation as a function. The array satisfies the property (f x) = (select (_ as-array f) x) for every argument x.
Sets
Z3_sort Z3_API Z3_mk_set_sort (Z3_context c, Z3_sort ty)
Create Set type.
Z3_ast Z3_API Z3_mk_empty_set (Z3_context c, Z3_sort domain)
Create the empty set.
Z3_ast Z3_API Z3_mk_full_set (Z3_context c, Z3_sort domain)
Create the full set.
Z3_ast Z3_API Z3_mk_set_add (Z3_context c, Z3_ast set, Z3_ast elem)
Add an element to a set.
Z3_ast Z3_API Z3_mk_set_del (Z3_context c, Z3_ast set, Z3_ast elem)
Remove an element to a set.
Z3_ast Z3_API Z3_mk_set_union (Z3_context c, unsigned num_args, Z3_ast const args[])
Take the union of a list of sets.
Z3_ast Z3_API Z3_mk_set_intersect (Z3_context c, unsigned num_args, Z3_ast const args[])
Take the intersection of a list of sets.
Z3_ast Z3_API Z3_mk_set_difference (Z3_context c, Z3_ast arg1, Z3_ast arg2)
Take the set difference between two sets.
Z3_ast Z3_API Z3_mk_set_complement (Z3_context c, Z3_ast arg)
Take the complement of a set.
Z3_ast Z3_API Z3_mk_set_member (Z3_context c, Z3_ast elem, Z3_ast set)
Check for set membership.
Z3_ast Z3_API Z3_mk_set_subset (Z3_context c, Z3_ast arg1, Z3_ast arg2)
Check for subsetness of sets.
Z3_ast Z3_API Z3_mk_array_ext (Z3_context c, Z3_ast arg1, Z3_ast arg2)
Create array extensionality index given two arrays with the same sort. The meaning is given by the axiom: (=> (= (select A (array-ext A B)) (select B (array-ext A B))) (= A B))
Numerals
Z3_ast Z3_API Z3_mk_numeral (Z3_context c, Z3_string numeral, Z3_sort ty)
Create a numeral of a given sort.
Z3_ast Z3_API Z3_mk_real (Z3_context c, int num, int den)
Create a real from a fraction.
Z3_ast Z3_API Z3_mk_real_int64 (Z3_context c, int64_t num, int64_t den)
Create a real from a fraction of int64.
Z3_ast Z3_API Z3_mk_int (Z3_context c, int v, Z3_sort ty)
Create a numeral of an int, bit-vector, or finite-domain sort.
Z3_ast Z3_API Z3_mk_unsigned_int (Z3_context c, unsigned v, Z3_sort ty)
Create a numeral of a int, bit-vector, or finite-domain sort.
Z3_ast Z3_API Z3_mk_int64 (Z3_context c, int64_t v, Z3_sort ty)
Create a numeral of a int, bit-vector, or finite-domain sort.
Z3_ast Z3_API Z3_mk_unsigned_int64 (Z3_context c, uint64_t v, Z3_sort ty)
Create a numeral of a int, bit-vector, or finite-domain sort.
Z3_ast Z3_API Z3_mk_bv_numeral (Z3_context c, unsigned sz, bool const *bits)
create a bit-vector numeral from a vector of Booleans.
Sequences and regular expressions
Z3_sort Z3_API Z3_mk_seq_sort (Z3_context c, Z3_sort s)
Create a sequence sort out of the sort for the elements.
bool Z3_API Z3_is_seq_sort (Z3_context c, Z3_sort s)
Check if s is a sequence sort.
Z3_sort Z3_API Z3_get_seq_sort_basis (Z3_context c, Z3_sort s)
Retrieve basis sort for sequence sort.
Z3_sort Z3_API Z3_mk_re_sort (Z3_context c, Z3_sort seq)
Create a regular expression sort out of a sequence sort.
bool Z3_API Z3_is_re_sort (Z3_context c, Z3_sort s)
Check if s is a regular expression sort.
Z3_sort Z3_API Z3_get_re_sort_basis (Z3_context c, Z3_sort s)
Retrieve basis sort for regex sort.
Z3_sort Z3_API Z3_mk_string_sort (Z3_context c)
Create a sort for unicode strings.
Z3_sort Z3_API Z3_mk_char_sort (Z3_context c)
Create a sort for unicode characters.
bool Z3_API Z3_is_string_sort (Z3_context c, Z3_sort s)
Check if s is a string sort.
bool Z3_API Z3_is_char_sort (Z3_context c, Z3_sort s)
Check if s is a character sort.
Z3_ast Z3_API Z3_mk_string (Z3_context c, Z3_string s)
Create a string constant out of the string that is passed in The string may contain escape encoding for non-printable characters or characters outside of the basic printable ASCII range. For example, the escape encoding \u{0} represents the character 0 and the encoding \u{100} represents the character 256.
Z3_ast Z3_API Z3_mk_lstring (Z3_context c, unsigned len, Z3_string s)
Create a string constant out of the string that is passed in It takes the length of the string as well to take into account 0 characters. The string is treated as if it is unescaped so a sequence of characters \u{0} is treated as 5 characters and not the character 0.
Z3_ast Z3_API Z3_mk_u32string (Z3_context c, unsigned len, unsigned const chars[])
Create a string constant out of the string that is passed in It takes the length of the string as well to take into account 0 characters. The string is unescaped.
bool Z3_API Z3_is_string (Z3_context c, Z3_ast s)
Determine if s is a string constant.
Z3_string Z3_API Z3_get_string (Z3_context c, Z3_ast s)
Retrieve the string constant stored in s. Characters outside the basic printable ASCII range are escaped.
Z3_char_ptr Z3_API Z3_get_lstring (Z3_context c, Z3_ast s, unsigned *length)
Retrieve the string constant stored in s. The string can contain escape sequences. Characters in the range 1 to 255 are literal. Characters in the range 0, and 256 above are escaped.
unsigned Z3_API Z3_get_string_length (Z3_context c, Z3_ast s)
Retrieve the length of the unescaped string constant stored in s.
void Z3_API Z3_get_string_contents (Z3_context c, Z3_ast s, unsigned length, unsigned contents[])
Retrieve the unescaped string constant stored in s.
Z3_ast Z3_API Z3_mk_seq_empty (Z3_context c, Z3_sort seq)
Create an empty sequence of the sequence sort seq.
Z3_ast Z3_API Z3_mk_seq_unit (Z3_context c, Z3_ast a)
Create a unit sequence of a.
Z3_ast Z3_API Z3_mk_seq_concat (Z3_context c, unsigned n, Z3_ast const args[])
Concatenate sequences.
Z3_ast Z3_API Z3_mk_seq_prefix (Z3_context c, Z3_ast prefix, Z3_ast s)
Check if prefix is a prefix of s.
Z3_ast Z3_API Z3_mk_seq_suffix (Z3_context c, Z3_ast suffix, Z3_ast s)
Check if suffix is a suffix of s.
Z3_ast Z3_API Z3_mk_seq_contains (Z3_context c, Z3_ast container, Z3_ast containee)
Check if container contains containee.
Z3_ast Z3_API Z3_mk_str_lt (Z3_context c, Z3_ast prefix, Z3_ast s)
Check if s1 is lexicographically strictly less than s2.
Z3_ast Z3_API Z3_mk_str_le (Z3_context c, Z3_ast prefix, Z3_ast s)
Check if s1 is equal or lexicographically strictly less than s2.
Z3_ast Z3_API Z3_mk_seq_extract (Z3_context c, Z3_ast s, Z3_ast offset, Z3_ast length)
Extract subsequence starting at offset of length.
Z3_ast Z3_API Z3_mk_seq_replace (Z3_context c, Z3_ast s, Z3_ast src, Z3_ast dst)
Replace the first occurrence of src with dst in s.
Z3_ast Z3_API Z3_mk_seq_replace_all (Z3_context c, Z3_ast s, Z3_ast src, Z3_ast dst)
Replace all occurrences of src with dst in s.
Z3_ast Z3_API Z3_mk_seq_replace_re (Z3_context c, Z3_ast s, Z3_ast re, Z3_ast dst)
Replace the first occurrence of regular expression re with dst in s.
Z3_ast Z3_API Z3_mk_seq_replace_re_all (Z3_context c, Z3_ast s, Z3_ast re, Z3_ast dst)
Replace all occurrences of regular expression re with dst in s.
Z3_ast Z3_API Z3_mk_seq_at (Z3_context c, Z3_ast s, Z3_ast index)
Retrieve from s the unit sequence positioned at position index. The sequence is empty if the index is out of bounds.
Z3_ast Z3_API Z3_mk_seq_nth (Z3_context c, Z3_ast s, Z3_ast index)
Retrieve from s the element positioned at position index. The function is under-specified if the index is out of bounds.
Z3_ast Z3_API Z3_mk_seq_length (Z3_context c, Z3_ast s)
Return the length of the sequence s.
Z3_ast Z3_API Z3_mk_seq_index (Z3_context c, Z3_ast s, Z3_ast substr, Z3_ast offset)
Return index of the first occurrence of substr in s starting from offset offset. If s does not contain substr, then the value is -1, if offset is the length of s, then the value is -1 as well. The value is -1 if offset is negative or larger than the length of s.
Z3_ast Z3_API Z3_mk_seq_last_index (Z3_context c, Z3_ast s, Z3_ast substr)
Return index of the last occurrence of substr in s. If s does not contain substr, then the value is -1,.
Z3_ast Z3_API Z3_mk_seq_map (Z3_context c, Z3_ast f, Z3_ast s)
Create a map of the function f over the sequence s.
Z3_ast Z3_API Z3_mk_seq_mapi (Z3_context c, Z3_ast f, Z3_ast i, Z3_ast s)
Create a map of the function f over the sequence s starting at index i.
Z3_ast Z3_API Z3_mk_seq_foldl (Z3_context c, Z3_ast f, Z3_ast a, Z3_ast s)
Create a fold of the function f over the sequence s with accumulator a.
Z3_ast Z3_API Z3_mk_seq_foldli (Z3_context c, Z3_ast f, Z3_ast i, Z3_ast a, Z3_ast s)
Create a fold with index tracking of the function f over the sequence s with accumulator a starting at index i.
Z3_ast Z3_API Z3_mk_str_to_int (Z3_context c, Z3_ast s)
Convert string to integer.
Z3_ast Z3_API Z3_mk_int_to_str (Z3_context c, Z3_ast s)
Integer to string conversion.
Z3_ast Z3_API Z3_mk_string_to_code (Z3_context c, Z3_ast a)
String to code conversion.
Z3_ast Z3_API Z3_mk_string_from_code (Z3_context c, Z3_ast a)
Code to string conversion.
Z3_ast Z3_API Z3_mk_ubv_to_str (Z3_context c, Z3_ast s)
Unsigned bit-vector to string conversion.
Z3_ast Z3_API Z3_mk_sbv_to_str (Z3_context c, Z3_ast s)
Signed bit-vector to string conversion.
Z3_ast Z3_API Z3_mk_seq_to_re (Z3_context c, Z3_ast seq)
Create a regular expression that accepts the sequence seq.
Z3_ast Z3_API Z3_mk_seq_in_re (Z3_context c, Z3_ast seq, Z3_ast re)
Check if seq is in the language generated by the regular expression re.
Z3_ast Z3_API Z3_mk_re_plus (Z3_context c, Z3_ast re)
Create the regular language re+.
Z3_ast Z3_API Z3_mk_re_star (Z3_context c, Z3_ast re)
Create the regular language re*.
Z3_ast Z3_API Z3_mk_re_option (Z3_context c, Z3_ast re)
Create the regular language [re].
Z3_ast Z3_API Z3_mk_re_union (Z3_context c, unsigned n, Z3_ast const args[])
Create the union of the regular languages.
Z3_ast Z3_API Z3_mk_re_concat (Z3_context c, unsigned n, Z3_ast const args[])
Create the concatenation of the regular languages.
Z3_ast Z3_API Z3_mk_re_range (Z3_context c, Z3_ast lo, Z3_ast hi)
Create the range regular expression over two sequences of length 1.
Z3_ast Z3_API Z3_mk_re_allchar (Z3_context c, Z3_sort regex_sort)
Create a regular expression that accepts all singleton sequences of the regular expression sort.
Z3_ast Z3_API Z3_mk_re_loop (Z3_context c, Z3_ast r, unsigned lo, unsigned hi)
Create a regular expression loop. The supplied regular expression r is repeated between lo and hi times. The lo should be below hi with one exception: when supplying the value hi as 0, the meaning is to repeat the argument r at least lo number of times, and with an unbounded upper bound.
Z3_ast Z3_API Z3_mk_re_power (Z3_context c, Z3_ast re, unsigned n)
Create a power regular expression.
Z3_ast Z3_API Z3_mk_re_intersect (Z3_context c, unsigned n, Z3_ast const args[])
Create the intersection of the regular languages.
Z3_ast Z3_API Z3_mk_re_complement (Z3_context c, Z3_ast re)
Create the complement of the regular language re.
Z3_ast Z3_API Z3_mk_re_diff (Z3_context c, Z3_ast re1, Z3_ast re2)
Create the difference of regular expressions.
Z3_ast Z3_API Z3_mk_re_empty (Z3_context c, Z3_sort re)
Create an empty regular expression of sort re.
Z3_ast Z3_API Z3_mk_re_full (Z3_context c, Z3_sort re)
Create an universal regular expression of sort re.
Z3_ast Z3_API Z3_mk_char (Z3_context c, unsigned ch)
Create a character literal.
Z3_ast Z3_API Z3_mk_char_le (Z3_context c, Z3_ast ch1, Z3_ast ch2)
Create less than or equal to between two characters.
Z3_ast Z3_API Z3_mk_char_to_int (Z3_context c, Z3_ast ch)
Create an integer (code point) from character.
Z3_ast Z3_API Z3_mk_char_to_bv (Z3_context c, Z3_ast ch)
Create a bit-vector (code point) from character.
Z3_ast Z3_API Z3_mk_char_from_bv (Z3_context c, Z3_ast bv)
Create a character from a bit-vector (code point).
Z3_ast Z3_API Z3_mk_char_is_digit (Z3_context c, Z3_ast ch)
Create a check if the character is a digit.
Special relations
Z3_func_decl Z3_API Z3_mk_linear_order (Z3_context c, Z3_sort a, unsigned id)
create a linear ordering relation over signature a. The relation is identified by the index id.
Z3_func_decl Z3_API Z3_mk_partial_order (Z3_context c, Z3_sort a, unsigned id)
create a partial ordering relation over signature a and index id.
Z3_func_decl Z3_API Z3_mk_piecewise_linear_order (Z3_context c, Z3_sort a, unsigned id)
create a piecewise linear ordering relation over signature a and index id.
Z3_func_decl Z3_API Z3_mk_tree_order (Z3_context c, Z3_sort a, unsigned id)
create a tree ordering relation over signature a identified using index id.
Z3_func_decl Z3_API Z3_mk_transitive_closure (Z3_context c, Z3_func_decl f)
create transitive closure of binary relation.
Quantifiers
Z3_pattern Z3_API Z3_mk_pattern (Z3_context c, unsigned num_patterns, Z3_ast const terms[])
Create a pattern for quantifier instantiation.
Z3_ast Z3_API Z3_mk_bound (Z3_context c, unsigned index, Z3_sort ty)
Create a variable.
Z3_ast Z3_API Z3_mk_forall (Z3_context c, unsigned weight, unsigned num_patterns, Z3_pattern const patterns[], unsigned num_decls, Z3_sort const sorts[], Z3_symbol const decl_names[], Z3_ast body)
Create a forall formula. It takes an expression body that contains bound variables of the same sorts as the sorts listed in the array sorts. The bound variables are de-Bruijn indices created using Z3_mk_bound. The array decl_names contains the names that the quantified formula uses for the bound variables. Z3 applies the convention that the last element in the decl_names and sorts array refers to the variable with index 0, the second to last element of decl_names and sorts refers to the variable with index 1, etc.
Z3_ast Z3_API Z3_mk_exists (Z3_context c, unsigned weight, unsigned num_patterns, Z3_pattern const patterns[], unsigned num_decls, Z3_sort const sorts[], Z3_symbol const decl_names[], Z3_ast body)
Create an exists formula. Similar to Z3_mk_forall.
Z3_ast Z3_API Z3_mk_quantifier (Z3_context c, bool is_forall, unsigned weight, unsigned num_patterns, Z3_pattern const patterns[], unsigned num_decls, Z3_sort const sorts[], Z3_symbol const decl_names[], Z3_ast body)
Create a quantifier - universal or existential, with pattern hints. See the documentation for Z3_mk_forall for an explanation of the parameters.
Z3_ast Z3_API Z3_mk_quantifier_ex (Z3_context c, bool is_forall, unsigned weight, Z3_symbol quantifier_id, Z3_symbol skolem_id, unsigned num_patterns, Z3_pattern const patterns[], unsigned num_no_patterns, Z3_ast const no_patterns[], unsigned num_decls, Z3_sort const sorts[], Z3_symbol const decl_names[], Z3_ast body)
Create a quantifier - universal or existential, with pattern hints, no patterns, and attributes.
Z3_ast Z3_API Z3_mk_forall_const (Z3_context c, unsigned weight, unsigned num_bound, Z3_app const bound[], unsigned num_patterns, Z3_pattern const patterns[], Z3_ast body)
Create a universal quantifier using a list of constants that will form the set of bound variables.
Z3_ast Z3_API Z3_mk_exists_const (Z3_context c, unsigned weight, unsigned num_bound, Z3_app const bound[], unsigned num_patterns, Z3_pattern const patterns[], Z3_ast body)
Similar to Z3_mk_forall_const.
Z3_ast Z3_API Z3_mk_quantifier_const (Z3_context c, bool is_forall, unsigned weight, unsigned num_bound, Z3_app const bound[], unsigned num_patterns, Z3_pattern const patterns[], Z3_ast body)
Create a universal or existential quantifier using a list of constants that will form the set of bound variables.
Z3_ast Z3_API Z3_mk_quantifier_const_ex (Z3_context c, bool is_forall, unsigned weight, Z3_symbol quantifier_id, Z3_symbol skolem_id, unsigned num_bound, Z3_app const bound[], unsigned num_patterns, Z3_pattern const patterns[], unsigned num_no_patterns, Z3_ast const no_patterns[], Z3_ast body)
Create a universal or existential quantifier using a list of constants that will form the set of bound variables.
Z3_ast Z3_API Z3_mk_lambda (Z3_context c, unsigned num_decls, Z3_sort const sorts[], Z3_symbol const decl_names[], Z3_ast body)
Create a lambda expression. It takes an expression body that contains bound variables of the same sorts as the sorts listed in the array sorts. The bound variables are de-Bruijn indices created using Z3_mk_bound. The array decl_names contains the names that the quantified formula uses for the bound variables. Z3 applies the convention that the last element in the decl_names and sorts array refers to the variable with index 0, the second to last element of decl_names and sorts refers to the variable with index 1, etc. The sort of the resulting expression is (Array sorts range) where range is the sort of body. For example, if the lambda binds two variables of sort Int and Bool, and the body has sort Real, the sort of the expression is (Array Int Bool Real).
Z3_ast Z3_API Z3_mk_lambda_const (Z3_context c, unsigned num_bound, Z3_app const bound[], Z3_ast body)
Create a lambda expression using a list of constants that form the set of bound variables.
Accessors
Z3_symbol_kind Z3_API Z3_get_symbol_kind (Z3_context c, Z3_symbol s)
Return Z3_INT_SYMBOL if the symbol was constructed using Z3_mk_int_symbol, and Z3_STRING_SYMBOL if the symbol was constructed using Z3_mk_string_symbol.
int Z3_API Z3_get_symbol_int (Z3_context c, Z3_symbol s)
Return the symbol int value.
Z3_string Z3_API Z3_get_symbol_string (Z3_context c, Z3_symbol s)
Return the symbol name.
Z3_symbol Z3_API Z3_get_sort_name (Z3_context c, Z3_sort d)
Return the sort name as a symbol.
unsigned Z3_API Z3_get_sort_id (Z3_context c, Z3_sort s)
Return a unique identifier for s.
Z3_ast Z3_API Z3_sort_to_ast (Z3_context c, Z3_sort s)
Convert a Z3_sort into Z3_ast. This is just type casting.
bool Z3_API Z3_is_eq_sort (Z3_context c, Z3_sort s1, Z3_sort s2)
compare sorts.
Z3_sort_kind Z3_API Z3_get_sort_kind (Z3_context c, Z3_sort t)
Return the sort kind (e.g., array, tuple, int, bool, etc).
unsigned Z3_API Z3_get_bv_sort_size (Z3_context c, Z3_sort t)
Return the size of the given bit-vector sort.
bool Z3_API Z3_get_finite_domain_sort_size (Z3_context c, Z3_sort s, uint64_t *r)
Store the size of the sort in r. Return false if the call failed. That is, Z3_get_sort_kind(s) == Z3_FINITE_DOMAIN_SORT.
unsigned Z3_API Z3_get_array_arity (Z3_context c, Z3_sort s)
Return the arity (number of dimensions) of the given array sort.
Z3_sort Z3_API Z3_get_array_sort_domain (Z3_context c, Z3_sort t)
Return the domain of the given array sort. In the case of a multi-dimensional array, this function returns the sort of the first dimension.
Z3_sort Z3_API Z3_get_array_sort_domain_n (Z3_context c, Z3_sort t, unsigned idx)
Return the i'th domain sort of an n-dimensional array.
Z3_sort Z3_API Z3_get_array_sort_range (Z3_context c, Z3_sort t)
Return the range of the given array sort.
Z3_func_decl Z3_API Z3_get_tuple_sort_mk_decl (Z3_context c, Z3_sort t)
Return the constructor declaration of the given tuple sort.
unsigned Z3_API Z3_get_tuple_sort_num_fields (Z3_context c, Z3_sort t)
Return the number of fields of the given tuple sort.
Z3_func_decl Z3_API Z3_get_tuple_sort_field_decl (Z3_context c, Z3_sort t, unsigned i)
Return the i-th field declaration (i.e., projection function declaration) of the given tuple sort.
bool Z3_API Z3_is_recursive_datatype_sort (Z3_context c, Z3_sort s)
Check if s is a recursive datatype sort.
unsigned Z3_API Z3_get_datatype_sort_num_constructors (Z3_context c, Z3_sort t)
Return number of constructors for datatype.
Z3_func_decl Z3_API Z3_get_datatype_sort_constructor (Z3_context c, Z3_sort t, unsigned idx)
Return idx'th constructor.
Z3_func_decl Z3_API Z3_get_datatype_sort_recognizer (Z3_context c, Z3_sort t, unsigned idx)
Return idx'th recognizer.
Z3_func_decl Z3_API Z3_get_datatype_sort_constructor_accessor (Z3_context c, Z3_sort t, unsigned idx_c, unsigned idx_a)
Return idx_a'th accessor for the idx_c'th constructor.
Z3_ast Z3_API Z3_datatype_update_field (Z3_context c, Z3_func_decl field_access, Z3_ast t, Z3_ast value)
Update record field with a value.
unsigned Z3_API Z3_get_relation_arity (Z3_context c, Z3_sort s)
Return arity of relation.
Z3_sort Z3_API Z3_get_relation_column (Z3_context c, Z3_sort s, unsigned col)
Return sort at i'th column of relation sort.
Z3_ast Z3_API Z3_mk_atmost (Z3_context c, unsigned num_args, Z3_ast const args[], unsigned k)
Pseudo-Boolean relations.
Z3_ast Z3_API Z3_mk_atleast (Z3_context c, unsigned num_args, Z3_ast const args[], unsigned k)
Pseudo-Boolean relations.
Z3_ast Z3_API Z3_mk_pble (Z3_context c, unsigned num_args, Z3_ast const args[], int const coeffs[], int k)
Pseudo-Boolean relations.
Z3_ast Z3_API Z3_mk_pbge (Z3_context c, unsigned num_args, Z3_ast const args[], int const coeffs[], int k)
Pseudo-Boolean relations.
Z3_ast Z3_API Z3_mk_pbeq (Z3_context c, unsigned num_args, Z3_ast const args[], int const coeffs[], int k)
Pseudo-Boolean relations.
Z3_ast Z3_API Z3_func_decl_to_ast (Z3_context c, Z3_func_decl f)
Convert a Z3_func_decl into Z3_ast. This is just type casting.
bool Z3_API Z3_is_eq_func_decl (Z3_context c, Z3_func_decl f1, Z3_func_decl f2)
Compare terms.
unsigned Z3_API Z3_get_func_decl_id (Z3_context c, Z3_func_decl f)
Return a unique identifier for f.
Z3_symbol Z3_API Z3_get_decl_name (Z3_context c, Z3_func_decl d)
Return the constant declaration name as a symbol.
Z3_decl_kind Z3_API Z3_get_decl_kind (Z3_context c, Z3_func_decl d)
Return declaration kind corresponding to declaration.
unsigned Z3_API Z3_get_domain_size (Z3_context c, Z3_func_decl d)
Return the number of parameters of the given declaration.
unsigned Z3_API Z3_get_arity (Z3_context c, Z3_func_decl d)
Alias for Z3_get_domain_size.
Z3_sort Z3_API Z3_get_domain (Z3_context c, Z3_func_decl d, unsigned i)
Return the sort of the i-th parameter of the given function declaration.
Z3_sort Z3_API Z3_get_range (Z3_context c, Z3_func_decl d)
Return the range of the given declaration.
unsigned Z3_API Z3_get_decl_num_parameters (Z3_context c, Z3_func_decl d)
Return the number of parameters associated with a declaration.
Z3_parameter_kind Z3_API Z3_get_decl_parameter_kind (Z3_context c, Z3_func_decl d, unsigned idx)
Return the parameter type associated with a declaration.
int Z3_API Z3_get_decl_int_parameter (Z3_context c, Z3_func_decl d, unsigned idx)
Return the integer value associated with an integer parameter.
double Z3_API Z3_get_decl_double_parameter (Z3_context c, Z3_func_decl d, unsigned idx)
Return the double value associated with an double parameter.
Z3_symbol Z3_API Z3_get_decl_symbol_parameter (Z3_context c, Z3_func_decl d, unsigned idx)
Return the double value associated with an double parameter.
Z3_sort Z3_API Z3_get_decl_sort_parameter (Z3_context c, Z3_func_decl d, unsigned idx)
Return the sort value associated with a sort parameter.
Z3_ast Z3_API Z3_get_decl_ast_parameter (Z3_context c, Z3_func_decl d, unsigned idx)
Return the expression value associated with an expression parameter.
Z3_func_decl Z3_API Z3_get_decl_func_decl_parameter (Z3_context c, Z3_func_decl d, unsigned idx)
Return the expression value associated with an expression parameter.
Z3_string Z3_API Z3_get_decl_rational_parameter (Z3_context c, Z3_func_decl d, unsigned idx)
Return the rational value, as a string, associated with a rational parameter.
Z3_ast Z3_API Z3_app_to_ast (Z3_context c, Z3_app a)
Convert a Z3_app into Z3_ast. This is just type casting.
Z3_func_decl Z3_API Z3_get_app_decl (Z3_context c, Z3_app a)
Return the declaration of a constant or function application.
unsigned Z3_API Z3_get_app_num_args (Z3_context c, Z3_app a)
Return the number of argument of an application. If t is an constant, then the number of arguments is 0.
Z3_ast Z3_API Z3_get_app_arg (Z3_context c, Z3_app a, unsigned i)
Return the i-th argument of the given application.
bool Z3_API Z3_is_eq_ast (Z3_context c, Z3_ast t1, Z3_ast t2)
Compare terms.
unsigned Z3_API Z3_get_ast_id (Z3_context c, Z3_ast t)
Return a unique identifier for t. The identifier is unique up to structural equality. Thus, two ast nodes created by the same context and having the same children and same function symbols have the same identifiers. Ast nodes created in the same context, but having different children or different functions have different identifiers. Variables and quantifiers are also assigned different identifiers according to their structure.
unsigned Z3_API Z3_get_ast_hash (Z3_context c, Z3_ast a)
Return a hash code for the given AST. The hash code is structural but two different AST objects can map to the same hash. The result of Z3_get_ast_id returns an identifier that is unique over the set of live AST objects.
Z3_sort Z3_API Z3_get_sort (Z3_context c, Z3_ast a)
Return the sort of an AST node.
bool Z3_API Z3_is_well_sorted (Z3_context c, Z3_ast t)
Return true if the given expression t is well sorted.
Z3_lbool Z3_API Z3_get_bool_value (Z3_context c, Z3_ast a)
Return Z3_L_TRUE if a is true, Z3_L_FALSE if it is false, and Z3_L_UNDEF otherwise.
Z3_ast_kind Z3_API Z3_get_ast_kind (Z3_context c, Z3_ast a)
Return the kind of the given AST.
bool Z3_API Z3_is_app (Z3_context c, Z3_ast a)
bool Z3_API Z3_is_ground (Z3_context c, Z3_ast a)
unsigned Z3_API Z3_get_depth (Z3_context c, Z3_ast a)
bool Z3_API Z3_is_numeral_ast (Z3_context c, Z3_ast a)
bool Z3_API Z3_is_algebraic_number (Z3_context c, Z3_ast a)
Return true if the given AST is a real algebraic number.
Z3_app Z3_API Z3_to_app (Z3_context c, Z3_ast a)
Convert an ast into an APP_AST. This is just type casting.
Z3_func_decl Z3_API Z3_to_func_decl (Z3_context c, Z3_ast a)
Convert an AST into a FUNC_DECL_AST. This is just type casting.
Z3_string Z3_API Z3_get_numeral_string (Z3_context c, Z3_ast a)
Return numeral value, as a decimal string of a numeric constant term.
Z3_string Z3_API Z3_get_numeral_binary_string (Z3_context c, Z3_ast a)
Return numeral value, as a binary string of a numeric constant term.
Z3_string Z3_API Z3_get_numeral_decimal_string (Z3_context c, Z3_ast a, unsigned precision)
Return numeral as a string in decimal notation. The result has at most precision decimal places.
double Z3_API Z3_get_numeral_double (Z3_context c, Z3_ast a)
Return numeral as a double.
Z3_ast Z3_API Z3_get_numerator (Z3_context c, Z3_ast a)
Return the numerator (as a numeral AST) of a numeral AST of sort Real.
Z3_ast Z3_API Z3_get_denominator (Z3_context c, Z3_ast a)
Return the denominator (as a numeral AST) of a numeral AST of sort Real.
bool Z3_API Z3_get_numeral_small (Z3_context c, Z3_ast a, int64_t *num, int64_t *den)
Return numeral value, as a pair of 64 bit numbers if the representation fits.
bool Z3_API Z3_get_numeral_int (Z3_context c, Z3_ast v, int *i)
Similar to Z3_get_numeral_string, but only succeeds if the value can fit in a machine int. Return true if the call succeeded.
bool Z3_API Z3_get_numeral_uint (Z3_context c, Z3_ast v, unsigned *u)
Similar to Z3_get_numeral_string, but only succeeds if the value can fit in a machine unsigned int. Return true if the call succeeded.
bool Z3_API Z3_get_numeral_uint64 (Z3_context c, Z3_ast v, uint64_t *u)
Similar to Z3_get_numeral_string, but only succeeds if the value can fit in a machine uint64_t int. Return true if the call succeeded.
bool Z3_API Z3_get_numeral_int64 (Z3_context c, Z3_ast v, int64_t *i)
Similar to Z3_get_numeral_string, but only succeeds if the value can fit in a machine int64_t int. Return true if the call succeeded.
bool Z3_API Z3_get_numeral_rational_int64 (Z3_context c, Z3_ast v, int64_t *num, int64_t *den)
Similar to Z3_get_numeral_string, but only succeeds if the value can fit as a rational number as machine int64_t int. Return true if the call succeeded.
Z3_ast Z3_API Z3_get_algebraic_number_lower (Z3_context c, Z3_ast a, unsigned precision)
Return a lower bound for the given real algebraic number. The interval isolating the number is smaller than 1/10^precision. The result is a numeral AST of sort Real.
Z3_ast Z3_API Z3_get_algebraic_number_upper (Z3_context c, Z3_ast a, unsigned precision)
Return a upper bound for the given real algebraic number. The interval isolating the number is smaller than 1/10^precision. The result is a numeral AST of sort Real.
Z3_ast Z3_API Z3_pattern_to_ast (Z3_context c, Z3_pattern p)
Convert a Z3_pattern into Z3_ast. This is just type casting.
unsigned Z3_API Z3_get_pattern_num_terms (Z3_context c, Z3_pattern p)
Return number of terms in pattern.
Z3_ast Z3_API Z3_get_pattern (Z3_context c, Z3_pattern p, unsigned idx)
Return i'th ast in pattern.
unsigned Z3_API Z3_get_index_value (Z3_context c, Z3_ast a)
Return index of de-Bruijn bound variable.
bool Z3_API Z3_is_quantifier_forall (Z3_context c, Z3_ast a)
Determine if an ast is a universal quantifier.
bool Z3_API Z3_is_quantifier_exists (Z3_context c, Z3_ast a)
Determine if ast is an existential quantifier.
bool Z3_API Z3_is_lambda (Z3_context c, Z3_ast a)
Determine if ast is a lambda expression.
unsigned Z3_API Z3_get_quantifier_weight (Z3_context c, Z3_ast a)
Obtain weight of quantifier.
Z3_symbol Z3_API Z3_get_quantifier_skolem_id (Z3_context c, Z3_ast a)
Obtain skolem id of quantifier.
Z3_symbol Z3_API Z3_get_quantifier_id (Z3_context c, Z3_ast a)
Obtain id of quantifier.
unsigned Z3_API Z3_get_quantifier_num_patterns (Z3_context c, Z3_ast a)
Return number of patterns used in quantifier.
Z3_pattern Z3_API Z3_get_quantifier_pattern_ast (Z3_context c, Z3_ast a, unsigned i)
Return i'th pattern.
unsigned Z3_API Z3_get_quantifier_num_no_patterns (Z3_context c, Z3_ast a)
Return number of no_patterns used in quantifier.
Z3_ast Z3_API Z3_get_quantifier_no_pattern_ast (Z3_context c, Z3_ast a, unsigned i)
Return i'th no_pattern.
unsigned Z3_API Z3_get_quantifier_num_bound (Z3_context c, Z3_ast a)
Return number of bound variables of quantifier.
Z3_symbol Z3_API Z3_get_quantifier_bound_name (Z3_context c, Z3_ast a, unsigned i)
Return symbol of the i'th bound variable.
Z3_sort Z3_API Z3_get_quantifier_bound_sort (Z3_context c, Z3_ast a, unsigned i)
Return sort of the i'th bound variable.
Z3_ast Z3_API Z3_get_quantifier_body (Z3_context c, Z3_ast a)
Return body of quantifier.
Z3_ast Z3_API Z3_simplify (Z3_context c, Z3_ast a)
Interface to simplifier.
Z3_ast Z3_API Z3_simplify_ex (Z3_context c, Z3_ast a, Z3_params p)
Interface to simplifier.
Z3_string Z3_API Z3_simplify_get_help (Z3_context c)
Return a string describing all available parameters.
Z3_param_descrs Z3_API Z3_simplify_get_param_descrs (Z3_context c)
Return the parameter description set for the simplify procedure.
Modifiers
Z3_ast Z3_API Z3_update_term (Z3_context c, Z3_ast a, unsigned num_args, Z3_ast const args[])
Update the arguments of term a using the arguments args. The number of arguments num_args should coincide with the number of arguments to a. If a is a quantifier, then num_args has to be 1.
Z3_ast Z3_API Z3_substitute (Z3_context c, Z3_ast a, unsigned num_exprs, Z3_ast const from[], Z3_ast const to[])
Substitute every occurrence of from[i] in a with to[i], for i smaller than num_exprs. The result is the new AST. The arrays from and to must have size num_exprs. For every i smaller than num_exprs, we must have that sort of from[i] must be equal to sort of to[i].
Z3_ast Z3_API Z3_substitute_vars (Z3_context c, Z3_ast a, unsigned num_exprs, Z3_ast const to[])
Substitute the variables in a with the expressions in to. For every i smaller than num_exprs, the variable with de-Bruijn index i is replaced with term to[i]. Note that a variable is created using the function Z3_mk_bound.
Z3_ast Z3_API Z3_substitute_funs (Z3_context c, Z3_ast a, unsigned num_funs, Z3_func_decl const from[], Z3_ast const to[])
Substitute functions in from with new expressions in to.
Z3_ast Z3_API Z3_translate (Z3_context source, Z3_ast a, Z3_context target)
Translate/Copy the AST a from context source to context target. AST a must have been created using context source.
Models
Z3_model Z3_API Z3_mk_model (Z3_context c)
Create a fresh model object. It has reference count 0.
void Z3_API Z3_model_inc_ref (Z3_context c, Z3_model m)
Increment the reference counter of the given model.
void Z3_API Z3_model_dec_ref (Z3_context c, Z3_model m)
Decrement the reference counter of the given model.
bool Z3_API Z3_model_eval (Z3_context c, Z3_model m, Z3_ast t, bool model_completion, Z3_ast *v)
Evaluate the AST node t in the given model. Return true if succeeded, and store the result in v.
Z3_ast Z3_API Z3_model_get_const_interp (Z3_context c, Z3_model m, Z3_func_decl a)
Return the interpretation (i.e., assignment) of constant a in the model m. Return NULL, if the model does not assign an interpretation for a. That should be interpreted as: the value of a does not matter.
bool Z3_API Z3_model_has_interp (Z3_context c, Z3_model m, Z3_func_decl a)
Test if there exists an interpretation (i.e., assignment) for a in the model m.
Z3_func_interp Z3_API Z3_model_get_func_interp (Z3_context c, Z3_model m, Z3_func_decl f)
Return the interpretation of the function f in the model m. Return NULL, if the model does not assign an interpretation for f. That should be interpreted as: the f does not matter.
unsigned Z3_API Z3_model_get_num_consts (Z3_context c, Z3_model m)
Return the number of constants assigned by the given model.
Z3_func_decl Z3_API Z3_model_get_const_decl (Z3_context c, Z3_model m, unsigned i)
Return the i-th constant in the given model.
unsigned Z3_API Z3_model_get_num_funcs (Z3_context c, Z3_model m)
Return the number of function interpretations in the given model.
Z3_func_decl Z3_API Z3_model_get_func_decl (Z3_context c, Z3_model m, unsigned i)
Return the declaration of the i-th function in the given model.
unsigned Z3_API Z3_model_get_num_sorts (Z3_context c, Z3_model m)
Return the number of uninterpreted sorts that m assigns an interpretation to.
Z3_sort Z3_API Z3_model_get_sort (Z3_context c, Z3_model m, unsigned i)
Return a uninterpreted sort that m assigns an interpretation.
Z3_ast_vector Z3_API Z3_model_get_sort_universe (Z3_context c, Z3_model m, Z3_sort s)
Return the finite set of distinct values that represent the interpretation for sort s.
Z3_model Z3_API Z3_model_translate (Z3_context c, Z3_model m, Z3_context dst)
translate model from context c to context dst.
bool Z3_API Z3_is_as_array (Z3_context c, Z3_ast a)
The (_ as-array f) AST node is a construct for assigning interpretations for arrays in Z3. It is the array such that forall indices i we have that (select (_ as-array f) i) is equal to (f i). This procedure returns true if the a is an as-array AST node.
Z3_func_decl Z3_API Z3_get_as_array_func_decl (Z3_context c, Z3_ast a)
Return the function declaration f associated with a (_ as_array f) node.
Z3_func_interp Z3_API Z3_add_func_interp (Z3_context c, Z3_model m, Z3_func_decl f, Z3_ast default_value)
Create a fresh func_interp object, add it to a model for a specified function. It has reference count 0.
void Z3_API Z3_add_const_interp (Z3_context c, Z3_model m, Z3_func_decl f, Z3_ast a)
Add a constant interpretation.
void Z3_API Z3_func_interp_inc_ref (Z3_context c, Z3_func_interp f)
Increment the reference counter of the given Z3_func_interp object.
void Z3_API Z3_func_interp_dec_ref (Z3_context c, Z3_func_interp f)
Decrement the reference counter of the given Z3_func_interp object.
unsigned Z3_API Z3_func_interp_get_num_entries (Z3_context c, Z3_func_interp f)
Return the number of entries in the given function interpretation.
Z3_func_entry Z3_API Z3_func_interp_get_entry (Z3_context c, Z3_func_interp f, unsigned i)
Return a "point" of the given function interpretation. It represents the value of f in a particular point.
Z3_ast Z3_API Z3_func_interp_get_else (Z3_context c, Z3_func_interp f)
Return the 'else' value of the given function interpretation.
void Z3_API Z3_func_interp_set_else (Z3_context c, Z3_func_interp f, Z3_ast else_value)
Return the 'else' value of the given function interpretation.
unsigned Z3_API Z3_func_interp_get_arity (Z3_context c, Z3_func_interp f)
Return the arity (number of arguments) of the given function interpretation.
void Z3_API Z3_func_interp_add_entry (Z3_context c, Z3_func_interp fi, Z3_ast_vector args, Z3_ast value)
add a function entry to a function interpretation.
void Z3_API Z3_func_entry_inc_ref (Z3_context c, Z3_func_entry e)
Increment the reference counter of the given Z3_func_entry object.
void Z3_API Z3_func_entry_dec_ref (Z3_context c, Z3_func_entry e)
Decrement the reference counter of the given Z3_func_entry object.
Z3_ast Z3_API Z3_func_entry_get_value (Z3_context c, Z3_func_entry e)
Return the value of this point.
unsigned Z3_API Z3_func_entry_get_num_args (Z3_context c, Z3_func_entry e)
Return the number of arguments in a Z3_func_entry object.
Z3_ast Z3_API Z3_func_entry_get_arg (Z3_context c, Z3_func_entry e, unsigned i)
Return an argument of a Z3_func_entry object.
Interaction logging
bool Z3_API Z3_open_log (Z3_string filename)
Log interaction to a file.
void Z3_API Z3_append_log (Z3_string string)
Append user-defined string to interaction log.
void Z3_API Z3_close_log (void)
Close interaction log.
void Z3_API Z3_toggle_warning_messages (bool enabled)
Enable/disable printing warning messages to the console.
String conversion
void Z3_API Z3_set_ast_print_mode (Z3_context c, Z3_ast_print_mode mode)
Select mode for the format used for pretty-printing AST nodes.
Z3_string Z3_API Z3_ast_to_string (Z3_context c, Z3_ast a)
Convert the given AST node into a string.
Z3_string Z3_API Z3_pattern_to_string (Z3_context c, Z3_pattern p)
Z3_string Z3_API Z3_sort_to_string (Z3_context c, Z3_sort s)
Z3_string Z3_API Z3_func_decl_to_string (Z3_context c, Z3_func_decl d)
Z3_string Z3_API Z3_model_to_string (Z3_context c, Z3_model m)
Convert the given model into a string.
Z3_string Z3_API Z3_benchmark_to_smtlib_string (Z3_context c, Z3_string name, Z3_string logic, Z3_string status, Z3_string attributes, unsigned num_assumptions, Z3_ast const assumptions[], Z3_ast formula)
Convert the given benchmark into SMT-LIB formatted string.
Parser interface
Z3_ast_vector Z3_API Z3_parse_smtlib2_string (Z3_context c, Z3_string str, unsigned num_sorts, Z3_symbol const sort_names[], Z3_sort const sorts[], unsigned num_decls, Z3_symbol const decl_names[], Z3_func_decl const decls[])
Parse the given string using the SMT-LIB2 parser.
Z3_ast_vector Z3_API Z3_parse_smtlib2_file (Z3_context c, Z3_string file_name, unsigned num_sorts, Z3_symbol const sort_names[], Z3_sort const sorts[], unsigned num_decls, Z3_symbol const decl_names[], Z3_func_decl const decls[])
Similar to Z3_parse_smtlib2_string, but reads the benchmark from a file.
Z3_string Z3_API Z3_eval_smtlib2_string (Z3_context c, Z3_string str)
Parse and evaluate and SMT-LIB2 command sequence. The state from a previous call is saved so the next evaluation builds on top of the previous call.
Z3_parser_context Z3_API Z3_mk_parser_context (Z3_context c)
Create a parser context.
void Z3_API Z3_parser_context_inc_ref (Z3_context c, Z3_parser_context pc)
Increment the reference counter of the given Z3_parser_context object.
void Z3_API Z3_parser_context_dec_ref (Z3_context c, Z3_parser_context pc)
Decrement the reference counter of the given Z3_parser_context object.
void Z3_API Z3_parser_context_add_sort (Z3_context c, Z3_parser_context pc, Z3_sort s)
Add a sort declaration.
void Z3_API Z3_parser_context_add_decl (Z3_context c, Z3_parser_context pc, Z3_func_decl f)
Add a function declaration.
Z3_ast_vector Z3_API Z3_parser_context_from_string (Z3_context c, Z3_parser_context pc, Z3_string s)
Parse a string of SMTLIB2 commands. Return assertions.
Error Handling
Z3_error_code Z3_API Z3_get_error_code (Z3_context c)
Return the error code for the last API call.
void Z3_API Z3_set_error_handler (Z3_context c, Z3_error_handler h)
Register a Z3 error handler.
void Z3_API Z3_set_error (Z3_context c, Z3_error_code e)
Set an error.
Z3_string Z3_API Z3_get_error_msg (Z3_context c, Z3_error_code err)
Return a string describing the given error code.
Miscellaneous
void Z3_API Z3_get_version (unsigned *major, unsigned *minor, unsigned *build_number, unsigned *revision_number)
Return Z3 version number information.
Z3_string Z3_API Z3_get_full_version (void)
Return a string that fully describes the version of Z3 in use.
void Z3_API Z3_enable_trace (Z3_string tag)
Enable tracing messages tagged as tag when Z3 is compiled in debug mode. It is a NOOP otherwise.
void Z3_API Z3_disable_trace (Z3_string tag)
Disable tracing messages tagged as tag when Z3 is compiled in debug mode. It is a NOOP otherwise.
void Z3_API Z3_reset_memory (void)
Reset all allocated resources.
void Z3_API Z3_finalize_memory (void)
Destroy all allocated resources.
Goals
Z3_goal Z3_API Z3_mk_goal (Z3_context c, bool models, bool unsat_cores, bool proofs)
Create a goal (aka problem). A goal is essentially a set of formulas, that can be solved and/or transformed using tactics and solvers.
void Z3_API Z3_goal_inc_ref (Z3_context c, Z3_goal g)
Increment the reference counter of the given goal.
void Z3_API Z3_goal_dec_ref (Z3_context c, Z3_goal g)
Decrement the reference counter of the given goal.
Z3_goal_prec Z3_API Z3_goal_precision (Z3_context c, Z3_goal g)
Return the "precision" of the given goal. Goals can be transformed using over and under approximations. A under approximation is applied when the objective is to find a model for a given goal. An over approximation is applied when the objective is to find a proof for a given goal.
void Z3_API Z3_goal_assert (Z3_context c, Z3_goal g, Z3_ast a)
Add a new formula a to the given goal. The formula is split according to the following procedure that is applied until a fixed-point: Conjunctions are split into separate formulas. Negations are distributed over disjunctions, resulting in separate formulas. If the goal is false, adding new formulas is a no-op. If the formula a is true, then nothing is added. If the formula a is false, then the entire goal is replaced by the formula false.
bool Z3_API Z3_goal_inconsistent (Z3_context c, Z3_goal g)
Return true if the given goal contains the formula false.
unsigned Z3_API Z3_goal_depth (Z3_context c, Z3_goal g)
Return the depth of the given goal. It tracks how many transformations were applied to it.
void Z3_API Z3_goal_reset (Z3_context c, Z3_goal g)
Erase all formulas from the given goal.
unsigned Z3_API Z3_goal_size (Z3_context c, Z3_goal g)
Return the number of formulas in the given goal.
Z3_ast Z3_API Z3_goal_formula (Z3_context c, Z3_goal g, unsigned idx)
Return a formula from the given goal.
unsigned Z3_API Z3_goal_num_exprs (Z3_context c, Z3_goal g)
Return the number of formulas, subformulas and terms in the given goal.
bool Z3_API Z3_goal_is_decided_sat (Z3_context c, Z3_goal g)
Return true if the goal is empty, and it is precise or the product of a under approximation.
bool Z3_API Z3_goal_is_decided_unsat (Z3_context c, Z3_goal g)
Return true if the goal contains false, and it is precise or the product of an over approximation.
Z3_goal Z3_API Z3_goal_translate (Z3_context source, Z3_goal g, Z3_context target)
Copy a goal g from the context source to the context target.
Z3_model Z3_API Z3_goal_convert_model (Z3_context c, Z3_goal g, Z3_model m)
Convert a model of the formulas of a goal to a model of an original goal. The model may be null, in which case the returned model is valid if the goal was established satisfiable.
Z3_string Z3_API Z3_goal_to_string (Z3_context c, Z3_goal g)
Convert a goal into a string.
Z3_string Z3_API Z3_goal_to_dimacs_string (Z3_context c, Z3_goal g, bool include_names)
Convert a goal into a DIMACS formatted string. The goal must be in CNF. You can convert a goal to CNF by applying the tseitin-cnf tactic. Bit-vectors are not automatically converted to Booleans either, so if the caller intends to preserve satisfiability, it should apply bit-blasting tactics. Quantifiers and theory atoms will not be encoded.
Tactics, Simplifiers and Probes
Z3_tactic Z3_API Z3_mk_tactic (Z3_context c, Z3_string name)
Return a tactic associated with the given name. The complete list of tactics may be obtained using the procedures Z3_get_num_tactics and Z3_get_tactic_name. It may also be obtained using the command (help-tactic) in the SMT 2.0 front-end.
void Z3_API Z3_tactic_inc_ref (Z3_context c, Z3_tactic t)
Increment the reference counter of the given tactic.
void Z3_API Z3_tactic_dec_ref (Z3_context c, Z3_tactic g)
Decrement the reference counter of the given tactic.
Z3_probe Z3_API Z3_mk_probe (Z3_context c, Z3_string name)
Return a probe associated with the given name. The complete list of probes may be obtained using the procedures Z3_get_num_probes and Z3_get_probe_name. It may also be obtained using the command (help-tactic) in the SMT 2.0 front-end.
void Z3_API Z3_probe_inc_ref (Z3_context c, Z3_probe p)
Increment the reference counter of the given probe.
void Z3_API Z3_probe_dec_ref (Z3_context c, Z3_probe p)
Decrement the reference counter of the given probe.
Z3_tactic Z3_API Z3_tactic_and_then (Z3_context c, Z3_tactic t1, Z3_tactic t2)
Return a tactic that applies t1 to a given goal and t2 to every subgoal produced by t1.
Z3_tactic Z3_API Z3_tactic_or_else (Z3_context c, Z3_tactic t1, Z3_tactic t2)
Return a tactic that first applies t1 to a given goal, if it fails then returns the result of t2 applied to the given goal.
Z3_tactic Z3_API Z3_tactic_par_or (Z3_context c, unsigned num, Z3_tactic const ts[])
Return a tactic that applies the given tactics in parallel.
Z3_tactic Z3_API Z3_tactic_par_and_then (Z3_context c, Z3_tactic t1, Z3_tactic t2)
Return a tactic that applies t1 to a given goal and then t2 to every subgoal produced by t1. The subgoals are processed in parallel.
Z3_tactic Z3_API Z3_tactic_try_for (Z3_context c, Z3_tactic t, unsigned ms)
Return a tactic that applies t to a given goal for ms milliseconds. If t does not terminate in ms milliseconds, then it fails.
Z3_tactic Z3_API Z3_tactic_when (Z3_context c, Z3_probe p, Z3_tactic t)
Return a tactic that applies t to a given goal is the probe p evaluates to true. If p evaluates to false, then the new tactic behaves like the skip tactic.
Z3_tactic Z3_API Z3_tactic_cond (Z3_context c, Z3_probe p, Z3_tactic t1, Z3_tactic t2)
Return a tactic that applies t1 to a given goal if the probe p evaluates to true, and t2 if p evaluates to false.
Z3_tactic Z3_API Z3_tactic_repeat (Z3_context c, Z3_tactic t, unsigned max)
Return a tactic that keeps applying t until the goal is not modified anymore or the maximum number of iterations max is reached.
Z3_tactic Z3_API Z3_tactic_skip (Z3_context c)
Return a tactic that just return the given goal.
Z3_tactic Z3_API Z3_tactic_fail (Z3_context c)
Return a tactic that always fails.
Z3_tactic Z3_API Z3_tactic_fail_if (Z3_context c, Z3_probe p)
Return a tactic that fails if the probe p evaluates to false.
Z3_tactic Z3_API Z3_tactic_fail_if_not_decided (Z3_context c)
Return a tactic that fails if the goal is not trivially satisfiable (i.e., empty) or trivially unsatisfiable (i.e., contains false).
Z3_tactic Z3_API Z3_tactic_using_params (Z3_context c, Z3_tactic t, Z3_params p)
Return a tactic that applies t using the given set of parameters.
Z3_simplifier Z3_API Z3_mk_simplifier (Z3_context c, Z3_string name)
Return a simplifier associated with the given name. The complete list of simplifiers may be obtained using the procedures Z3_get_num_simplifiers and Z3_get_simplifier_name. It may also be obtained using the command (help-simplifier) in the SMT 2.0 front-end.
void Z3_API Z3_simplifier_inc_ref (Z3_context c, Z3_simplifier t)
Increment the reference counter of the given simplifier.
void Z3_API Z3_simplifier_dec_ref (Z3_context c, Z3_simplifier g)
Decrement the reference counter of the given simplifier.
Z3_solver Z3_API Z3_solver_add_simplifier (Z3_context c, Z3_solver solver, Z3_simplifier simplifier)
Attach simplifier to a solver. The solver will use the simplifier for incremental pre-processing.
Z3_simplifier Z3_API Z3_simplifier_and_then (Z3_context c, Z3_simplifier t1, Z3_simplifier t2)
Return a simplifier that applies t1 to a given goal and t2 to every subgoal produced by t1.
Z3_simplifier Z3_API Z3_simplifier_using_params (Z3_context c, Z3_simplifier t, Z3_params p)
Return a simplifier that applies t using the given set of parameters.
unsigned Z3_API Z3_get_num_simplifiers (Z3_context c)
Return the number of builtin simplifiers available in Z3.
Z3_string Z3_API Z3_get_simplifier_name (Z3_context c, unsigned i)
Return the name of the idx simplifier.
Z3_string Z3_API Z3_simplifier_get_help (Z3_context c, Z3_simplifier t)
Return a string containing a description of parameters accepted by the given simplifier.
Z3_param_descrs Z3_API Z3_simplifier_get_param_descrs (Z3_context c, Z3_simplifier t)
Return the parameter description set for the given simplifier object.
Z3_string Z3_API Z3_simplifier_get_descr (Z3_context c, Z3_string name)
Return a string containing a description of the simplifier with the given name.
Z3_probe Z3_API Z3_probe_const (Z3_context x, double val)
Return a probe that always evaluates to val.
Z3_probe Z3_API Z3_probe_lt (Z3_context x, Z3_probe p1, Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is less than the value returned by p2.
Z3_probe Z3_API Z3_probe_gt (Z3_context x, Z3_probe p1, Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is greater than the value returned by p2.
Z3_probe Z3_API Z3_probe_le (Z3_context x, Z3_probe p1, Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is less than or equal to the value returned by p2.
Z3_probe Z3_API Z3_probe_ge (Z3_context x, Z3_probe p1, Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is greater than or equal to the value returned by p2.
Z3_probe Z3_API Z3_probe_eq (Z3_context x, Z3_probe p1, Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is equal to the value returned by p2.
Z3_probe Z3_API Z3_probe_and (Z3_context x, Z3_probe p1, Z3_probe p2)
Return a probe that evaluates to "true" when p1 and p2 evaluates to true.
Z3_probe Z3_API Z3_probe_or (Z3_context x, Z3_probe p1, Z3_probe p2)
Return a probe that evaluates to "true" when p1 or p2 evaluates to true.
Z3_probe Z3_API Z3_probe_not (Z3_context x, Z3_probe p)
Return a probe that evaluates to "true" when p does not evaluate to true.
unsigned Z3_API Z3_get_num_tactics (Z3_context c)
Return the number of builtin tactics available in Z3.
Z3_string Z3_API Z3_get_tactic_name (Z3_context c, unsigned i)
Return the name of the idx tactic.
unsigned Z3_API Z3_get_num_probes (Z3_context c)
Return the number of builtin probes available in Z3.
Z3_string Z3_API Z3_get_probe_name (Z3_context c, unsigned i)
Return the name of the i probe.
Z3_string Z3_API Z3_tactic_get_help (Z3_context c, Z3_tactic t)
Return a string containing a description of parameters accepted by the given tactic.
Z3_param_descrs Z3_API Z3_tactic_get_param_descrs (Z3_context c, Z3_tactic t)
Return the parameter description set for the given tactic object.
Z3_string Z3_API Z3_tactic_get_descr (Z3_context c, Z3_string name)
Return a string containing a description of the tactic with the given name.
Z3_string Z3_API Z3_probe_get_descr (Z3_context c, Z3_string name)
Return a string containing a description of the probe with the given name.
double Z3_API Z3_probe_apply (Z3_context c, Z3_probe p, Z3_goal g)
Execute the probe over the goal. The probe always produce a double value. "Boolean" probes return 0.0 for false, and a value different from 0.0 for true.
Z3_apply_result Z3_API Z3_tactic_apply (Z3_context c, Z3_tactic t, Z3_goal g)
Apply tactic t to the goal g.
Z3_apply_result Z3_API Z3_tactic_apply_ex (Z3_context c, Z3_tactic t, Z3_goal g, Z3_params p)
Apply tactic t to the goal g using the parameter set p.
void Z3_API Z3_apply_result_inc_ref (Z3_context c, Z3_apply_result r)
Increment the reference counter of the given Z3_apply_result object.
void Z3_API Z3_apply_result_dec_ref (Z3_context c, Z3_apply_result r)
Decrement the reference counter of the given Z3_apply_result object.
Z3_string Z3_API Z3_apply_result_to_string (Z3_context c, Z3_apply_result r)
Convert the Z3_apply_result object returned by Z3_tactic_apply into a string.
unsigned Z3_API Z3_apply_result_get_num_subgoals (Z3_context c, Z3_apply_result r)
Return the number of subgoals in the Z3_apply_result object returned by Z3_tactic_apply.
Z3_goal Z3_API Z3_apply_result_get_subgoal (Z3_context c, Z3_apply_result r, unsigned i)
Return one of the subgoals in the Z3_apply_result object returned by Z3_tactic_apply.
Solvers
Z3_solver Z3_API Z3_mk_solver (Z3_context c)
Create a new solver. This solver is a "combined solver" (see combined_solver module) that internally uses a non-incremental (solver1) and an incremental solver (solver2). This combined solver changes its behaviour based on how it is used and how its parameters are set.
Z3_solver Z3_API Z3_mk_simple_solver (Z3_context c)
Create a new incremental solver.
Z3_solver Z3_API Z3_mk_solver_for_logic (Z3_context c, Z3_symbol logic)
Create a new solver customized for the given logic. It behaves like Z3_mk_solver if the logic is unknown or unsupported.
Z3_solver Z3_API Z3_mk_solver_from_tactic (Z3_context c, Z3_tactic t)
Create a new solver that is implemented using the given tactic. The solver supports the commands Z3_solver_push and Z3_solver_pop, but it will always solve each Z3_solver_check from scratch.
Z3_solver Z3_API Z3_solver_translate (Z3_context source, Z3_solver s, Z3_context target)
Copy a solver s from the context source to the context target.
void Z3_API Z3_solver_import_model_converter (Z3_context ctx, Z3_solver src, Z3_solver dst)
Ad-hoc method for importing model conversion from solver.
Z3_string Z3_API Z3_solver_get_help (Z3_context c, Z3_solver s)
Return a string describing all solver available parameters.
Z3_param_descrs Z3_API Z3_solver_get_param_descrs (Z3_context c, Z3_solver s)
Return the parameter description set for the given solver object.
void Z3_API Z3_solver_set_params (Z3_context c, Z3_solver s, Z3_params p)
Set the given solver using the given parameters.
void Z3_API Z3_solver_inc_ref (Z3_context c, Z3_solver s)
Increment the reference counter of the given solver.
void Z3_API Z3_solver_dec_ref (Z3_context c, Z3_solver s)
Decrement the reference counter of the given solver.
void Z3_API Z3_solver_interrupt (Z3_context c, Z3_solver s)
Solver local interrupt. Normally you should use Z3_interrupt to cancel solvers because only one solver is enabled concurrently per context. However, per GitHub issue #1006, there are use cases where it is more convenient to cancel a specific solver. Solvers that are not selected for interrupts are left alone.
void Z3_API Z3_solver_push (Z3_context c, Z3_solver s)
Create a backtracking point.
void Z3_API Z3_solver_pop (Z3_context c, Z3_solver s, unsigned n)
Backtrack n backtracking points.
void Z3_API Z3_solver_reset (Z3_context c, Z3_solver s)
Remove all assertions from the solver.
unsigned Z3_API Z3_solver_get_num_scopes (Z3_context c, Z3_solver s)
Return the number of backtracking points.
void Z3_API Z3_solver_assert (Z3_context c, Z3_solver s, Z3_ast a)
Assert a constraint into the solver.
void Z3_API Z3_solver_assert_and_track (Z3_context c, Z3_solver s, Z3_ast a, Z3_ast p)
Assert a constraint a into the solver, and track it (in the unsat) core using the Boolean constant p.
void Z3_API Z3_solver_from_file (Z3_context c, Z3_solver s, Z3_string file_name)
load solver assertions from a file.
void Z3_API Z3_solver_from_string (Z3_context c, Z3_solver s, Z3_string str)
load solver assertions from a string.
Z3_ast_vector Z3_API Z3_solver_get_assertions (Z3_context c, Z3_solver s)
Return the set of asserted formulas on the solver.
Z3_ast_vector Z3_API Z3_solver_get_units (Z3_context c, Z3_solver s)
Return the set of units modulo model conversion.
Z3_ast_vector Z3_API Z3_solver_get_trail (Z3_context c, Z3_solver s)
Return the trail modulo model conversion, in order of decision level The decision level can be retrieved using Z3_solver_get_level based on the trail.
Z3_ast_vector Z3_API Z3_solver_get_non_units (Z3_context c, Z3_solver s)
Return the set of non units in the solver state.
void Z3_API Z3_solver_get_levels (Z3_context c, Z3_solver s, Z3_ast_vector literals, unsigned sz, unsigned levels[])
retrieve the decision depth of Boolean literals (variables or their negations). Assumes a check-sat call and no other calls (to extract models) have been invoked.
Z3_ast Z3_API Z3_solver_congruence_root (Z3_context c, Z3_solver s, Z3_ast a)
retrieve the congruence closure root of an expression. The root is retrieved relative to the state where the solver was in when it completed. If it completed during a set of case splits, the congruence roots are relative to these case splits. That is, the congruences are not consequences but they are true under the current state.
Z3_ast Z3_API Z3_solver_congruence_next (Z3_context c, Z3_solver s, Z3_ast a)
retrieve the next expression in the congruence class. The set of congruent siblings form a cyclic list. Repeated calls on the siblings will result in returning to the original expression.
Z3_ast Z3_API Z3_solver_congruence_explain (Z3_context c, Z3_solver s, Z3_ast a, Z3_ast b)
retrieve explanation for congruence.
void Z3_API Z3_solver_solve_for (Z3_context c, Z3_solver s, Z3_ast_vector variables, Z3_ast_vector terms, Z3_ast_vector guards)
retrieve a 'solution' for variables as defined by equalities in maintained by solvers. At this point, only linear solution are supported. The solution to variables may be presented in triangular form, such that variables used in solutions themselves have solutions.
void Z3_API Z3_solver_register_on_clause (Z3_context c, Z3_solver s, void *user_context, Z3_on_clause_eh on_clause_eh)
register a callback to that retrieves assumed, inferred and deleted clauses during search.
void Z3_API Z3_solver_propagate_init (Z3_context c, Z3_solver s, void *user_context, Z3_push_eh push_eh, Z3_pop_eh pop_eh, Z3_fresh_eh fresh_eh)
register a user-propagator with the solver.
void Z3_API Z3_solver_propagate_fixed (Z3_context c, Z3_solver s, Z3_fixed_eh fixed_eh)
register a callback for when an expression is bound to a fixed value. The supported expression types are
void Z3_API Z3_solver_propagate_final (Z3_context c, Z3_solver s, Z3_final_eh final_eh)
register a callback on final check. This provides freedom to the propagator to delay actions or implement a branch-and bound solver. The final check is invoked when all decision variables have been assigned by the solver.
void Z3_API Z3_solver_propagate_eq (Z3_context c, Z3_solver s, Z3_eq_eh eq_eh)
register a callback on expression equalities.
void Z3_API Z3_solver_propagate_diseq (Z3_context c, Z3_solver s, Z3_eq_eh eq_eh)
register a callback on expression dis-equalities.
void Z3_API Z3_solver_propagate_created (Z3_context c, Z3_solver s, Z3_created_eh created_eh)
register a callback when a new expression with a registered function is used by the solver The registered function appears at the top level and is created using Z3_solver_propagate_declare.
void Z3_API Z3_solver_propagate_decide (Z3_context c, Z3_solver s, Z3_decide_eh decide_eh)
register a callback when the solver decides to split on a registered expression. The callback may change the arguments by providing other values by calling Z3_solver_next_split
void Z3_API Z3_solver_propagate_on_binding (Z3_context c, Z3_solver s, Z3_on_binding_eh on_binding_eh)
register a callback when the solver instantiates a quantifier. If the callback returns false, the actual instantiation of the quantifier is blocked. This allows the user propagator selectively prioritize instantiations without relying on default or configured weights.
bool Z3_API Z3_solver_next_split (Z3_context c, Z3_solver_callback cb, Z3_ast t, unsigned idx, Z3_lbool phase)
Z3_func_decl Z3_API Z3_solver_propagate_declare (Z3_context c, Z3_symbol name, unsigned n, Z3_sort *domain, Z3_sort range)
void Z3_API Z3_solver_propagate_register (Z3_context c, Z3_solver s, Z3_ast e)
register an expression to propagate on with the solver. Only expressions of type Bool and type Bit-Vector can be registered for propagation.
void Z3_API Z3_solver_propagate_register_cb (Z3_context c, Z3_solver_callback cb, Z3_ast e)
register an expression to propagate on with the solver. Only expressions of type Bool and type Bit-Vector can be registered for propagation. Unlike Z3_solver_propagate_register, this function takes a solver callback context as argument. It can be invoked during a callback to register new expressions.
bool Z3_API Z3_solver_propagate_consequence (Z3_context c, Z3_solver_callback cb, unsigned num_fixed, Z3_ast const *fixed, unsigned num_eqs, Z3_ast const *eq_lhs, Z3_ast const *eq_rhs, Z3_ast conseq)
propagate a consequence based on fixed values and equalities.
A client may invoke it during the propagate_fixed, propagate_eq, propagate_diseq, and propagate_final callbacks. The callback adds a propagation consequence based on the fixed values passed ids and equalities eqs based on parameters lhs, rhs.
void Z3_API Z3_solver_set_initial_value (Z3_context c, Z3_solver s, Z3_ast v, Z3_ast val)
provide an initialization hint to the solver. The initialization hint is used to calibrate an initial value of the expression that represents a variable. If the variable is Boolean, the initial phase is set according to value. If the variable is an integer or real, the initial Simplex tableau is recalibrated to attempt to follow the value assignment.
Z3_lbool Z3_API Z3_solver_check (Z3_context c, Z3_solver s)
Check whether the assertions in a given solver are consistent or not.
Z3_lbool Z3_API Z3_solver_check_assumptions (Z3_context c, Z3_solver s, unsigned num_assumptions, Z3_ast const assumptions[])
Check whether the assertions in the given solver and optional assumptions are consistent or not.
Z3_lbool Z3_API Z3_get_implied_equalities (Z3_context c, Z3_solver s, unsigned num_terms, Z3_ast const terms[], unsigned class_ids[])
Retrieve congruence class representatives for terms.
Z3_lbool Z3_API Z3_solver_get_consequences (Z3_context c, Z3_solver s, Z3_ast_vector assumptions, Z3_ast_vector variables, Z3_ast_vector consequences)
retrieve consequences from solver that determine values of the supplied function symbols.
Z3_ast_vector Z3_API Z3_solver_cube (Z3_context c, Z3_solver s, Z3_ast_vector vars, unsigned backtrack_level)
extract a next cube for a solver. The last cube is the constant true or false. The number of (non-constant) cubes is by default 1. For the sat solver cubing is controlled using parameters sat.lookahead.cube.cutoff and sat.lookahead.cube.fraction.
Z3_model Z3_API Z3_solver_get_model (Z3_context c, Z3_solver s)
Retrieve the model for the last Z3_solver_check or Z3_solver_check_assumptions.
Z3_ast Z3_API Z3_solver_get_proof (Z3_context c, Z3_solver s)
Retrieve the proof for the last Z3_solver_check or Z3_solver_check_assumptions.
Z3_ast_vector Z3_API Z3_solver_get_unsat_core (Z3_context c, Z3_solver s)
Retrieve the unsat core for the last Z3_solver_check_assumptions The unsat core is a subset of the assumptions a.
Z3_string Z3_API Z3_solver_get_reason_unknown (Z3_context c, Z3_solver s)
Return a brief justification for an "unknown" result (i.e., Z3_L_UNDEF) for the commands Z3_solver_check and Z3_solver_check_assumptions.
Z3_stats Z3_API Z3_solver_get_statistics (Z3_context c, Z3_solver s)
Return statistics for the given solver.
Z3_string Z3_API Z3_solver_to_string (Z3_context c, Z3_solver s)
Convert a solver into a string.
Z3_string Z3_API Z3_solver_to_dimacs_string (Z3_context c, Z3_solver s, bool include_names)
Convert a solver into a DIMACS formatted string.
Statistics
Z3_string Z3_API Z3_stats_to_string (Z3_context c, Z3_stats s)
Convert a statistics into a string.
void Z3_API Z3_stats_inc_ref (Z3_context c, Z3_stats s)
Increment the reference counter of the given statistics object.
void Z3_API Z3_stats_dec_ref (Z3_context c, Z3_stats s)
Decrement the reference counter of the given statistics object.
unsigned Z3_API Z3_stats_size (Z3_context c, Z3_stats s)
Return the number of statistical data in s.
Z3_string Z3_API Z3_stats_get_key (Z3_context c, Z3_stats s, unsigned idx)
Return the key (a string) for a particular statistical data.
bool Z3_API Z3_stats_is_uint (Z3_context c, Z3_stats s, unsigned idx)
Return true if the given statistical data is a unsigned integer.
bool Z3_API Z3_stats_is_double (Z3_context c, Z3_stats s, unsigned idx)
Return true if the given statistical data is a double.
unsigned Z3_API Z3_stats_get_uint_value (Z3_context c, Z3_stats s, unsigned idx)
Return the unsigned value of the given statistical data.
double Z3_API Z3_stats_get_double_value (Z3_context c, Z3_stats s, unsigned idx)
Return the double value of the given statistical data.
uint64_t Z3_API Z3_get_estimated_alloc_size (void)
Return the estimated allocated memory in bytes.
AST vectors
Z3_ast_vector Z3_API Z3_mk_ast_vector (Z3_context c)
Return an empty AST vector.
void Z3_API Z3_ast_vector_inc_ref (Z3_context c, Z3_ast_vector v)
Increment the reference counter of the given AST vector.
void Z3_API Z3_ast_vector_dec_ref (Z3_context c, Z3_ast_vector v)
Decrement the reference counter of the given AST vector.
unsigned Z3_API Z3_ast_vector_size (Z3_context c, Z3_ast_vector v)
Return the size of the given AST vector.
Z3_ast Z3_API Z3_ast_vector_get (Z3_context c, Z3_ast_vector v, unsigned i)
Return the AST at position i in the AST vector v.
void Z3_API Z3_ast_vector_set (Z3_context c, Z3_ast_vector v, unsigned i, Z3_ast a)
Update position i of the AST vector v with the AST a.
void Z3_API Z3_ast_vector_resize (Z3_context c, Z3_ast_vector v, unsigned n)
Resize the AST vector v.
void Z3_API Z3_ast_vector_push (Z3_context c, Z3_ast_vector v, Z3_ast a)
Add the AST a in the end of the AST vector v. The size of v is increased by one.
Z3_ast_vector Z3_API Z3_ast_vector_translate (Z3_context s, Z3_ast_vector v, Z3_context t)
Translate the AST vector v from context s into an AST vector in context t.
Z3_string Z3_API Z3_ast_vector_to_string (Z3_context c, Z3_ast_vector v)
Convert AST vector into a string.
AST maps
Z3_ast_map Z3_API Z3_mk_ast_map (Z3_context c)
Return an empty mapping from AST to AST.
void Z3_API Z3_ast_map_inc_ref (Z3_context c, Z3_ast_map m)
Increment the reference counter of the given AST map.
void Z3_API Z3_ast_map_dec_ref (Z3_context c, Z3_ast_map m)
Decrement the reference counter of the given AST map.
bool Z3_API Z3_ast_map_contains (Z3_context c, Z3_ast_map m, Z3_ast k)
Return true if the map m contains the AST key k.
Z3_ast Z3_API Z3_ast_map_find (Z3_context c, Z3_ast_map m, Z3_ast k)
Return the value associated with the key k.
void Z3_API Z3_ast_map_insert (Z3_context c, Z3_ast_map m, Z3_ast k, Z3_ast v)
Store/Replace a new key, value pair in the given map.
void Z3_API Z3_ast_map_erase (Z3_context c, Z3_ast_map m, Z3_ast k)
Erase a key from the map.
void Z3_API Z3_ast_map_reset (Z3_context c, Z3_ast_map m)
Remove all keys from the given map.
unsigned Z3_API Z3_ast_map_size (Z3_context c, Z3_ast_map m)
Return the size of the given map.
Z3_ast_vector Z3_API Z3_ast_map_keys (Z3_context c, Z3_ast_map m)
Return the keys stored in the given map.
Z3_string Z3_API Z3_ast_map_to_string (Z3_context c, Z3_ast_map m)
Convert the given map into a string.
Floating-Point Arithmetic
Z3_sort Z3_API Z3_mk_fpa_rounding_mode_sort (Z3_context c)
Create the RoundingMode sort.
Z3_ast Z3_API Z3_mk_fpa_round_nearest_ties_to_even (Z3_context c)
Create a numeral of RoundingMode sort which represents the NearestTiesToEven rounding mode.
Z3_ast Z3_API Z3_mk_fpa_rne (Z3_context c)
Create a numeral of RoundingMode sort which represents the NearestTiesToEven rounding mode.
Z3_ast Z3_API Z3_mk_fpa_round_nearest_ties_to_away (Z3_context c)
Create a numeral of RoundingMode sort which represents the NearestTiesToAway rounding mode.
Z3_ast Z3_API Z3_mk_fpa_rna (Z3_context c)
Create a numeral of RoundingMode sort which represents the NearestTiesToAway rounding mode.
Z3_ast Z3_API Z3_mk_fpa_round_toward_positive (Z3_context c)
Create a numeral of RoundingMode sort which represents the TowardPositive rounding mode.
Z3_ast Z3_API Z3_mk_fpa_rtp (Z3_context c)
Create a numeral of RoundingMode sort which represents the TowardPositive rounding mode.
Z3_ast Z3_API Z3_mk_fpa_round_toward_negative (Z3_context c)
Create a numeral of RoundingMode sort which represents the TowardNegative rounding mode.
Z3_ast Z3_API Z3_mk_fpa_rtn (Z3_context c)
Create a numeral of RoundingMode sort which represents the TowardNegative rounding mode.
Z3_ast Z3_API Z3_mk_fpa_round_toward_zero (Z3_context c)
Create a numeral of RoundingMode sort which represents the TowardZero rounding mode.
Z3_ast Z3_API Z3_mk_fpa_rtz (Z3_context c)
Create a numeral of RoundingMode sort which represents the TowardZero rounding mode.
Z3_sort Z3_API Z3_mk_fpa_sort (Z3_context c, unsigned ebits, unsigned sbits)
Create a FloatingPoint sort.
Z3_sort Z3_API Z3_mk_fpa_sort_half (Z3_context c)
Create the half-precision (16-bit) FloatingPoint sort.
Z3_sort Z3_API Z3_mk_fpa_sort_16 (Z3_context c)
Create the half-precision (16-bit) FloatingPoint sort.
Z3_sort Z3_API Z3_mk_fpa_sort_single (Z3_context c)
Create the single-precision (32-bit) FloatingPoint sort.
Z3_sort Z3_API Z3_mk_fpa_sort_32 (Z3_context c)
Create the single-precision (32-bit) FloatingPoint sort.
Z3_sort Z3_API Z3_mk_fpa_sort_double (Z3_context c)
Create the double-precision (64-bit) FloatingPoint sort.
Z3_sort Z3_API Z3_mk_fpa_sort_64 (Z3_context c)
Create the double-precision (64-bit) FloatingPoint sort.
Z3_sort Z3_API Z3_mk_fpa_sort_quadruple (Z3_context c)
Create the quadruple-precision (128-bit) FloatingPoint sort.
Z3_sort Z3_API Z3_mk_fpa_sort_128 (Z3_context c)
Create the quadruple-precision (128-bit) FloatingPoint sort.
Z3_ast Z3_API Z3_mk_fpa_nan (Z3_context c, Z3_sort s)
Create a floating-point NaN of sort s.
Z3_ast Z3_API Z3_mk_fpa_inf (Z3_context c, Z3_sort s, bool negative)
Create a floating-point infinity of sort s.
Z3_ast Z3_API Z3_mk_fpa_zero (Z3_context c, Z3_sort s, bool negative)
Create a floating-point zero of sort s.
Z3_ast Z3_API Z3_mk_fpa_fp (Z3_context c, Z3_ast sgn, Z3_ast exp, Z3_ast sig)
Create an expression of FloatingPoint sort from three bit-vector expressions.
Z3_ast Z3_API Z3_mk_fpa_numeral_float (Z3_context c, float v, Z3_sort ty)
Create a numeral of FloatingPoint sort from a float.
Z3_ast Z3_API Z3_mk_fpa_numeral_double (Z3_context c, double v, Z3_sort ty)
Create a numeral of FloatingPoint sort from a double.
Z3_ast Z3_API Z3_mk_fpa_numeral_int (Z3_context c, signed v, Z3_sort ty)
Create a numeral of FloatingPoint sort from a signed integer.
Z3_ast Z3_API Z3_mk_fpa_numeral_int_uint (Z3_context c, bool sgn, signed exp, unsigned sig, Z3_sort ty)
Create a numeral of FloatingPoint sort from a sign bit and two integers.
Z3_ast Z3_API Z3_mk_fpa_numeral_int64_uint64 (Z3_context c, bool sgn, int64_t exp, uint64_t sig, Z3_sort ty)
Create a numeral of FloatingPoint sort from a sign bit and two 64-bit integers.
Z3_ast Z3_API Z3_mk_fpa_abs (Z3_context c, Z3_ast t)
Floating-point absolute value.
Z3_ast Z3_API Z3_mk_fpa_neg (Z3_context c, Z3_ast t)
Floating-point negation.
Z3_ast Z3_API Z3_mk_fpa_add (Z3_context c, Z3_ast rm, Z3_ast t1, Z3_ast t2)
Floating-point addition.
Z3_ast Z3_API Z3_mk_fpa_sub (Z3_context c, Z3_ast rm, Z3_ast t1, Z3_ast t2)
Floating-point subtraction.
Z3_ast Z3_API Z3_mk_fpa_mul (Z3_context c, Z3_ast rm, Z3_ast t1, Z3_ast t2)
Floating-point multiplication.
Z3_ast Z3_API Z3_mk_fpa_div (Z3_context c, Z3_ast rm, Z3_ast t1, Z3_ast t2)
Floating-point division.
Z3_ast Z3_API Z3_mk_fpa_fma (Z3_context c, Z3_ast rm, Z3_ast t1, Z3_ast t2, Z3_ast t3)
Floating-point fused multiply-add.
Z3_ast Z3_API Z3_mk_fpa_sqrt (Z3_context c, Z3_ast rm, Z3_ast t)
Floating-point square root.
Z3_ast Z3_API Z3_mk_fpa_rem (Z3_context c, Z3_ast t1, Z3_ast t2)
Floating-point remainder.
Z3_ast Z3_API Z3_mk_fpa_round_to_integral (Z3_context c, Z3_ast rm, Z3_ast t)
Floating-point roundToIntegral. Rounds a floating-point number to the closest integer, again represented as a floating-point number.
Z3_ast Z3_API Z3_mk_fpa_min (Z3_context c, Z3_ast t1, Z3_ast t2)
Minimum of floating-point numbers.
Z3_ast Z3_API Z3_mk_fpa_max (Z3_context c, Z3_ast t1, Z3_ast t2)
Maximum of floating-point numbers.
Z3_ast Z3_API Z3_mk_fpa_leq (Z3_context c, Z3_ast t1, Z3_ast t2)
Floating-point less than or equal.
Z3_ast Z3_API Z3_mk_fpa_lt (Z3_context c, Z3_ast t1, Z3_ast t2)
Floating-point less than.
Z3_ast Z3_API Z3_mk_fpa_geq (Z3_context c, Z3_ast t1, Z3_ast t2)
Floating-point greater than or equal.
Z3_ast Z3_API Z3_mk_fpa_gt (Z3_context c, Z3_ast t1, Z3_ast t2)
Floating-point greater than.
Z3_ast Z3_API Z3_mk_fpa_eq (Z3_context c, Z3_ast t1, Z3_ast t2)
Floating-point equality.
Z3_ast Z3_API Z3_mk_fpa_is_normal (Z3_context c, Z3_ast t)
Predicate indicating whether t is a normal floating-point number.
Z3_ast Z3_API Z3_mk_fpa_is_subnormal (Z3_context c, Z3_ast t)
Predicate indicating whether t is a subnormal floating-point number.
Z3_ast Z3_API Z3_mk_fpa_is_zero (Z3_context c, Z3_ast t)
Predicate indicating whether t is a floating-point number with zero value, i.e., +zero or -zero.
Z3_ast Z3_API Z3_mk_fpa_is_infinite (Z3_context c, Z3_ast t)
Predicate indicating whether t is a floating-point number representing +oo or -oo.
Z3_ast Z3_API Z3_mk_fpa_is_nan (Z3_context c, Z3_ast t)
Predicate indicating whether t is a NaN.
Z3_ast Z3_API Z3_mk_fpa_is_negative (Z3_context c, Z3_ast t)
Predicate indicating whether t is a negative floating-point number.
Z3_ast Z3_API Z3_mk_fpa_is_positive (Z3_context c, Z3_ast t)
Predicate indicating whether t is a positive floating-point number.
Z3_ast Z3_API Z3_mk_fpa_to_fp_bv (Z3_context c, Z3_ast bv, Z3_sort s)
Conversion of a single IEEE 754-2008 bit-vector into a floating-point number.
Z3_ast Z3_API Z3_mk_fpa_to_fp_float (Z3_context c, Z3_ast rm, Z3_ast t, Z3_sort s)
Conversion of a FloatingPoint term into another term of different FloatingPoint sort.
Z3_ast Z3_API Z3_mk_fpa_to_fp_real (Z3_context c, Z3_ast rm, Z3_ast t, Z3_sort s)
Conversion of a term of real sort into a term of FloatingPoint sort.
Z3_ast Z3_API Z3_mk_fpa_to_fp_signed (Z3_context c, Z3_ast rm, Z3_ast t, Z3_sort s)
Conversion of a 2's complement signed bit-vector term into a term of FloatingPoint sort.
Z3_ast Z3_API Z3_mk_fpa_to_fp_unsigned (Z3_context c, Z3_ast rm, Z3_ast t, Z3_sort s)
Conversion of a 2's complement unsigned bit-vector term into a term of FloatingPoint sort.
Z3_ast Z3_API Z3_mk_fpa_to_ubv (Z3_context c, Z3_ast rm, Z3_ast t, unsigned sz)
Conversion of a floating-point term into an unsigned bit-vector.
Z3_ast Z3_API Z3_mk_fpa_to_sbv (Z3_context c, Z3_ast rm, Z3_ast t, unsigned sz)
Conversion of a floating-point term into a signed bit-vector.
Z3_ast Z3_API Z3_mk_fpa_to_real (Z3_context c, Z3_ast t)
Conversion of a floating-point term into a real-numbered term.
Z3-specific floating-point extensions
unsigned Z3_API Z3_fpa_get_ebits (Z3_context c, Z3_sort s)
Retrieves the number of bits reserved for the exponent in a FloatingPoint sort.
unsigned Z3_API Z3_fpa_get_sbits (Z3_context c, Z3_sort s)
Retrieves the number of bits reserved for the significand in a FloatingPoint sort.
bool Z3_API Z3_fpa_is_numeral (Z3_context c, Z3_ast t)
Checks whether a given ast is a floating-point numeral.
bool Z3_API Z3_fpa_is_numeral_nan (Z3_context c, Z3_ast t)
Checks whether a given floating-point numeral is a NaN.
bool Z3_API Z3_fpa_is_numeral_inf (Z3_context c, Z3_ast t)
Checks whether a given floating-point numeral is a +oo or -oo.
bool Z3_API Z3_fpa_is_numeral_zero (Z3_context c, Z3_ast t)
Checks whether a given floating-point numeral is +zero or -zero.
bool Z3_API Z3_fpa_is_numeral_normal (Z3_context c, Z3_ast t)
Checks whether a given floating-point numeral is normal.
bool Z3_API Z3_fpa_is_numeral_subnormal (Z3_context c, Z3_ast t)
Checks whether a given floating-point numeral is subnormal.
bool Z3_API Z3_fpa_is_numeral_positive (Z3_context c, Z3_ast t)
Checks whether a given floating-point numeral is positive.
bool Z3_API Z3_fpa_is_numeral_negative (Z3_context c, Z3_ast t)
Checks whether a given floating-point numeral is negative.
Z3_ast Z3_API Z3_fpa_get_numeral_sign_bv (Z3_context c, Z3_ast t)
Retrieves the sign of a floating-point literal as a bit-vector expression.
Z3_ast Z3_API Z3_fpa_get_numeral_significand_bv (Z3_context c, Z3_ast t)
Retrieves the significand of a floating-point literal as a bit-vector expression.
bool Z3_API Z3_fpa_get_numeral_sign (Z3_context c, Z3_ast t, bool *sgn)
Retrieves the sign of a floating-point literal.
Z3_string Z3_API Z3_fpa_get_numeral_significand_string (Z3_context c, Z3_ast t)
Return the significand value of a floating-point numeral as a string.
bool Z3_API Z3_fpa_get_numeral_significand_uint64 (Z3_context c, Z3_ast t, uint64_t *n)
Return the significand value of a floating-point numeral as a uint64.
Z3_string Z3_API Z3_fpa_get_numeral_exponent_string (Z3_context c, Z3_ast t, bool biased)
Return the exponent value of a floating-point numeral as a string.
bool Z3_API Z3_fpa_get_numeral_exponent_int64 (Z3_context c, Z3_ast t, int64_t *n, bool biased)
Return the exponent value of a floating-point numeral as a signed 64-bit integer.
Z3_ast Z3_API Z3_fpa_get_numeral_exponent_bv (Z3_context c, Z3_ast t, bool biased)
Retrieves the exponent of a floating-point literal as a bit-vector expression.
Z3_ast Z3_API Z3_mk_fpa_to_ieee_bv (Z3_context c, Z3_ast t)
Conversion of a floating-point term into a bit-vector term in IEEE 754-2008 format.
Z3_ast Z3_API Z3_mk_fpa_to_fp_int_real (Z3_context c, Z3_ast rm, Z3_ast exp, Z3_ast sig, Z3_sort s)
Conversion of a real-sorted significand and an integer-sorted exponent into a term of FloatingPoint sort.
Optimization facilities
Z3_optimize Z3_API Z3_mk_optimize (Z3_context c)
Create a new optimize context.
void Z3_API Z3_optimize_inc_ref (Z3_context c, Z3_optimize d)
Increment the reference counter of the given optimize context.
void Z3_API Z3_optimize_dec_ref (Z3_context c, Z3_optimize d)
Decrement the reference counter of the given optimize context.
void Z3_API Z3_optimize_assert (Z3_context c, Z3_optimize o, Z3_ast a)
Assert hard constraint to the optimization context.
void Z3_API Z3_optimize_assert_and_track (Z3_context c, Z3_optimize o, Z3_ast a, Z3_ast t)
Assert tracked hard constraint to the optimization context.
unsigned Z3_API Z3_optimize_assert_soft (Z3_context c, Z3_optimize o, Z3_ast a, Z3_string weight, Z3_symbol id)
Assert soft constraint to the optimization context.
unsigned Z3_API Z3_optimize_maximize (Z3_context c, Z3_optimize o, Z3_ast t)
Add a maximization constraint.
unsigned Z3_API Z3_optimize_minimize (Z3_context c, Z3_optimize o, Z3_ast t)
Add a minimization constraint.
void Z3_API Z3_optimize_push (Z3_context c, Z3_optimize d)
Create a backtracking point.
void Z3_API Z3_optimize_pop (Z3_context c, Z3_optimize d)
Backtrack one level.
void Z3_API Z3_optimize_set_initial_value (Z3_context c, Z3_optimize o, Z3_ast v, Z3_ast val)
provide an initialization hint to the solver. The initialization hint is used to calibrate an initial value of the expression that represents a variable. If the variable is Boolean, the initial phase is set according to value. If the variable is an integer or real, the initial Simplex tableau is recalibrated to attempt to follow the value assignment.
Z3_lbool Z3_API Z3_optimize_check (Z3_context c, Z3_optimize o, unsigned num_assumptions, Z3_ast const assumptions[])
Check consistency and produce optimal values.
Z3_string Z3_API Z3_optimize_get_reason_unknown (Z3_context c, Z3_optimize d)
Retrieve a string that describes the last status returned by Z3_optimize_check.
Z3_model Z3_API Z3_optimize_get_model (Z3_context c, Z3_optimize o)
Retrieve the model for the last Z3_optimize_check.
Z3_ast_vector Z3_API Z3_optimize_get_unsat_core (Z3_context c, Z3_optimize o)
Retrieve the unsat core for the last Z3_optimize_check The unsat core is a subset of the assumptions a.
void Z3_API Z3_optimize_set_params (Z3_context c, Z3_optimize o, Z3_params p)
Set parameters on optimization context.
Z3_param_descrs Z3_API Z3_optimize_get_param_descrs (Z3_context c, Z3_optimize o)
Return the parameter description set for the given optimize object.
Z3_ast Z3_API Z3_optimize_get_lower (Z3_context c, Z3_optimize o, unsigned idx)
Retrieve lower bound value or approximation for the i'th optimization objective.
Z3_ast Z3_API Z3_optimize_get_upper (Z3_context c, Z3_optimize o, unsigned idx)
Retrieve upper bound value or approximation for the i'th optimization objective.
Z3_ast_vector Z3_API Z3_optimize_get_lower_as_vector (Z3_context c, Z3_optimize o, unsigned idx)
Retrieve lower bound value or approximation for the i'th optimization objective. The returned vector is of length 3. It always contains numerals. The three numerals are coefficients a, b, c and encode the result of Z3_optimize_get_lower a * infinity + b + c * epsilon.
Z3_ast_vector Z3_API Z3_optimize_get_upper_as_vector (Z3_context c, Z3_optimize o, unsigned idx)
Retrieve upper bound value or approximation for the i'th optimization objective.
Z3_string Z3_API Z3_optimize_to_string (Z3_context c, Z3_optimize o)
Print the current context as a string.
void Z3_API Z3_optimize_from_string (Z3_context c, Z3_optimize o, Z3_string s)
Parse an SMT-LIB2 string with assertions, soft constraints and optimization objectives. Add the parsed constraints and objectives to the optimization context.
void Z3_API Z3_optimize_from_file (Z3_context c, Z3_optimize o, Z3_string s)
Parse an SMT-LIB2 file with assertions, soft constraints and optimization objectives. Add the parsed constraints and objectives to the optimization context.
Z3_string Z3_API Z3_optimize_get_help (Z3_context c, Z3_optimize t)
Return a string containing a description of parameters accepted by optimize.
Z3_stats Z3_API Z3_optimize_get_statistics (Z3_context c, Z3_optimize d)
Retrieve statistics information from the last call to Z3_optimize_check.
Z3_ast_vector Z3_API Z3_optimize_get_assertions (Z3_context c, Z3_optimize o)
Return the set of asserted formulas on the optimization context.
Z3_ast_vector Z3_API Z3_optimize_get_objectives (Z3_context c, Z3_optimize o)
Return objectives on the optimization context. If the objective function is a max-sat objective it is returned as a Pseudo-Boolean (minimization) sum of the form (+ (if f1 w1 0) (if f2 w2 0) ...) If the objective function is entered as a maximization objective, then return the corresponding minimization objective. In this way the resulting objective function is always returned as a minimization objective.
void Z3_API Z3_optimize_register_model_eh (Z3_context c, Z3_optimize o, Z3_model m, void *ctx, Z3_model_eh model_eh)
register a model event handler for new models.
Z3_optimize Z3_API Z3_optimize_translate (Z3_context c, Z3_optimize o, Z3_context target)
Copy an optimization context from a source to a target context.
Polynomials
Z3_ast_vector Z3_API Z3_polynomial_subresultants (Z3_context c, Z3_ast p, Z3_ast q, Z3_ast x)
Return the nonzero subresultants of p and q with respect to the "variable" x.
Real Closed Fields
void Z3_API Z3_rcf_del (Z3_context c, Z3_rcf_num a)
Delete a RCF numeral created using the RCF API.
Z3_rcf_num Z3_API Z3_rcf_mk_rational (Z3_context c, Z3_string val)
Return a RCF rational using the given string.
Z3_rcf_num Z3_API Z3_rcf_mk_small_int (Z3_context c, int val)
Return a RCF small integer.
Z3_rcf_num Z3_API Z3_rcf_mk_pi (Z3_context c)
Return Pi.
Z3_rcf_num Z3_API Z3_rcf_mk_e (Z3_context c)
Return e (Euler's constant)
Z3_rcf_num Z3_API Z3_rcf_mk_infinitesimal (Z3_context c)
Return a new infinitesimal that is smaller than all elements in the Z3 field.
unsigned Z3_API Z3_rcf_mk_roots (Z3_context c, unsigned n, Z3_rcf_num const a[], Z3_rcf_num roots[])
Store in roots the roots of the polynomial a[n-1]*x^{n-1} + ... + a[0]. The output vector roots must have size n. It returns the number of roots of the polynomial.
Z3_rcf_num Z3_API Z3_rcf_add (Z3_context c, Z3_rcf_num a, Z3_rcf_num b)
Return the value a + b.
Z3_rcf_num Z3_API Z3_rcf_sub (Z3_context c, Z3_rcf_num a, Z3_rcf_num b)
Return the value a - b.
Z3_rcf_num Z3_API Z3_rcf_mul (Z3_context c, Z3_rcf_num a, Z3_rcf_num b)
Return the value a * b.
Z3_rcf_num Z3_API Z3_rcf_div (Z3_context c, Z3_rcf_num a, Z3_rcf_num b)
Return the value a / b.
Z3_rcf_num Z3_API Z3_rcf_neg (Z3_context c, Z3_rcf_num a)
Return the value -a.
Z3_rcf_num Z3_API Z3_rcf_inv (Z3_context c, Z3_rcf_num a)
Return the value 1/a.
Z3_rcf_num Z3_API Z3_rcf_power (Z3_context c, Z3_rcf_num a, unsigned k)
Return the value a^k.
bool Z3_API Z3_rcf_lt (Z3_context c, Z3_rcf_num a, Z3_rcf_num b)
Return true if a < b.
bool Z3_API Z3_rcf_gt (Z3_context c, Z3_rcf_num a, Z3_rcf_num b)
Return true if a > b.
bool Z3_API Z3_rcf_le (Z3_context c, Z3_rcf_num a, Z3_rcf_num b)
Return true if a <= b.
bool Z3_API Z3_rcf_ge (Z3_context c, Z3_rcf_num a, Z3_rcf_num b)
Return true if a >= b.
bool Z3_API Z3_rcf_eq (Z3_context c, Z3_rcf_num a, Z3_rcf_num b)
Return true if a == b.
bool Z3_API Z3_rcf_neq (Z3_context c, Z3_rcf_num a, Z3_rcf_num b)
Return true if a != b.
Z3_string Z3_API Z3_rcf_num_to_string (Z3_context c, Z3_rcf_num a, bool compact, bool html)
Convert the RCF numeral into a string.
Z3_string Z3_API Z3_rcf_num_to_decimal_string (Z3_context c, Z3_rcf_num a, unsigned prec)
Convert the RCF numeral into a string in decimal notation.
void Z3_API Z3_rcf_get_numerator_denominator (Z3_context c, Z3_rcf_num a, Z3_rcf_num *n, Z3_rcf_num *d)
Extract the "numerator" and "denominator" of the given RCF numeral. We have that a = n/d, moreover n and d are not represented using rational functions.
bool Z3_API Z3_rcf_is_rational (Z3_context c, Z3_rcf_num a)
Return true if a represents a rational number.
bool Z3_API Z3_rcf_is_algebraic (Z3_context c, Z3_rcf_num a)
Return true if a represents an algebraic number.
bool Z3_API Z3_rcf_is_infinitesimal (Z3_context c, Z3_rcf_num a)
Return true if a represents an infinitesimal.
bool Z3_API Z3_rcf_is_transcendental (Z3_context c, Z3_rcf_num a)
Return true if a represents a transcendental number.
unsigned Z3_API Z3_rcf_extension_index (Z3_context c, Z3_rcf_num a)
Return the index of a field extension.
Z3_symbol Z3_API Z3_rcf_transcendental_name (Z3_context c, Z3_rcf_num a)
Return the name of a transcendental.
Z3_symbol Z3_API Z3_rcf_infinitesimal_name (Z3_context c, Z3_rcf_num a)
Return the name of an infinitesimal.
unsigned Z3_API Z3_rcf_num_coefficients (Z3_context c, Z3_rcf_num a)
Return the number of coefficients in an algebraic number.
Z3_rcf_num Z3_API Z3_rcf_coefficient (Z3_context c, Z3_rcf_num a, unsigned i)
Extract a coefficient from an algebraic number.
int Z3_API Z3_rcf_interval (Z3_context c, Z3_rcf_num a, bool *lower_is_inf, bool *lower_is_open, Z3_rcf_num *lower, bool *upper_is_inf, bool *upper_is_open, Z3_rcf_num *upper)
Extract an interval from an algebraic number.
unsigned Z3_API Z3_rcf_num_sign_conditions (Z3_context c, Z3_rcf_num a)
Return the number of sign conditions of an algebraic number.
int Z3_API Z3_rcf_sign_condition_sign (Z3_context c, Z3_rcf_num a, unsigned i)
Extract the sign of a sign condition from an algebraic number.
unsigned Z3_API Z3_rcf_num_sign_condition_coefficients (Z3_context c, Z3_rcf_num a, unsigned i)
Return the number of sign condition polynomial coefficients of an algebraic number.
Z3_rcf_num Z3_API Z3_rcf_sign_condition_coefficient (Z3_context c, Z3_rcf_num a, unsigned i, unsigned j)
Extract the j-th polynomial coefficient of the i-th sign condition.
Detailed Description
Typedef Documentation
Z3_char_ptr
typedef char const* Z3_char_ptr
Definition at line 51 of file z3_api.h.
Z3_fixedpoint_new_lemma_eh
typedef void(* Z3_fixedpoint_new_lemma_eh) (void *state, Z3_ast lemma, unsigned level)
Definition at line 339 of file z3_fixedpoint.h.
Z3_fixedpoint_predecessor_eh
typedef void(* Z3_fixedpoint_predecessor_eh) (void *state)
Definition at line 340 of file z3_fixedpoint.h.
Z3_fixedpoint_reduce_app_callback_fptr
typedef void Z3_fixedpoint_reduce_app_callback_fptr(void *, Z3_func_decl, unsigned, Z3_ast const[], Z3_ast *)
Definition at line 318 of file z3_fixedpoint.h.
Z3_fixedpoint_reduce_assign_callback_fptr
typedef void Z3_fixedpoint_reduce_assign_callback_fptr(void *, Z3_func_decl, unsigned, Z3_ast const[], unsigned, Z3_ast const[])
The following utilities allows adding user-defined domains.
Definition at line 313 of file z3_fixedpoint.h.
Z3_fixedpoint_unfold_eh
typedef void(* Z3_fixedpoint_unfold_eh) (void *state)
Definition at line 341 of file z3_fixedpoint.h.
Z3_string
typedef const char* Z3_string
Z3 string type. It is just an alias for const char *.
Most of the types in the C API are opaque pointers.
Z3_config: configuration object used to initialize logical contexts.
Z3_context: manager of all other Z3 objects, global configuration options, etc.
Z3_symbol: Lisp-like symbol used to name types, constants, and functions. A symbol can be created using string or integers.
Z3_ast: abstract syntax tree node. That is, the data-structure used in Z3 to represent terms, formulas and types.
Z3_sort: kind of AST used to represent types.
Z3_func_decl: kind of AST used to represent function symbols.
Z3_app: kind of AST used to represent function applications.
Z3_pattern: kind of AST used to represent pattern and multi-patterns used to guide quantifier instantiation.
Z3_constructor: type constructor for a (recursive) datatype.
Z3_constructor_list: list of constructors for a (recursive) datatype.
Z3_params: parameter set used to configure many components such as: simplifiers, tactics, solvers, etc.
Z3_param_descrs: provides a collection of parameter names, their types, default values and documentation strings. Solvers, tactics, and other objects accept different collection of parameters.
Z3_parser_context: context for incrementally parsing strings. Declarations can be added incrementally to the parser state.
Z3_model: model for the constraints asserted into the logical context.
Z3_func_interp: interpretation of a function in a model.
Z3_func_entry: representation of the value of a Z3_func_interp at a particular point.
Z3_fixedpoint: context for the recursive predicate solver.
Z3_optimize: context for solving optimization queries.
Z3_ast_vector: vector of Z3_ast objects.
Z3_ast_map: mapping from Z3_ast to Z3_ast objects.
Z3_goal: set of formulas that can be solved and/or transformed using tactics and solvers.
Z3_tactic: basic building block for creating custom solvers for specific problem domains.
Z3_simplifier: basic building block for creating custom pre-processing simplifiers.
Z3_probe: function/predicate used to inspect a goal and collect information that may be used to decide which solver and/or preprocessing step will be used.
Z3_apply_result: collection of subgoals resulting from applying of a tactic to a goal.
Z3_solver: (incremental) solver, possibly specialized by a particular tactic or logic.
Z3_stats: statistical data for a solver.
Definition at line 50 of file z3_api.h.
Z3_string_ptr
typedef Z3_string* Z3_string_ptr
Definition at line 52 of file z3_api.h.
Enumeration Type Documentation
Z3_ast_kind
enum Z3_ast_kind
The different kinds of Z3 AST (abstract syntax trees). That is, terms, formulas and types.
Z3_APP_AST: constant and applications
Z3_NUMERAL_AST: numeral constants
Z3_VAR_AST: bound variables
Z3_QUANTIFIER_AST: quantifiers
Z3_SORT_AST: sort
Z3_FUNC_DECL_AST: function declaration
Z3_UNKNOWN_AST: internal
Enumerator
Z3_NUMERAL_AST
Z3_APP_AST
Z3_VAR_AST
Z3_QUANTIFIER_AST
Z3_SORT_AST
Z3_FUNC_DECL_AST
Z3_UNKNOWN_AST
Definition at line 141 of file z3_api.h.
{
    Z3_NUMERAL_AST,
    Z3_APP_AST,
    Z3_VAR_AST,
    Z3_QUANTIFIER_AST,
    Z3_SORT_AST,
    Z3_FUNC_DECL_AST,
    Z3_UNKNOWN_AST = 1000
} Z3_ast_kind;
Z3_ast_print_mode
enum Z3_ast_print_mode
Z3 pretty printing modes (See Z3_set_ast_print_mode).
Z3_PRINT_SMTLIB_FULL: Print AST nodes in SMTLIB verbose format.
Z3_PRINT_LOW_LEVEL: Print AST nodes using a low-level format.
Z3_PRINT_SMTLIB2_COMPLIANT: Print AST nodes in SMTLIB 2.x compliant format.
Enumerator
Z3_PRINT_SMTLIB_FULL
Z3_PRINT_LOW_LEVEL
Z3_PRINT_SMTLIB2_COMPLIANT
Definition at line 1322 of file z3_api.h.
             {
    Z3_PRINT_SMTLIB_FULL,
    Z3_PRINT_LOW_LEVEL,
    Z3_PRINT_SMTLIB2_COMPLIANT
} Z3_ast_print_mode;
Z3_decl_kind
enum Z3_decl_kind
The different kinds of interpreted function kinds.
Z3_OP_TRUE The constant true.
Z3_OP_FALSE The constant false.
Z3_OP_EQ The equality predicate.
Z3_OP_DISTINCT The n-ary distinct predicate (every argument is mutually distinct).
Z3_OP_ITE The ternary if-then-else term.
Z3_OP_AND n-ary conjunction.
Z3_OP_OR n-ary disjunction.
Z3_OP_IFF equivalence (binary).
Z3_OP_XOR Exclusive or.
Z3_OP_NOT Negation.
Z3_OP_IMPLIES Implication.
Z3_OP_OEQ Binary equivalence modulo namings. This binary predicate is used in proof terms. It captures equisatisfiability and equivalence modulo renamings.
Z3_OP_ANUM Arithmetic numeral.
Z3_OP_AGNUM Arithmetic algebraic numeral. Algebraic numbers are used to represent irrational numbers in Z3.
Z3_OP_LE <=.
Z3_OP_GE >=.
Z3_OP_LT <.
Z3_OP_GT >.
Z3_OP_ADD Addition - Binary.
Z3_OP_SUB Binary subtraction.
Z3_OP_UMINUS Unary minus.
Z3_OP_MUL Multiplication - Binary.
Z3_OP_DIV Division - Binary.
Z3_OP_IDIV Integer division - Binary.
Z3_OP_REM Remainder - Binary.
Z3_OP_MOD Modulus - Binary.
Z3_OP_TO_REAL Coercion of integer to real - Unary.
Z3_OP_TO_INT Coercion of real to integer - Unary.
Z3_OP_IS_INT Check if real is also an integer - Unary.
Z3_OP_POWER Power operator x^y.
Z3_OP_STORE Array store. It satisfies select(store(a,i,v),j) = if i = j then v else select(a,j). Array store takes at least 3 arguments.
Z3_OP_SELECT Array select.
Z3_OP_CONST_ARRAY The constant array. For example, select(const(v),i) = v holds for every v and i. The function is unary.
Z3_OP_ARRAY_DEFAULT Default value of arrays. For example default(const(v)) = v. The function is unary.
Z3_OP_ARRAY_MAP Array map operator. It satisfies mapf[i] = f(a1[i],...,a_n[i]) for every i.
Z3_OP_SET_UNION Set union between two Boolean arrays (two arrays whose range type is Boolean). The function is binary.
Z3_OP_SET_INTERSECT Set intersection between two Boolean arrays. The function is binary.
Z3_OP_SET_DIFFERENCE Set difference between two Boolean arrays. The function is binary.
Z3_OP_SET_COMPLEMENT Set complement of a Boolean array. The function is unary.
Z3_OP_SET_SUBSET Subset predicate between two Boolean arrays. The relation is binary.
Z3_OP_AS_ARRAY An array value that behaves as the function graph of the function passed as parameter.
Z3_OP_ARRAY_EXT Array extensionality function. It takes two arrays as arguments and produces an index, such that the arrays are different if they are different on the index.
Z3_OP_BNUM Bit-vector numeral.
Z3_OP_BIT1 One bit bit-vector.
Z3_OP_BIT0 Zero bit bit-vector.
Z3_OP_BNEG Unary minus.
Z3_OP_BADD Binary addition.
Z3_OP_BSUB Binary subtraction.
Z3_OP_BMUL Binary multiplication.
Z3_OP_BSDIV Binary signed division.
Z3_OP_BUDIV Binary unsigned division.
Z3_OP_BSREM Binary signed remainder.
Z3_OP_BUREM Binary unsigned remainder.
Z3_OP_BSMOD Binary signed modulus.
Z3_OP_BSDIV0 Unary function. bsdiv(x,0) is congruent to bsdiv0(x).
Z3_OP_BUDIV0 Unary function. budiv(x,0) is congruent to budiv0(x).
Z3_OP_BSREM0 Unary function. bsrem(x,0) is congruent to bsrem0(x).
Z3_OP_BUREM0 Unary function. burem(x,0) is congruent to burem0(x).
Z3_OP_BSMOD0 Unary function. bsmod(x,0) is congruent to bsmod0(x).
Z3_OP_ULEQ Unsigned bit-vector <= - Binary relation.
Z3_OP_SLEQ Signed bit-vector <= - Binary relation.
Z3_OP_UGEQ Unsigned bit-vector >= - Binary relation.
Z3_OP_SGEQ Signed bit-vector >= - Binary relation.
Z3_OP_ULT Unsigned bit-vector < - Binary relation.
Z3_OP_SLT Signed bit-vector < - Binary relation.
Z3_OP_UGT Unsigned bit-vector > - Binary relation.
Z3_OP_SGT Signed bit-vector > - Binary relation.
Z3_OP_BAND Bit-wise and - Binary.
Z3_OP_BOR Bit-wise or - Binary.
Z3_OP_BNOT Bit-wise not - Unary.
Z3_OP_BXOR Bit-wise xor - Binary.
Z3_OP_BNAND Bit-wise nand - Binary.
Z3_OP_BNOR Bit-wise nor - Binary.
Z3_OP_BXNOR Bit-wise xnor - Binary.
Z3_OP_CONCAT Bit-vector concatenation - Binary.
Z3_OP_SIGN_EXT Bit-vector sign extension.
Z3_OP_ZERO_EXT Bit-vector zero extension.
Z3_OP_EXTRACT Bit-vector extraction.
Z3_OP_REPEAT Repeat bit-vector n times.
Z3_OP_BREDOR Bit-vector reduce or - Unary.
Z3_OP_BREDAND Bit-vector reduce and - Unary.
Z3_OP_BCOMP .
Z3_OP_BSHL Shift left.
Z3_OP_BLSHR Logical shift right.
Z3_OP_BASHR Arithmetical shift right.
Z3_OP_ROTATE_LEFT Left rotation.
Z3_OP_ROTATE_RIGHT Right rotation.
Z3_OP_EXT_ROTATE_LEFT (extended) Left rotation. Similar to Z3_OP_ROTATE_LEFT, but it is a binary operator instead of a parametric one.
Z3_OP_EXT_ROTATE_RIGHT (extended) Right rotation. Similar to Z3_OP_ROTATE_RIGHT, but it is a binary operator instead of a parametric one.
Z3_OP_INT2BV Coerce integer to bit-vector.
Z3_OP_BV2INT Coerce bit-vector to integer.
Z3_OP_SBV2INT Coerce signed bit-vector to integer.
Z3_OP_CARRY Compute the carry bit in a full-adder. The meaning is given by the equivalence (carry l1 l2 l3) <=> (or (and l1 l2) (and l1 l3) (and l2 l3)))
Z3_OP_XOR3 Compute ternary XOR. The meaning is given by the equivalence (xor3 l1 l2 l3) <=> (xor (xor l1 l2) l3)
Z3_OP_BSMUL_NO_OVFL: a predicate to check that bit-wise signed multiplication does not overflow. Signed multiplication overflows if the operands have the same sign and the result of multiplication does not fit within the available bits.
See also
Z3_mk_bvmul_no_overflow.
Z3_OP_BUMUL_NO_OVFL: check that bit-wise unsigned multiplication does not overflow. Unsigned multiplication overflows if the result does not fit within the available bits.
See also
Z3_mk_bvmul_no_overflow.
Z3_OP_BSMUL_NO_UDFL: check that bit-wise signed multiplication does not underflow. Signed multiplication underflows if the operands have opposite signs and the result of multiplication does not fit within the available bits. Z3_mk_bvmul_no_underflow.
Z3_OP_BSDIV_I: Binary signed division. It has the same semantics as Z3_OP_BSDIV, but created in a context where the second operand can be assumed to be non-zero.
Z3_OP_BUDIV_I: Binary unsigned division. It has the same semantics as Z3_OP_BUDIV, but created in a context where the second operand can be assumed to be non-zero.
Z3_OP_BSREM_I: Binary signed remainder. It has the same semantics as Z3_OP_BSREM, but created in a context where the second operand can be assumed to be non-zero.
Z3_OP_BUREM_I: Binary unsigned remainder. It has the same semantics as Z3_OP_BUREM, but created in a context where the second operand can be assumed to be non-zero.
Z3_OP_BSMOD_I: Binary signed modulus. It has the same semantics as Z3_OP_BSMOD, but created in a context where the second operand can be assumed to be non-zero.
Z3_OP_PR_UNDEF: Undef/Null proof object.
Z3_OP_PR_TRUE: Proof for the expression 'true'.
Z3_OP_PR_ASSERTED: Proof for a fact asserted by the user.
Z3_OP_PR_GOAL: Proof for a fact (tagged as goal) asserted by the user.
Z3_OP_PR_MODUS_PONENS: Given a proof for p and a proof for (implies p q), produces a proof for q.
 T1: p
 T2: (implies p q)
 [mp T1 T2]: q
The second antecedents may also be a proof for (iff p q).
Z3_OP_PR_REFLEXIVITY: A proof for (R t t), where R is a reflexive relation. This proof object has no antecedents. The only reflexive relations that are used are equivalence modulo namings, equality and equivalence. That is, R is either '~', '=' or 'iff'.
Z3_OP_PR_SYMMETRY: Given an symmetric relation R and a proof for (R t s), produces a proof for (R s t).
       T1: (R t s)
       [symmetry T1]: (R s t)
T1 is the antecedent of this proof object.
Z3_OP_PR_TRANSITIVITY: Given a transitive relation R, and proofs for (R t s) and (R s u), produces a proof for (R t u).
    T1: (R t s)
    T2: (R s u)
    [trans T1 T2]: (R t u)
Z3_OP_PR_TRANSITIVITY_STAR: Condensed transitivity proof. It combines several symmetry and transitivity proofs. Example:
       T1: (R a b)
       T2: (R c b)
       T3: (R c d)
       [trans* T1 T2 T3]: (R a d)
R must be a symmetric and transitive relation.
Assuming that this proof object is a proof for (R s t), then a proof checker must check if it is possible to prove (R s t) using the antecedents, symmetry and transitivity. That is, if there is a path from s to t, if we view every antecedent (R a b) as an edge between a and b.
Z3_OP_PR_MONOTONICITY: Monotonicity proof object.
 T1: (R t_1 s_1)
 ...
 Tn: (R t_n s_n)
 [monotonicity T1 ... Tn]: (R (f t_1 ... t_n) (f s_1 ... s_n))
Remark: if t_i == s_i, then the antecedent Ti is suppressed. That is, reflexivity proofs are suppressed to save space.
Z3_OP_PR_QUANT_INTRO: Given a proof for (~ p q), produces a proof for (~ (forall (x) p) (forall (x) q)).
T1: (~ p q)
Z3_OP_PR_BIND: Given a proof p, produces a proof of lambda x . p, where x are free variables in p.
 T1: f
[proof-bind T1] forall (x) f
Z3_OP_PR_DISTRIBUTIVITY: Distributivity proof object. Given that f (= or) distributes over g (= and), produces a proof for
       (= (f a (g c d))
          (g (f a c) (f a d)))
If f and g are associative, this proof also justifies the following equality:
       (= (f (g a b) (g c d))
          (g (f a c) (f a d) (f b c) (f b d)))
where each f and g can have arbitrary number of arguments.
This proof object has no antecedents. Remark. This rule is used by the CNF conversion pass and instantiated by f = or, and g = and.
Z3_OP_PR_AND_ELIM: Given a proof for (and l_1 ... l_n), produces a proof for l_i
T1: (and l_1 ... l_n)
Z3_OP_PR_NOT_OR_ELIM: Given a proof for (not (or l_1 ... l_n)), produces a proof for (not l_i).
T1: (not (or l_1 ... l_n))
[not-or-elim T1]: (not l_i)
Z3_OP_PR_REWRITE: A proof for a local rewriting step (= t s). The head function symbol of t is interpreted.
This proof object has no antecedents. The conclusion of a rewrite rule is either an equality (= t s), an equivalence (iff t s), or equi-satisfiability (~ t s). Remark: if f is bool, then = is iff. Examples:
       (= (+ x 0) x)
       (= (+ x 1 2) (+ 3 x))
       (iff (or x false) x)
Z3_OP_PR_REWRITE_STAR: A proof for rewriting an expression t into an expression s. This proof object can have n antecedents. The antecedents are proofs for equalities used as substitution rules. The proof rule is used in a few cases. The cases are:
When applying contextual simplification (CONTEXT_SIMPLIFIER=true)
When converting bit-vectors to Booleans (BIT2BOOL=true)
Z3_OP_PR_PULL_QUANT: A proof for (iff (f (forall (x) q(x)) r) (forall (x) (f (q x) r))). This proof object has no antecedents.
Z3_OP_PR_PUSH_QUANT: A proof for:
       (iff (forall (x_1 ... x_m) (and p_1[x_1 ... x_m] ... p_n[x_1 ... x_m]))
            (and (forall (x_1 ... x_m) p_1[x_1 ... x_m])
              ...
            (forall (x_1 ... x_m) p_n[x_1 ... x_m])))
This proof object has no antecedents.
Z3_OP_PR_ELIM_UNUSED_VARS: A proof for (iff (forall (x_1 ... x_n y_1 ... y_m) p[x_1 ... x_n]) (forall (x_1 ... x_n) p[x_1 ... x_n]))
It is used to justify the elimination of unused variables. This proof object has no antecedents.
Z3_OP_PR_DER: A proof for destructive equality resolution: (iff (forall (x) (or (not (= x t)) P[x])) P[t]) if x does not occur in t.
This proof object has no antecedents.
Several variables can be eliminated simultaneously.
Z3_OP_PR_QUANT_INST: A proof of (or (not (forall (x) (P x))) (P a))
Z3_OP_PR_HYPOTHESIS: Mark a hypothesis in a natural deduction style proof.
Z3_OP_PR_LEMMA:
 T1: false
 [lemma T1]: (or (not l_1) ... (not l_n))
This proof object has one antecedent: a hypothetical proof for false. It converts the proof in a proof for (or (not l_1) ... (not l_n)), when T1 contains the open hypotheses: l_1, ..., l_n. The hypotheses are closed after an application of a lemma. Furthermore, there are no other open hypotheses in the subtree covered by the lemma.
Z3_OP_PR_UNIT_RESOLUTION:
       T1:      (or l_1 ... l_n l_1' ... l_m')
       T2:      (not l_1)
       ...
       T(n+1):  (not l_n)
       [unit-resolution T1 ... T(n+1)]: (or l_1' ... l_m')
Z3_OP_PR_IFF_TRUE:
    T1: p
    [iff-true T1]: (iff p true)
Z3_OP_PR_IFF_FALSE:
    T1: (not p)
    [iff-false T1]: (iff p false)
Z3_OP_PR_COMMUTATIVITY:
 [comm]: (= (f a b) (f b a))
 f is a commutative operator.
 This proof object has no antecedents.
 Remark: if f is bool, then = is iff.
Z3_OP_PR_DEF_AXIOM: Proof object used to justify Tseitin's like axioms:
       (or (not (and p q)) p)
       (or (not (and p q)) q)
       (or (not (and p q r)) p)
       (or (not (and p q r)) q)
       (or (not (and p q r)) r)
       ...
       (or (and p q) (not p) (not q))
       (or (not (or p q)) p q)
       (or (or p q) (not p))
       (or (or p q) (not q))
       (or (not (iff p q)) (not p) q)
       (or (not (iff p q)) p (not q))
       (or (iff p q) (not p) (not q))
       (or (iff p q) p q)
       (or (not (ite a b c)) (not a) b)
       (or (not (ite a b c)) a c)
       (or (ite a b c) (not a) (not b))
       (or (ite a b c) a (not c))
       (or (not (not a)) (not a))
       (or (not a) a)
This proof object has no antecedents. Note: all axioms are propositional tautologies. Note also that 'and' and 'or' can take multiple arguments. You can recover the propositional tautologies by unfolding the Boolean connectives in the axioms a small bounded number of steps (=3).
Z3_OP_PR_ASSUMPTION_ADD Clausal proof adding axiom
Z3_OP_PR_LEMMA_ADD Clausal proof lemma addition
Z3_OP_PR_REDUNDANT_DEL Clausal proof lemma deletion
Z3_OP_PR_CLAUSE_TRAIL, Clausal proof trail of additions and deletions
Z3_OP_PR_DEF_INTRO: Introduces a name for a formula/term. Suppose e is an expression with free variables x, and def-intro introduces the name n(x). The possible cases are:
When e is of Boolean type:
or:
when e only occurs positively.
When e is of the form (ite cond th el):
Otherwise: [def-intro]: (= n e)
Z3_OP_PR_APPLY_DEF:
[apply-def T1]: F ~ n
F is 'equivalent' to n, given that T1 is a proof that n is a name for F.
Z3_OP_PR_IFF_OEQ:
T1: (iff p q) [iff~ T1]: (~ p q)
Z3_OP_PR_NNF_POS: Proof for a (positive) NNF step. Example:
 T1: (not s_1) ~ r_1
 T2: (not s_2) ~ r_2
 T3: s_1 ~ r_1'
 T4: s_2 ~ r_2'
 [nnf-pos T1 T2 T3 T4]: (~ (iff s_1 s_2) (and (or r_1 r_2') (or r_1' r_2)))
The negation normal form steps NNF_POS and NNF_NEG are used in the following cases: (a) When creating the NNF of a positive force quantifier. The quantifier is retained (unless the bound variables are eliminated). Example
 T1: q ~ q_new
 [nnf-pos T1]: (~ (forall (x T) q) (forall (x T) q_new))
(b) When recursively creating NNF over Boolean formulas, where the top-level connective is changed during NNF conversion. The relevant Boolean connectives for NNF_POS are 'implies', 'iff', 'xor', 'ite'. NNF_NEG furthermore handles the case where negation is pushed over Boolean connectives 'and' and 'or'.
Z3_OP_PR_NNF_NEG: Proof for a (negative) NNF step. Examples:
 T1: (not s_1) ~ r_1
 ...
 Tn: (not s_n) ~ r_n
 [nnf-neg T1 ... Tn]: (not (and s_1 ... s_n)) ~ (or r_1 ... r_n)
 and
 T1: (not s_1) ~ r_1
 ...
 Tn: (not s_n) ~ r_n
 [nnf-neg T1 ... Tn]: (not (or s_1 ... s_n)) ~ (and r_1 ... r_n)
 and
 T1: (not s_1) ~ r_1
 T2: (not s_2) ~ r_2
 T3: s_1 ~ r_1'
 T4: s_2 ~ r_2'
 [nnf-neg T1 T2 T3 T4]: (~ (not (iff s_1 s_2))
                          (and (or r_1 r_2) (or r_1' r_2')))
Z3_OP_PR_SKOLEMIZE: Proof for:
 [sk]: (~ (not (forall x (p x y))) (not (p (sk y) y)))
 [sk]: (~ (exists x (p x y)) (p (sk y) y))
This proof object has no antecedents.
Z3_OP_PR_MODUS_PONENS_OEQ: Modus ponens style rule for equi-satisfiability.
 T1: p
 T2: (~ p q)
 [mp~ T1 T2]: q
Z3_OP_PR_TH_LEMMA: Generic proof for theory lemmas. The theory lemma function comes with one or more parameters. The first parameter indicates the name of the theory. For the theory of arithmetic, additional parameters provide hints for checking the theory lemma. The hints for arithmetic are:
- farkas - followed by rational coefficients. Multiply the coefficients to the
  inequalities in the lemma, add the (negated) inequalities and obtain a contradiction.
- triangle-eq - Indicates a lemma related to the equivalence:
   (iff (= t1 t2) (and (<= t1 t2) (<= t2 t1)))
- gcd-test - Indicates an integer linear arithmetic lemma that uses a gcd test.
Z3_OP_PR_HYPER_RESOLVE: Hyper-resolution rule.
The premises of the rules is a sequence of clauses. The first clause argument is the main clause of the rule. with a literal from the first (main) clause.
Premises of the rules are of the form
             (or l0 l1 l2 .. ln)
or
          (=> (and l1 l2 .. ln) l0)
or in the most general (ground) form:
          (=> (and ln+1 ln+2 .. ln+m) (or l0 l1 .. ln))
In other words we use the following (Prolog style) convention for Horn implications: The head of a Horn implication is position 0, the first conjunct in the body of an implication is position 1 the second conjunct in the body of an implication is position 2
For general implications where the head is a disjunction, the first n positions correspond to the n disjuncts in the head. The next m positions correspond to the m conjuncts in the body.
The premises can be universally quantified so that the most general non-ground form is:
          (forall (vars) (=> (and ln+1 ln+2 .. ln+m) (or l0 l1 .. ln)))
The hyper-resolution rule takes a sequence of parameters. The parameters are substitutions of bound variables separated by pairs of literal positions from the main clause and side clause.
Z3_OP_RA_STORE: Insert a record into a relation. The function takes n+1 arguments, where the first argument is the relation and the remaining n elements correspond to the n columns of the relation.
Z3_OP_RA_EMPTY: Creates the empty relation.
Z3_OP_RA_IS_EMPTY: Tests if the relation is empty.
Z3_OP_RA_JOIN: Create the relational join.
Z3_OP_RA_UNION: Create the union or convex hull of two relations. The function takes two arguments.
Z3_OP_RA_WIDEN: Widen two relations. The function takes two arguments.
Z3_OP_RA_PROJECT: Project the columns (provided as numbers in the parameters). The function takes one argument.
Z3_OP_RA_FILTER: Filter (restrict) a relation with respect to a predicate. The first argument is a relation. The second argument is a predicate with free de-Bruijn indices corresponding to the columns of the relation. So the first column in the relation has index 0.
Z3_OP_RA_NEGATION_FILTER: Intersect the first relation with respect to negation of the second relation (the function takes two arguments). Logically, the specification can be described by a function
target = filter_by_negation(pos, neg, columns)
where columns are pairs c1, d1, .., cN, dN of columns from pos and neg, such that target are elements in x in pos, such that there is no y in neg that agrees with x on the columns c1, d1, .., cN, dN.
Z3_OP_RA_RENAME: rename columns in the relation. The function takes one argument. The parameters contain the renaming as a cycle.
Z3_OP_RA_COMPLEMENT: Complement the relation.
Z3_OP_RA_SELECT: Check if a record is an element of the relation. The function takes n+1 arguments, where the first argument is a relation, and the remaining n arguments correspond to a record.
Z3_OP_RA_CLONE: Create a fresh copy (clone) of a relation. The function is logically the identity, but in the context of a register machine allows for Z3_OP_RA_UNION to perform destructive updates to the first argument.
Z3_OP_FD_LT: A less than predicate over the finite domain Z3_FINITE_DOMAIN_SORT.
Z3_OP_LABEL: A label (used by the Boogie Verification condition generator). The label has two parameters, a string and a Boolean polarity. It takes one argument, a formula.
Z3_OP_LABEL_LIT: A label literal (used by the Boogie Verification condition generator). A label literal has a set of string parameters. It takes no arguments.
Z3_OP_DT_CONSTRUCTOR: datatype constructor.
Z3_OP_DT_RECOGNISER: datatype recognizer.
Z3_OP_DT_IS: datatype recognizer.
Z3_OP_DT_ACCESSOR: datatype accessor.
Z3_OP_DT_UPDATE_FIELD: datatype field update.
Z3_OP_PB_AT_MOST: Cardinality constraint. E.g., x + y + z <= 2
Z3_OP_PB_AT_LEAST: Cardinality constraint. E.g., x + y + z >= 2
Z3_OP_PB_LE: Generalized Pseudo-Boolean cardinality constraint. Example 2*x + 3*y <= 4
Z3_OP_PB_GE: Generalized Pseudo-Boolean cardinality constraint. Example 2*x + 3*y + 2*z >= 4
Z3_OP_PB_EQ: Generalized Pseudo-Boolean equality constraint. Example 2*x + 1*y + 2*z + 1*u = 4
Z3_OP_SPECIAL_RELATION_LO: A relation that is a total linear order
Z3_OP_SPECIAL_RELATION_PO: A relation that is a partial order
Z3_OP_SPECIAL_RELATION_PLO: A relation that is a piecewise linear order
Z3_OP_SPECIAL_RELATION_TO: A relation that is a tree order
Z3_OP_SPECIAL_RELATION_TC: Transitive closure of a relation
Z3_OP_SPECIAL_RELATION_TRC: Transitive reflexive closure of a relation
Z3_OP_FPA_RM_NEAREST_TIES_TO_EVEN: Floating-point rounding mode RNE
Z3_OP_FPA_RM_NEAREST_TIES_TO_AWAY: Floating-point rounding mode RNA
Z3_OP_FPA_RM_TOWARD_POSITIVE: Floating-point rounding mode RTP
Z3_OP_FPA_RM_TOWARD_NEGATIVE: Floating-point rounding mode RTN
Z3_OP_FPA_RM_TOWARD_ZERO: Floating-point rounding mode RTZ
Z3_OP_FPA_NUM: Floating-point value
Z3_OP_FPA_PLUS_INF: Floating-point +oo
Z3_OP_FPA_MINUS_INF: Floating-point -oo
Z3_OP_FPA_NAN: Floating-point NaN
Z3_OP_FPA_PLUS_ZERO: Floating-point +zero
Z3_OP_FPA_MINUS_ZERO: Floating-point -zero
Z3_OP_FPA_ADD: Floating-point addition
Z3_OP_FPA_SUB: Floating-point subtraction
Z3_OP_FPA_NEG: Floating-point negation
Z3_OP_FPA_MUL: Floating-point multiplication
Z3_OP_FPA_DIV: Floating-point division
Z3_OP_FPA_REM: Floating-point remainder
Z3_OP_FPA_ABS: Floating-point absolute value
Z3_OP_FPA_MIN: Floating-point minimum
Z3_OP_FPA_MAX: Floating-point maximum
Z3_OP_FPA_FMA: Floating-point fused multiply-add
Z3_OP_FPA_SQRT: Floating-point square root
Z3_OP_FPA_ROUND_TO_INTEGRAL: Floating-point round to integral
Z3_OP_FPA_EQ: Floating-point equality
Z3_OP_FPA_LT: Floating-point less than
Z3_OP_FPA_GT: Floating-point greater than
Z3_OP_FPA_LE: Floating-point less than or equal
Z3_OP_FPA_GE: Floating-point greater than or equal
Z3_OP_FPA_IS_NAN: Floating-point isNaN
Z3_OP_FPA_IS_INF: Floating-point isInfinite
Z3_OP_FPA_IS_ZERO: Floating-point isZero
Z3_OP_FPA_IS_NORMAL: Floating-point isNormal
Z3_OP_FPA_IS_SUBNORMAL: Floating-point isSubnormal
Z3_OP_FPA_IS_NEGATIVE: Floating-point isNegative
Z3_OP_FPA_IS_POSITIVE: Floating-point isPositive
Z3_OP_FPA_FP: Floating-point constructor from 3 bit-vectors
Z3_OP_FPA_TO_FP: Floating-point conversion (various)
Z3_OP_FPA_TO_FP_UNSIGNED: Floating-point conversion from unsigned bit-vector
Z3_OP_FPA_TO_UBV: Floating-point conversion to unsigned bit-vector
Z3_OP_FPA_TO_SBV: Floating-point conversion to signed bit-vector
Z3_OP_FPA_TO_REAL: Floating-point conversion to real number
Z3_OP_FPA_TO_IEEE_BV: Floating-point conversion to IEEE-754 bit-vector
Z3_OP_FPA_BVWRAP: (Implicitly) represents the internal bitvector- representation of a floating-point term (used for the lazy encoding of non-relevant terms in theory_fpa)
Z3_OP_FPA_BV2RM: Conversion of a 3-bit bit-vector term to a floating-point rounding-mode term
The conversion uses the following values: 0 = 000 = Z3_OP_FPA_RM_NEAREST_TIES_TO_EVEN, 1 = 001 = Z3_OP_FPA_RM_NEAREST_TIES_TO_AWAY, 2 = 010 = Z3_OP_FPA_RM_TOWARD_POSITIVE, 3 = 011 = Z3_OP_FPA_RM_TOWARD_NEGATIVE, 4 = 100 = Z3_OP_FPA_RM_TOWARD_ZERO.
Z3_OP_INTERNAL: internal (often interpreted) symbol, but no additional information is exposed. Tools may use the string representation of the function declaration to obtain more information.
Z3_OP_RECURSIVE: function declared as recursive
Z3_OP_UNINTERPRETED: kind used for uninterpreted symbols.
Enumerator
Z3_OP_TRUE
Z3_OP_FALSE
Z3_OP_EQ
Z3_OP_DISTINCT
Z3_OP_ITE
Z3_OP_AND
Z3_OP_OR
Z3_OP_IFF
Z3_OP_XOR
Z3_OP_NOT
Z3_OP_IMPLIES
Z3_OP_OEQ
Z3_OP_ANUM
Z3_OP_AGNUM
Z3_OP_LE
Z3_OP_GE
Z3_OP_LT
Z3_OP_GT
Z3_OP_ADD
Z3_OP_SUB
Z3_OP_UMINUS
Z3_OP_MUL
Z3_OP_DIV
Z3_OP_IDIV
Z3_OP_REM
Z3_OP_MOD
Z3_OP_TO_REAL
Z3_OP_TO_INT
Z3_OP_IS_INT
Z3_OP_POWER
Z3_OP_ABS
Z3_OP_STORE
Z3_OP_SELECT
Z3_OP_CONST_ARRAY
Z3_OP_ARRAY_MAP
Z3_OP_ARRAY_DEFAULT
Z3_OP_SET_UNION
Z3_OP_SET_INTERSECT
Z3_OP_SET_DIFFERENCE
Z3_OP_SET_COMPLEMENT
Z3_OP_SET_SUBSET
Z3_OP_AS_ARRAY
Z3_OP_ARRAY_EXT
Z3_OP_BNUM
Z3_OP_BIT1
Z3_OP_BIT0
Z3_OP_BNEG
Z3_OP_BADD
Z3_OP_BSUB
Z3_OP_BMUL
Z3_OP_BSDIV
Z3_OP_BUDIV
Z3_OP_BSREM
Z3_OP_BUREM
Z3_OP_BSMOD
Z3_OP_BSDIV0
Z3_OP_BUDIV0
Z3_OP_BSREM0
Z3_OP_BUREM0
Z3_OP_BSMOD0
Z3_OP_ULEQ
Z3_OP_SLEQ
Z3_OP_UGEQ
Z3_OP_SGEQ
Z3_OP_ULT
Z3_OP_SLT
Z3_OP_UGT
Z3_OP_SGT
Z3_OP_BAND
Z3_OP_BOR
Z3_OP_BNOT
Z3_OP_BXOR
Z3_OP_BNAND
Z3_OP_BNOR
Z3_OP_BXNOR
Z3_OP_CONCAT
Z3_OP_SIGN_EXT
Z3_OP_ZERO_EXT
Z3_OP_EXTRACT
Z3_OP_REPEAT
Z3_OP_BREDOR
Z3_OP_BREDAND
Z3_OP_BCOMP
Z3_OP_BSHL
Z3_OP_BLSHR
Z3_OP_BASHR
Z3_OP_ROTATE_LEFT
Z3_OP_ROTATE_RIGHT
Z3_OP_EXT_ROTATE_LEFT
Z3_OP_EXT_ROTATE_RIGHT
Z3_OP_BIT2BOOL
Z3_OP_INT2BV
Z3_OP_BV2INT
Z3_OP_SBV2INT
Z3_OP_CARRY
Z3_OP_XOR3
Z3_OP_BSMUL_NO_OVFL
Z3_OP_BUMUL_NO_OVFL
Z3_OP_BSMUL_NO_UDFL
Z3_OP_BSDIV_I
Z3_OP_BUDIV_I
Z3_OP_BSREM_I
Z3_OP_BUREM_I
Z3_OP_BSMOD_I
Z3_OP_PR_UNDEF
Z3_OP_PR_TRUE
Z3_OP_PR_ASSERTED
Z3_OP_PR_GOAL
Z3_OP_PR_MODUS_PONENS
Z3_OP_PR_REFLEXIVITY
Z3_OP_PR_SYMMETRY
Z3_OP_PR_TRANSITIVITY
Z3_OP_PR_TRANSITIVITY_STAR
Z3_OP_PR_MONOTONICITY
Z3_OP_PR_QUANT_INTRO
Z3_OP_PR_BIND
Z3_OP_PR_DISTRIBUTIVITY
Z3_OP_PR_AND_ELIM
Z3_OP_PR_NOT_OR_ELIM
Z3_OP_PR_REWRITE
Z3_OP_PR_REWRITE_STAR
Z3_OP_PR_PULL_QUANT
Z3_OP_PR_PUSH_QUANT
Z3_OP_PR_ELIM_UNUSED_VARS
Z3_OP_PR_DER
Z3_OP_PR_QUANT_INST
Z3_OP_PR_HYPOTHESIS
Z3_OP_PR_LEMMA
Z3_OP_PR_UNIT_RESOLUTION
Z3_OP_PR_IFF_TRUE
Z3_OP_PR_IFF_FALSE
Z3_OP_PR_COMMUTATIVITY
Z3_OP_PR_DEF_AXIOM
Z3_OP_PR_ASSUMPTION_ADD
Z3_OP_PR_LEMMA_ADD
Z3_OP_PR_REDUNDANT_DEL
Z3_OP_PR_CLAUSE_TRAIL
Z3_OP_PR_DEF_INTRO
Z3_OP_PR_APPLY_DEF
Z3_OP_PR_IFF_OEQ
Z3_OP_PR_NNF_POS
Z3_OP_PR_NNF_NEG
Z3_OP_PR_SKOLEMIZE
Z3_OP_PR_MODUS_PONENS_OEQ
Z3_OP_PR_TH_LEMMA
Z3_OP_PR_HYPER_RESOLVE
Z3_OP_RA_STORE
Z3_OP_RA_EMPTY
Z3_OP_RA_IS_EMPTY
Z3_OP_RA_JOIN
Z3_OP_RA_UNION
Z3_OP_RA_WIDEN
Z3_OP_RA_PROJECT
Z3_OP_RA_FILTER
Z3_OP_RA_NEGATION_FILTER
Z3_OP_RA_RENAME
Z3_OP_RA_COMPLEMENT
Z3_OP_RA_SELECT
Z3_OP_RA_CLONE
Z3_OP_FD_CONSTANT
Z3_OP_FD_LT
Z3_OP_SEQ_UNIT
Z3_OP_SEQ_EMPTY
Z3_OP_SEQ_CONCAT
Z3_OP_SEQ_PREFIX
Z3_OP_SEQ_SUFFIX
Z3_OP_SEQ_CONTAINS
Z3_OP_SEQ_EXTRACT
Z3_OP_SEQ_REPLACE
Z3_OP_SEQ_REPLACE_RE
Z3_OP_SEQ_REPLACE_RE_ALL
Z3_OP_SEQ_REPLACE_ALL
Z3_OP_SEQ_AT
Z3_OP_SEQ_NTH
Z3_OP_SEQ_LENGTH
Z3_OP_SEQ_INDEX
Z3_OP_SEQ_LAST_INDEX
Z3_OP_SEQ_TO_RE
Z3_OP_SEQ_IN_RE
Z3_OP_SEQ_MAP
Z3_OP_SEQ_MAPI
Z3_OP_SEQ_FOLDL
Z3_OP_SEQ_FOLDLI
Z3_OP_STR_TO_INT
Z3_OP_INT_TO_STR
Z3_OP_UBV_TO_STR
Z3_OP_SBV_TO_STR
Z3_OP_STR_TO_CODE
Z3_OP_STR_FROM_CODE
Z3_OP_STRING_LT
Z3_OP_STRING_LE
Z3_OP_RE_PLUS
Z3_OP_RE_STAR
Z3_OP_RE_OPTION
Z3_OP_RE_CONCAT
Z3_OP_RE_UNION
Z3_OP_RE_RANGE
Z3_OP_RE_DIFF
Z3_OP_RE_INTERSECT
Z3_OP_RE_LOOP
Z3_OP_RE_POWER
Z3_OP_RE_COMPLEMENT
Z3_OP_RE_EMPTY_SET
Z3_OP_RE_FULL_SET
Z3_OP_RE_FULL_CHAR_SET
Z3_OP_RE_OF_PRED
Z3_OP_RE_REVERSE
Z3_OP_RE_DERIVATIVE
Z3_OP_CHAR_CONST
Z3_OP_CHAR_LE
Z3_OP_CHAR_TO_INT
Z3_OP_CHAR_TO_BV
Z3_OP_CHAR_FROM_BV
Z3_OP_CHAR_IS_DIGIT
Z3_OP_LABEL
Z3_OP_LABEL_LIT
Z3_OP_DT_CONSTRUCTOR
Z3_OP_DT_RECOGNISER
Z3_OP_DT_IS
Z3_OP_DT_ACCESSOR
Z3_OP_DT_UPDATE_FIELD
Z3_OP_PB_AT_MOST
Z3_OP_PB_AT_LEAST
Z3_OP_PB_LE
Z3_OP_PB_GE
Z3_OP_PB_EQ
Z3_OP_SPECIAL_RELATION_LO
Z3_OP_SPECIAL_RELATION_PO
Z3_OP_SPECIAL_RELATION_PLO
Z3_OP_SPECIAL_RELATION_TO
Z3_OP_SPECIAL_RELATION_TC
Z3_OP_SPECIAL_RELATION_TRC
Z3_OP_FPA_RM_NEAREST_TIES_TO_EVEN
Z3_OP_FPA_RM_NEAREST_TIES_TO_AWAY
Z3_OP_FPA_RM_TOWARD_POSITIVE
Z3_OP_FPA_RM_TOWARD_NEGATIVE
Z3_OP_FPA_RM_TOWARD_ZERO
Z3_OP_FPA_NUM
Z3_OP_FPA_PLUS_INF
Z3_OP_FPA_MINUS_INF
Z3_OP_FPA_NAN
Z3_OP_FPA_PLUS_ZERO
Z3_OP_FPA_MINUS_ZERO
Z3_OP_FPA_ADD
Z3_OP_FPA_SUB
Z3_OP_FPA_NEG
Z3_OP_FPA_MUL
Z3_OP_FPA_DIV
Z3_OP_FPA_REM
Z3_OP_FPA_ABS
Z3_OP_FPA_MIN
Z3_OP_FPA_MAX
Z3_OP_FPA_FMA
Z3_OP_FPA_SQRT
Z3_OP_FPA_ROUND_TO_INTEGRAL
Z3_OP_FPA_EQ
Z3_OP_FPA_LT
Z3_OP_FPA_GT
Z3_OP_FPA_LE
Z3_OP_FPA_GE
Z3_OP_FPA_IS_NAN
Z3_OP_FPA_IS_INF
Z3_OP_FPA_IS_ZERO
Z3_OP_FPA_IS_NORMAL
Z3_OP_FPA_IS_SUBNORMAL
Z3_OP_FPA_IS_NEGATIVE
Z3_OP_FPA_IS_POSITIVE
Z3_OP_FPA_FP
Z3_OP_FPA_TO_FP
Z3_OP_FPA_TO_FP_UNSIGNED
Z3_OP_FPA_TO_UBV
Z3_OP_FPA_TO_SBV
Z3_OP_FPA_TO_REAL
Z3_OP_FPA_TO_IEEE_BV
Z3_OP_FPA_BVWRAP
Z3_OP_FPA_BV2RM
Z3_OP_INTERNAL
Z3_OP_RECURSIVE
Z3_OP_UNINTERPRETED
Definition at line 962 of file z3_api.h.
             {
    // Basic
    Z3_OP_TRUE = 0x100,
    Z3_OP_FALSE,
    Z3_OP_EQ,
    Z3_OP_DISTINCT,
    Z3_OP_ITE,
    Z3_OP_AND,
    Z3_OP_OR,
    Z3_OP_IFF,
    Z3_OP_XOR,
    Z3_OP_NOT,
    Z3_OP_IMPLIES,
    Z3_OP_OEQ,
    // Arithmetic
    Z3_OP_ANUM = 0x200,
    Z3_OP_AGNUM,
    Z3_OP_LE,
    Z3_OP_GE,
    Z3_OP_LT,
    Z3_OP_GT,
    Z3_OP_ADD,
    Z3_OP_SUB,
    Z3_OP_UMINUS,
    Z3_OP_MUL,
    Z3_OP_DIV,
    Z3_OP_IDIV,
    Z3_OP_REM,
    Z3_OP_MOD,
    Z3_OP_TO_REAL,
    Z3_OP_TO_INT,
    Z3_OP_IS_INT,
    Z3_OP_POWER,
    Z3_OP_ABS,
    // Arrays & Sets
    Z3_OP_STORE = 0x300,
    Z3_OP_SELECT,
    Z3_OP_CONST_ARRAY,
    Z3_OP_ARRAY_MAP,
    Z3_OP_ARRAY_DEFAULT,
    Z3_OP_SET_UNION,
    Z3_OP_SET_INTERSECT,
    Z3_OP_SET_DIFFERENCE,
    Z3_OP_SET_COMPLEMENT,
    Z3_OP_SET_SUBSET,
    Z3_OP_AS_ARRAY,
    Z3_OP_ARRAY_EXT,
    // Bit-vectors
    Z3_OP_BNUM = 0x400,
    Z3_OP_BIT1,
    Z3_OP_BIT0,
    Z3_OP_BNEG,
    Z3_OP_BADD,
    Z3_OP_BSUB,
    Z3_OP_BMUL,
    Z3_OP_BSDIV,
    Z3_OP_BUDIV,
    Z3_OP_BSREM,
    Z3_OP_BUREM,
    Z3_OP_BSMOD,
    // special functions to record the division by 0 cases
    // these are internal functions
    Z3_OP_BSDIV0,
    Z3_OP_BUDIV0,
    Z3_OP_BSREM0,
    Z3_OP_BUREM0,
    Z3_OP_BSMOD0,
    Z3_OP_ULEQ,
    Z3_OP_SLEQ,
    Z3_OP_UGEQ,
    Z3_OP_SGEQ,
    Z3_OP_ULT,
    Z3_OP_SLT,
    Z3_OP_UGT,
    Z3_OP_SGT,
    Z3_OP_BAND,
    Z3_OP_BOR,
    Z3_OP_BNOT,
    Z3_OP_BXOR,
    Z3_OP_BNAND,
    Z3_OP_BNOR,
    Z3_OP_BXNOR,
    Z3_OP_CONCAT,
    Z3_OP_SIGN_EXT,
    Z3_OP_ZERO_EXT,
    Z3_OP_EXTRACT,
    Z3_OP_REPEAT,
    Z3_OP_BREDOR,
    Z3_OP_BREDAND,
    Z3_OP_BCOMP,
    Z3_OP_BSHL,
    Z3_OP_BLSHR,
    Z3_OP_BASHR,
    Z3_OP_ROTATE_LEFT,
    Z3_OP_ROTATE_RIGHT,
    Z3_OP_EXT_ROTATE_LEFT,
    Z3_OP_EXT_ROTATE_RIGHT,
    Z3_OP_BIT2BOOL,
    Z3_OP_INT2BV,
    Z3_OP_BV2INT,
    Z3_OP_SBV2INT,
    Z3_OP_CARRY,
    Z3_OP_XOR3,
    Z3_OP_BSMUL_NO_OVFL,
    Z3_OP_BUMUL_NO_OVFL,
    Z3_OP_BSMUL_NO_UDFL,
    Z3_OP_BSDIV_I,
    Z3_OP_BUDIV_I,
    Z3_OP_BSREM_I,
    Z3_OP_BUREM_I,
    Z3_OP_BSMOD_I,
    // Proofs
    Z3_OP_PR_UNDEF = 0x500,
    Z3_OP_PR_TRUE,
    Z3_OP_PR_ASSERTED,
    Z3_OP_PR_GOAL,
    Z3_OP_PR_MODUS_PONENS,
    Z3_OP_PR_REFLEXIVITY,
    Z3_OP_PR_SYMMETRY,
    Z3_OP_PR_TRANSITIVITY,
    Z3_OP_PR_TRANSITIVITY_STAR,
    Z3_OP_PR_MONOTONICITY,
    Z3_OP_PR_QUANT_INTRO,
    Z3_OP_PR_BIND,
    Z3_OP_PR_DISTRIBUTIVITY,
    Z3_OP_PR_AND_ELIM,
    Z3_OP_PR_NOT_OR_ELIM,
    Z3_OP_PR_REWRITE,
    Z3_OP_PR_REWRITE_STAR,
    Z3_OP_PR_PULL_QUANT,
    Z3_OP_PR_PUSH_QUANT,
    Z3_OP_PR_ELIM_UNUSED_VARS,
    Z3_OP_PR_DER,
    Z3_OP_PR_QUANT_INST,
    Z3_OP_PR_HYPOTHESIS,
    Z3_OP_PR_LEMMA,
    Z3_OP_PR_UNIT_RESOLUTION,
    Z3_OP_PR_IFF_TRUE,
    Z3_OP_PR_IFF_FALSE,
    Z3_OP_PR_COMMUTATIVITY,
    Z3_OP_PR_DEF_AXIOM,
    Z3_OP_PR_ASSUMPTION_ADD,
    Z3_OP_PR_LEMMA_ADD,
    Z3_OP_PR_REDUNDANT_DEL,
    Z3_OP_PR_CLAUSE_TRAIL,
    Z3_OP_PR_DEF_INTRO,
    Z3_OP_PR_APPLY_DEF,
    Z3_OP_PR_IFF_OEQ,
    Z3_OP_PR_NNF_POS,
    Z3_OP_PR_NNF_NEG,
    Z3_OP_PR_SKOLEMIZE,
    Z3_OP_PR_MODUS_PONENS_OEQ,
    Z3_OP_PR_TH_LEMMA,
    Z3_OP_PR_HYPER_RESOLVE,
    // Relational algebra
    Z3_OP_RA_STORE = 0x600,
    Z3_OP_RA_EMPTY,
    Z3_OP_RA_IS_EMPTY,
    Z3_OP_RA_JOIN,
    Z3_OP_RA_UNION,
    Z3_OP_RA_WIDEN,
    Z3_OP_RA_PROJECT,
    Z3_OP_RA_FILTER,
    Z3_OP_RA_NEGATION_FILTER,
    Z3_OP_RA_RENAME,
    Z3_OP_RA_COMPLEMENT,
    Z3_OP_RA_SELECT,
    Z3_OP_RA_CLONE,
    Z3_OP_FD_CONSTANT,
    Z3_OP_FD_LT,
    // Sequences
    Z3_OP_SEQ_UNIT,
    Z3_OP_SEQ_EMPTY,
    Z3_OP_SEQ_CONCAT,
    Z3_OP_SEQ_PREFIX,
    Z3_OP_SEQ_SUFFIX,
    Z3_OP_SEQ_CONTAINS,
    Z3_OP_SEQ_EXTRACT,
    Z3_OP_SEQ_REPLACE,
    Z3_OP_SEQ_REPLACE_RE,
    Z3_OP_SEQ_REPLACE_RE_ALL,
    Z3_OP_SEQ_REPLACE_ALL,
    Z3_OP_SEQ_AT,
    Z3_OP_SEQ_NTH,
    Z3_OP_SEQ_LENGTH,
    Z3_OP_SEQ_INDEX,
    Z3_OP_SEQ_LAST_INDEX,
    Z3_OP_SEQ_TO_RE,
    Z3_OP_SEQ_IN_RE,
    Z3_OP_SEQ_MAP,
    Z3_OP_SEQ_MAPI,
    Z3_OP_SEQ_FOLDL,
    Z3_OP_SEQ_FOLDLI,
    // strings
    Z3_OP_STR_TO_INT,
    Z3_OP_INT_TO_STR,
    Z3_OP_UBV_TO_STR,
    Z3_OP_SBV_TO_STR,
    Z3_OP_STR_TO_CODE,
    Z3_OP_STR_FROM_CODE,
    Z3_OP_STRING_LT,
    Z3_OP_STRING_LE,
    // regular expressions
    Z3_OP_RE_PLUS,
    Z3_OP_RE_STAR,
    Z3_OP_RE_OPTION,
    Z3_OP_RE_CONCAT,
    Z3_OP_RE_UNION,
    Z3_OP_RE_RANGE,
    Z3_OP_RE_DIFF,
    Z3_OP_RE_INTERSECT,
    Z3_OP_RE_LOOP,
    Z3_OP_RE_POWER,
    Z3_OP_RE_COMPLEMENT,
    Z3_OP_RE_EMPTY_SET,
    Z3_OP_RE_FULL_SET,
    Z3_OP_RE_FULL_CHAR_SET,
    Z3_OP_RE_OF_PRED,
    Z3_OP_RE_REVERSE,
    Z3_OP_RE_DERIVATIVE,
    // char
    Z3_OP_CHAR_CONST,
    Z3_OP_CHAR_LE,
    Z3_OP_CHAR_TO_INT,
    Z3_OP_CHAR_TO_BV,
    Z3_OP_CHAR_FROM_BV,
    Z3_OP_CHAR_IS_DIGIT,
    // Auxiliary
    Z3_OP_LABEL = 0x700,
    Z3_OP_LABEL_LIT,
    // Datatypes
    Z3_OP_DT_CONSTRUCTOR=0x800,
    Z3_OP_DT_RECOGNISER,
    Z3_OP_DT_IS,
    Z3_OP_DT_ACCESSOR,
    Z3_OP_DT_UPDATE_FIELD,
    // Pseudo Booleans
    Z3_OP_PB_AT_MOST=0x900,
    Z3_OP_PB_AT_LEAST,
    Z3_OP_PB_LE,
    Z3_OP_PB_GE,
    Z3_OP_PB_EQ,
    // Special relations
    Z3_OP_SPECIAL_RELATION_LO = 0xa000,
    Z3_OP_SPECIAL_RELATION_PO,
    Z3_OP_SPECIAL_RELATION_PLO,
    Z3_OP_SPECIAL_RELATION_TO,
    Z3_OP_SPECIAL_RELATION_TC,
    Z3_OP_SPECIAL_RELATION_TRC,
    // Floating-Point Arithmetic
    Z3_OP_FPA_RM_NEAREST_TIES_TO_EVEN = 0xb000,
    Z3_OP_FPA_RM_NEAREST_TIES_TO_AWAY,
    Z3_OP_FPA_RM_TOWARD_POSITIVE,
    Z3_OP_FPA_RM_TOWARD_NEGATIVE,
    Z3_OP_FPA_RM_TOWARD_ZERO,
    Z3_OP_FPA_NUM,
    Z3_OP_FPA_PLUS_INF,
    Z3_OP_FPA_MINUS_INF,
    Z3_OP_FPA_NAN,
    Z3_OP_FPA_PLUS_ZERO,
    Z3_OP_FPA_MINUS_ZERO,
    Z3_OP_FPA_ADD,
    Z3_OP_FPA_SUB,
    Z3_OP_FPA_NEG,
    Z3_OP_FPA_MUL,
    Z3_OP_FPA_DIV,
    Z3_OP_FPA_REM,
    Z3_OP_FPA_ABS,
    Z3_OP_FPA_MIN,
    Z3_OP_FPA_MAX,
    Z3_OP_FPA_FMA,
    Z3_OP_FPA_SQRT,
    Z3_OP_FPA_ROUND_TO_INTEGRAL,
    Z3_OP_FPA_EQ,
    Z3_OP_FPA_LT,
    Z3_OP_FPA_GT,
    Z3_OP_FPA_LE,
    Z3_OP_FPA_GE,
    Z3_OP_FPA_IS_NAN,
    Z3_OP_FPA_IS_INF,
    Z3_OP_FPA_IS_ZERO,
    Z3_OP_FPA_IS_NORMAL,
    Z3_OP_FPA_IS_SUBNORMAL,
    Z3_OP_FPA_IS_NEGATIVE,
    Z3_OP_FPA_IS_POSITIVE,
    Z3_OP_FPA_FP,
    Z3_OP_FPA_TO_FP,
    Z3_OP_FPA_TO_FP_UNSIGNED,
    Z3_OP_FPA_TO_UBV,
    Z3_OP_FPA_TO_SBV,
    Z3_OP_FPA_TO_REAL,
    Z3_OP_FPA_TO_IEEE_BV,
    Z3_OP_FPA_BVWRAP,
    Z3_OP_FPA_BV2RM,
    Z3_OP_INTERNAL,
    Z3_OP_RECURSIVE,
    Z3_OP_UNINTERPRETED
} Z3_decl_kind;
Z3_error_code
enum Z3_error_code
Z3 error codes (See Z3_get_error_code).
Z3_OK: No error.
Z3_SORT_ERROR: User tried to build an invalid (type incorrect) AST.
Z3_IOB: Index out of bounds.
Z3_INVALID_ARG: Invalid argument was provided.
Z3_PARSER_ERROR: An error occurred when parsing a string or file.
Z3_NO_PARSER: Parser output is not available, that is, user didn't invoke Z3_parse_smtlib2_string or Z3_parse_smtlib2_file.
Z3_INVALID_PATTERN: Invalid pattern was used to build a quantifier.
Z3_MEMOUT_FAIL: A memory allocation failure was encountered.
Z3_FILE_ACCESS_ERROR: A file could not be accessed.
Z3_INVALID_USAGE: API call is invalid in the current state.
Z3_INTERNAL_FATAL: An error internal to Z3 occurred.
Z3_DEC_REF_ERROR: Trying to decrement the reference counter of an AST that was deleted or the reference counter was not initialized with Z3_inc_ref.
Z3_EXCEPTION: Internal Z3 exception. Additional details can be retrieved using Z3_get_error_msg.
Enumerator
Z3_OK
Z3_SORT_ERROR
Z3_IOB
Z3_INVALID_ARG
Z3_PARSER_ERROR
Z3_NO_PARSER
Z3_INVALID_PATTERN
Z3_MEMOUT_FAIL
Z3_FILE_ACCESS_ERROR
Z3_INTERNAL_FATAL
Z3_INVALID_USAGE
Z3_DEC_REF_ERROR
Z3_EXCEPTION
Definition at line 1346 of file z3_api.h.
{
    Z3_OK,
    Z3_SORT_ERROR,
    Z3_IOB,
    Z3_INVALID_ARG,
    Z3_PARSER_ERROR,
    Z3_NO_PARSER,
    Z3_INVALID_PATTERN,
    Z3_MEMOUT_FAIL,
    Z3_FILE_ACCESS_ERROR,
    Z3_INTERNAL_FATAL,
    Z3_INVALID_USAGE,
    Z3_DEC_REF_ERROR,
    Z3_EXCEPTION
} Z3_error_code;
Z3_goal_prec
enum Z3_goal_prec
Z3 custom error handler (See Z3_set_error_handler).
Definitions for update_api.py
callback functions for user propagator.
A Goal is essentially a set of formulas. Z3 provide APIs for building strategies/tactics for solving and transforming Goals. Some of these transformations apply under/over approximations.
Z3_GOAL_PRECISE: Approximations/Relaxations were not applied on the goal (sat and unsat answers were preserved).
Z3_GOAL_UNDER: Goal is the product of a under-approximation (sat answers are preserved).
Z3_GOAL_OVER: Goal is the product of an over-approximation (unsat answers are preserved).
Z3_GOAL_UNDER_OVER: Goal is garbage (it is the product of over- and under-approximations, sat and unsat answers are not preserved).
Enumerator
Z3_GOAL_PRECISE
Z3_GOAL_UNDER
Z3_GOAL_OVER
Z3_GOAL_UNDER_OVER
Definition at line 1387 of file z3_api.h.
{
    Z3_GOAL_PRECISE,
    Z3_GOAL_UNDER,
    Z3_GOAL_OVER,
    Z3_GOAL_UNDER_OVER
} Z3_goal_prec;
Z3_lbool
enum Z3_lbool
Lifted Boolean type: false, undefined, true.
Enumerator
Z3_L_FALSE
Z3_L_UNDEF
Z3_L_TRUE
Definition at line 57 of file z3_api.h.
{
    Z3_L_FALSE = -1,
    Z3_L_UNDEF,
    Z3_L_TRUE
} Z3_lbool;
Z3_param_kind
enum Z3_param_kind
The different kinds of parameters that can be associated with parameter sets. (see Z3_mk_params).
Z3_PK_UINT integer parameters.
Z3_PK_BOOL boolean parameters.
Z3_PK_DOUBLE double parameters.
Z3_PK_SYMBOL symbol parameters.
Z3_PK_STRING string parameters.
Z3_PK_OTHER all internal parameter kinds which are not exposed in the API.
Z3_PK_INVALID invalid parameter.
Enumerator
Z3_PK_UINT
Z3_PK_BOOL
Z3_PK_DOUBLE
Z3_PK_SYMBOL
Z3_PK_STRING
Z3_PK_OTHER
Z3_PK_INVALID
Definition at line 1305 of file z3_api.h.
             {
    Z3_PK_UINT,
    Z3_PK_BOOL,
    Z3_PK_DOUBLE,
    Z3_PK_SYMBOL,
    Z3_PK_STRING,
    Z3_PK_OTHER,
    Z3_PK_INVALID
} Z3_param_kind;
Z3_parameter_kind
enum Z3_parameter_kind
The different kinds of parameters that can be associated with function symbols.
See also
Z3_get_decl_num_parameters
Z3_get_decl_parameter_kind
Z3_PARAMETER_INT is used for integer parameters.
Z3_PARAMETER_DOUBLE is used for double parameters.
Z3_PARAMETER_RATIONAL is used for parameters that are rational numbers.
Z3_PARAMETER_SYMBOL is used for parameters that are symbols.
Z3_PARAMETER_SORT is used for sort parameters.
Z3_PARAMETER_AST is used for expression parameters.
Z3_PARAMETER_FUNC_DECL is used for function declaration parameters.
Z3_PARAMETER_INTERNAL is used for parameters that are private to Z3. They cannot be accessed.
Z3_PARAMETER_ZSTRING is used for string parameters.
Enumerator
Z3_PARAMETER_INT
Z3_PARAMETER_DOUBLE
Z3_PARAMETER_RATIONAL
Z3_PARAMETER_SYMBOL
Z3_PARAMETER_SORT
Z3_PARAMETER_AST
Z3_PARAMETER_FUNC_DECL
Z3_PARAMETER_INTERNAL
Z3_PARAMETER_ZSTRING
Definition at line 93 of file z3_api.h.
{
    Z3_PARAMETER_INT,
    Z3_PARAMETER_DOUBLE,
    Z3_PARAMETER_RATIONAL,
    Z3_PARAMETER_SYMBOL,
    Z3_PARAMETER_SORT,
    Z3_PARAMETER_AST,
    Z3_PARAMETER_FUNC_DECL,
    Z3_PARAMETER_INTERNAL,
    Z3_PARAMETER_ZSTRING
} Z3_parameter_kind;
Z3_sort_kind
enum Z3_sort_kind
The different kinds of Z3 types (See Z3_get_sort_kind).
Enumerator
Z3_UNINTERPRETED_SORT
Z3_BOOL_SORT
Z3_INT_SORT
Z3_REAL_SORT
Z3_BV_SORT
Z3_ARRAY_SORT
Z3_DATATYPE_SORT
Z3_RELATION_SORT
Z3_FINITE_DOMAIN_SORT
Z3_FLOATING_POINT_SORT
Z3_ROUNDING_MODE_SORT
Z3_SEQ_SORT
Z3_RE_SORT
Z3_CHAR_SORT
Z3_TYPE_VAR
Z3_UNKNOWN_SORT
Definition at line 109 of file z3_api.h.
{
    Z3_UNINTERPRETED_SORT,
    Z3_BOOL_SORT,
    Z3_INT_SORT,
    Z3_REAL_SORT,
    Z3_BV_SORT,
    Z3_ARRAY_SORT,
    Z3_DATATYPE_SORT,
    Z3_RELATION_SORT,
    Z3_FINITE_DOMAIN_SORT,
    Z3_FLOATING_POINT_SORT,
    Z3_ROUNDING_MODE_SORT,
    Z3_SEQ_SORT,
    Z3_RE_SORT,
    Z3_CHAR_SORT,
    Z3_TYPE_VAR,
    Z3_UNKNOWN_SORT = 1000
} Z3_sort_kind;
Z3_symbol_kind
enum Z3_symbol_kind
The different kinds of symbol. In Z3, a symbol can be represented using integers and strings (See Z3_get_symbol_kind).
See also
Z3_mk_int_symbol
Z3_mk_string_symbol
Enumerator
Z3_INT_SYMBOL
Z3_STRING_SYMBOL
Definition at line 71 of file z3_api.h.
{
    Z3_INT_SYMBOL,
    Z3_STRING_SYMBOL
} Z3_symbol_kind;
Function Documentation
Z3_add_const_interp()
void Z3_API Z3_add_const_interp (Z3_context c, Z3_model m, Z3_func_decl f, Z3_ast a)
Add a constant interpretation.
Referenced by model::add_const_interp(), and ModelRef::update_value().
Z3_add_func_interp()
Z3_func_interp Z3_API Z3_add_func_interp (Z3_context c, Z3_model m, Z3_func_decl f, Z3_ast default_value)
Create a fresh func_interp object, add it to a model for a specified function. It has reference count 0.
Parameters
c context
m model
f function declaration
default_value default value for function interpretation
Referenced by model::add_func_interp(), and ModelRef::update_value().
Z3_add_rec_def()
void Z3_API Z3_add_rec_def (Z3_context c, Z3_func_decl f, unsigned n, Z3_ast args[], Z3_ast body)
Define the body of a recursive function.
Parameters
c logical context.
f function declaration.
n number of arguments to the function
args constants that are used as arguments to the recursive function in the definition.
body body of the recursive function
After declaring a recursive function or a collection of mutually recursive functions, use this function to provide the definition for the recursive function.
See also
Z3_mk_rec_func_decl
Referenced by z3py::RecAddDefinition(), and context::recdef().
Z3_algebraic_add()
Z3_ast Z3_API Z3_algebraic_add (Z3_context c, Z3_ast a, Z3_ast b)
Return the value a + b.
Precondition
Z3_algebraic_is_value(c, a)
Z3_algebraic_is_value(c, b)
Postcondition
Z3_algebraic_is_value(c, result)
Z3_algebraic_div()
Z3_ast Z3_API Z3_algebraic_div (Z3_context c, Z3_ast a, Z3_ast b)
Return the value a / b.
Precondition
Z3_algebraic_is_value(c, a)
Z3_algebraic_is_value(c, b)
!Z3_algebraic_is_zero(c, b)
Postcondition
Z3_algebraic_is_value(c, result)
Z3_algebraic_eq()
bool Z3_API Z3_algebraic_eq (Z3_context c, Z3_ast a, Z3_ast b)
Return true if a == b, and false otherwise.
Precondition
Z3_algebraic_is_value(c, a)
Z3_algebraic_is_value(c, b)
Z3_algebraic_eval()
int Z3_API Z3_algebraic_eval (Z3_context c, Z3_ast p, unsigned n, Z3_ast a[])
Given a multivariate polynomial p(x_0, ..., x_{n-1}), return the sign of p(a[0], ..., a[n-1]).
Precondition
p is a Z3 expression that contains only arithmetic terms and free variables.
forall i in [0, n) Z3_algebraic_is_value(c, a[i])
Z3_algebraic_ge()
bool Z3_API Z3_algebraic_ge (Z3_context c, Z3_ast a, Z3_ast b)
Return true if a >= b, and false otherwise.
Precondition
Z3_algebraic_is_value(c, a)
Z3_algebraic_is_value(c, b)
Z3_algebraic_get_i()
unsigned Z3_API Z3_algebraic_get_i (Z3_context c, Z3_ast a)
Return which root of the polynomial the algebraic number represents.
Precondition
Z3_algebraic_is_value(c, a)
Referenced by expr::algebraic_i(), and AlgebraicNumRef::index().
Z3_algebraic_get_poly()
Z3_ast_vector Z3_API Z3_algebraic_get_poly (Z3_context c, Z3_ast a)
Return the coefficients of the defining polynomial.
Precondition
Z3_algebraic_is_value(c, a)
Referenced by expr::algebraic_poly(), and AlgebraicNumRef::poly().
Z3_algebraic_gt()
bool Z3_API Z3_algebraic_gt (Z3_context c, Z3_ast a, Z3_ast b)
Return true if a > b, and false otherwise.
Precondition
Z3_algebraic_is_value(c, a)
Z3_algebraic_is_value(c, b)
Z3_algebraic_is_neg()
bool Z3_API Z3_algebraic_is_neg (Z3_context c, Z3_ast a)
Return true if a is negative, and false otherwise.
Precondition
Z3_algebraic_is_value(c, a)
Z3_algebraic_is_pos()
bool Z3_API Z3_algebraic_is_pos (Z3_context c, Z3_ast a)
Return true if a is positive, and false otherwise.
Precondition
Z3_algebraic_is_value(c, a)
Z3_algebraic_is_value()
bool Z3_API Z3_algebraic_is_value (Z3_context c, Z3_ast a)
Return true if a can be used as value in the Z3 real algebraic number package.
Z3_algebraic_is_zero()
bool Z3_API Z3_algebraic_is_zero (Z3_context c, Z3_ast a)
Return true if a is zero, and false otherwise.
Precondition
Z3_algebraic_is_value(c, a)
Z3_algebraic_le()
bool Z3_API Z3_algebraic_le (Z3_context c, Z3_ast a, Z3_ast b)
Return true if a <= b, and false otherwise.
Precondition
Z3_algebraic_is_value(c, a)
Z3_algebraic_is_value(c, b)
Z3_algebraic_lt()
bool Z3_API Z3_algebraic_lt (Z3_context c, Z3_ast a, Z3_ast b)
Return true if a < b, and false otherwise.
Precondition
Z3_algebraic_is_value(c, a)
Z3_algebraic_is_value(c, b)
Z3_algebraic_mul()
Z3_ast Z3_API Z3_algebraic_mul (Z3_context c, Z3_ast a, Z3_ast b)
Return the value a * b.
Precondition
Z3_algebraic_is_value(c, a)
Z3_algebraic_is_value(c, b)
Postcondition
Z3_algebraic_is_value(c, result)
Z3_algebraic_neq()
bool Z3_API Z3_algebraic_neq (Z3_context c, Z3_ast a, Z3_ast b)
Return true if a != b, and false otherwise.
Precondition
Z3_algebraic_is_value(c, a)
Z3_algebraic_is_value(c, b)
Z3_algebraic_power()
Z3_ast Z3_API Z3_algebraic_power (Z3_context c, Z3_ast a, unsigned k)
Return the a^k.
Precondition
Z3_algebraic_is_value(c, a)
Postcondition
Z3_algebraic_is_value(c, result)
Z3_algebraic_root()
Z3_ast Z3_API Z3_algebraic_root (Z3_context c, Z3_ast a, unsigned k)
Return the a^(1/k)
Precondition
Z3_algebraic_is_value(c, a)
k is even => !Z3_algebraic_is_neg(c, a)
Postcondition
Z3_algebraic_is_value(c, result)
Z3_algebraic_roots()
Z3_ast_vector Z3_API Z3_algebraic_roots (Z3_context c, Z3_ast p, unsigned n, Z3_ast a[])
Given a multivariate polynomial p(x_0, ..., x_{n-1}, x_n), returns the roots of the univariate polynomial p(a[0], ..., a[n-1], x_n).
Precondition
p is a Z3 expression that contains only arithmetic terms and free variables.
forall i in [0, n) Z3_algebraic_is_value(c, a[i])
Postcondition
forall r in result Z3_algebraic_is_value(c, result)
Z3_algebraic_sign()
int Z3_API Z3_algebraic_sign (Z3_context c, Z3_ast a)
Return 1 if a is positive, 0 if a is zero, and -1 if a is negative.
Precondition
Z3_algebraic_is_value(c, a)
Z3_algebraic_sub()
Z3_ast Z3_API Z3_algebraic_sub (Z3_context c, Z3_ast a, Z3_ast b)
Return the value a - b.
Precondition
Z3_algebraic_is_value(c, a)
Z3_algebraic_is_value(c, b)
Postcondition
Z3_algebraic_is_value(c, result)
Z3_app_to_ast()
Z3_ast Z3_API Z3_app_to_ast (Z3_context c, Z3_app a)
Convert a Z3_app into Z3_ast. This is just type casting.
Z3_append_log()
void Z3_API Z3_append_log (Z3_string string)
Append user-defined string to interaction log.
The interaction log is opened using Z3_open_log. It contains the formulas that are checked using Z3. You can use this command to append comments, for instance.
See also
Z3_open_log
Z3_close_log
Referenced by z3py::append_log().
Z3_apply_result_dec_ref()
void Z3_API Z3_apply_result_dec_ref (Z3_context c, Z3_apply_result r)
Decrement the reference counter of the given Z3_apply_result object.
Referenced by apply_result::operator=(), and apply_result::~apply_result().
Z3_apply_result_get_num_subgoals()
unsigned Z3_API Z3_apply_result_get_num_subgoals (Z3_context c, Z3_apply_result r)
Return the number of subgoals in the Z3_apply_result object returned by Z3_tactic_apply.
See also
Z3_apply_result_get_subgoal
Referenced by apply_result::size().
Z3_apply_result_get_subgoal()
Z3_goal Z3_API Z3_apply_result_get_subgoal (Z3_context c, Z3_apply_result r, unsigned i)
Return one of the subgoals in the Z3_apply_result object returned by Z3_tactic_apply.
Precondition
i < Z3_apply_result_get_num_subgoals(c, r)
See also
Z3_apply_result_get_num_subgoals
Referenced by apply_result::operator[]().
Z3_apply_result_inc_ref()
void Z3_API Z3_apply_result_inc_ref (Z3_context c, Z3_apply_result r)
Increment the reference counter of the given Z3_apply_result object.
Referenced by apply_result::operator=().
Z3_apply_result_to_string()
Z3_string Z3_API Z3_apply_result_to_string (Z3_context c, Z3_apply_result r)
Convert the Z3_apply_result object returned by Z3_tactic_apply into a string.
Z3_ast_map_contains()
bool Z3_API Z3_ast_map_contains (Z3_context c, Z3_ast_map m, Z3_ast k)
Return true if the map m contains the AST key k.
Referenced by AstMap::__contains__().
Z3_ast_map_dec_ref()
void Z3_API Z3_ast_map_dec_ref (Z3_context c, Z3_ast_map m)
Decrement the reference counter of the given AST map.
Referenced by AstMap::__del__().
Z3_ast_map_erase()
void Z3_API Z3_ast_map_erase (Z3_context c, Z3_ast_map m, Z3_ast k)
Erase a key from the map.
Referenced by AstMap::erase().
Z3_ast_map_find()
Z3_ast Z3_API Z3_ast_map_find (Z3_context c, Z3_ast_map m, Z3_ast k)
Return the value associated with the key k.
The procedure invokes the error handler if k is not in the map.
Referenced by AstMap::__getitem__().
Z3_ast_map_inc_ref()
void Z3_API Z3_ast_map_inc_ref (Z3_context c, Z3_ast_map m)
Increment the reference counter of the given AST map.
Z3_ast_map_insert()
void Z3_API Z3_ast_map_insert (Z3_context c, Z3_ast_map m, Z3_ast k, Z3_ast v)
Store/Replace a new key, value pair in the given map.
Referenced by AstMap::__setitem__().
Z3_ast_map_keys()
Z3_ast_vector Z3_API Z3_ast_map_keys (Z3_context c, Z3_ast_map m)
Return the keys stored in the given map.
Referenced by AstMap::keys().
Z3_ast_map_reset()
void Z3_API Z3_ast_map_reset (Z3_context c, Z3_ast_map m)
Remove all keys from the given map.
Referenced by AstMap::reset().
Z3_ast_map_size()
unsigned Z3_API Z3_ast_map_size (Z3_context c, Z3_ast_map m)
Return the size of the given map.
Referenced by AstMap::__len__().
Z3_ast_map_to_string()
Z3_string Z3_API Z3_ast_map_to_string (Z3_context c, Z3_ast_map m)
Convert the given map into a string.
Referenced by AstMap::__repr__().
Z3_ast_to_string()
Z3_string Z3_API Z3_ast_to_string (Z3_context c, Z3_ast a)
Convert the given AST node into a string.
Warning
The result buffer is statically allocated by Z3. It will be automatically deallocated when Z3_del_context is invoked. So, the buffer is invalidated in the next call to Z3_ast_to_string.
See also
Z3_pattern_to_string
Z3_sort_to_string
Referenced by AstRef::sexpr(), and ast::to_string().
Z3_ast_vector_dec_ref()
void Z3_API Z3_ast_vector_dec_ref (Z3_context c, Z3_ast_vector v)
Decrement the reference counter of the given AST vector.
Referenced by AstVector::__del__(), ast_vector_tpl< T >::operator=(), and ast_vector_tpl< T >::~ast_vector_tpl().
Z3_ast_vector_get()
Z3_ast Z3_API Z3_ast_vector_get (Z3_context c, Z3_ast_vector v, unsigned i)
Return the AST at position i in the AST vector v.
Precondition
i < Z3_ast_vector_size(c, v)
Referenced by AstVector::__getitem__(), and ast_vector_tpl< T >::operator[]().
Z3_ast_vector_inc_ref()
void Z3_API Z3_ast_vector_inc_ref (Z3_context c, Z3_ast_vector v)
Increment the reference counter of the given AST vector.
Referenced by ast_vector_tpl< T >::ast_vector_tpl(), and ast_vector_tpl< T >::operator=().
Z3_ast_vector_push()
void Z3_API Z3_ast_vector_push (Z3_context c, Z3_ast_vector v, Z3_ast a)
Add the AST a in the end of the AST vector v. The size of v is increased by one.
Referenced by AstVector::push(), and ast_vector_tpl< T >::push_back().
Z3_ast_vector_resize()
void Z3_API Z3_ast_vector_resize (Z3_context c, Z3_ast_vector v, unsigned n)
Resize the AST vector v.
Referenced by AstVector::resize(), and ast_vector_tpl< T >::resize().
Z3_ast_vector_set()
void Z3_API Z3_ast_vector_set (Z3_context c, Z3_ast_vector v, unsigned i, Z3_ast a)
Update position i of the AST vector v with the AST a.
Precondition
i < Z3_ast_vector_size(c, v)
Referenced by AstVector::__setitem__(), ast_vector_tpl< T >::iterator::set(), and ast_vector_tpl< T >::set().
Z3_ast_vector_size()
unsigned Z3_API Z3_ast_vector_size (Z3_context c, Z3_ast_vector v)
Return the size of the given AST vector.
Referenced by AstVector::__len__(), and ast_vector_tpl< T >::size().
Z3_ast_vector_to_string()
Z3_string Z3_API Z3_ast_vector_to_string (Z3_context c, Z3_ast_vector v)
Convert AST vector into a string.
Referenced by AstVector::sexpr(), and ast_vector_tpl< T >::to_string().
Z3_ast_vector_translate()
Z3_ast_vector Z3_API Z3_ast_vector_translate (Z3_context s, Z3_ast_vector v, Z3_context t)
Translate the AST vector v from context s into an AST vector in context t.
Referenced by ast_vector_tpl< T >::ast_vector_tpl(), and AstVector::translate().
Z3_benchmark_to_smtlib_string()
Z3_string Z3_API Z3_benchmark_to_smtlib_string (Z3_context c, Z3_string name, Z3_string logic, Z3_string status, Z3_string attributes, unsigned num_assumptions, Z3_ast const assumptions[], Z3_ast formula)
Convert the given benchmark into SMT-LIB formatted string.
Warning
The result buffer is statically allocated by Z3. It will be automatically deallocated when Z3_del_context is invoked. So, the buffer is invalidated in the next call to Z3_benchmark_to_smtlib_string.
Parameters
c - context.
name - name of benchmark. The argument is optional.
logic - the benchmark logic.
status - the status string (sat, unsat, or unknown)
attributes - other attributes, such as source, difficulty or category.
num_assumptions - number of assumptions.
assumptions - auxiliary assumptions.
formula - formula to be checked for consistency in conjunction with assumptions.
Referenced by solver::to_smt2().
Z3_close_log()
void Z3_API Z3_close_log (void)
Close interaction log.
See also
Z3_open_log
Z3_append_log
Z3_constructor_num_fields()
unsigned Z3_API Z3_constructor_num_fields (Z3_context c, Z3_constructor constr)
Retrieve the number of fields of a constructor.
Parameters
c logical context.
constr constructor.
Z3_datatype_update_field()
Z3_ast Z3_API Z3_datatype_update_field (Z3_context c, Z3_func_decl field_access, Z3_ast t, Z3_ast value)
Update record field with a value.
This corresponds to the 'with' construct in OCaml. It has the effect of updating a record field with a given value. The remaining fields are left unchanged. It is the record equivalent of an array store (see
See also
Z3_mk_store). If the datatype has more than one constructor, then the update function behaves as identity if there is a mismatch between the accessor and constructor. For example ((_ update-field car) nil 1) is nil, while ((_ update-field car) (cons 2 nil) 1) is (cons 1 nil).
Precondition
Z3_get_sort_kind(Z3_get_sort(c, t)) == Z3_get_domain(c, field_access, 1) == Z3_DATATYPE_SORT
Z3_get_sort(c, value) == Z3_get_range(c, field_access)
Z3_dec_ref()
void Z3_API Z3_dec_ref (Z3_context c, Z3_ast a)
Decrement the reference counter of the given AST. The context c should have been created using Z3_mk_context_rc. This function is a NOOP if c was created using Z3_mk_context.
Referenced by AstRef::__del__(), ast::operator=(), and ast::~ast().
Z3_del_config()
void Z3_API Z3_del_config (Z3_config c)
Delete the given configuration object.
See also
Z3_mk_config
Referenced by config::~config().
Z3_del_constructor()
void Z3_API Z3_del_constructor (Z3_context c, Z3_constructor constr)
Reclaim memory allocated to constructor.
Parameters
c logical context.
constr constructor.
See also
Z3_mk_constructor
Referenced by ScopedConstructor::__del__(), and constructors::~constructors().
Z3_del_constructor_list()
void Z3_API Z3_del_constructor_list (Z3_context c, Z3_constructor_list clist)
Reclaim memory allocated for constructor list.
Each constructor inside the constructor list must be independently reclaimed using Z3_del_constructor.
Parameters
c logical context.
clist constructor list container.
See also
Z3_mk_constructor_list
Referenced by ScopedConstructorList::__del__(), and constructor_list::~constructor_list().
Z3_del_context()
void Z3_API Z3_del_context (Z3_context c)
Delete the given logical context.
See also
Z3_mk_context
Referenced by Context::__del__(), and context::~context().
Z3_disable_trace()
void Z3_API Z3_disable_trace (Z3_string tag)
Disable tracing messages tagged as tag when Z3 is compiled in debug mode. It is a NOOP otherwise.
See also
Z3_enable_trace
Referenced by z3py::disable_trace().
Z3_enable_concurrent_dec_ref()
void Z3_API Z3_enable_concurrent_dec_ref (Z3_context c)
use concurrency control for dec-ref. Reference counting decrements are allowed in separate threads from the context. If this setting is not invoked, reference counting decrements are not going to be thread safe.
Z3_enable_trace()
void Z3_API Z3_enable_trace (Z3_string tag)
Enable tracing messages tagged as tag when Z3 is compiled in debug mode. It is a NOOP otherwise.
See also
Z3_disable_trace
Referenced by z3py::enable_trace().
Z3_eval_smtlib2_string()
Z3_string Z3_API Z3_eval_smtlib2_string (Z3_context c, Z3_string str)
Parse and evaluate and SMT-LIB2 command sequence. The state from a previous call is saved so the next evaluation builds on top of the previous call.
Returns
output generated from processing commands.
Z3_finalize_memory()
void Z3_API Z3_finalize_memory (void)
Destroy all allocated resources.
Any pointers previously returned by the API become invalid. Can be used for memory leak detection.
Z3_fixedpoint_add_callback()
void Z3_API Z3_fixedpoint_add_callback (Z3_context ctx, Z3_fixedpoint f, void * state, Z3_fixedpoint_new_lemma_eh new_lemma_eh, Z3_fixedpoint_predecessor_eh predecessor_eh, Z3_fixedpoint_unfold_eh unfold_eh)
set export callback for lemmas
Z3_fixedpoint_add_constraint()
void Z3_API Z3_fixedpoint_add_constraint (Z3_context c, Z3_fixedpoint d, Z3_ast e, unsigned lvl)
Z3_fixedpoint_add_cover()
void Z3_API Z3_fixedpoint_add_cover (Z3_context c, Z3_fixedpoint d, int level, Z3_func_decl pred, Z3_ast property)
Add property about the predicate pred. Add a property of predicate pred at level. It gets pushed forward when possible.
Note: level = -1 is treated as the fixedpoint. So passing -1 for the level means that the property is true of the fixed-point unfolding with respect to pred.
Note: this functionality is PDR specific.
Referenced by fixedpoint::add_cover().
Z3_fixedpoint_add_fact()
void Z3_API Z3_fixedpoint_add_fact (Z3_context c, Z3_fixedpoint d, Z3_func_decl r, unsigned num_args, unsigned args[])
Add a Database fact.
Parameters
c - context
d - fixed point context
r - relation signature for the row.
num_args - number of columns for the given row.
args - array of the row elements.
The number of arguments num_args should be equal to the number of sorts in the domain of r. Each sort in the domain should be an integral (bit-vector, Boolean or or finite domain sort).
The call has the same effect as adding a rule where r is applied to the arguments.
Referenced by fixedpoint::add_fact().
Z3_fixedpoint_add_rule()
void Z3_API Z3_fixedpoint_add_rule (Z3_context c, Z3_fixedpoint d, Z3_ast rule, Z3_symbol name)
Add a universal Horn clause as a named rule. The horn_rule should be of the form:
horn_rule ::= (forall (bound-vars) horn_rule)
           |  (=> atoms horn_rule)
           |  atom
Referenced by fixedpoint::add_rule().
Z3_fixedpoint_assert()
void Z3_API Z3_fixedpoint_assert (Z3_context c, Z3_fixedpoint d, Z3_ast axiom)
Assert a constraint to the fixedpoint context.
The constraints are used as background axioms when the fixedpoint engine uses the PDR mode. They are ignored for standard Datalog mode.
Z3_fixedpoint_dec_ref()
void Z3_API Z3_fixedpoint_dec_ref (Z3_context c, Z3_fixedpoint d)
Decrement the reference counter of the given fixedpoint context.
Referenced by fixedpoint::operator=(), and fixedpoint::~fixedpoint().
Z3_fixedpoint_from_file()
Z3_ast_vector Z3_API Z3_fixedpoint_from_file (Z3_context c, Z3_fixedpoint f, Z3_string s)
Parse an SMT-LIB2 file with fixedpoint rules. Add the rules to the current fixedpoint context. Return the set of queries in the file.
Parameters
c - context.
f - fixedpoint context.
s - path to file containing SMT2 specification.
See also
Z3_fixedpoint_from_string
Z3_fixedpoint_to_string
Referenced by fixedpoint::from_file().
Z3_fixedpoint_from_string()
Z3_ast_vector Z3_API Z3_fixedpoint_from_string (Z3_context c, Z3_fixedpoint f, Z3_string s)
Parse an SMT-LIB2 string with fixedpoint rules. Add the rules to the current fixedpoint context. Return the set of queries in the string.
Parameters
c - context.
f - fixedpoint context.
s - string containing SMT2 specification.
See also
Z3_fixedpoint_from_file
Z3_fixedpoint_to_string
Referenced by fixedpoint::from_string().
Z3_fixedpoint_get_answer()
Z3_ast Z3_API Z3_fixedpoint_get_answer (Z3_context c, Z3_fixedpoint d)
Retrieve a formula that encodes satisfying answers to the query.
When used in Datalog mode, the returned answer is a disjunction of conjuncts. Each conjunct encodes values of the bound variables of the query that are satisfied. In PDR mode, the returned answer is a single conjunction.
When used in Datalog mode the previous call to Z3_fixedpoint_query must have returned Z3_L_TRUE. When used with the PDR engine, the previous call must have been either Z3_L_TRUE or Z3_L_FALSE.
Referenced by fixedpoint::get_answer().
Z3_fixedpoint_get_assertions()
Z3_ast_vector Z3_API Z3_fixedpoint_get_assertions (Z3_context c, Z3_fixedpoint f)
Retrieve set of background assertions from fixedpoint context.
Referenced by fixedpoint::assertions().
Z3_fixedpoint_get_cover_delta()
Z3_ast Z3_API Z3_fixedpoint_get_cover_delta (Z3_context c, Z3_fixedpoint d, int level, Z3_func_decl pred)
Retrieve the current cover of pred up to level unfoldings. Return just the delta that is known at level. To obtain the full set of properties of pred one should query at level+1 , level+2 etc, and include level=-1.
Note: this functionality is PDR specific.
Referenced by fixedpoint::get_cover_delta().
Z3_fixedpoint_get_help()
Z3_string Z3_API Z3_fixedpoint_get_help (Z3_context c, Z3_fixedpoint f)
Return a string describing all fixedpoint available parameters.
See also
Z3_fixedpoint_get_param_descrs
Z3_fixedpoint_set_params
Referenced by fixedpoint::help().
Z3_fixedpoint_get_num_levels()
unsigned Z3_API Z3_fixedpoint_get_num_levels (Z3_context c, Z3_fixedpoint d, Z3_func_decl pred)
Query the PDR engine for the maximal levels properties are known about predicate.
This call retrieves the maximal number of relevant unfoldings of pred with respect to the current exploration state. Note: this functionality is PDR specific.
Referenced by fixedpoint::get_num_levels().
Z3_fixedpoint_get_param_descrs()
Z3_param_descrs Z3_API Z3_fixedpoint_get_param_descrs (Z3_context c, Z3_fixedpoint f)
Return the parameter description set for the given fixedpoint object.
See also
Z3_fixedpoint_get_help
Z3_fixedpoint_set_params
Referenced by fixedpoint::get_param_descrs().
Z3_fixedpoint_get_reason_unknown()
Z3_string Z3_API Z3_fixedpoint_get_reason_unknown (Z3_context c, Z3_fixedpoint d)
Retrieve a string that describes the last status returned by Z3_fixedpoint_query.
Use this method when Z3_fixedpoint_query returns Z3_L_UNDEF.
Referenced by fixedpoint::reason_unknown().
Z3_fixedpoint_get_rules()
Z3_ast_vector Z3_API Z3_fixedpoint_get_rules (Z3_context c, Z3_fixedpoint f)
Retrieve set of rules from fixedpoint context.
Referenced by fixedpoint::rules().
Z3_fixedpoint_get_statistics()
Z3_stats Z3_API Z3_fixedpoint_get_statistics (Z3_context c, Z3_fixedpoint d)
Retrieve statistics information from the last call to Z3_fixedpoint_query.
Referenced by fixedpoint::statistics().
Z3_fixedpoint_inc_ref()
void Z3_API Z3_fixedpoint_inc_ref (Z3_context c, Z3_fixedpoint d)
Increment the reference counter of the given fixedpoint context.
Referenced by fixedpoint::fixedpoint(), fixedpoint::fixedpoint(), and fixedpoint::operator=().
Z3_fixedpoint_init()
void Z3_API Z3_fixedpoint_init (Z3_context c, Z3_fixedpoint d, void * state)
Initialize the context with a user-defined state.
Z3_fixedpoint_query()
Z3_lbool Z3_API Z3_fixedpoint_query (Z3_context c, Z3_fixedpoint d, Z3_ast query)
Pose a query against the asserted rules.
query ::= (exists (bound-vars) query)
      |  literals
query returns
Z3_L_FALSE if the query is unsatisfiable.
Z3_L_TRUE if the query is satisfiable. Obtain the answer by calling Z3_fixedpoint_get_answer.
Z3_L_UNDEF if the query was interrupted, timed out or otherwise failed.
Referenced by fixedpoint::query().
Z3_fixedpoint_query_relations()
Z3_lbool Z3_API Z3_fixedpoint_query_relations (Z3_context c, Z3_fixedpoint d, unsigned num_relations, Z3_func_decl const relations[])
Pose multiple queries against the asserted rules.
The queries are encoded as relations (function declarations).
query returns
Z3_L_FALSE if the query is unsatisfiable.
Z3_L_TRUE if the query is satisfiable. Obtain the answer by calling Z3_fixedpoint_get_answer.
Z3_L_UNDEF if the query was interrupted, timed out or otherwise failed.
Referenced by fixedpoint::query().
Z3_fixedpoint_register_relation()
void Z3_API Z3_fixedpoint_register_relation (Z3_context c, Z3_fixedpoint d, Z3_func_decl f)
Register relation as Fixedpoint defined. Fixedpoint defined relations have least-fixedpoint semantics. For example, the relation is empty if it does not occur in a head or a fact.
Referenced by fixedpoint::register_relation().
Z3_fixedpoint_set_params()
void Z3_API Z3_fixedpoint_set_params (Z3_context c, Z3_fixedpoint f, Z3_params p)
Set parameters on fixedpoint context.
See also
Z3_fixedpoint_get_help
Z3_fixedpoint_get_param_descrs
Referenced by fixedpoint::set().
Z3_fixedpoint_set_predicate_representation()
void Z3_API Z3_fixedpoint_set_predicate_representation (Z3_context c, Z3_fixedpoint d, Z3_func_decl f, unsigned num_relations, Z3_symbol const relation_kinds[])
Configure the predicate representation.
It sets the predicate to use a set of domains given by the list of symbols. The domains given by the list of symbols must belong to a set of built-in domains.
Z3_fixedpoint_set_reduce_app_callback()
void Z3_API Z3_fixedpoint_set_reduce_app_callback (Z3_context c, Z3_fixedpoint d, Z3_fixedpoint_reduce_app_callback_fptr cb)
Register a callback for building terms based on the relational operators.
Z3_fixedpoint_set_reduce_assign_callback()
void Z3_API Z3_fixedpoint_set_reduce_assign_callback (Z3_context c, Z3_fixedpoint d, Z3_fixedpoint_reduce_assign_callback_fptr cb)
Register a callback to destructive updates.
Registers are identified with terms encoded as fresh constants,
Z3_fixedpoint_to_string()
Z3_string Z3_API Z3_fixedpoint_to_string (Z3_context c, Z3_fixedpoint f, unsigned num_queries, Z3_ast queries[])
Print the current rules and background axioms as a string.
Parameters
c - context.
f - fixedpoint context.
num_queries - number of additional queries to print.
queries - additional queries.
See also
Z3_fixedpoint_from_file
Z3_fixedpoint_from_string
Referenced by z3::operator<<(), fixedpoint::to_string(), and fixedpoint::to_string().
Z3_fixedpoint_update_rule()
void Z3_API Z3_fixedpoint_update_rule (Z3_context c, Z3_fixedpoint d, Z3_ast a, Z3_symbol name)
Update a named rule. A rule with the same name must have been previously created.
Referenced by fixedpoint::update_rule().
Z3_fpa_get_ebits()
unsigned Z3_API Z3_fpa_get_ebits (Z3_context c, Z3_sort s)
Retrieves the number of bits reserved for the exponent in a FloatingPoint sort.
Parameters
c logical context
s FloatingPoint sort
See also
Z3_fpa_get_sbits
Referenced by sort::fpa_ebits().
Z3_fpa_get_numeral_exponent_bv()
Z3_ast Z3_API Z3_fpa_get_numeral_exponent_bv (Z3_context c, Z3_ast t, bool biased)
Retrieves the exponent of a floating-point literal as a bit-vector expression.
Parameters
c logical context
t a floating-point numeral
biased flag to indicate whether the result is in biased representation
Remarks: This function extracts the exponent in t, without normalization. NaN is an invalid arguments.
Z3_fpa_get_numeral_exponent_int64()
bool Z3_API Z3_fpa_get_numeral_exponent_int64 (Z3_context c, Z3_ast t, int64_t * n, bool biased)
Return the exponent value of a floating-point numeral as a signed 64-bit integer.
Parameters
c logical context
t a floating-point numeral
n exponent
biased flag to indicate whether the result is in biased representation
Returns
true if t corresponds to a floating point numeral, otherwise invokes exception handler or returns false
Remarks: This function extracts the exponent in t, without normalization. NaN is an invalid argument.
Z3_fpa_get_numeral_exponent_string()
Z3_string Z3_API Z3_fpa_get_numeral_exponent_string (Z3_context c, Z3_ast t, bool biased)
Return the exponent value of a floating-point numeral as a string.
Parameters
c logical context
t a floating-point numeral
biased flag to indicate whether the result is in biased representation
Returns
true if t corresponds to a floating point numeral, otherwise invokes exception handler or returns false
Remarks: This function extracts the exponent in t, without normalization. NaN is an invalid argument.
Z3_fpa_get_numeral_sign()
bool Z3_API Z3_fpa_get_numeral_sign (Z3_context c, Z3_ast t, bool * sgn)
Retrieves the sign of a floating-point literal.
Parameters
c logical context
t a floating-point numeral
sgn the retrieved sign
Returns
true if t corresponds to a floating point numeral, otherwise invokes exception handler or returns false
Remarks: sets sgn to false if ‘t’ is positive and to true otherwise, except for NaN, which is an invalid argument.
Z3_fpa_get_numeral_sign_bv()
Z3_ast Z3_API Z3_fpa_get_numeral_sign_bv (Z3_context c, Z3_ast t)
Retrieves the sign of a floating-point literal as a bit-vector expression.
Parameters
c logical context
t a floating-point numeral
Remarks: NaN is an invalid argument.
Z3_fpa_get_numeral_significand_bv()
Z3_ast Z3_API Z3_fpa_get_numeral_significand_bv (Z3_context c, Z3_ast t)
Retrieves the significand of a floating-point literal as a bit-vector expression.
Parameters
c logical context
t a floating-point numeral
Remarks: NaN is an invalid argument.
Z3_fpa_get_numeral_significand_string()
Z3_string Z3_API Z3_fpa_get_numeral_significand_string (Z3_context c, Z3_ast t)
Return the significand value of a floating-point numeral as a string.
Parameters
c logical context
t a floating-point numeral
Returns
true if t corresponds to a floating point numeral, otherwise invokes exception handler or returns false
Remarks: The significand s is always 0.0 <= s < 2.0; the resulting string is long enough to represent the real significand precisely.
Z3_fpa_get_numeral_significand_uint64()
bool Z3_API Z3_fpa_get_numeral_significand_uint64 (Z3_context c, Z3_ast t, uint64_t * n)
Return the significand value of a floating-point numeral as a uint64.
Parameters
c logical context
t a floating-point numeral
n pointer to output uint64
Remarks: This function extracts the significand bits in t, without the hidden bit or normalization. Sets the Z3_INVALID_ARG error code if the significand does not fit into a uint64. NaN is an invalid argument.
Z3_fpa_get_sbits()
unsigned Z3_API Z3_fpa_get_sbits (Z3_context c, Z3_sort s)
Retrieves the number of bits reserved for the significand in a FloatingPoint sort.
Parameters
c logical context
s FloatingPoint sort
See also
Z3_fpa_get_ebits
Referenced by sort::fpa_sbits().
Z3_fpa_is_numeral()
bool Z3_API Z3_fpa_is_numeral (Z3_context c, Z3_ast t)
Checks whether a given ast is a floating-point numeral.
Parameters
c logical context
t an ast
See also
Z3_fpa_is_numeral_nan
Z3_fpa_is_numeral_inf
Z3_fpa_is_numeral_normal
Z3_fpa_is_numeral_subnormal
Z3_fpa_is_numeral_zero
Z3_fpa_is_numeral_inf()
bool Z3_API Z3_fpa_is_numeral_inf (Z3_context c, Z3_ast t)
Checks whether a given floating-point numeral is a +oo or -oo.
Parameters
c logical context
t a floating-point numeral
See also
Z3_fpa_is_numeral_nan
Z3_fpa_is_numeral_normal
Z3_fpa_is_numeral_subnormal
Z3_fpa_is_numeral_zero
Z3_fpa_is_numeral_nan()
bool Z3_API Z3_fpa_is_numeral_nan (Z3_context c, Z3_ast t)
Checks whether a given floating-point numeral is a NaN.
Parameters
c logical context
t a floating-point numeral
See also
Z3_fpa_is_numeral_inf
Z3_fpa_is_numeral_normal
Z3_fpa_is_numeral_subnormal
Z3_fpa_is_numeral_zero
Z3_fpa_is_numeral_negative()
bool Z3_API Z3_fpa_is_numeral_negative (Z3_context c, Z3_ast t)
Checks whether a given floating-point numeral is negative.
Parameters
c logical context
t a floating-point numeral
See also
Z3_fpa_is_numeral_positive
Z3_fpa_is_numeral_normal()
bool Z3_API Z3_fpa_is_numeral_normal (Z3_context c, Z3_ast t)
Checks whether a given floating-point numeral is normal.
Parameters
c logical context
t a floating-point numeral
See also
Z3_fpa_is_numeral_inf
Z3_fpa_is_numeral_nan
Z3_fpa_is_numeral_subnormal
Z3_fpa_is_numeral_zero
Z3_fpa_is_numeral_positive()
bool Z3_API Z3_fpa_is_numeral_positive (Z3_context c, Z3_ast t)
Checks whether a given floating-point numeral is positive.
Parameters
c logical context
t a floating-point numeral
See also
Z3_fpa_is_numeral_negative
Z3_fpa_is_numeral_subnormal()
bool Z3_API Z3_fpa_is_numeral_subnormal (Z3_context c, Z3_ast t)
Checks whether a given floating-point numeral is subnormal.
Parameters
c logical context
t a floating-point numeral
See also
Z3_fpa_is_numeral_inf
Z3_fpa_is_numeral_nan
Z3_fpa_is_numeral_normal
Z3_fpa_is_numeral_zero
Z3_fpa_is_numeral_zero()
bool Z3_API Z3_fpa_is_numeral_zero (Z3_context c, Z3_ast t)
Checks whether a given floating-point numeral is +zero or -zero.
Parameters
c logical context
t a floating-point numeral
See also
Z3_fpa_is_numeral_inf
Z3_fpa_is_numeral_nan
Z3_fpa_is_numeral_normal
Z3_fpa_is_numeral_subnormal
Z3_func_decl_to_ast()
Z3_ast Z3_API Z3_func_decl_to_ast (Z3_context c, Z3_func_decl f)
Convert a Z3_func_decl into Z3_ast. This is just type casting.
Z3_func_decl_to_string()
Z3_string Z3_API Z3_func_decl_to_string (Z3_context c, Z3_func_decl d)
Z3_func_entry_dec_ref()
void Z3_API Z3_func_entry_dec_ref (Z3_context c, Z3_func_entry e)
Decrement the reference counter of the given Z3_func_entry object.
Referenced by FuncEntry::__del__(), func_entry::operator=(), and func_entry::~func_entry().
Z3_func_entry_get_arg()
Z3_ast Z3_API Z3_func_entry_get_arg (Z3_context c, Z3_func_entry e, unsigned i)
Return an argument of a Z3_func_entry object.
Precondition
i < Z3_func_entry_get_num_args(c, e)
See also
Z3_func_entry_get_num_args
Z3_func_interp_get_entry
Referenced by func_entry::arg(), and FuncEntry::arg_value().
Z3_func_entry_get_num_args()
unsigned Z3_API Z3_func_entry_get_num_args (Z3_context c, Z3_func_entry e)
Return the number of arguments in a Z3_func_entry object.
See also
Z3_func_entry_get_arg
Z3_func_interp_get_entry
Referenced by func_entry::num_args(), FuncEntry::num_args(), and ModelRef::update_value().
Z3_func_entry_get_value()
Z3_ast Z3_API Z3_func_entry_get_value (Z3_context c, Z3_func_entry e)
Return the value of this point.
A Z3_func_entry object represents an element in the finite map used to encode a function interpretation.
See also
Z3_func_interp_get_entry
Referenced by ModelRef::update_value(), func_entry::value(), and FuncEntry::value().
Z3_func_entry_inc_ref()
void Z3_API Z3_func_entry_inc_ref (Z3_context c, Z3_func_entry e)
Increment the reference counter of the given Z3_func_entry object.
Referenced by func_entry::operator=().
Z3_func_interp_add_entry()
void Z3_API Z3_func_interp_add_entry (Z3_context c, Z3_func_interp fi, Z3_ast_vector args, Z3_ast value)
add a function entry to a function interpretation.
Parameters
c logical context
fi a function interpretation to be updated.
args list of arguments. They should be constant values (such as integers) and be of the same types as the domain of the function.
value value of the function when the parameters match args.
It is assumed that entries added to a function cover disjoint arguments. If an two entries are added with the same arguments, only the second insertion survives and the first inserted entry is removed.
Referenced by func_interp::add_entry(), and ModelRef::update_value().
Z3_func_interp_dec_ref()
void Z3_API Z3_func_interp_dec_ref (Z3_context c, Z3_func_interp f)
Decrement the reference counter of the given Z3_func_interp object.
Referenced by FuncInterp::__del__(), func_interp::operator=(), and func_interp::~func_interp().
Z3_func_interp_get_arity()
unsigned Z3_API Z3_func_interp_get_arity (Z3_context c, Z3_func_interp f)
Return the arity (number of arguments) of the given function interpretation.
Referenced by FuncInterp::arity().
Z3_func_interp_get_else()
Z3_ast Z3_API Z3_func_interp_get_else (Z3_context c, Z3_func_interp f)
Return the 'else' value of the given function interpretation.
A function interpretation is represented as a finite map and an 'else' value. This procedure returns the 'else' value.
Referenced by func_interp::else_value(), and FuncInterp::else_value().
Z3_func_interp_get_entry()
Z3_func_entry Z3_API Z3_func_interp_get_entry (Z3_context c, Z3_func_interp f, unsigned i)
Return a "point" of the given function interpretation. It represents the value of f in a particular point.
Precondition
i < Z3_func_interp_get_num_entries(c, f)
See also
Z3_func_interp_get_num_entries
Referenced by FuncInterp::entry(), and func_interp::entry().
Z3_func_interp_get_num_entries()
unsigned Z3_API Z3_func_interp_get_num_entries (Z3_context c, Z3_func_interp f)
Return the number of entries in the given function interpretation.
A function interpretation is represented as a finite map and an 'else' value. Each entry in the finite map represents the value of a function given a set of arguments. This procedure return the number of element in the finite map of f.
See also
Z3_func_interp_get_entry
Referenced by func_interp::num_entries(), and FuncInterp::num_entries().
Z3_func_interp_inc_ref()
void Z3_API Z3_func_interp_inc_ref (Z3_context c, Z3_func_interp f)
Increment the reference counter of the given Z3_func_interp object.
Referenced by func_interp::operator=().
Z3_func_interp_set_else()
void Z3_API Z3_func_interp_set_else (Z3_context c, Z3_func_interp f, Z3_ast else_value)
Return the 'else' value of the given function interpretation.
A function interpretation is represented as a finite map and an 'else' value. This procedure can be used to update the 'else' value.
Referenced by func_interp::set_else().
Z3_get_algebraic_number_lower()
Z3_ast Z3_API Z3_get_algebraic_number_lower (Z3_context c, Z3_ast a, unsigned precision)
Return a lower bound for the given real algebraic number. The interval isolating the number is smaller than 1/10^precision. The result is a numeral AST of sort Real.
Precondition
Z3_is_algebraic_number(c, a)
Referenced by expr::algebraic_lower().
Z3_get_algebraic_number_upper()
Z3_ast Z3_API Z3_get_algebraic_number_upper (Z3_context c, Z3_ast a, unsigned precision)
Return a upper bound for the given real algebraic number. The interval isolating the number is smaller than 1/10^precision. The result is a numeral AST of sort Real.
Precondition
Z3_is_algebraic_number(c, a)
Referenced by expr::algebraic_upper().
Z3_get_app_arg()
Z3_ast Z3_API Z3_get_app_arg (Z3_context c, Z3_app a, unsigned i)
Return the i-th argument of the given application.
Precondition
i < Z3_get_app_num_args(c, a)
See also
Z3_get_app_num_args
Referenced by ExprRef::arg(), and expr::arg().
Z3_get_app_decl()
Z3_func_decl Z3_API Z3_get_app_decl (Z3_context c, Z3_app a)
Return the declaration of a constant or function application.
Referenced by expr::decl(), and ExprRef::decl().
Z3_get_app_num_args()
unsigned Z3_API Z3_get_app_num_args (Z3_context c, Z3_app a)
Return the number of argument of an application. If t is an constant, then the number of arguments is 0.
See also
Z3_get_app_arg
Referenced by expr::num_args(), and ExprRef::num_args().
Z3_get_arity()
unsigned Z3_API Z3_get_arity (Z3_context c, Z3_func_decl d)
Alias for Z3_get_domain_size.
See also
Z3_get_domain_size
Referenced by func_decl::arity(), and FuncDeclRef::arity().
Z3_get_array_arity()
unsigned Z3_API Z3_get_array_arity (Z3_context c, Z3_sort s)
Return the arity (number of dimensions) of the given array sort.
Precondition
Z3_get_sort_kind(s) == Z3_ARRAY_SORT
See also
Z3_get_array_sort_domain_n
Z3_get_array_sort_domain()
Z3_sort Z3_API Z3_get_array_sort_domain (Z3_context c, Z3_sort t)
Return the domain of the given array sort. In the case of a multi-dimensional array, this function returns the sort of the first dimension.
Precondition
Z3_get_sort_kind(c, t) == Z3_ARRAY_SORT
See also
Z3_mk_array_sort
Z3_get_sort_kind
Z3_get_array_sort_domain_n
Referenced by sort::array_domain().
Z3_get_array_sort_domain_n()
Z3_sort Z3_API Z3_get_array_sort_domain_n (Z3_context c, Z3_sort t, unsigned idx)
Return the i'th domain sort of an n-dimensional array.
Precondition
Z3_get_sort_kind(c, t) == Z3_ARRAY_SORT
See also
Z3_mk_array_sort
Z3_get_sort_kind
Z3_get_array_sort_domain
Referenced by ArraySortRef::domain_n().
Z3_get_array_sort_range()
Z3_sort Z3_API Z3_get_array_sort_range (Z3_context c, Z3_sort t)
Return the range of the given array sort.
Precondition
Z3_get_sort_kind(c, t) == Z3_ARRAY_SORT
See also
Z3_mk_array_sort
Z3_get_sort_kind
Referenced by sort::array_range(), and ArraySortRef::range().
Z3_get_as_array_func_decl()
Z3_func_decl Z3_API Z3_get_as_array_func_decl (Z3_context c, Z3_ast a)
Return the function declaration f associated with a (_ as_array f) node.
See also
Z3_is_as_array
Referenced by z3py::get_as_array_func().
Z3_get_ast_hash()
unsigned Z3_API Z3_get_ast_hash (Z3_context c, Z3_ast a)
Return a hash code for the given AST. The hash code is structural but two different AST objects can map to the same hash. The result of Z3_get_ast_id returns an identifier that is unique over the set of live AST objects.
Referenced by ast::hash(), and AstRef::hash().
Z3_get_ast_id()
unsigned Z3_API Z3_get_ast_id (Z3_context c, Z3_ast t)
Return a unique identifier for t. The identifier is unique up to structural equality. Thus, two ast nodes created by the same context and having the same children and same function symbols have the same identifiers. Ast nodes created in the same context, but having different children or different functions have different identifiers. Variables and quantifiers are also assigned different identifiers according to their structure.
Referenced by AstRef::get_id(), SortRef::get_id(), FuncDeclRef::get_id(), ExprRef::get_id(), PatternRef::get_id(), QuantifierRef::get_id(), and expr::id().
Z3_get_ast_kind()
Z3_ast_kind Z3_API Z3_get_ast_kind (Z3_context c, Z3_ast a)
Return the kind of the given AST.
Referenced by z3py::_ast_kind(), z3py::_to_expr_ref(), ast::kind(), cast_ast< expr >::operator()(), cast_ast< sort >::operator()(), cast_ast< func_decl >::operator()(), and z3::to_expr().
Z3_get_bool_value()
Z3_lbool Z3_API Z3_get_bool_value (Z3_context c, Z3_ast a)
Return Z3_L_TRUE if a is true, Z3_L_FALSE if it is false, and Z3_L_UNDEF otherwise.
Referenced by expr::bool_value().
Z3_get_bv_sort_size()
unsigned Z3_API Z3_get_bv_sort_size (Z3_context c, Z3_sort t)
Return the size of the given bit-vector sort.
Precondition
Z3_get_sort_kind(c, t) == Z3_BV_SORT
See also
Z3_mk_bv_sort
Z3_get_sort_kind
Referenced by sort::bv_size().
Z3_get_datatype_sort_constructor()
Z3_func_decl Z3_API Z3_get_datatype_sort_constructor (Z3_context c, Z3_sort t, unsigned idx)
Return idx'th constructor.
Precondition
Z3_get_sort_kind(t) == Z3_DATATYPE_SORT
idx < Z3_get_datatype_sort_num_constructors(c, t)
See also
Z3_get_datatype_sort_num_constructors
Z3_get_datatype_sort_recognizer
Z3_get_datatype_sort_constructor_accessor
Referenced by func_decl::accessors(), and sort::constructors().
Z3_get_datatype_sort_constructor_accessor()
Z3_func_decl Z3_API Z3_get_datatype_sort_constructor_accessor (Z3_context c, Z3_sort t, unsigned idx_c, unsigned idx_a)
Return idx_a'th accessor for the idx_c'th constructor.
Precondition
Z3_get_sort_kind(t) == Z3_DATATYPE_SORT
idx_c < Z3_get_datatype_sort_num_constructors(c, t)
idx_a < Z3_get_domain_size(c, Z3_get_datatype_sort_constructor(c, idx_c))
See also
Z3_get_datatype_sort_num_constructors
Z3_get_datatype_sort_constructor
Z3_get_datatype_sort_recognizer
Referenced by DatatypeSortRef::accessor(), and func_decl::accessors().
Z3_get_datatype_sort_num_constructors()
unsigned Z3_API Z3_get_datatype_sort_num_constructors (Z3_context c, Z3_sort t)
Return number of constructors for datatype.
Precondition
Z3_get_sort_kind(t) == Z3_DATATYPE_SORT
See also
Z3_get_datatype_sort_constructor
Z3_get_datatype_sort_recognizer
Z3_get_datatype_sort_constructor_accessor
Referenced by func_decl::accessors(), sort::constructors(), and sort::recognizers().
Z3_get_datatype_sort_recognizer()
Z3_func_decl Z3_API Z3_get_datatype_sort_recognizer (Z3_context c, Z3_sort t, unsigned idx)
Return idx'th recognizer.
Precondition
Z3_get_sort_kind(t) == Z3_DATATYPE_SORT
idx < Z3_get_datatype_sort_num_constructors(c, t)
See also
Z3_get_datatype_sort_num_constructors
Z3_get_datatype_sort_constructor
Z3_get_datatype_sort_constructor_accessor
Referenced by DatatypeSortRef::recognizer(), and sort::recognizers().
Z3_get_decl_ast_parameter()
Z3_ast Z3_API Z3_get_decl_ast_parameter (Z3_context c, Z3_func_decl d, unsigned idx)
Return the expression value associated with an expression parameter.
Precondition
Z3_get_decl_parameter_kind(c, d, idx) == Z3_PARAMETER_AST
Referenced by parameter::get_expr(), z3py::get_map_func(), and FuncDeclRef::params().
Z3_get_decl_double_parameter()
double Z3_API Z3_get_decl_double_parameter (Z3_context c, Z3_func_decl d, unsigned idx)
Return the double value associated with an double parameter.
Precondition
Z3_get_decl_parameter_kind(c, d, idx) == Z3_PARAMETER_DOUBLE
Referenced by parameter::get_double(), and FuncDeclRef::params().
Z3_get_decl_func_decl_parameter()
Z3_func_decl Z3_API Z3_get_decl_func_decl_parameter (Z3_context c, Z3_func_decl d, unsigned idx)
Return the expression value associated with an expression parameter.
Precondition
Z3_get_decl_parameter_kind(c, d, idx) == Z3_PARAMETER_FUNC_DECL
Referenced by parameter::get_decl(), and FuncDeclRef::params().
Z3_get_decl_int_parameter()
int Z3_API Z3_get_decl_int_parameter (Z3_context c, Z3_func_decl d, unsigned idx)
Return the integer value associated with an integer parameter.
Precondition
Z3_get_decl_parameter_kind(c, d, idx) == Z3_PARAMETER_INT
Referenced by parameter::get_int(), expr::hi(), expr::lo(), and FuncDeclRef::params().
Z3_get_decl_kind()
Z3_decl_kind Z3_API Z3_get_decl_kind (Z3_context c, Z3_func_decl d)
Return declaration kind corresponding to declaration.
Referenced by func_decl::decl_kind(), and FuncDeclRef::kind().
Z3_get_decl_name()
Z3_symbol Z3_API Z3_get_decl_name (Z3_context c, Z3_func_decl d)
Return the constant declaration name as a symbol.
Referenced by func_decl::name().
Z3_get_decl_num_parameters()
unsigned Z3_API Z3_get_decl_num_parameters (Z3_context c, Z3_func_decl d)
Return the number of parameters associated with a declaration.
Referenced by expr::hi(), expr::lo(), func_decl::num_parameters(), and FuncDeclRef::params().
Z3_get_decl_parameter_kind()
Z3_parameter_kind Z3_API Z3_get_decl_parameter_kind (Z3_context c, Z3_func_decl d, unsigned idx)
Return the parameter type associated with a declaration.
Parameters
c the context
d the function declaration
idx is the index of the named parameter it should be between 0 and the number of parameters.
Referenced by parameter::parameter(), parameter::parameter(), and FuncDeclRef::params().
Z3_get_decl_rational_parameter()
Z3_string Z3_API Z3_get_decl_rational_parameter (Z3_context c, Z3_func_decl d, unsigned idx)
Return the rational value, as a string, associated with a rational parameter.
Precondition
Z3_get_decl_parameter_kind(c, d, idx) == Z3_PARAMETER_RATIONAL
Referenced by parameter::get_rational(), and FuncDeclRef::params().
Z3_get_decl_sort_parameter()
Z3_sort Z3_API Z3_get_decl_sort_parameter (Z3_context c, Z3_func_decl d, unsigned idx)
Return the sort value associated with a sort parameter.
Precondition
Z3_get_decl_parameter_kind(c, d, idx) == Z3_PARAMETER_SORT
Referenced by parameter::get_sort(), and FuncDeclRef::params().
Z3_get_decl_symbol_parameter()
Z3_symbol Z3_API Z3_get_decl_symbol_parameter (Z3_context c, Z3_func_decl d, unsigned idx)
Return the double value associated with an double parameter.
Precondition
Z3_get_decl_parameter_kind(c, d, idx) == Z3_PARAMETER_SYMBOL
Referenced by parameter::get_symbol(), and FuncDeclRef::params().
Z3_get_denominator()
Z3_ast Z3_API Z3_get_denominator (Z3_context c, Z3_ast a)
Return the denominator (as a numeral AST) of a numeral AST of sort Real.
Precondition
Z3_get_ast_kind(c, a) == Z3_NUMERAL_AST
Referenced by expr::denominator(), and RatNumRef::denominator().
Z3_get_depth()
unsigned Z3_API Z3_get_depth (Z3_context c, Z3_ast a)
Z3_get_domain()
Z3_sort Z3_API Z3_get_domain (Z3_context c, Z3_func_decl d, unsigned i)
Return the sort of the i-th parameter of the given function declaration.
Precondition
i < Z3_get_domain_size(d)
See also
Z3_get_domain_size
Referenced by FuncDeclRef::domain(), and func_decl::domain().
Z3_get_domain_size()
unsigned Z3_API Z3_get_domain_size (Z3_context c, Z3_func_decl d)
Return the number of parameters of the given declaration.
See also
Z3_get_arity
Z3_get_error_code()
Z3_error_code Z3_API Z3_get_error_code (Z3_context c)
Return the error code for the last API call.
A call to a Z3 function may return a non Z3_OK error code, when it is not used correctly.
See also
Z3_set_error_handler
Referenced by context::check_error().
Z3_get_error_msg()
Z3_string Z3_API Z3_get_error_msg (Z3_context c, Z3_error_code err)
Return a string describing the given error code.
Referenced by context::check_error().
Z3_get_estimated_alloc_size()
uint64_t Z3_API Z3_get_estimated_alloc_size (void)
Return the estimated allocated memory in bytes.
Z3_get_finite_domain_sort_size()
bool Z3_API Z3_get_finite_domain_sort_size (Z3_context c, Z3_sort s, uint64_t * r)
Store the size of the sort in r. Return false if the call failed. That is, Z3_get_sort_kind(s) == Z3_FINITE_DOMAIN_SORT.
Z3_get_full_version()
Z3_string Z3_API Z3_get_full_version (void)
Return a string that fully describes the version of Z3 in use.
See also
Z3_get_version
Referenced by z3py::get_full_version().
Z3_get_func_decl_id()
unsigned Z3_API Z3_get_func_decl_id (Z3_context c, Z3_func_decl f)
Return a unique identifier for f.
Referenced by func_decl::id().
Z3_get_global_param_descrs()
Z3_param_descrs Z3_API Z3_get_global_param_descrs (Z3_context c)
Retrieve description of global parameters.
Referenced by param_descrs::global_param_descrs(), and Context::param_descrs().
Z3_get_implied_equalities()
Z3_lbool Z3_API Z3_get_implied_equalities (Z3_context c, Z3_solver s, unsigned num_terms, Z3_ast const terms[], unsigned class_ids[])
Retrieve congruence class representatives for terms.
The function can be used for relying on Z3 to identify equal terms under the current set of assumptions. The array of terms and array of class identifiers should have the same length. The class identifiers are numerals that are assigned to the same value for their corresponding terms if the current context forces the terms to be equal. You cannot deduce that terms corresponding to different numerals must be all different, (especially when using non-convex theories). All implied equalities are returned by this call. This means that two terms map to the same class identifier if and only if the current context implies that they are equal.
A side-effect of the function is a satisfiability check on the assertions on the solver that is passed in. The function return Z3_L_FALSE if the current assertions are not satisfiable.
Z3_get_index_value()
unsigned Z3_API Z3_get_index_value (Z3_context c, Z3_ast a)
Return index of de-Bruijn bound variable.
Precondition
Z3_get_ast_kind(a) == Z3_VAR_AST
Referenced by z3py::get_var_index().
Z3_get_lstring()
Z3_char_ptr Z3_API Z3_get_lstring (Z3_context c, Z3_ast s, unsigned * length)
Retrieve the string constant stored in s. The string can contain escape sequences. Characters in the range 1 to 255 are literal. Characters in the range 0, and 256 above are escaped.
Precondition
Z3_is_string(c, s)
Z3_get_num_probes()
unsigned Z3_API Z3_get_num_probes (Z3_context c)
Return the number of builtin probes available in Z3.
See also
Z3_get_probe_name
Z3_get_num_simplifiers()
unsigned Z3_API Z3_get_num_simplifiers (Z3_context c)
Return the number of builtin simplifiers available in Z3.
See also
Z3_get_simplifier_name
Z3_get_num_tactics()
unsigned Z3_API Z3_get_num_tactics (Z3_context c)
Return the number of builtin tactics available in Z3.
See also
Z3_get_tactic_name
Z3_get_numeral_binary_string()
Z3_string Z3_API Z3_get_numeral_binary_string (Z3_context c, Z3_ast a)
Return numeral value, as a binary string of a numeric constant term.
Precondition
Z3_get_ast_kind(c, a) == Z3_NUMERAL_AST
a represents a non-negative integer
Referenced by expr::as_binary(), IntNumRef::as_binary_string(), and BitVecNumRef::as_binary_string().
Z3_get_numeral_decimal_string()
Z3_string Z3_API Z3_get_numeral_decimal_string (Z3_context c, Z3_ast a, unsigned precision)
Return numeral as a string in decimal notation. The result has at most precision decimal places.
Precondition
Z3_get_ast_kind(c, a) == Z3_NUMERAL_AST || Z3_is_algebraic_number(c, a)
Referenced by RatNumRef::as_decimal(), AlgebraicNumRef::as_decimal(), expr::get_decimal_string(), and expr::is_numeral().
Z3_get_numeral_double()
double Z3_API Z3_get_numeral_double (Z3_context c, Z3_ast a)
Return numeral as a double.
Precondition
Z3_get_ast_kind(c, a) == Z3_NUMERAL_AST || Z3_is_algebraic_number(c, a)
Referenced by expr::is_numeral(), and RatNumRef::py_value().
Z3_get_numeral_int()
bool Z3_API Z3_get_numeral_int (Z3_context c, Z3_ast v, int * i)
Similar to Z3_get_numeral_string, but only succeeds if the value can fit in a machine int. Return true if the call succeeded.
Precondition
Z3_get_ast_kind(c, v) == Z3_NUMERAL_AST
See also
Z3_get_numeral_string
Referenced by expr::is_numeral_i().
Z3_get_numeral_int64()
bool Z3_API Z3_get_numeral_int64 (Z3_context c, Z3_ast v, int64_t * i)
Similar to Z3_get_numeral_string, but only succeeds if the value can fit in a machine int64_t int. Return true if the call succeeded.
Precondition
Z3_get_ast_kind(c, v) == Z3_NUMERAL_AST
See also
Z3_get_numeral_string
Referenced by expr::is_numeral_i64().
Z3_get_numeral_rational_int64()
bool Z3_API Z3_get_numeral_rational_int64 (Z3_context c, Z3_ast v, int64_t * num, int64_t * den)
Similar to Z3_get_numeral_string, but only succeeds if the value can fit as a rational number as machine int64_t int. Return true if the call succeeded.
Precondition
Z3_get_ast_kind(c, v) == Z3_NUMERAL_AST
See also
Z3_get_numeral_string
Z3_get_numeral_small()
bool Z3_API Z3_get_numeral_small (Z3_context c, Z3_ast a, int64_t * num, int64_t * den)
Return numeral value, as a pair of 64 bit numbers if the representation fits.
Parameters
c logical context.
a term.
num numerator.
den denominator.
Return true if the numeral value fits in 64 bit numerals, false otherwise.
Equivalent to Z3_get_numeral_rational_int64 except that for unsupported expression arguments Z3_get_numeral_small signals an error while Z3_get_numeral_rational_int64 returns false.
Precondition
Z3_get_ast_kind(a) == Z3_NUMERAL_AST
Z3_get_numeral_string()
Z3_string Z3_API Z3_get_numeral_string (Z3_context c, Z3_ast a)
Return numeral value, as a decimal string of a numeric constant term.
Precondition
Z3_get_ast_kind(c, a) == Z3_NUMERAL_AST
Referenced by IntNumRef::as_string(), RatNumRef::as_string(), BitVecNumRef::as_string(), and expr::is_numeral().
Z3_get_numeral_uint()
bool Z3_API Z3_get_numeral_uint (Z3_context c, Z3_ast v, unsigned * u)
Similar to Z3_get_numeral_string, but only succeeds if the value can fit in a machine unsigned int. Return true if the call succeeded.
Precondition
Z3_get_ast_kind(c, v) == Z3_NUMERAL_AST
See also
Z3_get_numeral_string
Referenced by expr::is_numeral_u().
Z3_get_numeral_uint64()
bool Z3_API Z3_get_numeral_uint64 (Z3_context c, Z3_ast v, uint64_t * u)
Similar to Z3_get_numeral_string, but only succeeds if the value can fit in a machine uint64_t int. Return true if the call succeeded.
Precondition
Z3_get_ast_kind(c, v) == Z3_NUMERAL_AST
See also
Z3_get_numeral_string
Referenced by expr::is_numeral_u64().
Z3_get_numerator()
Z3_ast Z3_API Z3_get_numerator (Z3_context c, Z3_ast a)
Return the numerator (as a numeral AST) of a numeral AST of sort Real.
Precondition
Z3_get_ast_kind(c, a) == Z3_NUMERAL_AST
Referenced by expr::numerator().
Z3_get_pattern()
Z3_ast Z3_API Z3_get_pattern (Z3_context c, Z3_pattern p, unsigned idx)
Return i'th ast in pattern.
Z3_get_pattern_num_terms()
unsigned Z3_API Z3_get_pattern_num_terms (Z3_context c, Z3_pattern p)
Return number of terms in pattern.
Z3_get_probe_name()
Z3_string Z3_API Z3_get_probe_name (Z3_context c, unsigned i)
Return the name of the i probe.
Precondition
i < Z3_get_num_probes(c)
See also
Z3_get_num_probes
Z3_get_quantifier_body()
Z3_ast Z3_API Z3_get_quantifier_body (Z3_context c, Z3_ast a)
Return body of quantifier.
Precondition
Z3_get_ast_kind(a) == Z3_QUANTIFIER_AST
Referenced by expr::body(), and QuantifierRef::body().
Z3_get_quantifier_bound_name()
Z3_symbol Z3_API Z3_get_quantifier_bound_name (Z3_context c, Z3_ast a, unsigned i)
Return symbol of the i'th bound variable.
Precondition
Z3_get_ast_kind(a) == Z3_QUANTIFIER_AST
Referenced by QuantifierRef::var_name().
Z3_get_quantifier_bound_sort()
Z3_sort Z3_API Z3_get_quantifier_bound_sort (Z3_context c, Z3_ast a, unsigned i)
Return sort of the i'th bound variable.
Precondition
Z3_get_ast_kind(a) == Z3_QUANTIFIER_AST
Referenced by QuantifierRef::var_sort().
Z3_get_quantifier_id()
Z3_symbol Z3_API Z3_get_quantifier_id (Z3_context c, Z3_ast a)
Obtain id of quantifier.
Precondition
Z3_get_ast_kind(a) == Z3_QUANTIFIER_AST
Referenced by QuantifierRef::qid().
Z3_get_quantifier_no_pattern_ast()
Z3_ast Z3_API Z3_get_quantifier_no_pattern_ast (Z3_context c, Z3_ast a, unsigned i)
Return i'th no_pattern.
Precondition
Z3_get_ast_kind(a) == Z3_QUANTIFIER_AST
Referenced by QuantifierRef::no_pattern().
Z3_get_quantifier_num_bound()
unsigned Z3_API Z3_get_quantifier_num_bound (Z3_context c, Z3_ast a)
Return number of bound variables of quantifier.
Precondition
Z3_get_ast_kind(a) == Z3_QUANTIFIER_AST
Referenced by QuantifierRef::num_vars().
Z3_get_quantifier_num_no_patterns()
unsigned Z3_API Z3_get_quantifier_num_no_patterns (Z3_context c, Z3_ast a)
Return number of no_patterns used in quantifier.
Precondition
Z3_get_ast_kind(a) == Z3_QUANTIFIER_AST
Referenced by QuantifierRef::num_no_patterns().
Z3_get_quantifier_num_patterns()
unsigned Z3_API Z3_get_quantifier_num_patterns (Z3_context c, Z3_ast a)
Return number of patterns used in quantifier.
Precondition
Z3_get_ast_kind(a) == Z3_QUANTIFIER_AST
Referenced by QuantifierRef::num_patterns().
Z3_get_quantifier_pattern_ast()
Z3_pattern Z3_API Z3_get_quantifier_pattern_ast (Z3_context c, Z3_ast a, unsigned i)
Return i'th pattern.
Precondition
Z3_get_ast_kind(a) == Z3_QUANTIFIER_AST
Referenced by QuantifierRef::pattern().
Z3_get_quantifier_skolem_id()
Z3_symbol Z3_API Z3_get_quantifier_skolem_id (Z3_context c, Z3_ast a)
Obtain skolem id of quantifier.
Precondition
Z3_get_ast_kind(a) == Z3_QUANTIFIER_AST
Referenced by QuantifierRef::skolem_id().
Z3_get_quantifier_weight()
unsigned Z3_API Z3_get_quantifier_weight (Z3_context c, Z3_ast a)
Obtain weight of quantifier.
Precondition
Z3_get_ast_kind(a) == Z3_QUANTIFIER_AST
Referenced by QuantifierRef::weight().
Z3_get_range()
Z3_sort Z3_API Z3_get_range (Z3_context c, Z3_func_decl d)
Return the range of the given declaration.
If d is a constant (i.e., has zero arguments), then this function returns the sort of the constant.
Referenced by func_decl::range(), and FuncDeclRef::range().
Z3_get_re_sort_basis()
Z3_sort Z3_API Z3_get_re_sort_basis (Z3_context c, Z3_sort s)
Retrieve basis sort for regex sort.
Z3_get_relation_arity()
unsigned Z3_API Z3_get_relation_arity (Z3_context c, Z3_sort s)
Return arity of relation.
Precondition
Z3_get_sort_kind(s) == Z3_RELATION_SORT
See also
Z3_get_relation_column
Z3_get_relation_column()
Z3_sort Z3_API Z3_get_relation_column (Z3_context c, Z3_sort s, unsigned col)
Return sort at i'th column of relation sort.
Precondition
Z3_get_sort_kind(c, s) == Z3_RELATION_SORT
col < Z3_get_relation_arity(c, s)
See also
Z3_get_relation_arity
Z3_get_seq_sort_basis()
Z3_sort Z3_API Z3_get_seq_sort_basis (Z3_context c, Z3_sort s)
Retrieve basis sort for sequence sort.
Z3_get_simplifier_name()
Z3_string Z3_API Z3_get_simplifier_name (Z3_context c, unsigned i)
Return the name of the idx simplifier.
Precondition
i < Z3_get_num_simplifiers(c)
See also
Z3_get_num_simplifiers
Z3_get_sort()
Z3_sort Z3_API Z3_get_sort (Z3_context c, Z3_ast a)
Return the sort of an AST node.
The AST node must be a constant, application, numeral, bound variable, or quantifier.
Referenced by z3py::_check_same_sort(), z3py::_sort(), z3py::_to_expr_ref(), expr::get_sort(), and z3py::is_array_sort().
Z3_get_sort_id()
unsigned Z3_API Z3_get_sort_id (Z3_context c, Z3_sort s)
Return a unique identifier for s.
Referenced by sort::id().
Z3_get_sort_kind()
Z3_sort_kind Z3_API Z3_get_sort_kind (Z3_context c, Z3_sort t)
Return the sort kind (e.g., array, tuple, int, bool, etc).
See also
Z3_sort_kind
Referenced by z3py::_sort_kind(), z3py::_to_expr_ref(), z3py::is_array_sort(), and sort::sort_kind().
Z3_get_sort_name()
Z3_symbol Z3_API Z3_get_sort_name (Z3_context c, Z3_sort d)
Return the sort name as a symbol.
Referenced by sort::name(), and SortRef::name().
Z3_get_string()
Z3_string Z3_API Z3_get_string (Z3_context c, Z3_ast s)
Retrieve the string constant stored in s. Characters outside the basic printable ASCII range are escaped.
Precondition
Z3_is_string(c, s)
Referenced by expr::get_string().
Z3_get_string_contents()
void Z3_API Z3_get_string_contents (Z3_context c, Z3_ast s, unsigned length, unsigned contents[])
Retrieve the unescaped string constant stored in s.
Precondition
Z3_is_string(c, s)
length contains the number of characters in s
Referenced by expr::get_u32string().
Z3_get_string_length()
unsigned Z3_API Z3_get_string_length (Z3_context c, Z3_ast s)
Retrieve the length of the unescaped string constant stored in s.
Precondition
Z3_is_string(c, s)
Referenced by expr::get_u32string().
Z3_get_symbol_int()
int Z3_API Z3_get_symbol_int (Z3_context c, Z3_symbol s)
Return the symbol int value.
Precondition
Z3_get_symbol_kind(s) == Z3_INT_SYMBOL
See also
Z3_mk_int_symbol
Referenced by z3py::_symbol2py(), and symbol::to_int().
Z3_get_symbol_kind()
Z3_symbol_kind Z3_API Z3_get_symbol_kind (Z3_context c, Z3_symbol s)
Return Z3_INT_SYMBOL if the symbol was constructed using Z3_mk_int_symbol, and Z3_STRING_SYMBOL if the symbol was constructed using Z3_mk_string_symbol.
Referenced by z3py::_symbol2py(), and symbol::kind().
Z3_get_symbol_string()
Z3_string Z3_API Z3_get_symbol_string (Z3_context c, Z3_symbol s)
Return the symbol name.
Precondition
Z3_get_symbol_kind(s) == Z3_STRING_SYMBOL
Warning
The returned buffer is statically allocated by Z3. It will be automatically deallocated when Z3_del_context is invoked. So, the buffer is invalidated in the next call to Z3_get_symbol_string.
See also
Z3_mk_string_symbol
Referenced by z3py::_symbol2py(), and symbol::str().
Z3_get_tactic_name()
Z3_string Z3_API Z3_get_tactic_name (Z3_context c, unsigned i)
Return the name of the idx tactic.
Precondition
i < Z3_get_num_tactics(c)
See also
Z3_get_num_tactics
Z3_get_tuple_sort_field_decl()
Z3_func_decl Z3_API Z3_get_tuple_sort_field_decl (Z3_context c, Z3_sort t, unsigned i)
Return the i-th field declaration (i.e., projection function declaration) of the given tuple sort.
Precondition
Z3_get_sort_kind(t) == Z3_DATATYPE_SORT
i < Z3_get_tuple_sort_num_fields(c, t)
See also
Z3_mk_tuple_sort
Z3_get_sort_kind
Z3_get_tuple_sort_mk_decl()
Z3_func_decl Z3_API Z3_get_tuple_sort_mk_decl (Z3_context c, Z3_sort t)
Return the constructor declaration of the given tuple sort.
Precondition
Z3_get_sort_kind(c, t) == Z3_DATATYPE_SORT
See also
Z3_mk_tuple_sort
Z3_get_sort_kind
Z3_get_tuple_sort_num_fields()
unsigned Z3_API Z3_get_tuple_sort_num_fields (Z3_context c, Z3_sort t)
Return the number of fields of the given tuple sort.
Precondition
Z3_get_sort_kind(c, t) == Z3_DATATYPE_SORT
See also
Z3_mk_tuple_sort
Z3_get_sort_kind
Z3_get_version()
void Z3_API Z3_get_version (unsigned * major, unsigned * minor, unsigned * build_number, unsigned * revision_number)
Return Z3 version number information.
See also
Z3_get_full_version
Referenced by z3py::get_version(), and z3py::get_version_string().
Z3_global_param_get()
bool Z3_API Z3_global_param_get (Z3_string param_id, Z3_string_ptr param_value)
Get a global (or module) parameter.
Returns false if the parameter value does not exist.
See also
Z3_global_param_reset_all
Z3_global_param_set
Remarks
This function cannot be invoked simultaneously from different threads without synchronization. The result string stored in param_value is stored in shared location.
Referenced by z3py::get_param().
Z3_global_param_reset_all()
void Z3_API Z3_global_param_reset_all (void)
Restore the value of all global (and module) parameters. This command will not affect already created objects (such as tactics and solvers).
See also
Z3_global_param_get
Z3_global_param_set
Referenced by z3py::reset_params(), and z3::reset_params().
Z3_global_param_set()
void Z3_API Z3_global_param_set (Z3_string param_id, Z3_string param_value)
Set a global (or module) parameter. This setting is shared by all Z3 contexts.
When a Z3 module is initialized it will use the value of these parameters when Z3_params objects are not provided.
The name of parameter can be composed of characters [a-z][A-Z], digits [0-9], '-' and '_'. The character '.' is a delimiter (more later).
The parameter names are case-insensitive. The character '-' should be viewed as an "alias" for '_'. Thus, the following parameter names are considered equivalent: "pp.decimal-precision" and "PP.DECIMAL_PRECISION".
This function can be used to set parameters for a specific Z3 module. This can be done by using <module-name>.<parameter-name>. For example: Z3_global_param_set('pp.decimal', 'true') will set the parameter "decimal" in the module "pp" to true.
See also
Z3_global_param_get
Z3_global_param_reset_all
Referenced by z3py::set_param(), z3::set_param(), z3::set_param(), and z3::set_param().
Z3_goal_assert()
void Z3_API Z3_goal_assert (Z3_context c, Z3_goal g, Z3_ast a)
Add a new formula a to the given goal. The formula is split according to the following procedure that is applied until a fixed-point: Conjunctions are split into separate formulas. Negations are distributed over disjunctions, resulting in separate formulas. If the goal is false, adding new formulas is a no-op. If the formula a is true, then nothing is added. If the formula a is false, then the entire goal is replaced by the formula false.
Referenced by goal::add(), and Goal::assert_exprs().
Z3_goal_convert_model()
Z3_model Z3_API Z3_goal_convert_model (Z3_context c, Z3_goal g, Z3_model m)
Convert a model of the formulas of a goal to a model of an original goal. The model may be null, in which case the returned model is valid if the goal was established satisfiable.
When using this feature it is advisable to set the parameter model.compact to false. It is by default true, which erases variables created by the solver from models. Without access to model values for intermediary variables, values of other variables may end up having the wrong values.
Referenced by goal::convert_model(), Goal::convert_model(), and goal::get_model().
Z3_goal_dec_ref()
void Z3_API Z3_goal_dec_ref (Z3_context c, Z3_goal g)
Decrement the reference counter of the given goal.
Referenced by Goal::__del__(), goal::operator=(), and goal::~goal().
Z3_goal_depth()
unsigned Z3_API Z3_goal_depth (Z3_context c, Z3_goal g)
Return the depth of the given goal. It tracks how many transformations were applied to it.
Referenced by goal::depth(), and Goal::depth().
Z3_goal_formula()
Z3_ast Z3_API Z3_goal_formula (Z3_context c, Z3_goal g, unsigned idx)
Return a formula from the given goal.
Precondition
idx < Z3_goal_size(c, g)
Referenced by Goal::get(), and goal::operator[]().
Z3_goal_inc_ref()
void Z3_API Z3_goal_inc_ref (Z3_context c, Z3_goal g)
Increment the reference counter of the given goal.
Referenced by goal::operator=().
Z3_goal_inconsistent()
bool Z3_API Z3_goal_inconsistent (Z3_context c, Z3_goal g)
Return true if the given goal contains the formula false.
Referenced by goal::inconsistent(), and Goal::inconsistent().
Z3_goal_is_decided_sat()
bool Z3_API Z3_goal_is_decided_sat (Z3_context c, Z3_goal g)
Return true if the goal is empty, and it is precise or the product of a under approximation.
Referenced by goal::is_decided_sat().
Z3_goal_is_decided_unsat()
bool Z3_API Z3_goal_is_decided_unsat (Z3_context c, Z3_goal g)
Return true if the goal contains false, and it is precise or the product of an over approximation.
Referenced by goal::is_decided_unsat().
Z3_goal_num_exprs()
unsigned Z3_API Z3_goal_num_exprs (Z3_context c, Z3_goal g)
Return the number of formulas, subformulas and terms in the given goal.
Referenced by goal::num_exprs().
Z3_goal_precision()
Z3_goal_prec Z3_API Z3_goal_precision (Z3_context c, Z3_goal g)
Return the "precision" of the given goal. Goals can be transformed using over and under approximations. A under approximation is applied when the objective is to find a model for a given goal. An over approximation is applied when the objective is to find a proof for a given goal.
Referenced by Goal::prec(), and goal::precision().
Z3_goal_reset()
void Z3_API Z3_goal_reset (Z3_context c, Z3_goal g)
Erase all formulas from the given goal.
Referenced by goal::reset().
Z3_goal_size()
unsigned Z3_API Z3_goal_size (Z3_context c, Z3_goal g)
Return the number of formulas in the given goal.
Referenced by goal::size(), and Goal::size().
Z3_goal_to_dimacs_string()
Z3_string Z3_API Z3_goal_to_dimacs_string (Z3_context c, Z3_goal g, bool include_names)
Convert a goal into a DIMACS formatted string. The goal must be in CNF. You can convert a goal to CNF by applying the tseitin-cnf tactic. Bit-vectors are not automatically converted to Booleans either, so if the caller intends to preserve satisfiability, it should apply bit-blasting tactics. Quantifiers and theory atoms will not be encoded.
Referenced by goal::dimacs(), and Goal::dimacs().
Z3_goal_to_string()
Z3_string Z3_API Z3_goal_to_string (Z3_context c, Z3_goal g)
Convert a goal into a string.
Referenced by Goal::sexpr().
Z3_goal_translate()
Z3_goal Z3_API Z3_goal_translate (Z3_context source, Z3_goal g, Z3_context target)
Copy a goal g from the context source to the context target.
Referenced by Goal::translate().
Z3_inc_ref()
void Z3_API Z3_inc_ref (Z3_context c, Z3_ast a)
Increment the reference counter of the given AST. The context c should have been created using Z3_mk_context_rc. This function is a NOOP if c was created using Z3_mk_context.
Referenced by ast::ast(), ast::ast(), and ast::operator=().
Z3_interrupt()
void Z3_API Z3_interrupt (Z3_context c)
Interrupt the execution of a Z3 procedure. This procedure can be used to interrupt: solvers, simplifiers and tactics.
Referenced by context::interrupt(), and Context::interrupt().
Z3_is_algebraic_number()
bool Z3_API Z3_is_algebraic_number (Z3_context c, Z3_ast a)
Return true if the given AST is a real algebraic number.
Referenced by z3py::_is_algebraic(), and expr::is_algebraic().
Z3_is_app()
bool Z3_API Z3_is_app (Z3_context c, Z3_ast a)
Z3_is_as_array()
bool Z3_API Z3_is_as_array (Z3_context c, Z3_ast a)
The (_ as-array f) AST node is a construct for assigning interpretations for arrays in Z3. It is the array such that forall indices i we have that (select (_ as-array f) i) is equal to (f i). This procedure returns true if the a is an as-array AST node.
Z3 current solvers have minimal support for as_array nodes.
See also
Z3_get_as_array_func_decl
Referenced by z3py::is_as_array().
Z3_is_char_sort()
bool Z3_API Z3_is_char_sort (Z3_context c, Z3_sort s)
Check if s is a character sort.
Z3_is_eq_ast()
bool Z3_API Z3_is_eq_ast (Z3_context c, Z3_ast t1, Z3_ast t2)
Compare terms.
Referenced by AstRef::eq().
Z3_is_eq_func_decl()
bool Z3_API Z3_is_eq_func_decl (Z3_context c, Z3_func_decl f1, Z3_func_decl f2)
Compare terms.
Z3_is_eq_sort()
bool Z3_API Z3_is_eq_sort (Z3_context c, Z3_sort s1, Z3_sort s2)
compare sorts.
Referenced by SortRef::__eq__(), SortRef::__ne__(), and z3py::_check_same_sort().
Z3_is_ground()
bool Z3_API Z3_is_ground (Z3_context c, Z3_ast a)
Z3_is_lambda()
bool Z3_API Z3_is_lambda (Z3_context c, Z3_ast a)
Determine if ast is a lambda expression.
Precondition
Z3_get_ast_kind(a) == Z3_QUANTIFIER_AST
Referenced by expr::is_lambda(), and QuantifierRef::is_lambda().
Z3_is_numeral_ast()
bool Z3_API Z3_is_numeral_ast (Z3_context c, Z3_ast a)
Referenced by z3py::_is_numeral().
Z3_is_quantifier_exists()
bool Z3_API Z3_is_quantifier_exists (Z3_context c, Z3_ast a)
Determine if ast is an existential quantifier.
Referenced by expr::is_exists(), and QuantifierRef::is_exists().
Z3_is_quantifier_forall()
bool Z3_API Z3_is_quantifier_forall (Z3_context c, Z3_ast a)
Determine if an ast is a universal quantifier.
Referenced by expr::is_forall().
Z3_is_re_sort()
bool Z3_API Z3_is_re_sort (Z3_context c, Z3_sort s)
Check if s is a regular expression sort.
Z3_is_recursive_datatype_sort()
bool Z3_API Z3_is_recursive_datatype_sort (Z3_context c, Z3_sort s)
Check if s is a recursive datatype sort.
Z3_is_seq_sort()
bool Z3_API Z3_is_seq_sort (Z3_context c, Z3_sort s)
Check if s is a sequence sort.
Z3_is_string()
bool Z3_API Z3_is_string (Z3_context c, Z3_ast s)
Determine if s is a string constant.
Referenced by expr::is_string_value().
Z3_is_string_sort()
bool Z3_API Z3_is_string_sort (Z3_context c, Z3_sort s)
Check if s is a string sort.
Z3_is_well_sorted()
bool Z3_API Z3_is_well_sorted (Z3_context c, Z3_ast t)
Return true if the given expression t is well sorted.
Referenced by expr::is_well_sorted().
Z3_mk_abs()
Z3_ast Z3_API Z3_mk_abs (Z3_context c, Z3_ast arg)
Take the absolute value of an integer.
Z3_mk_add()
Z3_ast Z3_API Z3_mk_add (Z3_context c, unsigned num_args, Z3_ast const args[])
Create an AST node representing args[0] + ... + args[num_args-1].
The array args must have num_args elements. All arguments must have int or real sort.
Remarks
The number of arguments must be greater than zero.
Z3_mk_and()
Z3_ast Z3_API Z3_mk_and (Z3_context c, unsigned num_args, Z3_ast const args[])
Create an AST node representing args[0] and ... and args[num_args-1].
The array args must have num_args elements. All arguments must have Boolean sort.
Remarks
The number of arguments must be greater than zero.
Referenced by z3py::And(), and goal::as_expr().
Z3_mk_app()
Z3_ast Z3_API Z3_mk_app (Z3_context c, Z3_func_decl d, unsigned num_args, Z3_ast const args[])
Create a constant or function application.
See also
Z3_mk_fresh_func_decl
Z3_mk_func_decl
Z3_mk_rec_func_decl
Referenced by FuncDeclRef::__call__(), func_decl::operator()(), func_decl::operator()(), func_decl::operator()(), func_decl::operator()(), func_decl::operator()(), func_decl::operator()(), func_decl::operator()(), func_decl::operator()(), func_decl::operator()(), func_decl::operator()(), and func_decl::operator()().
Z3_mk_array_default()
Z3_ast Z3_API Z3_mk_array_default (Z3_context c, Z3_ast array)
Access the array default value. Produces the default range value, for arrays that can be represented as finite maps with a default range value.
Parameters
c logical context.
array array value whose default range value is accessed.
Referenced by ArrayRef::default().
Z3_mk_array_ext()
Z3_ast Z3_API Z3_mk_array_ext (Z3_context c, Z3_ast arg1, Z3_ast arg2)
Create array extensionality index given two arrays with the same sort. The meaning is given by the axiom: (=> (= (select A (array-ext A B)) (select B (array-ext A B))) (= A B))
Referenced by z3py::Ext().
Z3_mk_array_sort()
Z3_sort Z3_API Z3_mk_array_sort (Z3_context c, Z3_sort domain, Z3_sort range)
Create an array type.
We usually represent the array type as: [domain -> range]. Arrays are usually used to model the heap/memory in software verification.
See also
Z3_mk_select
Z3_mk_store
Referenced by context::array_sort(), and z3py::ArraySort().
Z3_mk_array_sort_n()
Z3_sort Z3_API Z3_mk_array_sort_n (Z3_context c, unsigned n, Z3_sort const * domain, Z3_sort range)
Create an array type with N arguments.
See also
Z3_mk_select_n
Z3_mk_store_n
Referenced by context::array_sort(), and z3py::ArraySort().
Z3_mk_as_array()
Z3_ast Z3_API Z3_mk_as_array (Z3_context c, Z3_func_decl f)
Create array with the same interpretation as a function. The array satisfies the property (f x) = (select (_ as-array f) x) for every argument x.
Referenced by z3::as_array().
Z3_mk_ast_map()
Z3_ast_map Z3_API Z3_mk_ast_map (Z3_context c)
Return an empty mapping from AST to AST.
Remarks
Reference counting must be used to manage AST maps, even when the Z3_context was created using Z3_mk_context instead of Z3_mk_context_rc.
Z3_mk_ast_vector()
Z3_ast_vector Z3_API Z3_mk_ast_vector (Z3_context c)
Return an empty AST vector.
Remarks
Reference counting must be used to manage AST vectors, even when the Z3_context was created using Z3_mk_context instead of Z3_mk_context_rc.
Referenced by ast_vector_tpl< T >::ast_vector_tpl().
Z3_mk_atleast()
Z3_ast Z3_API Z3_mk_atleast (Z3_context c, unsigned num_args, Z3_ast const args[], unsigned k)
Pseudo-Boolean relations.
Encode p1 + p2 + ... + pn >= k
Z3_mk_atmost()
Z3_ast Z3_API Z3_mk_atmost (Z3_context c, unsigned num_args, Z3_ast const args[], unsigned k)
Pseudo-Boolean relations.
Encode p1 + p2 + ... + pn <= k
Z3_mk_bit2bool()
Z3_ast Z3_API Z3_mk_bit2bool (Z3_context c, unsigned i, Z3_ast t1)
Extracts the bit at position i of a bit-vector and yields a boolean.
The node t1 must have a bit-vector sort.
Referenced by expr::bit2bool().
Z3_mk_bool_sort()
Z3_sort Z3_API Z3_mk_bool_sort (Z3_context c)
Create the Boolean type.
This type is used to create propositional variables and predicates.
Referenced by context::bool_sort(), and z3py::BoolSort().
Z3_mk_bound()
Z3_ast Z3_API Z3_mk_bound (Z3_context c, unsigned index, Z3_sort ty)
Create a variable.
Variables are intended to be bound by a scope created by a quantifier. So we call them bound variables even if they appear as free variables in the expression produced by Z3_mk_bound.
Bound variables are indexed by de-Bruijn indices. It is perhaps easiest to explain the meaning of de-Bruijn indices by indicating the compilation process from non-de-Bruijn formulas to de-Bruijn format.
abs(forall (x1) phi) = forall (x1) abs1(phi, x1, 0)
abs(forall (x1, x2) phi) = abs(forall (x1) abs(forall (x2) phi))
abs1(x, x, n) = b_n
abs1(y, x, n) = y
abs1(f(t1,...,tn), x, n) = f(abs1(t1,x,n), ..., abs1(tn,x,n))
abs1(forall (x1) phi, x, n) = forall (x1) (abs1(phi, x, n+1))
The last line is significant: the index of a bound variable is different depending on the scope in which it appears. The deeper x appears, the higher is its index.
Parameters
c logical context
index de-Bruijn index
ty sort of the bound variable
See also
Z3_mk_forall
Z3_mk_exists
Referenced by z3py::Var(), and context::variable().
Z3_mk_bv2int()
Z3_ast Z3_API Z3_mk_bv2int (Z3_context c, Z3_ast t1, bool is_signed)
Create an integer from the bit-vector argument t1. If is_signed is false, then the bit-vector t1 is treated as unsigned. So the result is non-negative and in the range [0..2^N-1], where N are the number of bits in t1. If is_signed is true, t1 is treated as a signed bit-vector.
The node t1 must have a bit-vector sort.
Referenced by z3py::BV2Int().
Z3_mk_bv_numeral()
Z3_ast Z3_API Z3_mk_bv_numeral (Z3_context c, unsigned sz, bool const * bits)
create a bit-vector numeral from a vector of Booleans.
See also
Z3_mk_numeral
Referenced by context::bv_val().
Z3_mk_bv_sort()
Z3_sort Z3_API Z3_mk_bv_sort (Z3_context c, unsigned sz)
Create a bit-vector type of the given size.
This type can also be seen as a machine integer.
Remarks
The size of the bit-vector type must be greater than zero.
Referenced by z3py::BitVecSort(), and context::bv_sort().
Z3_mk_bvadd()
Z3_ast Z3_API Z3_mk_bvadd (Z3_context c, Z3_ast t1, Z3_ast t2)
Standard two's complement addition.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by BitVecRef::__add__(), and BitVecRef::__radd__().
Z3_mk_bvadd_no_overflow()
Z3_ast Z3_API Z3_mk_bvadd_no_overflow (Z3_context c, Z3_ast t1, Z3_ast t2, bool is_signed)
Create a predicate that checks that the bit-wise addition of t1 and t2 does not overflow.
The nodes t1 and t2 must have the same bit-vector sort. The returned node is of sort Bool.
Referenced by z3py::BVAddNoOverflow().
Z3_mk_bvadd_no_underflow()
Z3_ast Z3_API Z3_mk_bvadd_no_underflow (Z3_context c, Z3_ast t1, Z3_ast t2)
Create a predicate that checks that the bit-wise signed addition of t1 and t2 does not underflow.
The nodes t1 and t2 must have the same bit-vector sort. The returned node is of sort Bool.
Referenced by z3py::BVAddNoUnderflow().
Z3_mk_bvand()
Z3_ast Z3_API Z3_mk_bvand (Z3_context c, Z3_ast t1, Z3_ast t2)
Bitwise and.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by BitVecRef::__and__(), and BitVecRef::__rand__().
Z3_mk_bvashr()
Z3_ast Z3_API Z3_mk_bvashr (Z3_context c, Z3_ast t1, Z3_ast t2)
Arithmetic shift right.
It is like logical shift right except that the most significant bits of the result always copy the most significant bit of the second argument.
The semantics of shift operations varies between environments. This definition does not necessarily capture directly the semantics of the programming language or assembly architecture you are modeling.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by BitVecRef::__rrshift__(), BitVecRef::__rshift__(), and z3::ashr().
Z3_mk_bvlshr()
Z3_ast Z3_API Z3_mk_bvlshr (Z3_context c, Z3_ast t1, Z3_ast t2)
Logical shift right.
It is equivalent to unsigned division by 2^x where x is the value of the third argument.
NB. The semantics of shift operations varies between environments. This definition does not necessarily capture directly the semantics of the programming language or assembly architecture you are modeling.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by z3py::LShR(), and z3::lshr().
Z3_mk_bvmul()
Z3_ast Z3_API Z3_mk_bvmul (Z3_context c, Z3_ast t1, Z3_ast t2)
Standard two's complement multiplication.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by BitVecRef::__mul__(), and BitVecRef::__rmul__().
Z3_mk_bvmul_no_overflow()
Z3_ast Z3_API Z3_mk_bvmul_no_overflow (Z3_context c, Z3_ast t1, Z3_ast t2, bool is_signed)
Create a predicate that checks that the bit-wise multiplication of t1 and t2 does not overflow.
The nodes t1 and t2 must have the same bit-vector sort. The returned node is of sort Bool.
Referenced by z3py::BVMulNoOverflow().
Z3_mk_bvmul_no_underflow()
Z3_ast Z3_API Z3_mk_bvmul_no_underflow (Z3_context c, Z3_ast t1, Z3_ast t2)
Create a predicate that checks that the bit-wise signed multiplication of t1 and t2 does not underflow.
The nodes t1 and t2 must have the same bit-vector sort. The returned node is of sort Bool.
Referenced by z3py::BVMulNoUnderflow().
Z3_mk_bvnand()
Z3_ast Z3_API Z3_mk_bvnand (Z3_context c, Z3_ast t1, Z3_ast t2)
Bitwise nand.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_mk_bvneg()
Z3_ast Z3_API Z3_mk_bvneg (Z3_context c, Z3_ast t1)
Standard two's complement unary minus.
The node t1 must have bit-vector sort.
Referenced by BitVecRef::__neg__().
Z3_mk_bvneg_no_overflow()
Z3_ast Z3_API Z3_mk_bvneg_no_overflow (Z3_context c, Z3_ast t1)
Check that bit-wise negation does not overflow when t1 is interpreted as a signed bit-vector.
The node t1 must have bit-vector sort. The returned node is of sort Bool.
Referenced by z3py::BVSNegNoOverflow().
Z3_mk_bvnor()
Z3_ast Z3_API Z3_mk_bvnor (Z3_context c, Z3_ast t1, Z3_ast t2)
Bitwise nor.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_mk_bvnot()
Z3_ast Z3_API Z3_mk_bvnot (Z3_context c, Z3_ast t1)
Bitwise negation.
The node t1 must have a bit-vector sort.
Referenced by BitVecRef::__invert__().
Z3_mk_bvor()
Z3_ast Z3_API Z3_mk_bvor (Z3_context c, Z3_ast t1, Z3_ast t2)
Bitwise or.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by BitVecRef::__or__(), and BitVecRef::__ror__().
Z3_mk_bvredand()
Z3_ast Z3_API Z3_mk_bvredand (Z3_context c, Z3_ast t1)
Take conjunction of bits in vector, return vector of length 1.
The node t1 must have a bit-vector sort.
Referenced by z3py::BVRedAnd().
Z3_mk_bvredor()
Z3_ast Z3_API Z3_mk_bvredor (Z3_context c, Z3_ast t1)
Take disjunction of bits in vector, return vector of length 1.
The node t1 must have a bit-vector sort.
Referenced by z3py::BVRedOr().
Z3_mk_bvsdiv()
Z3_ast Z3_API Z3_mk_bvsdiv (Z3_context c, Z3_ast t1, Z3_ast t2)
Two's complement signed division.
It is defined in the following way:
The floor of t1/t2 if t2 is different from zero, and t1*t2 >= 0.
The ceiling of t1/t2 if t2 is different from zero, and t1*t2 < 0.
If t2 is zero, then the result is undefined.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by BitVecRef::__div__(), BitVecRef::__rdiv__(), and z3::sdiv().
Z3_mk_bvsdiv_no_overflow()
Z3_ast Z3_API Z3_mk_bvsdiv_no_overflow (Z3_context c, Z3_ast t1, Z3_ast t2)
Create a predicate that checks that the bit-wise signed division of t1 and t2 does not overflow.
The nodes t1 and t2 must have the same bit-vector sort. The returned node is of sort Bool.
Referenced by z3py::BVSDivNoOverflow().
Z3_mk_bvsge()
Z3_ast Z3_API Z3_mk_bvsge (Z3_context c, Z3_ast t1, Z3_ast t2)
Two's complement signed greater than or equal to.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by BitVecRef::__ge__(), and z3::sge().
Z3_mk_bvsgt()
Z3_ast Z3_API Z3_mk_bvsgt (Z3_context c, Z3_ast t1, Z3_ast t2)
Two's complement signed greater than.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by BitVecRef::__gt__(), and z3::sgt().
Z3_mk_bvshl()
Z3_ast Z3_API Z3_mk_bvshl (Z3_context c, Z3_ast t1, Z3_ast t2)
Shift left.
It is equivalent to multiplication by 2^x where x is the value of the third argument.
NB. The semantics of shift operations varies between environments. This definition does not necessarily capture directly the semantics of the programming language or assembly architecture you are modeling.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by BitVecRef::__lshift__(), BitVecRef::__rlshift__(), and z3::shl().
Z3_mk_bvsle()
Z3_ast Z3_API Z3_mk_bvsle (Z3_context c, Z3_ast t1, Z3_ast t2)
Two's complement signed less than or equal to.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by BitVecRef::__le__(), and z3::sle().
Z3_mk_bvslt()
Z3_ast Z3_API Z3_mk_bvslt (Z3_context c, Z3_ast t1, Z3_ast t2)
Two's complement signed less than.
It abbreviates:
(or (and (= (extract[|m-1|:|m-1|] t1) bit1)
        (= (extract[|m-1|:|m-1|] t2) bit0))
    (and (= (extract[|m-1|:|m-1|] t1) (extract[|m-1|:|m-1|] t2))
        (bvult t1 t2)))
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by BitVecRef::__lt__(), and z3::slt().
Z3_mk_bvsmod()
Z3_ast Z3_API Z3_mk_bvsmod (Z3_context c, Z3_ast t1, Z3_ast t2)
Two's complement signed remainder (sign follows divisor).
If t2 is zero, then the result is undefined.
The nodes t1 and t2 must have the same bit-vector sort.
See also
Z3_mk_bvsrem
Referenced by BitVecRef::__mod__(), BitVecRef::__rmod__(), and z3::smod().
Z3_mk_bvsrem()
Z3_ast Z3_API Z3_mk_bvsrem (Z3_context c, Z3_ast t1, Z3_ast t2)
Two's complement signed remainder (sign follows dividend).
It is defined as t1 - (t1 /s t2) * t2, where /s represents signed division. The most significant bit (sign) of the result is equal to the most significant bit of t1.
If t2 is zero, then the result is undefined.
The nodes t1 and t2 must have the same bit-vector sort.
See also
Z3_mk_bvsmod
Referenced by z3py::SRem(), and z3::srem().
Z3_mk_bvsub()
Z3_ast Z3_API Z3_mk_bvsub (Z3_context c, Z3_ast t1, Z3_ast t2)
Standard two's complement subtraction.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by BitVecRef::__rsub__(), and BitVecRef::__sub__().
Z3_mk_bvsub_no_overflow()
Z3_ast Z3_API Z3_mk_bvsub_no_overflow (Z3_context c, Z3_ast t1, Z3_ast t2)
Create a predicate that checks that the bit-wise signed subtraction of t1 and t2 does not overflow.
The nodes t1 and t2 must have the same bit-vector sort. The returned node is of sort Bool.
Referenced by z3py::BVSubNoOverflow().
Z3_mk_bvsub_no_underflow()
Z3_ast Z3_API Z3_mk_bvsub_no_underflow (Z3_context c, Z3_ast t1, Z3_ast t2, bool is_signed)
Create a predicate that checks that the bit-wise subtraction of t1 and t2 does not underflow.
The nodes t1 and t2 must have the same bit-vector sort. The returned node is of sort Bool.
Referenced by z3py::BVSubNoUnderflow().
Z3_mk_bvudiv()
Z3_ast Z3_API Z3_mk_bvudiv (Z3_context c, Z3_ast t1, Z3_ast t2)
Unsigned division.
It is defined as the floor of t1/t2 if t2 is different from zero. If t2 is zero, then the result is undefined.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by z3py::UDiv(), and z3::udiv().
Z3_mk_bvuge()
Z3_ast Z3_API Z3_mk_bvuge (Z3_context c, Z3_ast t1, Z3_ast t2)
Unsigned greater than or equal to.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by z3py::UGE(), and z3::uge().
Z3_mk_bvugt()
Z3_ast Z3_API Z3_mk_bvugt (Z3_context c, Z3_ast t1, Z3_ast t2)
Unsigned greater than.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by z3py::UGT(), and z3::ugt().
Z3_mk_bvule()
Z3_ast Z3_API Z3_mk_bvule (Z3_context c, Z3_ast t1, Z3_ast t2)
Unsigned less than or equal to.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by z3py::ULE(), and z3::ule().
Z3_mk_bvult()
Z3_ast Z3_API Z3_mk_bvult (Z3_context c, Z3_ast t1, Z3_ast t2)
Unsigned less than.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by z3py::ULT(), and z3::ult().
Z3_mk_bvurem()
Z3_ast Z3_API Z3_mk_bvurem (Z3_context c, Z3_ast t1, Z3_ast t2)
Unsigned remainder.
It is defined as t1 - (t1 /u t2) * t2, where /u represents unsigned division.
If t2 is zero, then the result is undefined.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by z3py::URem(), and z3::urem().
Z3_mk_bvxnor()
Z3_ast Z3_API Z3_mk_bvxnor (Z3_context c, Z3_ast t1, Z3_ast t2)
Bitwise xnor.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_mk_bvxor()
Z3_ast Z3_API Z3_mk_bvxor (Z3_context c, Z3_ast t1, Z3_ast t2)
Bitwise exclusive-or.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by BitVecRef::__rxor__(), and BitVecRef::__xor__().
Z3_mk_char()
Z3_ast Z3_API Z3_mk_char (Z3_context c, unsigned ch)
Create a character literal.
Z3_mk_char_from_bv()
Z3_ast Z3_API Z3_mk_char_from_bv (Z3_context c, Z3_ast bv)
Create a character from a bit-vector (code point).
Referenced by expr::char_from_bv().
Z3_mk_char_is_digit()
Z3_ast Z3_API Z3_mk_char_is_digit (Z3_context c, Z3_ast ch)
Create a check if the character is a digit.
Referenced by expr::is_digit().
Z3_mk_char_le()
Z3_ast Z3_API Z3_mk_char_le (Z3_context c, Z3_ast ch1, Z3_ast ch2)
Create less than or equal to between two characters.
Z3_mk_char_sort()
Z3_sort Z3_API Z3_mk_char_sort (Z3_context c)
Create a sort for unicode characters.
The sort for characters can be changed to ASCII by setting the global parameter encoding to ascii, or alternative to 16 bit characters by setting encoding to bmp.
Referenced by context::char_sort().
Z3_mk_char_to_bv()
Z3_ast Z3_API Z3_mk_char_to_bv (Z3_context c, Z3_ast ch)
Create a bit-vector (code point) from character.
Referenced by expr::char_to_bv().
Z3_mk_char_to_int()
Z3_ast Z3_API Z3_mk_char_to_int (Z3_context c, Z3_ast ch)
Create an integer (code point) from character.
Referenced by expr::char_to_int().
Z3_mk_concat()
Z3_ast Z3_API Z3_mk_concat (Z3_context c, Z3_ast t1, Z3_ast t2)
Concatenate the given bit-vectors.
The nodes t1 and t2 must have (possibly different) bit-vector sorts
The result is a bit-vector of size n1+n2, where n1 (n2) is the size of t1 (t2).
Referenced by z3py::Concat().
Z3_mk_config()
Z3_config Z3_API Z3_mk_config (void)
Create a configuration object for the Z3 context object.
Configurations are created in order to assign parameters prior to creating contexts for Z3 interaction. For example, if the users wishes to use proof generation, then call:
Z3_set_param_value(cfg, "proof", "true")
Remarks
In previous versions of Z3, the Z3_config was used to store global and module configurations. Now, we should use Z3_global_param_set.
The following parameters can be set:
- proof  (Boolean)           Enable proof generation
- debug_ref_count (Boolean)  Enable debug support for Z3_ast reference counting
- trace  (Boolean)           Tracing support for VCC
- trace_file_name (String)   Trace out file for VCC traces
- timeout (unsigned)         default timeout (in milliseconds) used for solvers
- well_sorted_check          type checker
- auto_config                use heuristics to automatically select solver and configure it
- model                      model generation for solvers, this parameter can be overwritten when creating a solver
- model_validate             validate models produced by solvers
- unsat_core                 unsat-core generation for solvers, this parameter can be overwritten when creating a solver
- encoding                   the string encoding used internally (must be either "unicode" - 18 bit, "bmp" - 16 bit or "ascii" - 8 bit)
See also
Z3_set_param_value
Z3_del_config
Referenced by Context::__init__(), and config::config().
Z3_mk_const()
Z3_ast Z3_API Z3_mk_const (Z3_context c, Z3_symbol s, Z3_sort ty)
Declare and create a constant.
This function is a shorthand for:
Z3_func_decl d = Z3_mk_func_decl(c, s, 0, 0, ty);
Z3_ast n            = Z3_mk_app(c, d, 0, 0);
See also
Z3_mk_app
Z3_mk_fresh_const
Z3_mk_func_decl
Referenced by z3py::Array(), z3py::BitVec(), z3py::Bool(), z3py::Const(), context::constant(), z3py::Int(), and z3py::Real().
Z3_mk_const_array()
Z3_ast Z3_API Z3_mk_const_array (Z3_context c, Z3_sort domain, Z3_ast v)
Create the constant array.
The resulting term is an array, such that a select on an arbitrary index produces the value v.
Parameters
c logical context.
domain domain sort for the array.
v value that the array maps to.
Referenced by z3::const_array(), and z3py::K().
Z3_mk_constructor()
Z3_constructor Z3_API Z3_mk_constructor (Z3_context c, Z3_symbol name, Z3_symbol recognizer, unsigned num_fields, Z3_symbol const field_names[], Z3_sort const sorts[], unsigned sort_refs[])
Create a constructor.
Parameters
c logical context.
name constructor name.
recognizer name of recognizer function.
num_fields number of fields in constructor.
field_names names of the constructor fields.
sorts field sorts, 0 if the field sort refers to a recursive sort.
sort_refs reference to datatype sort that is an argument to the constructor; if the corresponding sort reference is 0, then the value in sort_refs should be an index referring to one of the recursive datatypes that is declared.
See also
Z3_del_constructor
Z3_mk_constructor_list
Z3_query_constructor
Referenced by constructors::add(), and z3py::CreateDatatypes().
Z3_mk_constructor_list()
Z3_constructor_list Z3_API Z3_mk_constructor_list (Z3_context c, unsigned num_constructors, Z3_constructor const constructors[])
Create list of constructors.
Parameters
c logical context.
num_constructors number of constructors in list.
constructors list of constructors.
See also
Z3_del_constructor_list
Z3_mk_constructor
Referenced by constructor_list::constructor_list(), and z3py::CreateDatatypes().
Z3_mk_context()
Z3_context Z3_API Z3_mk_context (Z3_config c)
Create a context using the given configuration.
After a context is created, the configuration cannot be changed, although some parameters can be changed using Z3_update_param_value. All main interaction with Z3 happens in the context of a Z3_context.
In contrast to Z3_mk_context_rc the life time of Z3_ast objects persists with the life time of the context.
Note that all other reference counted objects, including Z3_model, Z3_solver, Z3_func_interp have to be managed by the caller. Their reference counts are not handled by the context.
Remarks
Thread safety: objects created using a given context should not be accessed from different threads without synchronization. In other words, operations on a context are not thread safe. To use Z3 from different threads create separate context objects. The Z3_translate, Z3_solver_translate, Z3_model_translate, Z3_goal_translate methods are exposed to allow copying state from one context to another.
Z3_sort, Z3_func_decl, Z3_app, Z3_pattern are Z3_ast's.
Z3 uses hash-consing, i.e., when the same Z3_ast is created twice, Z3 will return the same pointer twice.
See also
Z3_del_context
Z3_mk_context_rc()
Z3_context Z3_API Z3_mk_context_rc (Z3_config c)
Create a context using the given configuration. This function is similar to Z3_mk_context. However, in the context returned by this function, the user is responsible for managing Z3_ast reference counters. Managing reference counters is a burden and error-prone, but allows the user to use the memory more efficiently. The user must invoke Z3_inc_ref for any Z3_ast returned by Z3, and Z3_dec_ref whenever the Z3_ast is not needed anymore. This idiom is similar to the one used in BDD (binary decision diagrams) packages such as CUDD.
Remarks:
Z3_sort, Z3_func_decl, Z3_app, Z3_pattern are Z3_ast's.
After a context is created, the configuration cannot be changed.
All main interaction with Z3 happens in the context of a Z3_context.
Z3 uses hash-consing, i.e., when the same Z3_ast is created twice, Z3 will return the same pointer twice.
Z3_mk_datatype()
Z3_sort Z3_API Z3_mk_datatype (Z3_context c, Z3_symbol name, unsigned num_constructors, Z3_constructor constructors[])
Create datatype, such as lists, trees, records, enumerations or unions of records. The datatype may be recursive. Return the datatype sort.
Parameters
c logical context.
name name of datatype.
num_constructors number of constructors passed in.
constructors array of constructor containers.
See also
Z3_mk_constructor
Z3_mk_constructor_list
Z3_mk_datatypes
Referenced by context::datatype().
Z3_mk_datatype_sort()
Z3_sort Z3_API Z3_mk_datatype_sort (Z3_context c, Z3_symbol name, unsigned num_params, Z3_sort const params[])
create a forward reference to a recursive datatype being declared. The forward reference can be used in a nested occurrence: the range of an array or as element sort of a sequence. The forward reference should only be used when used in an accessor for a recursive datatype that gets declared.
Forward references can replace the use sort references, that are unsigned integers in the Z3_mk_constructor call
Parameters
c logical context
name name of the datatype
num_params number of sort parameters
params array of sort parameters
Referenced by context::datatype_sort(), context::datatype_sort(), and z3py::DatatypeSort().
Z3_mk_datatypes()
void Z3_API Z3_mk_datatypes (Z3_context c, unsigned num_sorts, Z3_symbol const sort_names[], Z3_sort sorts[], Z3_constructor_list constructor_lists[])
Create mutually recursive datatypes.
Parameters
c logical context.
num_sorts number of datatype sorts.
sort_names names of datatype sorts.
sorts array of datatype sorts.
constructor_lists list of constructors, one list per sort.
See also
Z3_mk_constructor
Z3_mk_constructor_list
Z3_mk_datatype
Referenced by z3py::CreateDatatypes(), and context::datatypes().
Z3_mk_distinct()
Z3_ast Z3_API Z3_mk_distinct (Z3_context c, unsigned num_args, Z3_ast const args[])
Create an AST node representing distinct(args[0], ..., args[num_args-1]).
The distinct construct is used for declaring the arguments pairwise distinct. That is, Forall 0 <= i < j < num_args. not args[i] = args[j].
All arguments must have the same sort.
Remarks
The number of arguments of a distinct construct must be greater than one.
Referenced by ExprRef::__ne__(), and z3py::Distinct().
Z3_mk_div()
Z3_ast Z3_API Z3_mk_div (Z3_context c, Z3_ast arg1, Z3_ast arg2)
Create an AST node representing arg1 div arg2.
The arguments must either both have int type or both have real type. If the arguments have int type, then the result type is an int type, otherwise the the result type is real.
Referenced by ArithRef::__div__(), and ArithRef::__rdiv__().
Z3_mk_divides()
Z3_ast Z3_API Z3_mk_divides (Z3_context c, Z3_ast t1, Z3_ast t2)
Create division predicate.
The nodes t1 and t2 must be of integer sort. The predicate is true when t1 divides t2. For the predicate to be part of linear integer arithmetic, the first argument t1 must be a non-zero integer.
Z3_mk_empty_set()
Z3_ast Z3_API Z3_mk_empty_set (Z3_context c, Z3_sort domain)
Create the empty set.
Referenced by z3::empty_set(), and z3py::EmptySet().
Z3_mk_enumeration_sort()
Z3_sort Z3_API Z3_mk_enumeration_sort (Z3_context c, Z3_symbol name, unsigned n, Z3_symbol const enum_names[], Z3_func_decl enum_consts[], Z3_func_decl enum_testers[])
Create a enumeration sort.
An enumeration sort with n elements. This function will also declare the functions corresponding to the enumerations.
Parameters
c logical context
name name of the enumeration sort.
n number of elements in enumeration sort.
enum_names names of the enumerated elements.
enum_consts constants corresponding to the enumerated elements.
enum_testers predicates testing if terms of the enumeration sort correspond to an enumeration.
For example, if this function is called with three symbols A, B, C and the name S, then s is a sort whose name is S, and the function returns three terms corresponding to A, B, C in enum_consts. The array enum_testers has three predicates of type (s -> Bool). The first predicate (corresponding to A) is true when applied to A, and false otherwise. Similarly for the other predicates.
Referenced by context::enumeration_sort(), and z3py::EnumSort().
Z3_mk_eq()
Z3_ast Z3_API Z3_mk_eq (Z3_context c, Z3_ast l, Z3_ast r)
Create an AST node representing l = r.
The nodes l and r must have the same type.
Referenced by ExprRef::__eq__().
Z3_mk_exists()
Z3_ast Z3_API Z3_mk_exists (Z3_context c, unsigned weight, unsigned num_patterns, Z3_pattern const patterns[], unsigned num_decls, Z3_sort const sorts[], Z3_symbol const decl_names[], Z3_ast body)
Create an exists formula. Similar to Z3_mk_forall.
See also
Z3_mk_pattern
Z3_mk_bound
Z3_mk_forall
Z3_mk_quantifier
Z3_mk_exists_const()
Z3_ast Z3_API Z3_mk_exists_const (Z3_context c, unsigned weight, unsigned num_bound, Z3_app const bound[], unsigned num_patterns, Z3_pattern const patterns[], Z3_ast body)
Similar to Z3_mk_forall_const.
Create an existential quantifier using a list of constants that will form the set of bound variables.
Parameters
c logical context.
weight quantifiers are associated with weights indicating the importance of using the quantifier during instantiation. By default, pass the weight 0.
num_bound number of constants to be abstracted into bound variables.
bound array of constants to be abstracted into bound variables.
num_patterns number of patterns.
patterns array containing the patterns created using Z3_mk_pattern.
body the body of the quantifier.
See also
Z3_mk_pattern
Z3_mk_forall_const
Referenced by z3::exists(), z3::exists(), z3::exists(), z3::exists(), and z3::exists().
Z3_mk_ext_rotate_left()
Z3_ast Z3_API Z3_mk_ext_rotate_left (Z3_context c, Z3_ast t1, Z3_ast t2)
Rotate bits of t1 to the left t2 times.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by z3py::RotateLeft().
Z3_mk_ext_rotate_right()
Z3_ast Z3_API Z3_mk_ext_rotate_right (Z3_context c, Z3_ast t1, Z3_ast t2)
Rotate bits of t1 to the right t2 times.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by z3py::RotateRight().
Z3_mk_extract()
Z3_ast Z3_API Z3_mk_extract (Z3_context c, unsigned high, unsigned low, Z3_ast t1)
Extract the bits high down to low from a bit-vector of size m to yield a new bit-vector of size n, where n = high - low + 1.
The node t1 must have a bit-vector sort.
Referenced by z3py::Extract(), and expr::extract().
Z3_mk_false()
Z3_ast Z3_API Z3_mk_false (Z3_context c)
Create an AST node representing false.
Referenced by context::bool_val(), and z3py::BoolVal().
Z3_mk_finite_domain_sort()
Z3_sort Z3_API Z3_mk_finite_domain_sort (Z3_context c, Z3_symbol name, uint64_t size)
Create a named finite domain sort.
To create constants that belong to the finite domain, use the APIs for creating numerals and pass a numeric constant together with the sort returned by this call. The numeric constant should be between 0 and the less than the size of the domain.
See also
Z3_get_finite_domain_sort_size
Z3_mk_fixedpoint()
Z3_fixedpoint Z3_API Z3_mk_fixedpoint (Z3_context c)
Create a new fixedpoint context.
Remarks
User must use Z3_fixedpoint_inc_ref and Z3_fixedpoint_dec_ref to manage fixedpoint objects. Even if the context was created using Z3_mk_context instead of Z3_mk_context_rc.
Referenced by fixedpoint::fixedpoint().
Z3_mk_forall()
Z3_ast Z3_API Z3_mk_forall (Z3_context c, unsigned weight, unsigned num_patterns, Z3_pattern const patterns[], unsigned num_decls, Z3_sort const sorts[], Z3_symbol const decl_names[], Z3_ast body)
Create a forall formula. It takes an expression body that contains bound variables of the same sorts as the sorts listed in the array sorts. The bound variables are de-Bruijn indices created using Z3_mk_bound. The array decl_names contains the names that the quantified formula uses for the bound variables. Z3 applies the convention that the last element in the decl_names and sorts array refers to the variable with index 0, the second to last element of decl_names and sorts refers to the variable with index 1, etc.
Parameters
c logical context.
weight quantifiers are associated with weights indicating the importance of using the quantifier during instantiation. By default, pass the weight 0.
num_patterns number of patterns.
patterns array containing the patterns created using Z3_mk_pattern.
num_decls number of variables to be bound.
sorts the sorts of the bound variables.
decl_names names of the bound variables
body the body of the quantifier.
See also
Z3_mk_pattern
Z3_mk_bound
Z3_mk_exists
Z3_mk_forall_const()
Z3_ast Z3_API Z3_mk_forall_const (Z3_context c, unsigned weight, unsigned num_bound, Z3_app const bound[], unsigned num_patterns, Z3_pattern const patterns[], Z3_ast body)
Create a universal quantifier using a list of constants that will form the set of bound variables.
Parameters
c logical context.
weight quantifiers are associated with weights indicating the importance of using the quantifier during instantiation. By default, pass the weight 0.
num_bound number of constants to be abstracted into bound variables.
bound array of constants to be abstracted into bound variables.
num_patterns number of patterns.
patterns array containing the patterns created using Z3_mk_pattern.
body the body of the quantifier.
See also
Z3_mk_pattern
Z3_mk_exists_const
Referenced by z3::forall(), z3::forall(), z3::forall(), z3::forall(), and z3::forall().
Z3_mk_fpa_abs()
Z3_ast Z3_API Z3_mk_fpa_abs (Z3_context c, Z3_ast t)
Floating-point absolute value.
Parameters
c logical context
t term of FloatingPoint sort
See also
Z3_mk_fpa_is_negative
Z3_mk_fpa_is_positive
Z3_mk_fpa_neg
Z3_mk_fpa_add()
Z3_ast Z3_API Z3_mk_fpa_add (Z3_context c, Z3_ast rm, Z3_ast t1, Z3_ast t2)
Floating-point addition.
Parameters
c logical context
rm term of RoundingMode sort
t1 term of FloatingPoint sort
t2 term of FloatingPoint sort
rm must be of RoundingMode sort, t1 and t2 must have the same FloatingPoint sort.
Z3_mk_fpa_div()
Z3_ast Z3_API Z3_mk_fpa_div (Z3_context c, Z3_ast rm, Z3_ast t1, Z3_ast t2)
Floating-point division.
Parameters
c logical context
rm term of RoundingMode sort
t1 term of FloatingPoint sort.
t2 term of FloatingPoint sort
The nodes rm must be of RoundingMode sort, t1 and t2 must have the same FloatingPoint sort.
Z3_mk_fpa_eq()
Z3_ast Z3_API Z3_mk_fpa_eq (Z3_context c, Z3_ast t1, Z3_ast t2)
Floating-point equality.
Parameters
c logical context
t1 term of FloatingPoint sort
t2 term of FloatingPoint sort
Note that this is IEEE 754 equality (as opposed to SMT-LIB =).
t1 and t2 must have the same FloatingPoint sort.
See also
Z3_mk_fpa_geq
Z3_mk_fpa_gt
Z3_mk_fpa_leq
Z3_mk_fpa_lt
Z3_mk_fpa_fma()
Z3_ast Z3_API Z3_mk_fpa_fma (Z3_context c, Z3_ast rm, Z3_ast t1, Z3_ast t2, Z3_ast t3)
Floating-point fused multiply-add.
Parameters
c logical context
rm term of RoundingMode sort
t1 term of FloatingPoint sort
t2 term of FloatingPoint sort
t3 term of FloatingPoint sort
The result is round((t1 * t2) + t3).
rm must be of RoundingMode sort, t1, t2, and t3 must have the same FloatingPoint sort.
Z3_mk_fpa_fp()
Z3_ast Z3_API Z3_mk_fpa_fp (Z3_context c, Z3_ast sgn, Z3_ast exp, Z3_ast sig)
Create an expression of FloatingPoint sort from three bit-vector expressions.
This is the operator named ‘fp’ in the SMT FP theory definition. Note that sgn is required to be a bit-vector of size 1. Significand and exponent are required to be longer than 1 and 2 respectively. The FloatingPoint sort of the resulting expression is automatically determined from the bit-vector sizes of the arguments. The exponent is assumed to be in IEEE-754 biased representation.
Parameters
c logical context
sgn sign
exp exponent
sig significand
See also
Z3_mk_fpa_numeral_double
Z3_mk_fpa_numeral_float
Z3_mk_fpa_numeral_int
Z3_mk_fpa_numeral_int_uint
Z3_mk_fpa_numeral_int64_uint64
Z3_mk_numeral
Z3_mk_fpa_geq()
Z3_ast Z3_API Z3_mk_fpa_geq (Z3_context c, Z3_ast t1, Z3_ast t2)
Floating-point greater than or equal.
Parameters
c logical context
t1 term of FloatingPoint sort
t2 term of FloatingPoint sort
t1 and t2 must have the same FloatingPoint sort.
See also
Z3_mk_fpa_eq
Z3_mk_fpa_gt
Z3_mk_fpa_leq
Z3_mk_fpa_lt
Z3_mk_fpa_gt()
Z3_ast Z3_API Z3_mk_fpa_gt (Z3_context c, Z3_ast t1, Z3_ast t2)
Floating-point greater than.
Parameters
c logical context
t1 term of FloatingPoint sort
t2 term of FloatingPoint sort
t1 and t2 must have the same FloatingPoint sort.
See also
Z3_mk_fpa_eq
Z3_mk_fpa_geq
Z3_mk_fpa_leq
Z3_mk_fpa_lt
Z3_mk_fpa_inf()
Z3_ast Z3_API Z3_mk_fpa_inf (Z3_context c, Z3_sort s, bool negative)
Create a floating-point infinity of sort s.
Parameters
c logical context
s target sort
negative indicates whether the result should be negative
When negative is true, -oo will be generated instead of +oo.
See also
Z3_mk_fpa_is_infinite
Z3_mk_fpa_nan
Z3_mk_fpa_zero
Referenced by context::fpa_inf().
Z3_mk_fpa_is_infinite()
Z3_ast Z3_API Z3_mk_fpa_is_infinite (Z3_context c, Z3_ast t)
Predicate indicating whether t is a floating-point number representing +oo or -oo.
Parameters
c logical context
t term of FloatingPoint sort
t must have FloatingPoint sort.
See also
Z3_mk_fpa_inf
Z3_mk_fpa_is_nan
Z3_mk_fpa_is_normal
Z3_mk_fpa_is_subnormal
Z3_mk_fpa_is_zero
Referenced by expr::mk_is_inf().
Z3_mk_fpa_is_nan()
Z3_ast Z3_API Z3_mk_fpa_is_nan (Z3_context c, Z3_ast t)
Predicate indicating whether t is a NaN.
Parameters
c logical context
t term of FloatingPoint sort
t must have FloatingPoint sort.
See also
Z3_mk_fpa_is_infinite
Z3_mk_fpa_is_normal
Z3_mk_fpa_is_subnormal
Z3_mk_fpa_is_zero
Z3_mk_fpa_nan
Referenced by expr::mk_is_nan().
Z3_mk_fpa_is_negative()
Z3_ast Z3_API Z3_mk_fpa_is_negative (Z3_context c, Z3_ast t)
Predicate indicating whether t is a negative floating-point number.
Parameters
c logical context
t term of FloatingPoint sort
t must have FloatingPoint sort.
See also
Z3_mk_fpa_abs
Z3_mk_fpa_is_positive
Z3_mk_fpa_neg
Z3_mk_fpa_is_normal()
Z3_ast Z3_API Z3_mk_fpa_is_normal (Z3_context c, Z3_ast t)
Predicate indicating whether t is a normal floating-point number.
Parameters
c logical context
t term of FloatingPoint sort
t must have FloatingPoint sort.
See also
Z3_mk_fpa_is_infinite
Z3_mk_fpa_is_nan
Z3_mk_fpa_is_subnormal
Z3_mk_fpa_is_zero
Referenced by expr::mk_is_normal().
Z3_mk_fpa_is_positive()
Z3_ast Z3_API Z3_mk_fpa_is_positive (Z3_context c, Z3_ast t)
Predicate indicating whether t is a positive floating-point number.
Parameters
c logical context
t term of FloatingPoint sort
t must have FloatingPoint sort.
See also
Z3_mk_fpa_abs
Z3_mk_fpa_is_negative
Z3_mk_fpa_neg
Z3_mk_fpa_is_subnormal()
Z3_ast Z3_API Z3_mk_fpa_is_subnormal (Z3_context c, Z3_ast t)
Predicate indicating whether t is a subnormal floating-point number.
Parameters
c logical context
t term of FloatingPoint sort
t must have FloatingPoint sort.
See also
Z3_mk_fpa_is_infinite
Z3_mk_fpa_is_nan
Z3_mk_fpa_is_normal
Z3_mk_fpa_is_zero
Referenced by expr::mk_is_subnormal().
Z3_mk_fpa_is_zero()
Z3_ast Z3_API Z3_mk_fpa_is_zero (Z3_context c, Z3_ast t)
Predicate indicating whether t is a floating-point number with zero value, i.e., +zero or -zero.
Parameters
c logical context
t term of FloatingPoint sort
t must have FloatingPoint sort.
See also
Z3_mk_fpa_is_infinite
Z3_mk_fpa_is_nan
Z3_mk_fpa_is_normal
Z3_mk_fpa_is_subnormal
Z3_mk_fpa_zero
Referenced by expr::mk_is_zero().
Z3_mk_fpa_leq()
Z3_ast Z3_API Z3_mk_fpa_leq (Z3_context c, Z3_ast t1, Z3_ast t2)
Floating-point less than or equal.
Parameters
c logical context
t1 term of FloatingPoint sort
t2 term of FloatingPoint sort
t1 and t2 must have the same FloatingPoint sort.
See also
Z3_mk_fpa_eq
Z3_mk_fpa_geq
Z3_mk_fpa_gt
Z3_mk_fpa_lt
Z3_mk_fpa_lt()
Z3_ast Z3_API Z3_mk_fpa_lt (Z3_context c, Z3_ast t1, Z3_ast t2)
Floating-point less than.
Parameters
c logical context
t1 term of FloatingPoint sort
t2 term of FloatingPoint sort
t1 and t2 must have the same FloatingPoint sort.
See also
Z3_mk_fpa_eq
Z3_mk_fpa_geq
Z3_mk_fpa_gt
Z3_mk_fpa_leq
Z3_mk_fpa_max()
Z3_ast Z3_API Z3_mk_fpa_max (Z3_context c, Z3_ast t1, Z3_ast t2)
Maximum of floating-point numbers.
Parameters
c logical context
t1 term of FloatingPoint sort
t2 term of FloatingPoint sort
t1, t2 must have the same FloatingPoint sort.
See also
Z3_mk_fpa_min
Z3_mk_fpa_min()
Z3_ast Z3_API Z3_mk_fpa_min (Z3_context c, Z3_ast t1, Z3_ast t2)
Minimum of floating-point numbers.
Parameters
c logical context
t1 term of FloatingPoint sort
t2 term of FloatingPoint sort
t1, t2 must have the same FloatingPoint sort.
See also
Z3_mk_fpa_max
Z3_mk_fpa_mul()
Z3_ast Z3_API Z3_mk_fpa_mul (Z3_context c, Z3_ast rm, Z3_ast t1, Z3_ast t2)
Floating-point multiplication.
Parameters
c logical context
rm term of RoundingMode sort
t1 term of FloatingPoint sort
t2 term of FloatingPoint sort
rm must be of RoundingMode sort, t1 and t2 must have the same FloatingPoint sort.
Z3_mk_fpa_nan()
Z3_ast Z3_API Z3_mk_fpa_nan (Z3_context c, Z3_sort s)
Create a floating-point NaN of sort s.
Parameters
c logical context
s target sort
See also
Z3_mk_fpa_inf
Z3_mk_fpa_is_nan
Z3_mk_fpa_zero
Referenced by context::fpa_nan().
Z3_mk_fpa_neg()
Z3_ast Z3_API Z3_mk_fpa_neg (Z3_context c, Z3_ast t)
Floating-point negation.
Parameters
c logical context
t term of FloatingPoint sort
See also
Z3_mk_fpa_abs
Z3_mk_fpa_is_negative
Z3_mk_fpa_is_positive
Z3_mk_fpa_numeral_double()
Z3_ast Z3_API Z3_mk_fpa_numeral_double (Z3_context c, double v, Z3_sort ty)
Create a numeral of FloatingPoint sort from a double.
This function is used to create numerals that fit in a double value. It is slightly faster than Z3_mk_numeral since it is not necessary to parse a string.
Parameters
c logical context
v value
ty sort
ty must be a FloatingPoint sort
See also
Z3_mk_fpa_fp
Z3_mk_fpa_numeral_float
Z3_mk_fpa_numeral_int
Z3_mk_fpa_numeral_int_uint
Z3_mk_fpa_numeral_int64_uint64
Z3_mk_numeral
Referenced by context::fpa_val().
Z3_mk_fpa_numeral_float()
Z3_ast Z3_API Z3_mk_fpa_numeral_float (Z3_context c, float v, Z3_sort ty)
Create a numeral of FloatingPoint sort from a float.
This function is used to create numerals that fit in a float value. It is slightly faster than Z3_mk_numeral since it is not necessary to parse a string.
Parameters
c logical context
v value
ty sort
ty must be a FloatingPoint sort
See also
Z3_mk_fpa_fp
Z3_mk_fpa_numeral_double
Z3_mk_fpa_numeral_int
Z3_mk_fpa_numeral_int_uint
Z3_mk_fpa_numeral_int64_uint64
Z3_mk_numeral
Referenced by context::fpa_val().
Z3_mk_fpa_numeral_int()
Z3_ast Z3_API Z3_mk_fpa_numeral_int (Z3_context c, signed v, Z3_sort ty)
Create a numeral of FloatingPoint sort from a signed integer.
Parameters
c logical context
v value
ty result sort
ty must be a FloatingPoint sort
See also
Z3_mk_fpa_fp
Z3_mk_fpa_numeral_double
Z3_mk_fpa_numeral_float
Z3_mk_fpa_numeral_int_uint
Z3_mk_fpa_numeral_int64_uint64
Z3_mk_numeral
Z3_mk_fpa_numeral_int64_uint64()
Z3_ast Z3_API Z3_mk_fpa_numeral_int64_uint64 (Z3_context c, bool sgn, int64_t exp, uint64_t sig, Z3_sort ty)
Create a numeral of FloatingPoint sort from a sign bit and two 64-bit integers.
Parameters
c logical context
sgn sign bit (true == negative)
sig significand
exp exponent
ty result sort
ty must be a FloatingPoint sort
See also
Z3_mk_fpa_fp
Z3_mk_fpa_numeral_double
Z3_mk_fpa_numeral_float
Z3_mk_fpa_numeral_int
Z3_mk_fpa_numeral_int_uint
Z3_mk_numeral
Z3_mk_fpa_numeral_int_uint()
Z3_ast Z3_API Z3_mk_fpa_numeral_int_uint (Z3_context c, bool sgn, signed exp, unsigned sig, Z3_sort ty)
Create a numeral of FloatingPoint sort from a sign bit and two integers.
Parameters
c logical context
sgn sign bit (true == negative)
sig significand
exp exponent
ty result sort
ty must be a FloatingPoint sort
See also
Z3_mk_fpa_fp
Z3_mk_fpa_numeral_double
Z3_mk_fpa_numeral_float
Z3_mk_fpa_numeral_int
Z3_mk_fpa_numeral_int64_uint64
Z3_mk_numeral
Z3_mk_fpa_rem()
Z3_ast Z3_API Z3_mk_fpa_rem (Z3_context c, Z3_ast t1, Z3_ast t2)
Floating-point remainder.
Parameters
c logical context
t1 term of FloatingPoint sort
t2 term of FloatingPoint sort
t1 and t2 must have the same FloatingPoint sort.
Z3_mk_fpa_rna()
Z3_ast Z3_API Z3_mk_fpa_rna (Z3_context c)
Create a numeral of RoundingMode sort which represents the NearestTiesToAway rounding mode.
This is the same as Z3_mk_fpa_round_nearest_ties_to_away.
Parameters
c logical context
See also
Z3_mk_fpa_rounding_mode_sort
Z3_mk_fpa_rne
Z3_mk_fpa_rtn
Z3_mk_fpa_rtp
Z3_mk_fpa_rtz
Referenced by context::fpa_rounding_mode().
Z3_mk_fpa_rne()
Z3_ast Z3_API Z3_mk_fpa_rne (Z3_context c)
Create a numeral of RoundingMode sort which represents the NearestTiesToEven rounding mode.
This is the same as Z3_mk_fpa_round_nearest_ties_to_even.
Parameters
c logical context
See also
Z3_mk_fpa_rounding_mode_sort
Z3_mk_fpa_rna
Z3_mk_fpa_rtn
Z3_mk_fpa_rtp
Z3_mk_fpa_rtz
Referenced by context::fpa_rounding_mode().
Z3_mk_fpa_round_nearest_ties_to_away()
Z3_ast Z3_API Z3_mk_fpa_round_nearest_ties_to_away (Z3_context c)
Create a numeral of RoundingMode sort which represents the NearestTiesToAway rounding mode.
This is the same as Z3_mk_fpa_rna.
Parameters
c logical context
See also
Z3_mk_fpa_rounding_mode_sort
Z3_mk_fpa_round_nearest_ties_to_even
Z3_mk_fpa_round_toward_negative
Z3_mk_fpa_round_toward_positive
Z3_mk_fpa_round_toward_zero
Z3_mk_fpa_round_nearest_ties_to_even()
Z3_ast Z3_API Z3_mk_fpa_round_nearest_ties_to_even (Z3_context c)
Create a numeral of RoundingMode sort which represents the NearestTiesToEven rounding mode.
This is the same as Z3_mk_fpa_rne.
Parameters
c logical context
See also
Z3_mk_fpa_rounding_mode_sort
Z3_mk_fpa_round_nearest_ties_to_away
Z3_mk_fpa_round_toward_negative
Z3_mk_fpa_round_toward_positive
Z3_mk_fpa_round_toward_zero
Z3_mk_fpa_round_to_integral()
Z3_ast Z3_API Z3_mk_fpa_round_to_integral (Z3_context c, Z3_ast rm, Z3_ast t)
Floating-point roundToIntegral. Rounds a floating-point number to the closest integer, again represented as a floating-point number.
Parameters
c logical context
rm term of RoundingMode sort
t term of FloatingPoint sort
t must be of FloatingPoint sort.
Z3_mk_fpa_round_toward_negative()
Z3_ast Z3_API Z3_mk_fpa_round_toward_negative (Z3_context c)
Create a numeral of RoundingMode sort which represents the TowardNegative rounding mode.
This is the same as Z3_mk_fpa_rtn.
Parameters
c logical context
See also
Z3_mk_fpa_rounding_mode_sort
Z3_mk_fpa_round_nearest_ties_to_away
Z3_mk_fpa_round_nearest_ties_to_even
Z3_mk_fpa_round_toward_positive
Z3_mk_fpa_round_toward_zero
Z3_mk_fpa_round_toward_positive()
Z3_ast Z3_API Z3_mk_fpa_round_toward_positive (Z3_context c)
Create a numeral of RoundingMode sort which represents the TowardPositive rounding mode.
This is the same as Z3_mk_fpa_rtp.
Parameters
c logical context
See also
Z3_mk_fpa_rounding_mode_sort
Z3_mk_fpa_round_nearest_ties_to_away
Z3_mk_fpa_round_nearest_ties_to_even
Z3_mk_fpa_round_toward_negative
Z3_mk_fpa_round_toward_zero
Z3_mk_fpa_round_toward_zero()
Z3_ast Z3_API Z3_mk_fpa_round_toward_zero (Z3_context c)
Create a numeral of RoundingMode sort which represents the TowardZero rounding mode.
This is the same as Z3_mk_fpa_rtz.
Parameters
c logical context
See also
Z3_mk_fpa_rounding_mode_sort
Z3_mk_fpa_round_nearest_ties_to_away
Z3_mk_fpa_round_nearest_ties_to_even
Z3_mk_fpa_round_toward_negative
Z3_mk_fpa_round_toward_positive
Z3_mk_fpa_rounding_mode_sort()
Z3_sort Z3_API Z3_mk_fpa_rounding_mode_sort (Z3_context c)
Create the RoundingMode sort.
Parameters
c logical context
See also
Z3_mk_fpa_round_nearest_ties_to_away or Z3_mk_fpa_rna
Z3_mk_fpa_round_nearest_ties_to_even or Z3_mk_fpa_rne
Z3_mk_fpa_round_toward_negative or Z3_mk_fpa_rtn
Z3_mk_fpa_round_toward_positive or Z3_mk_fpa_rtp
Z3_mk_fpa_round_toward_zero or Z3_mk_fpa_rtz
Referenced by context::fpa_rounding_mode_sort().
Z3_mk_fpa_rtn()
Z3_ast Z3_API Z3_mk_fpa_rtn (Z3_context c)
Create a numeral of RoundingMode sort which represents the TowardNegative rounding mode.
This is the same as Z3_mk_fpa_round_toward_negative.
Parameters
c logical context
See also
Z3_mk_fpa_rounding_mode_sort
Z3_mk_fpa_rna
Z3_mk_fpa_rne
Z3_mk_fpa_rtp
Z3_mk_fpa_rtz
Referenced by context::fpa_rounding_mode().
Z3_mk_fpa_rtp()
Z3_ast Z3_API Z3_mk_fpa_rtp (Z3_context c)
Create a numeral of RoundingMode sort which represents the TowardPositive rounding mode.
This is the same as Z3_mk_fpa_round_toward_positive.
Parameters
c logical context
See also
Z3_mk_fpa_rounding_mode_sort
Z3_mk_fpa_rna
Z3_mk_fpa_rne
Z3_mk_fpa_rtn
Z3_mk_fpa_rtz
Referenced by context::fpa_rounding_mode().
Z3_mk_fpa_rtz()
Z3_ast Z3_API Z3_mk_fpa_rtz (Z3_context c)
Create a numeral of RoundingMode sort which represents the TowardZero rounding mode.
This is the same as Z3_mk_fpa_round_toward_zero.
Parameters
c logical context
See also
Z3_mk_fpa_rounding_mode_sort
Z3_mk_fpa_rna
Z3_mk_fpa_rne
Z3_mk_fpa_rtn
Z3_mk_fpa_rtp
Referenced by context::fpa_rounding_mode().
Z3_mk_fpa_sort()
Z3_sort Z3_API Z3_mk_fpa_sort (Z3_context c, unsigned ebits, unsigned sbits)
Create a FloatingPoint sort.
Parameters
c logical context
ebits number of exponent bits
sbits number of significand bits
Remarks
ebits must be larger than 1 and sbits must be larger than 2.
See also
Z3_mk_fpa_sort_half or Z3_mk_fpa_sort_16
Z3_mk_fpa_sort_single or Z3_mk_fpa_sort_32
Z3_mk_fpa_sort_double or Z3_mk_fpa_sort_64
Z3_mk_fpa_sort_quadruple or Z3_mk_fpa_sort_128
Referenced by context::fpa_sort().
Z3_mk_fpa_sort_128()
Z3_sort Z3_API Z3_mk_fpa_sort_128 (Z3_context c)
Create the quadruple-precision (128-bit) FloatingPoint sort.
This is the same as Z3_mk_fpa_sort_quadruple.
Parameters
c logical context
See also
Z3_mk_fpa_sort
Z3_mk_fpa_sort_16
Z3_mk_fpa_sort_32
Z3_mk_fpa_sort_64
Z3_mk_fpa_sort_16()
Z3_sort Z3_API Z3_mk_fpa_sort_16 (Z3_context c)
Create the half-precision (16-bit) FloatingPoint sort.
This is the same as Z3_mk_fpa_sort_half.
Parameters
c logical context
See also
Z3_mk_fpa_sort
Z3_mk_fpa_sort_32
Z3_mk_fpa_sort_64
Z3_mk_fpa_sort_128
Z3_mk_fpa_sort_32()
Z3_sort Z3_API Z3_mk_fpa_sort_32 (Z3_context c)
Create the single-precision (32-bit) FloatingPoint sort.
This is the same as Z3_mk_fpa_sort_single.
Parameters
c logical context
See also
Z3_mk_fpa_sort
Z3_mk_fpa_sort_16
Z3_mk_fpa_sort_64
Z3_mk_fpa_sort_128
Z3_mk_fpa_sort_64()
Z3_sort Z3_API Z3_mk_fpa_sort_64 (Z3_context c)
Create the double-precision (64-bit) FloatingPoint sort.
This is the same as Z3_mk_fpa_sort_double.
Parameters
c logical context
See also
Z3_mk_fpa_sort
Z3_mk_fpa_sort_16
Z3_mk_fpa_sort_32
Z3_mk_fpa_sort_128
Z3_mk_fpa_sort_double()
Z3_sort Z3_API Z3_mk_fpa_sort_double (Z3_context c)
Create the double-precision (64-bit) FloatingPoint sort.
This is the same as Z3_mk_fpa_sort_64.
Parameters
c logical context
See also
Z3_mk_fpa_sort
Z3_mk_fpa_sort_half
Z3_mk_fpa_sort_single
Z3_mk_fpa_sort_quadruple
Z3_mk_fpa_sort_half()
Z3_sort Z3_API Z3_mk_fpa_sort_half (Z3_context c)
Create the half-precision (16-bit) FloatingPoint sort.
This is the same as Z3_mk_fpa_sort_16.
Parameters
c logical context
See also
Z3_mk_fpa_sort
Z3_mk_fpa_sort_single
Z3_mk_fpa_sort_double
Z3_mk_fpa_sort_quadruple
Z3_mk_fpa_sort_quadruple()
Z3_sort Z3_API Z3_mk_fpa_sort_quadruple (Z3_context c)
Create the quadruple-precision (128-bit) FloatingPoint sort.
This is the same as Z3_mk_fpa_sort_128.
Parameters
c logical context
See also
Z3_mk_fpa_sort
Z3_mk_fpa_sort_half
Z3_mk_fpa_sort_single
Z3_mk_fpa_sort_double
Z3_mk_fpa_sort_single()
Z3_sort Z3_API Z3_mk_fpa_sort_single (Z3_context c)
Create the single-precision (32-bit) FloatingPoint sort.
This is the same as Z3_mk_fpa_sort_32.
Parameters
c logical context.
See also
Z3_mk_fpa_sort
Z3_mk_fpa_sort_half
Z3_mk_fpa_sort_double
Z3_mk_fpa_sort_quadruple
Z3_mk_fpa_sqrt()
Z3_ast Z3_API Z3_mk_fpa_sqrt (Z3_context c, Z3_ast rm, Z3_ast t)
Floating-point square root.
Parameters
c logical context
rm term of RoundingMode sort
t term of FloatingPoint sort
rm must be of RoundingMode sort, t must have FloatingPoint sort.
Z3_mk_fpa_sub()
Z3_ast Z3_API Z3_mk_fpa_sub (Z3_context c, Z3_ast rm, Z3_ast t1, Z3_ast t2)
Floating-point subtraction.
Parameters
c logical context
rm term of RoundingMode sort
t1 term of FloatingPoint sort
t2 term of FloatingPoint sort
rm must be of RoundingMode sort, t1 and t2 must have the same FloatingPoint sort.
Z3_mk_fpa_to_fp_bv()
Z3_ast Z3_API Z3_mk_fpa_to_fp_bv (Z3_context c, Z3_ast bv, Z3_sort s)
Conversion of a single IEEE 754-2008 bit-vector into a floating-point number.
Produces a term that represents the conversion of a bit-vector term bv to a floating-point term of sort s.
Parameters
c logical context
bv a bit-vector term
s floating-point sort
s must be a FloatingPoint sort, t must be of bit-vector sort, and the bit-vector size of bv must be equal to ebits+sbits of s. The format of the bit-vector is as defined by the IEEE 754-2008 interchange format.
Referenced by expr::mk_from_ieee_bv().
Z3_mk_fpa_to_fp_float()
Z3_ast Z3_API Z3_mk_fpa_to_fp_float (Z3_context c, Z3_ast rm, Z3_ast t, Z3_sort s)
Conversion of a FloatingPoint term into another term of different FloatingPoint sort.
Produces a term that represents the conversion of a floating-point term t to a floating-point term of sort s. If necessary, the result will be rounded according to rounding mode rm.
Parameters
c logical context
rm term of RoundingMode sort
t term of FloatingPoint sort
s floating-point sort
s must be a FloatingPoint sort, rm must be of RoundingMode sort, t must be of floating-point sort.
Z3_mk_fpa_to_fp_int_real()
Z3_ast Z3_API Z3_mk_fpa_to_fp_int_real (Z3_context c, Z3_ast rm, Z3_ast exp, Z3_ast sig, Z3_sort s)
Conversion of a real-sorted significand and an integer-sorted exponent into a term of FloatingPoint sort.
Produces a term that represents the conversion of sig * 2^exp into a floating-point term of sort s. If necessary, the result will be rounded according to rounding mode rm.
Parameters
c logical context
rm term of RoundingMode sort
exp exponent term of Int sort
sig significand term of Real sort
s FloatingPoint sort
s must be a FloatingPoint sort, rm must be of RoundingMode sort, exp must be of int sort, sig must be of real sort.
Z3_mk_fpa_to_fp_real()
Z3_ast Z3_API Z3_mk_fpa_to_fp_real (Z3_context c, Z3_ast rm, Z3_ast t, Z3_sort s)
Conversion of a term of real sort into a term of FloatingPoint sort.
Produces a term that represents the conversion of term t of real sort into a floating-point term of sort s. If necessary, the result will be rounded according to rounding mode rm.
Parameters
c logical context
rm term of RoundingMode sort
t term of Real sort
s floating-point sort
s must be a FloatingPoint sort, rm must be of RoundingMode sort, t must be of real sort.
Z3_mk_fpa_to_fp_signed()
Z3_ast Z3_API Z3_mk_fpa_to_fp_signed (Z3_context c, Z3_ast rm, Z3_ast t, Z3_sort s)
Conversion of a 2's complement signed bit-vector term into a term of FloatingPoint sort.
Produces a term that represents the conversion of the bit-vector term t into a floating-point term of sort s. The bit-vector t is taken to be in signed 2's complement format. If necessary, the result will be rounded according to rounding mode rm.
Parameters
c logical context
rm term of RoundingMode sort
t term of bit-vector sort
s floating-point sort
s must be a FloatingPoint sort, rm must be of RoundingMode sort, t must be of bit-vector sort.
Z3_mk_fpa_to_fp_unsigned()
Z3_ast Z3_API Z3_mk_fpa_to_fp_unsigned (Z3_context c, Z3_ast rm, Z3_ast t, Z3_sort s)
Conversion of a 2's complement unsigned bit-vector term into a term of FloatingPoint sort.
Produces a term that represents the conversion of the bit-vector term t into a floating-point term of sort s. The bit-vector t is taken to be in unsigned 2's complement format. If necessary, the result will be rounded according to rounding mode rm.
Parameters
c logical context
rm term of RoundingMode sort
t term of bit-vector sort
s floating-point sort
s must be a FloatingPoint sort, rm must be of RoundingMode sort, t must be of bit-vector sort.
Z3_mk_fpa_to_ieee_bv()
Z3_ast Z3_API Z3_mk_fpa_to_ieee_bv (Z3_context c, Z3_ast t)
Conversion of a floating-point term into a bit-vector term in IEEE 754-2008 format.
Parameters
c logical context
t term of FloatingPoint sort
t must have FloatingPoint sort. The size of the resulting bit-vector is automatically determined.
Note that IEEE 754-2008 allows multiple different representations of NaN. This conversion knows only one NaN and it will always produce the same bit-vector representation of that NaN.
Referenced by expr::mk_to_ieee_bv().
Z3_mk_fpa_to_real()
Z3_ast Z3_API Z3_mk_fpa_to_real (Z3_context c, Z3_ast t)
Conversion of a floating-point term into a real-numbered term.
Produces a term that represents the conversion of the floating-point term t into a real number. Note that this type of conversion will often result in non-linear constraints over real terms.
Parameters
c logical context
t term of FloatingPoint sort
Z3_mk_fpa_to_sbv()
Z3_ast Z3_API Z3_mk_fpa_to_sbv (Z3_context c, Z3_ast rm, Z3_ast t, unsigned sz)
Conversion of a floating-point term into a signed bit-vector.
Produces a term that represents the conversion of the floating-point term t into a bit-vector term of size sz in signed 2's complement format. If necessary, the result will be rounded according to rounding mode rm.
Parameters
c logical context
rm term of RoundingMode sort
t term of FloatingPoint sort
sz size of the resulting bit-vector
Z3_mk_fpa_to_ubv()
Z3_ast Z3_API Z3_mk_fpa_to_ubv (Z3_context c, Z3_ast rm, Z3_ast t, unsigned sz)
Conversion of a floating-point term into an unsigned bit-vector.
Produces a term that represents the conversion of the floating-point term t into a bit-vector term of size sz in unsigned 2's complement format. If necessary, the result will be rounded according to rounding mode rm.
Parameters
c logical context
rm term of RoundingMode sort
t term of FloatingPoint sort
sz size of the resulting bit-vector
Z3_mk_fpa_zero()
Z3_ast Z3_API Z3_mk_fpa_zero (Z3_context c, Z3_sort s, bool negative)
Create a floating-point zero of sort s.
Parameters
c logical context
s target sort
negative indicates whether the result should be negative
When negative is true, -zero will be generated instead of +zero.
See also
Z3_mk_fpa_inf
Z3_mk_fpa_is_zero
Z3_mk_fpa_nan
Z3_mk_fresh_const()
Z3_ast Z3_API Z3_mk_fresh_const (Z3_context c, Z3_string prefix, Z3_sort ty)
Declare and create a fresh constant.
This function is a shorthand for:
Z3_func_decl d = Z3_mk_fresh_func_decl(c, prefix, 0, 0, ty); Z3_ast n = Z3_mk_app(c, d, 0, 0);
Remarks
If prefix is NULL, then it is assumed to be the empty string.
See also
Z3_mk_app
Z3_mk_const
Z3_mk_fresh_func_decl
Z3_mk_func_decl
Referenced by z3py::FreshBool(), z3py::FreshConst(), z3py::FreshInt(), and z3py::FreshReal().
Z3_mk_fresh_func_decl()
Z3_func_decl Z3_API Z3_mk_fresh_func_decl (Z3_context c, Z3_string prefix, unsigned domain_size, Z3_sort const domain[], Z3_sort range)
Declare a fresh constant or function.
Z3 will generate an unique name for this function declaration. If prefix is different from NULL, then the name generate by Z3 will start with prefix.
Remarks
If prefix is NULL, then it is assumed to be the empty string.
See also
Z3_mk_func_decl
Referenced by z3py::FreshFunction().
Z3_mk_full_set()
Z3_ast Z3_API Z3_mk_full_set (Z3_context c, Z3_sort domain)
Create the full set.
Referenced by z3::full_set(), and z3py::FullSet().
Z3_mk_func_decl()
Z3_func_decl Z3_API Z3_mk_func_decl (Z3_context c, Z3_symbol s, unsigned domain_size, Z3_sort const domain[], Z3_sort range)
Declare a constant or function.
Parameters
c logical context.
s name of the constant or function.
domain_size number of arguments. It is 0 when declaring a constant.
domain array containing the sort of each argument. The array must contain domain_size elements. It is 0 when declaring a constant.
range sort of the constant or the return sort of the function.
After declaring a constant or function, the function Z3_mk_app can be used to create a constant or function application.
See also
Z3_mk_app
Z3_mk_fresh_func_decl
Z3_mk_rec_func_decl
Referenced by context::function(), context::function(), context::function(), context::function(), context::function(), z3py::Function(), context::function(), and context::function().
Z3_mk_ge()
Z3_ast Z3_API Z3_mk_ge (Z3_context c, Z3_ast t1, Z3_ast t2)
Create greater than or equal to.
The nodes t1 and t2 must have the same sort, and must be int or real.
Referenced by ArithRef::__ge__().
Z3_mk_goal()
Z3_goal Z3_API Z3_mk_goal (Z3_context c, bool models, bool unsat_cores, bool proofs)
Create a goal (aka problem). A goal is essentially a set of formulas, that can be solved and/or transformed using tactics and solvers.
If models is true, then model generation is enabled for the new goal.
If unsat_cores is true, then unsat core generation is enabled for the new goal.
If proofs is true, then proof generation is enabled for the new goal. Remark, the Z3 context c must have been created with proof generation support.
Remarks
Reference counting must be used to manage goals, even when the Z3_context was created using Z3_mk_context instead of Z3_mk_context_rc.
Referenced by goal::goal().
Z3_mk_gt()
Z3_ast Z3_API Z3_mk_gt (Z3_context c, Z3_ast t1, Z3_ast t2)
Create greater than.
The nodes t1 and t2 must have the same sort, and must be int or real.
Referenced by ArithRef::__gt__().
Z3_mk_iff()
Z3_ast Z3_API Z3_mk_iff (Z3_context c, Z3_ast t1, Z3_ast t2)
Create an AST node representing t1 iff t2.
The nodes t1 and t2 must have Boolean sort.
Z3_mk_implies()
Z3_ast Z3_API Z3_mk_implies (Z3_context c, Z3_ast t1, Z3_ast t2)
Create an AST node representing t1 implies t2.
The nodes t1 and t2 must have Boolean sort.
Referenced by z3py::Implies().
Z3_mk_int()
Z3_ast Z3_API Z3_mk_int (Z3_context c, int v, Z3_sort ty)
Create a numeral of an int, bit-vector, or finite-domain sort.
This function can be used to create numerals that fit in a machine integer. It is slightly faster than Z3_mk_numeral since it is not necessary to parse a string.
See also
Z3_mk_numeral
Referenced by context::bv_val(), context::int_val(), context::num_val(), and context::real_val().
Z3_mk_int2bv()
Z3_ast Z3_API Z3_mk_int2bv (Z3_context c, unsigned n, Z3_ast t1)
Create an n bit bit-vector from the integer argument t1.
The resulting bit-vector has n bits, where the i'th bit (counting from 0 to n-1) is 1 if (t1 div 2^i) mod 2 is 1.
The node t1 must have integer sort.
Referenced by z3py::Int2BV().
Z3_mk_int2real()
Z3_ast Z3_API Z3_mk_int2real (Z3_context c, Z3_ast t1)
Coerce an integer to a real.
There is also a converse operation exposed. It follows the semantics prescribed by the SMT-LIB standard.
You can take the floor of a real by creating an auxiliary integer constant k and and asserting mk_int2real(k) <= t1 < mk_int2real(k)+1.
The node t1 must have sort integer.
See also
Z3_mk_real2int
Z3_mk_is_int
Referenced by z3::to_real(), and z3py::ToReal().
Z3_mk_int64()
Z3_ast Z3_API Z3_mk_int64 (Z3_context c, int64_t v, Z3_sort ty)
Create a numeral of a int, bit-vector, or finite-domain sort.
This function can be used to create numerals that fit in a machine int64_t integer. It is slightly faster than Z3_mk_numeral since it is not necessary to parse a string.
See also
Z3_mk_numeral
Referenced by context::bv_val(), context::int_val(), and context::real_val().
Z3_mk_int_sort()
Z3_sort Z3_API Z3_mk_int_sort (Z3_context c)
Create the integer type.
This type is not the int type found in programming languages. A machine integer can be represented using bit-vectors. The function Z3_mk_bv_sort creates a bit-vector type.
See also
Z3_mk_bv_sort
Referenced by context::int_sort(), and z3py::IntSort().
Z3_mk_int_symbol()
Z3_symbol Z3_API Z3_mk_int_symbol (Z3_context c, int i)
Create a Z3 symbol using an integer.
Symbols are used to name several term and type constructors.
NB. Not all integers can be passed to this function. The legal range of unsigned integers is 0 to 2^30-1.
See also
Z3_get_symbol_int
Z3_mk_string_symbol
Referenced by context::int_symbol(), and z3py::to_symbol().
Z3_mk_int_to_str()
Z3_ast Z3_API Z3_mk_int_to_str (Z3_context c, Z3_ast s)
Integer to string conversion.
Referenced by expr::itos().
Z3_mk_is_int()
Z3_ast Z3_API Z3_mk_is_int (Z3_context c, Z3_ast t1)
Check if a real number is an integer.
See also
Z3_mk_int2real
Z3_mk_real2int
Referenced by z3py::IsInt().
Z3_mk_ite()
Z3_ast Z3_API Z3_mk_ite (Z3_context c, Z3_ast t1, Z3_ast t2, Z3_ast t3)
Create an AST node representing an if-then-else: ite(t1, t2, t3).
The node t1 must have Boolean sort, t2 and t3 must have the same sort. The sort of the new node is equal to the sort of t2 and t3.
Referenced by z3py::If().
Z3_mk_lambda()
Z3_ast Z3_API Z3_mk_lambda (Z3_context c, unsigned num_decls, Z3_sort const sorts[], Z3_symbol const decl_names[], Z3_ast body)
Create a lambda expression. It takes an expression body that contains bound variables of the same sorts as the sorts listed in the array sorts. The bound variables are de-Bruijn indices created using Z3_mk_bound. The array decl_names contains the names that the quantified formula uses for the bound variables. Z3 applies the convention that the last element in the decl_names and sorts array refers to the variable with index 0, the second to last element of decl_names and sorts refers to the variable with index 1, etc. The sort of the resulting expression is (Array sorts range) where range is the sort of body. For example, if the lambda binds two variables of sort Int and Bool, and the body has sort Real, the sort of the expression is (Array Int Bool Real).
Parameters
c logical context
num_decls number of variables to be bound.
sorts the sorts of the bound variables.
decl_names names of the bound variables
body the body of the lambda expression.
See also
Z3_mk_bound
Z3_mk_forall
Z3_mk_lambda_const
Z3_mk_lambda_const()
Z3_ast Z3_API Z3_mk_lambda_const (Z3_context c, unsigned num_bound, Z3_app const bound[], Z3_ast body)
Create a lambda expression using a list of constants that form the set of bound variables.
Parameters
c logical context.
num_bound number of constants to be abstracted into bound variables.
bound array of constants to be abstracted into bound variables.
body the body of the lambda expression.
See also
Z3_mk_bound
Z3_mk_forall
Z3_mk_lambda
Referenced by z3::lambda(), z3::lambda(), z3::lambda(), z3::lambda(), z3::lambda(), and z3py::Lambda().
Z3_mk_le()
Z3_ast Z3_API Z3_mk_le (Z3_context c, Z3_ast t1, Z3_ast t2)
Create less than or equal to.
The nodes t1 and t2 must have the same sort, and must be int or real.
Referenced by ArithRef::__le__().
Z3_mk_linear_order()
Z3_func_decl Z3_API Z3_mk_linear_order (Z3_context c, Z3_sort a, unsigned id)
create a linear ordering relation over signature a. The relation is identified by the index id.
Referenced by z3::linear_order().
Z3_mk_list_sort()
Z3_sort Z3_API Z3_mk_list_sort (Z3_context c, Z3_symbol name, Z3_sort elem_sort, Z3_func_decl * nil_decl, Z3_func_decl * is_nil_decl, Z3_func_decl * cons_decl, Z3_func_decl * is_cons_decl, Z3_func_decl * head_decl, Z3_func_decl * tail_decl)
Create a list sort.
A list sort over elem_sort This function declares the corresponding constructors and testers for lists.
Parameters
c logical context
name name of the list sort.
elem_sort sort of list elements.
nil_decl declaration for the empty list.
is_nil_decl test for the empty list.
cons_decl declaration for a cons cell.
is_cons_decl cons cell test.
head_decl list head.
tail_decl list tail.
Z3_mk_lstring()
Z3_ast Z3_API Z3_mk_lstring (Z3_context c, unsigned len, Z3_string s)
Create a string constant out of the string that is passed in It takes the length of the string as well to take into account 0 characters. The string is treated as if it is unescaped so a sequence of characters \u{0} is treated as 5 characters and not the character 0.
Referenced by context::string_val().
Z3_mk_lt()
Z3_ast Z3_API Z3_mk_lt (Z3_context c, Z3_ast t1, Z3_ast t2)
Create less than.
The nodes t1 and t2 must have the same sort, and must be int or real.
Referenced by ArithRef::__lt__().
Z3_mk_map()
Z3_ast Z3_API Z3_mk_map (Z3_context c, Z3_func_decl f, unsigned n, Z3_ast const * args)
Map f on the argument arrays.
The n nodes args must be of array sorts [domain_i -> range_i]. The function declaration f must have type range_1 .. range_n -> range. v must have sort range. The sort of the result is [domain_i -> range].
See also
Z3_mk_array_sort
Z3_mk_store
Z3_mk_select
Referenced by z3py::Map().
Z3_mk_mod()
Z3_ast Z3_API Z3_mk_mod (Z3_context c, Z3_ast arg1, Z3_ast arg2)
Create an AST node representing arg1 mod arg2.
The arguments must have int type.
Referenced by ArithRef::__mod__(), and ArithRef::__rmod__().
Z3_mk_model()
Z3_model Z3_API Z3_mk_model (Z3_context c)
Create a fresh model object. It has reference count 0.
Referenced by model::model(), and z3py::Model().
Z3_mk_mul()
Z3_ast Z3_API Z3_mk_mul (Z3_context c, unsigned num_args, Z3_ast const args[])
Create an AST node representing args[0] * ... * args[num_args-1].
The array args must have num_args elements. All arguments must have int or real sort.
Remarks
Z3 has limited support for non-linear arithmetic.
The number of arguments must be greater than zero.
Z3_mk_not()
Z3_ast Z3_API Z3_mk_not (Z3_context c, Z3_ast a)
Create an AST node representing not(a).
The node a must have Boolean sort.
Referenced by z3py::Not().
Z3_mk_numeral()
Z3_ast Z3_API Z3_mk_numeral (Z3_context c, Z3_string numeral, Z3_sort ty)
Create a numeral of a given sort.
Parameters
c logical context.
numeral A string representing the numeral value in decimal notation. The string may be of the form [num]*[.[num]*][E[+|-][num]+]. If the given sort is a real, then the numeral can be a rational, that is, a string of the form [num]* / [num]* .
ty The sort of the numeral. In the current implementation, the given sort can be an int, real, finite-domain, or bit-vectors of arbitrary size.
See also
Z3_mk_int
Z3_mk_unsigned_int
Referenced by z3py::BitVecVal(), context::bv_val(), context::int_val(), z3py::IntVal(), context::real_val(), and z3py::RealVal().
Z3_mk_optimize()
Z3_optimize Z3_API Z3_mk_optimize (Z3_context c)
Create a new optimize context.
Remarks
User must use Z3_optimize_inc_ref and Z3_optimize_dec_ref to manage optimize objects. Even if the context was created using Z3_mk_context instead of Z3_mk_context_rc.
Referenced by optimize::optimize(), and optimize::optimize().
Z3_mk_or()
Z3_ast Z3_API Z3_mk_or (Z3_context c, unsigned num_args, Z3_ast const args[])
Create an AST node representing args[0] or ... or args[num_args-1].
The array args must have num_args elements. All arguments must have Boolean sort.
Remarks
The number of arguments must be greater than zero.
Referenced by z3py::Or().
Z3_mk_params()
Z3_params Z3_API Z3_mk_params (Z3_context c)
Create a Z3 (empty) parameter set. Starting at Z3 4.0, parameter sets are used to configure many components such as: simplifiers, tactics, solvers, etc.
Remarks
Reference counting must be used to manage parameter sets, even when the Z3_context was created using Z3_mk_context instead of Z3_mk_context_rc.
Referenced by params::params().
Z3_mk_parser_context()
Z3_parser_context Z3_API Z3_mk_parser_context (Z3_context c)
Create a parser context.
A parser context maintains state between calls to Z3_parser_context_parse_string where the caller can pass in a set of SMTLIB2 commands. It maintains all the declarations from previous calls together with of sorts and function declarations (including 0-ary) that are added directly to the context.
Z3_mk_partial_order()
Z3_func_decl Z3_API Z3_mk_partial_order (Z3_context c, Z3_sort a, unsigned id)
create a partial ordering relation over signature a and index id.
Referenced by z3::partial_order().
Z3_mk_pattern()
Z3_pattern Z3_API Z3_mk_pattern (Z3_context c, unsigned num_patterns, Z3_ast const terms[])
Create a pattern for quantifier instantiation.
Z3 uses pattern matching to instantiate quantifiers. If a pattern is not provided for a quantifier, then Z3 will automatically compute a set of patterns for it. However, for optimal performance, the user should provide the patterns.
Patterns comprise a list of terms. The list should be non-empty. If the list comprises of more than one term, it is a called a multi-pattern.
In general, one can pass in a list of (multi-)patterns in the quantifier constructor.
See also
Z3_mk_forall
Z3_mk_exists
Referenced by z3py::MultiPattern().
Z3_mk_pbeq()
Z3_ast Z3_API Z3_mk_pbeq (Z3_context c, unsigned num_args, Z3_ast const args[], int const coeffs[], int k)
Pseudo-Boolean relations.
Encode k1*p1 + k2*p2 + ... + kn*pn = k
Z3_mk_pbge()
Z3_ast Z3_API Z3_mk_pbge (Z3_context c, unsigned num_args, Z3_ast const args[], int const coeffs[], int k)
Pseudo-Boolean relations.
Encode k1*p1 + k2*p2 + ... + kn*pn >= k
Z3_mk_pble()
Z3_ast Z3_API Z3_mk_pble (Z3_context c, unsigned num_args, Z3_ast const args[], int const coeffs[], int k)
Pseudo-Boolean relations.
Encode k1*p1 + k2*p2 + ... + kn*pn <= k
Z3_mk_piecewise_linear_order()
Z3_func_decl Z3_API Z3_mk_piecewise_linear_order (Z3_context c, Z3_sort a, unsigned id)
create a piecewise linear ordering relation over signature a and index id.
Referenced by z3::piecewise_linear_order().
Z3_mk_polymorphic_datatype()
Z3_sort Z3_API Z3_mk_polymorphic_datatype (Z3_context c, Z3_symbol name, unsigned num_parameters, Z3_sort parameters[], unsigned num_constructors, Z3_constructor constructors[])
Create a parametric datatype with explicit type parameters.
This function is similar to Z3_mk_datatype, except it takes an explicit set of type parameters. The parameters can be type variables created with Z3_mk_type_variable, allowing the definition of polymorphic datatypes that can be instantiated with different concrete types.
Parameters
c logical context
name name of the datatype
num_parameters number of type parameters (can be 0)
parameters array of type parameters (type variables or concrete sorts)
num_constructors number of constructors
constructors array of constructor specifications
See also
Z3_mk_datatype
Z3_mk_type_variable
Z3_mk_datatype_sort
Referenced by context::datatype().
Z3_mk_power()
Z3_ast Z3_API Z3_mk_power (Z3_context c, Z3_ast arg1, Z3_ast arg2)
Create an AST node representing arg1 ^ arg2.
The arguments must have int or real type.
Referenced by ArithRef::__pow__(), and ArithRef::__rpow__().
Z3_mk_probe()
Z3_probe Z3_API Z3_mk_probe (Z3_context c, Z3_string name)
Return a probe associated with the given name. The complete list of probes may be obtained using the procedures Z3_get_num_probes and Z3_get_probe_name. It may also be obtained using the command (help-tactic) in the SMT 2.0 front-end.
Probes are used to inspect a goal (aka problem) and collect information that may be used to decide which solver and/or preprocessing step will be used.
Referenced by probe::probe().
Z3_mk_quantifier()
Z3_ast Z3_API Z3_mk_quantifier (Z3_context c, bool is_forall, unsigned weight, unsigned num_patterns, Z3_pattern const patterns[], unsigned num_decls, Z3_sort const sorts[], Z3_symbol const decl_names[], Z3_ast body)
Create a quantifier - universal or existential, with pattern hints. See the documentation for Z3_mk_forall for an explanation of the parameters.
Parameters
c logical context.
is_forall flag to indicate if this is a universal or existential quantifier.
weight quantifiers are associated with weights indicating the importance of using the quantifier during instantiation. By default, pass the weight 0.
num_patterns number of patterns.
patterns array containing the patterns created using Z3_mk_pattern.
num_decls number of variables to be bound.
sorts array of sorts of the bound variables.
decl_names names of the bound variables.
body the body of the quantifier.
See also
Z3_mk_pattern
Z3_mk_bound
Z3_mk_forall
Z3_mk_exists
Z3_mk_quantifier_const()
Z3_ast Z3_API Z3_mk_quantifier_const (Z3_context c, bool is_forall, unsigned weight, unsigned num_bound, Z3_app const bound[], unsigned num_patterns, Z3_pattern const patterns[], Z3_ast body)
Create a universal or existential quantifier using a list of constants that will form the set of bound variables.
Z3_mk_quantifier_const_ex()
Z3_ast Z3_API Z3_mk_quantifier_const_ex (Z3_context c, bool is_forall, unsigned weight, Z3_symbol quantifier_id, Z3_symbol skolem_id, unsigned num_bound, Z3_app const bound[], unsigned num_patterns, Z3_pattern const patterns[], unsigned num_no_patterns, Z3_ast const no_patterns[], Z3_ast body)
Create a universal or existential quantifier using a list of constants that will form the set of bound variables.
Referenced by z3py::_mk_quantifier().
Z3_mk_quantifier_ex()
Z3_ast Z3_API Z3_mk_quantifier_ex (Z3_context c, bool is_forall, unsigned weight, Z3_symbol quantifier_id, Z3_symbol skolem_id, unsigned num_patterns, Z3_pattern const patterns[], unsigned num_no_patterns, Z3_ast const no_patterns[], unsigned num_decls, Z3_sort const sorts[], Z3_symbol const decl_names[], Z3_ast body)
Create a quantifier - universal or existential, with pattern hints, no patterns, and attributes.
Parameters
c logical context.
is_forall flag to indicate if this is a universal or existential quantifier.
quantifier_id identifier to identify quantifier
skolem_id identifier to identify skolem constants introduced by quantifier.
weight quantifiers are associated with weights indicating the importance of using the quantifier during instantiation. By default, pass the weight 0.
num_patterns number of patterns.
patterns array containing the patterns created using Z3_mk_pattern.
num_no_patterns number of no_patterns.
no_patterns array containing subexpressions to be excluded from inferred patterns.
num_decls number of variables to be bound.
sorts array of sorts of the bound variables.
decl_names names of the bound variables.
body the body of the quantifier.
See also
Z3_mk_pattern
Z3_mk_bound
Z3_mk_forall
Z3_mk_exists
Z3_mk_re_allchar()
Z3_ast Z3_API Z3_mk_re_allchar (Z3_context c, Z3_sort regex_sort)
Create a regular expression that accepts all singleton sequences of the regular expression sort.
Z3_mk_re_complement()
Z3_ast Z3_API Z3_mk_re_complement (Z3_context c, Z3_ast re)
Create the complement of the regular language re.
Referenced by z3::re_complement().
Z3_mk_re_concat()
Z3_ast Z3_API Z3_mk_re_concat (Z3_context c, unsigned n, Z3_ast const args[])
Create the concatenation of the regular languages.
Precondition
n > 0
Referenced by z3py::Concat().
Z3_mk_re_diff()
Z3_ast Z3_API Z3_mk_re_diff (Z3_context c, Z3_ast re1, Z3_ast re2)
Create the difference of regular expressions.
Referenced by z3::re_diff().
Z3_mk_re_empty()
Z3_ast Z3_API Z3_mk_re_empty (Z3_context c, Z3_sort re)
Create an empty regular expression of sort re.
Precondition
re is a regular expression sort.
Referenced by z3::re_empty().
Z3_mk_re_full()
Z3_ast Z3_API Z3_mk_re_full (Z3_context c, Z3_sort re)
Create an universal regular expression of sort re.
Precondition
re is a regular expression sort.
Referenced by z3::re_full().
Z3_mk_re_intersect()
Z3_ast Z3_API Z3_mk_re_intersect (Z3_context c, unsigned n, Z3_ast const args[])
Create the intersection of the regular languages.
Precondition
n > 0
Referenced by z3::re_intersect().
Z3_mk_re_loop()
Z3_ast Z3_API Z3_mk_re_loop (Z3_context c, Z3_ast r, unsigned lo, unsigned hi)
Create a regular expression loop. The supplied regular expression r is repeated between lo and hi times. The lo should be below hi with one exception: when supplying the value hi as 0, the meaning is to repeat the argument r at least lo number of times, and with an unbounded upper bound.
Referenced by expr::loop(), and expr::loop().
Z3_mk_re_option()
Z3_ast Z3_API Z3_mk_re_option (Z3_context c, Z3_ast re)
Create the regular language [re].
Referenced by z3::option().
Z3_mk_re_plus()
Z3_ast Z3_API Z3_mk_re_plus (Z3_context c, Z3_ast re)
Create the regular language re+.
Referenced by z3::plus().
Z3_mk_re_power()
Z3_ast Z3_API Z3_mk_re_power (Z3_context c, Z3_ast re, unsigned n)
Create a power regular expression.
Z3_mk_re_range()
Z3_ast Z3_API Z3_mk_re_range (Z3_context c, Z3_ast lo, Z3_ast hi)
Create the range regular expression over two sequences of length 1.
Z3_mk_re_sort()
Z3_sort Z3_API Z3_mk_re_sort (Z3_context c, Z3_sort seq)
Create a regular expression sort out of a sequence sort.
Referenced by context::re_sort().
Z3_mk_re_star()
Z3_ast Z3_API Z3_mk_re_star (Z3_context c, Z3_ast re)
Create the regular language re*.
Referenced by z3::star().
Z3_mk_re_union()
Z3_ast Z3_API Z3_mk_re_union (Z3_context c, unsigned n, Z3_ast const args[])
Create the union of the regular languages.
Precondition
n > 0
Z3_mk_real()
Z3_ast Z3_API Z3_mk_real (Z3_context c, int num, int den)
Create a real from a fraction.
Parameters
c logical context.
num numerator of rational.
den denominator of rational.
Precondition
den != 0
See also
Z3_mk_numeral
Z3_mk_int
Z3_mk_real_int64
Z3_mk_unsigned_int
Z3_mk_real2int()
Z3_ast Z3_API Z3_mk_real2int (Z3_context c, Z3_ast t1)
Coerce a real to an integer.
The semantics of this function follows the SMT-LIB standard for the function to_int
See also
Z3_mk_int2real
Z3_mk_is_int
Referenced by z3py::ToInt().
Z3_mk_real_int64()
Z3_ast Z3_API Z3_mk_real_int64 (Z3_context c, int64_t num, int64_t den)
Create a real from a fraction of int64.
See also
Z3_mk_real
Referenced by context::real_val().
Z3_mk_real_sort()
Z3_sort Z3_API Z3_mk_real_sort (Z3_context c)
Create the real type.
Note that this type is not a floating point number.
Referenced by context::real_sort(), and z3py::RealSort().
Z3_mk_rec_func_decl()
Z3_func_decl Z3_API Z3_mk_rec_func_decl (Z3_context c, Z3_symbol s, unsigned domain_size, Z3_sort const domain[], Z3_sort range)
Declare a recursive function.
Parameters
c logical context.
s name of the function.
domain_size number of arguments. It should be greater than 0.
domain array containing the sort of each argument. The array must contain domain_size elements.
range sort of the constant or the return sort of the function.
After declaring recursive function, it should be associated with a recursive definition Z3_add_rec_def. The function Z3_mk_app can be used to create a constant or function application.
See also
Z3_add_rec_def
Z3_mk_app
Z3_mk_func_decl
Referenced by context::recfun(), context::recfun(), and z3py::RecFunction().
Z3_mk_rem()
Z3_ast Z3_API Z3_mk_rem (Z3_context c, Z3_ast arg1, Z3_ast arg2)
Create an AST node representing arg1 rem arg2.
The arguments must have int type.
Z3_mk_repeat()
Z3_ast Z3_API Z3_mk_repeat (Z3_context c, unsigned i, Z3_ast t1)
Repeat the given bit-vector up length i.
The node t1 must have a bit-vector sort.
Referenced by expr::repeat(), and z3py::RepeatBitVec().
Z3_mk_rotate_left()
Z3_ast Z3_API Z3_mk_rotate_left (Z3_context c, unsigned i, Z3_ast t1)
Rotate bits of t1 to the left i times.
The node t1 must have a bit-vector sort.
Referenced by expr::rotate_left().
Z3_mk_rotate_right()
Z3_ast Z3_API Z3_mk_rotate_right (Z3_context c, unsigned i, Z3_ast t1)
Rotate bits of t1 to the right i times.
The node t1 must have a bit-vector sort.
Referenced by expr::rotate_right().
Z3_mk_sbv_to_str()
Z3_ast Z3_API Z3_mk_sbv_to_str (Z3_context c, Z3_ast s)
Signed bit-vector to string conversion.
Referenced by expr::sbvtos().
Z3_mk_select()
Z3_ast Z3_API Z3_mk_select (Z3_context c, Z3_ast a, Z3_ast i)
Array read. The argument a is the array and i is the index of the array that gets read.
The node a must have an array sort [domain -> range], and i must have the sort domain. The sort of the result is range.
See also
Z3_mk_array_sort
Z3_mk_store
Referenced by z3py::_array_select(), and z3::select().
Z3_mk_select_n()
Z3_ast Z3_API Z3_mk_select_n (Z3_context c, Z3_ast a, unsigned n, Z3_ast const * idxs)
n-ary Array read. The argument a is the array and idxs are the indices of the array that gets read.
Referenced by z3py::_array_select(), and z3::select().
Z3_mk_seq_at()
Z3_ast Z3_API Z3_mk_seq_at (Z3_context c, Z3_ast s, Z3_ast index)
Retrieve from s the unit sequence positioned at position index. The sequence is empty if the index is out of bounds.
Referenced by expr::at().
Z3_mk_seq_concat()
Z3_ast Z3_API Z3_mk_seq_concat (Z3_context c, unsigned n, Z3_ast const args[])
Concatenate sequences.
Precondition
n > 0
Referenced by z3py::Concat().
Z3_mk_seq_contains()
Z3_ast Z3_API Z3_mk_seq_contains (Z3_context c, Z3_ast container, Z3_ast containee)
Check if container contains containee.
Precondition
container and containee are the same sequence sorts.
Referenced by expr::contains().
Z3_mk_seq_empty()
Z3_ast Z3_API Z3_mk_seq_empty (Z3_context c, Z3_sort seq)
Create an empty sequence of the sequence sort seq.
Precondition
s is a sequence sort.
Referenced by z3::empty().
Z3_mk_seq_extract()
Z3_ast Z3_API Z3_mk_seq_extract (Z3_context c, Z3_ast s, Z3_ast offset, Z3_ast length)
Extract subsequence starting at offset of length.
Referenced by expr::extract(), and z3py::Extract().
Z3_mk_seq_foldl()
Z3_ast Z3_API Z3_mk_seq_foldl (Z3_context c, Z3_ast f, Z3_ast a, Z3_ast s)
Create a fold of the function f over the sequence s with accumulator a.
Referenced by z3::foldl().
Z3_mk_seq_foldli()
Z3_ast Z3_API Z3_mk_seq_foldli (Z3_context c, Z3_ast f, Z3_ast i, Z3_ast a, Z3_ast s)
Create a fold with index tracking of the function f over the sequence s with accumulator a starting at index i.
Referenced by z3::foldli().
Z3_mk_seq_in_re()
Z3_ast Z3_API Z3_mk_seq_in_re (Z3_context c, Z3_ast seq, Z3_ast re)
Check if seq is in the language generated by the regular expression re.
Referenced by z3::in_re().
Z3_mk_seq_index()
Z3_ast Z3_API Z3_mk_seq_index (Z3_context c, Z3_ast s, Z3_ast substr, Z3_ast offset)
Return index of the first occurrence of substr in s starting from offset offset. If s does not contain substr, then the value is -1, if offset is the length of s, then the value is -1 as well. The value is -1 if offset is negative or larger than the length of s.
Referenced by z3::indexof().
Z3_mk_seq_last_index()
Z3_ast Z3_API Z3_mk_seq_last_index (Z3_context c, Z3_ast s, Z3_ast substr)
Return index of the last occurrence of substr in s. If s does not contain substr, then the value is -1,.
Referenced by z3::last_indexof().
Z3_mk_seq_length()
Z3_ast Z3_API Z3_mk_seq_length (Z3_context c, Z3_ast s)
Return the length of the sequence s.
Referenced by expr::length().
Z3_mk_seq_map()
Z3_ast Z3_API Z3_mk_seq_map (Z3_context c, Z3_ast f, Z3_ast s)
Create a map of the function f over the sequence s.
Referenced by z3::map().
Z3_mk_seq_mapi()
Z3_ast Z3_API Z3_mk_seq_mapi (Z3_context c, Z3_ast f, Z3_ast i, Z3_ast s)
Create a map of the function f over the sequence s starting at index i.
Referenced by z3::mapi().
Z3_mk_seq_nth()
Z3_ast Z3_API Z3_mk_seq_nth (Z3_context c, Z3_ast s, Z3_ast index)
Retrieve from s the element positioned at position index. The function is under-specified if the index is out of bounds.
Referenced by expr::nth().
Z3_mk_seq_prefix()
Z3_ast Z3_API Z3_mk_seq_prefix (Z3_context c, Z3_ast prefix, Z3_ast s)
Check if prefix is a prefix of s.
Precondition
prefix and s are the same sequence sorts.
Referenced by z3::prefixof().
Z3_mk_seq_replace()
Z3_ast Z3_API Z3_mk_seq_replace (Z3_context c, Z3_ast s, Z3_ast src, Z3_ast dst)
Replace the first occurrence of src with dst in s.
Referenced by expr::replace().
Z3_mk_seq_replace_all()
Z3_ast Z3_API Z3_mk_seq_replace_all (Z3_context c, Z3_ast s, Z3_ast src, Z3_ast dst)
Replace all occurrences of src with dst in s.
Z3_mk_seq_replace_re()
Z3_ast Z3_API Z3_mk_seq_replace_re (Z3_context c, Z3_ast s, Z3_ast re, Z3_ast dst)
Replace the first occurrence of regular expression re with dst in s.
Z3_mk_seq_replace_re_all()
Z3_ast Z3_API Z3_mk_seq_replace_re_all (Z3_context c, Z3_ast s, Z3_ast re, Z3_ast dst)
Replace all occurrences of regular expression re with dst in s.
Z3_mk_seq_sort()
Z3_sort Z3_API Z3_mk_seq_sort (Z3_context c, Z3_sort s)
Create a sequence sort out of the sort for the elements.
Referenced by context::seq_sort().
Z3_mk_seq_suffix()
Z3_ast Z3_API Z3_mk_seq_suffix (Z3_context c, Z3_ast suffix, Z3_ast s)
Check if suffix is a suffix of s.
Precondition
suffix and s are the same sequence sorts.
Referenced by z3::suffixof().
Z3_mk_seq_to_re()
Z3_ast Z3_API Z3_mk_seq_to_re (Z3_context c, Z3_ast seq)
Create a regular expression that accepts the sequence seq.
Referenced by z3::to_re().
Z3_mk_seq_unit()
Z3_ast Z3_API Z3_mk_seq_unit (Z3_context c, Z3_ast a)
Create a unit sequence of a.
Referenced by expr::unit().
Z3_mk_set_add()
Z3_ast Z3_API Z3_mk_set_add (Z3_context c, Z3_ast set, Z3_ast elem)
Add an element to a set.
The first argument must be a set, the second an element.
Referenced by z3::set_add(), and z3py::SetAdd().
Z3_mk_set_complement()
Z3_ast Z3_API Z3_mk_set_complement (Z3_context c, Z3_ast arg)
Take the complement of a set.
Referenced by z3::set_complement(), and z3py::SetComplement().
Z3_mk_set_del()
Z3_ast Z3_API Z3_mk_set_del (Z3_context c, Z3_ast set, Z3_ast elem)
Remove an element to a set.
The first argument must be a set, the second an element.
Referenced by z3::set_del(), and z3py::SetDel().
Z3_mk_set_difference()
Z3_ast Z3_API Z3_mk_set_difference (Z3_context c, Z3_ast arg1, Z3_ast arg2)
Take the set difference between two sets.
Referenced by z3::set_difference(), and z3py::SetDifference().
Z3_mk_set_intersect()
Z3_ast Z3_API Z3_mk_set_intersect (Z3_context c, unsigned num_args, Z3_ast const args[])
Take the intersection of a list of sets.
Referenced by z3::set_intersect(), and z3py::SetIntersect().
Z3_mk_set_member()
Z3_ast Z3_API Z3_mk_set_member (Z3_context c, Z3_ast elem, Z3_ast set)
Check for set membership.
The first argument should be an element type of the set.
Referenced by z3py::IsMember(), and z3::set_member().
Z3_mk_set_sort()
Z3_sort Z3_API Z3_mk_set_sort (Z3_context c, Z3_sort ty)
Create Set type.
Z3_mk_set_subset()
Z3_ast Z3_API Z3_mk_set_subset (Z3_context c, Z3_ast arg1, Z3_ast arg2)
Check for subsetness of sets.
Referenced by z3py::IsSubset(), and z3::set_subset().
Z3_mk_set_union()
Z3_ast Z3_API Z3_mk_set_union (Z3_context c, unsigned num_args, Z3_ast const args[])
Take the union of a list of sets.
Referenced by z3::set_union(), and z3py::SetUnion().
Z3_mk_sign_ext()
Z3_ast Z3_API Z3_mk_sign_ext (Z3_context c, unsigned i, Z3_ast t1)
Sign-extend of the given bit-vector to the (signed) equivalent bit-vector of size m+i, where m is the size of the given bit-vector.
The node t1 must have a bit-vector sort.
Referenced by z3::sext(), and z3py::SignExt().
Z3_mk_simple_solver()
Z3_solver Z3_API Z3_mk_simple_solver (Z3_context c)
Create a new incremental solver.
This is equivalent to applying the "smt" tactic.
Unlike Z3_mk_solver() this solver
Does not attempt to apply any logic specific tactics.
Does not change its behaviour based on whether it used incrementally/non-incrementally.
Note that these differences can result in very different performance compared to Z3_mk_solver().
The function Z3_solver_get_model retrieves a model if the assertions is satisfiable (i.e., the result is Z3_L_TRUE) and model construction is enabled. The function Z3_solver_get_model can also be used even if the result is Z3_L_UNDEF, but the returned model is not guaranteed to satisfy quantified assertions.
Remarks
User must use Z3_solver_inc_ref and Z3_solver_dec_ref to manage solver objects. Even if the context was created using Z3_mk_context instead of Z3_mk_context_rc.
See also
Z3_mk_solver
Z3_mk_solver_for_logic
Z3_mk_solver_from_tactic
Referenced by solver::solver().
Z3_mk_simplifier()
Z3_simplifier Z3_API Z3_mk_simplifier (Z3_context c, Z3_string name)
Return a simplifier associated with the given name. The complete list of simplifiers may be obtained using the procedures Z3_get_num_simplifiers and Z3_get_simplifier_name. It may also be obtained using the command (help-simplifier) in the SMT 2.0 front-end.
Simplifiers are the basic building block for creating custom solvers for specific problem domains.
Referenced by simplifier::simplifier().
Z3_mk_solver()
Z3_solver Z3_API Z3_mk_solver (Z3_context c)
Create a new solver. This solver is a "combined solver" (see combined_solver module) that internally uses a non-incremental (solver1) and an incremental solver (solver2). This combined solver changes its behaviour based on how it is used and how its parameters are set.
If the solver is used in a non incremental way (i.e. no calls to Z3_solver_push() or Z3_solver_pop(), and no calls to Z3_solver_assert() or Z3_solver_assert_and_track() after checking satisfiability without an intervening Z3_solver_reset()) then solver1 will be used. This solver will apply Z3's "default" tactic.
The "default" tactic will attempt to probe the logic used by the assertions and will apply a specialized tactic if one is supported. Otherwise the general (and-then simplify smt) tactic will be used.
If the solver is used in an incremental way then the combined solver will switch to using solver2 (which behaves similarly to the general "smt" tactic).
Note however it is possible to set the solver2_timeout, solver2_unknown, and ignore_solver1 parameters of the combined solver to change its behaviour.
The function Z3_solver_get_model retrieves a model if the assertions is satisfiable (i.e., the result is Z3_L_TRUE) and model construction is enabled. The function Z3_solver_get_model can also be used even if the result is Z3_L_UNDEF, but the returned model is not guaranteed to satisfy quantified assertions.
Remarks
User must use Z3_solver_inc_ref and Z3_solver_dec_ref to manage solver objects. Even if the context was created using Z3_mk_context instead of Z3_mk_context_rc.
See also
Z3_mk_simple_solver
Z3_mk_solver_for_logic
Z3_mk_solver_from_tactic
Referenced by solver::solver().
Z3_mk_solver_for_logic()
Z3_solver Z3_API Z3_mk_solver_for_logic (Z3_context c, Z3_symbol logic)
Create a new solver customized for the given logic. It behaves like Z3_mk_solver if the logic is unknown or unsupported.
Remarks
User must use Z3_solver_inc_ref and Z3_solver_dec_ref to manage solver objects. Even if the context was created using Z3_mk_context instead of Z3_mk_context_rc.
See also
Z3_mk_solver
Z3_mk_simple_solver
Z3_mk_solver_from_tactic
Referenced by solver::solver().
Z3_mk_solver_from_tactic()
Z3_solver Z3_API Z3_mk_solver_from_tactic (Z3_context c, Z3_tactic t)
Create a new solver that is implemented using the given tactic. The solver supports the commands Z3_solver_push and Z3_solver_pop, but it will always solve each Z3_solver_check from scratch.
Remarks
User must use Z3_solver_inc_ref and Z3_solver_dec_ref to manage solver objects. Even if the context was created using Z3_mk_context instead of Z3_mk_context_rc.
See also
Z3_mk_solver
Z3_mk_simple_solver
Z3_mk_solver_for_logic
Referenced by tactic::mk_solver().
Z3_mk_store()
Z3_ast Z3_API Z3_mk_store (Z3_context c, Z3_ast a, Z3_ast i, Z3_ast v)
Array update.
The node a must have an array sort [domain -> range], i must have sort domain, v must have sort range. The sort of the result is [domain -> range]. The semantics of this function is given by the theory of arrays described in the SMT-LIB standard. See http://smtlib.org for more details. The result of this function is an array that is equal to a (with respect to select) on all indices except for i, where it maps to v (and the select of a with respect to i may be a different value).
See also
Z3_mk_array_sort
Z3_mk_select
Referenced by z3::store(), and z3py::Update().
Z3_mk_store_n()
Z3_ast Z3_API Z3_mk_store_n (Z3_context c, Z3_ast a, unsigned n, Z3_ast const * idxs, Z3_ast v)
n-ary Array update.
Referenced by z3::store(), and z3py::Update().
Z3_mk_str_le()
Z3_ast Z3_API Z3_mk_str_le (Z3_context c, Z3_ast prefix, Z3_ast s)
Check if s1 is equal or lexicographically strictly less than s2.
Precondition
s1 and s2 are strings
Z3_mk_str_lt()
Z3_ast Z3_API Z3_mk_str_lt (Z3_context c, Z3_ast prefix, Z3_ast s)
Check if s1 is lexicographically strictly less than s2.
Precondition
s1 and s2 are strings
Z3_mk_str_to_int()
Z3_ast Z3_API Z3_mk_str_to_int (Z3_context c, Z3_ast s)
Convert string to integer.
Referenced by expr::stoi().
Z3_mk_string()
Z3_ast Z3_API Z3_mk_string (Z3_context c, Z3_string s)
Create a string constant out of the string that is passed in The string may contain escape encoding for non-printable characters or characters outside of the basic printable ASCII range. For example, the escape encoding \u{0} represents the character 0 and the encoding \u{100} represents the character 256.
Referenced by context::string_val(), and context::string_val().
Z3_mk_string_from_code()
Z3_ast Z3_API Z3_mk_string_from_code (Z3_context c, Z3_ast a)
Code to string conversion.
Z3_mk_string_sort()
Z3_sort Z3_API Z3_mk_string_sort (Z3_context c)
Create a sort for unicode strings.
The sort for characters can be changed to ASCII by setting the global parameter encoding to ascii, or alternative to 16 bit characters by setting encoding to bmp.
Referenced by context::string_sort().
Z3_mk_string_symbol()
Z3_symbol Z3_API Z3_mk_string_symbol (Z3_context c, Z3_string s)
Create a Z3 symbol using a C string.
Symbols are used to name several term and type constructors.
See also
Z3_get_symbol_string
Z3_mk_int_symbol
Referenced by context::enumeration_sort(), context::str_symbol(), z3py::to_symbol(), context::tuple_sort(), and context::uninterpreted_sort().
Z3_mk_string_to_code()
Z3_ast Z3_API Z3_mk_string_to_code (Z3_context c, Z3_ast a)
String to code conversion.
Z3_mk_sub()
Z3_ast Z3_API Z3_mk_sub (Z3_context c, unsigned num_args, Z3_ast const args[])
Create an AST node representing args[0] - ... - args[num_args - 1].
The array args must have num_args elements. All arguments must have int or real sort.
Remarks
The number of arguments must be greater than zero.
Z3_mk_tactic()
Z3_tactic Z3_API Z3_mk_tactic (Z3_context c, Z3_string name)
Return a tactic associated with the given name. The complete list of tactics may be obtained using the procedures Z3_get_num_tactics and Z3_get_tactic_name. It may also be obtained using the command (help-tactic) in the SMT 2.0 front-end.
Tactics are the basic building block for creating custom solvers for specific problem domains.
Referenced by tactic::tactic().
Z3_mk_transitive_closure()
Z3_func_decl Z3_API Z3_mk_transitive_closure (Z3_context c, Z3_func_decl f)
create transitive closure of binary relation.
Precondition
f is a binary relation, such that the two arguments have the same sorts.
The resulting relation f+ represents the transitive closure of f.
Referenced by func_decl::transitive_closure().
Z3_mk_tree_order()
Z3_func_decl Z3_API Z3_mk_tree_order (Z3_context c, Z3_sort a, unsigned id)
create a tree ordering relation over signature a identified using index id.
Referenced by z3::tree_order().
Z3_mk_true()
Z3_ast Z3_API Z3_mk_true (Z3_context c)
Create an AST node representing true.
Referenced by context::bool_val(), and z3py::BoolVal().
Z3_mk_tuple_sort()
Z3_sort Z3_API Z3_mk_tuple_sort (Z3_context c, Z3_symbol mk_tuple_name, unsigned num_fields, Z3_symbol const field_names[], Z3_sort const field_sorts[], Z3_func_decl * mk_tuple_decl, Z3_func_decl proj_decl[])
Create a tuple type.
A tuple with n fields has a constructor and n projections. This function will also declare the constructor and projection functions.
Parameters
c logical context
mk_tuple_name name of the constructor function associated with the tuple type.
num_fields number of fields in the tuple type.
field_names name of the projection functions.
field_sorts type of the tuple fields.
mk_tuple_decl output parameter that will contain the constructor declaration.
proj_decl output parameter that will contain the projection function declarations. This field must be a buffer of size num_fields allocated by the user.
Referenced by context::tuple_sort().
Z3_mk_type_variable()
Z3_sort Z3_API Z3_mk_type_variable (Z3_context c, Z3_symbol s)
Create a type variable.
Functions using type variables can be applied to instantiations that match the signature of the function. Assertions using type variables correspond to assertions over all possible instantiations.
Referenced by z3py::DeclareTypeVar().
Z3_mk_u32string()
Z3_ast Z3_API Z3_mk_u32string (Z3_context c, unsigned len, unsigned const chars[])
Create a string constant out of the string that is passed in It takes the length of the string as well to take into account 0 characters. The string is unescaped.
Referenced by context::string_val().
Z3_mk_ubv_to_str()
Z3_ast Z3_API Z3_mk_ubv_to_str (Z3_context c, Z3_ast s)
Unsigned bit-vector to string conversion.
Referenced by expr::ubvtos().
Z3_mk_unary_minus()
Z3_ast Z3_API Z3_mk_unary_minus (Z3_context c, Z3_ast arg)
Create an AST node representing - arg.
The arguments must have int or real type.
Referenced by ArithRef::__neg__().
Z3_mk_uninterpreted_sort()
Z3_sort Z3_API Z3_mk_uninterpreted_sort (Z3_context c, Z3_symbol s)
Create a free (uninterpreted) type using the given name (symbol).
Two free types are considered the same iff the have the same name.
Referenced by z3py::DeclareSort(), context::uninterpreted_sort(), and context::uninterpreted_sort().
Z3_mk_unsigned_int()
Z3_ast Z3_API Z3_mk_unsigned_int (Z3_context c, unsigned v, Z3_sort ty)
Create a numeral of a int, bit-vector, or finite-domain sort.
This function can be used to create numerals that fit in a machine unsigned integer. It is slightly faster than Z3_mk_numeral since it is not necessary to parse a string.
See also
Z3_mk_numeral
Referenced by context::bv_val(), context::int_val(), and context::real_val().
Z3_mk_unsigned_int64()
Z3_ast Z3_API Z3_mk_unsigned_int64 (Z3_context c, uint64_t v, Z3_sort ty)
Create a numeral of a int, bit-vector, or finite-domain sort.
This function can be used to create numerals that fit in a machine uint64_t integer. It is slightly faster than Z3_mk_numeral since it is not necessary to parse a string.
See also
Z3_mk_numeral
Referenced by context::bv_val(), context::int_val(), and context::real_val().
Z3_mk_xor()
Z3_ast Z3_API Z3_mk_xor (Z3_context c, Z3_ast t1, Z3_ast t2)
Create an AST node representing t1 xor t2.
The nodes t1 and t2 must have Boolean sort.
Referenced by z3py::Xor().
Z3_mk_zero_ext()
Z3_ast Z3_API Z3_mk_zero_ext (Z3_context c, unsigned i, Z3_ast t1)
Extend the given bit-vector with zeros to the (unsigned) equivalent bit-vector of size m+i, where m is the size of the given bit-vector.
The node t1 must have a bit-vector sort.
Referenced by z3py::ZeroExt(), and z3::zext().
Z3_model_dec_ref()
void Z3_API Z3_model_dec_ref (Z3_context c, Z3_model m)
Decrement the reference counter of the given model.
Referenced by ModelRef::__del__(), model::operator=(), and model::~model().
Z3_model_eval()
bool Z3_API Z3_model_eval (Z3_context c, Z3_model m, Z3_ast t, bool model_completion, Z3_ast * v)
Evaluate the AST node t in the given model. Return true if succeeded, and store the result in v.
If model_completion is true, then Z3 will assign an interpretation for any constant or function that does not have an interpretation in m. These constants and functions were essentially don't cares.
If model_completion is false, then Z3 will not assign interpretations to constants for functions that do not have interpretations in m. Evaluation behaves as the identify function in this case.
The evaluation may fail for the following reasons:
t contains a quantifier.
the model m is partial, that is, it doesn't have a complete interpretation for uninterpreted functions. That is, the option MODEL_PARTIAL=true was used.
t is type incorrect.
Z3_interrupt was invoked during evaluation.
Referenced by model::eval(), and ModelRef::eval().
Z3_model_get_const_decl()
Z3_func_decl Z3_API Z3_model_get_const_decl (Z3_context c, Z3_model m, unsigned i)
Return the i-th constant in the given model.
Precondition
i < Z3_model_get_num_consts(c, m)
See also
Z3_model_eval
Z3_model_get_num_consts
Referenced by ModelRef::__getitem__(), ModelRef::decls(), and model::get_const_decl().
Z3_model_get_const_interp()
Z3_ast Z3_API Z3_model_get_const_interp (Z3_context c, Z3_model m, Z3_func_decl a)
Return the interpretation (i.e., assignment) of constant a in the model m. Return NULL, if the model does not assign an interpretation for a. That should be interpreted as: the value of a does not matter.
Precondition
Z3_get_arity(c, a) == 0
Referenced by model::get_const_interp(), and ModelRef::get_interp().
Z3_model_get_func_decl()
Z3_func_decl Z3_API Z3_model_get_func_decl (Z3_context c, Z3_model m, unsigned i)
Return the declaration of the i-th function in the given model.
Precondition
i < Z3_model_get_num_funcs(c, m)
See also
Z3_model_get_num_funcs
Referenced by ModelRef::__getitem__(), ModelRef::decls(), and model::get_func_decl().
Z3_model_get_func_interp()
Z3_func_interp Z3_API Z3_model_get_func_interp (Z3_context c, Z3_model m, Z3_func_decl f)
Return the interpretation of the function f in the model m. Return NULL, if the model does not assign an interpretation for f. That should be interpreted as: the f does not matter.
Precondition
Z3_get_arity(c, f) > 0
Remarks
Reference counting must be used to manage Z3_func_interp objects, even when the Z3_context was created using Z3_mk_context instead of Z3_mk_context_rc.
Referenced by model::get_func_interp(), and ModelRef::get_interp().
Z3_model_get_num_consts()
unsigned Z3_API Z3_model_get_num_consts (Z3_context c, Z3_model m)
Return the number of constants assigned by the given model.
See also
Z3_model_get_const_decl
Referenced by ModelRef::__getitem__(), ModelRef::__len__(), ModelRef::decls(), and model::num_consts().
Z3_model_get_num_funcs()
unsigned Z3_API Z3_model_get_num_funcs (Z3_context c, Z3_model m)
Return the number of function interpretations in the given model.
A function interpretation is represented as a finite map and an 'else' value. Each entry in the finite map represents the value of a function given a set of arguments.
See also
Z3_model_get_func_decl
Referenced by ModelRef::__len__(), ModelRef::decls(), and model::num_funcs().
Z3_model_get_num_sorts()
unsigned Z3_API Z3_model_get_num_sorts (Z3_context c, Z3_model m)
Return the number of uninterpreted sorts that m assigns an interpretation to.
Z3 also provides an interpretation for uninterpreted sorts used in a formula. The interpretation for a sort s is a finite set of distinct values. We say this finite set is the "universe" of s.
See also
Z3_model_get_sort
Z3_model_get_sort_universe
Referenced by ModelRef::num_sorts().
Z3_model_get_sort()
Z3_sort Z3_API Z3_model_get_sort (Z3_context c, Z3_model m, unsigned i)
Return a uninterpreted sort that m assigns an interpretation.
Precondition
i < Z3_model_get_num_sorts(c, m)
See also
Z3_model_get_num_sorts
Z3_model_get_sort_universe
Referenced by ModelRef::get_sort().
Z3_model_get_sort_universe()
Z3_ast_vector Z3_API Z3_model_get_sort_universe (Z3_context c, Z3_model m, Z3_sort s)
Return the finite set of distinct values that represent the interpretation for sort s.
See also
Z3_model_get_num_sorts
Z3_model_get_sort
Referenced by ModelRef::get_universe().
Z3_model_has_interp()
bool Z3_API Z3_model_has_interp (Z3_context c, Z3_model m, Z3_func_decl a)
Test if there exists an interpretation (i.e., assignment) for a in the model m.
Referenced by model::has_interp().
Z3_model_inc_ref()
void Z3_API Z3_model_inc_ref (Z3_context c, Z3_model m)
Increment the reference counter of the given model.
Referenced by model::operator=().
Z3_model_to_string()
Z3_string Z3_API Z3_model_to_string (Z3_context c, Z3_model m)
Convert the given model into a string.
Warning
The result buffer is statically allocated by Z3. It will be automatically deallocated when Z3_del_context is invoked. So, the buffer is invalidated in the next call to Z3_model_to_string.
Referenced by ModelRef::sexpr(), and model::to_string().
Z3_model_translate()
Z3_model Z3_API Z3_model_translate (Z3_context c, Z3_model m, Z3_context dst)
translate model from context c to context dst.
Remarks
Use this method for cloning state between contexts. Note that operations on contexts are not thread safe and therefore all operations that related to a given context have to be synchronized (or run in the same thread).
Referenced by model::model(), and ModelRef::translate().
Z3_open_log()
bool Z3_API Z3_open_log (Z3_string filename)
Log interaction to a file.
See also
Z3_append_log
Z3_close_log
Referenced by z3py::open_log().
Z3_optimize_assert()
void Z3_API Z3_optimize_assert (Z3_context c, Z3_optimize o, Z3_ast a)
Assert hard constraint to the optimization context.
See also
Z3_optimize_assert_soft
Z3_optimize_assert_and_track
Referenced by optimize::add().
Z3_optimize_assert_and_track()
void Z3_API Z3_optimize_assert_and_track (Z3_context c, Z3_optimize o, Z3_ast a, Z3_ast t)
Assert tracked hard constraint to the optimization context.
See also
Z3_optimize_assert
Z3_optimize_assert_soft
Referenced by optimize::add().
Z3_optimize_assert_soft()
unsigned Z3_API Z3_optimize_assert_soft (Z3_context c, Z3_optimize o, Z3_ast a, Z3_string weight, Z3_symbol id)
Assert soft constraint to the optimization context.
Parameters
c - context
o - optimization context
a - formula
weight - a penalty for violating soft constraint. Negative weights convert into rewards.
id - optional identifier to group soft constraints
See also
Z3_optimize_assert
Z3_optimize_assert_and_track
Referenced by optimize::add_soft(), and optimize::add_soft().
Z3_optimize_check()
Z3_lbool Z3_API Z3_optimize_check (Z3_context c, Z3_optimize o, unsigned num_assumptions, Z3_ast const assumptions[])
Check consistency and produce optimal values.
Parameters
c - context
o - optimization context
num_assumptions - number of additional assumptions
assumptions - the additional assumptions
See also
Z3_optimize_get_reason_unknown
Z3_optimize_get_model
Z3_optimize_get_statistics
Z3_optimize_get_unsat_core
Referenced by optimize::check(), and optimize::check().
Z3_optimize_dec_ref()
void Z3_API Z3_optimize_dec_ref (Z3_context c, Z3_optimize d)
Decrement the reference counter of the given optimize context.
Referenced by optimize::operator=(), and optimize::~optimize().
Z3_optimize_from_file()
void Z3_API Z3_optimize_from_file (Z3_context c, Z3_optimize o, Z3_string s)
Parse an SMT-LIB2 file with assertions, soft constraints and optimization objectives. Add the parsed constraints and objectives to the optimization context.
Parameters
c - context.
o - optimize context.
s - path to file containing SMT2 specification.
See also
Z3_optimize_from_string
Z3_optimize_to_string
Referenced by optimize::from_file().
Z3_optimize_from_string()
void Z3_API Z3_optimize_from_string (Z3_context c, Z3_optimize o, Z3_string s)
Parse an SMT-LIB2 string with assertions, soft constraints and optimization objectives. Add the parsed constraints and objectives to the optimization context.
Parameters
c - context.
o - optimize context.
s - string containing SMT2 specification.
See also
Z3_optimize_from_file
Z3_optimize_to_string
Referenced by optimize::from_string().
Z3_optimize_get_assertions()
Z3_ast_vector Z3_API Z3_optimize_get_assertions (Z3_context c, Z3_optimize o)
Return the set of asserted formulas on the optimization context.
Referenced by optimize::assertions().
Z3_optimize_get_help()
Z3_string Z3_API Z3_optimize_get_help (Z3_context c, Z3_optimize t)
Return a string containing a description of parameters accepted by optimize.
See also
Z3_optimize_get_param_descrs
Z3_optimize_set_params
Referenced by optimize::help().
Z3_optimize_get_lower()
Z3_ast Z3_API Z3_optimize_get_lower (Z3_context c, Z3_optimize o, unsigned idx)
Retrieve lower bound value or approximation for the i'th optimization objective.
Parameters
c - context
o - optimization context
idx - index of optimization objective
See also
Z3_optimize_get_upper
Z3_optimize_get_lower_as_vector
Z3_optimize_get_upper_as_vector
Referenced by optimize::lower().
Z3_optimize_get_lower_as_vector()
Z3_ast_vector Z3_API Z3_optimize_get_lower_as_vector (Z3_context c, Z3_optimize o, unsigned idx)
Retrieve lower bound value or approximation for the i'th optimization objective. The returned vector is of length 3. It always contains numerals. The three numerals are coefficients a, b, c and encode the result of Z3_optimize_get_lower a * infinity + b + c * epsilon.
Parameters
c - context
o - optimization context
idx - index of optimization objective
See also
Z3_optimize_get_lower
Z3_optimize_get_upper
Z3_optimize_get_upper_as_vector
Z3_optimize_get_model()
Z3_model Z3_API Z3_optimize_get_model (Z3_context c, Z3_optimize o)
Retrieve the model for the last Z3_optimize_check.
The error handler is invoked if a model is not available because the commands above were not invoked for the given optimization solver, or if the result was Z3_L_FALSE.
Referenced by optimize::get_model().
Z3_optimize_get_objectives()
Z3_ast_vector Z3_API Z3_optimize_get_objectives (Z3_context c, Z3_optimize o)
Return objectives on the optimization context. If the objective function is a max-sat objective it is returned as a Pseudo-Boolean (minimization) sum of the form (+ (if f1 w1 0) (if f2 w2 0) ...) If the objective function is entered as a maximization objective, then return the corresponding minimization objective. In this way the resulting objective function is always returned as a minimization objective.
Referenced by optimize::objectives().
Z3_optimize_get_param_descrs()
Z3_param_descrs Z3_API Z3_optimize_get_param_descrs (Z3_context c, Z3_optimize o)
Return the parameter description set for the given optimize object.
Parameters
c - context
o - optimization context
See also
Z3_optimize_get_help
Z3_optimize_set_params
Z3_optimize_get_reason_unknown()
Z3_string Z3_API Z3_optimize_get_reason_unknown (Z3_context c, Z3_optimize d)
Retrieve a string that describes the last status returned by Z3_optimize_check.
Use this method when Z3_optimize_check returns Z3_L_UNDEF.
Z3_optimize_get_statistics()
Z3_stats Z3_API Z3_optimize_get_statistics (Z3_context c, Z3_optimize d)
Retrieve statistics information from the last call to Z3_optimize_check.
Referenced by optimize::statistics().
Z3_optimize_get_unsat_core()
Z3_ast_vector Z3_API Z3_optimize_get_unsat_core (Z3_context c, Z3_optimize o)
Retrieve the unsat core for the last Z3_optimize_check The unsat core is a subset of the assumptions a.
Referenced by optimize::unsat_core().
Z3_optimize_get_upper()
Z3_ast Z3_API Z3_optimize_get_upper (Z3_context c, Z3_optimize o, unsigned idx)
Retrieve upper bound value or approximation for the i'th optimization objective.
Parameters
c - context
o - optimization context
idx - index of optimization objective
See also
Z3_optimize_get_lower
Z3_optimize_get_lower_as_vector
Z3_optimize_get_upper_as_vector
Referenced by optimize::upper().
Z3_optimize_get_upper_as_vector()
Z3_ast_vector Z3_API Z3_optimize_get_upper_as_vector (Z3_context c, Z3_optimize o, unsigned idx)
Retrieve upper bound value or approximation for the i'th optimization objective.
Parameters
c - context
o - optimization context
idx - index of optimization objective
See also
Z3_optimize_get_lower
Z3_optimize_get_upper
Z3_optimize_get_lower_as_vector
Z3_optimize_inc_ref()
void Z3_API Z3_optimize_inc_ref (Z3_context c, Z3_optimize d)
Increment the reference counter of the given optimize context.
Referenced by optimize::operator=(), optimize::optimize(), optimize::optimize(), optimize::optimize(), and optimize::optimize().
Z3_optimize_maximize()
unsigned Z3_API Z3_optimize_maximize (Z3_context c, Z3_optimize o, Z3_ast t)
Add a maximization constraint.
Parameters
c - context
o - optimization context
t - arithmetical term
See also
Z3_optimize_minimize
Referenced by optimize::maximize().
Z3_optimize_minimize()
unsigned Z3_API Z3_optimize_minimize (Z3_context c, Z3_optimize o, Z3_ast t)
Add a minimization constraint.
Parameters
c - context
o - optimization context
t - arithmetical term
See also
Z3_optimize_maximize
Referenced by optimize::minimize().
Z3_optimize_pop()
void Z3_API Z3_optimize_pop (Z3_context c, Z3_optimize d)
Backtrack one level.
See also
Z3_optimize_push
Precondition
The number of calls to pop cannot exceed calls to push.
Referenced by optimize::pop().
Z3_optimize_push()
void Z3_API Z3_optimize_push (Z3_context c, Z3_optimize d)
Create a backtracking point.
The optimize solver contains a set of rules, added facts and assertions. The set of rules, facts and assertions are restored upon calling Z3_optimize_pop.
See also
Z3_optimize_pop
Referenced by optimize::push().
Z3_optimize_register_model_eh()
void Z3_API Z3_optimize_register_model_eh (Z3_context c, Z3_optimize o, Z3_model m, void * ctx, Z3_model_eh model_eh)
register a model event handler for new models.
Z3_optimize_set_initial_value()
void Z3_API Z3_optimize_set_initial_value (Z3_context c, Z3_optimize o, Z3_ast v, Z3_ast val)
provide an initialization hint to the solver. The initialization hint is used to calibrate an initial value of the expression that represents a variable. If the variable is Boolean, the initial phase is set according to value. If the variable is an integer or real, the initial Simplex tableau is recalibrated to attempt to follow the value assignment.
Referenced by optimize::set_initial_value().
Z3_optimize_set_params()
void Z3_API Z3_optimize_set_params (Z3_context c, Z3_optimize o, Z3_params p)
Set parameters on optimization context.
Parameters
c - context
o - optimization context
p - parameters
See also
Z3_optimize_get_help
Z3_optimize_get_param_descrs
Referenced by optimize::set().
Z3_optimize_to_string()
Z3_string Z3_API Z3_optimize_to_string (Z3_context c, Z3_optimize o)
Print the current context as a string.
Parameters
c - context.
o - optimization context.
See also
Z3_optimize_from_file
Z3_optimize_from_string
Z3_optimize_translate()
Z3_optimize Z3_API Z3_optimize_translate (Z3_context c, Z3_optimize o, Z3_context target)
Copy an optimization context from a source to a target context.
This function allows translating an optimization context from one Z3_context to another. This is useful when working with multiple contexts and needing to transfer optimization problems between them.
Parameters
c Source context containing the optimization context to translate
o The optimization context to translate from the source context
target Target context where the optimization context will be created
Returns
A new optimization context in the target context with the same state
Referenced by optimize::optimize().
Z3_param_descrs_dec_ref()
void Z3_API Z3_param_descrs_dec_ref (Z3_context c, Z3_param_descrs p)
Decrement the reference counter of the given parameter description set.
Referenced by ParamDescrsRef::__del__(), param_descrs::operator=(), and param_descrs::~param_descrs().
Z3_param_descrs_get_documentation()
Z3_string Z3_API Z3_param_descrs_get_documentation (Z3_context c, Z3_param_descrs p, Z3_symbol s)
Retrieve documentation string corresponding to parameter name s.
Referenced by param_descrs::documentation(), and ParamDescrsRef::get_documentation().
Z3_param_descrs_get_kind()
Z3_param_kind Z3_API Z3_param_descrs_get_kind (Z3_context c, Z3_param_descrs p, Z3_symbol n)
Return the kind associated with the given parameter name n.
Referenced by ParamDescrsRef::get_kind(), and param_descrs::kind().
Z3_param_descrs_get_name()
Z3_symbol Z3_API Z3_param_descrs_get_name (Z3_context c, Z3_param_descrs p, unsigned i)
Return the name of the parameter at given index i.
Precondition
i < Z3_param_descrs_size(c, p)
Referenced by ParamDescrsRef::get_name(), and param_descrs::name().
Z3_param_descrs_inc_ref()
void Z3_API Z3_param_descrs_inc_ref (Z3_context c, Z3_param_descrs p)
Increment the reference counter of the given parameter description set.
Referenced by param_descrs::operator=(), param_descrs::param_descrs(), and param_descrs::param_descrs().
Z3_param_descrs_size()
unsigned Z3_API Z3_param_descrs_size (Z3_context c, Z3_param_descrs p)
Return the number of parameters in the given parameter description set.
Referenced by param_descrs::size(), and ParamDescrsRef::size().
Z3_param_descrs_to_string()
Z3_string Z3_API Z3_param_descrs_to_string (Z3_context c, Z3_param_descrs p)
Convert a parameter description set into a string. This function is mainly used for printing the contents of a parameter description set.
Referenced by ParamDescrsRef::__repr__(), and param_descrs::to_string().
Z3_params_dec_ref()
void Z3_API Z3_params_dec_ref (Z3_context c, Z3_params p)
Decrement the reference counter of the given parameter set.
Referenced by ParamsRef::__del__(), params::operator=(), and params::~params().
Z3_params_inc_ref()
void Z3_API Z3_params_inc_ref (Z3_context c, Z3_params p)
Increment the reference counter of the given parameter set.
Referenced by params::operator=(), params::params(), and params::params().
Z3_params_set_bool()
void Z3_API Z3_params_set_bool (Z3_context c, Z3_params p, Z3_symbol k, bool v)
Add a Boolean parameter k with value v to the parameter set p.
Referenced by params::set(), and ParamsRef::set().
Z3_params_set_double()
void Z3_API Z3_params_set_double (Z3_context c, Z3_params p, Z3_symbol k, double v)
Add a double parameter k with value v to the parameter set p.
Referenced by params::set(), and ParamsRef::set().
Z3_params_set_symbol()
void Z3_API Z3_params_set_symbol (Z3_context c, Z3_params p, Z3_symbol k, Z3_symbol v)
Add a symbol parameter k with value v to the parameter set p.
Referenced by params::set(), params::set(), and ParamsRef::set().
Z3_params_set_uint()
void Z3_API Z3_params_set_uint (Z3_context c, Z3_params p, Z3_symbol k, unsigned v)
Add a unsigned parameter k with value v to the parameter set p.
Referenced by params::set(), and ParamsRef::set().
Z3_params_to_string()
Z3_string Z3_API Z3_params_to_string (Z3_context c, Z3_params p)
Convert a parameter set into a string. This function is mainly used for printing the contents of a parameter set.
Referenced by ParamsRef::__repr__().
Z3_params_validate()
void Z3_API Z3_params_validate (Z3_context c, Z3_params p, Z3_param_descrs d)
Validate the parameter set p against the parameter description set d.
The procedure invokes the error handler if p is invalid.
Referenced by ParamsRef::validate().
Z3_parse_smtlib2_file()
Z3_ast_vector Z3_API Z3_parse_smtlib2_file (Z3_context c, Z3_string file_name, unsigned num_sorts, Z3_symbol const sort_names[], Z3_sort const sorts[], unsigned num_decls, Z3_symbol const decl_names[], Z3_func_decl const decls[])
Similar to Z3_parse_smtlib2_string, but reads the benchmark from a file.
Referenced by context::parse_file(), and context::parse_file().
Z3_parse_smtlib2_string()
Z3_ast_vector Z3_API Z3_parse_smtlib2_string (Z3_context c, Z3_string str, unsigned num_sorts, Z3_symbol const sort_names[], Z3_sort const sorts[], unsigned num_decls, Z3_symbol const decl_names[], Z3_func_decl const decls[])
Parse the given string using the SMT-LIB2 parser.
It returns a formula comprising of the conjunction of assertions in the scope (up to push/pop) at the end of the string.
Referenced by context::parse_string(), and context::parse_string().
Z3_parser_context_add_decl()
void Z3_API Z3_parser_context_add_decl (Z3_context c, Z3_parser_context pc, Z3_func_decl f)
Add a function declaration.
Z3_parser_context_add_sort()
void Z3_API Z3_parser_context_add_sort (Z3_context c, Z3_parser_context pc, Z3_sort s)
Add a sort declaration.
Z3_parser_context_dec_ref()
void Z3_API Z3_parser_context_dec_ref (Z3_context c, Z3_parser_context pc)
Decrement the reference counter of the given Z3_parser_context object.
Z3_parser_context_from_string()
Z3_ast_vector Z3_API Z3_parser_context_from_string (Z3_context c, Z3_parser_context pc, Z3_string s)
Parse a string of SMTLIB2 commands. Return assertions.
Z3_parser_context_inc_ref()
void Z3_API Z3_parser_context_inc_ref (Z3_context c, Z3_parser_context pc)
Increment the reference counter of the given Z3_parser_context object.
Z3_pattern_to_ast()
Z3_ast Z3_API Z3_pattern_to_ast (Z3_context c, Z3_pattern p)
Convert a Z3_pattern into Z3_ast. This is just type casting.
Z3_pattern_to_string()
Z3_string Z3_API Z3_pattern_to_string (Z3_context c, Z3_pattern p)
Z3_polynomial_subresultants()
Z3_ast_vector Z3_API Z3_polynomial_subresultants (Z3_context c, Z3_ast p, Z3_ast q, Z3_ast x)
Return the nonzero subresultants of p and q with respect to the "variable" x.
Precondition
p, q and x are Z3 expressions where p and q are arithmetic terms. Note that, any subterm that cannot be viewed as a polynomial is assumed to be a variable. Example: f(a) is a considered to be a variable in the polynomial f(a)*f(a) + 2*f(a) + 1
Z3_probe_and()
Z3_probe Z3_API Z3_probe_and (Z3_context x, Z3_probe p1, Z3_probe p2)
Return a probe that evaluates to "true" when p1 and p2 evaluates to true.
Remarks
For probes, "true" is any value different from 0.0.
Z3_probe_apply()
double Z3_API Z3_probe_apply (Z3_context c, Z3_probe p, Z3_goal g)
Execute the probe over the goal. The probe always produce a double value. "Boolean" probes return 0.0 for false, and a value different from 0.0 for true.
Referenced by probe::apply().
Z3_probe_const()
Z3_probe Z3_API Z3_probe_const (Z3_context x, double val)
Return a probe that always evaluates to val.
Referenced by probe::probe().
Z3_probe_dec_ref()
void Z3_API Z3_probe_dec_ref (Z3_context c, Z3_probe p)
Decrement the reference counter of the given probe.
Referenced by probe::operator=(), and probe::~probe().
Z3_probe_eq()
Z3_probe Z3_API Z3_probe_eq (Z3_context x, Z3_probe p1, Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is equal to the value returned by p2.
Remarks
For probes, "true" is any value different from 0.0.
Z3_probe_ge()
Z3_probe Z3_API Z3_probe_ge (Z3_context x, Z3_probe p1, Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is greater than or equal to the value returned by p2.
Remarks
For probes, "true" is any value different from 0.0.
Z3_probe_get_descr()
Z3_string Z3_API Z3_probe_get_descr (Z3_context c, Z3_string name)
Return a string containing a description of the probe with the given name.
Z3_probe_gt()
Z3_probe Z3_API Z3_probe_gt (Z3_context x, Z3_probe p1, Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is greater than the value returned by p2.
Remarks
For probes, "true" is any value different from 0.0.
Z3_probe_inc_ref()
void Z3_API Z3_probe_inc_ref (Z3_context c, Z3_probe p)
Increment the reference counter of the given probe.
Referenced by probe::operator=().
Z3_probe_le()
Z3_probe Z3_API Z3_probe_le (Z3_context x, Z3_probe p1, Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is less than or equal to the value returned by p2.
Remarks
For probes, "true" is any value different from 0.0.
Z3_probe_lt()
Z3_probe Z3_API Z3_probe_lt (Z3_context x, Z3_probe p1, Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is less than the value returned by p2.
Remarks
For probes, "true" is any value different from 0.0.
Z3_probe_not()
Z3_probe Z3_API Z3_probe_not (Z3_context x, Z3_probe p)
Return a probe that evaluates to "true" when p does not evaluate to true.
Remarks
For probes, "true" is any value different from 0.0.
Referenced by z3py::Not().
Z3_probe_or()
Z3_probe Z3_API Z3_probe_or (Z3_context x, Z3_probe p1, Z3_probe p2)
Return a probe that evaluates to "true" when p1 or p2 evaluates to true.
Remarks
For probes, "true" is any value different from 0.0.
Z3_query_constructor()
void Z3_API Z3_query_constructor (Z3_context c, Z3_constructor constr, unsigned num_fields, Z3_func_decl * constructor, Z3_func_decl * tester, Z3_func_decl accessors[])
Query constructor for declared functions.
Parameters
c logical context.
constr constructor container. The container must have been passed into a Z3_mk_datatype call.
num_fields number of accessor fields in the constructor.
constructor constructor function declaration, allocated by user.
tester constructor test function declaration, allocated by user.
accessors array of accessor function declarations allocated by user. The array must contain num_fields elements.
See also
Z3_mk_constructor
Referenced by constructors::query().
Z3_rcf_add()
Z3_rcf_num Z3_API Z3_rcf_add (Z3_context c, Z3_rcf_num a, Z3_rcf_num b)
Return the value a + b.
Z3_rcf_coefficient()
Z3_rcf_num Z3_API Z3_rcf_coefficient (Z3_context c, Z3_rcf_num a, unsigned i)
Extract a coefficient from an algebraic number.
Precondition
Z3_rcf_is_algebraic(ctx, a);
Z3_rcf_del()
void Z3_API Z3_rcf_del (Z3_context c, Z3_rcf_num a)
Delete a RCF numeral created using the RCF API.
Z3_rcf_div()
Z3_rcf_num Z3_API Z3_rcf_div (Z3_context c, Z3_rcf_num a, Z3_rcf_num b)
Return the value a / b.
Z3_rcf_eq()
bool Z3_API Z3_rcf_eq (Z3_context c, Z3_rcf_num a, Z3_rcf_num b)
Return true if a == b.
Z3_rcf_extension_index()
unsigned Z3_API Z3_rcf_extension_index (Z3_context c, Z3_rcf_num a)
Return the index of a field extension.
Z3_rcf_ge()
bool Z3_API Z3_rcf_ge (Z3_context c, Z3_rcf_num a, Z3_rcf_num b)
Return true if a >= b.
Z3_rcf_get_numerator_denominator()
void Z3_API Z3_rcf_get_numerator_denominator (Z3_context c, Z3_rcf_num a, Z3_rcf_num * n, Z3_rcf_num * d)
Extract the "numerator" and "denominator" of the given RCF numeral. We have that a = n/d, moreover n and d are not represented using rational functions.
Z3_rcf_gt()
bool Z3_API Z3_rcf_gt (Z3_context c, Z3_rcf_num a, Z3_rcf_num b)
Return true if a > b.
Z3_rcf_infinitesimal_name()
Z3_symbol Z3_API Z3_rcf_infinitesimal_name (Z3_context c, Z3_rcf_num a)
Return the name of an infinitesimal.
Precondition
Z3_rcf_is_infinitesimal(ctx, a);
Z3_rcf_interval()
int Z3_API Z3_rcf_interval (Z3_context c, Z3_rcf_num a, bool * lower_is_inf, bool * lower_is_open, Z3_rcf_num * lower, bool * upper_is_inf, bool * upper_is_open, Z3_rcf_num * upper)
Extract an interval from an algebraic number.
Precondition
Z3_rcf_is_algebraic(ctx, a);
Z3_rcf_inv()
Z3_rcf_num Z3_API Z3_rcf_inv (Z3_context c, Z3_rcf_num a)
Return the value 1/a.
Z3_rcf_is_algebraic()
bool Z3_API Z3_rcf_is_algebraic (Z3_context c, Z3_rcf_num a)
Return true if a represents an algebraic number.
Z3_rcf_is_infinitesimal()
bool Z3_API Z3_rcf_is_infinitesimal (Z3_context c, Z3_rcf_num a)
Return true if a represents an infinitesimal.
Z3_rcf_is_rational()
bool Z3_API Z3_rcf_is_rational (Z3_context c, Z3_rcf_num a)
Return true if a represents a rational number.
Z3_rcf_is_transcendental()
bool Z3_API Z3_rcf_is_transcendental (Z3_context c, Z3_rcf_num a)
Return true if a represents a transcendental number.
Z3_rcf_le()
bool Z3_API Z3_rcf_le (Z3_context c, Z3_rcf_num a, Z3_rcf_num b)
Return true if a <= b.
Z3_rcf_lt()
bool Z3_API Z3_rcf_lt (Z3_context c, Z3_rcf_num a, Z3_rcf_num b)
Return true if a < b.
Z3_rcf_mk_e()
Z3_rcf_num Z3_API Z3_rcf_mk_e (Z3_context c)
Return e (Euler's constant)
Z3_rcf_mk_infinitesimal()
Z3_rcf_num Z3_API Z3_rcf_mk_infinitesimal (Z3_context c)
Return a new infinitesimal that is smaller than all elements in the Z3 field.
Z3_rcf_mk_pi()
Z3_rcf_num Z3_API Z3_rcf_mk_pi (Z3_context c)
Return Pi.
Z3_rcf_mk_rational()
Z3_rcf_num Z3_API Z3_rcf_mk_rational (Z3_context c, Z3_string val)
Return a RCF rational using the given string.
Z3_rcf_mk_roots()
unsigned Z3_API Z3_rcf_mk_roots (Z3_context c, unsigned n, Z3_rcf_num const a[], Z3_rcf_num roots[])
Store in roots the roots of the polynomial a[n-1]*x^{n-1} + ... + a[0]. The output vector roots must have size n. It returns the number of roots of the polynomial.
Precondition
The input polynomial is not the zero polynomial.
Z3_rcf_mk_small_int()
Z3_rcf_num Z3_API Z3_rcf_mk_small_int (Z3_context c, int val)
Return a RCF small integer.
Z3_rcf_mul()
Z3_rcf_num Z3_API Z3_rcf_mul (Z3_context c, Z3_rcf_num a, Z3_rcf_num b)
Return the value a * b.
Z3_rcf_neg()
Z3_rcf_num Z3_API Z3_rcf_neg (Z3_context c, Z3_rcf_num a)
Return the value -a.
Z3_rcf_neq()
bool Z3_API Z3_rcf_neq (Z3_context c, Z3_rcf_num a, Z3_rcf_num b)
Return true if a != b.
Z3_rcf_num_coefficients()
unsigned Z3_API Z3_rcf_num_coefficients (Z3_context c, Z3_rcf_num a)
Return the number of coefficients in an algebraic number.
Precondition
Z3_rcf_is_algebraic(ctx, a);
Z3_rcf_num_sign_condition_coefficients()
unsigned Z3_API Z3_rcf_num_sign_condition_coefficients (Z3_context c, Z3_rcf_num a, unsigned i)
Return the number of sign condition polynomial coefficients of an algebraic number.
Precondition
Z3_rcf_is_algebraic(ctx, a);
Z3_rcf_num_sign_conditions()
unsigned Z3_API Z3_rcf_num_sign_conditions (Z3_context c, Z3_rcf_num a)
Return the number of sign conditions of an algebraic number.
Precondition
Z3_rcf_is_algebraic(ctx, a);
Z3_rcf_num_to_decimal_string()
Z3_string Z3_API Z3_rcf_num_to_decimal_string (Z3_context c, Z3_rcf_num a, unsigned prec)
Convert the RCF numeral into a string in decimal notation.
Z3_rcf_num_to_string()
Z3_string Z3_API Z3_rcf_num_to_string (Z3_context c, Z3_rcf_num a, bool compact, bool html)
Convert the RCF numeral into a string.
Z3_rcf_power()
Z3_rcf_num Z3_API Z3_rcf_power (Z3_context c, Z3_rcf_num a, unsigned k)
Return the value a^k.
Z3_rcf_sign_condition_coefficient()
Z3_rcf_num Z3_API Z3_rcf_sign_condition_coefficient (Z3_context c, Z3_rcf_num a, unsigned i, unsigned j)
Extract the j-th polynomial coefficient of the i-th sign condition.
Precondition
Z3_rcf_is_algebraic(ctx, a);
Z3_rcf_sign_condition_sign()
int Z3_API Z3_rcf_sign_condition_sign (Z3_context c, Z3_rcf_num a, unsigned i)
Extract the sign of a sign condition from an algebraic number.
Precondition
Z3_rcf_is_algebraic(ctx, a);
Z3_rcf_sub()
Z3_rcf_num Z3_API Z3_rcf_sub (Z3_context c, Z3_rcf_num a, Z3_rcf_num b)
Return the value a - b.
Z3_rcf_transcendental_name()
Z3_symbol Z3_API Z3_rcf_transcendental_name (Z3_context c, Z3_rcf_num a)
Return the name of a transcendental.
Precondition
Z3_rcf_is_transcendtal(ctx, a);
Z3_reset_memory()
void Z3_API Z3_reset_memory (void)
Reset all allocated resources.
Use this facility on out-of memory errors. It allows discharging the previous state and resuming afresh. Any pointers previously returned by the API become invalid.
Z3_set_ast_print_mode()
void Z3_API Z3_set_ast_print_mode (Z3_context c, Z3_ast_print_mode mode)
Select mode for the format used for pretty-printing AST nodes.
The default mode for pretty printing AST nodes is to produce SMT-LIB style output where common subexpressions are printed at each occurrence. The mode is called Z3_PRINT_SMTLIB_FULL. To print shared common subexpressions only once, use the Z3_PRINT_LOW_LEVEL mode. To print in way that conforms to SMT-LIB standards and uses let expressions to share common sub-expressions use Z3_PRINT_SMTLIB2_COMPLIANT.
See also
Z3_ast_to_string
Z3_pattern_to_string
Z3_func_decl_to_string
Z3_set_error()
void Z3_API Z3_set_error (Z3_context c, Z3_error_code e)
Set an error.
Z3_set_error_handler()
void Z3_API Z3_set_error_handler (Z3_context c, Z3_error_handler h)
Register a Z3 error handler.
A call to a Z3 function may return a non Z3_OK error code, when it is not used correctly. An error handler can be registered and will be called in this case. To disable the use of the error handler, simply register with h=NULL.
Warning
Log files, created using Z3_open_log, may be potentially incomplete/incorrect if error handlers are used.
See also
Z3_get_error_code
Z3_set_param_value()
void Z3_API Z3_set_param_value (Z3_config c, Z3_string param_id, Z3_string param_value)
Set a configuration parameter.
The following parameters can be set for
See also
Z3_mk_config
Referenced by Context::__init__(), config::set(), config::set(), and config::set().
Z3_simplifier_and_then()
Z3_simplifier Z3_API Z3_simplifier_and_then (Z3_context c, Z3_simplifier t1, Z3_simplifier t2)
Return a simplifier that applies t1 to a given goal and t2 to every subgoal produced by t1.
Z3_simplifier_dec_ref()
void Z3_API Z3_simplifier_dec_ref (Z3_context c, Z3_simplifier g)
Decrement the reference counter of the given simplifier.
Referenced by simplifier::operator=(), and simplifier::~simplifier().
Z3_simplifier_get_descr()
Z3_string Z3_API Z3_simplifier_get_descr (Z3_context c, Z3_string name)
Return a string containing a description of the simplifier with the given name.
Z3_simplifier_get_help()
Z3_string Z3_API Z3_simplifier_get_help (Z3_context c, Z3_simplifier t)
Return a string containing a description of parameters accepted by the given simplifier.
Referenced by simplifier::help().
Z3_simplifier_get_param_descrs()
Z3_param_descrs Z3_API Z3_simplifier_get_param_descrs (Z3_context c, Z3_simplifier t)
Return the parameter description set for the given simplifier object.
Referenced by simplifier::get_param_descrs().
Z3_simplifier_inc_ref()
void Z3_API Z3_simplifier_inc_ref (Z3_context c, Z3_simplifier t)
Increment the reference counter of the given simplifier.
Referenced by simplifier::operator=().
Z3_simplifier_using_params()
Z3_simplifier Z3_API Z3_simplifier_using_params (Z3_context c, Z3_simplifier t, Z3_params p)
Return a simplifier that applies t using the given set of parameters.
Z3_simplify()
Z3_ast Z3_API Z3_simplify (Z3_context c, Z3_ast a)
Interface to simplifier.
Provides an interface to the AST simplifier used by Z3. It returns an AST object which is equal to the argument. The returned AST is simplified using algebraic simplification rules, such as constant propagation (propagating true/false over logical connectives).
See also
Z3_simplify_ex
Referenced by expr::simplify().
Z3_simplify_ex()
Z3_ast Z3_API Z3_simplify_ex (Z3_context c, Z3_ast a, Z3_params p)
Interface to simplifier.
Provides an interface to the AST simplifier used by Z3. This procedure is similar to Z3_simplify, but the behavior of the simplifier can be configured using the given parameter set.
See also
Z3_simplify
Z3_simplify_get_help
Z3_simplify_get_param_descrs
Referenced by expr::simplify().
Z3_simplify_get_help()
Z3_string Z3_API Z3_simplify_get_help (Z3_context c)
Return a string describing all available parameters.
See also
Z3_simplify_ex
Z3_simplify_get_param_descrs
Z3_simplify_get_param_descrs()
Z3_param_descrs Z3_API Z3_simplify_get_param_descrs (Z3_context c)
Return the parameter description set for the simplify procedure.
See also
Z3_simplify_ex
Z3_simplify_get_help
Referenced by param_descrs::simplify_param_descrs().
Z3_solver_add_simplifier()
Z3_solver Z3_API Z3_solver_add_simplifier (Z3_context c, Z3_solver solver, Z3_simplifier simplifier)
Attach simplifier to a solver. The solver will use the simplifier for incremental pre-processing.
Referenced by solver::solver().
Z3_solver_assert()
void Z3_API Z3_solver_assert (Z3_context c, Z3_solver s, Z3_ast a)
Assert a constraint into the solver.
The functions Z3_solver_check and Z3_solver_check_assumptions should be used to check whether the logical context is consistent or not.
See also
Z3_solver_assert_and_track
Z3_solver_reset
Referenced by solver::add(), and Solver::assert_exprs().
Z3_solver_assert_and_track()
void Z3_API Z3_solver_assert_and_track (Z3_context c, Z3_solver s, Z3_ast a, Z3_ast p)
Assert a constraint a into the solver, and track it (in the unsat) core using the Boolean constant p.
This API is an alternative to Z3_solver_check_assumptions for extracting unsat cores. Both APIs can be used in the same solver. The unsat core will contain a combination of the Boolean variables provided using Z3_solver_assert_and_track and the Boolean literals provided using Z3_solver_check_assumptions.
Precondition
a must be a Boolean expression
p must be a Boolean constant (aka variable).
See also
Z3_solver_assert
Z3_solver_reset
Referenced by solver::add(), and Solver::assert_and_track().
Z3_solver_check()
Z3_lbool Z3_API Z3_solver_check (Z3_context c, Z3_solver s)
Check whether the assertions in a given solver are consistent or not.
The function Z3_solver_get_model retrieves a model if the assertions is satisfiable (i.e., the result is Z3_L_TRUE) and model construction is enabled. Note that if the call returns Z3_L_UNDEF, Z3 does not ensure that calls to Z3_solver_get_model succeed and any models produced in this case are not guaranteed to satisfy the assertions.
The function Z3_solver_get_proof retrieves a proof if proof generation was enabled when the context was created, and the assertions are unsatisfiable (i.e., the result is Z3_L_FALSE).
See also
Z3_solver_check_assumptions
Referenced by solver::check().
Z3_solver_check_assumptions()
Z3_lbool Z3_API Z3_solver_check_assumptions (Z3_context c, Z3_solver s, unsigned num_assumptions, Z3_ast const assumptions[])
Check whether the assertions in the given solver and optional assumptions are consistent or not.
The function Z3_solver_get_unsat_core retrieves the subset of the assumptions used in the unsatisfiability proof produced by Z3.
See also
Z3_solver_check
Referenced by solver::check(), Solver::check(), and solver::check().
Z3_solver_congruence_explain()
Z3_ast Z3_API Z3_solver_congruence_explain (Z3_context c, Z3_solver s, Z3_ast a, Z3_ast b)
retrieve explanation for congruence.
Precondition
root(a) = root(b)
Z3_solver_congruence_next()
Z3_ast Z3_API Z3_solver_congruence_next (Z3_context c, Z3_solver s, Z3_ast a)
retrieve the next expression in the congruence class. The set of congruent siblings form a cyclic list. Repeated calls on the siblings will result in returning to the original expression.
Z3_solver_congruence_root()
Z3_ast Z3_API Z3_solver_congruence_root (Z3_context c, Z3_solver s, Z3_ast a)
retrieve the congruence closure root of an expression. The root is retrieved relative to the state where the solver was in when it completed. If it completed during a set of case splits, the congruence roots are relative to these case splits. That is, the congruences are not consequences but they are true under the current state.
Z3_solver_cube()
Z3_ast_vector Z3_API Z3_solver_cube (Z3_context c, Z3_solver s, Z3_ast_vector vars, unsigned backtrack_level)
extract a next cube for a solver. The last cube is the constant true or false. The number of (non-constant) cubes is by default 1. For the sat solver cubing is controlled using parameters sat.lookahead.cube.cutoff and sat.lookahead.cube.fraction.
The third argument is a vector of variables that may be used for cubing. The contents of the vector is only used in the first call. The initial list of variables is used in subsequent calls until it returns the unsatisfiable cube. The vector is modified to contain a set of Autarky variables that occur in clauses that are affected by the (last literal in the) cube. These variables could be used by a different cuber (on a different solver object) for further recursive cubing.
The last argument is a backtracking level. It instructs the cube process to backtrack below the indicated level for the next cube.
Referenced by solver::cube().
Z3_solver_dec_ref()
void Z3_API Z3_solver_dec_ref (Z3_context c, Z3_solver s)
Decrement the reference counter of the given solver.
Referenced by Solver::__del__(), solver::operator=(), and solver::~solver().
Z3_solver_from_file()
void Z3_API Z3_solver_from_file (Z3_context c, Z3_solver s, Z3_string file_name)
load solver assertions from a file.
See also
Z3_solver_from_string
Z3_solver_to_string
Referenced by solver::from_file().
Z3_solver_from_string()
void Z3_API Z3_solver_from_string (Z3_context c, Z3_solver s, Z3_string str)
load solver assertions from a string.
See also
Z3_solver_from_file
Z3_solver_to_string
Referenced by solver::from_string().
Z3_solver_get_assertions()
Z3_ast_vector Z3_API Z3_solver_get_assertions (Z3_context c, Z3_solver s)
Return the set of asserted formulas on the solver.
Referenced by solver::assertions().
Z3_solver_get_consequences()
Z3_lbool Z3_API Z3_solver_get_consequences (Z3_context c, Z3_solver s, Z3_ast_vector assumptions, Z3_ast_vector variables, Z3_ast_vector consequences)
retrieve consequences from solver that determine values of the supplied function symbols.
Referenced by solver::consequences().
Z3_solver_get_help()
Z3_string Z3_API Z3_solver_get_help (Z3_context c, Z3_solver s)
Return a string describing all solver available parameters.
See also
Z3_solver_get_param_descrs
Z3_solver_set_params
Z3_solver_get_levels()
void Z3_API Z3_solver_get_levels (Z3_context c, Z3_solver s, Z3_ast_vector literals, unsigned sz, unsigned levels[])
retrieve the decision depth of Boolean literals (variables or their negations). Assumes a check-sat call and no other calls (to extract models) have been invoked.
Referenced by solver::trail().
Z3_solver_get_model()
Z3_model Z3_API Z3_solver_get_model (Z3_context c, Z3_solver s)
Retrieve the model for the last Z3_solver_check or Z3_solver_check_assumptions.
The error handler is invoked if a model is not available because the commands above were not invoked for the given solver, or if the result was Z3_L_FALSE.
Referenced by solver::get_model(), and Solver::model().
Z3_solver_get_non_units()
Z3_ast_vector Z3_API Z3_solver_get_non_units (Z3_context c, Z3_solver s)
Return the set of non units in the solver state.
Referenced by solver::non_units().
Z3_solver_get_num_scopes()
unsigned Z3_API Z3_solver_get_num_scopes (Z3_context c, Z3_solver s)
Return the number of backtracking points.
See also
Z3_solver_push
Z3_solver_pop
Referenced by Solver::num_scopes().
Z3_solver_get_param_descrs()
Z3_param_descrs Z3_API Z3_solver_get_param_descrs (Z3_context c, Z3_solver s)
Return the parameter description set for the given solver object.
See also
Z3_solver_get_help
Z3_solver_set_params
Referenced by solver::get_param_descrs().
Z3_solver_get_proof()
Z3_ast Z3_API Z3_solver_get_proof (Z3_context c, Z3_solver s)
Retrieve the proof for the last Z3_solver_check or Z3_solver_check_assumptions.
The error handler is invoked if proof generation is not enabled, or if the commands above were not invoked for the given solver, or if the result was different from Z3_L_FALSE.
Referenced by solver::proof().
Z3_solver_get_reason_unknown()
Z3_string Z3_API Z3_solver_get_reason_unknown (Z3_context c, Z3_solver s)
Return a brief justification for an "unknown" result (i.e., Z3_L_UNDEF) for the commands Z3_solver_check and Z3_solver_check_assumptions.
Referenced by solver::reason_unknown().
Z3_solver_get_statistics()
Z3_stats Z3_API Z3_solver_get_statistics (Z3_context c, Z3_solver s)
Return statistics for the given solver.
Remarks
User must use Z3_stats_inc_ref and Z3_stats_dec_ref to manage Z3_stats objects.
Referenced by solver::statistics().
Z3_solver_get_trail()
Z3_ast_vector Z3_API Z3_solver_get_trail (Z3_context c, Z3_solver s)
Return the trail modulo model conversion, in order of decision level The decision level can be retrieved using Z3_solver_get_level based on the trail.
Referenced by solver::trail(), and solver::trail().
Z3_solver_get_units()
Z3_ast_vector Z3_API Z3_solver_get_units (Z3_context c, Z3_solver s)
Return the set of units modulo model conversion.
Referenced by solver::units().
Z3_solver_get_unsat_core()
Z3_ast_vector Z3_API Z3_solver_get_unsat_core (Z3_context c, Z3_solver s)
Retrieve the unsat core for the last Z3_solver_check_assumptions The unsat core is a subset of the assumptions a.
By default, the unsat core will not be minimized. Generation of a minimized unsat core can be enabled via the "sat.core.minimize" and "smt.core.minimize" settings for SAT and SMT cores respectively. Generation of minimized unsat cores will be more expensive.
Referenced by solver::unsat_core().
Z3_solver_import_model_converter()
void Z3_API Z3_solver_import_model_converter (Z3_context ctx, Z3_solver src, Z3_solver dst)
Ad-hoc method for importing model conversion from solver.
This method is used for scenarios where src has been used to solve a set of formulas and was interrupted. The dst solver may be a strengthening of src obtained from cubing (assigning a subset of literals or adding constraints over the assertions available in src). If dst ends up being satisfiable, the model for dst may not correspond to a model of the original formula due to inprocessing in src. This method is used to take the side-effect of inprocessing into account when returning a model for dst.
Z3_solver_inc_ref()
void Z3_API Z3_solver_inc_ref (Z3_context c, Z3_solver s)
Increment the reference counter of the given solver.
Referenced by solver::operator=().
Z3_solver_interrupt()
void Z3_API Z3_solver_interrupt (Z3_context c, Z3_solver s)
Solver local interrupt. Normally you should use Z3_interrupt to cancel solvers because only one solver is enabled concurrently per context. However, per GitHub issue #1006, there are use cases where it is more convenient to cancel a specific solver. Solvers that are not selected for interrupts are left alone.
Z3_solver_next_split()
bool Z3_API Z3_solver_next_split (Z3_context c, Z3_solver_callback cb, Z3_ast t, unsigned idx, Z3_lbool phase)
Sets the next (registered) expression to split on. The function returns false and ignores the given expression in case the expression is already assigned internally (due to relevancy propagation, this assignments might not have been reported yet by the fixed callback). In case the function is called in the decide callback, it overrides the currently selected variable and phase.
Referenced by user_propagator_base::next_split().
Z3_solver_pop()
void Z3_API Z3_solver_pop (Z3_context c, Z3_solver s, unsigned n)
Backtrack n backtracking points.
See also
Z3_solver_get_num_scopes
Z3_solver_push
Precondition
n <= Z3_solver_get_num_scopes(c, s)
Referenced by Solver::pop(), and solver::pop().
Z3_solver_propagate_consequence()
bool Z3_API Z3_solver_propagate_consequence (Z3_context c, Z3_solver_callback cb, unsigned num_fixed, Z3_ast const * fixed, unsigned num_eqs, Z3_ast const * eq_lhs, Z3_ast const * eq_rhs, Z3_ast conseq)
propagate a consequence based on fixed values and equalities.
A client may invoke it during the propagate_fixed, propagate_eq, propagate_diseq, and propagate_final callbacks. The callback adds a propagation consequence based on the fixed values passed ids and equalities eqs based on parameters lhs, rhs.
The solver might discard the propagation in case it is true in the current state. The function returns false in this case; otw. the function returns true. At least one propagation in the final callback has to return true in order to prevent the solver from finishing.
Assume the callback has the signature: propagate_consequence_eh(context, solver_cb, num_ids, ids, num_eqs, lhs, rhs, consequence).
Parameters
c - context
solver_cb - solver callback
num_ids - number of fixed terms used as premise to propagation
ids - array of length num_ids containing terms that are fixed in the current scope
num_eqs - number of equalities used as premise to propagation
lhs - left side of equalities
rhs - right side of equalities
consequence - consequence to propagate. It is typically an atomic formula, but it can be an arbitrary formula.
Referenced by user_propagator_base::conflict(), user_propagator_base::conflict(), user_propagator_base::propagate(), and user_propagator_base::propagate().
Z3_solver_propagate_created()
void Z3_API Z3_solver_propagate_created (Z3_context c, Z3_solver s, Z3_created_eh created_eh)
register a callback when a new expression with a registered function is used by the solver The registered function appears at the top level and is created using Z3_solver_propagate_declare.
Referenced by user_propagator_base::register_created(), and user_propagator_base::register_created().
Z3_solver_propagate_decide()
void Z3_API Z3_solver_propagate_decide (Z3_context c, Z3_solver s, Z3_decide_eh decide_eh)
register a callback when the solver decides to split on a registered expression. The callback may change the arguments by providing other values by calling Z3_solver_next_split
Referenced by user_propagator_base::register_decide(), and user_propagator_base::register_decide().
Z3_solver_propagate_declare()
Z3_func_decl Z3_API Z3_solver_propagate_declare (Z3_context c, Z3_symbol name, unsigned n, Z3_sort * domain, Z3_sort range)
Create uninterpreted function declaration for the user propagator. When expressions using the function are created by the solver invoke a callback to Z3_solver_propagate_created with arguments
context and callback solve
declared_expr: expression using function that was used as the top-level symbol
declared_id: a unique identifier (unique within the current scope) to track the expression.
Referenced by context::user_propagate_function().
Z3_solver_propagate_diseq()
void Z3_API Z3_solver_propagate_diseq (Z3_context c, Z3_solver s, Z3_eq_eh eq_eh)
register a callback on expression dis-equalities.
Z3_solver_propagate_eq()
void Z3_API Z3_solver_propagate_eq (Z3_context c, Z3_solver s, Z3_eq_eh eq_eh)
register a callback on expression equalities.
Referenced by user_propagator_base::register_eq(), and user_propagator_base::register_eq().
Z3_solver_propagate_final()
void Z3_API Z3_solver_propagate_final (Z3_context c, Z3_solver s, Z3_final_eh final_eh)
register a callback on final check. This provides freedom to the propagator to delay actions or implement a branch-and bound solver. The final check is invoked when all decision variables have been assigned by the solver.
The final_eh callback takes as argument the original user_context that was used when calling Z3_solver_propagate_init, and it takes a callback context with the opaque type Z3_solver_callback. The callback context is passed as argument to invoke the Z3_solver_propagate_consequence function. The callback context can only be accessed (for propagation and for dynamically registering expressions) within a callback. If the callback context gets used for propagation or conflicts, those propagations take effect and may trigger new decision variables to be set.
Referenced by user_propagator_base::register_final(), and user_propagator_base::register_final().
Z3_solver_propagate_fixed()
void Z3_API Z3_solver_propagate_fixed (Z3_context c, Z3_solver s, Z3_fixed_eh fixed_eh)
register a callback for when an expression is bound to a fixed value. The supported expression types are
Booleans
Bit-vectors
Referenced by user_propagator_base::register_fixed(), and user_propagator_base::register_fixed().
Z3_solver_propagate_init()
void Z3_API Z3_solver_propagate_init (Z3_context c, Z3_solver s, void * user_context, Z3_push_eh push_eh, Z3_pop_eh pop_eh, Z3_fresh_eh fresh_eh)
register a user-propagator with the solver.
Parameters
c - context.
s - solver object.
user_context - a context used to maintain state for callbacks.
push_eh - a callback invoked when scopes are pushed
pop_eh - a callback invoked when scopes are popped
fresh_eh - a solver may spawn new solvers internally. This callback is used to produce a fresh user_context to be associated with fresh solvers.
Referenced by user_propagator_base::user_propagator_base().
Z3_solver_propagate_on_binding()
void Z3_API Z3_solver_propagate_on_binding (Z3_context c, Z3_solver s, Z3_on_binding_eh on_binding_eh)
register a callback when the solver instantiates a quantifier. If the callback returns false, the actual instantiation of the quantifier is blocked. This allows the user propagator selectively prioritize instantiations without relying on default or configured weights.
Referenced by user_propagator_base::register_on_binding().
Z3_solver_propagate_register()
void Z3_API Z3_solver_propagate_register (Z3_context c, Z3_solver s, Z3_ast e)
register an expression to propagate on with the solver. Only expressions of type Bool and type Bit-Vector can be registered for propagation.
Referenced by user_propagator_base::add().
Z3_solver_propagate_register_cb()
void Z3_API Z3_solver_propagate_register_cb (Z3_context c, Z3_solver_callback cb, Z3_ast e)
register an expression to propagate on with the solver. Only expressions of type Bool and type Bit-Vector can be registered for propagation. Unlike Z3_solver_propagate_register, this function takes a solver callback context as argument. It can be invoked during a callback to register new expressions.
Referenced by user_propagator_base::add().
Z3_solver_push()
void Z3_API Z3_solver_push (Z3_context c, Z3_solver s)
Create a backtracking point.
The solver contains a stack of assertions.
See also
Z3_solver_get_num_scopes
Z3_solver_pop
Referenced by solver::push(), and Solver::push().
Z3_solver_register_on_clause()
void Z3_API Z3_solver_register_on_clause (Z3_context c, Z3_solver s, void * user_context, Z3_on_clause_eh on_clause_eh)
register a callback to that retrieves assumed, inferred and deleted clauses during search.
Parameters
c - context.
s - solver object.
user_context - a context used to maintain state for callbacks.
on_clause_eh - a callback that is invoked by when a clause is
asserted to the CDCL engine (corresponding to an input clause after pre-processing)
inferred by CDCL(T) using either a SAT or theory conflict/propagation
deleted by the CDCL(T) engine
Referenced by on_clause::on_clause().
Z3_solver_reset()
void Z3_API Z3_solver_reset (Z3_context c, Z3_solver s)
Remove all assertions from the solver.
See also
Z3_solver_assert
Z3_solver_assert_and_track
Referenced by solver::reset(), and Solver::reset().
Z3_solver_set_initial_value()
void Z3_API Z3_solver_set_initial_value (Z3_context c, Z3_solver s, Z3_ast v, Z3_ast val)
provide an initialization hint to the solver. The initialization hint is used to calibrate an initial value of the expression that represents a variable. If the variable is Boolean, the initial phase is set according to value. If the variable is an integer or real, the initial Simplex tableau is recalibrated to attempt to follow the value assignment.
Referenced by solver::set_initial_value().
Z3_solver_set_params()
void Z3_API Z3_solver_set_params (Z3_context c, Z3_solver s, Z3_params p)
Set the given solver using the given parameters.
See also
Z3_solver_get_help
Z3_solver_get_param_descrs
Referenced by solver::set(), and Solver::set().
Z3_solver_solve_for()
void Z3_API Z3_solver_solve_for (Z3_context c, Z3_solver s, Z3_ast_vector variables, Z3_ast_vector terms, Z3_ast_vector guards)
retrieve a 'solution' for variables as defined by equalities in maintained by solvers. At this point, only linear solution are supported. The solution to variables may be presented in triangular form, such that variables used in solutions themselves have solutions.
Z3_solver_to_dimacs_string()
Z3_string Z3_API Z3_solver_to_dimacs_string (Z3_context c, Z3_solver s, bool include_names)
Convert a solver into a DIMACS formatted string.
See also
Z3_goal_to_diamcs_string for requirements.
Referenced by solver::dimacs().
Z3_solver_to_string()
Z3_string Z3_API Z3_solver_to_string (Z3_context c, Z3_solver s)
Convert a solver into a string.
See also
Z3_solver_from_file
Z3_solver_from_string
Z3_solver_translate()
Z3_solver Z3_API Z3_solver_translate (Z3_context source, Z3_solver s, Z3_context target)
Copy a solver s from the context source to the context target.
Referenced by solver::solver().
Z3_sort_to_ast()
Z3_ast Z3_API Z3_sort_to_ast (Z3_context c, Z3_sort s)
Convert a Z3_sort into Z3_ast. This is just type casting.
Z3_sort_to_string()
Z3_string Z3_API Z3_sort_to_string (Z3_context c, Z3_sort s)
Z3_stats_dec_ref()
void Z3_API Z3_stats_dec_ref (Z3_context c, Z3_stats s)
Decrement the reference counter of the given statistics object.
Referenced by Statistics::__del__(), stats::operator=(), and stats::~stats().
Z3_stats_get_double_value()
double Z3_API Z3_stats_get_double_value (Z3_context c, Z3_stats s, unsigned idx)
Return the double value of the given statistical data.
Precondition
idx < Z3_stats_size(c, s) && Z3_stats_is_double(c, s)
Referenced by Statistics::__getitem__(), stats::double_value(), and Statistics::get_key_value().
Z3_stats_get_key()
Z3_string Z3_API Z3_stats_get_key (Z3_context c, Z3_stats s, unsigned idx)
Return the key (a string) for a particular statistical data.
Precondition
idx < Z3_stats_size(c, s)
Referenced by Statistics::__getitem__(), Statistics::get_key_value(), stats::key(), and Statistics::keys().
Z3_stats_get_uint_value()
unsigned Z3_API Z3_stats_get_uint_value (Z3_context c, Z3_stats s, unsigned idx)
Return the unsigned value of the given statistical data.
Precondition
idx < Z3_stats_size(c, s) && Z3_stats_is_uint(c, s)
Referenced by Statistics::__getitem__(), Statistics::get_key_value(), and stats::uint_value().
Z3_stats_inc_ref()
void Z3_API Z3_stats_inc_ref (Z3_context c, Z3_stats s)
Increment the reference counter of the given statistics object.
Referenced by stats::operator=().
Z3_stats_is_double()
bool Z3_API Z3_stats_is_double (Z3_context c, Z3_stats s, unsigned idx)
Return true if the given statistical data is a double.
Precondition
idx < Z3_stats_size(c, s)
Referenced by stats::is_double().
Z3_stats_is_uint()
bool Z3_API Z3_stats_is_uint (Z3_context c, Z3_stats s, unsigned idx)
Return true if the given statistical data is a unsigned integer.
Precondition
idx < Z3_stats_size(c, s)
Referenced by Statistics::__getitem__(), Statistics::get_key_value(), and stats::is_uint().
Z3_stats_size()
unsigned Z3_API Z3_stats_size (Z3_context c, Z3_stats s)
Return the number of statistical data in s.
Referenced by Statistics::__len__(), and stats::size().
Z3_stats_to_string()
Z3_string Z3_API Z3_stats_to_string (Z3_context c, Z3_stats s)
Convert a statistics into a string.
Referenced by Statistics::__repr__().
Z3_substitute()
Z3_ast Z3_API Z3_substitute (Z3_context c, Z3_ast a, unsigned num_exprs, Z3_ast const from[], Z3_ast const to[])
Substitute every occurrence of from[i] in a with to[i], for i smaller than num_exprs. The result is the new AST. The arrays from and to must have size num_exprs. For every i smaller than num_exprs, we must have that sort of from[i] must be equal to sort of to[i].
Referenced by expr::substitute().
Z3_substitute_funs()
Z3_ast Z3_API Z3_substitute_funs (Z3_context c, Z3_ast a, unsigned num_funs, Z3_func_decl const from[], Z3_ast const to[])
Substitute functions in from with new expressions in to.
The expressions in to can have free variables. The free variable in to at index 0 refers to the first argument of from, the free variable at index 1 corresponds to the second argument.
Referenced by expr::substitute().
Z3_substitute_vars()
Z3_ast Z3_API Z3_substitute_vars (Z3_context c, Z3_ast a, unsigned num_exprs, Z3_ast const to[])
Substitute the variables in a with the expressions in to. For every i smaller than num_exprs, the variable with de-Bruijn index i is replaced with term to[i]. Note that a variable is created using the function Z3_mk_bound.
Referenced by expr::substitute().
Z3_tactic_and_then()
Z3_tactic Z3_API Z3_tactic_and_then (Z3_context c, Z3_tactic t1, Z3_tactic t2)
Return a tactic that applies t1 to a given goal and t2 to every subgoal produced by t1.
Z3_tactic_apply()
Z3_apply_result Z3_API Z3_tactic_apply (Z3_context c, Z3_tactic t, Z3_goal g)
Apply tactic t to the goal g.
See also
Z3_tactic_apply_ex
Referenced by tactic::apply().
Z3_tactic_apply_ex()
Z3_apply_result Z3_API Z3_tactic_apply_ex (Z3_context c, Z3_tactic t, Z3_goal g, Z3_params p)
Apply tactic t to the goal g using the parameter set p.
See also
Z3_tactic_apply
Z3_tactic_cond()
Z3_tactic Z3_API Z3_tactic_cond (Z3_context c, Z3_probe p, Z3_tactic t1, Z3_tactic t2)
Return a tactic that applies t1 to a given goal if the probe p evaluates to true, and t2 if p evaluates to false.
Referenced by z3::cond().
Z3_tactic_dec_ref()
void Z3_API Z3_tactic_dec_ref (Z3_context c, Z3_tactic g)
Decrement the reference counter of the given tactic.
Referenced by tactic::operator=(), and tactic::~tactic().
Z3_tactic_fail()
Z3_tactic Z3_API Z3_tactic_fail (Z3_context c)
Return a tactic that always fails.
Z3_tactic_fail_if()
Z3_tactic Z3_API Z3_tactic_fail_if (Z3_context c, Z3_probe p)
Return a tactic that fails if the probe p evaluates to false.
Referenced by z3::fail_if().
Z3_tactic_fail_if_not_decided()
Z3_tactic Z3_API Z3_tactic_fail_if_not_decided (Z3_context c)
Return a tactic that fails if the goal is not trivially satisfiable (i.e., empty) or trivially unsatisfiable (i.e., contains false).
Z3_tactic_get_descr()
Z3_string Z3_API Z3_tactic_get_descr (Z3_context c, Z3_string name)
Return a string containing a description of the tactic with the given name.
Z3_tactic_get_help()
Z3_string Z3_API Z3_tactic_get_help (Z3_context c, Z3_tactic t)
Return a string containing a description of parameters accepted by the given tactic.
Referenced by tactic::help().
Z3_tactic_get_param_descrs()
Z3_param_descrs Z3_API Z3_tactic_get_param_descrs (Z3_context c, Z3_tactic t)
Return the parameter description set for the given tactic object.
Referenced by tactic::get_param_descrs().
Z3_tactic_inc_ref()
void Z3_API Z3_tactic_inc_ref (Z3_context c, Z3_tactic t)
Increment the reference counter of the given tactic.
Referenced by tactic::operator=().
Z3_tactic_or_else()
Z3_tactic Z3_API Z3_tactic_or_else (Z3_context c, Z3_tactic t1, Z3_tactic t2)
Return a tactic that first applies t1 to a given goal, if it fails then returns the result of t2 applied to the given goal.
Z3_tactic_par_and_then()
Z3_tactic Z3_API Z3_tactic_par_and_then (Z3_context c, Z3_tactic t1, Z3_tactic t2)
Return a tactic that applies t1 to a given goal and then t2 to every subgoal produced by t1. The subgoals are processed in parallel.
Z3_tactic_par_or()
Z3_tactic Z3_API Z3_tactic_par_or (Z3_context c, unsigned num, Z3_tactic const ts[])
Return a tactic that applies the given tactics in parallel.
Z3_tactic_repeat()
Z3_tactic Z3_API Z3_tactic_repeat (Z3_context c, Z3_tactic t, unsigned max)
Return a tactic that keeps applying t until the goal is not modified anymore or the maximum number of iterations max is reached.
Z3_tactic_skip()
Z3_tactic Z3_API Z3_tactic_skip (Z3_context c)
Return a tactic that just return the given goal.
Z3_tactic_try_for()
Z3_tactic Z3_API Z3_tactic_try_for (Z3_context c, Z3_tactic t, unsigned ms)
Return a tactic that applies t to a given goal for ms milliseconds. If t does not terminate in ms milliseconds, then it fails.
Z3_tactic_using_params()
Z3_tactic Z3_API Z3_tactic_using_params (Z3_context c, Z3_tactic t, Z3_params p)
Return a tactic that applies t using the given set of parameters.
Z3_tactic_when()
Z3_tactic Z3_API Z3_tactic_when (Z3_context c, Z3_probe p, Z3_tactic t)
Return a tactic that applies t to a given goal is the probe p evaluates to true. If p evaluates to false, then the new tactic behaves like the skip tactic.
Referenced by z3::when().
Z3_to_app()
Z3_app Z3_API Z3_to_app (Z3_context c, Z3_ast a)
Convert an ast into an APP_AST. This is just type casting.
Precondition
Z3_get_ast_kind(c, a) == \c Z3_APP_AST
Z3_to_func_decl()
Z3_func_decl Z3_API Z3_to_func_decl (Z3_context c, Z3_ast a)
Convert an AST into a FUNC_DECL_AST. This is just type casting.
Precondition
Z3_get_ast_kind(c, a) == Z3_FUNC_DECL_AST
Referenced by z3py::get_map_func().
Z3_toggle_warning_messages()
void Z3_API Z3_toggle_warning_messages (bool enabled)
Enable/disable printing warning messages to the console.
Warnings are printed after passing true, warning messages are suppressed after calling this method with false.
Z3_translate()
Z3_ast Z3_API Z3_translate (Z3_context source, Z3_ast a, Z3_context target)
Translate/Copy the AST a from context source to context target. AST a must have been created using context source.
Precondition
source != target
Referenced by AstRef::translate().
Z3_update_param_value()
void Z3_API Z3_update_param_value (Z3_context c, Z3_string param_id, Z3_string param_value)
Set a value of a context parameter.
See also
Z3_global_param_set
Referenced by context::set(), context::set(), and context::set().
Z3_update_term()
Z3_ast Z3_API Z3_update_term (Z3_context c, Z3_ast a, unsigned num_args, Z3_ast const args[])
Update the arguments of term a using the arguments args. The number of arguments num_args should coincide with the number of arguments to a. If a is a quantifier, then num_args has to be 1.